$ $XConsortium: libABobjXm.msg /main/3 1995/11/06 18:43:44 rswiston $
$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.5 24 Apr 1995 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "WARNING: %s : could not convert filename[%s] to pixmap\n"
2 "WARNING: %s : No glyph filename specified\n"
3 "ERROR: %s: NULL Object attachment\n"
4 "Instantiation ERROR: %s: widget-ID for parent is NULL\n"
5 "Instantiation ERROR: %s: could not instantiate menu\n"
6 "Instantiation ERROR: Object must have a valid name\n"
7 "Instantiation ERROR: %s: Object must have widget class\n"
8 "INTERNAL ERROR: salient counts don't match.\n"
9 "ERROR: objxm_comp_get_subobj - object not xmconfigured: %s\n"
10 "Folders"
11 "Filter"
12 "Enter Filename"
13 "Update"
14 "Warning: %s :\n"
15 "Graphic File base '%s'\ncould not be converted to a Pixmap because\n"
16 "File base is an empty string."
17 "None of the following files could be converted to a Pixmap:\n"
18 "filenames too long to display\n"
19 "%s.pm\n%s.xpm\n%s.bm\n%s.xbm\n"
20 "The graphic file name specified could not be converted\ninto a pixmap. App Builder searches for a file of the\nform Filename.pm, Filename.xpm, Filename.bm, and\nFilename.xbm.\n\nEither none of those files exists in the directory specified\n(via the Graphic Filename field or if no path was specified,\nthen the current working directory), or a file exists but may\nbe corrupt."
21 "WARNING: Object '%s'\nCould not allocate Background color \"%s\".\nObject's Background will default to white."
22 "WARNING: Object '%s'\nCould not allocate Foreground color \"%s\".\nObject's Foreground will default to black."
