$ $XConsortium: AddLibraryAgent.msg /main/8 1996/09/20 13:56:09 cde-hal $

$set	Set_AddLibraryAgent
$ 
$ messages specific to add information library dialog
$ Note: "Infolib" is a CDE glossary term.
$ 

1	"Dtinfo: Add Document Library"

$ 2     "Please enter an absolute path to the Infolib."
$       (Path must exist and include "/".)
2	"Please enter an absolute path to the Infolib."

$ 3     "Infolib open failed. Check the path specified."
$	(Path passed basic format check, but could not open target found.) 
3	"Infolib open failed. Check the path specified."

$ 4     "Infolib open failed. Check entry syntax or Infolib integrity."
$       (An unidentified error occurred on attempt to open.)
4	"Infolib open failed. Check entry syntax or Infolib integrity."

$ 5     "Infolib specification format error."
5	"Infolib specification format error."

$ 6     "No Infolib specified."
6	"No Infolib specified."

$ 7     "No Infolib found or specified."
7	"No Infolib found or specified."

$ 10	"Dtinfo: Infolib Selection"
$	(For title to the File Selection Dialog)
10	"Dtinfo: Infolib Selection"

$ 11	"No Infolibs Present"
$	(This string will be shown in a directory listing where there
$	 are no Infolibs found in the directory.)
11	"No Infolibs Present"

