$ $XConsortium: GraphicAgent.msg /main/4 1996/10/25 15:09:30 cde-hal $

$set	Set_GraphicAgent
$ 
$ messages specific to detached graphic window
$ 
1	"Dtinfo: Detached Graphic"
2	"Detached Graphic"
3	"Raster illustration (non-scalable)"
4	"Vector illustration (scalable)"
5	"Scaling illustration, please wait..."
$ 
$ Dtinfo*SetZoom
$ 
6	"Enter the new scaling percentage:"
$ 
$ Dtinfo*SetZoomTitle
$ 
7	"Dtinfo: Set Scale"
$ 
8	"Dtinfo: "
9	"Raster illustration (scalable)"
