$ $XConsortium: MessageAgent.msg /main/4 1996/08/16 17:07:57 cde-hal $

$set	Set_MessageAgent
$ 
$ messages specific to message dialogs
$ 

$ Dtinfo*ErrorDialogTitle
$ 
1	"Dtinfo: Error"

$ Dtinfo*WarningDialogTitle
$ 
2	"Dtinfo: Warning"

$ Dtinfo*InfoDialogTitle
$ 
3	"Dtinfo: Information"

$ Dtinfo*ProgressDialogTitle
$ 
$	4	"Progress" is a level of completion in regards
$		 to a task.
4	"Dtinfo: Progress"

$ Dtinfo*QuitDialogTitle
$ 
5	"Dtinfo: Confirm Quit"

$ Dtinfo*QuestionDialogTitle
$ 
6	"Dtinfo: Question"
$ 
7	"Dtinfo: File a Bug"

