$ $XConsortium: NodeWindowAgent.msg /main/7 1996/11/06 16:38:20 cde-hal $

$set	Set_NodeWindowAgent
$ 
$ messages specific to browser window
$ 
1	"Dtinfo: Browser"
2	"To preview a link destination, click and hold on the link."
3	"Information Library"

$	4	"The locator for this section is %s"
$	This message is the result of the "Show Locator" operation.
4	"The locator for this section is %s"
$ 
$ line-break rules (reserved)
$ 
5	""
6	""
$ 
$ selected range of text consists only of run-time inserted text,
$ hence cannot create bookmark with it.
$ 
7	"The selected text is dynamically inserted and cannot\n\
be used alone to create a bookmark reference.\n\
Either select other text near the point, or include more\n\
of the surrounding text."

