$ $TOG: PrintPanelAgent.msg /main/7 1997/08/01 15:14:54 samborn $

$set	Set_PrintPanelAgent
$ 
$ messages specific to printing
$ 
1	"Dtinfo: Print"
$          Messages 2 - 5 are obsolete, and have been replaced by 12
2	No Print Dialog Manager can be found in the environment
3	Cannot start the Print Dialog Manager
4	Print Dialog Manager is not authorized to connect to Video display
5	Print Dialog Manager is not authorized to connect to Print display
6	Unable to display the Print Dialog Manager
7	Unable to copy default print data
8	Error printing to file
9	Print to file completed
10	Dtinfo: Print Status
11	Print Job Failed.\n\nThe X Print Server is Temporarily Out of Resources
$       Message 12 is used to handle errors from the PDM
12	Print Dialog Manager (PDM) error - setup failed.
