$ $XConsortium: UrlAgent.msg /main/5 1996/07/24 18:21:16 drk $

$set	Set_UrlAgent
$ 
$ messages specific to open locator dialog, and locator
$ input formats in general.
$ 
$ 1	"Dtinfo: Open Locator"
1	"Dtinfo: Open Locator"

$ 2     "Locator specification format error."
2	"Locator specification format error."

$ 3     "Locator resolution failed."
3       "Locator resolution failed."

$ 4     "Locator resolution failed within the loaded infolibs."
4	"Locator resolution failed within the loaded infolibs."

$ 5     "Document not found."
5	"Document not found."

$ 6     "No locator value provided."
6	"No locator value provided."

