$ $XConsortium: Mrm.msg /main/3 1996/10/19 14:28:48 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 
$ (c) Copyright 1996 Digital Equipment Corporation.
$ (c) Copyright 1996 Hewlett-Packard Company.
$ (c) Copyright 1996 International Business Machines Corp.
$ (c) Copyright 1996 Sun Microsystems, Inc.
$ (c) Copyright 1996 Novell, Inc. 
$ (c) Copyright 1996 FUJITSU LIMITED.
$ (c) Copyright 1996 Hitachi.
$ 

$ This message catalog contains messages issued by Motif Mrm library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.

$quote "

$set MS_Mrm

MSG__0000 "Vektorzuteilung fehlgeschlagen."

MSG__0001 "Pufferzuteilung fehlgeschlagen."

MSG__0002 "Ungültiger Puffer"

MSG__0003 "\"Block holen\" fehlgeschlagen."

MSG__0004 "\"Block ablegen\" fehlgeschlagen."

MSG__0005 "Ungültiger Datensatzumschlag"

MSG__0006 "Ungültiger Kontext"

MSG__0007 "Ungültige Dateneingabe"

MSG__0008 "Ungültige Segmenteingabe"

MSG__0009 "Unbekannter Dateneingabetyp"

MSG__0010 "Unerwarteter Datensatztyp"

MSG__0011 "Die Dateiversion %s ist größer als die Mrm-Version %s."

MSG__0012 "Dies ist nicht der Umschlag-Datensatz."

MSG__0013 "Ressourcenindex außerhalb des Bereichs"

MSG__0014 "NULL-Datenzeiger"

MSG__0015 "Ungültiger Überlauf-Datensatz"

MSG__0016 "GT-Datensatz stimmt nicht überein."

MSG__0017 "LT-Datensatz stimmt nicht überein."

MSG__0018 "Unerwarteter übergeordneter Datensatztyp"

MSG__0019 "Datensatz geht über EOF hinaus."

MSG__0020 "Kann Datensatz #%d Typ %d nicht austauschen."

MSG__0021 "Nicht implementierten Typ %d im Funktionsaufruf für Element %d angetroffen."

MSG__0022 "Nicht implementierten Argumenttyp %d angetroffen."

MSG__0023 "NULL-Hierarchie-ID"

MSG__0024 "Ungültige Hierarchie"

MSG__0025 "Ungültiges Schnittstellenmodul"

MSG__0026 "Ungültiger Widget-Datensatz"

MSG__0027 "Kontextzuteilung fehlgeschlagen."

MSG__0028 "Gültigkeitsprüfung fehlgeschlagen."

MSG__0029 "Ressource zu groß."

MSG__0030 "Anzeige noch nicht geöffnet."

MSG__0031 "Konnte Datei %s nicht öffnen."

MSG__0032 "Konnte Datei %s nicht öffnen - UID-Dateiversion stimmt nicht überein."

MSG__0033 "XmGetPixmap mit XmUNSPECIFIED_PIXMAP für %s fehlgeschlagen."

MSG__0034 "XCreateImage während IconImage-Umwandlung fehlgeschlagen."

MSG__0035 "XCreatePixmap während IconImage-Umwandlung fehlgeschlagen."

MSG__0036 "XCreateGC während IconImage-Umwandlung fehlgeschlagen."

MSG__0037 "XtMalloc während IconImage-Umwandlung fehlgeschlagen."

MSG__0038 "Konnte Farbe '%s' nicht laden."

MSG__0039 "Konnte RGB Farbe/Pixel '%d,%d,%d' nicht umwandeln."

MSG__0040 "Ungültiger Farbdeskriptortyp"

MSG__0041 "Ungültiger Monochromstatus %d des Farbelements"

MSG__0042 "Kann Literal '%s' nicht finden."
$ literal in this context means a named value.

MSG__0043 "Ungültiger Ressourcenkontext"

MSG__0044 "Zu viele Widgets"

MSG__0045 "Oberster Index außerhalb der Grenzen"

MSG__0046 "Listenzuteilung fehlgeschlagen."

MSG__0047 "Listenvektorzuteilung fehlgeschlagen."

MSG__0048 "Vektorneuzuteilung fehlgeschlagen."

MSG__0049 "Zeichenfolgezuteilung fehlgeschlagen."

MSG__0050 "UID-Datei ist veraltet - hat keine Komprimierungstabelle."

MSG__0051 "Konnte Klassendeskriptor für Klasse %s nicht finden."

MSG__0052 "Kann indiziertes Widget '%s' nicht finden."

MSG__0053 "Kann RID-Widget '%x' nicht finden."

MSG__0054 "?? UNBEKANNTER Tastentyp %d"

MSG__0055 "Unbekannte Widget-Varietät"

MSG__0056 "Ungelöste Widget-Referenz im Funktionsaufruf für die Erstellung"

MSG__0057 "Konnte keine Funktionsaufrufe für die Erstellung herstellen."

MSG__0058 "Unbekannter untergeordneter Typ"

MSG__0059 "Untergeordnetes Element nicht gefunden."

MSG__0060 "Widget-Referenz nicht indiziert."

MSG__0061 "Konnte Farbe/Pixel '%s' nicht umwandeln."

MSG__0062 "Konnte Zeichenfolge-Code %d nicht entkomprimieren."

MSG__0063 "Nicht abgewickelte Ressourcengruppe"

MSG__0064 "Konnte ASCIZ '%s' nicht in zusammengesetzte Zeichenfolge umwandeln."

MSG__0065 "Konnte Übersetzungstabelle '%s' nicht analysieren."

MSG__0066 "Konnte Identifizierer '%s' nicht umwandeln."

MSG__0067 "Interner Fehler: MrmRtypeIconImage für Groß- und Kleinschreibung gefunden."

MSG__0068 "Interner Fehler: MrmRtypeXBitmapFile für Groß- und Kleinschreibung gefunden."

MSG__0069 " Interner Fehler: Konnte Anzeige nicht in Zeichenfolge umwandeln."

MSG__0070 "Konnte Schriftart '%s' nicht umwandeln."

MSG__0071 "Konnte fontset '%s' nicht umwandeln."
$ please do not translate fontset.

MSG__0072 "Konnte eine oder mehrere Schriftarten für fontset '%s' nicht öffnen."

MSG__0073 "Konnte fontlist-Schriftart '%s' nicht der Liste hinzufügen."

MSG__0074 " Konnte fontlist-Schriftart '%s' nicht der Liste hinzufügen "

MSG__0075 "Konnte Klassen-Datensatzname '%s' nicht umwandeln."

MSG__0076 "Konnte keysym-Zeichenfolge '%s' nicht in KeySym umwandeln."

MSG__0077 "Kann indizierten Literal '%s' nicht finden."

MSG__0078 "Kann RID-Literal '%x' nicht finden."

MSG__0079 "Unbekannter Literal-Tastentyp %d"

MSG__0080 "Ungültiger ColorTable-Literaltyp %d"

MSG__0081 "Ungültiger ColorTable-Typencode %d"

MSG__0082 "Ungültiger Farb-Literaltyp %d"

MSG__0083 "Ungültiger ColorItem-Typencode %d"

MSG__0084 "Funktionsaufruf-Routine '%s' nicht registriert."

MSG__0085 "Widget-Referenz nicht indiziert."

MSG__0086 "Kann indizierte Widget-Ressource '%s' nicht finden."

MSG__0087 "Kann RID-Widget-Ressource '%x' nicht finden."

MSG__0088 "Unbekannter Ressourcen-Tastentyp %d"

MSG__0089 "Konnte Widget-Baum not instantitate??."

MSG__0090 "Leerer benutzerdefinierter Klassenname"

MSG__0091 "Ungültiger Klassencode"

MSG__0092 "Zu viele Argumente"

MSG__0093 "Ungültiger Komprimierungscode"

MSG__0094 "Ungültiger oder nicht abgewickelter Typ"

MSG__0095 "Vektor zu groß."

MSG__0096 "Leerer Routinenname"

MSG__0097 "Char8Vector noch nicht implementiert."

MSG__0098 "CStringVector noch nicht implementiert."

MSG__0099 "Zu viele untergeordnete Elemente"

MSG__0100 "Leerer Listendeskriptor für untergeordnete Elemente"

MSG__0101 "Index für untergeordnete Elemente außerhalb der Grenzen."

MSG__0102 "Leerer Index"

MSG__0103 "Ungültiger Tastentyp"

MSG__0104 "Arg-Index außerhalb der Grenzen."

MSG__0105 "Ungültiger Widget/Gadget-Datensatz"

MSG__0106 "Ungültiger Funktionsaufruf-Deskriptor"

MSG__0107 "Funktionsaufruf-Elementindex außerhalb der Grenzen."

MSG__0108 "Konnte Zeichenfolge-Code %d nicht entkomprimieren."

MSG__0109 "Zu viele Elemente"

MSG__0110 "Konnte Mehrwort-Zeichenfolge nicht in Breitzeichen-Zeichenfolge umwandeln."

MSG__0111 "Konnte Integer '%d' nicht in Symbolbild umwandeln."

MSG__0112 "Konnte nicht in Symbolbild umwandeln."

MSG__0113 "Konnte Puffer nicht öffnen - UID-Version stimmt nicht überein."

MSG__0114 "Konnte Puffer nicht öffnen."

MSG__0115 "Kann Einheiten nicht in XmPIXELS umwandeln: fehlerhaftes Einheitenformat oder Typ."

MSG__0116 "Kann Einheiten nicht in XmPIXELS umwandeln: Fließkomma-Überlauf."

MSG__0117 "Ungültige Version-Zeichenfolge %s in UID-Datei. Kann Datei nicht lesen."

MSG__0118 "Mrm-Version %s ist größer als Dateiversion %s;\nbitte UIL-Datei neu kompilieren."

MSG__0119 "Objekt '%s' als PRIVATE erklärt."

