$ $XConsortium: Uil.msg /main/3 1996/10/19 14:28:51 rws $

$quote "

$set UIL_SET1


UIL_0 "Zweite Version \"%s\" wurde ignoriert."

UIL_1 "Unbekannte Option \"%s\" wurde ignoriert."

UIL_2 "Zusätzliche UIL-Quellendatei: %s wurde ignoriert."

UIL_3 "Fehler beim Öffnen der Quellendatei: %s"

UIL_4 "Fehler beim Lesen der nächsten Zeile der Quellendatei: %s"

UIL_5 "Interner Fehler: %s"

UIL_6 "Zeile nach %d Zeichen abgeschnitten."

UIL_7 "Wert von %s ist außerhalb des Bereichs %s."

UIL_8 "%s nicht abgeschlossene %s."

UIL_9 "Nicht druckbares Zeichen \\%d\\ ignoriert."

UIL_10 "Unbekannte Sequenz \"%s\" ignoriert."

UIL_11 "Unbekannte Escape-Sequenz \"\\%c\" - \\ ignoriert."

UIL_12 "Name überschreitet %d Zeichen - abgeschnitten auf: %s"

UIL_13 "Compiler hat keinen virtuellen Speicher mehr."

UIL_14 "Unerwartetes Token %s gefunden - die Analyse wird nach \"%c\" wiederaufgenommen."

UIL_15 "%s %s muß vor dieser Referenz definiert sein."

UIL_16 "Kontext erfordert die Angabe von %s - %s."

UIL_17 "%s wurde noch nicht implementiert."

UIL_18 "Wert %s gefunden, als Wert %s erwartet wurde."

UIL_19 "%s %s wird für das Objekt %s nicht unterstützt."

UIL_20 "Dies %s %s löst eine vorherige Definition in diesem %s %s ab."

UIL_21 "Der Name %s wurde zuvor als %s definiert."

UIL_22 "Der in diesem Kontext verwendete Wert muß privat sein."

UIL_23 "Die Prozedur %s wurde zuvor mit den Argumenten %d angegeben."

UIL_24 "Wert %s gefunden - das Argument der Prozedur %s muß der Wert %s sein."

UIL_25 "%s %s gefunden, als %s %s erwartet wurde."

UIL_26 "%s %s wurde noch nicht definiert."

UIL_27 "%s %s für dieses %s %s bereits angegeben."

UIL_28 "Element %s nicht in %s %s erlaubt."

UIL_29 "Kompilierung abgeschlossen - bitte vorherige Fehler beheben."

UIL_30 "Interner Fehler - bitte Fehlerreport vorlegen."

UIL_31 " "

UIL_32 "%s fehlt nach der Option \"%s\"."

UIL_33 "Fehler beim Öffnen der Listing-Datei: %s"

UIL_34 "Fehler beim Schreiben in die Listing-Datei: %s"

UIL_35 "Ungültige Modulstruktur- UIL-Modulsyntax überprüfen!"

UIL_36 "Zu viele Quellendateien geöffnet: %s"

UIL_37 "Quellenzeile enthält ein leeres Zeichen."

UIL_38 "Fehler: %d Warnungen: %d  Informationsmeldungen: %d"

UIL_39 "Fehler beim Öffnen der Datei UID: %s"

UIL_40 "Es wurde keine Datei UID produziert."

UIL_41 "Erstellungsprozedur wird nicht durch das Widget %s unterstützt."

UIL_42 "Erstellungsprozedur ist in einer %s Widget-Referenz nicht erlaubt."

UIL_43 "Erstellungsprozedur wird in einer %s Widget-Vereinbarung erfordert."

UIL_44 "Ein NULL-Zeichen wird in einer Zeichenfolge nicht unterstützt."

UIL_45 "Widget %s ist Teil einer kreisförmigen Definition."

UIL_46 "Keine Quellendatei angegeben."

UIL_47 "%s %s unterstützt nur ein einfaches %s %s."

UIL_48 "Widget %s unterstützt nur ein einzelnes Bedienelement."

UIL_49 "Unbekannter Zeichensatz"

UIL_50 "Namen-Aussage vor andere Modul-Aussagen stellen."

UIL_51 "Farbbuchstaben-Zeichenfolge muß ein einzelnes Zeichen sein."

UIL_52 "Farbbuchstabe wurde schon für vorherige Farbe in dieser Tabelle verwendet."

UIL_53 "Reihe %d muß dieselbe Breite wie Reihe 1 haben."

UIL_54 "Reihe %d, Zeile %d: Buchstabe \"%c\" nicht in Farbtabelle."

UIL_55 "Zu viele %ss in %s, die Grenze ist %d."

UIL_56 "Untergeordnete Kennzeichnung ist mit negierter Kennzeichnung nicht erlaubt."

UIL_57 "Gadget %s wird nicht unterstützt - stattdessen wird Widget %s benutzt."

UIL_58 "Typ %s ist nicht für %s gültig."

UIL_59 "Die Unterstützung für diesen Zeichensatz kann in einer zukünftigen Version entfernt werden."

UIL_60 "Die Grenze %s wird für %s %s nicht unterstützt."

UIL_61 "Zu viele \"%s\" Optionen, die Grenze ist %d."

UIL_62 "Fehler beim Schließen der Quellendatei: %s"

UIL_63 "Der Wert %s ist kreisförmig definiert."

UIL_64 "Mitgelieferter Name %s wird außer Kraft gesetzt."

UIL_65 "Das Argument %s unterstützt keine Numerierungswerte."

UIL_66 "Das Argument %s unterstützt nicht den Numerierungswert %s."

UIL_67 "$LANG enthält einen unbekannten Zeichensatz."

UIL_68 "Die Bedienelement-Hierarchie des Objektes %s enthält eine Referenz auf sich selbst."

UIL_69 "Der Wert %s ist zu groß für den Kontextpuffer."

UIL_70 "Vorwärtsreferenzieren ist für %s nicht erlaubt."

UIL_71 "Kann Typ %s nicht in Typ %s umwandeln."

UIL_72 "%s ist ungültig."

UIL_V2_73 "Fehler beim Lesen der binären Datenbank."

UIL_V2_74 "Binäre Datenbank mit einer zukünftigen Version kompiliert."

UIL_V2_75 "Fehler beim Öffnen der Datenbankdatei: %s"

UIL_V2_76 "Fehler beim Schreiben der UID-Datei: %s"

UIL_V2_77 "'%s' ist ein unbekannter Toolkit Class Record-Name."

UIL_78 "Ungültiger include file??-Name."

UIL_V2_79 "Nicht kompatible Einheitstypen für die arithmetische Operation."

UIL_V2_80 "%s als charset-Name benutzt; %s als charset-Komponente benutzt."


$set UIL_VALUES

UIL_VAL_0 "** Fehler **"

UIL_VAL_1 "** unbekannt **"


$set UIL_SET_MISC


UIL_INF "Info: "

UIL_WAR "Warnung: "

UIL_ERR "Fehler: "

UIL_SEV "Schwerwiegend: "

UIL_MISC_0 "Zeile \t\t: Datei %d: %s"

UIL_MISC_1 "Zeile \t\t: Position %d: Datei %d: %s"
