$ $XConsortium: Xm.msg /main/8 1996/10/19 14:28:54 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 

$ This message catalog contains messages issued by Motif toolkit library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.

$quote " 


$set MS_ArrowButton

MSG_ArrowButton_1000 "Die Pfeilrichtung ist nicht korrekt."
$ MSG_ArrowButton_1000 message is obsolete - DO NOT localize this message.

$set MS_BulletinB

MSG_BulletinB_1000 "Ungültiges Verfahren zur Größenänderung."
$ MSG_BulletinB_1000 message is obsolete - DO NOT localize this message.

$ MSG_BulletinB_0001 "Ungültiger Dialog-Style."
MSG_BulletinB_0001 "Dialog-Style muß XmDIALOG_MODELESS sein."

MSG_BulletinB_1001 "Ungültiger Typ für Schatten."
$ MSG_BulletinB_1001 message is obsolete - DO NOT localize this message.

MSG_BulletinB_1002 "Leere Schriftartliste (Keine Standard-Shell des Herstellers)"
$ MSG_BulletinB_1002 message is obsolete - DO NOT localize this message.


$set MS_CascadeB

MSG_CascadeB_1000 "XmCascadeButton muß korrekten Typ des \n\
Parent XmRowColumnWidgetClass besitzen."
$ MSG_CascadeB_1000 message is obsolete - DO NOT localize this message.

$ MSG_CascadeB_0001 "Nur XmMENU_PULLDOWN XmRowColumnWidgets können Submenüs sein."
MSG_CascadeB_0001 "Nur XmRowColumn Widgets des Typs XmMENU_PULLDOWN können submenus sein."
$ please do not translate submenus. 

MSG_CascadeB_0002 "XmNmappingDelay muß größer oder gleich 0 sein."

MSG_CascadeB_0000 "XmCascadeButton[Gadget] muß übergeordnetes XmRowColumn mit \n\
XmNrowColumnType XmMENU_PULLDOWN, XmMENU_POPUP, XmMENU_BAR oder XmMENU_OPTION haben."

MSG_CascadeB_0003 "XtGrabPointer gescheitert."

MSG_RowColText_0024 "XtGrabKeyboard gescheitert."


$set MS_Command

MSG_Command_0000 "Der Dialogtyp muß XmDIALOG_COMMAND sein."

MSG_Command_0001 "Ungültiger Child-Typ.\n\
Der Widget für Befehle besitzt nicht dieses Child."
$ please do not translate Command.

MSG_Command_0002 "NULL oder leere XmString."

MSG_Command_0003 "NULL oder leere XmString an XmCommandAppendValue übertragen."

MSG_Command_0004 "XmNmustMatch ist immer False (unwahr) für ein Befehls-Widget."
$ please do not translate False or Command. 

MSG_Command_0005 "XmNhistoryMaxItems muß eine positive Ganzzahl größer Null sein."


$set MS_CutPaste

MSG_CutPaste_0000 "XmClipboardStartCopy() muß vor XmClipboardCopy() aufgerufen werden"

MSG_CutPaste_0001 "XmClipboardStartCopy() muß vor XmClipboardEndCopy()\n\
aufgerufen werden"

MSG_CutPaste_0002 "Zu viele Formate in XmClipboardCopy()"

MSG_CutPaste_0003 "ClipboardBadDataType"
$ please do not translate ClipboardBadDataType.

MSG_CutPaste_0004 "Falscher Datentyp"

MSG_CutPaste_0005 "ClipboardCorrupt"
$ please do not translate ClipboardCorrupt.

MSG_CutPaste_0006 "Interner Fehler - fehlerhafte Datenstruktur"

MSG_CutPaste_0007 "ClipboardBadFormat"
$ please do not translate ClipboardBadFormat

MSG_CutPaste_0008 "Fehler - die registrierte Formatlänge muß 8, 16 oder 32 betragen."

MSG_CutPaste_0009 "Fehler - registrierter Formatname darf nicht leer sein."


$set MS_DialogS

MSG_DialogS_0000 "DialogShell-Widget unterstützt nur RectObj als Child-Objekt"
$ please do not translate DialogShell and RectObj.

MSG_DialogS_1000 "Gadgets sind in Shell unzulässig"
$ MSG_DialogS_1000 message is obsolete - DO NOT localize this message.


$set MS_DrawingA

MSG_DrawingA_1001 "Randbreite oder Randhöhe dürfen nicht negativ sein."
$ MSG_DrawingA_1001 message is obsolete - DO NOT localize this message.

MSG_DrawingA_1002 "Ungültiges Verfahren zur Größenänderung."
$ MSG_DrawingA_1002 message is obsolete - DO NOT localize this message.


$set MS_Form

MSG_Form_0000 "Nenner muß ungleich Null sein."

MSG_Form_1000 "Ungültiger Typ für Form der Anlage."
$ MSG_Form_1000 message is obsolete - DO NOT localize this message.

MSG_Form_1001 "Grenzen für Widgets mit fester Größe können nicht festgelegt werden."
$ MSG_Form_1001 message is obsolete - DO NOT localize this message.

MSG_Form_1002 "Widget für Anlage muß ungleich Null sein."
$ MSG_Form_1002 message is obsolete - DO NOT localize this message.
$ please do not translate Attachment

MSG_Form_0002 "Kreisförmige Abhängigkeit in den Children des Form Widget.\n\
Auf kreisförmige Anhänge zwischen den Children prüfen."
$ please do not translate Form. 

MSG_Form_1006 "Rand ist einem Widget zugeordnet, das nicht angegeben wurde."
$ MSG_Form_1006 message is obsolete - DO NOT localize this message.

MSG_Form_0003 "Synchronisation von abandoned edge?? nach 10000 Iterationen.\n\
Auf widersprüchliche Grenzen der Children dieses Form Widgets prüfen."
$ please do not translate Form.

MSG_Form_0004 "Anlage-Widget muß gleichen Parent wie Widget haben."
$ please do not translate Attachment
$ MSG_Form_0004 message is obsolete - DO NOT localize this message.


$set MS_Frame

MSG_Frame_1000 "Nur ein Child-Objekt sollte in einen Rahmen eingefügt werden."
$ please do not translate Frame.
$ MSG_Frame_1000 message is obsolete - DO NOT localize this message.

MSG_Frame_1001 "Ungültige Randbreite."
$ MSG_Frame_1001 message is obsolete - DO NOT localize this message.

MSG_Frame_1002 "Ungültige Randhöhe."
$ MSG_Frame_1002 message is obsolete - DO NOT localize this message.


$set MS_Gadget

MSG_Gadget_1000 "Ungültiger Wert für die Breite der Hervorhebung."
$ MSG_Gadget_1000 message is obsolete - DO NOT localize this message.

MSG_Gadget_1001 "Der Typ der Einheit ist ungültig."
$ MSG_Gadget_1001 message is obsolete - DO NOT localize this message.

MSG_Gadget_1002 "Ungültige Dicke des Schattens."
$ MSG_Gadget_1002 message is obsolete - DO NOT localize this message.

MSG_Gadget_1003 "Ressource für Pixmap muß angegeben werden."
$ MSG_Gadget_1003 message is obsolete - DO NOT localize this message.

MSG_Gadget_0000 "Kann XmNlayoutDirection nach der Initialisierung nicht ändern."


$set MS_Label

MSG_Label_1001 "Ungültiger XmNlabeType"
$ MSG_Label_1001 message is obsolete - DO NOT localize this message.

MSG_Label_1002 "Ungültiger Wert in XmNalignment"
$ MSG_Label_1002 message is obsolete - DO NOT localize this message.

MSG_Label_1003 "Ungültiger Wert in XmNstringDirection"
$ MSG_Label_1003 message is obsolete - DO NOT localize this message.

MSG_Label_0003 "XmNlabelString muß Compound String sein."
$ please do not translate Compound String.

MSG_Label_0004 "XmNacceleratorText muß Compound String sein."
$ please do not translate Compound String.


$set MS_List

MSG_List_0000 "Falls es geändert wird, muß XmNvisibleItemCount wenigstens 1 sein."

MSG_List_1001 "Ungültiges Auswahlverfahren."
$ MSG_List_1001 message is obsolete - DO NOT localize this message.

MSG_List_1002 "Ungültiges Verfahren für Größe."
$ MSG_List_1002 message is obsolete - DO NOT localize this message.

MSG_List_1003 "Ungültiges Verfahren der Anzeige der Bildlaufleiste."
$ MSG_List_1003 message is obsolete - DO NOT localize this message.

MSG_List_1004 "Ungültige Richtung der Zeichenfolge."
$ MSG_List_1004 message is obsolete - DO NOT localize this message.

MSG_List_0005 "Kann XmNlistSizePolicy nach der Initialisierung nicht ändern."

MSG_List_0006 "Falls es geändert wird, muß XmNitemCount nicht-negativ sein."
$ non-negative means zero or positive.

MSG_List_1007 "NULL-Schriftart in SetValues ignoriert."
$ MSG_List_1007 message is obsolete - DO NOT localize this message.
$ please do not translate SetValues

MSG_List_0007 "Zu löschende(s) Element(e) ist/sind in der Liste nicht enthalten."

MSG_List_1009 "Keine horizontale Bildlaufleiste zum Festlegen vorhanden."
$ MSG_List_1009 message is obsolete - DO NOT localize this message.

MSG_List_1010 "Ungültige Randeinstellung."
$ MSG_List_1010 message is obsolete - DO NOT localize this message.

MSG_List_0008 "XmNlistSpacing muß nicht-negativ sein."

MSG_List_0009 "Kann XmNitems nicht auf NULL setzen, wenn XmNitemCount positiv ist."

MSG_List_0010 "XmNselectedItemCount darf nicht negativ sein."

MSG_List_0011 "Kann XmNselectedItems nicht auf NULL setzen, wenn XmNselectedItemCount \
positiv ist."

MSG_List_0012 "XmNtopItemPosition muß nicht-negativ sein."

MSG_List_0013 "XmNitems und XmNitemCount weichen voneinander ab!"

MSG_List_1017 "Hinzufügemodus kann in einer Mehrfachauswahl nicht verlassen werden."
$ MSG_List_1017 message is obsolete - DO NOT localize this message.

MSG_List_0014 "XmNselectedPositionCount darf nicht negativ sein."

MSG_List_0015 "Kann XmNselectedPositions nicht auf NULL setzen, wenn XmNselectedPositionCount \
positiv ist."


$set MS_MainW

MSG_MainW_0000 "Die MenuBar kann nicht in NULL geändert werden."
$ please do not translate MenuBar.

MSG_MainW_0001 "Das CommandWindow kann nicht in NULL geändert werden."
$ please do not translate CommandWindow.

MSG_MainW_1003 "Negative Werte für Rand ignoriert."
$ MSG_MainW_1003 message is obsolete - DO NOT localize this message.


$set MS_MenuShell

MSG_MenuShell_0000 "MenuShell Widgets akzeptieren nur XmRowColumn als Children."
$ please do not translate MenuShell.

MSG_MenuShell_0001 "Es wird versucht, ein Pulldown-Menü zu verwalten, das nicht \n\
mit einer Überlappen-Taste verbunden ist."

MSG_MenuShell_0002 "XmPopup erfordert eine subclass von shellWidgetClass."
$ please do not translate shellWidgetClass.

MSG_MenuShell_0003 "XmPopdown erfordert eine subclass von shellWidgetClass."
$ please do not translate shellWidgetClass.

MSG_MenuShell_0004 "XtMenuPopup erfordert genau ein Argument."

MSG_MenuShell_0005 "XtMenuPopup unterstützt nur die Ereignisse ButtonPress, KeyPress oder EnterNotify."
$ please do not translate ButtonPress, KeyPress or EnterNotify.

MSG_MenuShell_0006 "Kann Popup Widget \"%s\" in XtMenuPopup nicht finden."

MSG_MenuShell_0007 "Kann Popup Widget \"%s\" in XtMenuPopdown nicht finden."

MSG_MenuShell_0008 "XtMenuPopdown mit mehr als einem Argument aufgerufen."

MSG_MenuShell_0009 "Kann XmNlayoutDirection nach der Initialisierung nicht ändern."


$set MS_MessageB

MSG_MessageB_1001 "Ungültiger Dialogtyp."
$ MSG_MessageB_1001 message is obsolete - DO NOT localize this message.

MSG_MessageB_1002 "Ungültiger Typ für Standardtaste."
$ MSG_MessageB_1002 message is obsolete - DO NOT localize this message.

MSG_MessageB_1003 "Ungültiger Typ für Ausrichtung."
$ MSG_MessageB_1003 message is obsolete - DO NOT localize this message.

MSG_MessageB_0003 "Ungültiger Unterordnungstyp; Widget hat dieses Child nicht."

MSG_MessageB_0004 "Taste Abbrechen kann nicht geändert werden."

MSG_MessageB_1006 "XmNdefaultButtonType verwenden um Standardtaste der MessageBox\n\
festzulegen."
$ MSG_MessageB_1006 message is obsolete - DO NOT localize this message.


$set MS_PanedW

MSG_PanedW_0000 "Minimalwert muß größer als 0 sein."

MSG_PanedW_0001 "Maximalwert muß größer als 0 sein."

MSG_PanedW_0002 "Minimalwert muß kleiner als Maximalwert sein."

MSG_PanedW_0003 "Grenzwerte erlauben keine angemessene Größenfestlegung."
$ MSG_PanedW_0003 message is obsolete - DO NOT localize this message.

MSG_PanedW_0004 "Zu wenige Parameter in Funktionsaufruf für Schieber."

MSG_PanedW_0005 "Ungültiger erster Parameter in Funktionsaufruf für Schieber."


$set MS_PWidget

MSG_PWI_1001 "fontList ist nicht definiert"
$ MSG_PWI_1001 message is obsolete - DO NOT localize this message.
$ please do not translate fontList.


$set MS_Protocols

MSG_Protocols_0000 "Widget muß eine VendorShell sein."
$ please do not translate VendorShell.

MSG_Protocols_0001 "Protokol-Manager ist bereits vorhanden"

MSG_Protocols_0002 "Mehr Protokolle vorhanden, als Widget abwickeln kann;\n\
32 ist die Grenze."


$set MS_PushB

MSG_PushB_1001 "Speicher reicht nicht aus"
$ MSG_PushB_1001 message is obsolete - DO NOT localize this message.


$set MS_RowColumn

$ In this set, do not translate the word that starts with "XmN" or "Xm". 

MSG_RowColumn_1001 "Versuch die Breite auf Null zu setzen.\n\
Wird auf Standardwert 16 gesetzt."
$ MSG_RowColumn_1001 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0000 "Versuch ignoriert, die Breite auf Null zu setzen. "

MSG_RowColumn_1003 "Versuch die Höhe auf Null zu setzen.\n\
Wird auf Standardwert 16 gesetzt."
$ MSG_RowColumn_1003 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0001 "Versuch ignoriert, die Höhe auf Null zu setzen."

MSG_RowColumn_0002 "XmNhelpWidget auf NULL gesetzt, da nicht von Popup-Menüs benutzt."

MSG_RowColumn_0003 "XmNhelpWidget auf NULL gesetzt, da nicht von Pulldown-Menüs benutzt."

MSG_RowColumn_0004 "XmNhelpWidget auf NULL gesetzt, da nicht von Optionsmenüs benutzt."

MSG_RowColumn_0005 "XmNhelpWidget auf NULL gesetzt, da nicht von Arbeitsbereichen benutzt."

MSG_RowColumn_1009 "Unbekannter Wert für XmNrowColumnType.\n\
Wird auf WorkArea gesetzt."
$ MSG_RowColumn_1009 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0007 "Widget-Hierarchie nicht geeignet für diesen XmNrowColumnType:\n\
kehrt zum Standard XmWORK_AREA zurück."

MSG_RowColumn_0008 "Versuch ignoriert, XmNrowColumnType nach der Initialisierung zu ändern."

MSG_RowColumn_1012 "Unbekannter Wert für XmNorientation.\n\
Der Standardwert wird verwendet."
$ MSG_RowColumn_1012 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1013 "Versuch XmNorientation auf einen unbekannten Wert zu setzen.\n\
Der Wert wird ignoriert."
$ MSG_RowColumn_1013 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1014 "Unbekannter Wert für XmNpacking.\n\
Der Standardwert wird verwendet."
$ MSG_RowColumn_1014 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1015 "Versuch XmNpacking auf einen unbekannten Wert zu setzen.\n\
Der Wert wird ignoriert."
$ MSG_RowColumn_1015 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1016 "Unbekannter Wert für XmNentryAlignment.\n\
Der Standardwert wird verwendet."
$ MSG_RowColumn_1016 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1017 "Versuch XmNentryAlignment auf einen unbekannten Wert zu setzen.\n\
Der Wert wird ignoriert."
$ MSG_RowColumn_1017 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0015 "Versuch ignoriert, XmNisHomogenous für ein RowColumn Widget des Typs \
XmMENU_BAR auf FALSE zu setzen."
$ please do not translate FALSE and RowColumn.

MSG_RowColumn_0016 "Versuch ignoriert, XmNentryClass für ein RowColumn Widget des Typs \
XmMENU_BAR zu ändern."
$ please do not translate RowColumn.

MSG_RowColumn_0017 "Versuch ignoriert, XmNwhichButton über XtSetValues für ein RowColumn Widget \
des Typs XmMENU_PULLDOWN zu ändern."
$ please do not translate RowColumn.

MSG_RowColumn_0018 "Versuch ignoriert, XmNmenuPost über XtSetValues für ein RowColumn Widget \
des Typs XmMENU_PULLDOWN zu ändern."
$ please do not translate RowColumn.

MSG_RowColumn_0019 "Versuch ignoriert, XmNmenuPost auf einen ungültigen Wert zu setzen."

MSG_RowColumn_0020 "Versuch ignoriert, XmNshadowThickness für ein RowColumn Widget nicht vom Typ \
XmMENU_PULLDOWN oder XmMENU_POPUP zu ändern."
$ please do not translate RowColumn.

MSG_RowColumn_1024 "Versuch XmNorientation für einen RowColumn-Widget \n\
des Typs XmMENU_OPTION zu ändern.\n\
Der Wert wird ignoriert."
$ MSG_RowColumn_1024 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0022 "Versuch einen ungültigen Child-Typ einem.  \n\
Menü-Widget (z.B. Menü RowColumn) hinzuzufügen"

MSG_RowColumn_0023 "Versuch, einen ungültigen Child-Typ einem homogenen \n\
RowColumn-Widget hinzuzufügen"

MSG_RowColumn_0025 "Versuch XmNisHomogeneous für ein RowColumn \n\
\t Widget vom Typ XmMENU_OPTION zu ändern, ignoriert"
$ please do not translate RowColumn.

MSG_RowColumn_0026 "Aktivierung von Tear off bei einem mehrfach verwendeten Menüteilfenster wird nicht empfohlen."

MSG_RowColumn_0027 "Ungültiges mnemonisches Zeichen. X KEYSYM konnte nicht\n\
\t in einen Tastencode umgewandelt werden."
$ please do not translate X KEYSYM.


$set MS_Scale

MSG_Scale_0000 "Der Wert für das Minimum der Skala ist größer oder \n\
gleich dem Wert für das Maximum."

MSG_Scale_0001 "Der angegebene Wert für die Skala ist kleiner  \n\
als der Minimalwert der Skala."

MSG_Scale_0002 "Der angegebene Wert für die Skala ist größer \n\
als der Maximalwert der Skala."

MSG_Scale_1004 "Ausrichtung nicht korrekt."
$ MSG_Scale_1004 message is obsolete - DO NOT localize this message.

MSG_ScaleScrBar_0004 "Bewegungsrichtung ist nicht korrekt."

MSG_Scale_0005 "Ungültige Stärke (Dicke) der Hervorhebung."
$ MSG_Scale_0005 message is obsolete - DO NOT localize this message.

MSG_Scale_0006 "Ungültiges XmNscaleMultiple; größer als (max - min)"

MSG_Scale_0007 "Ungültiges XmNscaleMultiple; kleiner als Null"

MSG_Scale_0008 "(Maximum - Minimum) darf nicht größer sein als \n\
\tINT_MAX geteilt durch 2. Das Minimum wurde auf Null gesetzt. \n\
\tDas Maximum wurde möglicherweise auf (INT_MAX/2) gesetzt."

MSG_Scale_0009 "XmNshowValue hat falschen Wert."


$set MS_ScrollBar

MSG_ScrollBar_0000 "Der Minimalwert der Bildlaufleist ist größer oder\n\
gleich dem Maximalwert."

MSG_ScrollBar_0001 "Die angegebnen Größe des Reglers (slider) ist kleiner 1"

MSG_ScrollBar_0002 "Der angebene Wert für die Bildlaufleiste ist kleiner\n\
als der Minimalwert für die Bildlaufleiste."

MSG_ScrollBar_0003 "Der angegebene Wert für die Bildlaufleiste ist \n\
größer als der Maximalwert abzüglich der Größe\n\
des Reglers der Bildlaufleiste."

MSG_ScrollBar_1005 "Ausrichtung nicht korrekt."
$ MSG_ScrollBar_1005 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_1006 "Bewegungsrichtung ist nicht korrekt."
$ MSG_ScrollBar_1006 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_0004 "Das Inkrement für die Bildlaufleiste ist kleiner 1."

MSG_ScrollBar_0005 "Das Inkrement für eine Seite der Bildlaufleiste ist kleiner 1."

MSG_ScrollBar_0006 "Der Wert für die anfängliche Verzögerung der Bildlaufleiste\n\
ist kleiner 1."

MSG_ScrollBar_0007 "Die Wiederholrate für die Bildlaufleiste ist kleiner 1."

MSG_ScrollBar_1011 "Fehler im Kontext-Manager; Hintergrund der Bildlaufleisten\n\
kann nicht korrekt festgelegt werden"
$ MSG_ScrollBar_1011 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_1012 "Fehler im Kontext-Manager; Vordergrund der Bildlaufleisten\n\
kann nicht korrekt festgelegt werden"
$ MSG_ScrollBar_1012 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_0008 "Die Größe des Reglers ist größer als die Differenz\n\
zwischen Maximal- und Minimalwert der Bildlaufleiste."


$set MS_ScrolledW

MSG_ScrolledW_1001 "Ungültiges Verfahren zur Anzeige der Bildlaufleiste."
$ MSG_ScrolledW_1001 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1002 "Ungültiges Verfahren für das Durchlaufen des Bildes."
$ MSG_ScrolledW_1002 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1003 "Ungültiges Verfahren zur Anzeige."
$ MSG_ScrolledW_1003 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1004 "Ungültiges Verfahren der Plazierung."
$ MSG_ScrolledW_1004 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_0004 "Verfahren für das Durchlaufen des Bildes kann nach der\n\
Initialisierung nicht geändert werden."

MSG_ScrolledW_0005 "Verfahren zur Anzeige kann nach der Initialisierung nicht\n\
geändert werden."

MSG_ScrolledW_0006 "Verfahren AS_NEEDED für die Bildlaufleiste kann nicht\n\
mit dem Verfahren VARIABLE für die Anzeige festgelegt werden."
$ please do not translate AS_NEEDED or VARIABLE.

MSG_ScrolledW_0007 "Widget für Bildlaufleiste kann nicht auf Modus AUTOMATIC\n\
festgelegt werden."
$ please do not translate AUTOMATIC.

MSG_ScrolledW_0008 "Klemmfenster (clip window) kann nicht geändert werden"

MSG_ScrolledW_0009 "Verfahren CONSTANT für die Anzeige kann im Modus APPLICATION_DEFINED\n\
nicht festgelegt werden."
$ please do not translate CONSTANT or APPLICATION_DEFINED.

MSG_ScrollVis_0000 "Falsche Parameter an die Funktion XmScrollVisible übergeben."


$set MS_SelectioB

MSG_SelectioB_1001 "Ungültiger Dialogtyp."
$ MSG_SelectioB_1001 message is obsolete - DO NOT localize this message.

MSG_SelectioB_0001 "Dialogtyp kann nicht geändert werden."
$ please do not translate Dialog.

MSG_SelectioB_1003 "Nur ein Child des Arbeitsbereichs zulässig."
$ MSG_SelectioB_1003 message is obsolete - DO NOT localize this message.

MSG_SelectioB_0002 "Widget unterstützt diesen Child-Typ nicht."


$set MS_Separator

MSG_Separator_1001 "Ungültiger Trennzeichentyp."
$ MSG_Separator_1001 message is obsolete - DO NOT localize this message.

MSG_Separator_1002 "Ungültige Ausrichtung."
$ MSG_Separator_1002 message is obsolete - DO NOT localize this message.


$set MS_Text

MSG_Text_0000 "Falscher Quellentext wird ignoriert."

MSG_Text_1003 "Ungültiger Bearbeitemodus."
$ MSG_Text_1003 message is obsolete - DO NOT localize this message.

MSG_Text_0002 "Text widget is editable; XmNtraversalOn must be True."
$ please do not translate XmNtraversalOn and True.
$ MSG_Text_0002 message is obsolete - DO NOT localize this message.

MSG_TextIn_0000 "Kann Position nicht finden beim Versuch, in vorherige Zeile zu verschieben."

MSG_TextOut_0000 "Anzahl der Reihen muß größer als 0 sein."

MSG_TextF_0002 "XmFontListInitFontContext gescheitert."
$ please do not translate XmFontListInitFontContext.

MSG_TextF_0003 "XmFontListGetNextFont gescheitert."
$ please do not translate XmFontListGetNextFont.

MSG_TextF_0004 "Zeichen '%s' wird in der Schriftart nicht unterstützt. Verworfen."

MSG_TextFWcs_0000 "Zeichen '%s' wird in der Schriftart nicht unterstützt. Verworfen."

MSG_TextFWcs_0001 "Cannot use multibyte locale without a fontset.  Value discarded."
$ MSG_TextFWcs_0001 message is obsolete - DO NOT localize this message.

$set MS_TextF

MSG_TextF_0000 "Cursorposition muß größer oder gleich 0 sein."

MSG_TextF_0001 "Spaltenzahl muß größer als 0 sein."

MSG_TextF_0005 "XmNtraversalOn must always be True."
$ please do not translate XmNtraversalOn and True.
$ MSG_TextF_0005 message is obsolete - DO NOT localize this message.

MSG_TextF_0006 "Spaltenzahl muß größer oder gleich 0 sein."


$set MS_ToggleB

MSG_ToggleB_1001 "(Kenn-)Anzeige (Indicator) sollte entweder XmONE_OF_MANY oder\n\
XmN_OF_MANY sein"
$ MSG_ToggleB_1001 message is obsolete - DO NOT localize this message.


$set MS_Traversal

MSG_Traversal_1001 "Ungültiger Wert für navigation_type"
$ MSG_Traversal_1001 message is obsolete - DO NOT localize this message.

MSG_Traversal_1002 "Falscher Wert in old für navigation_type!!"
$ MSG_Traversal_1002 message is obsolete - DO NOT localize this message.

MSG_Traversal_1003 "Traversale Bootstrap-Situation mit ungeeigneten Parametern"
$ MSG_Traversal_1003 message is obsolete - DO NOT localize this message.

MSG_Traversal_1004 "Versuch mit ungeeigneten Parametern auf den neuen Tabulator\n\
zu positionieren"
$ MSG_Traversal_1004 message is obsolete - DO NOT localize this message.

MSG_Traversal_1005 "startWidget ist nicht in der Child-Liste"
$ MSG_Traversal_1005 message is obsolete - DO NOT localize this message.
$ please do not translate startWidget

MSG_Traversal_1006 "Ungeeignete Parameter für TraverseToChild"
$ MSG_Traversal_1006 message is obsolete - DO NOT localize this message.
$ please do not translate TraverseToChild.


$set MS_Vendor

MSG_Vendor_0000 Ungültiger Wert für XmNdeleteResponse.

MSG_Vendor_1002 "Ungültiger XmNpreeditType, wird auf Standard OverTheSpot gesetzt"
$ MSG_Vendor_1002 message is obsolete - DO NOT localize this message.

MSG_Vendor_0001 "Ungültiger Wert für XmNinputPolicy."

MSG_Vendor_0002 "XmNlayoutDirection kann nicht geändert werden."

MSG_Vendor_0003 "Schwerwiegender Fehler: \n\
_XmGetDefaultDisplay kann nicht vor VendorS verwendet werden. Initialisieren, gibt NULL zurück."


$set MS_VendorE

MSG_VendorE_1001 "FetchUnitType: ungeeignete Widget-Klasse"
$ MSG_VendorE_1001 message is obsolete - DO NOT localize this message.

MSG_VendorE_0000 "String to no-op conversion needs no extra arguments"
$ MSG_VendorE_0000 message is obsolete - DO NOT localize this message.

MSG_VendorE_0005 "FetchUnitType ohne einen Widget als Referenz aufgerufen."
$ Do not translate FetchUnitType. 
$ please do not translate FetchUnitType.
$ MSG_VendorE_0005 message is obsolete - DO NOT localize this message.


$set MS_VirtKeys

MSG_VirtKey_1001 "Virtuelle Belegungsinitialisierung (bindings Initialize) wurde\n\
nicht aufgerufen"
$ MSG_VirtKey_1001 message is obsolete - DO NOT localize this message.


$set MS_Visual

MSG_Visual_0000 "Ungültige Farbe von _XmAccessColorData angefordert."

MSG_Visual_0001 "Kann Farbtabellen-Eintrag für Standardhintergrund nicht zuteilen."

MSG_Visual_0002 "Kann Farbangabe für Standardhintergrund nicht analysieren."


$set MS_XmIm

MSG_XmIm_0000 "Kann Eingabemethode nicht öffnen - XLookupString wird verwendet."

MSG_XmIm_1002 "Das Objekt für die Art der Eingabe kann nicht erstellt werden"
$ MSG_XmIm_1002 message is obsolete - DO NOT localize this message.

MSG_XmIm_1003 "XmIMFocus mit einem NULL-Widget aufgerufen."
$ MSG_XmIm_1003 message is obsolete - DO NOT localize this message.

MSG_XmIm_1004 "XmIMMove ohne Fokus für Art der Eingabe aufgerufen ."
$ MSG_XmIm_1004 message is obsolete - DO NOT localize this message.


$set MS_Resources

MSG_Resource_0001 "OK"
$ "OK" as in "Go ahead"/"Confirmed to proceed as instructed"/"Fine"

MSG_Resource_0002 "Abbruch"
$ ... as in "Never mind"/"abort this operation"/"Stop current request"

MSG_Resource_0003 "Auswahl"
$ ... as in "choosing from a list of items"

MSG_Resource_0004 "Anwenden"
$ ... as in "To do something with the things selected"

MSG_Resource_0005 "Hilfe"
$ ... as in "Need more guidance on how to deal with this dialog box"

MSG_Resource_0006 "Filter"
$ ... the noun "Filter", as in "a sifter/a filter/a qualifier to screen out"
$ files with

MSG_Resource_0007 "Dateien"
$ ... as in "a list of the files"

MSG_Resource_0008 "Verzeichnisse"
$ ... as in "a list of the directories" 

MSG_Resource_0009 "Elemente"
$ ... as in "a list of things to choose from"

MSG_Resource_0010 "Filter"
$ ... the verb "Filter", as in "To screen out some files"
$ Note this has a slightly different semantics from MSG_Res_1006.
$ In English, it is the same word, but MSG_Res_1006 means "a sifter", and
$ MSG_Res_1010 means "Push this button to filter out some files"
$ MSG_Res_1006 is a label indicating "entry below is qualifier to filter out" 
$ files with

MSG_Resource_0011 "Verzeichnis"

MSG_Resource_0012 ">"
$ command-line prompt in the Command widget. 


$set MS_BaseClass

MSG_BaseClass_0000 "Kein Kontext für Erweiterung gefunden."

MSG_BaseClass_0001 "_XmPopWidgetExtData: keine Erweiterung mit XFindContext gefunden."

MSG_BaseClass_0002 "XmFreeWidgetExtData ist eine nicht unterstützte Routine."
$ MSG_BaseClass_0002 message is obsolete - DO NOT localize this message.

MSG_GetSecRes_0000 "getLabelSecResData: nicht genügend Speicher."
$ please do not translate getLabelSecResData.
$ MSG_GetSecRes_0000 message is obsolete - DO NOT localize this message.


$set MS_Display

MSG_Display_0001 "Mehrere XmDisplays für die gleiche X-Anzeige erstellt.\n\
\tFür eine bestimmte Anzeige wurde nur das erste XmDisplay erstellt,\n\
\tauf das mittels Aufrufen von XmGetXmDisplay refernziert werden kann."
$ please do not translate XmDisplay or XmGetXmDisplay

MSG_Display_0002 "TOP_LEVEL_LEAVE ohne aktiven DragContext empfangen."
$ please do not translate TOP_LEVEL_LEAVE or DragContext

MSG_Display_0003 "XmDisplay-Klasse kann nicht zu einer non-subclass von XmDisplay\n\
festgelegt werden."
$ please do not translate XmDisplay


$set MS_DragBS

MSG_DragBS_0000 "Das _MOTIF_DRAG_WINDOW wurde zerstört."
$ please do not translate _MOTIF_DRAG_WINDOW

MSG_DragBS_0001 "Der Stand der Protokollversionen stimmt nicht überein."

MSG_DragBS_0002 "Öffnen der Anzeige nicht möglich."

MSG_DragBS_0003 "Die Tabelle der Atome ist leer."

MSG_DragBS_0004 "Die Zieltabelle ist leer."

MSG_DragBS_0005 "Die Zieltabelle hat eine inkonsistente Eigenschaft."

MSG_DragBS_0006 "Ungültiger Index der Zieltabelle."


$set MS_DragC

MSG_DragC_0001 "GenerateCallback erwartet kein XmCR_DROP_SITE_ENTER als Argument."
$ please do not translate GenerateCallback or XmCR_DROP_SITE_ENTER

MSG_DragC_0002 "Ungültige Auswahl in DropConvertCallback."
$ please do not translate DropConvertCallback

MSG_DragC_0003 "Die Auswahl zur Übergabe ging verloren."

MSG_DragC_0004 "XGrabPointer gescheitert."

MSG_DragC_0005 "ExternalNotifyHandler: Die Callback-Argument kann nicht\n\
akzeptiert werden."
$ please do not translate ExternalNotifyHandler

MSG_DragC_0006 "XmDragStart muß als Ergebnis eines Tastendrucks oder Motion Events aufgerufen werden."
$ please do not translate XmDragStart


$set MS_DragICC

MSG_DragICC_0000 "Unbekannter Typ der Meldung zu Ziehen und Übergeben."

MSG_DragICC_0001 "Die Ebenen der Protokollversion stimmen nicht überein."


$set MS_DragIcon

MSG_DragIcon_0000 "Keine Größenfestlegung (Geometrie) für dragIcon-Pixmap angegeben."
$ please do not translate dragIcon

MSG_DragIcon_0001 "dragIcon wurde ohne Pixmap erstellt."
$ please do not translate dragIcon

MSG_DragIcon_0002 "String to Bitmap converter needs Screen argument"
$ MSG_DragIcon_0002 message is obsolete - DO NOT localize this message.


$set MS_DragOverS

MSG_DragOverS_0000 "Tiefe stimmt nicht überein."

MSG_DragOverS_0001 "Unbekannte Anlage (Attachment) zum Symbol."

MSG_DragOverS_0002 "Unbekannter Status zum Ziehen."

MSG_DragOverS_0003 "Unbekanntes XmNblendModel."
$ please do not translate XmNblendModel 


$set MS_DragUnder

MSG_DragUnder_0000 "Fenster-Geometrie der dropSite nicht zugänglich."

MSG_DragUnder_0001 "Ungültige animationPixmapDepth."
$ please do not translate animationPixmapDepth


$set MS_DropSMgr

MSG_DropSMgr_0001 "Übergabebereiche, die Childeren eines einfachen Übergabebereichs\n\
sind können nicht erstellt werden."

MSG_DropSMgr_0002 "Motion Events ohne aktiven Ziehen-Kontext erhalten."

MSG_DropSMgr_0003 "Operation changed ohne aktiven Ziehen-Kontext erhalten."

MSG_DropSMgr_0004 "Aktiven Übergabebereich ohne Übergabe-Prozedur erstellt."

MSG_DropSMgr_0005 "Rechtecke oder die Zahlenangaben der Rechtecke von \n\
zusammengesetzten Übergabebereichen können nicht festgelegt werden."

MSG_DropSMgr_0006 "Ein Widget wurde als Übergabebereich auserhalb der Reihenfolge\n\
\tregistriert. Ancestors (übergeordnete Fensterobjekte) müssen \n\
\tregistriert werden bevor einer der Descendants (untergordnete\n\
\tFensterobjekte) registriert wird."

MSG_DropSMgr_0007 "Ein Widget kann nich mehr als einmal als Übergabebereich\n\
registriert werden."

MSG_DropSMgr_0008 "DropSite-Typ sollte nur zur Zeit der Erstellung festgelegt werden."
$ please do not translate DropSite

MSG_DropSMgr_0009 "Rechtecke eines nicht einfachen Übergabebereichs können nicht\n\
geändert werden."

MSG_DropSMgr_0010 "Kann eine Shell nicht als Übergabebereich registrieren."

MSG_DropSMgrI_0001 "Ein Übergabebereich der ein untergeordnetes Fensterobjekt eines \n\
einfachen Übergabebereichs ist kann nictht registriert werden."

MSG_DropSMgrI_0002 "Eine durchgänge Child-Liste kann für eine zusammengesetzten \n\
Übergabebereich nicht erstellt werden."

MSG_DropSMgrI_0003 "%s ist kein Child-Übergabebereich von %s."


$set MS_GeoUtils

MSG_GeoUtils_0000 "Failure of geometry request to \"almost\" reply"
$ please do not translate "almost"
$ MSG_GeoUtils_0000 message is obsolete - DO NOT localize this message.

MSG_GeoUtils_0001 "Invalid layout of children found"
$ MSG_GeoUtils_0001 message is obsolete - DO NOT localize this message.

MSG_GeoUtils_0002 "Invalid order found in XmSelectionBox"
$ MSG_GeoUtils_0002 message is obsolete - DO NOT localize this message.


$set MS_Region

MSG_Region_0000 "Speicherfehler."


$set MS_RepType

MSG_RepType_0001 "Ungültige Kennung für Repräsentationstyp."

MSG_RepType_0002 "Ungültiger Wert (%d) für rep Typ XmR%s."
$ please do not translate XmR%s

MSG_RepType_0000 "Umgekehrte Umwandlung von "


$set MS_ResConvert

MSG_ResConvert_0000 "FetchUnitType: ungültige Widget-Klasse."
$ please do not translate FetchUnitType.
$ MSG_ResConvert_0000 message is obsolete - DO NOT localize this message.

MSG_ResConvert_0001 "Falsch definierte Standardliste! Wird beendet..."

MSG_ResConvert_0002 "Fehlender Doppelpunkt in Schriftartzeichenfolge \"%s\"; alle übrigen Schriftarten in der Liste nicht analysiert."

MSG_ResConvert_0003 "Ungültiger Begrenzer in Identifizierungskennzeichen \"%s\"; alle übrigen Schriftarten in der Liste nicht analysiert."

MSG_ResConvert_0004 "Unmatched quotation marks in string \"%s\"; any remaining fonts in list unparsed"
$ MSG_ResConvert_0004 message is obsolete - DO NOT localize this message.

MSG_ResConvert_0005 "Nicht übereinstimmende Anführungszeichen in Identifizierungskennzeichen \"%s\"; alle übrigen Schriftarten in der Liste nicht analysiert."

MSG_ResConvert_0006 "Leeres Identifizierungskennzeichen bei der Umwandlung in Typ %s gefunden; alle übrigen Schriftarten in der Liste nicht analysiert."

MSG_ResConvert_0007 "Kann XmString nicht in zusammengesetzten Text umwandeln"

MSG_ResConvert_0008 "Nicht genügend Speicher für XmbTextListToTextProperty"

MSG_ResConvert_0009 "Länderspezifische Angaben für XmbTextListToTextProperty nicht unterstützt."

MSG_ResConvert_0010 "XmbTextListToTextProperty fehlgeschlagen."

MSG_ResConvert_0011 "Kann Widgetnamen nicht in Widget umwandeln."
$ please do not translate Widget.

MSG_ResConvert_0012 "Kann zusammengesetzten Text nicht in XmString umwandeln."

MSG_ResConvert_0013 "Kann XmString nicht in zusammengesetzten Text umwandeln."

MSG_ResConvert_0014 "FetchUnitType called without a widget to reference"
$ please do not translate FetchUnitType.
$ MSG_ResConvert_0014 message is obsolete - DO NOT localize this message

MSG_ResConvert_0015 "FetchDisplayArg called without a widget to reference"
$ please do not translate FetchDisplayArg.
$ MSG_ResConvert_0015 message is obsolete - DO NOT localize this message

MSG_ResConvert_0016 "FetchWidgetArg called without a widget to reference"
$ please do not translate FetchWidgetArg.
$ MSG_ResConvert_0016 message is obsolete - DO NOT localize this message


$set MS_Screen

MSG_Screen_0000 "Symolanzeige stimmt nicht überein."

MSG_Screen_0001 "XmScreen nicht erhalten, da XmDisplay nicht gefunden wurde."


$set MS_ColObj

MSG_ColObj_0001 "Speicherzuordnung für Farbobjektdaten nicht möglich."

MSG_ColObj_0002 "Ungültige Zahl der Anzeige von der Auswahl des Farb-Servers."


$set MS_IG

MSG_IG_1 "Ausrichtung nicht korrekt."
$ MSG_IG_1 message is obsolete - DO NOT localize this message.

MSG_IG_2 "Verhalten nicht korrekt."
$ MSG_IG_2 message is obsolete - DO NOT localize this message.

MSG_IG_3 "Modus für Füllen nicht korrekt."
$ MSG_IG_3 message is obsolete - DO NOT localize this message.

MSG_IG_4 "Position der Zeichenfolge oder der Pixmap nicht korrekt."
$ MSG_IG_4 message is obsolete - DO NOT localize this message.

MSG_IG_5 "Randbreite oder -höhe nicht korrekt."
$ MSG_IG_5 message is obsolete - DO NOT localize this message.

MSG_IG_6 "Typ des Schattens nicht korrekt."
$ MSG_IG_6 message is obsolete - DO NOT localize this message.


$set MS_ComboBox

MSG_ComboBox_0000 "Anwendungen können XmComboBox Widgets keine Children hinzufügen."

MSG_ComboBox_0001 "Die Ressource XmNcomboBoxType kann durch XtSetValues nicht geändert werden."

MSG_ComboBox_0002 "XmFontListGetNextFont failed."
$ MSG_ComboBox_0002 message is obsolete - DO NOT localize this message.

MSG_ComboBox_0003 "XmFontListInitFontContext failed."
$ MSG_ComboBox_0003 message is obsolete - DO NOT localize this message.

MSG_ComboBox_0004 "Internes Widget wurde zerstört. Verhalten ist nicht definiert."

MSG_ComboBox_0005 "Internes Widget war nicht verwaltet. Verhalten ist nicht definiert."

MSG_ComboBox_0006 "XmQUICK_NAVIGATE ist nur gültig für ComboBoxes des Typs XmNcomboBoxType XmDROP_DOWN_LIST"

MSG_ComboBox_0007 "Aktion mit der falschen Parameterzahl aufgerufen."

MSG_ComboBox_0008 "Aktionsroutine von einem Widget aufgerufen, das kein Descendant (untergeordnetes Fensterobjekt) von ComboBox ist."

MSG_ComboBox_0009 "XmComboBoxSelectItem aufgerufen, obwohl ein Element nicht in der ComboBox enthalten ist."

MSG_ComboBox_0010 "XmComboBoxSetItem aufgerufen, obwohl ein Element nicht in der ComboBox enthalten ist."

MSG_ComboBox_0011 "XmComboBoxDeletePos mit einer ungültigen Position aufgerufen."

MSG_ComboBox_0012 "Dienstprogramm-Routine XmComboBox mit einem ungültigen Widget aufgerufen."

MSG_ComboBox_0013 "Anwendungen setzen möglicherweise nicht die automatischen XmComboBox Widget Children."

MSG_ComboBox_0014 "XmComboBox positionMode darf nach der Erstellung nicht geändert werden."
$ please do not translate positionMode.


$set MS_Container

MSG_Container_0000 "Aktion mit der falschen Parameterzahl aufgerufen."

MSG_Container_0001 "XmNdetailColumnHeading und XmNdetailColumnHeadingCount stimmen nicht überein!"


$set MS_CSText

MSG_CSText_0000 "Invalid margin height; must be greater than or equal to 0."
$ MSG_CSText_0000 message is obsolete - DO NOT localize this message.

MSG_CSText_0001 "Invalid margin width; must be greater than or equal to 0."
$ MSG_CSText_0001 message is obsolete - DO NOT localize this message.

MSG_CSText_0002 "Invalid edit mode."
$ MSG_CSText_0002 message is obsolete - DO NOT localize this message.

MSG_CSText_0003 "XmNtraversalOn must always be true."
$ MSG_CSText_0003 message is obsolete - DO NOT localize this message.

MSG_CSText_0004 "Cannot change XmNscrollHorizontal after initialization."
$ MSG_CSText_0004 message is obsolete - DO NOT localize this message.

MSG_CSText_0005 "Cannot change XmNscrollVertical after initialization."
$ MSG_CSText_0005 message is obsolete - DO NOT localize this message.

MSG_CSText_0006 "Cannot change XmNscrollTopSide after initialization."
$ MSG_CSText_0006 message is obsolete - DO NOT localize this message.

MSG_CSText_0007 "Cannot change XmNscrollLeftSide after initialization."
$ MSG_CSText_0007 message is obsolete - DO NOT localize this message.


$set MS_GrabShell

MSG_GrabS_0000 "XmPopup requires a subclass of shellWidgetClass."
$ please do not translate shellWidgetClass.
$ MSG_GrabS_0000 message is obsolete - DO NOT localize this message.


$set MS_Manager

MSG_Manager_0000 "Widget-Klasse %s hat ungültigen Datensatz CompositeClassExtension."
$ please do not translate CompositeClassExtension.

MSG_Manager_0001 "Kann XmNlayoutDirection oder XmNstringDirection nach der Initialisierung nicht ändern."


$set MS_NavigMap

MSG_NavigMap_0000 "_XmNavigate called with invalid direction"
$ MSG_NavigMap_0000 message is obsolete - DO NOT localize this message.


$set MS_Notebook

MSG_Notebook_0000 "Ressource XmNnotebookChildType kann nicht von XtSetValues gesetzt werden."


$set MS_PixConv

MSG_PixConv_0000 "Falsche Parameterzahl für CvtStringToPixmap"
$ please do not translate CvtStringToPixmap.


$set MS_Primitive

MSG_Primitive_0000 "Kann XmNlayoutDirection nach der Initialisierung nicht ändern."


$set MS_ScrollFrameT

MSG_ScrollFrameT_0000 "AssocNavigator erfordert eine Navigatoreigenschaft."
$ please do not translate AssocNavigator.

MSG_ScrollFrameT_0001 "DeAssocNavigator erfordert eine Navigatoreigenschaft."
$ please do not translate DeAssocNavigator.


$set MS_SpinB

MSG_SpinB_0001 "Invalid value for XmNarrowLayout."
$ MSG_SpinB_0001 message is obsolete - DO NOT localize this message.

MSG_SpinB_0002 "XmNminimumValue equals XmNmaximumValue."
$ MSG_SpinB_0002 message is obsolete - DO NOT localize this message.

MSG_SpinB_0003 "Keine Elemente für XmSTRING Child angegeben."

MSG_SpinB_0004 "XmNincrement-Wert kann nicht 0 betragen. Ein Wert von 1 wird benutzt."

MSG_SpinB_0005 "Die von XmNincrementValue angegebene Durchlaufrichtung\n\
wurde umgekehrt, um mit den angegebenen\n\
XmNminimumValue und XmNmaximumValue übereinzustimmen."

MSG_SpinB_0006 "XmNposition außerhalb des Bereichs; minimale XmNposition verwendet."

MSG_SpinB_0007 "XmNposition außerhalb des Bereichs; maximale XmNposition verwendet."

MSG_SpinB_0008 "Ungültiger Wert für XmNpositionType. Standardwert wird benutzt."

MSG_SpinB_0009 "XmNpositionType resource can only be set at creation time."
$ MSG_SpinB_0009 message is obsolete - DO NOT localize this message.


$set MS_Transfer

MSG_Transfer_0000 "SelectionCallbackWrapper wird aufgerufen, wenn Übertragungen beendet sein sollten."
$ please do not translate SelectionCallbackWrapper.

MSG_Transfer_0001 "Cannot lock the clipboard; aborting transfer"
$ MSG_Transfer_0001 message is obsolete - DO NOT localize this message.

MSG_Transfer_0002 "Format und Typ der vom Funktionsaufruf gelieferten Daten stimmen nicht mit den Daten überein, die zusammengefügt werden."

MSG_Transfer_0003 "Der Status in XmConvertCallbackStruct ist nicht XmCONVERT_MERGE."

MSG_Transfer_0004 "CONVERT_MORE wird noch nicht unterstützt."
$ please do not translate CONVERT_MORE.

MSG_Transfer_0005 "Falscher Atomwert gefunden."

MSG_Transfer_0006 "Warnung: Es wird versucht, eine MULTIPLE-Übertragung zu starten, obwohl schon eine im Gange ist."
$ please do not translate MULTIPLE.

MSG_Transfer_0007 "Warnung: Es wird versucht, eine MULTIPLE-Übertragung zu senden, obwohl keine im Gange ist."
$ please do not translate MULTIPLE.


$set MS_VaSimple

MSG_VaSimple_0000 "XtVaTypedArg-Umwandlung benötigt nicht-leere Widget-Grifffläche."

MSG_VaSimple_0001 "Kann Ressourcentyp für die Umwandlung nicht finden."

MSG_VaSimple_0002 "Typumwandlung fehlgeschlagen."


$set MS_Xm

MSG_Motif_0000 "\nName: %s\nKlasse: %s\n"

MSG_Motif_0001 "Aktion mit der falschen Parameterzahl aufgerufen."


$set MS_XmRenderT

MSG_XmRenderT_0000 "XmNtag kann nicht NULL sein. Wird auf leere Zeichenfolge gesetzt."

MSG_XmRenderT_0001 "Anzeige ist NULL. Kann Schriftart nicht laden."

MSG_XmRenderT_0002 "XmNfontType ungültig. Kann Schriftart nicht laden."

MSG_XmRenderT_0003 "Umwandlung fehlgeschlagen. Kann Schriftart nicht laden."

MSG_XmRenderT_0004 "XmNfontType auf XmAS_IS gesetzt. Kann Schriftart nicht laden."

MSG_XmRenderT_0005 "XmNloadModel ist XmLOAD_IMMEDIATE, aber XmNfont und XmNfontName nicht angegeben.\n\
Kann Schriftart nicht laden."


$set MS_XmSelect

MSG_XmSelect_0000 "Internal error: no selection property context for display"
$ MSG_XmSelect_0000 message is obsolete - DO NOT localize this message.

MSG_XmSelect_0001 "Selection owner returned type INCR property with format != 32"
$ please do not translate INCR.
$ MSG_XmSelect_0001 message is obsolete - DO NOT localize this message.

MSG_XmSelect_0002 "XtGetSelectionRequest called for widget \"%s\" outside of ConvertSelection proc"
$ please do not translate ConvertSelection.
$ MSG_XmSelect_0002 message is obsolete - DO NOT localize this message.


$set MS_XmString

MSG_XmString_0000 "Keine Schriftart gefunden."


$set MS_XmTabList

MSG_XmTabList_0000 "Tabulatorwert kann nicht negativ sein."


$set MS_SSpinB

MSG_SSpinB_0001 "Ressource XmNtextField kann nicht gesetzt werden."

MSG_SSpinB_0002 "Ressource XmNpositionType kann nur während der Erstellung gesetzt werden."

MSG_SSpinB_0003 "Element existiert nicht. XmNposition ist unverändert."
