/* XPM */
/* $XConsortium: audio.pm /main/5 1996/07/23 14:06:07 drk $ */
static char * AudioOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconColor2	m white	c white",
"o	s iconGray1	m white	c #e1e1e1e1e1e1",
"O	s iconGray3	m white	c #afafafafafaf",
"+	s iconGray7	m black	c #4b4b4b4b4b4b",
"@	s iconGray5	m black	c #7d7d7d7d7d7d",
"#	s iconGray8	m black	c #323232323232",
"$	s topShadowColor	m white	c #c8c8c8c8c8c8",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                           ....                                 ",
"                X          .ooo.                                ",
"                OX         .oOOO.                               ",
"                +OX        .O++OO.                              ",
"                 +OX       .X+@OOO.                             ",
"                  +OX      .X++OOOO.                            ",
"                   +OX     .X++XOOOO.                           ",
"                    +OX    .X+@XXOOOO.                          ",
"             XXXX    +OX   .X++XXXOOO........                   ",
"             OOOXXX   +OX  .O+@XXXXOOOOOOOOO..                  ",
"             +++OOOXXX +O  .OO@XXXXXO+OOOOOO#$                  ",
"               ++++OOO  +  .O++XXXXXXXXXXXXXX$                  ",
"                  ++++     .O++OXOXOX+XOXOXO#$                  ",
"                          .XO@+XOXOXO+OXOXOX#$                  ",
"           XXXXXXXXXXXXXX .OO++OXOXOX+XOXOXO#$                  ",
"           OOOOOOOOOOOOOO .XO+@X@X@X@+@X@X@X#$                  ",
"           ++++++++++++++ .OO++@X@X@X+X@X@X@#$                  ",
"                          .XO++X@X@X@+@X@X@X#$                  ",
"                  XXXX    ..O++@X@@@@+@@@@@@#$                  ",
"               XXXXOOO  X  .O++@@@@@@+@@@@@@#$                  ",
"             XXXOOO+++ XO  .O++@@@@@@+@@@@@##$                  ",
"             OOO+++   XO+  .O++@@@@@@+######$$                  ",
"             ++++    XO+   .+++@@@@++#$$$$$$$                   ",
"                    XO+    .+++@@@++#$                          ",
"                   XO+     .+++@@++#$                           ",
"                  XO+      .+++@++#$                            ",
"                 XO+       .+++++#$                             ",
"                XO+        .O+++#$                              ",
"                O+         .O++#$                               ",
"                +          .###$                                ",
"                           .$$$                                 ",
"                                                                ",
"                                                                "};
