/* XPM */
/* $XConsortium: scricon.pm /main/5 1996/07/23 14:08:58 drk $ */
static char * ScreenOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconGray1	m white	c #e1e1e1e1e1e1",
"o	s topShadowColor	m white	c #c8c8c8c8c8c8",
"O	s iconGray3	m white	c #afafafafafaf",
"+	s iconGray7	m black	c #4b4b4b4b4b4b",
"@	s iconColor5	m black	c blue",
"#	s iconColor2	m white	c white",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"           .........................................            ",
"           .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOO+++++++++++++++++++++++++++++++++OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .X++++++++++++++++++++++++++++++++++++++o            ",
"           .oooooooooooooooooooooooooooooooooooooooo            ",
"                                                                ",
"                                                                ",
"                                                                "};
