/* XPM */
/* $XConsortium: startup.pm /main/5 1996/07/23 14:09:31 drk $ */
static char * StartuOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconGray1	m white	c #e1e1e1e1e1e1",
"o	s iconGray5	m black	c #7d7d7d7d7d7d",
"O	s iconColor2	m white	c white",
"+	s iconGray8	m black	c #323232323232",
"@	s iconGray7	m black	c #4b4b4b4b4b4b",
"#	s iconColor1	m black	c black",
"$	s topShadowColor	m white	c #c8c8c8c8c8c8",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"         ...............                                        ",
"        .XXXXXXXXXXXXXXX.                                       ",
"       .XXoXoXoXoXoXoXoXo.                                      ",
"      .XoXoXoXoXoXoXoXoXoo............................          ",
"      .XoXoXoXoXoXoXoXoXooOOOOOOOOOOOOOOOOOOOOOOOOOOOO.         ",
"      .Xo+++++oXoXoXoXoXoo++++++++++++++++++++++++@++++.        ",
"      .Xo+   XoXoXoXoXoXooXXXXOOXXXXXXXOOXXXXXXXXOOOXXX.        ",
"      .Xo+   XoXoXoXoXoXoo#######################++++++.        ",
"      .Xo+   XoXoXoXoXoXooXXXXXXXXXXXXXXXXXXXXXXXXXXX$$         ",
"      .Xo+   XoXoXoXoXoXooXXOOOXOOOOOXXOO++XXO++OX++$$          ",
"      .Xo+   XoXoXoXoXoXooXXO++OOO+++OOO+$+OO++$+O+$$           ",
"      .Xo+   XoXoXoXoXoXooXO++++O++$$+++$ $++$$ $$$$            ",
"      .Xo+   XoXoXoXoXoXooO++$$+++$ $$$$   $$                   ",
"      .Xo+XXXXoXoXoXoXoXo+++$  $$$                              ",
"      .XoXoXoXoXoXoXoXoXo+$$                                    ",
"      .XoXoXoXoXoXoXoXoXo+$                                     ",
"       .oXoXoXoXoXoXoXoXo+$                                     ",
"        $++++++++++++++++$                                      ",
"         $$$$$$$$$$$$$$$$                                       ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "};
