/* XPM */
/* $XConsortium: winmgr.pm /main/5 1996/07/23 14:09:56 drk $ */
static char * Vuewm [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconGray1	m white	c #e1e1e1e1e1e1",
"o	s topShadowColor	m white	c #c8c8c8c8c8c8",
"O	s iconGray8	m black	c #323232323232",
"+	s iconGray3	m white	c #afafafafafaf",
"@	s iconGray5	m black	c #7d7d7d7d7d7d",
/* pixels */
"                                                                ",
"                                                                ",
"  ............................................................  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++OOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo  ",
"  .XX++++OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo   ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++++++o   ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++++o    ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++++o    ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++XXXXXXXX++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++X++++++O++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++X++++++O++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++XOOOOOOO++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OXOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOo       ",
"  .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo        ",
"  .XXXXXXXO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o        ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o        ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .oooooooooooooooooooooooooooooooooooooooooooooooooooo         ",
"                                                                ",
"                                                                ",
"                                                                "};
