$ $XConsortium: Message.msg /main/6 1996/10/31 10:31:28 cde-hal $

$set	Set_Messages
$ 
$ dtinfo general messages
$ 
$ 
$ Dtinfo*PixmapAllocationError
$ 
1	"There is not enough Server memory\n\
available to render the graphic."
$ 
$ Dtinfo*AbandonChanges
$ 
2	"Abandon changes?"
$ 
$ Dtinfo*NoHelp
$ 
3	"The help information cannot be found."
$ 
$ Dtinfo*NoSelection
$ 
4	"There is no text selected.\n\
Select some text, then try again."
$ 
$ Dtinfo*AbandonBookmarks
$ 
5	"There are unsaved bookmarks open.\n\
Quit without saving them?"
$ 
$ Dtinfo*ConfirmQuit
$ 
6	"Quit Dtinfo?"
$ 
$ Dtinfo*BadTocHierarchy
$ 
7	"File a Bug"
$ 
$ Dtinfo*LinkToBookTitle
$ 
8	"Link to %s: %s"
$ 
$ Dtinfo*LinkToTitle
$ 
9	"Link to %s"
$ 
$ Dtinfo*MarkCreateFailed
$ 
10	"Dtinfo is unable to create this bookmark."
$ 
$ Dtinfo*MarkDeleteFailed
$ 
11	"Dtinfo is unable to delete this bookmark."
$ 
$ Dtinfo*MarkMoveFailed
$ 
12	"Dtinfo is unable to remove this bookmark."
$ 
$ Dtinfo*MaxDepthExceeded
$ 
13	"File a Bug"
$ 
$ Dtinfo*MarkIconInvisible
$ 
14	"The bookmark selected cannot be displayed.\n\
It is outside the viewable region of this section."
$ 
$ Dtinfo*MViewNoBase
$ 
15	"The mark selected is not\n\
in an accessible document.\n\
Load the appropriate Infolib."
$ 
$ Dtinfo*GetGeometry
$ 
16	"Click inside a Dtinfo window that has\n\
the size to be saved as the default."
$ 
$ Dtinfo*SaveModifiedScope
$ 
17	"Save changes to the current scope?"
$ 
$ Dtinfo*BadScopeName
$ 
18	"The characters colon (:), comma (,),\n\
and semicolon (;) are not allowed\n\
in a search scope name."
$ 
$ Dtinfo*EmptyScopeName
$ 
19	"Please enter a valid scope name."
$ 
$ Dtinfo*ScopeNameTooLong
$ 
20	"A search scope name may not exceed 30 characters.\n\
Please enter a shorter scope name."
$ 
$ Dtinfo*DuplicateScopeName
$ 
21	"The name you entered is already in use.\n\
Please enter a unique scope name."
$ 
$ Dtinfo*Everything
$	22	"Everything" refers to section components like
$		titles, body, and related.
$ 
22	"Everything"
$ 
$ Dtinfo*Titles
$ 
23	"Titles"
$ 
$ Dtinfo*Body
$	24	"Body" as in the body of text.
$ 
24	"Body"
$ 
$ Dtinfo*Examples
$ 
25	"Examples"
$ 
$ Dtinfo*Index
$ 
26	"Index"
$ 
$ Dtinfo*Tables
$ 
27	"Tables"
$ 
$ Dtinfo*Graphics
$ 
28	"Graphics"
$ 
$ Dtinfo*ScopeDeleteConfirm
$ 
29	"Delete the displayed scope?"
$ 
$ Dtinfo*CurrentSection
$ 
30	"Current Section"
$ 
$ Dtinfo*IgnoredScopes
$ 
31	"Ignoring saved scopes that aren't\n\
valid for this Infolib(s)."
$ 
$ Dtinfo*MarkBaseOpenFailed
$ 
32	"Cannot open the user marks database."
$ 
$ Dtinfo*NoOpenMarkBases
$ 
33	"Dtinfo marks database was not found.\n\
Dtinfo cannot create a bookmark."
$ 
$ Dtinfo*MarkBaseReadOnly
$ 
34	"The current marks database has read-only permissions."
$ 
35	"Unknown error in document: Please notify product support."

36	"An unexpected message was received from the\n\
search engine (in UAS_SearchEngine):\n\
Please notify product support."
$ 
$ Dtinfo*TooManyIbases
$ 
37	"Due to a search engine limitation only the first %d\n\
bookcases in the current scope may be searched.\n\
Continue?"
$ 
$ Dtinfo*DemoFailure
$ 
38	"This is an Evaluation Version of the Browser.\n\
There is no permission to access this Infolib."
$ 
$ Dtinfo*StyleSheetSyntaxError
$ 
39	"There is an error in the Style Sheet for this document.\n\
Default features have been applied."
$ 
$ Dtinfo*NoHits
$ 
40	"No matches were found for this query."
$ 
$ Dtinfo*BadQuery
$ 
41	"Dtinfo does not understand the query. \n\
Please enter a valid query."
$ 
$ Dtinfo*SearchError
$ 
42	"An internal search engine error has been detected. All\n\
subsequent searching will fail for this Browser session.\n\n\
This problem has been logged and will be fixed in a later\n\
release of the Browser. As a temporary workaround, try to\n\
avoid entering queries that cause this condition to occur.\n\
To re-enable searching, quit and restart the Browser."
$ 
$ Dtinfo*KernelError
$ 
43	"An internal search engine error has been detected.\n\
It's likely that this machine's /usr/tmp directory\n\
is on (or links to) a tmpfs filesystem. All subsequent\n\
searching will fail for this Browser session.\n\n\
This problem is known and has been logged. A workaround\n\
is to reconfigure the /usr/tmp directory on this machine\n\
so that it is not on (or linked to) a tmpfs filesystem.\n\
After do so and restarting the Browser, searching should\n\
be re-enabled and work properly. For more information see\n\
a system administrator."
$ 
$ Dtinfo*FulcrumNoMemory
$ 
44	"The search engine was unable to complete your search request\n\
because it could not allocate memory. Before attempting to\n\
search again try quitting other applications, or increase\n\
the system's physical or virtual memory."
$ 
$ Dtinfo*FulcrumError
$ 
45	"A Search Engine error has occurred. \n\
Please report Search Error %d to Product Support."
$ 
$ Dtinfo*BadHelp
$ 
46	"This button links to an Dtinfo document which is\n\
not present in the currently loaded Infolib(s)."
$ 
$ Dtinfo*query_is_read_only
$ 
47	"This is a display-only field.  To edit the query\n\
use the Query Editor or the quick search field in\n\
the Reading window or Booklist window."
$ 
$ Dtinfo*ExceedRdWindows
$ 
48	"The maximum number of active reading windows (%d)\n\
as set under User Preferences is already reached."
$ 
$ Dtinfo*NoPrefBase
$ 
49	"There is no User Preference Database available."
$ 
$ Dtinfo*PrefBaseReadOnly
$ 
50	"The User Preference Database has been opened in\n\
read-only mode. No new preferences can be saved to disk."
$ 
$ Dtinfo*DeadEndLink
$ 
51	"The document or section requested is not available."
$ 
$ Dtinfo*MarkPositionFailed
$ 
52	"Dtinfo cannot display the mark named\n\
\42%s\42\n\
because the paragraph it was associated with\n\
no longer exists."
$ 
$ Dtinfo*ScopeChangeAbandon
$ 
53	"Abandon changes to the current scope?"
$ 
$ Dtinfo*InformationLibrary
$ 
63	"Information Library"
$ 
$ Dtinfo*On
$ 
64	"On"
$ 
$ Dtinfo*Off
$ 
65	"Off"
$ 
67	"Could not create the Infolib."

68	"Infolib creation failed."
$ 
69	"Search result weighting is not available."

$	70	The "qualified locator" is a "fully qualified
$		locator" as opposed to the simple format.
70	"Invalid access method in qualified locator (URL)."

71	"Document creation failed."

72	"Dtinfo: Detach Graphic"
73	"Click on a graphic to detach it."
