$ $XConsortium: dtscreen.msg /main/3 1995/11/08 11:55:29 rswiston $
$ @(#)25\t1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37 
$  
$ COMPONENT_NAME: dtscreen 
$  
$ FUNCTIONS: dtscreen.msg 
$  
$  
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993 
$ All Rights Reserved 
$ Licensed Materials - Property of IBM 
$  
$ US Government Users Restricted Rights - Use, duplication or 
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp. 
$  
$  

$quote "

$set 2        Define initial set#

$ message file created 1993 

1 "1386-101 %s:  ungültige Befehlszeilenoption \"%s\"\n\n\
"

2 "1386-102 \n\
%s -help für eine vollständige Beschreibung eingeben.\n\n\
"

3 "1386-103 Verwendung:\n\
        %s [-optionen ...]\n\n\
\t Mögliche Optionen:\n\
"

5 "1386-105    %-28s %s\n\
\t verfügbare Modi:\n\
\", \"-mode mode\", \"animation mode"

7 "1386-107 Unbekannter Modus: "

10 "1386-110 %s konnte nicht zugeordnet werden\n\
"

11 "1386-111 %d Pixel zugeordnet\n\
"

17 "1386-117 %s: Anzeige %s kann nicht geöffnet werden.\n\
"

18 "1386-118 %s: GetResource - es konnte kein Speicher zugeordnet werden"

19 "1386-119 %s: Ungültiges Argument für -display: \"%s\"\n\
"

20 "1386-120 Argument für -batchcount muß positiv sein."

21 "1386-121 Argument für -saturation muß zwischen 0.0 und 1.0 liegen."

25 "1386-125 %s: es können nur %d Anzeigen untersützt werden.\n\
"

30 "1386-130 Argument für -delay muß positiv sein."

35 "1386-135 %s konnte nicht zugeordnet werden; Verwendung von: %s\n\
"

40 "%s: Fenster, in dem gezeichnet werden soll, kann nicht gefunden werden. \n\
        Bei Angabe der Option -create erstellt %s ein eigenes Fenster.\n\
"
