$ $XConsortium: dttypes.msg /main/2 1996/07/24 18:27:55 drk $
$quote "

$set 1

1 "Dttype"
$ Do not Translate  

2 "Dttype"
$ Do not Translate  

3 "Initialisierung unvollständig\n"

4 "NULL"
$ this should mean a "Empty string".  

5 "=============== %s ===============\n"
$ Do not Translate  

6 "\0"
$ Do not Translate  

7 "%s\n"
$ Do not Translate  

8 ""
$ Do not Translate  

9 "geladen von %s\n"

10 "Unbekannt"

11 "\t%s"
$ Do not Translate  

12 "\0"
$ Do not Translate  

13 " :\t%s"
$ Do not Translate  

14 "\0"
$ Do not Translate  

15 "\n"
$ Do not Translate  

16 "-db"
$ Do not Translate  

17 "-w"
$ Do not Translate  

18 "-l"
$ Do not Translate  

19 "rec_info"
$ Do not Translate  

20 "rec_name"
$ Do not Translate  

21 "fld_name"
$ Do not Translate  

22 "fld_value"
$ Do not Translate  

23 "all"
$ Do not Translate  

24 "Fehler = %o, %s\n"
$ Translate "error" only  

25 "Verwendung:  dttypes [-help]\n\
\tdttypes [-type Dateiname]\n\
\tdttypes [-db Datenbank] [-w [rec_name reg_Ausdruck] [fld_name reg_Ausdruck]\n\
\t\t\t[fld_value reg_Ausdruck]]\n\
\t\t[-l [rec_name] [rec_info] [fld_name reg_Ausdruck] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"  

26 "-type"
$ Do not Translate  

27 "%s ist vom Typ %s\n"

28 "$"
$ Do not Translate  

29 "--------------------- %s ----------------\n"
$ Do not Translate  

30 "Ungültige Datenbank\n"

31 "Kein gültiges Argument\n"

32 "Ungültiges Feld rec_info bei Option -w\n"
$ do not translate "rec_info" or "-w"  

33 "Nicht bei Option -w oder -l\n"
$ do not translate "-w" or "-l"  

34 "Unbekannte Option\n"

35 "-help"
$ Do not Translate  

36 "Fehler in regulärem Ausdruck %s\n"
