$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 BDF-Dateiauswahl
4 Die ausgewählte Datei existiert. Überschreiben?
6 Konnte ausgewählte Datei nicht öffnen.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 Diese Schriftart hat keine benutzerdefinierten Zeichen.
4 Konnte ausgewählte Schriftart nicht öffnen. Sie haben kein Zugriffsrecht auf die Schriftartdatei, oder das Format der Datei ist nicht korrekt.
6 Die Schriftartdatei wird gerade von einer anderen UDC-Anwendung benutzt.
8 Keine Schriftart vorhanden.
10 Öffnen
12 Abbrechen
14 Dienstprogramm UDC-Datenaustausch
16 SelectItems
18 - Code-Set:
20 -   Stil:
22 -   Breite:
24 -  Höhe:

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 Möchten Sie den UDC-Datenaustausch beenden?
4 Es existieren keine UDCs in dieser Schriftart.
6 XLFD-Name wurde nicht ausgewählt.
8 Kann Schriftartdatei nicht öffnen.
10 Die Schriftartdatei wird gerade von einer anderen UDC-Anwendung benutzt.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 Dienstprogramm UDC-Datenaustausch
4 Schwerwiegender Fehler.
6 Kann Schriftartdatei nicht öffnen.
8 Kann Schriftartdatei nicht lesen.
10 Kein Speicher mehr!
12 Schwerwiegender Fehler.
14 Die angegebene Schriftartdatei existiert nicht.
16 Diese Schriftart ist keine pcf- oder snf-Schriftart.
18 Kann Datei fonts.list nicht öffnen.
20 Das Format der Datei fonts.list ist nicht korrekt.
22 Die Beschreibungen der Datei fonts.list sind nicht korrekt.
24 Das Format der Datei fonts.list ist nicht korrekt.
26 Kann Datei fonts.dir nicht öffnen.
28 Kann Datei fonts.dir nicht lesen.
30 Kann die Schriftart-Eigenschaften nicht lesen.
32 Kann die Eigenschaft FONT nicht holen.
34 Kann die Eigenschaft FAMILY_NAME nicht holen.
36 Diese Schriftartdatei wird bereits von einer anderen Anwendung benutzt.
38 Kann die Schriftartdatei nicht sperren.
40 Kann die Schriftartdatei nicht entsperren.
42 Kann keine Sperrinformationen von der Schriftartdatei holen.
44 Kann die angegebene Schriftartdatei nicht finden.
46 Kann die NLS-Datenbank nicht lesen.
48 Kann keine charset-Namen von der NLS-Datenbank holen.
50 Der charset-Name ist nicht in der NLS-Datenbank definiert.
52 Die angegebene Schriftart wurde nicht geöffnet.
54 Schwerwiegender Fehler.
56 XLFD-Name          :
58 Ursprüngliche Schriftart (XLFD-Name)  :
60 UDC-Codebereich      :
62 Stil              :
64 Größe (Buchstabengröße) :
66 Öffnen
68 Abbrechen
70 OK
72 abbrechen
74 Ursprungscode(hex) kopieren  :
76 Zielcode(hex) kopieren :
78 Kopieren
80 Überlagern
82 Funktion Exportieren
84 Funktion Importieren
86 Abbrechen

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Konnte BDF-Datei nicht erstellen.
4 Keine Indexe ausgewählt.
6 OK
8 Abbrechen
10 Glyphen-Index

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Glyphenabbilder in dieser BDF-Datei können der Schriftart nicht hinzugefügt werden.
4 Konnte die ausgewählte BDF-Schriftart nicht öffnen. Sie haben kein Zugriffsrecht auf die Schriftartdatei, oder das Dateiformat ist nicht korrekt.
6 Ein oder mehrere Glyphenabbilder werden überschrieben. Überschreiben?
8 Konnte ausgewählte Schriftart nicht öffnen. Sie haben kein Zugriffsrecht auf die Schriftartdatei, oder das Dateiformat ist nicht korrekt.
10 Glyphenabbilder in dieser BDF-Datei können der Schriftart nicht hinzugefügt werden.
12 Registrierung der Schriftartdatei fehlgeschlagen.
