$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcfonted.msg
$ **
$ **  Project:     Fujitsu DT UDC Font Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcfonted
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **
$set 2
$ *****************************************************************************
$ ** _DtMessage set for ufont.c
$ *****************************************************************************

$ This is footer message when registration of the character.
2 Registrierung wird intern bearbeitet.

$ Message4-8 are error messages when registration of the character.
4 Registrierung des Zeichens fehlgeschlagen.
6 Ungültiger Code.
8 Da Speicherzuteilung nicht durchführbar ist, ist das Hinzufügen nicht möglich.

$ Message10-16 are error messages when copying of the character.
10 Es existiert kein Zeichen des angegebenen Codes.
12 Der Fehler findet sich im angegebenen Kopierursprungs-Code.
14 Der Fehler findet sich im angegebenen Kopierziel-Code.
16 Es existiert kein Zeichen im angegebenen Bereich.

$ This is footer message.
18 Bitte einen Moment warten.

$ This is error message when copying of the character.
20 Keine Kopierursprungs-Codedatei angegeben.

$ Message22-24 are error message of user defined character
22 Informationen zum benutzerdefinierten Zeichen können nicht gesammelt werden.\nKeine Schriftart angegeben.
24 Informationen zum benutzerdefinierten Zeichen können nicht gesammelt werden.\nMehrere Schriftarten angegeben.

$ UDC is User Defined Character.
26 Die angegebene Schriftart hat keine UDC-Bereiche.

28 Kein Speicher mehr!
30 Die Informationen im UDC-Bereich sind ungültig.
32 Die Schriftartdatei kann nicht lesen.\nDer Musterbereich ist defekt.

$ Dtudcfonted is the name of this application.
34 Dtudcfonted kann keine proportionale Zeichenschriftart bearbeiten.

36 Es existieren ungespeicherte Bearbeitungen.\nMöchten Sie sie vor dem Öffnen speichern?
38 Es existieren ungespeicherte Bearbeitungen.\nMöchten Sie sie vor dem Beenden speichern?
40 Nach Beendigung des Kopiervorgangs ist die Glyphenabbildung\n innerhalb der folgenden Bereiche verändert.\nMöchten Sie den Kopiervorgang durchführen?\n\n
42 Kein Schreibrecht für diese Schriftart. Sie sollten den Dateizugriffsmodus vor dem Speichern verändern.\n

$ There are user-visible labels in font-open dialog.
100 Elemente auswählen
102 -        Code-Set:
104 -          Stil:
106 -          Breite:
108 -         Höhe:
110 Öffnen
112 Beenden

$ There are user-visible labels in menubar.
114 Schriftart
116 Bearbeiten
118 Zeichen
120 Informationen

$ There are user-visible labels in File menu.
122 Öffnen...
124 Speichern
126 Beenden

$ There are user-visible labels in Edit menu.
$ Message135 is copy of cut&copy
128 Löschen
130 Ausfüllen
132 Umkehren
134 Ausschneiden
135 Kopieren
136 Einfügen
138 Drehen
140 Umblättern (Vertikal)
142 Umblättern (Horizontal)
144 Rückgängig

$ There are user-visible labels in Character menu.
$ Message148 is copy of character
146 Hinzufügen/Löschen...
148 Kopieren...

$ There are user-visible labels in Information menu.
150 XLFD-Name...
152 Code-Bereich...

$ There are user-visible labels in add/delete dialog.
154 Hinzufügen
156 Löschen
158 Abbrechen

$ There are user-visible labels in copy dialog.
$ Message166 is label of execute button
160 Code(hex):
162 Kopierursprungs-Code(hex):
164 Kopierziel-Code(hex):
166 Kopieren
168 Überlagern
170 OK

$ There are user-visible labels in unsaved edits.
172 Speichern
174 Nicht speichern
176 Speichern und Beenden
178 Ohne Speichern beenden

$ There are user-visible labels in delete notice dialog.
$ This format is `Message180 (?? Message182)' and `Message184 (?? Message186)'.
$ These Message180 and Message182 are used in only one character.
$ These Message184 and Message186 are used in plural characters.
180 Das folgende Zeichen wird gelöscht.
182 Zeichen
184 Die folgenden Zeichen werden gelöscht.
186 Zeichen
188 Registrierung beendet.
190 Code :
192 Code-Bereich :

$ There are footer message label.
194 Meldung :

$ There are user-visible labels in code dialog.
196 Code...
198 Letzte Seite
200 Nächste Seite
202 Anwenden

$ There are title.
204 Benutzerdefiniertes Zeichen-Editor: Frage
206 Benutzerdefiniertes Zeichen-Editor: Warnung
208 Benutzerdefiniertes Zeichen-Editor: Fehler

$ There are error message of libfal.
300 Schwerwiegender Fehler.
301 Kann Schriftartdatei nicht öffnen.
302 Kann Schriftartdatei nicht lesen.
303 Kein Speicher mehr.
304 Schwerwiegender Fehler.
305 Die angegebene Schriftartdatei existiert nicht.
306 Diese Schriftart ist keine pcf- oder snf-Schriftart.
307 Kann Datei fonts.list nicht öffnen.
308 Das Format der Datei fonts.list ist ungültig.
309 Die Beschreibungen der Datei fonts.list sind nicht korrekt.
310 Das Format der Datei fonts.list ist ungültig.
311 Kann Datei fonts.dir nicht öffnen.
312 Kann Datei fonts.dir nicht lesen.
313 Kann Schriftart-Eigenschaften nicht lesen.
314 Kann Eigenschaft FONT nicht holen.
315 Kann Eigenschaft FAMILY_NAME nicht holen.
316 Diese Schriftartdatei wurde bereits von einer anderen Anwendung geöffnet.
317 Kann Schriftartdatei nicht sperren.
318 Kann Schriftartdatei nicht entsperren.
319 Kann keine Sperrinformationen von der Schriftartdatei holen.
320 Kann die angegebene Schriftartdatei nicht finden.
321 Kann die NLS-Datenbank nicht lesen.
322 Kann keine charset-Namen von der NLS-Datenbank holen.
323 Charset-Name nicht in NLS-Datenbank definiert.
324 Die angegebene Schriftart wurde noch nicht geöffnet.
325 Schwerwiegender Fehler.
