$   
$ +SNOTICE  
$   
$  $XConsortium: MotifApp.msg /main/5 1996/10/19 14:26:20 rws $  
$   
$  RESTRICTED CONFIDENTIAL INFORMATION:  
$   
$  The information in this document is subject to special  
$  restrictions in a confidential disclosure agreement between  
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this  
$  document outside HP, IBM, Sun, USL, SCO, or Univel without  
$  Sun's specific written approval.  This document and all copies  
$  and derivative works thereof must be returned or destroyed at  
$  Sun's request.  
$   
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.  
$   
$ +ENOTICE  
$   

$quote "

$set 1
1 "Soll dieser Befehl wirklich ausgeführt werden?"
2 "OK"
3 "Abbruch"
4 "DtMail Version Dialog"
5 "DtMail Version Dialog"
6 "Eine Komponente innerhalb der Anwendung auswählen.\n"
7 "DtMail Hilfe"
8 "DtMail Hilfe"
9 "Diesen Ordner Schließen?"
10 "Dieser Befehl kann nicht offen bleiben. Trotzdem fortfahren?"

11 "Verborgene Ordner und Dateien zeigen"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "Post : Hilfe"

$set 2        Redefine set#
1 "Auswahlfehler, Fortfahren nicht möglich\n"
2 "Auswahl durch Benutzer abgebrochen.\n"
