$ $XConsortium: Mrm.msg /main/3 1996/10/19 15:28:17 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 
$ (c) Copyright 1996 Digital Equipment Corporation.
$ (c) Copyright 1996 Hewlett-Packard Company.
$ (c) Copyright 1996 International Business Machines Corp.
$ (c) Copyright 1996 Sun Microsystems, Inc.
$ (c) Copyright 1996 Novell, Inc. 
$ (c) Copyright 1996 FUJITSU LIMITED.
$ (c) Copyright 1996 Hitachi.
$ 

$ This message catalog contains messages issued by Motif Mrm library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.
 
$quote "

$set MS_Mrm

MSG__0000 "L'allocation du vecteur n'a pas abouti"

MSG__0001 "L'allocation du tampon n'a pas abouti"

MSG__0002 "Tampon incorrect"

MSG__0003 "Impossible d'obtenir le bloc"

MSG__0004 "Impossible de poser le bloc"

MSG__0005 "En-tête d'enregistrement incorrect"

MSG__0006 "Contexte incorrect"

MSG__0007 "Entrée incorrecte"

MSG__0008 "Segment incorrect"

MSG__0009 "Type de données inconnu"

MSG__0010 "Type d'enregistrement inattendu"

MSG__0011 "La version du fichier %s est supérieure à la version Mrm %s."

MSG__0012 "Ce n'est pas un enregistrement d'en-tête."

MSG__0013 "L'index de ressource est hors limites"

MSG__0014 "Le pointeur de données est NULL"

MSG__0015 "Enregistrement de débordement illégal"

MSG__0016 "Incompatiblité d'enregistrement GT"

MSG__0017 " Incompatiblité d'enregistrement LT"

MSG__0018 "Le type d'enregistrement du parent est inattendu"

MSG__0019 "Enregistrement au-delà de EOF"

MSG__0020 "Impossible d'échanger l'enregistrement #%d type %d"

MSG__0021 "Le type %d détecté n'est pas généré, dans l'élément Callback %d"

MSG__0022 "Le type %d d'argument détecté n'est pas généré"

MSG__0023 "L'id de la hiérachie est NULL"

MSG__0024 "Hiérarchie incorrecte"

MSG__0025 "Module de l'interface incorrect"

MSG__0026 "Enregistrement du widget incorrect"

MSG__0027 "L'allocation du contexte n'a pas abouti"

MSG__0028 "La validation a échoué"

MSG__0029 "La ressource est trop grande"

MSG__0030 "L'écran n'a pas été ouvert"

MSG__0031 "Impossible d'ouvrir le fichier %s"

MSG__0032 " Impossible d'ouvrir le fichier %s - La version du fichier UID est incompatible"

MSG__0033 "XmGetPixmap a échoué avec XmUNSPECIFIED_PIXMAP pour %s"

MSG__0034 "XCreateImage a échoué lors de la conversion d'IconImage"

MSG__0035 "XCreatePixmap a échoué lors de la conversion d'IconImage "

MSG__0036 "XCreateGC a échoué lors de la conversion d'IconImage "

MSG__0037 "XtMalloc a échoué lors de la conversion d'IconImage "

MSG__0038 "Impossible de charger la couleur '%s'"

MSG__0039 "Impossible de convertir couleur/pixel RGB '%d,%d,%d'"

MSG__0040 "Type de descripteur de couleur incorrect"

MSG__0041 "L'état monochrome de l'élément couleur %d est illégal"

MSG__0042 "Impossible de trouver la constante '%s'"
$ literal in this context means a named value.

MSG__0043 "Le contexte de la ressource est incorrect"

MSG__0044 "Trop de widgets"

MSG__0045 "L'index supérieur est hors limites."

MSG__0046 "L'allocation de la liste n'a pas abouti"

MSG__0047 "L'allocation du vecteur de la liste n'a pas abouti"

MSG__0048 "La re-allocation du vecteur n'a pas abouti"

MSG__0049 "L'allocation de la chaîne n'a pas abouti"

MSG__0050 "Le fichier UID est périmé - il n'a pas de table de compression"

MSG__0051 "Impossible de trouver un descripteur pour la classe %s"

MSG__0052 "Impossible de trouver le widget indexé '%s'"

MSG__0053 " Impossible de trouver le widget RID '%x'"

MSG__0054 "?? Type de clé %d INCONNU"

MSG__0055 "Type de widget inconnu"

MSG__0056 "La référence Widget non résolue au cours de l'appel "

MSG__0057 "Impossible de Fixup les appels de création"

MSG__0058 "Type d'enfant inconnu"

MSG__0059 "Enfant de parent introuvable"

MSG__0060 "La référence Widget n'est pas indexée"


MSG__0061 "Impossible de convertir couleur/pixel '%s'"

MSG__0062 "Impossible de comprimer le code de la chaîne %d"

MSG__0063 "Groupe de ressource non traité"

MSG__0064 "Impossible de convertir ASCIZ '%s' en chaîne composée"

MSG__0065 "Impossible d'analyser la table de traduction '%s'"

MSG__0066 "Impossible de convertir l'identificateur '%s'"

MSG__0067 "Erreur interne : cas MrmRtypeIconImage détecté"

MSG__0068 " Erreur interne : cas MrmRtypeXBitmapFile détecté"

MSG__0069 " Erreur interne : Impossible de convertir Display en String"

MSG__0070 "Impossible de convertir la police '%s'"

MSG__0071 "Impossible de convertir fontset '%s'"
$ please do not translate fontset.

MSG__0072 "Impossible d'onvrir une ou plusieurs polices pour fontset '%s'"

MSG__0073 "Impossible d'ajouter la police de la liste de polices '%s' à la liste"

MSG__0074 "Impossible d'ajouter fontset de la liste de polices '%s' à la liste"

MSG__0075 "Impossible de convertir l'enregistrement de classe '%s'"

MSG__0076 "Impossible de convertir la chaîne keysym '%s' en KeySym"

MSG__0077 "Impossible de trouver la constante indexée '%s'"

MSG__0078 "Impossible de trouver la constante RID '%x'"

MSG__0079 "Type de clé constante %d inconnu"

MSG__0080 "Type de constante de ColorTable %d incorrect"

MSG__0081 "Code de type ColorTable %d incorrect"

MSG__0082 "Type de constante Color %d incorrect"

MSG__0083 "Code de type ColorItem %d incorrect"

MSG__0084 "la routine Callback '%s' n'est pas enregistrée"

MSG__0085 "La référence Widget n'est pas indexée"

MSG__0086 "Impossible de trouver la resssource de widget indexé '%s'"

MSG__0087 "Impossible de trouver la ressource widget RID '%x'"

MSG__0088 "Type de clé de ressource %d inconnu"

MSG__0089 "Impossible d'instancier l'arbre widget"

MSG__0090 "La valeur du nom de classe définie par l'utilisateur est Null "

MSG__0091 "Code de classe incorrect"

MSG__0092 "Trop d'arguments"

MSG__0093 "Code de compression incorrect"

MSG__0094 "Type non traité ou incorrect"

MSG__0095 "Vecteur trop grand"

MSG__0096 "Nom de routine vide"

MSG__0097 "Char8Vector n'est pas encore mis en oeuvre"

MSG__0098 "CStringVector n'est pas encore mis en oeuvre "

MSG__0099 "Trop d'enfants"

MSG__0100 "Le descripteur de la liste d'enfants a une valeur Null "

MSG__0101 "L'index d'enfant est hors limites"

MSG__0102 "L'index est Null"

MSG__0103 "Type de clé incorrect"

MSG__0104 "l'index Arg est hors limites"

MSG__0105 "L'enregistrement de widget/gadget est incorrect"

MSG__0106 "Le descripteur d'appels est incorrect"

MSG__0107 "L'index d'éléments d'appels est hors limites"

MSG__0108 "Impossible de compresser le code de chaîne %d"

MSG__0109 "Trop d'éléments"

MSG__0110 "Impossible de convertir la chaîne multioctet en chaîne caractère large"

MSG__0111 "Impossible de convertir l'entier '%d' en icône"

MSG__0112 "Impossible de convertir en icône"

MSG__0113 "Impossible d'ouvrir le tampon - version UID incompatible"

MSG__0114 " Impossible d'ouvrir le tampon "

MSG__0115 "Impossible de convertir les unités en XmPIXELS: format ou type d'unités incorrect"

MSG__0116 " Impossible de convertir les unités en XmPIXELS : débordement de la virgule flottante"

MSG__0117 "Chaîne de version %s incorrecte dans le fichier UID. Lecture du fichier impossible."

MSG__0118 "La version %s Mrm est supérieure à la version %s du fichier ;\nrecompilez le fichier UIL."

MSG__0119 "L'object '%s' est déclaré PRIVATE."

