$ $XConsortium: Uil.msg /main/3 1996/10/19 15:28:20 rws $

$quote "

$set UIL_SET1


UIL_0 "l'option en double \"%s\" a été ignorée"

UIL_1 "l'option inconnue \"%s\" a été ignorée"

UIL_2 "le fichier source UIL supplémentaire : %s a été ignoré"

UIL_3 "erreur d'ouverture du fichier source: %s"

UIL_4 "erreur de lecture de la ligne suivante du fichier source : %s"

UIL_5 "Erreur interne : %s"

UIL_6 "ligne tronquée aux caractères %d"

UIL_7 "la valeur de %s est hors de la plage %s"

UIL_8 "%s pas terminé %s"

UIL_9 "le caractère \\%d\\ impossible à imprimer est ignoré"

UIL_10 "la séquence inconnue \"%s\" est ignorée"

UIL_11 "la séquence d'échappement inconnue \"\\%c\" - \\ est ignorée"

UIL_12 "le nom a plus de %d caractères - tronqué à: %s"

UIL_13 "la mémoire virtuelle du compilateur est épuisée"

UIL_14 "jeton %s inattendu - analyse recommencée après \"%c\""

UIL_15 "%s %s doit être défini avant cette référence"

UIL_16 "le contexte exige un %s - %s a été spécifié"

UIL_17 "%s n'est pas encore mis en oeuvre"

UIL_18 "la valeur %s a été trouvée mais la valeur %s était attendue"

UIL_19 "le %s %s n'est pas pris en charge pour l'objet %s"

UIL_20 " %s %s annule la définition précédente dans ce %s %s"

UIL_21 "le nom %s a été défini antérieurement par %s"

UIL_22 "la valeur utilisée dans ce contexte doit être privée"

UIL_23 "Vous avez déclaré la procédure %s antérieurement avec les arguments %d"

UIL_24 "La valeur trouvée est de %s - les arguments de la procédure %s doivent avoir la valeur de %s"

UIL_25 " %s %s a été trouvée mais %s %s était attendue"

UIL_26 "%s %s pas défini"

UIL_27 "%s %s déjà spécifié pour ce %s %s"

UIL_28 " l'élément %s n'est pas autorisé dans %s %s"

UIL_29 "compilation complète - rectifiez les erreurs précédentes"

UIL_30 "erreur interne - établissez un rapport des erreurs"

UIL_31  

UIL_32 "%s est absent après l'option \"%s\""

UIL_33 "erreur d'ouverture du fichier de listage : %s"

UIL_34 " erreur d'écriture du fichier de listage: %s"

UIL_35 "structure de module incorrecte - vérifiez la syntaxe du module UIL"

UIL_36 "trop de fichiers source ouverts : %s"

UIL_37 "la ligne source contient un caractère null"

UIL_38 "erreurs : %d  avertissements : %d  informationels : %d"

UIL_39 "erreur d'ouverture du fichier UID : %s"

UIL_40 "aucun fichier UID créé"

UIL_41 "la procédure de création n'est pas prise en charge par le widget % "

UIL_42 " la procédure de création n'est pas autorisée dans une référence widget %s"

UIL_43 " la procédure de création est exigée dans une déclaration widget %s"

UIL_44 "un caractère NULL dans une chaîne n'est pas pris en charge"

UIL_45 "widget %s fait partie d'une définition circulaire"

UIL_46 "aucun fichier source spécifié"

UIL_47 "%s %s ne prend en charge qu'un seul %s %s"

UIL_48 "widget %s ne prend en charge qu'un seul contrôle"

UIL_49 "jeu de caractères inconnu"

UIL_50 "placez la clause de nom avant les autres clauses de module"

UIL_51 "la chaîne de lettre couleur se compose d'un seul caractère"

UIL_52 "La lettre en couleur a déjà été utilisée dans cette table"

UIL_53 "la ligne %d doit être de la même largeur que la ligne 1"

UIL_54 "ligne %d, colonne %d: lettre \"%c\" pas dans la table des couleurs"

UIL_55 "trop de %ss dans %s, la limite est de %d"

UIL_56 "Un sous qualifiant n'est pas autorisé avec un qualifiant négatif"

UIL_57 "le gadget %s n'est pas pris en charge - le widget %s le remplace"

UIL_58 "le type %s est incorrect pour %s"

UIL_59 "la prise en charge de ce caractère sera peut-être interrompue dans une version ultérieure"

UIL_60 "la contrainte %s n'est pas prise en charge dans le %s %s"

UIL_61 "trop d'options \"%s\", la limite est de %d"

UIL_62 "erreur de fermeture du fichier source : %s"

UIL_63 "la valeur %s est une valeur circulaire"

UIL_64 "suppression du nom intégré %s"

UIL_65 "l'argument %s ne prend pas en charge les valeurs énumérées"

UIL_66 " l'argument %s ne prend pas en charge les valeurs énumérées %s"

UIL_67 "$LANG contient un jeu de caractères inconnu"

UIL_68 "la hiérachie des contrôles d'objet %s contient sa propre référence"

UIL_69 "la valeur %s est trop grande pour le tampon du contexte"

UIL_70 "impossible d'utiliser la référence %s avant de l'avoir définie"

UIL_71 "impossible de convertir le type %s en %s"

UIL_72 "%s est incorrect"

UIL_V2_73 "erreur de lecture de la base de données binaire"

UIL_V2_74 "La base de données binaire a été compilée avec une version ultérieure"

UIL_V2_75 "erreur d'ouverture du fichier de base de données : %s"

UIL_V2_76 "erreur d'écriture du fichier UID : %s"

UIL_V2_77 "'%s' est un enregistrement de classe Toolkit inconnu"

UIL_78 "nom de fichier d'inclusion incorrect"

UIL_V2_79 "type d'unités incompatibles avec une opération arithmétique"

UIL_V2_80 "%s utilisé en tant que nom de charset; %s utilisé en tant que composant de charset"


$set UIL_VALUES

UIL_VAL_0 "** erreur **"

UIL_VAL_1 "** inconnu **"


$set UIL_SET_MISC


UIL_INF "Info: "

UIL_WAR "Avertissement: "

UIL_ERR "Erreur: "

UIL_SEV "Grave: "

UIL_MISC_0 "\t\t ligne: %d  fichier: %s"

UIL_MISC_1 "\t\t ligne: %d  position: %d  fichier: %s"
