.\" $XConsortium: dtudcfonted.1 /main/2 1996/10/29 15:41:16 drk $
.\"---
.\"    (c) Copyright 1996 FUJITSU Ltd.
.\"---
.TH dtudcfonted 1X "20 Feb. 1996""
.BH "20 Feb. 1996""
.SH NAME
dtudcfonted - the User Defined Characters (UDCs) Font Editor
.SH SYNOPSIS
dtudcfonted [options]
.SH DESCRIPTION
The UDCs Editor provides the facilities that enable the user to edit
User Defined Characters font.
.P
The UDCs Editor uses lines and geometric shape drawing tools in order
to create new User Defined Character or modify existing ones.
It support PCF (Portable Compoled Formet) and SNF (Server Natural Format)
formats.
.sp .5
.SS Key Supported Tasks
.RS
.P
- Modify size of window.
.P
- Modify location of window.
.P
- Iconify window.
.P
- Edit a User Defined Character or existing icon.
.P
- Save the current font.
.P
- Undo the last operation.
.P
- Cut, copy, and paste areas within the UDCs Editor editing area.
.P
- Rotate selected area.
.P
- Copy User Defined Character.
.RE
.SH OPTIONS
The following options are available from the command line:
.sp 1.5
.BI \-pane_size " pane_size"
.sp .5
This option takes a size of UDCs Editor editing area.
.sp 1.5
.BI \-codepoint
.sp .5
This option specifies code format.
If you do not set this optiton, UDCs editor uses Glyph Index code.
If you do set this optiton, UDCs editor uses Code point code.
.sp 1.5
.SH RETURN VALUE
 Exit values are:
.IP "\f30\fP" .5i
Successful completion.
.IP "\f3>0\fP" .5i
Error condition occurred.
.sp 1.5
.SH EXAMPLES
.IP "dtudcfonted" .5i
Starts the UDCs Editor.
.sp 1.5
.IP NOTE:   .5i
UDCs Editor uses with root user.
.sp 1.5
.SH FILES
Files used by this component.
.IP "/.../dt/app-defaults/C/Dtudcfonted       App-defaults file. " .5i
.IP "/.../dt/app-defaults/ja_JP/Dtudcfonted   App-defaults file. " .5i
