#! /bin/ksh
# This script checks to see if the system release is OK and the compiler
# is OK on hpux.

RELEASE=`uname -r|fgrep '9.05' 2>/dev/null`

if [ ! "$RELEASE" ];then
	echo "	System Release Incorrect. uname -r should be 9.05"
	echo "	system is instead `uname -r`"
	echo ""
fi
	
COMPILER=`what /bin/c89 |fgrep '9.68' 2>/dev/null`

if [ ! "$COMPILER" ];then
	echo "	Compiler version is Incorrect. It should be 9.68"
	echo "	Instead it is:"
	what /bin/c89
	echo ""
fi


