/* $XConsortium: dtdext.h /main/3 1995/11/08 09:49:13 rswiston $ */
/* Copyright (c) 1988, 1989 Hewlett-Packard Co. */
/* Dtdext.h contains the dtd-independent external forms of
   declarations relevant to document-type definitions.  The
   definition form of these declarations is contained in files
   dtd.h and arc.h generated by BUILD. */


#include "dtddef.h"

extern M_PTRIE m_entree[] ;

extern M_WCHAR m_ename[] ;

extern int m_elcount ;
extern M_ELTSTRUCT m_element[] ;

extern M_WCHAR m_keyword[] ;

extern M_WCHAR m_defval[] ;

extern struct {
  int keyword, next ;
  } m_ptype[] ;

extern M_PARAMETER m_parameter[] ;

extern M_WCHAR m_pname[] ;

extern M_PTRIE m_maptree[] ;

extern M_PTRIE m_sreftree[] ;

extern int m_map[] ;

extern M_SREF m_sref[] ;

extern M_STATESTRUCT m_state[] ;

extern M_ANDSTRUCT m_andgroup[] ;

extern M_EXCEPTION m_exception[] ;

extern M_ARCSTRUCT m_arc[] ;


