#define Set_CatMgr		1
#define Set_DtSR_Parser		2
#define Set_SearchMgr		3
#define Set_AgentLabel		7
#define Set_AgentQHelp		8
#define Set_LibraryAgent	4
#define Set_NodeWindowAgent	5
#define Set_AddLibraryAgent	6
#define Set_BookmarkEdit	9
#define Set_GraphicAgent	10
#define Set_MarkList		11
#define Set_MarkChooser		12
#define Set_NodeHistoryAgent	13
#define Set_PrefAgent		14
#define Set_PrintPanelAgent	15
#define Set_SearchScopeAgent	16
#define Set_SearchResultsAgent	17
#define Set_UrlAgent		18
#define Set_QueryEditor		19
#define Set_Messages		20
#define Set_MessageAgent	21
#define Set_Version		22
#define Set_CanvasRenderer	23
#define Set_UAS_Base		24
#define Set_UAS_MMDB		27
#define Set_MapAgent		28
#define Set_SearchHistoryList	29
#define Set_WindowSystem	30
#define Set_NodePrintAgent	31
#define Set_EnvMgr		40
#define Set_TtIpcMgr		41
#define Set_DtSR_SearchEngine	42
