/* $XConsortium: Makefile /main/3 1996/05/10 17:20:47 drk $ */
/*
 * kpv delta/update library
 * retained for pax compatibility
 *
 * OBSOLETE: use vdelta
 */

:PACKAGE: ast

odelta :LIBRARY: update.h suftree.h \
	delta.c mtchstring.c suftree.c update.c
