/* XPM */
/* $XConsortium: DtTtsnp.m.pm /main/3 1995/07/18 16:08:33 drk $ */
static char * DtTtsnp_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor4	m white	c green",
"X	s iconColor2	m white	c white",
"o	s iconGray4	m white	c #969696969696",
"O	s iconGray2	m white	c #c8c8c8c8c8c8",
"+	s iconColor1	m black	c black",
"@	s iconGray3	m white	c #afafafafafaf",
"#	s iconGray6	m black	c #646464646464",
"$	s iconGray5	m black	c #7d7d7d7d7d7d",
"%	s iconGray1	m white	c #e1e1e1e1e1e1",
"&	s iconGray8	m black	c #323232323232",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"  ..  XXo XX     Oo+     +OO    ",
"  .Xo@XX##@#     Oo        O    ",
"  ..$.###o##    OO         O    ",
"  .X@.X%oooo    Oo          o   ",
"  .XX.X%o       OO         Oo   ",
"  ...oX%.        O         Oo   ",
"  ...oX%.X       Oo       OO    ",
"  .X.oo$+..       Oo      Oo    ",
"  .X.oo$+..X       Oo   OOo     ",
"  ...oo$+oX..       O   Oo      ",
"  ...oo$+o ..X      OO Oo       ",
"  .XX.o$+...X..      O Oo       ",
"  .XX.o$+..XX..X     OOO        ",
"  ....o$+........     Oo        ",
"      o$+o            &         ",
"      o$+o            &         ",
"      o$+o            &         ",
"      +++             &&        ",
"                       +        ",
"                        &       ",
"  ++   &&&&             &       ",
"  +++   &&               &      ",
"  +++++++++++&           &      ",
"  ++          &&        &       ",
"                &&    &&        ",
"                  &&&&          ",
"                                ",
"                                "};
