/* XPM */
/* $XConsortium: DtTtsnp.l.pm /main/3 1995/07/18 16:08:25 drk $ */
static char * ttsnoop_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor4	m white	c green",
"X	s iconGray2	m white	c #c8c8c8c8c8c8",
"o	s iconGray8	m black	c #323232323232",
"O	s iconColor2	m white	c white",
"+	s iconGray4	m white	c #969696969696",
"@	s iconGray3	m white	c #afafafafafaf",
"#	s iconGray6	m black	c #646464646464",
"$	s iconGray1	m white	c #e1e1e1e1e1e1",
"%	s iconGray7	m black	c #4b4b4b4b4b4b",
"&	s iconGray5	m black	c #7d7d7d7d7d7d",
"*	s iconColor1	m black	c black",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"   .                      Xoo        ooX        ",
"   ..O  OOOO+ OOO        XX+           XX       ",
"   .OO+@OOOO##O@#+       X++            X+      ",
"   .$O+%XXXX##$@#+       X+             X+      ",
"   ..&&.%####+###+      XX+             XX      ",
"   .O.@.@O$#++++++      X++              X+     ",
"   ..O.O.O$#+           X+               X+     ",
"   .O.O.OO$#+           XX+             XX+     ",
"   ..O.+.O$#.            X+             X++     ",
"   .O..++O$#@.           X+             X+      ",
"   ..O.+ O$#.O.          XX+           XX+      ",
"   .O..+&+&**.O.          XX+         XX++      ",
"   ..O.+&+&**O.O.          XX+       XX++       ",
"   .O..+&+&**.O.O.          XX+     XX++        ",
"   ..O.+&+&**+.O.O.          XX    XX++         ",
"   .O..+&+&**+ .O.O.          X+   X++          ",
"   ..O.+&+&**+  .O.O.         XX+ XX+           ",
"   .O.O.&+&**.....O.O.         X+ X++           ",
"   ..O.O&+&**@.O.O.O.O.        X+ X+            ",
"   .O.O.&+&**.O.O.O.O.O.       XXXX+            ",
"   .....&+&**............       XX+             ",
"    ++++&+&**+++++++++++        XX              ",
"        &+&**+                  oo              ",
"        &+&**+                  oo              ",
"        &+&**+                  oo              ",
"        &+&**+                  oo              ",
"        *****                    oo             ",
"                                  oo            ",
"                                   o            ",
"                                    o           ",
"          oooooo                    o           ",
"   **     oooooo                    o           ",
"   ****     oo                       o          ",
"   ******oooooooooo                  o          ",
"   ****            oo                o          ",
"   **                oo             o           ",
"                       o           o            ",
"                        oo       oo             ",
"                          ooooooo               ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
