/* XPM */
/* $XConsortium: contain.pm /main/1 1996/03/09 20:11:49 rws $ */
static char * container_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 9 1 0 0",
/* colors */
" 	c #8C8C8C8C8C8C",
".	s iconColor1	m black	c black",
"X	c #7E7E7E7E7E7E",
"o	c #D9D9D9D9D9D9",
"O	s iconColor2	m white	c white",
"+    s iconGray8     m black c #212121212121",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray5     m black c #737373737373",
"$	c #B7B7B7B7B7B7",
/* pixels */
"                                                ",
"                                                ",
"   ..........                                   ",
"   .XXXXXXXXoOO     OOO          ++++++++++++++ ",
"   .XOXXXXXXOO.      O           +@@@@@@@@@@@@@ ",
"   .OOOXXXXOO.       O O    O  O +@@@@@@@@@@@@@ ",
"   OOOOOXXOO.        O O O  O  # +@@@@@@@@@@@@@ ",
"   .OOOOOOO.o        O O  O O  O @@@@@@@@@@@@@@ ",
"   .XOOOOO.Xo               #        #          ",
"   .XXOOO.XXo                                   ",
"   .XXXO.XXXo                                   ",
"   .ooooooooo                                   ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"      #   #                                     ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"  ............................................  ",
"  .            ooooooooooooo                 o  ",
"  .            o$$$$ .o$$$$.                 o  ",
"  .            o$$$$ .o$$$$.                 o  ",
"  .            o$$$$ .o$$$$.                 o  ",
"  .            o............                 o  ",
"  .ooooooooooooooooooooooooooooooooooooooooooo  ",
"                                                ",
"                                                "};
