/* XPM */
/* $XConsortium: fsb.pm /main/1 1996/03/09 20:12:17 rws $ */
static char * fsb_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 8 1 0 0",
/* colors */
" 	c #C3C3C3C3C3C3",
".	s iconColor1	m black	c black",
"X	c #8C8C8C8C8C8C",
"o    s iconGray5     m black c #737373737373",
"O	c #B7B7B7B7B7B7",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#	c #7E7E7E7E7E7E",
/* pixels */
"    .                                          .",
" XXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
" Xoo.oXXXoooooXXXXXXXXXXXXXXXXXXXXXXXXXXXXooooX.",
"O...............................................",
" X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X.",
" X.X.................. XX.................. X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.+++++++++++++++++ XX.+++++++++++++++++ X X.",
" X.X.                  XX.                  X X.",
" X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X.",
" X.X........................................X X.",
" X.X.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ X X.",
" X.X.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ X X.",
" X.X.@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ X X.",
" X.X.                                       X X.",
" X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X.",
" X                                            X.",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
" X            .XXX            .XXX           .X.",
" X ###########.XXX ###########.XXX ##########.X.",
" X ###########.XXX ###########.XXX ##########.X.",
" X ............XXX ............XXX ...........X.",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
" ..............................................."};
