/* XPM */
/* $XConsortium: termpi.pm /main/1 1996/03/09 20:12:49 rws $ */
static char * term_pane_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 9 1 0 0",
/* colors */
"     s iconGray4     m white c #949494949494",
".	s iconColor1	m black	c black",
"X	c #7E7E7E7E7E7E",
"o	c #CCCCCCCCCCCC",
"O	s iconColor2	m white	c white",
"+	c #C3C3C3C3C3C3",
"@    s iconGray1     m white c #dededededede",
"#	c #8C8C8C8C8C8C",
"$	c #B7B7B7B7B7B7",
/* pixels */
"                                                ",
"              ....................             X",
"             .oooooooooooooooooooo.            X",
"            .OOOOOOOOOOOOOOOOOOOOOO.           X",
"            .O+++++++++++++++++++++.           X",
"            .O+XXXXXXXXXXXXXXXXXXX+.           X",
"            .O+X.................O+.           X",
"            .O+X.................O+.           X",
"            .O+X..@@@@@@@@.......O+.           X",
"            .O+X.................O+.           X",
"            .O+X.................O+.           X",
"            .O+X..@@@@@..........O+.           X",
"            .O+X.................O+.           X",
"            .O+X.................O+.           X",
"            .O+X..@@@@@@@@@@@@...O+.           X",
"            .O+X.................O+.           X",
"            .O+X.................O+.           X",
"            .O+XOOOOOOOOOOOOOOOOOO+.           X",
"            .O+++++++++++++++++++++.           X",
"             ......................            X",
"                .XXXXXXXXXXXXXX.               X",
"                 ..          ..                X",
"         ..............................        X",
"         .############################.        X",
"         .ooo#oo#oo#oo#o#ooo#o#o#ooooo.        X",
"        .ooo#oo#oo#oo#oo#ooo#oo#o#ooooo.       X",
"        .oo#oo#ooooooooooooo#o#o#o#oooo.       X",
"       .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.      X",
"       .$##############################$.      X",
"       ..................................      X",
"        ................................       X",
" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
