#!/bin/ksh
#
# initialize_view
#
########################################################################

PROG_NAME=$0
X_TOP=/proj/x11/xc
MOTIF_TOP=/proj/motif
CDE_TOP=/proj/cde
CDE_TEST_TOP=/proj/cde-test
VERBOSE=""
DEBUG=""

usage ()
{
	print -u1 "USAGE: $1"
	print -u1 "\t[-v | -verbose]  # Turn on tracing"
	print -u1 "\t[-d | -debug]    # Print commands but do NOT execute them"
}

while [ $# -gt 0 ]; do
	case $1 in
		-v | -verbose)		VERBOSE="True";	shift 1 ;;

		-d | -debug)		DEBUG="echo";	shift 1 ;;

		-h | -? | -help)	usage $PROG_NAME 
					shift 1
					exit 1 ;;
	esac
done

if [ "True" = "$VERBOSE" ]; then
	set -x
fi

#
# Motif
#
$DEBUG cd $MOTIF_TOP
if [ ! -d exports ]; then
	$DEBUG mkdir exports
	$DEBUG chmod 777 exports
fi
if [ ! -d imports ]; then
	$DEBUG mkdir imports
	$DEBUG chmod 777 imports
fi
$DEBUG cd imports
if [ ! -L x11 ]; then
	$DEBUG ln -s ../../x11/xc/exports x11
fi

#
# CDE
#
$DEBUG cd $CDE_TOP
if [ ! -d exports ]; then
	$DEBUG mkdir exports
	$DEBUG chmod 777 exports
fi
if [ ! -d imports ]; then
	$DEBUG mkdir imports
	$DEBUG chmod 777 imports
fi
$DEBUG cd imports
if [ ! -L x11 ]; then
	$DEBUG ln -s ../../motif/imports/x11 x11
fi
if [ ! -L motif ]; then
	$DEBUG ln -s ../../motif/exports motif
fi

#
# CDE test build config links
#

if [ -d $CDE_TEST_TOP/config ]; then
	$DEBUG cd $CDE_TEST_TOP/config
	if [ ! -L OSVersion.tmpl ] || [ ! -L localtree.tmpl ]; then

		case "`uname -s`" in
	   		HP-UX)	if [ ! -L OSVersion.tmpl ]; then
					$DEBUG ln -s OSVersiontemplates/10.20 OSVersion.tmpl
				fi

				if [ ! -L localtree.tmpl ]; then
					$DEBUG ln -s localtemplates/hpux/10.20/optimized.shared localtree.tmpl 
				fi
				;;

	   		OSF1)   if [ ! -L OSVersion.tmpl ]; then
                                        $DEBUG ln -s OSVersiontemplates/4.0 OSVersion.tmpl
                                fi

                                if [ ! -L localtree.tmpl ]; then
                                        $DEBUG ln -s localtemplates/dec/alpha/osf/optimized.sharedlibs localtree.tmpl
                                fi	
				;;

                        AIX)  if [ ! -L OSVersion.tmpl ]; then
                                        $DEBUG ln -s OSVersiontemplates/4.2 OSVersion.tmpl
                                fi

                                if [ ! -L localtree.tmpl ]; then
                                        $DEBUG ln -s localtemplates/ibm/rs6000/aix4.2/optimized.sharedlibs localtree.tmpl
                                fi
				;;

                        SunOS)  if [ ! -L OSVersion.tmpl ]; then
                                        $DEBUG ln -s OSVersiontemplates/5.4 OSVersion.tmpl
                                fi

                                if [ ! -L localtree.tmpl ]; then
                                        $DEBUG ln -s localtemplates/sun/optimized.sharedlibs localtree.tmpl 
                                fi
				;;
			
			UNIX_SV) if [ ! -L OSVersion.tmpl ]; then
                                        $DEBUG ln -s OSVersiontemplates/4.2 OSVersion.tmpl
                                fi

                                if [ ! -L localtree.tmpl ]; then
                                        $DEBUG ln -s localtemplates/sun/optimized.sharedlibs localtree.tmpl
                                fi
                                ;;

			*)	$DEBUG print -u1 "$PROG_NAME: Test build config links not set up for this architecture"
				;;
		esac

	fi

else
        $DEBUG print -u2 "$PROG_NAME: CDE test config directory $CDE_TEST_TOP/config does not exist!"
        $DEBUG exit 1
fi
exit 0
