/* XPM */
static char *amarok_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 192 2",
"   c #01448B",
".  c #07488D",
"X  c #0B4B8E",
"o  c #16508F",
"O  c #19518C",
"+  c #004790",
"@  c #014A94",
"#  c #0D4D91",
"$  c #014D9B",
"%  c #094F98",
"&  c #114F91",
"*  c #0C5197",
"=  c #04519D",
"-  c #0A539C",
";  c #145293",
":  c #1A5695",
">  c #1E5997",
",  c #1F5A98",
"<  c #255B93",
"1  c #295C93",
"2  c #245D99",
"3  c #285F9A",
"4  c #2D629B",
"5  c #386391",
"6  c #3B6897",
"7  c #326398",
"8  c #3A6A9D",
"9  c #0253A4",
"0  c #0A55A3",
"q  c #0D59A4",
"w  c #0057AD",
"e  c #0258AE",
"r  c #0C5CAD",
"t  c #115BAA",
"y  c #065AB1",
"u  c #0B5EB2",
"i  c #125EB0",
"p  c #1C65AF",
"a  c #0F60B5",
"s  c #1262B5",
"d  c #1B63B2",
"f  c #1B68B7",
"g  c #1564B9",
"h  c #1A65BA",
"j  c #1F6ABF",
"k  c #2268AF",
"l  c #296BAE",
"z  c #3569A0",
"x  c #3A6EA5",
"c  c #3F71A7",
"v  c #3270AF",
"b  c #3B75AF",
"n  c #226CB4",
"m  c #226ABA",
"M  c #2B6CBA",
"N  c #2D73BC",
"B  c #3675B4",
"V  c #3C78B4",
"C  c #3577B9",
"Z  c #3A75BC",
"A  c #3F7BBB",
"S  c #486F97",
"D  c #466E99",
"F  c #4A719B",
"G  c #50759C",
"H  c #57799E",
"J  c #5E7C9B",
"K  c #4271A3",
"L  c #4C76A2",
"P  c #4173A8",
"I  c #447AB0",
"U  c #4A7FB3",
"Y  c #256DC2",
"T  c #286FC1",
"R  c #2C72C5",
"E  c #3275C6",
"W  c #3876C1",
"Q  c #3276C8",
"!  c #3678C8",
"~  c #3C7CC9",
"^  c #69839F",
"/  c #74869A",
"(  c #7B8B9C",
")  c #5D80A6",
"_  c #5F83AA",
"`  c #4C82B7",
"'  c #4780BA",
"]  c #4B83BA",
"[  c #5E8AB6",
"{  c #6685A5",
"}  c #6687AA",
"|  c #6589AC",
" . c #6C8AAB",
".. c #7C90A5",
"X. c #7C93AC",
"o. c #658BB0",
"O. c #7492B1",
"+. c #7C96B1",
"@. c #7D98B4",
"#. c #7295BB",
"$. c #7C9ABB",
"%. c #4680C5",
"&. c #4A80C1",
"*. c #4481CB",
"=. c #4B85CC",
"-. c #5C8DC4",
";. c #548ACC",
":. c #598FCF",
">. c #5C90CF",
",. c #588ED0",
"<. c #618FC6",
"1. c #6390C1",
"2. c #6394CF",
"3. c #779FCF",
"4. c #6595D0",
"5. c #6897D0",
"6. c #6C9AD2",
"7. c #719DD2",
"8. c #7BA0C7",
"9. c #73A0D4",
"0. c #7BA3D4",
"q. c #86929F",
"w. c #8D959D",
"e. c #9E9E9E",
"r. c #8293A5",
"t. c #8998A7",
"y. c #8B9DAF",
"u. c #919EAC",
"i. c #8199B2",
"p. c #889DB1",
"a. c #819CBA",
"s. c #8DA2B9",
"d. c #94A4B7",
"f. c #9FA7B0",
"g. c #9EA8B3",
"h. c #94A7BB",
"j. c #9BAABA",
"k. c #A3A3A3",
"l. c #A0A7AF",
"z. c #A5AAAF",
"x. c #ACACAC",
"c. c #A5ABB2",
"v. c #AAAEB3",
"b. c #ADB0B2",
"n. c #ABB2B8",
"m. c #B2B3B3",
"M. c #B0B7BD",
"N. c #BBBBBB",
"B. c #80A1C6",
"V. c #8DABC9",
"C. c #97B2CF",
"Z. c #99B3CF",
"A. c #81A7D6",
"S. c #85AAD4",
"D. c #88ACD6",
"F. c #91B0D6",
"G. c #99B3D0",
"H. c #9EB8D2",
"J. c #96B5D9",
"K. c #9AB7DA",
"L. c #9CB8DA",
"P. c #B3BAC2",
"I. c #BBBFC3",
"U. c #A4BCD6",
"Y. c #A7BFDC",
"T. c #BDC1C5",
"R. c #ACC2DE",
"E. c #B4C7DF",
"W. c #B6CADF",
"Q. c #BACCDF",
"!. c #B4C8E0",
"~. c #B8CDE1",
"^. c #C4C4C4",
"/. c #C3C6C8",
"(. c #C7C9CB",
"). c #CCCCCC",
"_. c #C9CED3",
"`. c #D3D3D3",
"'. c #D5D7DA",
"]. c #DBDBDB",
"[. c #C4D4E4",
"{. c #D6DFE9",
"}. c #D7E1EC",
"|. c #E3E3E3",
" X c #ECECEC",
".X c #E9ECF0",
"XX c #EAF0F5",
"oX c #F3F3F3",
"OX c #F1F5F8",
"+X c #F7F9FB",
"@X c #FBFBFB",
"#X c None",
/* pixels */
"#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Xw w w w e e w w w w #X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Xw e w w q k v I I v p r w w e w #X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#X#X#Xe e r b O.c.m.m.m.m.m.m.m.m.c.O.b r e e #X#X#X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#Xe w l +.b.m.m.m.m.m.m.m.m.m.m.m.m.m.m.v.+.l w w #X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#Xe e p r.m.m.b.m.N.).`.`.].`.`.`.).^.N.m.m.m.m.m.X.p w e #X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#Xe e o.m.b.m.N.).].].|.].].].`.`.`.`.`.).).^.N.m.m.m.m.o.e e #X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#Xe r p.m.m.m.).].|.{.].].].`.].].`.`.`.).).).(.(.^.m.m.m.m.p.r e #X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#Xw p f.m.m.N.].|.].|.].].].].].`.`.`.`.).`.).).(.(.^.^.M.m.m.m.c.k w #X#X#X#X#X#X#X",
"#X#X#X#X#X#Xe k v.m.m.N.].|.|.|.].].].].].`.'.`.`.`.`.).).).^.).^.^.^.N.m.m.m.v.n e #X#X#X#X#X#X",
"#X#X#X#X#Xe r g.m.m.^.|.|.|.|.].].].].].].'.`.`.`.).).).).).(.^.^.^.M.^.N.m.m.m.f.r e #X#X#X#X#X",
"#X#X#X#Xe e y.m.b.N.].|.|.].].].].].].`.`.`.`.`.`.`.).).).).^.^.I.) . X.^.m.m.m.m.p.e e #X#X#X#X",
"#X#X#X#Xe  .b.m.m.].|.|.|.].].].].].].].`.`.`.`.).).).).^.(.(.N.7 .     f.N.m.m.m.m.o.w #X#X#X#X",
"#X#X#Xe d b.b.m.`.|.|.].].].].].].].`.`.`.`.`.).).).).).).).g.: > 3 .   F N.N.m.m.b.b.p e #X#X#X",
"#X#X#Xe +.m.b.N.].].].].].].].].].`.].`.`.`.).`.`.).).(.^. .  : 3 3 3   5 k.N.m.m.m.m.X.e #X#X#X",
"#X#Xe l m.m.m.`.].].].].].].'.].].`.`.`.`.`.`.).).(.(.I.8   X 2 2 3 2   / e.x.N.N.m.m.m.l e #X#X",
"#X#Xw +.m.m.N.].].].].].].].`.`.`.`.`.`.`.).).).).).j.o   . < 2 2 2 ; 1 k.e.k.N.N.m.N.m.@.w #X#X",
"#Xw r v.m.m.^.].].].].].].'.].`.`.`.`.).`.).).).(.} . : . : 2 2 2 2   ( k.e.x.^.m.N.N.m.b.y w #X",
"#Xw b m.m.m.`.].`.`.`.`.`.`.`.`.`.).`.).).).).P.8 & ;   o > > , 2 & 1 k.k.k.m.^.^.m.N.N.N.I y #X",
"#Xw O.m.m.m.'.'.`.].`.`.`.`.`.).`.).j.8 & . # . ; .   X : > > > <   / k.k.m.^.N.N.N.^.N.N.@.w #X",
"w w x.m.m.N.`.`.`.`.`.`.`.`.`.`._.+.; < , 2 : ;       : : : > > & X k.x.k.^.^.^.^.^.N.^.I.M.w w ",
"w r m.m.m.N.`.`.`.).`.`.).`.).).{ # : ; 2 3.C.4     ; : : : > :   S k.k.N.^.j.I.^.^.^.^.^.^.r w ",
"w d m.m.m.^.).`.`.`.`.).`.).(.K # ; ; c oX@X@X#   * ; ; : : : ;   < J { } <   i.^.^.^.^.^.^.f w ",
"e v m.m.m.^.).`.)._.).).).I.7 X & & . }.@XXXP   X ; ; ; ; : : .         # ;   L ^.^.).^.^.^.b w ",
"e I m.m.m.^.).).).).^.X.8 X . X X . B.@X}.,   . ; o : ; ; : : X . # ; < ; . 5 u.m.N.).).^.(.` r ",
"w I m.m.b.N.).).(.P.2 &   .   .   . +X[.;   . & X ; ; ; ; ; : ; : : ;   1 r.x.m.m.m.).).).).` e ",
"e v m.m.b.N.(.).n.3 P z &         P Q..   . & & X ; ; ; ; ; : : : & O ..m.m.m.b.N.).`.`.)._.V e ",
"w p m.m.m.m.T. .3 3 X             3 X   . X # X X ; # ; ; ; ; : . : c.m.m.m.^.`.'.`.`.`.`.`.n w ",
"w r m.m.c.J O : .                     . . X X X X ; ; X ; ; ;   < c.m.m.^.'.].].].].].'.`.`.u w ",
"w w l.G . ; :   . # & & .             . . . X . X X # ; # o   1 m.m.N.^.].].|.|.].].].].'._.e e ",
"#Xe O.6 & ; .   & & : . # :         . . @ . # # # # # & *     l.m.N.`.|.|.|.|.|.|.|.|.].].V.e #X",
"#Xe b z.O X & & # . . : &         @ @ @ $ % % % % * % # .   1 N.N.`.|.|. X|.|.|.|.|.|.].].' e #X",
"#Xw r b.t.. . . X & #       + @ @ @ $ % $ % = - - - * * @   { N.^.|.|. X X X X X X|.|.|.].u e #X",
"#X#Xw +.m.q.X           + + @ $ $ $ $ 9 $ 0 9 0 0 0 0 % $ @ y.N.`. X X X X X X X X X X|.H.w #X#X",
"#X#Xe l m.m.w.O       @ $ $ $ $ $ 9 $ 9 9 9 9 0 0 9 0 = 0 $ b.N.]. X X XoXoXoXoX X X X|.C w #X#X",
"#X#X#Xe +.m.m./     @ @ $ 9 0 9 9 0 w 9 e w w w e r 9 9 q 0 N.N. X X.XoXoX+XoXoX X X XU.w #X#X#X",
"#X#X#Xe p b.m.D     $ $ - 0 9 9 0 w w e e r 0 u e e w u 0 l N.^. X XoXoXoX@X@XoXoXoX Xn y #X#X#X",
"#X#X#X#Xw o.S   + $ $ 9 9 9 w r y y t i g t i i s u y f w b ^.). X XoXoX@X@X@X@XoXXXS.w #X#X#X#X",
"#X#X#X#Xe e 2 @ $ $ 9 9 9 w u u u i d g h i h h h g g m r U I.). X XoXoX@X@X@X@XoX~.r e #X#X#X#X",
"#X#X#X#X#Xe q @ $ $ 9 9 w y i s h M Y Y M Y Y m m Y R j u [ N.`. X XoXoX+X@X@XoX}.s e #X#X#X#X#X",
"#X#X#X#X#X#Xy 0 $ 9 9 w y s g h M Y Y R W E ! M T R *.m g #.N.`. X X XoXoXoXoX XN r #X#X#X#X#X#X",
"#X#X#X#X#X#X#Xw 0 9 w w u g h Y R E ! %.*.*.*.Z ~ *.*.Y j i.N.]. X X X.X XoX}.N w #X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#Xw w w y g g Y Q Q ~ *.;.;.;.;.&.=.,.=.Q Y s.N.].|.|. X X XW.s e #X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#Xy e i g j R Q ~ =.>.>.2.5.2.-.,.4.,.~ Q j.M.].|.|.|. XS.e e #X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#Xw e h Y R ~ =.;.5.7.0.A.A.3.6.6.7.=.! c.N.].|.|.H.n e r #X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#Xw g ! *.;.4.9.D.J.K.K.F.D.7.9.6.*.d.N.'.Z.C w e #X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#X#X#Xr f *.7.D.K.R.E.!.Y.J.A.6.4.<.$.' u w e #X#X#X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Xy a I [ 3.Z.U.C.B.1.W s w w y w #X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X",
"#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Xw w w e w y e e e w #X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X"
};
