/* XPM */
static char *brasero_m[] = {
/* columns rows colors chars-per-pixel */
"32 32 178 2 ",
"   c #555555",
".  c #7D7D7E",
"X  c #FBE854",
"o  c #CAC17C",
"O  c #D3CB76",
"+  c #D4CB7C",
"@  c #DBD071",
"#  c #E6D962",
"$  c #E1D66D",
"%  c #E0D575",
"&  c #E5D97C",
"*  c #F7E765",
"=  c #ECE07F",
"-  c #FDED70",
";  c #848484",
":  c #898987",
">  c #878788",
",  c #8A8A8A",
"<  c #939394",
"1  c #969899",
"2  c #9C9D9E",
"3  c #BAB384",
"4  c #A5A49E",
"5  c #AAA79C",
"6  c #ACAD99",
"7  c #B2B395",
"8  c #B2B19D",
"9  c #B9B699",
"0  c #BDBC9E",
"q  c #9FA1A3",
"w  c #A4A4A5",
"e  c #AEA9A4",
"r  c #A2A6A8",
"t  c #A8A7A8",
"y  c #A4A8AB",
"u  c #ABACAD",
"i  c #B3AFA3",
"p  c #B2AEAD",
"a  c #AEB1A6",
"s  c #B3B5A4",
"d  c #BDBBA3",
"f  c #B3B2AC",
"g  c #B8B5AD",
"h  c #B5B8AE",
"j  c #BEBCAC",
"k  c #A9A6B4",
"l  c #A7A9B5",
"z  c #ACABB3",
"x  c #A5A6BD",
"c  c #A6A9BA",
"v  c #ABAABC",
"b  c #B2ADB4",
"n  c #B1ACB9",
"m  c #ADB0B6",
"M  c #B3B3B3",
"N  c #B5B8B4",
"B  c #BABBB6",
"V  c #B4B2BB",
"C  c #B5BABB",
"Z  c #BBBDBA",
"A  c #C4BC80",
"S  c #C1BD8C",
"D  c #C1BE96",
"F  c #C2BE9D",
"G  c #C1BEA3",
"H  c #C2BEB6",
"J  c #C1BEBC",
"K  c #BFC2AA",
"L  c #BDC1BF",
"P  c #CAC383",
"I  c #CCC68B",
"U  c #D3CE82",
"Y  c #D1CA8C",
"T  c #CDC793",
"R  c #C4C29C",
"E  c #E8DD89",
"W  c #EFE48A",
"Q  c #F0E68B",
"!  c #EBE394",
"~  c #EDE49C",
"^  c #C0C0A5",
"/  c #CDC9A5",
"(  c #C4C2AC",
")  c #CCC9AC",
"_  c #C3C4B1",
"`  c #C3C3BC",
"'  c #C9C7BF",
"]  c #CDCCBB",
"[  c #D4D3BB",
"{  c #E9E2AA",
"}  c #F0E8A1",
"|  c #F5EDAE",
" . c #E8E3BA",
".. c #F5EFBF",
"X. c #FEF7BC",
"o. c #AEAFC4",
"O. c #B1AFC7",
"+. c #B4B2C5",
"@. c #BAB7C5",
"#. c #B7BEC4",
"$. c #BBBCC5",
"%. c #B4B4CA",
"&. c #BDBBCE",
"*. c #BDBDD3",
"=. c #BDBDD8",
"-. c #C1BEC4",
";. c #C1BDC8",
":. c #BDC2C4",
">. c #BCC2CB",
",. c #BEC5D2",
"<. c #C5C4C3",
"1. c #C3C8C4",
"2. c #CBCBC3",
"3. c #C4C4CB",
"4. c #C9C6CC",
"5. c #C4C9CE",
"6. c #CBCBCC",
"7. c #D1CECE",
"8. c #CCD1CF",
"9. c #D1D2C0",
"0. c #D2D2CE",
"q. c #DDDDCD",
"w. c #C4C4D3",
"e. c #C8C6D1",
"r. c #C6CBD3",
"t. c #CBCBD3",
"y. c #CAC7DA",
"u. c #CDCBDC",
"i. c #D1CCD2",
"p. c #D2CDDA",
"a. c #CDD3DB",
"s. c #D3D2D3",
"d. c #DAD6D5",
"f. c #DADAD6",
"g. c #D4D4DA",
"h. c #D9D5DC",
"j. c #D6D9D9",
"k. c #DDDCDC",
"l. c #E2DFC9",
"z. c #E0DADF",
"x. c #DFE0DA",
"c. c #FEF9CD",
"v. c #E7E7D7",
"b. c #E2E2DE",
"n. c #E8E8DE",
"m. c #FEFAD5",
"M. c #FCF9DD",
"N. c #CBCCE2",
"B. c #D3CFE8",
"V. c #CFD5E2",
"C. c #D3D4E1",
"Z. c #DBD6E3",
"A. c #D7DBE5",
"S. c #DCDBE3",
"D. c #D5D5EA",
"F. c #DCDDEC",
"G. c #D6D8F0",
"H. c #E1DDE4",
"J. c #E4DFE8",
"K. c #DCE0EB",
"L. c #E4E3E3",
"P. c #E8E4E6",
"I. c #E9E9E7",
"U. c #E6E4EA",
"Y. c #EAE5E9",
"T. c #ECEBEB",
"R. c #F1EEEF",
"E. c #F0F0EF",
"W. c #FDFBED",
"Q. c #E6E8F0",
"!. c #EEEEF3",
"~. c #F1EFF2",
"^. c #F4F3F3",
"/. c #FBFBF5",
"(. c #F7F6F9",
"). c #F9F6F9",
"_. c #FDFDFD",
"`. c None",
/* pixels */
"`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`.`.`.`., , ; ; > , , `.`.`.`.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`., : u 0.k.I.T.I.L.s.g , , `.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.> > ` L.b.f.s.s.s.d.k.L.R.R.6.: , `.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.> 4 ] ) ^ G ` 4.7.0.s.h.z.P.Y.~.R.u , `.`.`.`.`.`.",
"`.`.`.`.`.`.> B ] P @ % + F J 4.7.i.i.z.J.P.Y.R.~.<., `.`.`.`.`.",
"`.`.`.`.`.> Z 0.S W /._.X.+ G e.7.7.i.z.J.J.P.Y.T.~.<.> `.`.`.`.",
"`.`.`.`., w L.j o m._._._.E F ;.4.4.i.z.z.P.P.Y.Y.R.^.e < `.`.`.",
"`.`.`.`.> L.0.f T _._._./.% G -.-.;.i.Z.H.H.U.Y.Y.R.R.T.: `.`.`.",
"`.`.`., 1.L.` h ^./.X.m.W A e Z k n ;.p.Z.H.J.U.Y.P.b.T.` , `.`.",
"`.`.`., T.0.B I._.) P o 3 5 k J v n w.y.u.Z.H.H.k.k.H.L.T., `.`.",
"`.`.`.M I.6.B _.b.` g 5 4 w z <.&.&.y.y.u.u.p.u.h.h.k.z.T.u `.`.",
"`.`., f.L.2.0._.s.4.V z t p u < ; < @.B.*.o.@.t.p.j.k.k.n.6., `.",
"`.`., P.x.` T.(.6.4.n l z M ; `.`.`.; +.&.o.o.w.t.p.g.f.b.f., `.",
"`.`., E.x.` (.Q.t.w.+.+.&.< `.`.`.`.`.< N.x c &.r.r.a.j.f.L.: `.",
"`.`.; ^.x.:.^.T.p.e.3.2.q.; `.`.`.`.`.; g.c c %.w.5.r.j.j.U.; `.",
"`.`., E.L.1.^.E.p.w.%.+.=.< `.`.`.`.`.< q.y l #.,.,.5.8.j.S.; `.",
"`.`., T.I.6.E.^.C.p.%.o.&.@.; `.`.`.; ` [ a y $.&.>.>.r.a.8., `.",
"`.`.< f.E.0.f._.S.C.*.=.y.D.;.< ; < ` v._ s s $.:.:.>.,.a.1., `.",
"`.`.`.B /.b.1._.E.F.G.N.y.N.p.h.q.l.[ ( ( d j Z _ C :.,.a.r `.`.",
"`.`.`., /.T.s.L._.K.F.D.N.p.$.b p i 7 9 F G j G R C :.,.a.> `.`.",
"`.`.`., 8.).L.6._.).F.G.D.C.@.b p p i D F G G U D N #.r.m , `.`.",
"`.`.`.`., (.E.g.6._._.F.F.C.w.-.J H H H G D $ O a C >.,.> `.`.`.",
"`.`.`.`., p ).T.g.6.^.W.n.g.t.6.2.<.' / & X # 7 h C r.2 > `.`.`.",
"`.`.`.`.`., 6.).!.g.5.n.M.c... .{ ~ W - * O 6 a N >.y : `.`.`.`.",
"`.`.`.`.`.`., 6.(.!.S.e.$.]  .| } ! E Y 8 a h L L r > `.`.`.`.`.",
"`.`.`.`.`.`.`., u ~.!.Q.C.r.#.C N N N N L L 1.L 1 : `.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.> , 6.!.Q.K.V.a.r.r.8.2.8.8.u > ; `.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`., , u 5.g.A.K.a.8.L q > ; `.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`.`.`.  ; > ; ; ; ; .   `.`.`.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.",
"`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`."
};
