/* XPM */
static char * IMdisplay_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	c #808080808080",
"O	c #C0C0C0C0C0C0",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray5	m black	c #737373737373",
/* pixels */
"                                ",
"                                ",
"                                ",
"                                ",
"              ....              ",
"             .XXXo.             ",
"      ..    .OOOO.o.  ....      ",
"    ..XX....OOOOOO....XXXo...   ",
"   .O....OO.oooooo.oO.....oOO.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXO+.  ",
" .XOOOOOOOOOOOOOOOOOOOOOOOO++.  ",
" .XOOOOOOOOOOOOOOOOOOOOOOOO++.  ",
" .XOOOOOOOOO.....OOOOOOOOOO+..  ",
" ...........XXXX..............  ",
" .........OOOOOXX...........+.  ",
" .......OO.....OOoo........++.  ",
" ......Oo.@@@@@.oO.........++.  ",
" ......O.@@OXO@@.Oo........++.  ",
" .....O.@@OX@@@@@.O........++.  ",
" .....O.@@XO@@@@@.O........++.  ",
" .....O.@@X@@@@@@.O........++.  ",
" .....O.@@O@@@@@@.O........++.  ",
" .....O.@@@@@@@@@.O........++.  ",
" ......O.@@@@@@@.O.........+..  ",
" ......Oo.@@@@@.oO.........+.   ",
"  ......OO.....OO...........    ",
"   ......oOOOOOo...........     ",
"          .....                 ",
"                                ",
"                                ",
"                                ",
"                                "};
