/* XPM */
static char * IMdisplay_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconColor2	m white	c white",
"o	c #808080808080",
"O	c #C0C0C0C0C0C0",
"+	s iconGray6	m black	c #636363636363",
"@	s iconGray5	m black	c #737373737373",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                      .....                     ",
"                    ..XXXXo..                   ",
"                    ..XXXXo..                   ",
"          ...      .OOOOOO.oo.   ......         ",
"         .XXX......OOOOOOOO......XXXXoo....     ",
"        ..XXX......OOOOOOOO......XXXXoo....     ",
"      ..O......OO..oooooooo..oOO.......oOOO.    ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO++.    ",
"    .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+++.    ",
"    .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+++.    ",
"    .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+++.    ",
"    .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+...    ",
"    .XOOOOOOOOOOOOO......OOOOOOOOOOOOOOO+...    ",
"    ...............XXXXX....................    ",
"    ............OOOOOOOXXX...............++.    ",
"    ..........OO.......OOOo.............+++.    ",
"    .........OOO.......OOOoo............+++.    ",
"    ........Ooo.@@@@@@@.ooO.............+++.    ",
"    ........O..@@@OXOO@@..Ooo...........+++.    ",
"    ........O..@@OOXO@@@..Ooo...........+++.    ",
"    .......O.@@@OXX@@@@@@@.O............+++.    ",
"    .......O.@@@XO@@@@@@@@.OO...........+++.    ",
"    .......O.@@@X@@@@@@@@@.OO...........+++.    ",
"    .......O.@@@X@@@@@@@@@.OO...........+++.    ",
"    .......O.@@@O@@@@@@@@@.OO...........+++.    ",
"    .......O.@@@@@@@@@@@@@.OO...........+++.    ",
"    .......O.@@@@@@@@@@@@@.O............+++.    ",
"    ........O..@@@@@@@@@..O.............+...    ",
"    ........Ooo.@@@@@@@.ooO.............+..     ",
"     ........OOO.......OOO...............       ",
"     .........OO.......OOO...............       ",
"      .........oOOOOOOOo................        ",
"                .......                         ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
