/* XPM */
/*
 * @DEC_COPYRIGHT@
 */
/*
 * HISTORY
 * $Log$
 * Revision 1.1.2.2  1995/06/13  13:41:01  Chris_Beute
 * 	Added support for Digital logo to login screen
 * 	[1995/06/09  14:45:51  Chris_Beute]
 *
 * $EndLog$
 */
/*
 * @(#)$XConsortium: DECDtlogo.pm /main/2 1996/07/18 15:29:01 drk $
 */
/* XPM */
static char * DECDtlogo_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"195 120 21 1 0 0",
/* colors */
" 	s background	m black	c #969696969696",
".	s iconGray7	m black	c #4b4b4b4b4b4b",
"X	s iconGray2	m white	c #c8c8c8c8c8c8",
"o	c #333347473F3F",
"O	c #808000002B2B",
"+	c #A0A040406060",
"@	c #909020204646",
"#	c #989830305353",
"$	c #C0C080809595",
"%	c #B0B060607B7B",
"&	c #E7E7CFCFD7D7",
"*	s iconColor2	m white	c white",
"=	c #C7C78F8FA2A2",
"-	c #CFCF9F9FB0B0",
";	c #B8B870708888",
":	c #DFDFBFBFCACA",
"?	c #A8A850506D6D",
">	c #EFEFDFDFE5E5",
",	c #888810103838",
"<	c #D7D7AFAFBDBD",
"1	c #F7F7EFEFF2F2",
/* pixels */
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                  ............................................................................................................................................................X                    ",
"                  ...........................................................................................................................................................XX                    ",
"                  ..........................................................................................................................................................XXX                    ",
"                  ...XXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXoXXX                    ",
"                  ...XXXXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXXXXX..XXXXXXXXXXXXXXXXXXooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOO+@OOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOO+#OOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO@$$$%OOO..XXOOOOOO&**=OOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOO&**-OOOOOOO..XXOOOOOOO#;=OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO+$$$%OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOO%****@OOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOO?****@OOOOOO..XXOOOOO#>**:OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOO?****,OOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOO?****@OOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOOO:**$OOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOO:**$OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOOOO#@OOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOO#@OOOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOO+***:OOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOO+;$?@OOOOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOO,;<:<%+***:OOO..XXOOOOO#::::OOOOOO..XXOOOOOO%-::$,::::OOO..XXOOOOO#::::OOOOOOO..XXOOO#:&***1::%OOO..XXOOOOOO$1*****&#OOOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOO#>*****>***:OOO..XXOOOOO+****OOOOOO..XXOOOO,:*****>****OOO..XXOOOOO+****OOOOOOO..XXOOO+********$OOO..XXOOOOO:********1#OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOO#***********:OOO..XXOOOOO+****OOOOOO..XXOOOO>***********OOO..XXOOOOO+****OOOOOOO..XXOOO+********$OOO..XXOOOO$****>:****-OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOO:****&>*****:OOO..XXOOOOO+****OOOOOO..XXOOO$****>&******OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOO:***?OO,1**>OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO?****%OO-****:OOO..XXOOOOO+****OOOOOO..XXOO,1***-OO%*****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOO,%%OOOO1***OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO$***:OOO,1***:OOO..XXOOOOO+****OOOOOO..XXOO+****,OOO<****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOOOOO@%&****OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO:***$OOOO-***:OOO..XXOOOOO+****OOOOOO..XXOO;***:OOOO?****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOOOO@=>*******OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO>***+OOOO$***:OOO..XXOOOOO+****OOOOOO..XXOO$***=OOOO+****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOO,<**********OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO:***+OOOO$***:OOO..XXOOOOO+****OOOOOO..XXOO$***$OOOO+****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOOO&****1-?$***OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO<***%OOOO$***:OOO..XXOOOOO+****OOOOOO..XXOO%***<OOOO+****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOO%***1%OOO-***OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO$***-OOOO<***:OOO..XXOOOOO+****OOOOOO..XXOO+***>OOOO%****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOO-***%OOOO:***OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO;****,OO@****:OOO..XXOOOOO+****OOOOOO..XXOO@****?OOO>****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***:OOOOOO..XXOOO:***#OOO#****OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOO,1***&%%1****:OOO..XXOOOOO+****OOOOOO..XXOOO<***1$?:*****OOO..XXOOOOO+****OOOOOOO..XXOOOOO+***>@?+OOO..XXOOO$***<,O#>****OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOO;***********:OOO..XXOOOOO+****OOOOOO..XXOOO@************OOO..XXOOOOO+****OOOOOOO..XXOOOOO+******$OOO..XXOOO+*****1******OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOO:**********:OOO..XXOOOOO+****OOOOOO..XXOOOO;***********OOO..XXOOOOO+****OOOOOOO..XXOOOOOO>*****$OOO..XXOOOO:***********OOOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOO;****1=***:OOO..XXOOOOO+****OOOOOO..XXOOOOO+>****$****OOO..XXOOOOO+****OOOOOOO..XXOOOOOO#1***1%OOO..XXOOOO,<*****$$***#OOO..XXOOOOO$***:OOOOOOooXXX                    ",
"                  ...XXOOOOOOO#++OOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOO@++,O***1OOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOO+%#OOOOO..XXOOOOOO#%$?@OOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOO@***:OOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOO#=:,OOO;***=OOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOO,1***:%?-****%OOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOO-**********:OOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOO,<********>@OOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOO%:****1$,OOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOO@+OOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOOOOO..XXOOOOOOOOOOOOOOOOooXXX                    ",
"                  ...X......................X...................X......................X....................X...................X.......................X..................oXXX                    ",
"                  .........................................................................................................................................................oXXX                    ",
"                  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ",
"                  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ",
"                  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                    ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   ",
"                                                                                                                                                                                                   "};
