/* XPM */
/* $XConsortium: Dtaprnt.m.pm /main/2 1996/07/23 12:03:55 drk $ */
static char * Dtaprnt_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor2	m white	c white",
"X	s iconColor1	m black	c black",
"o	s iconColor5	m black	c blue",
"O	s iconGray4	m white	c #969696969696",
"+	s iconGray2	m white	c #c8c8c8c8c8c8",
"@	s iconGray6	m black	c #646464646464",
"#	s iconGray7	m black	c #4b4b4b4b4b4b",
"$	s iconGray5	m black	c #7d7d7d7d7d7d",
"%	s iconGray1	m white	c #e1e1e1e1e1e1",
"&	s iconGray8	m black	c #323232323232",
"*	s iconColor7	m white	c cyan",
"=	s iconGray3	m white	c #afafafafafaf",
/* pixels */
" .............................X ",
" .ooooooooooooooooooooooooooooX ",
" .ooooooooooooooooooooooooooooX ",
"......ooooooooooooooooooo......X",
".OOOOO.ooooooooooooooooo.OOOOOOX",
".OOOOOO.ooooooooooooooo.OOOOOOOX",
".OOOOOOO...............OOOOOOOOX",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
".OOOOOOO............OOOOOOOOOOOX",
".OOOOOOO.++.....+++.@OOOOOOOOOOX",
".OOOOOOO............@OOOOOOOOOOX",
".OOOOOOO.+++++.++++.@OOOOOOOOOOX",
".OOOOOOO............@OOOOOOOOOOX",
".OOOO....+++..+++.+.@.....##OOOX",
".OOO.+$O............@%+++++##OOX",
".OO.++&&&&&&&&&&&&&&&.++++++##OX",
".OO.%%%%%%%%%%%%%%%%%%%%%%%%##OX",
".OO.%+++++++++++++++%@@@@@@%##OX",
".OO.%%%%%%%%%%%%%%%%%@****@%##OX",
".OO.%%$$$$$$$$$$$$$$$@@@@@@%##OX",
".OO.%%%%%%%%%%%%%%%%%%%%%%%%##OX",
".OO.%%%%%%%%%%%%%%%%%%%%%%%%##OX",
".OO.%%&&&&&&&&&&&&&&&&%%%%%%##OX",
".OO.%%&%$$$$$$$$$$$$$&%%%%%%##OX",
".OO.&&%===============&&&&&&##OX",
".OOOO#O$$$$$$$$$$$$$$$####&##OOX",
".OOOO&@@@@@@@@@@@@@@@@&&&&&#OOOX",
".OOOOO&&&&&&&&&&&&&&&&######OOOX",
".OOOOO#################OOOOOOOOX",
".OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"};
