/* XPM */
static char *DtGamesCards_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 110 2",
"   c #000000",
".  c #0C0C0C",
"X  c #131313",
"o  c #1E1E1E",
"O  c #212121",
"+  c #2F2F2F",
"@  c #373737",
"#  c #3B3B3B",
"$  c #454545",
"%  c #4E4E4E",
"&  c #565656",
"*  c #5B5B5B",
"=  c #636363",
"-  c #6B6B6B",
";  c #737373",
":  c #7C7C7C",
">  c #CC0303",
",  c #CD0C0C",
"<  c #CF1212",
"1  c #CF1919",
"2  c #D01515",
"3  c #D11C1C",
"4  c #CB2424",
"5  c #CC2828",
"6  c #D22323",
"7  c #D32A2A",
"8  c #CC3838",
"9  c #D33232",
"0  c #D53B3B",
"q  c #D83D3D",
"w  c #D34444",
"e  c #D84242",
"r  c #D44C4C",
"t  c #D55454",
"y  c #D25959",
"u  c #DB5E5E",
"i  c #D36161",
"p  c #DC6363",
"a  c #D66D6D",
"s  c #DE6B6B",
"d  c #DA7373",
"f  c #DA7A7A",
"g  c #E26B6B",
"h  c #E47777",
"j  c #E17A7A",
"k  c #0000CC",
"l  c #1111CE",
"z  c #0000D3",
"x  c #2E2ECD",
"c  c #3030D1",
"v  c #0101E2",
"b  c #0000EC",
"n  c #0000FF",
"m  c #4444D4",
"M  c #7070DB",
"N  c #848484",
"B  c #8C8C8C",
"V  c #949494",
"C  c #9B9B9B",
"Z  c #9BA2A2",
"A  c #A2A2A2",
"S  c #ADADAD",
"D  c #B4B4B4",
"F  c #BFBFBF",
"G  c #DD9797",
"H  c #DB9A9A",
"J  c #E78A8A",
"K  c #EA9292",
"L  c #E09B9B",
"P  c #ED9898",
"I  c #D9A5A5",
"U  c #DDABAB",
"Y  c #DABABA",
"T  c #E2A3A3",
"R  c #EAB4B4",
"E  c #E3BDBD",
"W  c #9191DF",
"Q  c #B3B3E4",
"!  c #BFC1C1",
"~  c #C1C1C1",
"^  c #C1CACA",
"/  c #CBCBCB",
"(  c #D7C5C5",
")  c #DCCCCC",
"_  c #D5D5D5",
"`  c #DAD2D2",
"'  c #D5DFDF",
"]  c #DBDBDB",
"[  c #E3D4D4",
"{  c #EBD5D5",
"}  c #E4DCDC",
"|  c #EBDCDC",
" . c #F5D0D0",
".. c #F5DEDE",
"X. c #FADEDE",
"o. c #CBCBE5",
"O. c #DCE3E3",
"+. c #DDE9E9",
"@. c #E4E4E4",
"#. c #ECE2E2",
"$. c #E3EBEB",
"%. c #ECECEC",
"&. c #F0E4E4",
"*. c #F8E4E4",
"=. c #FBE9E9",
"-. c #EDF3F3",
";. c #F3F3F3",
":. c #F5F8F8",
">. c #FEFEFE",
",. c None",
/* pixels */
",.,.O.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.O   ,.",
",.,.} ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; O   ,.",
",.,.] n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n O   ,.",
",.,.] n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n O   ,.",
",.,.@.; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; ; n ; O   ,.",
">.>.>.>.>.>.>.>.>.n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n n ; n >.>.>.>.>.>.>.>.  ",
">.S V V V V V V V >.; n n ; n n ; n n ; n n ; b z * k v ; n n ; n n ; n n ; >.V V V V V V V =   ",
">.S V V V V V V V V >.; ; n ; ; n - - l - - x V S Q _ V k ; ; n ; ; n ; ; >.V V V V V V V V =   ",
">.S V V V V V V B B B ;.v - c m V M W / o.%.;.%.%.@.@.;.& n n ; n n ; n >.V V V V V V V V V =   ",
">.S V V V B N N V A D / $.%.%.@.%.@.@.@.O.] _ _ ] _ _ @.D %.>.>.>.>.>.>.V V V V V V V V V V =   ",
">.S V V : C %.%.;.@.@.] ] } ] ] _ ] ] ] ] ] ] ] ] ] ] @.A : V V V V V V V V V V V V V V V V =   ",
">.S V V : ] @.C $ @.] ] ] _ ] ] ] _ S S S S S S S S S D B * ; ; ; ; ; ; ; ; ; : ; B V V V V =   ",
">.S V B ; _ ] O   # / ] ] ] _ ] ] S / =.X.=.X.=.>.>.>.>.>.>.:.>.>.>.:.:.:.>.:.>.@.N B V V V =   ",
">.S V B - / N       : @.] ] ] ] _ C ;.4 > 5 > 8 ' _ _ _ _ _ _ _ _ _ ` _ _ _ _ _ @.C B V V V =   ",
">.S V B ; D ~ +   O _ ] ] ] ] ] _ V @.> , , , > O._ _ ] ] _ _ ] ] _ _ ] ] _ _ _ } V N V V V =   ",
">.S V V : C @._ $ C @.] ] ] ] ] _ V @.w > < > y ' ] ] _ ] ] ] _ _ ] ] _ ] ] ] ] O.B N V V V =   ",
">.S V V N V @.] ] ] ] ] ] ] ] ] _ V @.( 9 > w ] _ ] _ ] _ ] _ ] ] ] _ ] _ ] _ ] } B N V V V =   ",
">.S V V N N ] } ] ] @.] ] } O.] ] B $.] Y i ` ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] @.B N V V V =   ",
">.S V V N : _ @.@.] ] ] ] @.] @._ # @.] O.+.] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] @.V N V V V =   ",
">.S V V B ; / @.} O.@.] @.] ] %.N   %.] ] ] ] } ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] @.V N V V V =   ",
">.S V V B ; ~ @.O.] @.O.] @.@.~ @   %.] ] ] ] ] O.+.+.+.] ] ] +.+.+.+.] ] ] ] ] @.B N V V V =   ",
">.S V V V : D @.} @.@.} @.} ] N .   %.] ] ] ] ] I 5 < 7 H O.( y 1 < y ) @.] O.] $.V N V V V =   ",
">.D V V V : A @.O.} O.} @.@.~ o X   %.] O.] @.Y > 2 2 2 < a w < 2 2 2 r ] } } ] @.V N V V V =   ",
">.S V V V : V @.@.O.@.@.@.@.* X o   %.} } O.+.r 2 3 3 1 3 < < 3 3 3 3 6 I O.O.] %.V N V V V =   ",
">.S V V V N N @.@.@.@.@.%.S X o o . %.} @.] $.6 3 3 3 3 3 3 3 3 3 3 3 2 G @.O.} %.V N V V V =   ",
">.S V V V B ; @.@.@.@.@.@./ @ o o . %.O.@.@.$.3 3 3 3 3 6 3 6 3 6 3 3 2 G +.@.] @.V N V V V =   ",
">.S V V V B - ] @.@.@.@.@.@._ % O . %.@.O.} $.7 6 6 3 6 6 3 3 6 6 3 3 3 H +.} @.%.V N V V V =   ",
">.S V V V V : / %.@.@.#.@.%.%._ * X %.@.@.@.$.d 3 6 6 6 6 6 6 6 6 6 6 0 E @.@.@.%.V N V V V =   ",
">.S V V V V ; D %.@.%.%.@.@.@.%._ $ ;.@.@.@.@.{ 9 6 7 6 6 6 6 6 6 6 6 f %.@.@.@.%.V N V V V =   ",
">.S V V V V : C ;.%.%.@.%.%.%.%.@.V -.@.%.@.@.@.R 7 6 6 6 7 6 7 6 6 t | @.@.@.@.%.V N V V V =   ",
">.S V V V V : N :.%.%.@.%.%.%.%.@.C ;.@.@.@.%.@.@.H 7 6 7 7 7 7 6 r } %.@.%.@.@.%.C N V V V =   ",
">.S V V V V B = :.%.%.%.%.%.%.%.@.A ;.@.@.%.@.@.$.%.L 9 7 7 7 6 r %.@.@.$.@.%.@.;.V N V V V =   ",
">.S V V V V B - ;.%.%.;.%.%.%.%.@.A :.@.%.%.%.@.%.@.-.L 9 7 7 u #.$.%.@.%.%.@.%.%.C N V V V =   ",
">.S V V V V V - / :.%.%.%.;.%.;.#.A ;.%.%.@.%.%.%.%.$.:.T 0 g { %.%.%.%.%.%.%.%.;.V N V V V =   ",
">.S V V V V V ; F >.%.%.%.;.;.;.%.A :.%.%.%.%.%.%.%.%.%.-.E { -.%.%.%.%.%.%.%.%.:.V N V V V =   ",
">.D V V V V V ; V >.;.;.;.;.%.;.@.A >.%.%.%.;.%.%.;.%.%.%.;.%.%.;.%.%.%.%.%.;.%.:.V N V V V =   ",
">.S V V V V V N ; >.;.;.;.;.;.;.%.A >.%.;.%.%.%.;.%.%.;.%.;.%.;.%.;.%.;.%.;.;.%.>.V N V V V =   ",
">.S V V V V V B = >.;.;.;.;.;.:.%.A >.%.%.;.;.-.;.;.;.%.%.;.;.%.;.%.%.;.;.#.| ;.:.A N V V V =   ",
">.S V V V V V B = %.:.;.:.;.;.;.%.S >.;.;.;.;.;.;.%.;.;.;.;.;.;.;.;.;.;.#.g u { >.C N V V V =   ",
">.S V V V V V V = _ >.;.;.;.;.>.:.S >.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.&.j q q p *.C N V V V =   ",
">.S V V V V V V ; A >.>.>.>.>.%./ ; >.;.;.:.;.:.;.;.;.:.;.;.:.;.;.:.;.R q e e e P Z N V V V =   ",
">.S V V V V V V N = A F C ; * * & $ >.:.:.;.;.;.:.:.;.:.:.:.;.:.:.;.:.R q e e e K Z N V V V =   ",
">.S V V V V V V B : - = - ; : : : = %.>.:.:.:.:.:.:.:.:.:.:.:.:.:.:.>...h J K g  .V N V V V =   ",
">.S V V V V V V V B N N N B B B B ; : ~ Y ! ! F ! Y F F ! Y F ~ ~ ~ ! ! ^ ! ^ ^ A - N V V V =   ",
">.S V V V V V V V V V V V V V V V B ; - - - - - - - - - - - - - - - - - - - - - - N V V V V =   ",
">.S V V V V V V V V V V V V V V V V B N N N N N N N N N N N N N N N N N N N N N B B V V V V =   ",
">.= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =   ",
"                                                                                                "
};
