/* XPM */
static char * dvi_l_xpm[] = {
"48 48 185 2",
"  	c None",
". 	c #8D8D8D",
"+ 	c #909090",
"@ 	c #F2F2F2",
"# 	c #F1F1F1",
"$ 	c #F0F0F0",
"% 	c #EFEFEF",
"& 	c #EDEDED",
"* 	c #EAEAEA",
"= 	c #E7E7E7",
"- 	c #DDDDDD",
"; 	c #D4D4D4",
"> 	c #CFCFCF",
", 	c #C5C5C5",
"' 	c #848484",
") 	c #FFFFFF",
"! 	c #FEFEFE",
"~ 	c #F5F5F5",
"{ 	c #E8E8E8",
"] 	c #9E9E9E",
"^ 	c #ADADAD",
"/ 	c #888888",
"( 	c #FAFAFA",
"_ 	c #E3E3E3",
": 	c #A5A5A5",
"< 	c #F7F7F7",
"[ 	c #CBCBCB",
"} 	c #B8B8B8",
"| 	c #AAAAAA",
"1 	c #FCFCFC",
"2 	c #C3C3C3",
"3 	c #FDFDFD",
"4 	c #F3F3F3",
"5 	c #AFAFAF",
"6 	c #FBFBFB",
"7 	c #CDCDCD",
"8 	c #A0A0A0",
"9 	c #F4F4F4",
"0 	c #F9F9F9",
"a 	c #BEBEBE",
"b 	c #F8F8F8",
"c 	c #F6F6F6",
"d 	c #B5B5B5",
"e 	c #E2E2E2",
"f 	c #E4E4E4",
"g 	c #A8A8A8",
"h 	c #B0B0B0",
"i 	c #B7B7B7",
"j 	c #B6B6B6",
"k 	c #C9C9C9",
"l 	c #E1E1E1",
"m 	c #EEEEEE",
"n 	c #E5E5E5",
"o 	c #D0D0D0",
"p 	c #C1C1C1",
"q 	c #9D9D9D",
"r 	c #979797",
"s 	c #8A8A8A",
"t 	c #7A7A7A",
"u 	c #636363",
"v 	c #575757",
"w 	c #4A4A4A",
"x 	c #929292",
"y 	c #A3A3A3",
"z 	c #B3B3B3",
"A 	c #B4B4B4",
"B 	c #CACACA",
"C 	c #7E7E7E",
"D 	c #727272",
"E 	c #555555",
"F 	c #E9E9E9",
"G 	c #E0E0E0",
"H 	c #D3D3D3",
"I 	c #C7C7C7",
"J 	c #DADADA",
"K 	c #A9A9A9",
"L 	c #969696",
"M 	c #9B9B9B",
"N 	c #E6E6E6",
"O 	c #D6D6D6",
"P 	c #707070",
"Q 	c #868686",
"R 	c #9C9C9C",
"S 	c #ACACAC",
"T 	c #B1B1B1",
"U 	c #B2B2B2",
"V 	c #EBEBEB",
"W 	c #D9D9D9",
"X 	c #C0C0C0",
"Y 	c #A7A7A7",
"Z 	c #D2D2D2",
"` 	c #919191",
" .	c #AEAEAE",
"..	c #DFDFDF",
"+.	c #C8C8C8",
"@.	c #BCBCBC",
"#.	c #8C8C8C",
"$.	c #646464",
"%.	c #787878",
"&.	c #A6A6A6",
"*.	c #ABABAB",
"=.	c #9F9F9F",
"-.	c #D8D8D8",
";.	c #ECECEC",
">.	c #D7D7D7",
",.	c #BFBFBF",
"'.	c #DBDBDB",
").	c #626262",
"!.	c #767676",
"~.	c #A4A4A4",
"{.	c #CCCCCC",
"].	c #BABABA",
"^.	c #A2A2A2",
"/.	c #C6C6C6",
"(.	c #BDBDBD",
"_.	c #DCDCDC",
":.	c #616161",
"<.	c #747474",
"[.	c #A1A1A1",
"}.	c #999999",
"|.	c #CECECE",
"1.	c #858585",
"2.	c #DEDEDE",
"3.	c #C2C2C2",
"4.	c #5F5F5F",
"5.	c #8B8B8B",
"6.	c #D5D5D5",
"7.	c #BBBBBB",
"8.	c #838383",
"9.	c #3D70C9",
"0.	c #3C6FC8",
"a.	c #3B6FC7",
"b.	c #3A6EC6",
"c.	c #396DC5",
"d.	c #386CC4",
"e.	c #717171",
"f.	c #0047C1",
"g.	c #797979",
"h.	c #989898",
"i.	c #606060",
"j.	c #828282",
"k.	c #D1D1D1",
"l.	c #B9B9B9",
"m.	c #808080",
"n.	c #1857C2",
"o.	c #8EA5CB",
"p.	c #CBCCCD",
"q.	c #878787",
"r.	c #C4C4C4",
"s.	c #B3B6BC",
"t.	c #909AAB",
"u.	c #6579A1",
"v.	c #3E6FC4",
"w.	c #7894C4",
"x.	c #B8BCC3",
"y.	c #9A9A9A",
"z.	c #8F8F8F",
"A.	c #AEB1B7",
"B.	c #8C95A6",
"C.	c #61759D",
"D.	c #3B6DC1",
"E.	c #7490C0",
"F.	c #B0B4BB",
"G.	c #1755C1",
"H.	c #869CC3",
"I.	c #C0C1C2",
"J.	c #939393",
"K.	c #838C9C",
"L.	c #2653A6",
"M.	c #2452A4",
"N.	c #788191",
"O.	c #66799B",
"P.	c #A2A4A8",
"Q.	c #9FA1A5",
"R.	c #627597",
"S.	c #8E8E8E",
"T.	c #003C96",
"U.	c #898989",
"V.	c #949494",
"W.	c #959595",
"X.	c #7C7C7C",
"Y.	c #6F6F6F",
"Z.	c #676767",
"`.	c #5A5A5A",
" +	c #565656",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                . . . . . . . . . . . . . . . . . . . . .                                       ",
"                + @ @ @ @ @ @ @ @ @ # $ % & * = - ; > , . '                                     ",
"                + @ ) ) ) ) ) ) ) ) ) ) ) ) ) ! ) ~ { > ] ^ /                                   ",
"                + @ ) ) ) ) ) ) ) ) ) ) ) ) ) ! ) ) ( _ : < [ /                                 ",
"                + @ ) ) } } } } ) ) ) ) ) ) ) ! ) ! ! & | 1 1 2 /                               ",
"                + # 3 3 1 1 1 1 3 3 ! ) ) ) ) ! ! 3 3 4 5 ( 1 6 2 /                             ",
"              7 7 7 7 7 7 7 7 8 # 9 0 3 ) ) ! 3 3 1 1 < a 4 0 b c d /                           ",
"              7 6 0 ~ $ & e f 7 8 8 g h d i j d d 6 6 0 k l { # m 1 d /                         ",
"              7 6 0 c @ % n f 7 o 8 o f 4 ( 1 6 6 ( ( 0 p | q r s t u v w                       ",
"              7 6 h h h h = f 8 8 8 8 x y ^ z A A ( 0 b 4 4 l B h r C D E                       ",
"              7 6 ) ) 4 $ F f G H I 8 h 7 n 9 0 0 0 b < c c @ = J , K L E                       ",
"              7 6 M M M M * N O [ k 8 P Q R S T U b < c m m V N W > X Y E                       ",
"              7 ( ! ! 3 3 V f Z > 7 8 `  .o * ~ < < c $ * * l ..J H +.@.E                       ",
"              7 0 M M M M M M M #.; 8 $.%.x &.5 T h ^ *.g g 8 =.] ; k +.E                       ",
"              7 c 3 3 1 1 ( b 9 J -.8 s &.B n # % % ;.V n n e J >.7 , ,.E                       ",
"              7 c M #.M ( M M #.#.'.8 ).!.+ ~.S  .^ *.g : : 8 =.M {.2 ].E                       ",
"              7 b 6 0 < ~ M & & #.'.8 / ^./.l & % & { N l l - J -.H /.(.E                       ",
"              7 b M #.#.m #.#.#.#._.8 :.<.. [.g | g : y 8 8 ] M }.|.k a E                       ",
"              7 ~ # m * N ..W H .._.8 1.8 2 2.= { N _ G '.'.-.; o {.+.3.E                       ",
"              7 9 #.#.#.#.#.#.#.#._.8 4.D 5.q : F N _ ..'.'.-.6.o k X 7.E                       ",
"              7 @ V V F = f _ G .._.8 8.] X J n N e 9.0.a.a.b.c.d.k 2 ].E                       ",
"              8 8 8 8 8 8 8 8 8 8 8 8 Q e.s M ^.l 2.f.f.f.f.f.f.f.+.p (.E                       ",
"                g.&.h.5.i.1.' ' 8.j.i.+ &.2 O ..2._.'.>.H H k.{.k , p l.E                       ",
"                m.d  .~.<.8 ] ] R R e.: 8.x M =.- J f.f.n.o.p.[ /.p (.d E                       ",
"                q.I [ r.#.p X a a a / p B ; J - _.>.s.t.u.f.v.w.x.a ].d E                       ",
"                . 6.G - =.J W -.>.O y.6.y.R q q >.; k.> {.{.f.f.f.l.i z E                       ",
"                z.J * = &.f f e l G 8 '.'.-.-.H Z o A.B.C.f.D.E.F.} T 5 E                       ",
"                + J * { Y : : ~.y y ^._.] M y.L o > f.f.G.H.I.,.].j h  .E                       ",
"                + W { = f f f e l - _.W -.H k.> |.[ +.r.3.(.@.].d U ^ *.E                       ",
"                + >.N _ l y y 8 =.q W O h.L J.` +., K.L.f.f.f.M.N.5 S K E                       ",
"                + ; - - - - - _.W O H o 7 B I r.p (.f.O.P.d Q.R.f.Y &.~.E                       ",
"                + k.G 2.8 8 8 ] R h.h.L J.+ S.5.@.l.f.} A U U h f.Y &.~.E                       ",
"                + |.2.'.'.- - >.; o o {.+./.p (.].l.f.T.T.T.T.T.f.&.[.=.E                       ",
"                + [ -.-.M R M h.L J.x + S.#.U.Q l.A f.f.f.f.f.f.f.8 R }.E                       ",
"                + +.; Z k.; Z o [ +./.r.p ,.].j U h S K &.&.: [.=.y.}.r E                       ",
"                + , k.> 7 o |.B I r.2 X @.].j h  .S K : ^.^.8 q }.h.r V.E                       ",
"                + X k +.I I , 3.,.(.7.} d z 5 S | Y ~.y ] ] q y.r W.J.J.E                       ",
"                + q r + s ' X.!.Y.Z.4.`. + +E E E E E E E E E E E E E E E                       ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
