/* XPM */
static char *fontforge_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 152 2 ",
"   c black",
".  c #281F05",
"X  c #262111",
"o  c #252525",
"O  c #272829",
"+  c #2A2C2A",
"@  c #2E302D",
"#  c #343930",
"$  c #393B35",
"%  c #3F3F3F",
"&  c #404535",
"*  c #45453B",
"=  c #454A3E",
"-  c #4F5336",
";  c #4D523A",
":  c #58543D",
">  c #565C39",
",  c #666B38",
"<  c #787C37",
"1  c #454644",
"2  c #454947",
"3  c #4A4B4B",
"4  c #535342",
"5  c #5E5441",
"6  c #53544E",
"7  c #535353",
"8  c #5D5D5D",
"9  c #695F50",
"0  c #6D6641",
"q  c #676349",
"w  c #7E7142",
"e  c #7A724E",
"r  c #6B6658",
"t  c #7C7358",
"y  c #626262",
"u  c #6C6C6C",
"i  c #767676",
"p  c #7B7B7B",
"a  c #8C7B37",
"s  c #947E38",
"d  c #907F43",
"f  c #B68F17",
"g  c #BA9317",
"h  c #8C9037",
"j  c #B39126",
"k  c #A68E35",
"l  c #B89B39",
"z  c #A8AA20",
"x  c #A1A536",
"c  c #BBBC3E",
"v  c #CBA52C",
"b  c #CFA92D",
"n  c #D3AC2F",
"m  c #CAA731",
"M  c #C9A93F",
"N  c #D2AD32",
"B  c #D0AE3C",
"V  c #E1C001",
"C  c #E9CE08",
"Z  c #DCD936",
"A  c #F8DE3E",
"S  c #EDE420",
"D  c #E5E128",
"F  c #8D8253",
"G  c #989A52",
"H  c #A68F46",
"J  c #B59B45",
"K  c #BB9F43",
"L  c #AC955A",
"P  c #B89E57",
"I  c #9B8F6C",
"U  c #B09E68",
"Y  c #AB9C74",
"T  c #A89E7D",
"R  c #BCA76F",
"E  c #BBA86A",
"W  c #AEA27C",
"Q  c #CDAC44",
"!  c #C2A749",
"~  c #D1B04A",
"^  c #C2A955",
"/  c #CEB257",
"(  c #CBB05B",
")  c #C0A960",
"_  c #CCB97C",
"`  c #CFCF46",
"'  c #CFD041",
"]  c #DCDA43",
"[  c #F6DA47",
"{  c #F8DC47",
"}  c #F4D956",
"|  c #F8DE58",
" . c #E6E243",
".. c #F8E140",
"X. c #F8E54B",
"o. c #EFE752",
"O. c #F6EB5E",
"+. c #F8E858",
"@. c #CEC17F",
"#. c #F3DA6B",
"$. c #F8DE6D",
"%. c #F7EB61",
"&. c #848484",
"*. c #8B8B8B",
"=. c #939393",
"-. c #9C9C9C",
";. c #A39B8C",
":. c #A59F93",
">. c #A9A188",
",. c #B3A385",
"<. c #BBB58F",
"1. c #ADA695",
"2. c #AAA69A",
"3. c #A3A3A3",
"4. c #AAA8A2",
"5. c #ABACAC",
"6. c #B1ACA1",
"7. c #AFB0B0",
"8. c #B3B3B3",
"9. c #BCBCBC",
"0. c #C2B380",
"q. c #CECF9C",
"w. c #E9D58E",
"e. c #F3DC81",
"r. c #F8E184",
"t. c #F3E096",
"y. c #F3E4AA",
"u. c #F3E9BC",
"i. c #C4C5C4",
"p. c #CBCBCB",
"a. c #D3D3D3",
"s. c #DBD9D4",
"d. c #D7D7D8",
"f. c #D7D8D8",
"g. c #DCDCDC",
"h. c #F6EDCC",
"j. c #F7F1DA",
"k. c #DFE0E0",
"l. c #E4E4E4",
"z. c #E6E7E8",
"x. c #E7E8E8",
"c. c #ECECEC",
"v. c #F8F4E5",
"b. c #F3F1E9",
"n. c #F8F6EE",
"m. c #EFEFF0",
"M. c #EFF0F0",
"N. c #F4F4F4",
"B. c #F9F8F5",
"V. c #F7F8F8",
"C. c #FBFBFB",
"Z. c None",
/* pixels */
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.N.m.M.M.M.M.N.M.N.M.N.M.N.N.N.N.N.N.N.N.N.N.N.N.N.V.V.N.V.V.N.N.C.N.N.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.m.l.z.z.z.x.x.x.x.c.c.c.c.c.c.c.c.c.M.M.M.M.M.M.M.M.m.m.m.M.m.b.N.M.M.N.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.m.z.z.z.x.x.c.c.c.c.c.c.c.c.c.M.M.M.M.M.M.M.M.N.M.M.N.m.M.m.N.N.M.M.M.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.m.z.x.c.x.x.k.c.c.c.c.c.c.M.M.M.l.M.M.l.M.M.M.M.N.M.M.N.N.g.m.m.M.N.M.N.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.M.z.x.x.c.x.a.c.c.c.c.M.M.M.M.M.g.M.M.g.M.N.N.M.N.N.N.m.N.g.c.N.N.M.N.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.M.x.x.g.a.i.5.i.i.i.i.i.i.i.i.i.5.9.i.5.i.i.i.i.i.i.p.p.p.9.p.l.c.N.N.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.N.x.c.c.c.x.&.&.p p i i i u u u 7 u u y i i p I &.&.&.&.&.&.c.N.N.N.N.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.M.c.g.a.i.9.i p i i u u i &.p i 7 8 y 8 &.*.&.p i i p p p p i.a.k.N.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.M.c.c.c.c.l.*.=.*.3.k.m.c.c.N.N.&.i i *.N.c.c.N.V.z.7.*.*.=.z.V.V.V.N.V.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.N.c.c.c.c.k.=.*.5.M.N.m.N.N.N.N.*.p p *.N.N.V.V.V.V.V.9.*.=.x.N.V.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.M.c.M.c.c.g.=.-.M.N.m.N.m.N.N.N.*.&.p *.N.V.V.V.V.V.V.V.=.=.l.C.V.N.N.C.Z.Z.Z.Z.Z.Z.",
"Z.7 1 C Z.Z.N.m.c.c.M.g.=.5.N.M.N.N.N.N.N.N.=.*.*.*.V.V.V.V.V.V.C.V.8.-.l.C.N.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.X 6 G <.Z.N.m.M.M.M.g.3.8.M.N.N.N.N.N.N.V.=.=.=.=.V.V.V.V.V.V.C.C.a.3.l.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.g ^ 5.q.V b.m.m.M.m.d.l.9.M.N.N.N.N.V.N.V.-.-.=.=.V.C.V.V.C.C.C.C.l.M.l.C.V.C.B.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.W 0.3 z [ c.M.m.M.d.l.i.c.N.N.N.N.V.V.V.-.3.3.-.V.C.C.C.C.V.C.M.m.M.l.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.f k 2 ` } b.M.N.d.z.M.a.z.N.V.V.V.V.V.3.5.3.-.V.V.C.V.C.C.C.N.C.N.k.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.g a 1 ] #.m.m.s.c.N.N.c.c.N.N.V.V.V.3.7.7.3.V.V.C.C.C.C.C.C.C.C.k.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.g F =  .e.N.d.c.N.V.N.N.V.V.V.V.V.4.8.8.3.C.C.C.C.C.C.C.C.C.C.l.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.. b e = o.t.l.N.N.N.V.V.V.V.C.V.C.3.7.5.3.C.C.C.C.C.C.C.C.C.C.x.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.  >.b q ; O.y.N.V.V.V.V.V.C.V.C.C.3.5.5.-.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.8.T n 4 > O.u.N.V.N.V.V.C.C.C.V.-.3.3.-.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.f.7.Y n * , +.h.N.C.V.V.C.C.C.C.=.*.=.-.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.m.a.7.U B $ < X.j.C.C.C.V.V.C.C.=.*.*.*.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.N.x.a.5.E M @ h ..v.C.V.C.C.C.C.*.&.&.*.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.M.c.p.5.) ! O x A n.C.C.C.C.C.*.p p *.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.N.N.z.p.4.^ J o c { B.C.M.N.C.*.i i *.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.N.N.N.l.p.4.( H o ' | C.C.l.g.&.u u &.C.C.C.C.C.C.C.C.C.C.V.V.V.V.C.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.N.N.V.N.z.i.4./ d @ Z $.C.C.a.&.u u p N.C.C.C.C.C.B.B.V.V.V.N.N.N.N.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.N.V.V.N.l.i.2.Q w # D r.C.x.y y y u C.C.C.C.C.C.V.B.M.M.m.m.m.m.m.C.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.C.N.N.C.M.l.9.1.~ 0 * S w.m.6 8 8 7 C.C.C.C.B.m.x.m.c.x.l.z.z.l.c.m.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.N.N.N.C.C.C.C.N.l.9.>.m : ; 0.2.3 7 7 1 i.C.C.C.N.g.l.k.g.a.a.p.p.g.g.=.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.N.C.N.N.C.C.N.g.5.I j d @.,.1 6 3 1 y -.g.m.a.a.p.9.8.5.5.7.p.a.-.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.V.C.N.C.C.V.C.C.N.g.5.5 L l _ 9 3 3 1 3 3 % 3 g.p.5.-.4.9.d.l.p.3.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.V.V.B.V.V.x.g.p.i.8.=.I L K R i.p.i.p.p.i.i.9.-.*.C.C.N.l.a.5.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.V.V.C.C.C.C.C.C.C.N.g.9.3.Y t ;.C.C.C.N.m.c.g.8.5.C.N.l.a.7.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.V.V.V.C.C.C.C.C.C.C.N.k.i.7.1.r g.C.B.N.m.x.d.5.9.B.l.a.8.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.N.B.V.V.C.C.C.C.C.C.C.C.V.x.a.9.i.6.V.B.m.m.l.p.3.g.l.a.8.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.V.B.V.V.C.C.C.C.C.C.C.C.C.C.N.g.d.l.N.N.N.c.l.i.5.l.d.8.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.V.B.V.V.C.V.C.C.C.C.C.C.C.C.C.V.m.x.m.B.m.c.g.i.i.a.5.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.V.V.V.V.V.C.C.C.C.C.C.C.C.C.C.C.C.C.V.V.B.m.x.g.p.a.3.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.V.B.V.V.C.V.C.C.C.C.C.C.C.C.C.C.C.C.B.N.m.c.k.a.3.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.V.N.c.-.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.",
"Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z."
};
