/* XPM */
/* $XConsortium: IcCM.m.pm /main/3 1995/07/18 17:12:51 drk $ */
static char * IcCM_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 11 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray3     m white c #adadadadadad",
"o	s iconColor2	m white	c white",
"O    s iconGray5     m black c #737373737373",
"+    s iconGray4     m white c #949494949494",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s iconGray7     m black c #424242424242",
"$    s selectColor m white c #737373737373",
"%	s iconColor1	m black	c black",
"&    s iconGray6     m black c #636363636363",
/* pixels */
"      .                 .       ",
"  XXX.oXOXXXXXXXXXXXXXX.oXOXX   ",
"  X...oX+...............oX+@#$  ",
"  X.@Xo+O@@@@@@@@@@@@@@Xo+OO#$  ",
"  X.@Xo+O@@@@@@@@@@@@@@X.+OO#$  ",
"  X.@%+%@@@@@@@@@@@@@@@%+%@O#$  ",
"  X.@@%@@@@@@@@@@@@@@@@@%@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@@@@@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@oo..OO#$  ",
"  X.@@@@@@@@@@@@@@@@@@o.XO&O#$  ",
"  X.@@@@@@@@@@@@@@@@@@.XO&@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@.O&@@O#$  ",
"  X.@@@@@@@@@@@@@@@@@@O&@@@O#$  ",
"  X.OOOOOOOOOOOOOOOOOOOOOOO##$  ",
"  X##########################$  ",
"   $$$$$$$$$$$$$$$$$$$$$$$$$$$  "};
