/* XPM */
static char *inkscape_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 137 2 ",
"   c #010101",
".  c #070709",
"X  c #070809",
"o  c #0B0C0C",
"O  c #0D0E11",
"+  c #0F1013",
"@  c #131414",
"#  c #15161B",
"$  c #17191E",
"%  c #1B1B1B",
"&  c #1B1D23",
"*  c #1E2025",
"=  c #1E2128",
"-  c #232323",
";  c #22242B",
":  c #2C2C2C",
">  c #262931",
",  c #292B34",
"<  c #2C2E38",
"1  c #2F3031",
"2  c #2E313C",
"3  c #343433",
"4  c #31353E",
"5  c #36383B",
"6  c #3B3B3C",
"7  c #333642",
"8  c #363A46",
"9  c #3C3E44",
"0  c #373B48",
"q  c #393D49",
"w  c #3D414E",
"e  c #3E4351",
"r  c #434444",
"t  c #43454C",
"y  c #4C4C4C",
"u  c #424553",
"i  c #454956",
"p  c #4B4D52",
"a  c #454A5A",
"s  c #494D5D",
"d  c #4E5053",
"f  c #525253",
"g  c #52545B",
"h  c #5A5A5A",
"j  c #60605F",
"k  c #4A4F60",
"l  c #4D5264",
"z  c #525665",
"x  c #5B5C61",
"c  c #515769",
"v  c #545A6D",
"b  c #595C68",
"n  c #575D71",
"m  c #595F73",
"M  c #5F6064",
"N  c #5D616B",
"B  c #5C6275",
"V  c #5F657B",
"C  c #626263",
"Z  c #65666A",
"A  c #6B6B6B",
"S  c #606575",
"D  c #666A75",
"F  c #696B74",
"G  c #61677C",
"H  c #62697F",
"J  c #6E717B",
"K  c #727272",
"L  c #71747D",
"P  c #7A7A7A",
"I  c #666C84",
"U  c #686F87",
"Y  c #6C7286",
"T  c #6C738A",
"R  c #757781",
"E  c #7B7D83",
"W  c #777C8F",
"Q  c #747B90",
"!  c #797F93",
"~  c #7F8085",
"^  c #7D8394",
"/  c #7F8498",
"(  c #848484",
")  c #848588",
"_  c #8A8A8B",
"`  c #838690",
"'  c #858891",
"]  c #8B8D93",
"[  c #868C9D",
"{  c #8D919C",
"}  c #949495",
"|  c #92949C",
" . c #97989E",
".. c #9C9C9C",
"X. c #8B8FA0",
"o. c #8D93A2",
"O. c #9195A2",
"+. c #9699A4",
"@. c #9D9EA2",
"#. c #979BAA",
"$. c #9B9EAA",
"%. c #9FA1A5",
"&. c #9DA1AC",
"*. c #A4A4A4",
"=. c #A4A6AC",
"-. c #A6A8AE",
";. c #ACACAC",
":. c #A2A6B2",
">. c #A6A9B5",
",. c #ABADB3",
"<. c #ABAEBA",
"1. c #AEB1BB",
"2. c #B4B4B4",
"3. c #B3B5BB",
"4. c #B7B9BC",
"5. c #BABABA",
"6. c #B2B6C0",
"7. c #B6B9C2",
"8. c #BDBEC3",
"9. c #C3C3C3",
"0. c #C3C5CA",
"q. c #CBCCCD",
"w. c #CDCFD4",
"e. c #CFD0D2",
"r. c #D3D4D5",
"t. c #D4D5DA",
"y. c #D7D8DC",
"u. c #DBDBDC",
"i. c #DCDDE1",
"p. c #E2E2E3",
"a. c #E6E7E9",
"s. c #ECECEC",
"d. c #EEEFF1",
"f. c #F4F4F4",
"g. c #F7F7F8",
"h. c #FEFEFE",
"j. c None",
/* pixels */
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.          j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  5 P  .' g . j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.. Z +.D B G | } + j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  A +.J p.h.y.O.#.$.+ j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  C @.J g.h.h.h.g.1.&.=.O j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  h *.b g.h.h.h.f.d.s.>.>.-.O j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  h *.d f.h.h.h.g.d.a.p.i.$.<.-.o j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.  f *.r s.h.h.h.f.s.p.i.y.t.w.o.1.:.X j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.  y *.6 a.h.h.g.d.a.p.y.t.w.q.0.0.o.1.@.X j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.  r *.3 p.h.h.g.d.a.u.t.w.q.9.8.7.6.6.[ 1.+.X j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.  6 ..1 u.h.h.g.d.p.u.r.q.0.8.4.3.1.<.>.>./ <.{ . j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.  3 } : r.h.h.g.s.p.u.q.9.9.4.1.,.-.=.&.$.$.#.^ >.` . j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.  1 _ : q.h.h.g.s.p.;.q.9.5.2.;.*.*.@.+.| | { { { Q :.E   j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.  - P - 9.h.h.g.s.p._ j 8.5.;.*... .| ] ] ' ` ` B ^ / T &.R . j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.  * A % 2.h.h.g.s.p.q.@ r 5.;.*.} } _ ) ~ E R R J l n Y U U #.F   j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.  % h % r h.h.g.s.u.r.j   - ;.*.} _ r * 9 f Z F F b e l n V I U o.m   j.j.j.j.j.j.j.",
"j.j.j.j.j.  @ f %   r 5.2..._ P C .   . ..} A @   . O # & , 9 w e a l n V I T [ z   j.j.j.j.j.j.",
"j.j.j.j.  o r @                         P 3         X O $ & > 2 0 e a l n V I T ` s   j.j.j.j.j.",
"j.j.j.  o 3 +                           .             X O $ & > 2 0 e k l m V U T W i   j.j.j.j.",
"j.j.  . - o                                             X + $ = > 2 q e s c m V U T T 8   j.j.j.",
"j.j.  + X                                                 o O $ = , 2 q e s c m H U U G &   j.j.",
"j.    X                                                     o + $ ; , 2 0 e s c m I I I l . j.j.",
"j.        .                                                 . X + $ ; < 7 q i k v m H I v O   j.",
"j.                                                            . o # & ; < 7 w i k v m B a X   j.",
"j.j.j.                                                          o @ & 1 7 9 t i a k k i $   j.j.",
"j.j.j.j.j.j.                                              . o % - 1 6 r d g g g u q < O   j.j.j.",
"j.j.j.j.j.j.j.j.j.          .                           X @ - 1 6 r h Z K x 9 , & O   j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.. o @ - : 3 5 3 : . .             O % : 6 y Z C 6 % + X .   j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.X % 1 r h A P ( _ ..A *.j @ .     . o @ % 1 : + . .     j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.    o 1 r y f f f f h A _ ..*.2.5.*.@       .           j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.      o % : 6 r r r r 6 3 3 y K _ ..;.K               j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.        . X + % - 1 3 3 3 : - - : r h -               j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.            . O @ - : : - % @ o o                   j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.              @ - : - % @ o .                     j.j.j.j.o y h % j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.      . % - % % o X .                       j.j.    . . .   j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.    o % - - @ + .           . . .       j.j.j.j.          j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.    j.j.  . o % - % @ o X         + o           j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.  y 5   j.  X o @ % % @ o .     o % X         j.j.j.  5 . j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.        j.j.  @ o o @ @ @ X .   O %       j.j.j.j.j.j.j.    j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.    j.j.j.  . X % - @ o X     - X   j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.        o : X .     : o   j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.    % -     o 1 :     j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.    3 : 3 6 - .     j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.  X @ @         j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.            j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j."
};
