/* XPM */
static char *nedit_32[] = {
/* width height num_colors chars_per_pixel */
"    32    32        9            1",
/* colors */
". c None",
"# c #cccccc",
"a c #000066",
"b c #0000cc",
"c c #999999",
"d c #666666",
"e c #009900",
"f c #ffffff",
"g c #000000",
/* pixels */
"................................",
"................................",
"..####....#####a................",
"..#bbb#...#bbbaa................",
"...#bbb#....baa.................",
"...#bbbb#...ba..................",
"...#bbbbb#..ba..................",
"...#ba#bbb#.ba..................",
"...#ba.#bbb#ba..................",
"...#ba..#bbbba..................",
"...#ba...#bbba..................",
"...#ba.########################.",
"...#ba.#eeeeeeeeeeeeeeeeeeeeeed.",
"..##ba.#eefffeffefffffeeeeeffed.",
"..#bbba#eeeeeeeeeeeeeeeeeeeeeed.",
"..#aaaa#ccccccccccccccccccccccd.",
".......#cfffffffffffffffffffccd.",
".......#cffggggggfffffffffffccd.",
".......#cfffffffffffffffffffccd.",
".......#cffffgggggffggffffffccd.",
".......#cfffffffffffffffffffccd.",
".......#cffffffgggggffffffffccd.",
".......#cfffffffffffffffffffccd.",
".......#cffffggggfffffffffffccd.",
".......#cfffffffffffffffffffccd.",
".......#cffggggggfffffffffffccd.",
".......#ccccccccccccccccccccccd.",
".......#ccccccccccccccccccccccd.",
".......dddddddddddddddddddddddd.",
"................................",
"................................",
"................................"
};
