/* XPM */
static char *nedit_48[] = {
/* width height num_colors chars_per_pixel */
"    48    48        9            1",
/* colors */
". c None",
"# c #cccccc",
"a c #000066",
"b c #0000cc",
"c c #999999",
"d c #666666",
"e c #009900",
"f c #ffffff",
"g c #000000",
/* pixels */
"................................................",
"................................................",
"................................................",
"..######a......#######a.........................",
"..#bbbbb#a.....#bbbbaaa.........................",
"..###bbbb#a.....#bbaaaa.........................",
"....##bbbb#a.....#baaa..........................",
".....#bbbbb#a....#baa...........................",
".....#bbbbbb#a...#baa...........................",
".....#bbbbbbb#a..#baa...........................",
".....#baa#bbbb#a.#baa...........................",
".....#baa.#bbbb#a#baa...........................",
".....#baa..#bbbb##baa...........................",
".....#baa...#bbbb#baa...........................",
".....#baa....#bbbbbaa...........................",
".....#baa.....#bbbbaa...........................",
".....#baa.####################################..",
".....#baa.#ccccccccccccccccccccccccccccccccccd..",
"....##baa.#ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecd..",
"...##bbaa.#ceefffffeefffefffffffeeeeeefefefecd..",
"...#bbbbaa#cefffffeefffefffffffeeeeeeefefefecd..",
"...#bbbbba#ceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecd..",
"...#aaaaaa#ccccccccccccccccccccccccccccccccccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffgggggggggfffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffgggggggggffffggggfffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffffffgggfffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffffffgggfffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffffffgggggggfffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffffgggggfffffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccfffgggggggggfffffffffffffffffcccd..",
"..........#ccfffffffffffffffffffffffffffffcccd..",
"..........#ccccccccccccccccccccccccccccccccccd..",
"..........#ccccccccccccccccccccccccccccccccccd..",
"..........#ccccccccccccccccccccccccccccccccccd..",
"..........dddddddddddddddddddddddddddddddddddd..",
"................................................",
"................................................",
"................................................",
"................................................",
"................................................"
};
