/* XPM */
static char *okular_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 127 2 ",
"   c #1D1D1D",
".  c #232323",
"X  c #2A2A2A",
"o  c #343434",
"O  c #3A3A3A",
"+  c #444444",
"@  c #4C4C4C",
"#  c #545454",
"$  c #5B5B5B",
"%  c #636363",
"&  c #6B6B6B",
"*  c #747474",
"=  c #7B7B7B",
"-  c #2177AD",
";  c #2278AE",
":  c #247CB3",
">  c #2B7EB2",
",  c #2781B9",
"<  c #2A84BD",
"1  c #3082B6",
"2  c #3A86B6",
"3  c #3F89B7",
"4  c #3F8EBF",
"5  c #4F85A7",
"6  c #5385A5",
"7  c #5888A6",
"8  c #4788B1",
"9  c #4D8DB5",
"0  c #4A8FBA",
"q  c #5A8FB1",
"w  c #4D93BF",
"e  c #6A94AE",
"r  c #2B87C1",
"t  c #2D8AC5",
"y  c #2F8EC9",
"u  c #358DC4",
"i  c #308FCA",
"p  c #3990C6",
"a  c #3191CD",
"s  c #3394D1",
"d  c #3997D2",
"f  c #3F9AD3",
"g  c #4491C1",
"h  c #459ACF",
"j  c #5296C1",
"k  c #5699C4",
"l  c #4A9ED2",
"z  c #629EC3",
"x  c #59A1CF",
"c  c #54A3D5",
"v  c #5BA4D2",
"b  c #56A6D9",
"n  c #65A0C5",
"m  c #69A3C6",
"M  c #61A4CF",
"N  c #6CA5C8",
"B  c #76ACCD",
"V  c #64A9D4",
"C  c #6AACD6",
"Z  c #75B0D5",
"A  c #78B0D4",
"S  c #71B1D9",
"D  c #7BB6DB",
"F  c #838383",
"G  c #8C8C8C",
"H  c #949494",
"J  c #9A9A9A",
"K  c #92AAB9",
"L  c gray64",
"P  c #ACACAC",
"I  c #A9B6BE",
"U  c #B4B4B4",
"Y  c #BCBCBC",
"T  c #86AEC7",
"R  c #9AB9CC",
"E  c #83B6D6",
"W  c #8BB7D2",
"Q  c #8DB9D4",
"!  c #81B7D8",
"~  c #82B8DB",
"^  c #8ABCDB",
"/  c #90B9D3",
"(  c #93BFDB",
")  c #A6B7C2",
"_  c #A0B8C7",
"`  c #ABBDC9",
"'  c #92C1DE",
"]  c #9EC3DA",
"[  c #BAC5CC",
"{  c #A0C0D4",
"}  c #A5C5D9",
"|  c #A7C8DC",
" . c #B1CADA",
".. c #A3CAE2",
"X. c #B2CFE1",
"o. c #B4D2E4",
"O. c #BBD4E4",
"+. c #BED9EB",
"@. c gray77",
"#. c #CBCBCB",
"$. c #C2CBD1",
"%. c #D3D3D3",
"&. c #D7D9DA",
"*. c #DCDCDC",
"=. c #C3D8E5",
"-. c #CFDBE2",
";. c #C7DCE9",
":. c #CCDEE9",
">. c #D5DEE4",
",. c #D3E3EC",
"<. c #DAE3E9",
"1. c #DCE8EF",
"2. c #D6E6F0",
"3. c #DBEAF3",
"4. c #E4E4E4",
"5. c #E4E7E9",
"6. c #E0E9EE",
"7. c #ECECEC",
"8. c #EBEFF1",
"9. c #E6F0F6",
"0. c #EEF3F5",
"q. c #EFF6FA",
"w. c #F4F4F4",
"e. c #F3F7F9",
"r. c #F5F8FA",
"t. c #FBFBFB",
"y. c None",
/* pixels */
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.&.5.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.*.5.7.w.7.7.7.*.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.[ { :.7.7.7.7.7.7.7.7.7.7.4.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.%.&.( D b d c 5.7.7.7.7.7.w.7.w.7.7.w.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.#.*.4.7.5.4.] s s s s =.7.7.7.7.7.7.w.7.w.w.w.w.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.&.4.7.4.*.*.4.4.4.>.h s s a S 7.7.7.w.7.w.w.w.w.w.w.w.w.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.4.4.4.*.*.*.*.*.4.4.4.4.4.E d s s a ;.7.7.7.w.w.7.w.w.w.w.w.w.t.&.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.4.*.*.*.*.*.4.4.4.4.4.4.>.d s a a C 8.w.w.w.w.w.w.t.w.w.w.t.w.t.7.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.*.*.*.4.*.*.*.4.4.4.4.7.^ a a a a O.7.w.w.w.w.w.w.w.t.t.t.t.t.t.w.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.%.*.*.*.*.4.4.4.4.5.4.5.l a a a h 7.w.w.w.w.w.w.w.t.t.t.t.t.t.t.t.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.4.*.4.*.4.4.4.4.7.7.O.a a a i D w.w.w.w.t.t.t.t.t.t.t.t.t.t.t.t.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.4.*.*.4.4.5.5.7.5.7.~ a i i i O.w.t.w.t.t.t.t.t.t.t.t.t.t.t.t.t.*.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.4.*.4.4.4.4.7.5.7.7.l a i i a 0.t.w.t.t.t.t.t.t.t.t.t.t.t.t.t.t.7.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.*.4.4.4.4.4.4.7.7.<.i i i t v w.t.w.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.%.4.4.4.4.7.7.7.7.X.i i y y ^ w.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.4.4.4.5.7.7.7.8.' i t i t o.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.7.7.5.5.7.7.7.w.A t i t t 2.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.*.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.7.4.7.7.7.7.w.w.C i y t t q.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.7.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.4.4.7.7.7.7.w.w.V t t t p r.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.t.X.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.&.7.7.7.7.7.w.w.C t t r p e.t.t.t.t.t.t.t.t.t.t.t.r.r.t.t.r.t.:.k y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.7.7.7.7.w.w.w.~ t t t u e.t.t.t.t.t.t.t.t.t.t.t.t.w.t.w.r.w.j 1 y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.7.7.w.w.w.w.w...t t r r 9.t.t.t.t.t.t.t.t.t.t.t.t.t.t.w.t.R : ; _ y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.7.7.w.7.w.w.w.<.t r r r +.t.t.t.t.t.t.t.w.t.t.w.e.t.w.t.:.> ; ; T y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.5.7.w.7.w.t.t.t.v r r < ~ t.t.t.t.t.t.t.t.w.t.w.w.t.w.6.2 - ; ; } y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.&.7.w.w.w.w.w.t.+.r < < u e.t.t.t.t.w.t.w.t.w.t.t.7.&.e 5 6 7 K #.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.w.w.w.t.w.t.t.t.Z < < < A t.t.t.t.t.t.r.r.w.%.#.` 9 3 3 0 O.w.7.U G y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.w.7.w.w.t.t.t.t.r.M < < < E e.t.t.t.w.w.#.#.<.| N z z / 8.w.w.w.@.G Y U y.y.y.",
"y.y.y.y.y.y.y.y.y.w.w.t.t.w.t.t.t.t.t.^ < 1 , g ( ;.1.<.I  .{ B N m W ,.w.4.*.*.#.Y H H y.y.y.y.",
"y.y.y.y.y.y.y.y.y.5.w.w.w.t.t.t.t.t.t.t.1.E p > : : 8 q j B B Q X.#.P H #.#.*.*.4.4.y.H y.y.y.y.",
"y.y.y.y.y.y.y.y.y.*.w.w.t.t.t.t.t.t.t.t.t.t.t.<. .R I X.2.6.%.P F & & G *.7.5.4.4.&.y.= y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.w.7.%.%.%.&.4.4.w.t.t.&.#.%.@.P @.*.Y G * * * J Y #.#.&.*.4.&.%.G y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.L %.4.w.w.t.t.t.r.4.@.L %.w.t.%.G * = F = = & & & % % % & * * G L = y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.w.t.t.t.t.t.t.t.w.%.U L F # o o % + = G H L L L J G = @ X . O # + $ * y.y.y.",
"y.y.y.y.y.y.y.y.y.y.w.t.t.t.w.%.U H $ O & X X # F P @.U %.%.*.*.*.*.%.#.@.#.U G H % o . X o # y.",
"y.y.y.y.J y.y.y.y.y.%.Y J = % # @ + O . * H 4.w.w.7.4.@.Y #.#.#.@.@.#.Y P P U #.&.*.@.y.y.    y.",
"y.y.y.J y.y.y.y.%.#.F % & = % # @ @ & U @.5.4.4.4.4.7.7.%.@.U U U P P U #.%.*.7.7.w.4.y.y.y.y.y.",
"y.y.y.H y.*.*.*.&.#.P *.Y & # # H %.*.*.@.4.7.w.w.t.t.w.7.4.*.&.*.&.*.4.7.7.7.w.7.w.7.y.y.y.y.y.",
"y.P &.L #.&.y.y.y.y.y.G $ # G &.*.*.*.@.%.7.w.t.t.w.w.w.w.w.w.w.w.w.7.w.7.7.w.7.w.w.w.y.y.y.y.y.",
"y.y.y.L y.y.y.y.y.J & $ & @.*.&.%.%.Y %.*.w.t.w.w.t.t.w.w.w.w.w.w.7.w.7.w.w.7.w.w.7.w.y.y.y.y.y.",
"y.y.y.y.G y.y.y.= $ @ * #.#.%.%.Y Y &.4.w.t.t.t.t.t.w.w.w.w.w.w.w.w.7.w.w.w.7.w.%.P y.y.y.y.y.y.",
"y.y.y.y.y.F y.X X .   F %.@.U U #.4.w.t.t.t.t.r.w.w.t.t.w.w.w.w.w.w.w.w.7.%.L y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.$ @ @ # y.& U @.*.4.w.t.t.t.t.t.t.r.t.w.w.w.t.w.w.t.w.7.&.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.o X . y.y.y.y.4.7.w.t.t.t.t.t.t.t.t.t.w.t.t.w.7.4.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.X X X y.y.y.y.y.7.t.t.t.t.t.t.t.t.t.t.7.4.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.X X . y.y.y.y.y.y.*.t.t.t.t.t.w.4.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.. y.y.y.y.y.y.y.y.w.4.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.",
"y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y."
};
