/* XPM */
static char * skype_xpm[] = {
"48 48 177 2",
"  	c None",
". 	c #1498C9",
"+ 	c #1598C8",
"@ 	c #0C9ACF",
"# 	c #2895BD",
"$ 	c #069FD8",
"% 	c #3295BA",
"& 	c #3395B9",
"* 	c #3896BA",
"= 	c #3E95B6",
"- 	c #3D98BA",
"; 	c #13A2D7",
"> 	c #02A6E3",
", 	c #299ECA",
"' 	c #0BA5DE",
") 	c #3D9CBE",
"! 	c #4C99B7",
"~ 	c #449CBC",
"{ 	c #5798B0",
"] 	c #07ACE9",
"^ 	c #00AFF0",
"/ 	c #13ABE4",
"( 	c #2FA5D2",
"_ 	c #02B0F0",
": 	c #03B0F0",
"< 	c #25A9DA",
"[ 	c #0BAFED",
"} 	c #05B1F0",
"| 	c #4AA2C3",
"1 	c #0EB0ED",
"2 	c #09B2F1",
"3 	c #0AB2F1",
"4 	c #6C9CAE",
"5 	c #2FABD8",
"6 	c #6E9DAE",
"7 	c #3CAAD3",
"8 	c #759DAC",
"9 	c #12B5F1",
"0 	c #13B5F1",
"a 	c #14B5F1",
"b 	c #15B6F1",
"c 	c #16B6F1",
"d 	c #17B6F1",
"e 	c #44ACD2",
"f 	c #2EB1E2",
"g 	c #57A8C6",
"h 	c #19B7F1",
"i 	c #61A7C0",
"j 	c #1BB7F2",
"k 	c #5DA8C5",
"l 	c #6BA6BC",
"m 	c #7DA2B0",
"n 	c #79A3B2",
"o 	c #1DB8F2",
"p 	c #4AAED2",
"q 	c #1EB8F2",
"r 	c #61A9C5",
"s 	c #1FB9F2",
"t 	c #31B6E6",
"u 	c #62ABC7",
"v 	c #22BAF2",
"w 	c #83A4B0",
"x 	c #23BAF2",
"y 	c #24BAF2",
"z 	c #6BAAC1",
"A 	c #85A4B0",
"B 	c #45B3DB",
"C 	c #70ABC2",
"D 	c #29BCF2",
"E 	c #59B1D2",
"F 	c #97A3A7",
"G 	c #2ABCF2",
"H 	c #2BBCF3",
"I 	c #57B2D5",
"J 	c #32BBEE",
"K 	c #2CBDF3",
"L 	c #9AA4A8",
"M 	c #2DBDF3",
"N 	c #37BBEC",
"O 	c #98A5AA",
"P 	c #6DAFC7",
"Q 	c #2FBEF3",
"R 	c #31BEF3",
"S 	c #33BFF3",
"T 	c #34BFF3",
"U 	c #6BB3CE",
"V 	c #A6A6A6",
"W 	c #9EA9AD",
"X 	c #9FAAAE",
"Y 	c #6FB6D0",
"Z 	c #3BC2F3",
"` 	c #3CC2F4",
" .	c #3DC2F4",
"..	c #3EC2F4",
"+.	c #6BB8D5",
"@.	c #47C1EE",
"#.	c #3FC3F4",
"$.	c #41C3F4",
"%.	c #42C4F4",
"&.	c #73B9D3",
"*.	c #43C4F4",
"=.	c #44C4F4",
"-.	c #4AC3F0",
";.	c #45C5F4",
">.	c #46C5F4",
",.	c #4BC7F4",
"'.	c #4CC7F4",
").	c #B1B1B1",
"!.	c #4FC8F5",
"~.	c #A9B4B8",
"{.	c #53C9F5",
"].	c #54C9F5",
"^.	c #57CAF5",
"/.	c #58CBF5",
"(.	c #B7B7B7",
"_.	c #5CCCF5",
":.	c #5DCCF5",
"<.	c #5ECCF6",
"[.	c #8BC2D6",
"}.	c #5FCDF6",
"|.	c #63CEF6",
"1.	c #AEBDC3",
"2.	c #64CEF6",
"3.	c #BCBCBC",
"4.	c #6CD1F6",
"5.	c #6DD1F6",
"6.	c #6FD2F7",
"7.	c #72D3F7",
"8.	c #74D3F7",
"9.	c #C2C2C2",
"0.	c #76D4F7",
"a.	c #85D2EE",
"b.	c #78D5F7",
"c.	c #7CD6F7",
"d.	c #7DD6F7",
"e.	c #7FD7F7",
"f.	c #BEC9CD",
"g.	c #81D7F7",
"h.	c #C8C8C8",
"i.	c #82D8F8",
"j.	c #83D8F8",
"k.	c #85D9F8",
"l.	c #93D6EF",
"m.	c #89DAF8",
"n.	c #8DDBF8",
"o.	c #CDCDCD",
"p.	c #C6CFD2",
"q.	c #8FDCF8",
"r.	c #90DCF8",
"s.	c #95DEF9",
"t.	c #9ADFF9",
"u.	c #D3D3D3",
"v.	c #9DE0F9",
"w.	c #9FE1F9",
"x.	c #A5E3FA",
"y.	c #AFE6FA",
"z.	c #B0E6FA",
"A.	c #DDDDDD",
"B.	c #BFEBFB",
"C.	c #E3E3E3",
"D.	c #CCEFFC",
"E.	c #E9E9E9",
"F.	c #CFF0FC",
"G.	c #D0F0FC",
"H.	c #D4F1FD",
"I.	c #EEEEEE",
"J.	c #D9F3FD",
"K.	c #DAF4FD",
"L.	c #DFF5FD",
"M.	c #F4F4F4",
"N.	c #E7F8FE",
"O.	c #E9F8FE",
"P.	c #EFFAFE",
"Q.	c #F0FAFE",
"R.	c #F9F9F9",
"S.	c #F4FBFE",
"T.	c #FFFFFF",
"                                                                                                ",
"                                                                                                ",
"                      ^ ^ ^ ^ ^ ^ ^                                                             ",
"                ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^                                         ",
"              ^ ^ ^ ..7.r.x.x.r.7...^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^                                   ",
"            ^ ^ R m.v.v.v.v.v.v.v.v.m.!.|.0.v.v.v.v.0.4.;.q ^ ^ ^ ^                             ",
"          ^ ^ ].s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.i.$.2 ^ ^                           ",
"        ^ ^ /.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n.j. .^ ^ ^                       ",
"      ^ ^ G k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.k.4.h ^ ^                     ",
"      ^ ^ 5.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.c.c.c.c.c.c.c.c.c.c.c.8.Q ^ ^                   ",
"      ^ H 8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.8.+.U P C U +.8.8.8.8.8.8.8.8.8.8.K ^ ^                 ",
"    ^ ^ ,.5.5.5.5.5.5.5.5.5.5.4.4.4.z A V (.3.9.h.3.(.V A z 4.4.4.4.4.4.4.4.D ^ ^               ",
"    ^ ^ ^.2.2.2.2.2.2.2.2.2.2.2.u O h.C.T.T.T.T.T.T.T.T.C.h.O l 2.2.2.2.2.2.<.0 ^               ",
"    ^ ^ :.:.:._._._._._._._._.i 9.M.T.T.T.T.T.T.T.T.T.T.T.T.M.o.n _._._._._._.,.^ ^             ",
"    ^ ^ ].].].].].].].].].].g h.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.A.m {.{.{.{.{.{.y ^ ^           ",
"    ^ ^ %.'.'.'.'.'.'.'.'.'.1.T.T.T.T.T.O.t.b.'.^.b.z.S.T.T.T.T.T.C.p '.'.'.'.,.>.} ^           ",
"    ^ ^ Q =.=.=.=.=.=.=.=.e M.T.T.T.T.N.@.*.*.*.*.*.*.-.G.T.T.T.T.T.r *.*.*.*.*.*.o ^           ",
"      ^ c ` ` ` ` ` ` ` ` k T.T.T.T.T.l.` ` ` ` ` ` ` ` ` K.T.T.T.T.B Z Z Z Z Z Z T ^ ^         ",
"      ^ ^ M T T T S S S S Y T.T.T.T.T.&.S S S S S S S S S N x.J.D.7.S S S S S S S S 3 ^         ",
"      ^ ^ b H H H H H H H I T.T.T.T.T.p.( H H H H H H H H H H H H H H H H H H H H H 0 ^         ",
"        ^ c x x x x x x x 5 T.T.T.T.T.R.(.6 ) < x x x x x x x x x x x x x x x x x v d ^         ",
"      ^ ^ c j j j j j j j j H.T.T.T.T.T.T.C.h.).L 4 ! , j j j j j j j j j j j j j j a ^ ^       ",
"      ^ ^ 0 0 0 0 0 0 0 0 0 t Q.T.T.T.T.T.T.T.T.R.C.u.3.V 8 - / 0 9 9 9 9 9 9 9 9 9 9 ^ ^       ",
"      ^ ^ 3 3 3 3 3 3 3 3 3 3 J Q.T.T.T.T.T.T.T.T.T.T.T.T.E.o.X * 3 3 3 3 3 3 3 3 3 3 ^ ^       ",
"      ^ ^ : : : : : : : : : : : 1 g.P.T.T.T.T.T.T.T.T.T.T.T.T.R.o.{ _ _ _ _ _ _ _ _ _ ^ ^       ",
"      ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ #.q.B.T.T.T.T.T.T.T.T.T.T.T.A.% ^ ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"      ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ #.e.B.T.T.T.T.T.T.T.T.f.^ ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"        ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ }.F.T.T.T.T.T.R.. ^ ^ ^ ^ ^ ^ ^ ^         ",
"        ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ > & & > ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ] L.T.T.T.T.T.| ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"        ^ ^ ^ ^ ^ ^ ^ ^ ^ $ W o.o.W @ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ a.T.T.T.T.T.E ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"        ^ ^ ^ ^ ^ ^ ^ ^ ^ ~ R.T.T.R.~.> ^ ^ ^ ^ ^ ^ ^ ^ ^ [.T.T.T.T.T.7 ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"          ^ ^ ^ ^ ^ ^ ^ ^ E T.T.T.T.R.w > ^ ^ ^ ^ ^ ^ ^ + C.T.T.T.T.T.; ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"          ^ ^ ^ ^ ^ ^ ^ ^ ' T.T.T.T.T.I.W # $ ^ ^ ^ $ = 3.T.T.T.T.T.B.^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"          ^ ^ ^ ^ ^ ^ ^ ^ ^ q.T.T.T.T.T.R.h.).V F V ).u.T.T.T.T.T.T.f ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"            ^ ^ ^ ^ ^ ^ ^ ^ ^ w.T.T.T.T.T.T.T.T.R.T.T.T.T.T.T.T.T.}.^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"              ^ ^ ^ ^ ^ ^ ^ ^ ^ }.P.T.T.T.T.T.T.T.T.T.T.T.T.T.L.#.^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"              ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ [ }.y.P.T.T.T.T.T.T.T.T.y.}.^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^     ",
"                ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ s #.#.6.#.#.Q ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"                  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"                    ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^       ",
"                      ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^         ",
"                          ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^           ",
"                            ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^             ",
"                                  ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^               ",
"                                          ^ ^ ^ ^ ^ ^   ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^                 ",
"                                                              ^ ^ ^ ^ ^ ^                       ",
"                                                                                                ",
"                                                                                                "};
