/* XPM */
static char * vlc_xpm[] = {
"48 48 256 2",
"  	c None",
". 	c #572D08",
"+ 	c #633209",
"@ 	c #66350C",
"# 	c #6C3909",
"$ 	c #713D0D",
"% 	c #7D420D",
"& 	c #7E420E",
"* 	c #814407",
"= 	c #8A470E",
"- 	c #8C4810",
"; 	c #8E4911",
"> 	c #9B4E11",
", 	c #9D5009",
"' 	c #A0520C",
") 	c #A3540F",
"! 	c #A45611",
"~ 	c #AC560B",
"{ 	c #A95A0B",
"] 	c #B15A10",
"^ 	c #B25C12",
"/ 	c #AE5E11",
"( 	c #B65E09",
"_ 	c #B55E15",
": 	c #B75F0B",
"< 	c #BD6312",
"[ 	c #BF6615",
"} 	c #CA6911",
"| 	c #CC6A13",
"1 	c #D16E19",
"2 	c #D26F1A",
"3 	c #D3700F",
"4 	c #D67213",
"5 	c #D87415",
"6 	c #D47613",
"7 	c #DA7517",
"8 	c #DB7618",
"9 	c #D67816",
"0 	c #D87908",
"a 	c #D77917",
"b 	c #D87A23",
"c 	c #E07A11",
"d 	c #DA7B1A",
"e 	c #DD7D10",
"f 	c #DD7D1D",
"g 	c #DF7F13",
"h 	c #E57D16",
"i 	c #DF7F1F",
"j 	c #E08021",
"k 	c #E77F19",
"l 	c #E28117",
"m 	c #E8801A",
"n 	c #E28223",
"o 	c #EB821D",
"p 	c #E5841B",
"q 	c #DF852C",
"r 	c #E7851D",
"s 	c #DB882B",
"t 	c #E28725",
"u 	c #EF8515",
"v 	c #E88628",
"w 	c #E9871F",
"x 	c #F08616",
"y 	c #E3882F",
"z 	c #EF8622",
"A 	c #EA8820",
"B 	c #F18718",
"C 	c #DF8B2F",
"D 	c #EB8921",
"E 	c #F28819",
"F 	c #EB892B",
"G 	c #F8871C",
"H 	c #EE8B18",
"I 	c #F4891B",
"J 	c #E88C2B",
"K 	c #EE8B24",
"L 	c #F58A1C",
"M 	c #E78C33",
"N 	c #ED8B2D",
"O 	c #F48A27",
"P 	c #E98D2C",
"Q 	c #EF8C25",
"R 	c #F68B1D",
"S 	c #E98D34",
"T 	c #EA8E2D",
"U 	c #F78C1F",
"V 	c #E59034",
"W 	c #F18E27",
"X 	c #EA8F36",
"Y 	c #F38F1E",
"Z 	c #E5913D",
"` 	c #F38F28",
" .	c #ED9030",
"..	c #EE9131",
"+.	c #F4902A",
"@.	c #F59120",
"#.	c #F5912B",
"$.	c #F1932A",
"%.	c #EF9332",
"&.	c #F7922C",
"*.	c #EF933A",
"=.	c #F19433",
"-.	c #F8932D",
";.	c #EC963A",
">.	c #F29534",
",.	c #F9942E",
"'.	c #F4962C",
").	c #ED973B",
"!.	c #F39635",
"~.	c #F5972E",
"{.	c #EE983C",
"].	c #F49736",
"^.	c #EE9844",
"/.	c #F4973E",
"(.	c #E99A43",
"_.	c #F0993D",
":.	c #F69837",
"<.	c #F79938",
"[.	c #F29B3F",
"}.	c #F89A39",
"|.	c #DD9F5D",
"1.	c #F29C47",
"2.	c #F49D42",
"3.	c #F69E3B",
"4.	c #EF9F48",
"5.	c #EFA04F",
"6.	c #F79F44",
"7.	c #F0A150",
"8.	c #F8A045",
"9.	c #EAA35D",
"0.	c #F3A34B",
"a.	c #E5A563",
"b.	c #FAA246",
"c.	c #F3A353",
"d.	c #F4A44C",
"e.	c #FAA34E",
"f.	c #E0A86A",
"g.	c #F6A54D",
"h.	c #F5A554",
"i.	c #F7A64E",
"j.	c #F8A74F",
"k.	c #F7A756",
"l.	c #F2A955",
"m.	c #F2A95D",
"n.	c #F4AA57",
"o.	c #EDAB63",
"p.	c #F3AA5E",
"q.	c #F9A958",
"r.	c #F4AB5F",
"s.	c #F3AB65",
"t.	c #F6AC60",
"u.	c #F5AD66",
"v.	c #F7AD61",
"w.	c #EFAF6C",
"x.	c #F8AF62",
"y.	c #F7AF68",
"z.	c #F9B063",
"A.	c #F8B069",
"B.	c #F4B269",
"C.	c #E3B586",
"D.	c #FAB16B",
"E.	c #F4B370",
"F.	c #F5B471",
"G.	c #F7B56C",
"H.	c #E5B888",
"I.	c #F8B66D",
"J.	c #F6B679",
"K.	c #F8B774",
"L.	c #E8BA8A",
"M.	c #FAB875",
"N.	c #FCBA77",
"O.	c #F6BC7D",
"P.	c #F4BC83",
"Q.	c #FBBB7E",
"R.	c #EFBF89",
"S.	c #F8BE7E",
"T.	c #F9BF7F",
"U.	c #F7BF86",
"V.	c #FAC188",
"W.	c #FAC28F",
"X.	c #FBC389",
"Y.	c #FDC48B",
"Z.	c #FCC491",
"`.	c #F7C690",
" +	c #FEC58C",
".+	c #FDC692",
"++	c #F8C892",
"@+	c #F5C89E",
"#+	c #EDCAAA",
"$+	c #FBCB9B",
"%+	c #FDCD9D",
"&+	c #EBD4BD",
"*+	c #EAD5C4",
"=+	c #FBD4A7",
"-+	c #F9D4AD",
";+	c #E4D8CB",
">+	c #F8D5B5",
",+	c #FCD8B8",
"'+	c #E7DCCF",
")+	c #EBDDCA",
"!+	c #F5DCBF",
"~+	c #FEDABA",
"{+	c #E7DED7",
"]+	c #EBE0D3",
"^+	c #FADEBB",
"/+	c #FCE1C5",
"(+	c #EAE4E3",
"_+	c #EDE5DE",
":+	c #FDE3C6",
"<+	c #FCE4CD",
"[+	c #E4E9EC",
"}+	c #EDE7E6",
"|+	c #E5EAED",
"1+	c #E8EAE7",
"2+	c #FEE6CF",
"3+	c #E9EBE8",
"4+	c #FFE7D0",
"5+	c #E6ECEE",
"6+	c #EAECE9",
"7+	c #E7EDEF",
"8+	c #FFE9D8",
"9+	c #F9EBD8",
"0+	c #EBEEEA",
"a+	c #FAECD9",
"b+	c #FBEDDA",
"c+	c #F6EEE7",
"d+	c #ECF1F4",
"e+	c #FDEFDB",
"f+	c #F6F0EF",
"g+	c #F0F2EF",
"h+	c #FBF0E3",
"i+	c #F1F3F0",
"j+	c #FCF1E4",
"k+	c #FAF1EA",
"l+	c #F2F4F1",
"m+	c #FEF2E5",
"n+	c #FFF3E6",
"o+	c #F4F7F3",
"p+	c #F2F7F9",
"q+	c #FEF6EE",
"r+	c #FCF6F5",
"s+	c #F7F9F6",
"t+	c #FFF8F0",
"u+	c #F5FAFD",
"v+	c #F8FAF7",
"w+	c #F6FBFE",
"x+	c #F9FBF8",
"y+	c #FFFAF9",
"z+	c #FAFCF9",
"A+	c #F7FDFF",
"B+	c #FBFDFA",
"C+	c #FFFCFA",
"D+	c #FFFDFB",
"E+	c #F9FFFF",
"F+	c #FCFFFB",
"G+	c #FEFFFC",
"                                                                                                ",
"                                                                                                ",
"                                              w o                                               ",
"                                            J K r m                                             ",
"                                            *. .w k                                             ",
"                                          ;._...T p                                             ",
"                                          7.[.>. .p g                                           ",
"                                          c.[.$. .v f                                           ",
"                                        7.c.:.#.+.T e                                           ",
"                                        F.n.:.#.!.^.a.)+                                        ",
"                                      y+G+9+^+~+<+k+p+0+                                        ",
"                                      G+G+G+G+G+G+u+i+0+                                        ",
"                                      !+q+t+y+C+z+r+c+*+f.                                      ",
"                                      c.p.z.K.O.N.E.5.l 0                                       ",
"                                    ).s.0.$.U L U +. .M d                                       ",
"                                    5.t.6.#.U U U +...M f                                       ",
"                                    m.k.2.#.U L U Y +.T j |.                                    ",
"                                  t+e+V.!.U B G B L B o.&+(+                                    ",
"                                  G+G+G+B+:+%+Y.$+^+x+w+d+1+6+                                  ",
"                                  G+G+G+G+G+G+G+G+G+B+s+g+1+3+                                  ",
"                                y+G+G+G+G+G+G+G+G+G+B+v+i+6+7+                                  ",
"                                /+t+C+G+G+G+G+G+G+G+G+x+f+_+C.                                  ",
"                                7.O.%+,+4+n+t+t+m+8+~+`.w.Z d 6                                 ",
"                                s.D.g.}.,.,.,.~.#.#.#.+...V q 9                                 ",
"                              ;.B.y.g.,.U L U U L U U +...X C 9                                 ",
"                              1.B.v.8.#.U L U U L U U +.$.X y s                                 ",
"                              4+U.k.}.#.U L U U L L U U W  .H.{+;+                              ",
"                            m+G+G+b+Z.8.~.#.#.@.#.#.:.v.-+o+d+|+1+                              ",
"                          @+y+G+G+G+G+G+q+a+<+:+2+h+G+G+A+s+g+1+5+#+                            ",
"                      `.$+,+B+G+G+G+G+G+G+G+G+G+G+G+G+G+A+v+g+3+[+]+`.$+U.                      ",
"                  O.Y.Z.V.P.a+y+G+G+G+G+G+G+G+G+G+C+G+G+G+u+l+}+'+H.P. +Z.V.                    ",
"              K.Q.O.O.O.J.7.r.W.=+/+m+G+G+G+G+G+G+G+G+y+9+>+R.9.q f o.O.O.O.O.N.K.              ",
"          D.G.G.G.G.G.G.r.4.y.D.q.2.:.:.i.z.M.M.G.q.3.~.,.#. .J t j (.G.G.G.G.G.G.G.y.          ",
"      n.v.v.v.v.v.v.v.v.1.7.v.v.e.~.Y U L B B G B B L U U Y W N v n M t.v.v.v.v.v.v.v.v.c.      ",
"    i.j.i.i.j.j.j.j.j.0...4.n.k.2.#.U U L U U U U U U L U U O K w p r 4.j.j.j.j.j.j.i.j.j.g.    ",
"    /.8.6.6.6.6.6.6.8.{...).1.2.!.+.L L U U L U U L U U L L B B u o w ;.8.6.6.6.6.6.6.6.8.X     ",
"    [ j >.<.}.<.<.<.}.>.........+.L B B B L L L L L L B B B B B u w K ..}.<.<.<.}.}.<...b :     ",
"      = < j K #.#.#.#.#.+.K K K H B B B B B B L L B B B B B B u z K K +.#.#.#.#.#.F 7 ] &       ",
"          $ < 7 B U U L L B B B u u B B B B B B B B B B B B u u B B B L U U U o 4 / .           ",
"              & < 7 u L U U B B B B B u B u B u u B B u u u B B L L L U B o 1 _ +               ",
"                  & ^ 7 o L U L L B B B B B B B B B B B B B B L L U B k 3 ) #                   ",
"                      . ^ 4 o U U L L L B B B B B B B B L L L U U h 1 '                         ",
"                          @ : 1 o B U U L L L L L L L U U U B k | {                             ",
"                              # ! 3 m B U U U U U U U U B h | >                                 ",
"                                    ) 2 k U U U U U B c } -                                     ",
"                                        ~ | 7 c c 4 } ,                                         ",
"                                            * ; ; &                                             ",
"                                                                                                "};
