/* XPM */
static char *xine_l[] = {
/* columns rows colors chars-per-pixel */
"48 48 137 2 ",
"   c #010101",
".  c #0B0B0B",
"X  c #141414",
"o  c #1C1C1C",
"O  c #232323",
"+  c #2C2C2C",
"@  c #333333",
"#  c #3C3C3C",
"$  c #464929",
"%  c #4C4D2A",
"&  c #54532C",
"*  c #5B562D",
"=  c #5F5A2E",
"-  c #625C2F",
";  c #69612F",
":  c #6C6231",
">  c #716630",
",  c #756933",
"<  c #7B6C33",
"1  c #434343",
"2  c #4A4A4A",
"3  c #5D5D5D",
"4  c gray50",
"5  c #806F34",
"6  c #837235",
"7  c #8A7635",
"8  c #8D7836",
"9  c #897638",
"0  c #927B37",
"q  c #957E39",
"w  c #9B823A",
"e  c #A0873C",
"r  c #A28A3E",
"t  c #A48B40",
"y  c #A79041",
"u  c #AB9444",
"i  c #AF9946",
"p  c #B09646",
"a  c #B49D49",
"s  c #B99F4B",
"d  c #B6A04A",
"f  c #BBA34D",
"g  c #BDA751",
"h  c #BFAB53",
"j  c #C0A74F",
"k  c #C4AB53",
"l  c #C8AF54",
"z  c #C7B057",
"x  c #C9B256",
"c  c #C6B259",
"v  c #CBB55A",
"b  c #CEB95C",
"n  c #D1BB5F",
"m  c #D2BE61",
"M  c #D5C364",
"N  c #D8C665",
"B  c #D9C866",
"V  c #D6C368",
"C  c #D9C669",
"Z  c #DCCC6B",
"A  c #DFD06D",
"S  c #E0D36F",
"D  c #E2D472",
"F  c #E6D975",
"G  c #E8DD77",
"H  c #EBDE7A",
"J  c #EEE37E",
"K  c #F0E57F",
"L  c #808080",
"P  c #8A9C8A",
"I  c #929292",
"U  c #9B9B9B",
"Y  c #A98181",
"T  c #A28D8D",
"R  c #AB9B9B",
"E  c #9DA99D",
"W  c #94B094",
"Q  c #A4A4A4",
"!  c #ABABAB",
"~  c #B0A1A1",
"^  c #AEB0AE",
"/  c #B4B3B3",
"(  c #BBBBBB",
")  c #C39A9A",
"_  c #C1A499",
"`  c #D2A5A5",
"'  c #D3AFAF",
"]  c #DCB8AD",
"[  c #D7BEBE",
"{  c #DCBFBF",
"}  c #E5AFAD",
"|  c #E4BEBE",
" . c #EBBEBE",
".. c #F3BDBD",
"X. c #FCBCBB",
"o. c #9AC79A",
"O. c #A4C199",
"+. c #ADC7AD",
"@. c #AED7AE",
"#. c #AEDFAE",
"$. c #BFD6BF",
"%. c #BFDCBF",
"&. c #B3E1AD",
"*. c #BEE3BE",
"=. c #BFE9BF",
"-. c #BDF2BD",
";. c #BCFDBB",
":. c #F1E680",
">. c #F4EB82",
",. c #CEC6AD",
"<. c #C1D3AD",
"1. c #DEDFBC",
"2. c #EDCEBC",
"3. c #F5C4BB",
"4. c #F8C4BB",
"5. c #F1C9BC",
"6. c #E5D5BC",
"7. c #E9D0BC",
"8. c #E2DABD",
"9. c #D7E6BD",
"0. c #DBE1BD",
"q. c #D4E8BD",
"w. c #CBF1BC",
"e. c #C2FBBB",
"r. c #C4C5C4",
"t. c #CBC0C0",
"y. c #C0CCC0",
"u. c #CBCBCB",
"i. c #D3C0C0",
"p. c #C0D2C0",
"a. c #D3D3D3",
"s. c #DCDCDC",
"d. c #E3E3E3",
"f. c #ECECEC",
"g. c #F4F4F4",
"h. c #FEFEFE",
"j. c None",
/* pixels */
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.@ @ @ @ @ @ @ @ j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.2 2 2 U ( ( / / / ~ T @ @ + j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.2 Q r.r.a.u.u.r.r.t.i.{ ' ` Y @ j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.3 2 a.u.s.s.a.a.u.u.r.t.[ |  ...} ] @ 2 j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.3 L d.f.d.s.s.a.a.u.u.r.t.[ |  .X.4.2.,.L 2 j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.3 L d.g.g.f.d.s.s.a.a.u.r.t.{ | ..X.5.6.1.<.4 2 j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.2 s.g.h.g.g.f.d.s.a.a.u.r.t.{  .X.4.7.1.q.w.&.  j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.2 a.g.g.g.h.g.f.d.s.a.a.u.r.t.| ..X.5.1.9.w.e.;.#.  j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.2 U u.f.f.g.g.h.g.f.d.s.a.u.r.i.| X.5.6.9.w.e.;.-.@.W   j.1 # j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.2 ( s.s.d.f.f.g.h.g.f.s.! Q U R  .X.7.9.w.e.;.-.*.*.+.2 # # h.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.2 u.s.s.d.d.d.f.g.h.r.( #   . 1 ) _ 1.w.;.-.=.*.%.1 1 # h.@ + j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ I s.a.s.s.s.d.d.d.r.U o @   .     4 O.;.-.*.%.1 1 # h.@ + O A j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ r.a.a.s.a.s.s.s.d.( o / 4 h.h.4     o.=.%.1 1 1 h.@ @ + r a z j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ ( a.a.a.a.a.a.s.! # @ 4 s.j.j.s.L   # 1 1 1 h.@ @ + : O o w r j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ ( a.a.a.a.a.u.a.!     h.j.j.j.j.h.1 1 1 h.# @ + 9 - $ - X < 8 j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ ( u.u.u.u.u.u.u.Q . . h.j.j.j.1 2 1 h.# @ @ n v s t 6 * . . > j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ ( u.u.u.r.u.u.u.U #   L s.1 1 1 h.# # @ m Z Z Z n l a w <   & j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ ^ r.u.r.r.r.r.r.y.E   1 1 1 h.# # @ f d g v M Z Z B n k p # @ j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.@ I r.r.r.r.r.y.p.%.1 1 1 h.# # @ G + + l j d k n M A Z M v k + j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.@ ! y.r.p.$.%.1 1 1 h.2 # # J :.>.K O B b l f a k n C S B M + j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.@ E $.$.%.1 1 1 h.1 # # d c V D :.:.o X D B b k d f l m B Z B j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.@ P +.1 1 1 h.1 1 # < 0 w u f c V F :.. >.J S M v k d g v o X j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.1 1 1 h.1 1 1 & & = : < q w u g b Z   # :.K G S M v o X X h.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.1 1 1 h.1 1 1 x @ @ < % & - > 6 q t i g M # J K >.:.o o X h.. . j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.2 h.1 1 1 Z B B n + p q > $ & - < 6 q r a @ + S O o X h.. .   j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.1 1 1 d h b V A B O o k u 0 : $ * ; < 8 w r O o o h.. . . j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.1 B b l f a z n C A X M v f y 9 - % * : + O o h.X . . j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.:.J D B b k f d x n . . B m v s e 5 + O o h.X . . j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.K >.:.J S N v j d f v 1 B Z B b + O O h.X X . j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.Z G K >.:.G A M x j d # # M + + O h.X X . j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.h m S H :.>.K F Z M l f + + O h.o X . j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.",
"j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j.j."
};
