.\" $XConsortium: binstall_sun.1 /main/3 1995/10/30 14:06:18 rswiston $
.TH binstall_hp 1 "" "" SunOS
.ds )H Sun Microsystems
.ds ]W January 1994
.SH NAME
binstall_sun \- build environment installation path availability
.SH DESCRIPTION
This man page describes the usage of the build install mechanism at
Sun Microsystems. The focus is primarily on the default locations for the
install paths.
.SH EXAMPLES
.SH PACKAGE INFORMATION
Currently no information is yet available for this package.
.SH SEE ALSO
binstall(1),
binstall(5).
