.\" $XConsortium: cleanLinks.1 /main/3 1995/10/30 14:06:27 rswiston $
.TH cleanLinks 1 "" "" HP-UX
.ds )H Hewlett-Packard Company OSSD-CV
.ds ]W July 1993
.SH NAME
cleanLinks \- OSSD-CV symbolic link to nowhere cleanup script
.SH SYNOPSIS
.B cleanLinks
.I <directory>
.SH DESCRIPTION
.I cleanLinks
is a perl script that cleans the directory structure(given by
.IR directory )
of files and directories that 
are symbolic links to nowhere. It does not remove any path name that
ends in RCS. It sends information on what files are removed to stdout.
Error information is sent to stderr.
.SH SEE ALSO
master_build(1),
buildAdmin(5).
.SH AUTHOR
.I cleanLinks
was developed by Marc Ayotte OSSD-CV, Hewlett-Packard.
