.\" $XConsortium: cleanLogs.1 /main/3 1995/10/30 14:06:35 rswiston $
.TH cleanLogs 1 "" "" HP-UX
.ds )H Hewlett-Packard Company OSSD-CV
.ds ]W June 1993
.SH NAME
cleanLogs \- OSSD-CV script to remove excessive build logs
.SH SYNOPSIS
.B cleanLogs
.RI [ \|options\| ]
.SH DESCRIPTION
.I cleanLogs
removes directories and files from a system. If no options are given, it
will leave the 14 newest directories in the /x/logs/build directory.
This script is generally run as part of the master cron for all builds.
See the
.I cron_example
file.
If one option is given, it is assumed to be the directory path
that should be cleaned.  If two options are given, the second option is
the number of files or directories that should remain after cleaning.
.SH SEE ALSO
master_build(1),
buildAdmin(5).
.SH AUTHOR
.I cleanLogs
was developed by Marc Ayotte OSSD-CV, Hewlett-Packard.
