.\" $XConsortium: ListTheTree.1 /main/3 1995/10/30 14:04:20 rswiston $
.TH ListTheTree 1 "" "" HP-UX
.ds )H Hewlett-Packard Company OSSD-CV
.ds ]W July 1993
.SH NAME
ListTheTree \- OSSD-CV tree and lock listing script
.SH SYNOPSIS
.B ListTheTree
.I <directory>
DIRECTORY MUST BEGIN with "/"
.SH DESCRIPTION
.I ListTheTree
is a perl script that creates three files in 
.IR directory :
.IR :TreeListing ,
.IR :TreeListing.locks ,
and
.IR :TreeListing.changes .
.I :TreeListing 
contains a complete recursive listing of all of the files in 
.IR directory .
.I :TreeListing.locks
contains a complete recursive listing of all of the files in
.IR directory
that are locked in RCS, and the name of the locker.
.I :TreeListing.changes
contains a complete listing of all of the files that have been 
checked in since the last listing and who checked them in.
.SH SEE ALSO
master_build(1),
buildAdmin(5).
.SH AUTHOR
.I ListTheTree
was originally developed by Jim Andreas, OSSD-CV, Hewlett Packard.
It was modified extensively and converted to a perl script by
Marc Ayotte, OSSD-CV, Hewlett Packard.
