.\" $XConsortium: remote_build.1 /main/3 1995/10/30 14:07:04 rswiston $
.TH remote_build 1 "" "" HP-UX
.ds )H Hewlett-Packard Company OSSD-CV
.ds ]W July 1993
.SH NAME
remote_build \- OSSD-CV remote startup script for the
.I master_build
script.
.SH SYNOPSIS
.B remote_build
.I <remote host>
.RI [ \|options\| ]
.SH DESCRIPTION
.I remote_build
is a shell script that remsh's to 
.I remote host
and executes the
.I master_build 
script with
.IR options .
All normal 
.I remsh
permissions, etc. must be set up for the script to execute
successfully. This script exists so that a builder can use one master
cron file to execute all of his builds.
.SH SEE ALSO
master_build(1),
buildAdmin(5).
.SH AUTHOR
.I remote_build
was developed by Marc Ayotte OSSD-CV, Hewlett-Packard.
