#! /bin/sh

#
# Script to remove comments and blank lines from ".lst" files
# and coalesce multiple blanks/tabs into a single blank
#

cat $@ | egrep -v '^[ 	]*#|^[ 	]*$' | sed 's/[ 	][ 	]*/ /g'|\
sed 's/ $//'
