#! /bin/sh

#
# Script to remove comments and blank lines from ".lst" files
# and coalesce multiple blanks/tabs into a single blank
#

cat "$@" | grep -E -v '^[ 	]*#|^[ 	]*$' | sed 's/[ 	][ 	]*/ /g'|\
sed 's/ $//'
