.TH vcal2xapia 1 11/3/2016
.SH NAME
 \fB vcal2xapia \fR -- converts vCalendar/iCalendar files to XAPIA format
.SH SYNOPSIS
.SY
\fB vcal2xapia\fR \<[vCalendar file] \> [XAPIA file]
.YS
.SH DESCRIPTION
The AWK script \fB vcal2xapia \fR reads on stdin a vCalendar/iCalendar file
containing a single appointment or ToDo item and writes on stdout a XAPIA format
file with the appointment or ToDo item. Such a file can be dragged on the
\fB dtcm(1) \fR calendar icon to create an appointment/ToDo in the CDE
calendar or further edited with \fB dtcm_editor(1) \fR.

.SH LIMITATIONS/BUGS
The script only handles events/ToDo items in UTC time, and can only parse
timezone data in numerical form. Attachments are ignored.

.SH SEE ALSO

.B dtcm(1), dtcm_editor(1), csacsa(5)

.SH AUTHOR
Edmond Orignac
.ME
