$ $XConsortium: dtscreen.msg /main/3 1995/11/08 12:13:11 rswiston $
$ ENGLISH_SOURCE_VERSION= 1.6   
$ ENGLISH_SOURCE_VERSION= 1.4   
$ %Z%%M%        %I%  %W% %G% %U%   
$ @(#)25\t1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37   
$    
$ COMPONENT_NAME: dtscreen   
$    
$ FUNCTIONS: dtscreen.msg   
$    
$    
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993   
$ All Rights Reserved   
$ Licensed Materials - Property of IBM   
$    
$ US Government Users Restricted Rights - Use, duplication or   
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.   
$    
$    
$quote "

$set 2
$ message file created 1993   

1 "1386-101 %s:  opción de línea de mandatos errónea \"%s\"\n\n"

2 "1386-102 \n\
Escriba %s -help para obtener una descripción completa.\n\n"

3 "1386-103 uso:\n\
        %s [-opciones ...]\n\n\
\t donde opciones incluye:\n"

5 "1386-105    %-28s %s\n\
\t donde modalidad es una de entre:\n"

7 "1386-107 Modalidad desconocida: "

10 "1386-110 no se pudo asignar: %s\n"

11 "1386-111 %d pixels asignados\n"

17 "1386-117 %s: no se puede abrir la pantalla %s.\n"

18 "1386-118 %s: GetResource - no se pudo asignar memoria"

19 "1386-119 %s: Argumento -display mal formado, %s\n"

20 "1386-120 El argumento -batchcount debe ser positivo."

21 "1386-121 El argumento -saturation debe estar entre 0,0 y 1,0."

25 "1386-125 %s: sólo se puede dar soporte a %d pantallas.\n"

30 "1386-130 El argumento -delay debe ser positivo."

35 "1386-135 no se pudo asignar: %s, se usa %s en su lugar\n"

40 "%s: No se puede ubicar la ventana en la que dibujar. Al utilizar la opción\n\
     -create ocasionará que %s cree su propia ventana.\n"
