$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 Selección de archivo BDF
4 El archivo seleccionado existe. ¿Desea sobreescribirlo?
6 No se pudo abrir el archivo seleccionado.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 Este font no contiene caracteres definidos por el usuario.
4 No se pudo abrir el font seleccionado. No cuenta con permiso para obtener acceso al archivo de fonts o el formato del archivo no es correcto.
6 Otra aplicación UDC está utilizando el archivo de fonts.
8 No hay ningún font
10 Abrir
12 Cancelar
14 Programa utilitario de intercambio de datos UDC
16 SelectItems
18 - Conjunto de códigos:
20 -   Estilo:
22 -   Ancho:
24 -  Altura:

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 ¿Desea detener el intercambio UDC?
4 No existen UDCs en este font
6 El nombre XLFD no está seleccionado
8 No se puede abrir el archivo de fonts
10 Otra aplicación UDC está utilizando el archivo de fonts.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 Programa utilitario de intercambio de datos UDC
4 Se produjo un error fatal.
6 No se puede abrir el archivo de fonts.
8 No se puede leer el archivo de fonts.
10 No queda memoria.
12 Se produjo un error fatal.
14 El archivo de fonts especificado no existe.
16 Este font no es pcf ni snf.
18 No se puede abrir el archivo fonts.list.
20 El formato del archivo fonts.list no es correcto.
22 Las descripciones del archivo fonts.list no son correctas.
24 El formato del archivo fonts.list no es correcto.
26 No se puede abrir el archivo fonts.dir.
28 No se puede leer el archivo fonts.dir.
30 No se pueden leer las propiedades del font.
32 No se puede obtener la propiedad FONT.
34 No se puede obtener la propiedad FAMILY_NAME.
36 Otra aplicación ya está utilizando el archivo de fonts.
38 No se puede bloquear el archivo de fonts.
40 No se puede desbloquear el archivo de fonts.
42 No se puede obtener información de bloqueo del archivo de fonts.
44 No se puede encontrar el archivo de fonts especificado.
46 No se puede leer la base de datos NLS.
48 No se pueden obtener nombres de juegos de caracteres de la base de datos NLS.
50 El nombre del juego de caracteres no está definido en la base de datos NLS.
52 No se ha abierto el font especificado.
54 Se produjo un error fatal.
56 Nombre XLFD          :
58 Font original (nombre XLFD)  :
60 Area de códigos UDC      :
62 Estilo              :
64 Tamaño (tamaño carta) :
66 Abrir
68 Cancelar
70 OK
72 cancelar
74 Copiar código de origen (hexadecimal)  :
76 Copiar código de destino (hexadecimal) :
78 Copiar
80 Superponer
82 función de exportación
84 función de importación
86 Cancelar

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 No se creó el archivo BDF
4 No se han seleccionado índices
6 OK
8 Cancelar
10 índices de símbolos

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 No se pueden agregar imágenes de símbolos de este archivo BDF al font.
4 No se pudo abrir el font BDF seleccionado. No cuenta con permiso para obtener acceso al archivo de font o el formato del archivo no es correcto.
6 Se sobreescribirán imágenes de símbolos. ¿Desea sobreescribirlas?
8 No se pudo abrir el font seleccionado. No cuenta con permiso para obtener acceso al archivo de font o el formato del archivo no es correcto.
10 No se pueden agregar imágenes de símbolos de este archivo DBD al font.
12 Ha fallado el registro del archivo de fonts.
