$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcfonted.msg
$ **
$ **  Project:     Fujitsu DT UDC Font Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcfonted
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **
$set 2
$ *****************************************************************************
$ ** _DtMessage set for ufont.c
$ *****************************************************************************

$ This is footer message when registration of the character.
2 El procesamiento de registro se efectúa adentro.

$ Message4-8 are error messages when registration of the character.
4 Falló el registro del carácter.
6 Código no válido.
8 No se puede añadir porque no se puede asignar memoria.

$ Message10-16 are error messages when copying of the character.
10 No hay ningún carácter correspondiente al código especificado.
12 Se encontró un error en el código de copia de origen especificado.
14 Se encontró un error en el código de copia de destino especificado.
16 No hay ningún carácter en el área especificada.

$ This is footer message.
18 Espere por favor.

$ This is error message when copying of the character.
20 No se especificó ningún archivo de copia de código de origen.

$ Message22-24 are error message of user defined character
22 No se puede recolectar información acerca del carácter definido por el usuario.\nNo se ha especificado ningún font.
24 No se puede recolectar información acerca del carácter definido por el usuario.\nSe han especificado múltiples fonts.

$ UDC is User Defined Character.
26 El font especificado no cuenta con ninguna área UDC.

28 No queda memoria.
30 La información del área UDC no es válida.
32 No se puede leer el archivo de fonts.\nEl área de diseño está dañada.

$ Dtudcfonted es el nombre de esta aplicación.
34 Dtudcfonted no puede editar fonts de caracteres proporcionales.

36 Existen modificaciones no guardadas.\n¿Desea guardarlas antes de abrir?
38 Existen modificaciones no guardadas.\n¿Desea guardarlas antes de salir?
40 Al efectuarse la operación de copia, \nse modificarán imágenes de símbolos de los siguientes conjuntos.\n¿Desea efectuar la operación de copia?\n\n
42 No cuenta con permiso de escritura para este font. Deberá modificar el modo de acceso del archivo antes de guardar.\n

$ There are user-visible labels in font-open dialog.
100 Seleccionar elementos:
102 -        Conjunto de códigos:
104 -          Estilo:
106 -          Ancho:
108 -         Altura:
110 Abrir
112 Salir

$ There are user-visible labels in menubar.
114 Font
116 Editar
118 Carácter
120 Información

$ There are user-visible labels in File menu.
122 Abrir...
124 Guardar
126 Salir

$ There are user-visible labels in Edit menu.
$ Message135 is copy of cut&copy
128 Borrar
130 Configurar
132 Revertir
134 Cortar
135 Copiar
136 Pegar
138 Girar
140 Giro vertical
142 Giro horizontal
144 Deshacer

$ There are user-visible labels in Character menu.
$ Message148 is copy of character
146 Añadir/Suprimir...
148 Copiar...

$ There are user-visible labels in Information menu.
150 Nombre XLFD...
152 Area de código...

$ There are user-visible labels in add/delete dialog.
154 Añadir
156 Suprimir
158 Cancelar

$ There are user-visible labels in copy dialog.
$ Message166 is label of execute button
160 Código (hexadecimal):
162 Copiar código de origen (hexadecimal):
164 Copiar código de destino (hexadecimal):
166 Copiar
168 Superponer
170 OK

$ There are user-visible labels in unsaved edits.
172 Guardar
174 No guardar
176 Guardar y salir
178 No guardar y salir

$ There are user-visible labels in delete notice dialog.
$ This format is `Message180 (?? Message182)' and `Message184 (?? Message186)'.
$ These Message180 and Message182 are used in only one character.
$ These Message184 and Message186 are used in plural characters.
180 Se eliminará el siguiente carácter.
182 carácter
184 Se eliminarán los siguientes caracteres.
186 caracteres
188 Se ha completado el registro
190 Código:
192 Intervalo de códigos:

$ There are footer message label.
194 Mensaje:

$ There are user-visible labels in code dialog.
196 código...
198 Re Pág
200 Av Pág
202 Aplicar

$ There are title.
204 Editor de caracteres definidos por el usuario: Pregunta
206 Editor de caracteres definidos por el usuario: Advertencia
208 Editor de caracteres definidos por el usuario: Error

$ There are error message of libfal.
300 Se produjo un error fatal.
301 No se puede abrir el archivo de fonts.
302 No se puede leer el archivo de fonts.
303 No queda memoria.
304 Se produjo un error fatal.
305 El archivo de fonts especificado no existe.
306 Este font no es pcf ni snf.
307 No se puede abrir el archivo fonts.list.
308 El formato del archivo fonts.list no es válido.
309 Las descripciones del archivo fonts.list no son correctas.
310 El formato del archivo fonts.list no es válido.
311 No se puede abrir el archivo fonts.dir.
312 No se puede leer el archivo fonts.dir.
313 No se pueden leer las propiedades del font.
314 No se puede obtener la propiedad FONT.
315 No se puede obtener la propiedad FAMILY_NAME.
316 Otra aplicación ya ha abierto este archivo de fonts.
317 No se puede bloquear el archivo de fonts.
318 NO se puede desbloquear el archivo de fonts.
319 No se puede obtener información de bloqueo del archivo de fonts.
320 No se puede encontrar el archivo de fonts especificado.
321 No se puede leer la base de datos NLS.
322 No se pueden obtener los nombres del juego de caracteres de la base de datos NLS.
323 El nombre del juego de caracteres no está definido en la base de datos NLS.
324 No se ha abierto el font especificado.
325 Se produjo un error fatal.
