$     
$ +SNOTICE    
$     
$  $XConsortium: MotifApp.msg /main/5 1996/10/19 14:45:32 rws $    
$     
$  RESTRICTED CONFIDENTIAL INFORMATION:    
$     
$  The information in this document is subject to special    
$  restrictions in a confidential disclosure agreement between    
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this    
$  document outside HP, IBM, Sun, USL, SCO, or Univel without    
$  Sun's specific written approval.  This document and all copies    
$  and derivative works thereof must be returned or destroyed at    
$  Sun's request.    
$     
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.    
$     
$ +ENOTICE    
$     

$quote "

$set 1
1 "¿Desea realmente ejecutar este mandato?"
2 "OK"
3 "Cancelar"
4 "Diálogo de la Versión DtMail"
5 "Diálogo de la Versión DtMail"
6 "Debe seleccionar un componente dentro de su apl.\n"
7 "Ayuda DtMail"
8 "Ayuda DtMail"
9 "¿Cerrar esta carpeta?"
10 "Este mandato no se puede deshacer. ¿Se sigue de todas formas?"

11 "Mostrar carpetas y archivos ocultos"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "Mailer : Ayuda"

$set 2        Redefine set#
1 "Error de selección, no se puede continuar\n"
2 "Selección cancelada por el usuario.\n"
