$ $XConsortium: libAButil.msg /main/3 1995/11/06 18:51:40 rswiston $
$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.5 02 Apr 1995 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR: error in allocating to int array\n"
2 "ISTR: error in allocating space for string\n"
3 "ISTR: error in allocating memory"
4 "Internal error"
5 "Recursive function calls"
6 "Permission denied"
7 "Couldn't open"
8 "Data space is full"
9 "Buffer is too small"
10 "Functionality is not implemented"
11 "Not initialized"
12 "Client error"
13 "Not found"
14 "Duplicate key"
15 "Bad parameter"
16 "I/O error"
17 "File not found"
18 "Could not open file"
19 "Could not write to file"
20 "Could not read file"
21 "End of file"
22 "Bad file format"
23 "Could not rename file"
24 "Memory error"
25 "No memory"
26 "Memory is corrupt"
27 "Multiple free of memory"
28 "Read-only file"
29 "Could not backup file"
30 "Unrecognized file format"
31 "The file %s does not appear to be in BIL\nformat. Either a BIL header (:bil-version) was\nnot found or the header is corrupt."
32 "Incompatible BIL version"
33 "The version of the BIL file %s (%3.2f)\nis not supported in this version of App Builder."
34 "No help text available"
35 "NoName"
