/* XPM */
/* $XConsortium: printmgr.pm /main/3 1996/12/18 01:43:52 cde-hit $ */
static char * DtPrtmg_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s topShadowColor m white c #bdbdbdbdbdbd",
"o	s iconColor2	m white	c white",
"O    s iconGray4     m white c #949494949494",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray6     m black c #636363636363",
"#    s iconGray1     m white c #dededededede",
"$    s iconGray5     m black c #737373737373",
"%    s iconGray3     m white c #adadadadadad",
"&    s iconGray7     m black c #424242424242",
"*    s iconGray8     m black c #212121212121",
"=	s iconColor1	m black	c black",
"-	s iconColor4	m white	c green",
/* pixels */
"                                ",
"         ..............X        ",
"         .ooooooooooooOX        ",
"         .o++ooooo+++o@X        ",
"         .oooooooooooo@X        ",
"         .o+++++o++++o@X        ",
"       ...oooooooooooo@X.....X  ",
"      .##$o+++oo+++o+o@o%%%%%&X ",
"     .o+$$oooooooooooo@#+++++%*X",
"    .$++***************=++++++*X",
"    .$##oooooooooo############*X",
"   .@$$@@@@@@@@@@@++++#@@@@@@#*X",
"   .Oo++ooooo+++o&#####@----@#*X",
"   .Ooooooooooooo&#$$$$@@@@@@#*X",
"   .Oo+++++o++++o&############*X",
"   .Ooooooooooooo&############*X",
"  .oOo+++oo+++o+o&$$$$$&++####*X",
" .+$Ooooooooooooo@#OOOOO&+####*X",
".++***************&++++++******X",
".########################*&&*&*X",
".#+++++++++++++++#@@@@@@#****&X ",
".#################@----@#*XXXX  ",
".##$$$$$$$$$$$$$$$@@@@@@#*X     ",
".########################*X     ",
".########################*X     ",
".##****************######*X     ",
".##*#$$$$$$$$$$$$$*######*X     ",
".**#%%%%%%%%%%%%%%%*******X     ",
"XX&O$$$$$$$$$$$$$$$&&&&*&&X     ",
"  *@@@@@@@@@@@@@@@@*****&X      ",
"  X****************XXXXXX       ",
"   XXXXXXXXXXXXXXXX             "};
