/* XPM */
/* $XConsortium: scricon.pm /main/2 1996/07/23 12:46:25 drk $ */
static char * ScreenOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 8 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray1     m white c #dededededede",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray3     m white c #adadadadadad",
"+    s iconGray7     m black c #424242424242",
"@	s iconColor5	m black	c blue",
"#	s iconColor2	m white	c white",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"           .........................................            ",
"           .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOO+++++++++++++++++++++++++++++++++OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@###@###@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOO+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#OO+o            ",
"           .XOO+################################OO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+o            ",
"           .X++++++++++++++++++++++++++++++++++++++o            ",
"           .oooooooooooooooooooooooooooooooooooooooo            ",
"                                                                ",
"                                                                ",
"                                                                "};
