$ $XConsortium: dttypes.msg /main/3 1995/11/08 12:44:52 rswiston $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"Impossibile inizializzare tutto\n"
4	"VUOTO"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"caricato da %s\n"
10	"Sconosciuto"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"errore = %o, %s\n"
$ Translate "error" only
25	"Sintassi: dttypes [-help]\n\tdttypes [-type nomefile]\n\tdttypes [-db database] [-w [rec_name esp_reg] [fld_name esp_reg]\n\t\t\t[fld_value esp_reg]]\n\t\t[-l [rec_name] [rec_info] [fld_name esp_reg] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s è di tipo %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"Database non valido\n"
31	"Argomento non valido\n"
32	"Campo rec_info non valido nell'opzione -w\n"
$ do not translate "rec_info" or "-w"
33	"Non presente nell'opzione -w o -l\n"
$ do not translate "-w" or "-l"
34	"Opzione sconosciuta\n"
35	"-help"
$ Do not Translate
36	"Errore nell'espressione regolare %s\n"
