$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 BDF file selection
4 Un file del nome specificato esiste già. Sovrascriverlo?
6 Impossibile aprire il file selezionato.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 Questo font non contiene caratteri definiti dall'utente.
4 Impossibile aprire il font selezionato. L'autorizzazione non è sufficiente o il formato del file non è corretto.
6 Il file del font è già in uso da un'altra applicazione di definizione caratteri (UDC).
8 Nessun font
10 Aprire
12 Annullare
14 Utilità scambio dati UDC 
16 Selezionare
18 -  InsiemeCodici: 
20 -          Stile: 
22 -      Larghezza:
24 -        Altezza:

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 Interrompere lo scambio dati UDC?
4 Questo font non contiene caratteri definiti dall'utente
6 Il nome XLFD non è selezionato
8 Impossibile aprire il file dei font
10 Il file del font è già in uso da un'altra applicazione di definizione carattere UDC.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 Utilità scambio data UDC
4 Errore irreversibile.
6 Impossibile aprire il file dei font.
8 Impossibile leggere il file dei font.
10 Memoria esaurita.
12 Errore irreversibile.
14 Il file specificato è introvabile.
16 Questo non è un font pcf o snf.
18 Impossibile aprire il file fonts.list
20 Il formato del file fonts.list non è valido.
22 Le descrizioni del file fonts.list file non sono corrette.
24 Il formato del file fonts.list non è valido.
26 Impossibile aprire il file fonts.dir
28 Impossibile leggere il file fonts.dir
30 Impossibile leggere le caratteristiche del font.
32 Impossibile ottenere la caratteristica FONT.
34 Impossibile ottenere la caratteristica FAMILY_NAME.
36 Questo file dei font è già in uso da un'altra applicazione.
38 Impossibile bloccare il file dei font.
40 Impossibile sbloccare il file dei font.
42 Impossibile identificare l'applicazione che ha aperto il file dei font.
44 Il file specificato è introvabile.
46 Impossibile leggere il database NLS.
48 Impossibile ottenere i nomi charset dal database NLS.
50 Il nome Charset non è stato definito nel database NLS.
52 Il font specificato non è stato aperto.
54 Errore irreversibile
56                  Nome XLFD :
58 Font originale (nome XLFD) :
60          Intervallo codici :
62                      Stile :
64 Dimensione (del carattere) :
66 Aprire
68 Annullare
70 Ok
72 annullare
74       Codice originale (esadecimale) :
76 Codice di destinazione (esadecimale) :
78 Copiare
80 Sovrapporre
82 esportazione
84 importazione
86 Annullare

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 La creazione del file BDF è fallita.
4 Non c'è un indice selezionato.
6 Ok
8 Annullare
10 indici dei caratteri

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Non è possibile aggiungere al font le immagini contenute in questo file BDF.
4 L'apertura del file BDF è fallita. L'autorizzazione non è sufficiente o il formato del file non è valido.
6 Una o piu' immagini verranno sovrascritte. Sovrascriverle?
8 Impossibile aprire il font selezionato. L'autorizzazione non è sufficiente o il formato del file non è valido. 
10 Non è possibile aggiungere al font le immagini contenute in questo file BDF.
12 La registrazione del file dei font è fallita.
