$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcfonted.msg
$ **
$ **  Project:     Fujitsu DT UDC Font Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcfonted
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **
$set 2
$ *****************************************************************************
$ ** _DtMessage set for ufont.c
$ *****************************************************************************

$ This is footer message when registration of the character.
2 Registrazione in corso...

$ Message4-8 are error messages when registration of the character.
4 La registrazione del carattere è fallita.
6 Codice non ammesso.
8 Impossibile allocare la memoria necessaria per registrare il carattere.

$ Message10-16 are error messages when copying of the character.
10 Non si trova un carattere del codice specificato.
12 Errore nel codice originale.
14 Errore nel codice di destinazione.
16 Non si trova un carattere nell'area specificata.

$ This is footer message.
18 Attendere...

$ This is error message when copying of the character.
20 Nessun codice originale è stato specificato.

$ Message22-24 are error message of user defined character
22 Impossibile accedere alle informazioni sul carattere definito dall'utente.Impossibile accedere alle informazioni sul carattere definito dall'utente.\nNon c'è nessun font specificato.
24 Impossibile accedere alle informazioni sul carattere definito dall'utente.\nTroppi font sono stati specificati.

$ UDC is User Defined Character.
26 Il font specificato non contiene un intervallo dove registrare i caratteri definiti dall'utente.

28 Memoria esaurita.
30 Dati non validi nell'area di caratteri definiti dall'utente.
32 Impossibile leggere il file del font.\nL'intervallo dei motivi è stato danneggiato.

$ Dtudcfonted is name of this application.
34 Dtudcfonted non supporta l'editazione di font di caratteri a spaziatura proporzionale.

36 Ci sono modifiche che non sono state salvate.\nSalvarle prima di aprire?
38 Ci sono modifiche che non sono state salvate.\nSalvarle prima di uscire?
40 L'operazione Copiare modificherà l'immagine del carattere\nnel seguente intervallo.\nCopiare?\n\n
42 Autorizzazione di scrittura negata per il font specificato. Cambiare le autorizazzioni del file prima di salvare.\n

$ There are user-visible labels in font-open dialog.
100 Selezionare
102 -  InsiemeCodici:
104 -          Stile:
106 -      Larghezza:
108 -        Altezza:
110 Aprire
112 Uscire

$ There are user-visible labels in menubar.
114 Font
116 Editare
118 Carattere
120 Informazioni

$ There are user-visible labels in File menu.
122 Aprire...
124 Salvare
126 Uscire

$ There are user-visible labels in Edit menu.
$ Message135 is copy of cut&copy
128 Azzerare
130 Dipingere
132 Invertire
134 Tagliare
135 Copiare
136 Incollare
138 Ruotare
140 Capovolgere verticalmente
142 Capovolgere orizzontalmente
144 Annullare

$ There are user-visible labels in Character menu.
$ Message148 is copy of character
146 Aggiungere/Cancellare...
148 Copiare...

$ There are user-visible labels in Information menu.
150 Nome XLFD...
152 Intervallo codici...

$ There are user-visible labels in add/delete dialog.
154 Aggiungere
156 Cancellare
158 Annullare

$ There are user-visible labels in copy dialog.
$ Message166 is label of execute button
160          Codice (esadecimale):
162 Codice original (esadecimale):
164 Codice di destinazione (esadecimale):
166 Copiare
168 Sovrapporre
170 OK

$ There are user-visible labels in unsaved edits.
172 Salvare
174 Non salvare
176 Salvare e uscire
178 Uscire senza salvare

$ There are user-visible labels in delete notice dialog.
$ This format is `Message180 (?? Message182)' and `Message184 (?? Message186)'.
$ These Message180 and Message182 are used in only one character.
$ These Message184 and Message186 are used in plural characters.
180 Il carattere seguente verrà cancellato.
182 carattere
184 I caratteri seguenti verranno cancellati.
186 caratteri
188 Registrazione eseguita.
190 Codice:
192 Intervallo codici:

$ There are footer message label.
194 Messaggio:

$ There are user-visible labels in code dialog.
196 codice...
198 Pagina in sù 
200 Page in giù 
202 Applicare

$ There are title.
204 Editor del carattere definito dall'utente: Domanda
206 Editor del carattere definito dall'utente: Avvertenza
208 Editor del carattere definito dall'utente: Errore

$ There are error message of libfal.
300 Errore irreversibile.
301 Impossibile aprire il file del font.
302 Impossibile leggere il file del font.
303 Memoria esaurita.
304 Errore irreversibile.
305 Il file specificato è introvabile.
306 Questo non è un font pcf o snf.
307 Impossibile aprire il file fonts.list
308 Il formato del file fonts.list non è valido.
309 Le descrizioni del file fonts.list file non sono corrette.
310 Il formato del file fonts.list non è valido.
311 Impossibile aprire il file fonts.dir 
312 Impossibile leggere il file fonts.dir
313 Impossibile leggere le caratteristiche del font.
314 Impossibile ottenere la caratteristica FONT. Impossibile identificare l'applicazione che ha aperto il file del font.
315 Impossibile ottenere la caratteristica FAMILY_NAME.
316 Questo file del font è stato aperto da un'altra applicazione.
317 Impossibile bloccare il file del font.
318 Impossibile sbloccare il file del font.
319 Impossibile identificare l'applicazione che ha aperto il file del font.
320 Il file specificato è introvabile.
321 Impossibile leggere il database NLS.
322 Impossibile ottenere i nomi charset dal database NLS.
323 Il nome Charset non è stato definito nel database NLS.
324 Il font specificato non è stato aperto.
325 Errore irreversibile.
