$ $XConsortium: libABobjXm.msg /main/1 1995/12/08 09:28:49 rswiston $

$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.2 13 Sep 1994 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "ATTENZIONE: %s : Impossibile convertire il nome del file[%s] in pixmap\n"
2 "ATTENZIONE: %s : Non è stato specificato alcun nome per il file del simbolo\n"
3 "ERRORE: %s: L'allegato dell'oggetto è VUOTO\n"
4 "ERRORE di istanza: %s: L'ID del widget padre è VUOTO\n"
5 "ERRORE di istanza: %s: Impossibile istanziare il menu\n"
6 "ERRORE di istanza: L'oggetto deve avere un nome valido\n"
7 "ERRORE di istanza: %s: L'oggetto deve avere la classe del widget\n"
8 "ERRORE INTERNO: I valori dei contatori non corrispondono.\n"
9 "ERRORE: objxm_comp_get_subobj - Oggetto non configurato xm: %s\n"
10 "Cartelle"
11 "Filtro"
12 "Nome del file"
13 "Aggiornare"
