$ $XConsortium: dtcopy.msg /main/3 1996/07/24 19:02:41 drk $
$ *****************************************************************************
$ **
$ **  File:        dtcopy.msg
$ **
$ **  Project:     CDE File Manager
$ **
$ *****************************************************************************

$set 2
$ ****** Module: main_dtcopy.c ******
3 óòÕù
4 óòÕù
5 ÄÍóòÕùÉè
6 ÄÍóòÕùÉè
7 òãë¨¡¨ àÒ
8 òãë¨¡¨ %d
10 ÆîÎÎ¡¨ %s [òÙâú ...] ËôäãÆøíº\n
11 óòÕùê§Ü¡ÔÞ -- óòÕùÉèÜÃÙ¯
12 óòÕùê§Ü¡ÔÞ -- óòÕùÉèîïêû
13 ÇÞÒ³òãë¨¡¢%s ÆÜØæÆª¡¤
14 ÉùÈ©¡¤
15 Ì½Ö¼Íõ
$ ** Message 20 - 32
$ ** LongFileOpNames ... message number = op + 20.
20 Ý¨Ü¡Äã
21 âäÚöÄã
22 âäÚöÄã
23 âäÚöÄã
24 ûôÌ½ÝÙá¸
25 É´ØæÄã
26 îïêûÄã
27 ÐúÇ¡Æøòç
28 îïêûÝÙá¸
29 ÐúÇ¡ÝÙá¸
30 ÄÖÉ¢Äã
31 ÑÒÄ¡Ô¶îïêû
32 ÑÒÄ¡Ô¶ÝÙá¸
33 Þ·ïõ

$set 3
$ ****** Module: copydialog.c ******
1 ú«úý
2 í²Øô
3 ÜÃÙ¯Äã¡¨
4 îïêûÄã¡¨
5 ÈÝóòÕùÉè¡¨
7 ÝÕíµÙòØôÅÏîïêûá£Ê©¡¤ Ç¶ÈôÄØîïêûÎû\n\
óòÕùÙòÖçÇãÆøíºóòÕùÉèÄã¡¤
10 ÝÕíµÙòØôÅÏÜÃÙ¯á£Ê©¡¤ Ç¶ÈôÄØÜÃÙ¯Îû\n\
óòÕùÙòÖçÇãÆøíºóòÕùÉèÄã¡¤
11 óòÕùÉèîïêû -- úÀÉË
12 óòÕùÉèÜÃÙ¯ -- úÀÉË
13 Ì½Ö¼îïêû
14 ú«úýîïêû
15 Ì½Ö¼ÜÃÙ¯
16 ú«úýÜÃÙ¯
17 ÄØÜÃÙ¯
18 ÄØîïêû

$set 4
$ ****** Module: errordialog.c ******
1 òãë¨ %s\n%s
2 ÇÞòãë¨ÈÔí²Øô
3 óòÕùÉèîïêû -- òãë¨
4 óòÕùÉèÜÃÙ¯ -- òãë¨

5 "ÎìÇµÜÃÙ¯ - òãë¨"

6 "ÎìÇµîïêû - òãë¨"

7 "ÎìÇµÌ×Éãóò - òãë¨"

8 "ÄâÄøÝÂÚÀÙòÎìÇµ \n\n\
    %s\n\n\
ÍóÄ«Ì×Éãóò.\n\n\
Use the Change Permissions choice from the object's\n\
popup menu or from the Selected menu to turn on your\n\
Read permission on the object.\n\n\n\
Note: If this object is a folder, you must also have\n\
Read permission for each of the objects inside the\n\
folder before you can put the folder in the trash."


$set 5
$ ****** Module: overwrtdialog.c ******
1 ÇØê¢Ò³\n%s\nÎûóòÕùÄØÇôÇãóòÕùÉèÄã\n%s
2 óòÕùÉèÜÃÙ¯ -- óòÕùÓììÑ
3 Ì½ÅîÇôÇãÎûóòÕù
4 ÙòÇôÇãÎûóòÕùÓìä»ÌÔÇØÒ³¡¨
5 Ùòä»ÎìÇµÓìä»ÌÔÇØÒ³¡¨
6 Ü©ç´ÝÕÔ¶óòÕù
7 É»Ì«ÙòÈºÙ¯É¢óÜÆîÍõÚÙúýÎûÇØê¢îíÒóÄã¡¤
8 ÛÃÚèÌ½ÎûÙ¯É¢¡¨
9 óòÕùÉèîïêû -- óòÕùÓììÑ
10 %s\nÄØÇôÇã¡¨îùòÙðåÆ¶ÆÀÎûÇØê¢¡¤
11 óòÕùÓììÑ -- òãë¨
12 %s\nàÒÎÎÓìä»ÌÔÇØÒ³\n%s\n%s

$set 6
$ ****** Module: utils.c ******
$ ** Button labels.
1 íýÌù
2 í²Øô
3 Ì½Ö¼
4 ëºÉ·ë©Íü
5 ÆøòçîïêûëºÉ·ë©Íü
6 ú«úý
7 Ì½Ö¼îïêû
8 Ì½Ö¼ÜÃÙ¯
