$ $XConsortium: dticon.msg /main/3 1995/11/08 14:06:53 rswiston $
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dticon.msg
$ **
$ **  Project:     HP DT Icon Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dticon
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company
$ **     (c) Copyright 1993, 1994 International Business Machines Corp.
$ **     (c) Copyright 1993, 1994 Sun Microsystems, Inc.
$ **     (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
$ **         Novell, Inc.
$ **
$ **     All Rights reserved
$ **
$ **
$ *****************************************************************************
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for fileIODialog.c
$ **
$ ** messages 10-16 are for the FileSelectionBox widget (default labels)
$ *****************************************************************************

2 è·çùî¾òÒğÂ -- óòÕùòÓÄ«/òÓÅø
4 è·çùî¾òÒğÂ -- óòÕùòÓÄ«/òÓÅø
6 è·çùî¾òÒğÂ -- óÃÇôÒ³
8 è·çùî¾òÒğÂ -- âäÚöóòÕù
10 ÊÕä»
12 óòÕùÉè
14 óòÕù
16 òÓÄ«óòÇØ¡¨
17 òÓÄ«óòÇØ¡¨
18 ÊÕä»
20 ÆÜÌùíº÷î
22 âäÚö
24 óÃÇô

$set 4
$ *****************************************************************************
$ ** _DtMessage set for newIconDialog.c
$ **
$ *****************************************************************************

2 ä»è·çùè×æãÕú
4 è·çùî¾òÒğÂ -- Óìä»ÊÕÊÑÄËÄÑ
6 íıÌù
8 Ì½Ö¼
10 ëºÉ·ë©Íü
12 ä»ìÏĞù¡¨
14 ä»ØíĞù¡¨

$set 6
$ *****************************************************************************
$ ** _DtMessage set for queryDialog.c
$ **
$ *****************************************************************************

2 è·çùî¾òÒğÂ -- úÀÉË
6 íıÌù
$ ** DO NOT LOCALIZE - the user should never see this message
8 Do ya really wanna?
10 Ì½Ö¼

$set 8
$ *****************************************************************************
$ ** _DtMessage set for stdErrDialog.c
$ **
$ *****************************************************************************

2 è·çùî¾òÒğÂ -- òãë¨
4 ú«úı

$set 10
$ *****************************************************************************
$ ** _DtMessage set for utils.c
$ **
$ *****************************************************************************

$ ** DO NOT LOCALIZE messages 2-48, they appear in the errorlog only
2 Cannot initialize button icon for circle
4 Cannot initialize button icon for solid circle
6 Cannot initialize button icon for polyline
8 Cannot initialize button icon for polygon
10 Cannot initialize button icon for solid polygon
12 Cannot initialize button icon for ellipse
14 Cannot initialize button icon for solid ellipse
16 Cannot initialize button icon for eraser
18 Cannot initialize button icon for line
20 Cannot initialize button icon for flood
22 Cannot initialize button icon for point
24 Cannot initialize button icon for rectangle
26 Cannot initialize button icon for solid rectangle
28 Cannot initialize button icon for select
30 Unable to parse static color no.
32 Unable to allocate static color no.
38 No memory(0)
40 No memory(1)
42 No memory(2)
44 No memory(3)
46 No memory(4)
48 No memory(5)

50 àÒÎÎÏÏËğÅ§óÜÆîá£È¢è·çùóÃÇôğÂ
52 '-f' Ù¶í°ÄæàÒÕæËğÆî
54 '-i' Ù¶í°ÄæàÒÕæËğÆî
56 '-session' Ù¶í°ÄæàÒÕæËğÆî
58 àÒÕæÎûÄËÄÑİ½Öª
60 ò­èİìàçùÊÎÌ½ÆÂÚõ
62 É¢äÆÆÂÚõ¡¤\nÈãÚ³è·ÄØéÈ
64 àÒÕæÎûî¯ŞØÙ¶í°

66 (ÆÜÌÔÇØ)


$set 12
$ *****************************************************************************
$ ** _DtMessage set for dtIconShell.c
$ **
$ *****************************************************************************

1 è·çùî¾òÒğÂ
2 ÷äÈã
3 è·çùî¾òÒğÂ -- (ÆÜÌÔÇØ)
4 ûãÏÒËğÆîè·çùî¾òÒğÂ¡¤
6 ãØÄ«èÒüÕ
8 òûèèÈãÚ³
10 Ù¯èèÈãÚ³
12 òûèèÈÈÈã
14 Ğ©ßß
16 Ó¬ßß
18 Ş¡ê¦İõìà
20 Íµê¦İõìà
22 òÙÌ½
24 İàÍü

$ ** message 26-198 are menu items with corresponding mnemonics
$ ** (for set grouping information, see the comment at the end-of-file)
26 N
28 ÛÒØæ(N)...
30 O
32 âäÚö(O)...
34 S
36 óÃÇô(S)
38 A
40 óÃÇôÒ³(A)...
42 x
44 á¸ÊÖ(x)
46 F
48 óòÕù(F)
50 U
52 ß¦ÔÏ(U)
54 t
56 ÙªÌ½Ù´ÙÑ(t)
58 C
60 ëºÉ·Ù´ÙÑ(C)
62 P
64 ¢¸¤â²Ù´ÙÑ(P)
68 L
70 ÆÊ(L)
72 R
74 Æ­(R)
76 R
78 Û¡÷ËÙ´ÙÑ(R)
82 V
84 ĞÍÎş(V)
86 H
88 ÅÕÆÍ(H)
90 F
92 ÆßÅ°÷ËÙ´ÙÑ(F)
94 S
96 ÅÒËóÅ¹Ù´ÙÑ(S)
98 z
100 ÊÕÊÑÄËÄÑÎûè·çù(z)...
102 A
104 ìÁÅûÉ¢Æîöµ(A)
106 D
108 É´ØæÉ¢Æîöµ(D)
110 G
112 ÊÎÌ½ò­èİìàçù(G)
114 e
116 ÛÒØæè·çù(e)
118 E
120 î¾òÒ(E)
122 V
124 Æ«ËÄê½öµ(V)
128 B
130 XBM(B)
134 P
136 XPM(P)
138 O
140 òÓÅøÖªÈ¢(O)
144 2x
146 3x
148 4x
150 5x
152 6x
154 8x
156 10x
158 12x
160 M
162 ÍóÄË(M)
164 O
166 òÙâú(O)
168 v
170 äÍı¨(v)...
172 T
174 ÄÖÉ¢(T)...
176 R
178 Ù¶ÈÓæñÕè(R)...
180 O
182 ùÃÍõâúÆø(O)
188 U
190 ËğÆîëºÉ·ë©Íü(U)...
192 A
194 ùÃÍõè·çùî¾òÒğÂ(A)...
196 H
198 ëºÉ·ë©Íü(H)

$ ** message 200-are used in the "instruction" line for current drawing mode
200 ÆøĞ©î¾òÒí¼È¢
202 (ÄØãØÄ«)
204 çÅá­
206 ãØéÈ
208 îÀÛ¾
210 ÇéÓìîÀ
212 ÏÛÅÉÊ°
214 Çéù±Ê°
216 ãÑ
218 ğûãÑ
220 Ö¼Øæ
222 òÙÌ½
224 àÒÕæ

$set 14
$ *****************************************************************************
$ ** _DtMessage set for help.c
$ **
$ *****************************************************************************

2 è·çùî¾òÒğÂ -- ëºÉ·ë©Íü
4 ÚÀÆÒâüÇãè·çùî¾òÒğÂÄù\nòÙğåÄ¡Ô¶âúÆø¡¤

$set 16
$ *****************************************************************************
$ ** _DtMessage set for process.c
$ **
$ *****************************************************************************

2 ÆÛóòÕùàÒÎÎÇôÌ½\nÍĞÅıÉÖàÒÕæÎûæñÕè
4 àÒÎÎÙòæñÕèìÑÄ«óòÕù
6 İÕÔ¶ÖÖÍÌÌşàÒÎÎËğÆî
8 àÒÇ¿Ğ©Îû\nìàçùÆ«Æî
10 ÑÀÌùÄ§àÒÕæÎû\nìÏĞùêØ/ÍĞØíĞù
12 ÆÜòÙÌ½Ù´ÙÑ
14 àÒÙ´ÙÑÇãÇ¿Ğ©İ·\nÙªÌ½ÍĞîïêû
16 ÆøĞ©Îûè·çùÌşÆÜóÃÇô¡¤\n\nÚÀØøÎûÊÕÊÑäÄéÅÆÂ¡¤
20 óôÑçóòÕùİÂÆ«ûâ
22 àÒÎÎÈÜóòÕùÄãÇßß¦âêÑôóòÕù
24 àÒÎÎÙòâêÑôóòÕùÇôÄ«óòÕùÄã

$ *****************************************************************************
$ ** End of _DtMessage Catalog File
$ ** (Comments only below this line)
$ *****************************************************************************
$ **
$ *****************************************************************************
$ ** Unique mnemonic groupings from set 12
$ *****************************************************************************
$ **
$ ** Unique Set 1:  (Main Menu Bar)
$ **
$ **   46 F
$ **   48 File
$ **
$ **   118 E
$ **   120 Edit
$ **
$ **   164 O
$ **   166 Options
$ **
$ **   196 H
$ **   198 Help
$ **
$ **
$ ** Unique Set 2:  (File Menu)
$ **
$ **   26 N
$ **   28 New...
$ **   30 O
$ **   32 Open...
$ **   34 S
$ **   36 Save
$ **   38 A
$ **   40 Save As...
$ **   42 x
$ **   44 Exit
$ **
$ **
$ ** Unique Set 3:  (Edit Menu)
$ **
$ **   50 U
$ **   52 Undo
$ **   54 t
$ **   56 Cut Area
$ **   58 C
$ **   60 Copy Area
$ **   62 P
$ **   64 Paste Area
$ **
$ **        Unique Set 3a:  (Rotate Sub-Menu)
$ **        68 L
$ **        70 Left
$ **        72 R
$ **        74 Right
$ **   76 R
$ **   78 Rotate Area
$ **
$ **        Unique Set 3b:  (Flip Sub-Menu)
$ **        82 V
$ **        84 Vertical
$ **        86 H
$ **        88 Horizontal
$ **   90 F
$ **   92 Flip Area
$ **   94 S
$ **   96 Scale Area
$ **   98 z
$ **   100 Resize Icon...
$ **   102 A
$ **   104 Add Hot Spot
$ **   106 D
$ **   108 Delete Hot Spot
$ **   110 G
$ **   112 Grab Screen Image
$ **   114 e
$ **   116 Clear Icon
$ **
$ **
$ ** Unique Set 4:  (Options Menu)
$ **
$ **   122 V
$ **   124 Visible Grid
$ **
$ **        Unique Set 4a:  (Output Sub-Menu)
$ **        128 B
$ **        130 XBM
$ **        134 P
$ **        136 XPM
$ **   138 O
$ **   140 Output Format
$ **   160 M
$ **   162 Magnification
$ **
$ **
$ ** Unique Set 5:  (Help Menu)
$ **
$ **   168 I
$ **   170 Introduction...
$ **   172 T
$ **   174 Tasks...
$ **   176 R
$ **   178 Reference...
$ **   180 O
$ **   182 On Item
$ **   188 U
$ **   190 Using Help...
$ **   192 V
$ **   194 Version...
$ **
