$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:50:38 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s¡¨ÌÔÅïÈçòÙâúòãë¨ \"%s\"\n\n"
2 "1386-102 \nõïÄ« %s -help É»Æ«ÚµÌ¯ÉùðìÎûë©Íü¡¤\n\n"

3 "1386-103 ÆîÎÎ¡¨\n        %s [-options ...]\n\n\
	 òÙâúÅýÑÄ¡¨\n"
5 "1386-105    %-28s %s\n\t í¼èèÒ³ÅèÄ¶ÄæÄ¡¡¨\n\", \"-mode mode\", \"animation mode"

7 "1386-107 ÆÜÏ¡Îûí¼èè¡¨"
10 "1386-110 àÒÎÎØÙåô¡¨%s\n"
11 "1386-111 ØÙåô %d Ô¶è·çùÞÌÄ÷\n"

17 "1386-117 %s¡¨àÒÎÎâäÚöüÏÆüðÂ %s¡¤\n"
18 "1386-118 %s¡¨GetResource - àÒÎÎØÙåôØ´ðÙüÕ"
19 "1386-119 %s¡¨-display Å¿í°ÖªÈ¢òãë¨¡¢\"%s\"\n"

20 "1386-120 -batchcount Å¿í°âüÒ³Æßí°¡¤"
21 "1386-121 -saturation Å¿í°ÆÒâüÄõÍõ 0.0 êØ 1.0 Äæâæ¡¤"

25 "1386-125 %s¡¨Æ·×äÅÅßÎ %d Ô¶ò­èÝ¡¤\n"
30 "1386-130 -delay Å¿í°âüÒ³Æßí°¡¤"
35 "1386-135 àÒÎÎØÙåô¡¨%s¡¢Åè %s Ì½Åî\n"
40 "%s¡¨àÒÎÎÊÆÌ¯áþá§Ëôøãè·¡¤ËðÆî -create\n\
        òÙâúÆ«üé %s ÐúÇ¡ÆÆÈÜÄ×Îûáþá§¡¤\n"

