$ $XConsortium: dttypes.msg /main/2 1996/07/24 19:03:29 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"àÒÎÎÙòÇ¶ÈôÎìÇµØÄÌîÝÃÌù\n"
4	"Ï¨ÇóÈë"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"ÈÜ %sç¥Ä«\n"
10	"ÄâÍüÎû"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" ¡¨\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"òãë¨ = %o, %s\n"
$ Translate "error" only
25	"ÆîÎÎ:  dttypes [-help]\n\tdttypes [-type filename]\n\tdttypes [-db database] [-w [rec_name regexp] [fld_name regexp]\n\t\t\t[fld_value regexp]]\n\t\t[-l [rec_name] [rec_info] [fld_name regexp] [fld_value]]\n"
$ Translate only the following¡¨ "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s ÎûùËÉ±ÑÒ %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"àÒÕæÎûæñÕèÕ»\n"
31	"ÄâÑÒÈ´ÕæÎûÅ¿í°\n"
32	"àÒÕæÎû rec_info úñÈíÇã  -w òÙâúÄã\n"
$ do not translate "rec_info" or "-w"
33	"ÄâÇã -w ÍÐ -l òÙâúÄã\n"
$ do not translate "-w" or "-l"
34	"ÄâÍüÎûòÙâú\n"
35	"-help"
$ Do not Translate
36	"Ä¡×ïÏÐÆüÈ¢ %s ÄãÈ´òãë¨\n"

