$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.2 13 Sep 1994 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR¡¨ØÙåôÌ¯ðìí°ØâÇÄÕëàõÆíòãë¨\n"
2 "ISTR¡¨Ò³ÇóÈëØÙåôÏ¨âæÕëàõÆíòãë¨\n"
3 "ISTR¡¨ØÙåôØ´ðÙüÕÕëàõÆíòãë¨"
4 "ÄùÝåòãë¨"
5 "ëÄØÏÈ¢ÌªÈ¢ÌËÆµ"
6 "ÄâÝ·ÝÂÆ«"
7 "àÒÎÎâäÚö"
