$ $XConsortium$

$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.2 13 Sep 1994 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "úÀÉË¡¨%s ¡¨àÒÎÎÙòóòÕùÇØê¢[%s]÷ËßÐÈ©è·çùÑÐ\n"
2 "úÀÉË¡¨%s ¡¨ÆÜÑÀÌùóòÕùÇØê¢\n"
3 "òãë¨¡¨%s¡¨ÊôÈ´ÎìÇµÏáááÎì\n"
4 "Ì¦üÕÅ§òãë¨¡¨%s¡¨Æàá£Ê©Äæwidget-ID ÑÒÏ¨ÆõÎû\n"
5 "Ì¦üÕÅ§òãë¨¡¨%s¡¨àÒÎÎÙòÅü×äÏÐÌ¦üÕÅ§\n"
6 "Ì¦üÕÅ§òãë¨¡¨ÎìÇµÆÒâüÈ´È´ÕæÎûÇØê¢\n"
7 "Ì¦üÕÅ§òãë¨¡¨%s¡¨ÎìÇµÆÒâüÈ´ widget á«×È\n"
8 "ÄùÝåòãë¨¡¨ÓÓí°ÄâÜÊÇÙ\n"
9 "òãë¨¡¨objxm_comp_get_subobj - ÎìÇµÆÜ xmconfigured¡¨%s\n"
10 "óòÕùÉè"
11 "ç´öÛðÂ"
12 "õïÄ«óòÇØ"
13 "ÊÕä»"
