$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/3 1995/11/08 14:04:03 rswiston $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$ -------------------------------------
$ MotifApp/Application.C
$ 

$quote "

$ -------------------------------------
$ MotifApp/AskFirstCmd.C
$ 

$quote "


$set 1
1 "ÚÀÖøÎûÓÑÙÚÈçÝÕÔ¶ÌÔÅïãÃ?"
$ -------------------------------------
$ MotifApp/DialogManager.C
$ 

$quote "


2 "íýÌù"
3 "Ì½Ö¼"
$ -------------------------------------
$ MotifApp/Help.C
$ 

$quote "


4 "DtMail ÎêÆÛè×æã"
5 "DtMail ÎêÆÛè×æã"
6 "ÚÀÆÒâüÇãóÜÆîá£È¢ÄãòÙÌ½Ä¡Ô¶Ä÷Çµ¡¤\n"
7 "DtMail Help"
8 "DtMail Help"


$quote "


9 "Close this folder?"
$ -------------------------------------
$ MotifApp/WarnNoUndoCmd.C
$ 

$quote "


10 "ÈºÑÀÅïàÒÎÎõäÔÏ¡¤Äó÷®ÓÑú«úýãÃ?"

$quote "

$set 2
1 "òÙðåòãë¨¡¢àÒÎÎú«úý\n" 
2 "ËðÆîÏ¯ÈÜÈçÄãöËòÙðå¡¤\n" 
$ -------------------------------------
$ MotifApp/QuitCmd.C
$ 
