$ $TOG: dtcm.msg /main/10 1999/09/20 10:36:17 mgreess $

$quote "


$set	1
1 "dtcm: メール通知の郵便受けが空です。\n"
2 "通知- %s"
3 "pm"
4 "am"
7 "\n\n\t** カレンダ・アポイント **\n\n\t日付:\t%s\n\t開始:\t%s\n\t終了:\t%s\n\t内容:\t%s"
16 "デフォルト・カレンダを削除できない可能性があります。"
17 "削除する名前を選択します。"
20 "[日付指定] フィールドの日付が無効です。"
21 "リスト編集..."
22 "ブラウズメニュー項目"
23 "前週"
24 "今週"
25 "翌週"
26 "前月"
27 "翌月"
28 "日付指定:"
29 "スケジュール..."
30 "メール..."
31 "個のカレンダを表示"
32 "個のカレンダを表示"
33 "日(D)"
34 "週(W)"
35 "月(M)"
36 "年(Y)"
37 "タイムゾーン(Z)..."
38 "アポイントリスト(A)..."
40 "表示(V)"
41 "検索(F)..."
42 "日付で検索(G)..."
65 "ファイル(F)"
68 "現在の表示の印刷(C)"
69 "印刷(P)..."
72 "オプション(O)..."
73 "終了(x)"
74 "アポイント(A)..."
76 "編集(E)"
77 "ヘルプ(H)"
79 "使い方(T)..."
80 "リファレンス(R)..."
82 "ヘルプの使い方(U)..."
84 "他の人のカレンダを表示(O)..."
85 "カレンダの比較(C)..."
86 "メニュー・エディタ(M)..."
87 "ブラウズ(B)"
88 "今日"
89 "quit_handler 内\n"
90 "カレンダ・ファイルを開いたときにエラーが発生しました。"
91 "rpc.cmsd がユーザ名に応答しません。\ninetd プロセスを実行中であるか、\nおよび rpc.cmsd に対する inetd.conf のエントリが\nご使用のホスト用であるか確認してください。"
92 "ユーザ名"
93 "ホスト"
94 "カレンダ : エラー"
95 "継続"
108 "カレンダの場所を指定していません。"
109 "位置を指定していません。[オプション] の [表示形式の設定] で\nホスト名を [起動時のカレンダ表示] に追加してください。\nカレンダ(dtcm)を -c オプション付きで実行した場合は、\nホスト名を指定したか確認してください。"
110 "カレンダ : エラー - ヘルプ"
113 "カレンダ"
$ 		/* NL_COMMENT
$ 
$ 		   Message 113 : ``Calendar'' is used in the main titlebar 
$ 		   of the tool: Calendar : user@host.
$ 		 */
114 "1 月"
115 "2 月"
116 "3 月"
117 "4 月"
118 "5 月"
119 "6 月"
120 "7 月"
121 "8 月"
122 "9 月"
123 "10 月"
124 "11 月"
125 "12 月"
126 "1 月"
127 "2 月"
128 "3 月"
129 "4 月"
130 "5 月"
131 "6 月"
132 "7 月"
133 "8 月"
134 "9 月"
135 "10 月"
136 "11 月"
137 "12 月"
138 "日曜"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   The strings (message number 138-144) are abbreviations to
$ 	   the days of the week:
$ 
$ 		Sun --> Sunday
$ 		Mon --> Monday
$ 		Tue --> Tuesday
$ 		Wed --> Wednesday
$ 		Thu --> Thursday
$ 		Fri --> Friday
$ 		Sat --> Saturday
$ 		Sun --> Sunday
$ 
$ 	*/
139 "月曜"
140 "火曜"
141 "水曜"
142 "木曜"
143 "金曜"
144 "土曜"
146 "日曜日"
147 "月曜日"
148 "火曜日"
149 "水曜日"
150 "木曜日"
151 "金曜日"
152 "土曜日"
154 "日"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   The strings (message number 154-160, 168) are one letter 
$ 	   abbreviations to the days of the week:
$ 
$ 		S --> Sunday (message 154)
$ 		M --> Monday
$ 		T --> Tuesday
$ 		W --> Wednesday
$ 		T --> Thursday
$ 		F --> Friday
$ 		S --> Saturday (message 160)
$ 
$ 	*/
155 "月"
156 "火"
157 "水"
158 "木"
159 "金"
160 "土"
170 "日"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   The strings (message number 170-176) are abbreviations to
$ 	   the days of the week:
$ 
$ 		SUN --> Sunday
$ 		MON --> Monday
$ 		TUE --> Tuesday
$ 		WED --> Wednesday
$ 		THU --> Thursday
$ 		FRI --> Friday
$ 		SAT --> Saturday
$ 
$ 	*/
171 "月"
172 "火"
173 "水"
174 "木"
175 "金"
176 "土"
178 "すでに %s をブラウズ中です。"
186 "カレンダ(dtcm)と rpc.cmsd のバージョンが違います。"
187 "使用方法:\n\tdtcm_delete [-c カレンダ] [-d <月/日/年>] [-v 表示]\n"
188 "\nカレンダ %s を開けません。\n"
189 "未知"
190 "項目を削除しますか(番号)? "
191 "使用方法:\n\tdtcm_insert [ -c カレンダ ] [-d <mm/dd/yy>] [ -v 表示 ]\n"
192 "                   [-w 内容文字列] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"
193 "追加したいアポイントの情報を入力してください。\nデフォルトを括弧内に示します。\n"
194 "カレンダ (%s): "
195 "日付 (%s): "
196 "開始 (%s): "
197 "無効な時間を入力しました。入力しなおしてください:\n"
198 "終了 (%s): "
199 "終了 (%s): "
200 "一回"
201 "周期 (%s): "
203 "デフォルトはありません。"
204 "期間 (%s): "
205 "内容 (最大 5 行まで入力できます。終了するには ^D を使用します。):\n"
206 "\nカレンダ %s を開けません。\n"
207 "使用方法:\n\tdtcm_lookup [ -c カレンダ ][ -d <月/日/年> ] [ -v 表示 ]\n"
208 "\nカレンダ \"%s\" を開けません。\n"
209 "未知"
210 "現在ブラウズ中のカレンダにアポイントをスケジュールします。\nさらにスケジュールしますか?"
211 "スケジュール先"
212 "カレンダ : アポイントのスケジュール"
214 "アポイントをスケジュールしました: %s"
218 "指定された [日付] は無効です。"
219 "指定された [開始] 時刻は無効です。"
220 "指定された [終了] 時刻は無効です。"
221 "[日付] フィールドが空か、ありません。"
222 "[開始] フィールドが空か、ありません。"
223 "[内容] フィールドが空か、ありません。"
224 "[周期] フィールドと [期間] フィールドが一致しません。"
225 "アポイント・スケジュールを取り消しました。"
226 "アポイントをスケジュールしたときに内部エラーが発生しました。"
230 "カレンダ : エラー - アポイントをドラッグ"
231 "アポイントを選択し、[ドラッグ] を選択しなおしてください。"
236 "カレンダ・アポイント"
237 "ビットマップの XCreateBitmapFromData() が失敗しました。\n"
238 "マスクの XCreateBitmapFromData() が失敗しました。\n"
239 "DragStart が NULL を返しました。\n"
247 "このアポイントに開始時刻よりも早い終了時刻を指定しています。\n終了時刻を翌日にスケジュールしますか?"
248 "カレンダ : アポイントをスケジュール"
250 "翌日"
251 "作成者"
252 "カレンダ : アポイント・エディタ - 削除"
253 "アポイントを選択し、[削除] を選択しなおしてください。"
256 "アポイントの選択で内部エラーが発生しました。\nアポイントを削除しません。"
258 "カレンダ : アポイント・エディタ - 変更"
259 "アポイントを選択し、[変更] を選択しなおしてください。"
268 "このアポイントは周期的アポイントの 1 つです。\n本当に変更しますか...?"
270 "このアポイントのみ"
271 "これ以降"
272 "すべて"
274 "このアポイントは周期的アポイントの 1 つです。\n本当に削除しますか...?"
279 "カレンダ : アポイント・エディタ"
280 "カレンダ : エラー - アポイントリスト"
281 "表示するアポイントがありません。"
283 "カレンダ : 検索"
284 "検索:"
285 "検索"
290 "検索するアポイント文字列を指定してください。"
291 "アポイントが見つかりません。"
292 "%d 個見つかりました。"
293 "日付:"
294 "検索"
297 "日付を入力してください。"
298 "すでに %s を表示中です。"
299 "日付が無効です。"
300 "作成者"
304 "メール..."
305 "カレンダ : エラー - グループアポイント・エディタ"
306 "カレンダを選択し、[挿入] を選択しなおしてください。"
314 "カレンダ : グループアポイント・エディタ - 削除"
315 "カレンダを選択し、[削除] を選択しなおしてください。"
329 "カレンダ : グループアポイント・エディタ - 変更"
330 "カレンダを選択し、[変更] を選択しなおしてください。"
340 "カレンダ"
341 "アクセス"
342 "挿入"
343 "変更"
348 "アクセス権の挿入"
349 "カレンダ : グループアポイント・エディタ"
350 "選択エラーです。継続できません。\n"
352 "アプリケーション内でコンポーネントを選択しなければなりません。\n"
353 "指定なし"
354 "終日"
355 "callog ファイルを開けません。\n操作を取り消しました。カレンダ"
356 "ユーザ要求によって、操作を取り消しました。\nカレンダ"
357 "[日付] フィールドに無効な値があります。\n操作を取り消しました。カレンダ"
358 "[開始] フィールドに無効な値があります。\n操作を取り消しました。カレンダ"
359 "[終了] フィールドに無効な値があります。\n操作を取り消しました。カレンダ"
360 "[日付] に値を指定しなければなりません。\n操作を取り消しました。カレンダ"
361 "[開始] に値を指定しなければなりません。\n操作を取り消しました。カレンダ"
362 "[内容] に値を指定しなければなりません。\n操作を取り消しました。カレンダ"
363 "[周期] の値と [期間] の値が無効、あるいは一致しません。\n操作を取り消しました。カレンダ"
364 "カレンダ : エラー - エディタ"
367 "カレンダはすでに存在します。\n操作を取り消しました。カレンダ"
368 "カレンダはありません。\n操作を取り消しました。カレンダ"
370 "権限エラーです。アクセス権が拒否されました。\n操作を取り消しました。カレンダ"
378 "メモリ割り当てエラーです。メモリが足りません。\n操作を取り消しました。カレンダ"
383 "未知のエラーです。\n操作を取り消しました。カレンダ"
386 "アポイントには、開始時刻よりも早い終了時刻を指定しています。\n終了時刻を翌日にスケジュールしますか?"
389 "翌日"
390 "プライバシ:"
391 "ユーザカレンダの場所:"
392 "活動時間帯:"
393 "開始:"
394 "終了:"
395 "時刻表示:"
396 "12 時間型"
397 "24 時間型"
398 "デフォルトの表示:"
399 "年"
400 "月"
401 "週"
402 "日"
403 "起動時のカレンダ表示:"
405 "最低 1 種類のアクセス権を選択してください。"
408 "最初に名前を選択してください。"
410 "ユーザ名:"
411 "名前の追加"
412 "アクセス権"
413 "アクセス権"
414 "名前の削除"
415 "B = ブラウズ I = 挿入 D = 削除"
416 "アクセス権:"
417 "ブラウズ"
419 "削除"
420 "出力先:"
421 "プリンタ"
422 "ファイル"
423 "プリンタ:"
424 "ディレクトリ:"
425 "オプション:"
426 "ファイル:"
427 "幅:"
428 "高さ:"
429 "位置:"
430 "左余白(インチ)"
431 "下余白(インチ)"
432 "ユニット:"
433 "印刷部数:"
434 "取込み:"
435 "アポイント時間と内容を開示"
436 "アポイント時間のみ開示"
437 "アポイントを開示しない"
438 "表示順序:"
439 "月 | 日 | 年"
440 "日 | 月 | 年"
441 "年 | 月 | 日"
442 "区切り記号:"
443 "ブランク"
445 "~/.desksetdefaults への書き込みでエラーが発生しました。\nこのファイルへの書き込み権を持っているか確認してください。"
448 "~/.desksetdefaults の読み込み中にエラーが発生しました。\nこのファイルの読み取り権を持っているか確認してください。"
450 "カレンダ : オプション - ヘルプ"
451 "まだ保存していない変更内容があります。\n変更内容を保存するか、変更を破棄するか、\nダイアログ内の以前の場所に戻ることができます。"
452 "保存"
454 "カレンダ : エラー - オプション"
458 "カレンダ : オプション"
459 "カテゴリ:"
460 "適用"
464 "ps_open_file(): ディレクトリまたはファイルを指定する必要があります。\n"
465 "ps_open_file(): ディレクトリ %s が無効です。\n"
466 "w+"
467 "ps_open_file(): ファイル %s を開けません。\n"
468 "ページ"
469 "カレンダ・マネージャの日表示"
470 "午前"
471 "午後"
473 "カレンダ・マネージャの予定表"
474 "カレンダ・マネージャのアポイントリスト"
475 "ページ"
476 "/"
477 "カレンダ・マネージャの月表示"
479 "ページ"
480 "日曜"
481 "月曜"
482 "火曜"
483 "水曜"
484 "木曜"
485 "金曜"
486 "土曜"
487 "ps_init_printer(): PostScript prolog ファイル %s を開けません。\n"
489 "   ページ"
490 "カレンダ・マネージャの週表示"
491 "月"
492 "火"
493 "水"
494 "木"
495 "金"
496 "土"
497 "日"
505 "土曜"
506 "日曜"
507 "カレンダ・マネージャの年表示"
523 "予定表: %d 年"
524 "アポイントリスト: %d 年"
525 "予定表: %s"
526 "アポイントリスト: %s"
527 "予定表: %s 週"
528 "アポイントリスト: %s 週"
529 "予定表: %s"
530 "アポイントリスト: %s"
531 "毎 %d %s"
532 "カレンダ : 周期"
533 "周期毎:"
534 "周期:"
535 "期間:"
536 "プライバシ:"
537 "カレンダ : エディタ - アポイントをスケジュール"
538 "このアポイントを月の最終週にスケジュールしますか、\nそれとも第 4 週にスケジュールしますか?"
540 "最終週"
541 "第 4 週"
542 "毎 %d %s"
543 "毎 %d %s"
544 "毎 %d %s"
559 "%s をブラウズ中..."
560 "カレンダ : 他の人のカレンダを表示"
562 "表示"
565 "作成者"
566 "カレンダ : エラー - 予定表エディタ"
567 "予定を選択し、[削除] を選択しなおしてください。"
570 "予定の選択で内部エラーが発生しました。\n予定を削除しません。"
573 "この予定は周期的な予定の 1 つです。\n本当に削除しますか...?"
579 "この予定は周期的な予定の 1 つです。\n本当に変更しますか...?"
585 "予定を選択し、[変更] を選択しなおしてください。"
590 "期限:"
591 "カレンダ : 予定表エディタ"
596 "月曜日 %d"
597 "火曜日 %d"
598 "水曜日 %d"
599 "木曜日 %d"
600 "金曜日 %d"
601 "土曜日 %d"
602 "日曜日 %d"
603 "[ユーザ名] フィールドに追加する名前を入力してください。"
604 "すでにリストにあります。"
607 "カレンダ名の登録で内部エラーが発生しました。"
610 "カレンダ名の検索で内部エラーが発生しました。"
612 "概要(O)..."
613 "カレンダについて(A)..."
619 "次の書式で、カレンダ名を入力してください: <ユーザ>@<ホスト名>"
620 "未知のカレンダです。カレンダ名が必要です: <名前>%s"
622 "未知のカレンダです。ホスト名が必要です: %s@<ホスト名>"
623 "カレンダは 1970 年 1 月 1 日より前の日付は表示しません。"
624 "カレンダは 2037 年 12 月 31 日より後の日付は表示しません。"
625 "追加設定の非表示"
626 "追加設定の表示"
627 "アポイントのドラッグ"
628 "時間内容"
631 "%d 個見つかりました。"
632 "表示するアポイントをリストから選択してください。"
633 "個のカレンダを選択しました。"
634 "個のカレンダを選択しました。"
641 "サーバが指定した位置でのネットワーク・アドレスの取得に失敗しました:\nホスト名が無効です。"
642 "rpc.cmsd デーモンは登録されていません。\nシステムに rpc.cmsd が正しくインストールされているか確認してください。"
643 "カレンダにアクセスできません。カレンダ"
644 "アポイント時間:"
645 "所要時間:"
646 "分間"
647 "%s を検索中..."
648 "SunDex"
649 "カレンダ : タイムゾーン"
650 "システムのタイムゾーン"
652 "タイムゾーンの変更"
653 "GMT"
654 "時間"
655 "了解"
659 "タイムゾーン:"
671 "バージョン"
672 "リビジョン"
674 "Copyright (c) 1993, 1994, 1995:"
675 "Hewlett-Packard Company"
676 "International Business Machines Corp."
677 "Novell, Inc."
678 "Sun Microsystems, Inc."
679 "追加設定の表示..."
680 "閉じる"
681 "カレンダ寄稿者"
682 "このアプリケーションの提供者は次の通りです:"
684 "ユーザ名にブランクまたはタブを含むことはできません。"
686 "名前の追加"
687 "名前の削除"
688 "ブラウズメニュー項目"
691 "リセット"
696 "使用方法:\n\\tdtcm_admin [ -d ] [ -a アクション ] [ -c カレンダ ] [ -s <月/日/年> ] [ -e <月/日/年> ] [-f ファイル名]\n"
697 "サポートされていない管理操作 \"%s\" を指定しました。\n"
698 "\n出力ファイル \"%s\" を開けません。\n"
699 "\n入力ファイル \"%s\" を開けません。\n"
700 "破棄"
703 "コンテキスト"
704 "%d 年"
705 "%s"
706 "%s の週"
707 "%s"
708 "このアポイントは、未知の周期で反復しています。すべての登録が変更されます。\n変更してもいいですか?"
711 "このアポイントは、未知の周期で反復しています。すべての登録が削除されます。\n削除してもいいですか?"
713 "必ず終了日より前に開始日を選択してください。"
714 "リストにアポイントはありません。必ずアポイントを表示する前に検索してください。"
715 "カレンダー : 日付で検索"
721 "時間と内容を参照可"
722 "時間のみ参照可"
723 "参照不可"
724 "[指定なし] アポイントは、[内容] に値を指定しなければなりません。\n操作を取り消しました。カレンダ"
725 "カレンダのエントリが存在しません。\n操作を取り消しました。カレンダ"
727 "要求がタイムアウトしました。\nご使用のシステム上に rpc.cmsd が正しくインストールされているか確認してください。"
728 "カレンダ : 印刷"
729 "プリンタ名:"
730 "印刷部数:"
731 "開始:"
732 "終了:"
733 "印刷コマンド・オプション:"
734 "ファイルに出力:"
735 "印刷"
736 "カレンダー : エラー - 印刷"
738 "アクセスリスト:"
739 "アクセス権:"
740 "追加"
743 "公用:"
744 "半私用:"
745 "私用:"
749 "アクセスリストに項目を追加するには、名前とアクセス権を設定しなければなりません。"
750 "カレンダ : エラー - アクセスリストとアクセス権"
751 "このエントリは、すでにアクセスリストに存在します。変更しますか?"
756 "アクセスリストの項目を変更するには、名前とアクセス権を設定しなければな~りません。"
758 "真夜中"
759 "値"
760 "値"
762 "エディタのデフォルト"
763 "表示形式の設定"
764 "アクセスリストとアクセス権"
765 "プリンタ設定"
766 "日付の形式"
772 "[ユーザカレンダの場所] に、ブランクまたはブランクを含む値を\n保存できません。\n属性設定は保存されません。"
773 "[起動時のカレンダ表示] に、ブランクまたはブランクを含む値を\n保存できません。\n属性設定は保存されません。"
774 "ps_open_file(): ファイルに出力するには、ファイル名が必要です。\n"
775 "通知予約を指定しなければなりません。\n操作を取り消しました。カレンダ"
776 "通知予約に、ブランクを含むことはできません。\n操作を取り消しました。カレンダ"
777 "予約の値はオプション符号付きの数字でなければなりません。\n操作を取り消しました。カレンダ"
778 "カレンダ : 予定表 - ヘルプ"
783 "保留"
784 "完了"
789 "予定の型:"
790 "コンテキスト"
791 "この予定は、未知の周期で反復しています。すべての登録が変更されます。\n\
削除してもいいですか?"
797 "予定"
798 "期限:"
802 "削除"
803 "消去"
806 "%d 年"
807 "%s"
808 "%s 週"
809 "%s"
810 "1/1/1970 以降の開始日を入力してください。"
811 "開始日の形式が不正です。"
812 "1/1/2038 より前の終了日を入力してください。"
813 "終了日の形式が不正です。"
814 "1969 年より後で 2038 年より前の日付を入力しなければなりません。"
816 "日数"
817 "週数"
818 "月数"
819 "[所要時間] の値は、符号なしの整数でなければなりません。\n属性設定は保存されません。"
820 "開始値は、有効な時間でなければなりません。\n属性設定は保存されません。"
821 "右マージン値で不正な位置を指定しました。\n属性設定は保存されません。"
822 "下マージン値で不正な位置を指定しました。\n属性設定は保存されません。"
825 "日数"
826 "週数"
827 "月数"
828 "日付"
829 "開始:"
830 "午前"
831 "午後"
832 "終了:"
833 "午前"
834 "午後"
835 "内容:"
836 "繰返し"
837 "カレンダ : エラー - 予定表エディタ"
839 "カレンダ : 通知"
841 "名前を追加するには、\"名前の追加\" をクリックします。変更内容を確認するには、\"適用\" をクリックします。"
$ 		/* NL_COMMENT
$ 		   Attention Translator:
$ 
$ 		   Message 841 is used in the Menu Editor's footer.  The
$ 		   Menu Editor is accessed through the browse menu.  The 
$ 		   message is displayed when something is typed into the User
$ 		   Name field in the editor.  If the translated footer message 
$ 		   is too long it causes the menu editor to grow horizontally
$ 		   which we do not want.  If you notice that the translated
$ 		   string causes the editor to grow horizontally please
$ 		   insert a newline (\n) character somewhere in the middle
$ 		   of the string so the footer will use two lines and the
$ 		   editor will grow vertically.
$ 		*/
842 "転送された情報に\nアポイントは含まれていません。"
843 "ドラッグ＆ドロップ操作が失敗しました。"
844 "転送された情報を検出できません。"
845 "ドラッグ＆ドロップ操作が失敗しました。\n内部整合性のエラーが発生しました。"
846 "保存"
848 "日付"
849 "時間"
850 "内容"
851 "アポイントを表示"
852 "一回"
853 "毎日"
854 "毎週"
855 "隔週"
856 "毎月(日付による)"
857 "毎月(曜日による)"
858 "毎年"
859 "月曜日から金曜日"
860 "月曜、水曜、金曜"
861 "火曜、木曜"
862 "周期毎..."
863 "2"
864 "3"
865 "4"
866 "5"
867 "6"
868 "7"
869 "8"
870 "9"
871 "10"
872 "11"
873 "12"
874 "13"
875 "14"
876 "永久"
877 "分前"
878 "時間前"
879 "日前"
881 "内部エラー #1: カレンダ／エントリ・ハンドルが無効です。\n操作を取り消しました。カレンダ"
882 "内部エラー #2: セッション・ハンドルが無効です。\n操作を取り消しました。カレンダ"
883 "内部エラー #3: データ値が無効です。\n操作を取り消しました。カレンダ"
884 "内部エラー #4: 読み専用属性に値を指定しています。\n操作を取り消しました。カレンダ"
885 "内部エラー #5: 属性値に不正なデータ型を指定しています。\n操作を取り消しました。カレンダ"
886 "内部エラー #6: カレンダのこのバージョンは、指定の属性をサポートしていません。\n操作を取り消しました。カレンダ"
887 "内部エラー #7: カレンダのこのバージョンは、指定の機能をサポートしていません。\n操作を取り消しました。カレンダ"
888 "内部エラー #8: 指定の演算子が無効です。\n操作を取り消しました。カレンダ"
890 "カレンダ : エラー - サービス"
892 "印刷する日付は 1969 年より後で 2038 年より前でなければなりません。"
894 "\"開始\" の日付の形式が不正です。"
896 "\"終了\" の日付の形式が不正です。"
898 "印刷する \"終了\" の日付は、\"開始\" の日付よりも後でなければなりません。"
899 "予定リストの開始: %s"
900 "アポイントリストの開始: %s"
901 "周期毎 ..."
902 "月曜日から金曜日"
903 "月曜、水曜、金曜"
906 "予定のドラッグ"
907 "カレンダ・ファイルに空き領域がありません。\n操作を取り消しました。カレンダ"
908 "通知の値としてブランクを設定することはできません。\n属性設定は保存されません。"
909 "通知の値にブランクを含めて設定することはできません。\n属性設定は保存されません。"
910 "通知の値は、オプション符号付きの数字でなければなりません。\n属性設定は保存されません。"
$ 911	"You have specified an illegal position from left offset value.\nYour properties settings have not been saved."
$ "position from left offset" has been changed to "left margin".
911 "左マージン値で不正な位置を指定しました。\n属性設定は保存されません。"
$ 912	"You have specified an illegal position from right offset value.\nYour properties settings have not been saved."
$ "position from right offset" has been changed to "top margin".
912 "上マージン値で不正な位置を指定しました。\n属性設定は保存されません。"
913 "予定項目には、内容項目の一行目にあるテキストがなければなりません。"
914 "カレンダ : エラー - エディタ"
916 "所要時間の値は、24 時間未満でなければなりません。\n属性設定は保存されません。"
917 "紛失\nグラフィック"
918 "紛失\nグラフィック"
919 "カレンダ"
920 "を表示しました。"
921 "カレンダにアクセスできません: "
922 "カレンダについて"
923 "取消し"
963 "カレンダ : メニュー・エディタ"
964 "アイテムヘルプ(I)"
965 "予定表(T)..."
966 "予定(T)..."
967 "カレンダ・サーバのバージョン"
968 "カレンダ・データのバージョン"
969 "カレンダ : エラー - 周期毎"
970 "[周期毎] の値は符号なしの整数でなければなりません。"
971 "時間カレンダ"
972 "内容"
973 "すべてを検索"
974 "検索開始"
975 "検索終了"
976 "レポート・タイプ:"
977 "日表示"
978 "週表示"
979 "月表示"
980 "年表示"
981 "アポイントリスト"
982 "予定表"
983 "ユーザ名"
984 "このアポイントは周期的アポイントの 1 つです。\n本当に挿入しますか...?"
985 "通知　　　　　"
986 "ビープ音"
987 "フラッシュ"
988 "ポップアップ"
989 "メール"
990 "メール宛先:"
992 "%Y年 %B %e日 %A"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993 "%Y年 %B %e日 %A から始まる週"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994 "日"
995 "週"
996 "隔週"
997 "月"
998 "年"
1002 "カレンダ寄稿者:"
1003 "このアポイントは他のユーザが所有するカレンダにあります。\n本当に変更しますか？"
1004 "このアポイントは他のユーザが所有するカレンダにあります。\n本当に削除しますか？"
1005 "削除"
1006 "変更"
1007 "アポイント選択で内部エラーが発生しました。\nアポイントは変更されません。"
1008 "カレンダ・アポイント : ヘルプ"
1009 "予定選択で内部エラーが発生しました。\n予定は変更されません。"
1010 "カレンダ : カレンダの比較"
1011 "\"期限\" フィールドに無効な値があります。\n操作を取り消しました。カレンダ"
1012 "カレンダ : 予定リスト"
1041 " %2d へ:%02d%s"
1042 "挿入アクセスが拒否されました: "
1043 "削除アクセスが拒否されました: "
1044 "検索アクセスが拒否されました: "
1045 "取り消されました。"
1046 "個のアポイントを取り消しました。\n"
1047 "このアポイント: '%s' の終了時間は\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048 "このアポイントの終了時間は\n"
1049 "開始時間より遅くなっています。"
1050 "次の日のスケジュールにしますか？ [Y/N]"
1051 "アポイント '%s' は周期的アポイントの 1 つです。"
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052 "次のいずれかを実行できます:"
1053 "\n\t1.  すべてを削除"
1054 "\n\t2.  このアポイントのみ削除"
1055 "\n\t3.  これ以降削除"
1056 "\n\t4.  取消し"
1057 "\n\tオプション [1-4]: "
1058 "指定の [日付] は無効です。\n"
1059 "指定の [開始] 時刻は無効です。\n"
1060 "指定の [終了] 時刻は無効です。\n"
1061 "[日付] フィールドが空か、ありません。\n"
1062 "[開始] フィールドが空か、ありません。\n"
1063 "[内容] フィールドが空か、ありません。\n"
1064 "[周期] フィールドと [期間] フィールドが一致しません。\n"
1065 "挿入したアポイントを取り消しました。\n"
1066 "アポイントは挿入されません。"
1067 "指定の [日付] は無効です:"
1068 "アポイントがあります。"
1069 "アポイントはありません。"
1070 "カレンダ : エラー - カレンダの比較"
1072 "カレンダ : エラー - ブラウズ"
1073 "カレンダ : エラー - ドラッグ＆ドロップ"
1074 "カレンダ・アポイント"
1075 "カレンダ : エラー - アポイントの変更"
1076 "カレンダ : ヘルプ"
1078 "カレンダ : アクセス・リストと許可 - 追加"
1079 "カレンダ : エラー - エディタの設定"
1083 "カレンダ : エラー - 表示の設定"
1085 "カレンダ : エラー - プリンタの設定"
1086 "カレンダ : アポイントリスト"
1087 "%1$2d:%2$02d%3$s から %4$2d:%5$02d%6$s まで"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088 "%1$2d:%2$02d%3$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089 "%1$02d%2$02d から %3$02d%4$02d まで"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090 "%1$02d%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091 "%Y年 %B"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092 "%Y年"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/
1100 "\n\n\t** カレンダー予定項目 **\n\n\t期日:\t%s\t期限:\t%s\t内容:\t\t%s"
1101 "アポイントの挿入"
1102 "予定の挿入"
1103 "この予定は周期的な予定の 1 つです。\n本当に項目を挿入しますか...?"
1104 "[期限] フィールドに無効な値があります。\n操作を取り消しました。カレンダ"
1105 "[期限] に値を指定しなければなりません。\n操作を取り消しました。カレンダ"
$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"日付"
1107	"ユーザId"
1108	"ページ番号"
1109	"レポートタイプ"
1110	"なし"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"カレンダー : エラー - 印刷設定"
1112	"印刷・ダイアログ・マネージャ(PDM) エラー - 設定失敗."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113 "指定されたプリンタまたはプリント・サーバは無効です。"
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114 "カレンダー : エラー - ファイルに出力"
1115 "エラー - ファイルに出力できません。"
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116 "カレンダー : ファイルに出力"
1117 "正常にファイルに出力しました。"
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118 "カレンダー : 警告 - 印刷"
1119 "警告 - フォント %s を読み込むことができません。"

$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled.
$ "NEW-"
1120	"The event cannot be scheduled in the given time frame.\nThe operation was cancelled."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
$ "NEW-"
1121	"Calendar : Print Server Error"
1122	"Print job failed.\n\nThe X Print Server is temporarily out of resources."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Calendar - Warning
$ "-NEW"
2 "Could not connect to ToolTalk:\n%s\n"
$ "-NEW"
3 OK
$ "-NEW"
4 "Calendar : Appointment Editor - Warning"
