$ 
$   COMPONENT_NAME: desktop
$ 
$   FUNCTIONS: none
$ 
$   ORIGINS: 27,118,119,120,121
$ 
$   This module contains IBM CONFIDENTIAL code. -- (IBM
$   Confidential Restricted when combined with the aggregated
$   modules for this product)
$   OBJECT CODE ONLY SOURCE MATERIALS
$ 
$   (C) COPYRIGHT International Business Machines Corp. 1995
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/41 1999/09/14 15:46:38 mgreess $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 
$		     Common Desktop Environment
$ 
$   (c) Copyright 1993, 1994, 1995 Hewlett-Packard Company
$   (c) Copyright 1993, 1994, 1995 International Business Machines Corp.
$   (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
$   (c) Copyright 1993, 1994, 1995 Novell, Inc.
$   (c) Copyright 1995 Digital Equipment Corp.
$   (c) Copyright 1995 Fujitsu Limited
$   (c) Copyright 1995 Hitachi, Ltd.
$                                                                   
$ 
$                     RESTRICTED RIGHTS LEGEND                              
$ 
$ Use, duplication, or disclosure by the U.S. Government is subject to
$ restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
$ Technical Data and Computer Software clause in DFARS 252.227-7013.  Rights
$ for non-DOD U.S. Government Departments and Agencies are as set forth in
$ FAR 52.227-19(c)(1,2).
$ 
$ Hewlett-Packard Company, 3000 Hanover Street, Palo Alto, CA 94304 U.S.A.
$ International Business Machines Corp., Route 100, Somers, NY 10589 U.S.A. 
$ Sun Microsystems, Inc., 2550 Garcia Avenue, Mountain View, CA 94043 U.S.A.
$ Novell, Inc., 190 River Road, Summit, NJ 07901 U.S.A.
$ Digital Equipment Corp., 111 Powdermill Road, Maynard, MA 01754, U.S.A.
$ Fujitsu Limited, 1015, Kamikodanaka Nakahara-Ku, Kawasaki 211, Japan
$ Hitachi, Ltd., 6, Kanda Surugadai 4-Chome, Chiyoda-ku, Tokyo 101, Japan

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "了解" 
$     /* NL_COMMENT
$      * This is a menu label, please refer to the resource file "Dtmail" for
$      * appropriate mnemonics tranlation
$      */
2 "メール・オプション(P)..."
3 "不在返信"
4 "属性の更新中..."


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "取消し"
6 "メール・プログラム"
7 "メール・プログラム"
8 "メール・プログラム"
9 "削除"
10 "次を表示"
11 "前を表示"
12 "発信者に返信(R)"
13 "印刷"
14 "発信者"
15 "主題"
16 "日付と時刻"
17 "サイズ"
$ 	/* NL_COMMENT
$        * Menu labels in Main Mailer (from RoamMenuWindow.C).
$        * The following menu labels require translation plus parenthesized 
$        * mnemonics for all Asian locales. Please refer to the resource file 
$        * "Dtmail" for each mnemonics.
$ 	 * Message 18-22,25,28,29 are menu labels for "Mailbox" pull down menu.
$        * Message 30,31,33-40 are menu labels for "Message" pull down menu. 
$        * Message 43-45 are menu labels for "Edit" pull down menu. 
$        * Message 47--55 are menu labels for "View" pull down menu. 
$        * Message 56-63 are menu labels for "Compose" pull down menu. 
$        * Message 64,65,221 are menu labels for "Move" pull down menu. 
$        * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$        * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	 */
18 "メールボックス(x)"
19 "新規メールをチェック(M)"
20 "受信箱を開く(I)"
21 "受信箱を開く(I)"
22 "新規(N)..."
23 "メール・プログラム - 新規"
24 "新規"
25 "開く(O)..."
26 "メール・プログラム - 開く"
27 "開く"
28 "削除したメッセージの破棄(D)"
29 "閉じる(C)"
30 "開く(O)"
31 "テキストとして保存(A)..."
32 "メール・プログラム - メッセージ - テキストとして保存"
33 "コピー先"
34 "印刷(P)..."
35 "検索(F)..."
36 "すべてを選択(S)"
37 "削除(D)"
38 "最後の削除の取消し"
39 "リストからの削除の取消し(U)..."
40 "メッセージ(M)"
41 "移動"
42 "メール・プログラム - メッセージ"
43 "コピー(C)"
44 "すべてを選択(S)"
45 "編集(E)"
46 "メール・プログラム - テキスト"
47 "次を表示(N)"
48 "前を表示(P)"
49 "略記ヘッダ(A)"
50 "日付／時刻でソート(D)"
51 "発信者でソート(S)"
52 "主題でソート(b)"
53 "サイズでソート(z)"
54 "ステータスでソート(t)"
55 "表示(V)"
56 "新規メッセージ(M)"
57 "新規、すべての内容を取り込む(N)"
58 "転送(F)"
59 "発信者に返信(R)"
60 "全員に返信(A)"
61 "発信者に返信(内容取込み)(S)"
62 "全員に返信(内容取込み)(I)"
63 "メール作成(P)"
64 "移動(o)"
65 "他のメールボックス(o)..."
66 "別名保存(A)..."
67 "メール・プログラム - アタッチメント - 別名保存"
68 "すべてを選択(S)"
69 "アタッチメント(A)"
70 "メール・プログラム - アタッチメント"
71 "概要(v)"
72 "使い方(T)"
73 "リファレンス(R)"
74 "アイテムヘルプ(O)"
75 "ヘルプの使い方(U)"
76 "ヘルプ(H)"
77 "メール・プログラムについて(A)..."
78 "このメールボックスの状態に関してメール・プログラムが混乱しています。\n\
[了解] を選択してメールボックスを閉じ、その後メール・プログラムを\n\
起動しなおしてください。"
79 "変換中... %d パーセント完了"
80 "メール・プログラム"

$ 
$ Strings from dtmail/AttachArea.C

81 "メール・プログラム"
82 "メール・プログラム"
83 "メール・プログラム"


$ 
$ Strings from dtmail/Attachment.C

84 "%s は、実行可能なアタッチメントです。このアタッチメントを実行しますか?"
85 "メール・プログラム"
86 "メール・プログラム"
87 "メール・プログラム"
88 "メール・プログラム"


$ 
$ Strings from dtmail/RoamCmds.C

89 "メール・プログラム - 他のメールボックス"
90 "移動"
91 "印刷中..."
92 "了解"
93 "保存"
94 "保存"
95 "保存"
96 "空にする"
97 "名前の変更"
98 "メール・プログラム - 名前の変更"
99 "メール・プログラム - 閉じる"
100 "了解"
101 "取消し"
102 "すでに不在返信以外の転送機能を使用しています。\n\
不在返信の実行中は、不在返信はこの他の転送動作に追加されます。\n\
不在返信を起動してもいいですか?"
103 "メール・プログラム"
104 "すでに .forward ファイルで不在返信プログラムを実行しています。\n\
不在返信プログラムを中止する方法をマニュアルで調べて、\n\
プログラムを .forward ファイルから削除してください。\n\
その後で、このコマンドを実行してください。"
105 ".vacation.msg ファイルを開けません。 -- 書き込み権がありません。"
106 ".vacation.msg ファイルが存在します。新規テキストに置き換えますか?"
107 ".vacation.msg ファイルを開けません。 -- 書き込み権がありません。"
108 "休暇中です。"
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "休暇中です。\n\"$SUBJECT\" についてのあなたのメールは、休暇終了後に読みます。\n"


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N" 


$ 
$ Strings from dtmail/Undelete.C

115 "削除の取消し"
116 "閉じる"

$ 
$ Strings from dtmail/SendMsgDialog.C

$ 	    /* NL_COMMENT
$            * Menu labels in Compose dialog (from SendMsgDialog.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 117,121,122,125,127-129 are menu labels for "File" pull down menu.
$            * Message 130-134,139,140,155,156 are menu labels for "Edit" pull down menu. 
$            * Message 141,142,145,147-150,226 are menu labels for "Attachment" pull down menu. 
$            * Message 152-154,157 are menu labels for "Format" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
117 "送信"
118 "閉じる"
119 "新規メッセージ"
120 "メール・プログラム"
121 "ファイル(F)"
122 "取込み(I)..."
123 "メール・プログラム - 取込み"
124 "取込み"
125 "テキストとして保存(A)..."
126 "メール・プログラム - テキストとして保存"
127 "メッセージのログ採取(L)"
128 "別の形式で送信"
129 "閉じる(C)"
130 "編集(E)"
131 "元に戻す(U)"
132 "カット(t)"
133 "コピー(C)"
134 "ペースト(P)"
135 "マーク付きをペースト"
136 "括弧"
137 "インデント"
138 "消去"
139 "削除(D)"
140 "すべてを選択(S)"
141 "アタッチメント(A)"
142 "ファイルの追加(F)..."
143 "メール・プログラム - 追加"
144 "追加"
145 "別名保存(A)..."
146 "メール・プログラム - アタッチメント - 別名保存"
147 "削除(D)"
148 "削除の取消し(U)"
149 "名前の変更(R)"
150 "すべてを選択(S)"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "区画を表示"
152 "書式(r)"
153 "折返し(W)"
154 "設定(S)..."
155 "検索／変更(F)..."
156 "スペルチェック(k)..."
157 "テンプレート(T)"
158 "メール・プログラム - アタッチメント"
159 "メール・プログラム - メール作成"
160 "新規メッセージ"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "コピー(C)"
162 "すべてを選択(S)"
163 "編集(E)"
164 "別名保存(A)..."
165 "メール・プログラム - アタッチメント - 別名保存"
166 "すべてを選択(S)"
167 "アタッチメント(A)"
168 "メール・プログラム - アタッチメント"
169 "メール・プログラム - テキスト"
170 "概要(v)"
171 "使い方(T)"
172 "リファレンス(R)"
173 "アイテムヘルプ(O)"
174 "ヘルプの使い方(U)"
175 "ヘルプ(H)"
176 "メール・プログラムについて(A)..."
177 "メール・プログラム"


$ 
$ Strings from dtmail/DtMailGenDialog.C

$  /* NL_COMMENT
$   * 178 and 179 are obsolete messages, replaced by messages
178 "メール・プログラム - メール・プログラムについて"
179 "メール・プログラム・バージョン 1.0"
180 "了解"
181 "了解"
182 "取消し"

$ 
$ Strings from dtmail/FindDialog.C

183 "検索"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "検索 & すべてを選択"
185 "消去"
186 "閉じる"
187 "ヘルプ"
188 "To:"
189 "From:"
190 "Subject:"
191 "Cc:"
192 "メール・プログラム - 検索"
193 "前方検索"
194 "後方検索"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */



$ 
$ Strings from dtmail/Editor.C

195 "------------- 転送メッセージ  ここから -------------\n\n"
196 "------------- 取込みメッセージ  ここから -------------\n\n"
197 "------------- 転送メッセージ  ここまで -------------\n\n"
198 "------------- 取込みメッセージ  ここまで -------------\n\n"

$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n------------- 取込みメッセージ  ここから -------------\n"
200 "\n------------- 取込みメッセージ  ここまで -------------\n"

$ 
$ Strings from dtmail/DtEditor.C

201 "\n------------- 取込みメッセージ  ここから -------------\n"
202 "\n------------- 取込みメッセージ  ここまで -------------\n"

$ 
$ Strings from dtmail/ComposeCmds.C

203 "メール・プログラム"
204 "メール作成ウィンドウを作成できません。"
205 "メール・プログラム"
206 "メール作成ウィンドウを作成できません。"
207 "メール・プログラム"
208 "メール作成ウィンドウを作成できません。"
209 "メール・プログラム"
210 "メール作成ウィンドウを作成できません。"
211 "メール・プログラム"
212 "テンプレートが存在しません。"
213 "メール・プログラム"
214 "テンプレートが壊れているようです。"
215 "メール・プログラム"
216 "テンプレートを読み込むのに十分なメモリがありません。"
217 "メール・プログラム"
218 "テンプレートが壊れているようです。"

$ 
$ Strings from dtmail/SortCmd.C

219 "ソート中..."

220 "すべてを選択"
221 "受信箱"

222 "%b %d日 %a %k:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%b %d日 %a %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%b %d日 %a %k:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%b %d日 %a %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "リストを表示(L)"

$ String from Undelete.C, Deleted Messages window title
227 "メール・プログラム - 削除したメッセージ"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "追加"
229 "削除"
230 "送信"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "検索中..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "1 個のメッセージを選択しました。"
233 "%d 個のメッセージを選択しました。"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "一致するものが見つかりません。"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "メール・プログラム - メール・プログラムについて"
236 "メール・プログラム・バージョン %d.%d.%d"
$  /* NL_COMMENT
$   * String 237 is the Copy button on Move Other Mailboxes dialog (from RoamCmds.C)
$   */
237 "コピー"


$ 
$ DTMC_BADSTATE
$ The mailbox is in a state which cannot be deciphered by the Mailer, i.e.
$ portions of the file have been deleted by another process (the Mailer
$ only knows how to handle other processes adding to the end of the mailbox.
$ 
$ "-NEW"
238 "Mailer is confused about the state of this mailbox.\nIt may be that another process has rewritten this mailbox in an unexpected way.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost."

$ 
$ DTMC_ACCESSFAILED
$ The Mailer cannot perform routine file operations on the mailbox file,
$ a.k.a. stat, fstat, write, ...
$ 
$ "-NEW"
239 "Mailer can no longer access this mailbox.\nIt may be that another process has deleted the mailbox file.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ DTMC_INODECHANGED
$ The mailbox has been rewritten by another process.
$ 
$ "-NEW"
240 "Mailer can no longer access this mailbox.\nAnother process has rewritten the mailbox file changing the inode.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ Messages 241-244 are header field labels for SendMsgDialog.
$ 
$ "-NEW"
241 "To"
$ "-NEW"
242 "Subject"
$ "-NEW"
243 "Cc"
$ "-NEW"
244 "Bcc"

$ 
$ Message 245 is the label for the Open command in the File menu
$ Message 246 is the label for the command in the OpenContainer menu
$	which opens Mailboxes not in the users folder list.
$ 
$ "-NEW"
245 "開く"
$ "-NEW"
246 "他のメールボックス..."

$ 
$ Message 247 is the label for the command in the Aliases menu
$	which opens the MailOptions dialog allowing the user to create
$	other aliases.
$ Message 248 is the label for the Aliases popup menu
$ 
$ "-NEW"
247 "Other Aliases..."
$ "-NEW"
248 "Mailer - Aliases"

$ 
$ Messages 249-255 are strings used to generate attachment summaries
$                  in included messages.
$ 
$ "-NEW"
249 "------------- Begin Included Attachment -------------\n\n" 
$ "-NEW"
250 "------------- End Included Attachment -------------\n\n" 
$ "-NEW"
251 "       Attachment Name:  "
$ "-NEW"
252 "     Attachment DtType:  "
$ "-NEW"
253 "Attachment ContentType:  "
$ "-NEW"
254 "Attachment Description:  "
$ "-NEW"
255 "------------------ Attachments ------------------\n" 

$ "-NEW"
$ DTMC_SERVERACCESSFAILED:
$ Mailer failed in attempt to retrieve messages from the mail server
256 "Mail server access failed:\n%s"

$ "-NEW"
$ Label on the button which causes the "Mail Retrieval" options to be displayed
257 "Options..."

$ "-NEW"
$ DTMC_GETMAILCOMMANDFAILED:
$ Mailer failed in attempt to retrieve messages via custom getmail command
258 "User Getmail command failed:\n%s"

$ "-NEW"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
259 "%Y %a %d %b"
260 "%a %d %b %k:%M"
261 "%a %d %b %H:%M"


$ "-NEW"
262 "Dead Letter Message"

$ "-NEW"
263 "The attachment '%s' is %d kilobytes.\nAdd as attachment?"





$set 2
1 "メール・プログラム"
2 "ToolTalk が初期化されていません。ToolTalk を使用しないとメール・プログラムを実行できません。\n/usr/dt/bin/dtsession を起動するか、システム管理者に問い合わせてください。"

3 "ウィンドウを初期化できません。終了します。\n"
4 "メール・プログラムが適切にインストールされていません。\n\
実行グループの設定が間違っているので、実行できません。"
5 "ユーザは %s を表示するアクセス権がありません。"
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "メールボックス %s はディレクトリなので開けません。"
7 "%s を空にできません。存在しません。"
8 "コンテナ %s を空にしました。"
9 "エラー - %s を空にできません。"
10 "メール・プログラム"
11 "%s"
12 "メール・プログラム"
13 "メール・プログラム"
14 "\"別名保存\" コマンドを発行してファイルを保存する前に、\n\
アタッチメントを選択する必要があります。"

15 "エラー - mailrc を取得できません。"
16 "メッセージを選択していません。"
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */


17 "\"%s\" は編集されています。削除してもいいですか?"
18 "エラー: ファイル %s を取り込めません。"
19 "\"別名保存\" コマンドを発行してファイルを保存する前に、\n\
アタッチメントを選択する必要があります。"


20 "\"別名保存\" コマンドを発行してファイルを保存する前に、\n\
アタッチメントを選択する必要があります。"

21 "メール・プログラム"
22 "~/.mailrcのファイルに回復することができない構文のエラーを見つけました。\n\
ターミナル上のメッセージを調べて下さい。\n\
エラーを確認し、dtmailを再起動してください。\n\
もし継続を選ぶならば、ファイルするためのオプションダイアログでの変更の幾らかは\n\
保存できません。"
23 "継続"
24 "終了"
25 "~/.mailrcのファイルに回復することができない構文のエラーを見つけました。\n\
メール・オプションの環境は現在のセッションでは適用されますが、\n\
ファイルに保存はされません。"

$ 
$ Messages for file locking dialog displayed from the Advanced option pane.
$ 
$ "-NEW"
26 "The value of the file locking option has changed.\nTo take immediate effect, folders need to be closed and reopened.\n  o Click on 'Reopen' to reopen folders,\n    making the new option take effect immediately.\n  o Click on 'Continue' to avoid reopening folders.\n    The new option will take effect the next time you open a folder.\n  o Click on 'Cancel' to cancel the Apply and return to editing options."
$ "-NEW"
27 "Reopen"
$ "-NEW"
28 "Continue"
$ "-NEW"
29 "Cancel"

$ 
$ Messages for ToolTalk errors.
$ 
$ "-NEW"
30 "%s returned ToolTalk error: %s\n"

$set 3
1 "自動保存中..."

2 "初期化中..."
3 "メールボックス %s は存在しません。\n\
この名前でメールボックスを作成しますか?"
4 "メール・プログラム"
5 "了解"
6 "メールボックス %s はロックされています。\n\
手動でメールボックスをロック解除し再試行するか、\n\
システム管理者に問い合わせてください。"
7 "メール・プログラム"
8 "了解"
9 "了解"
10 "了解"
11 "了解"
12 "%s"
13 "メッセージ %2$d の %1$d、新規 %3$d、削除 %4$d"
14 "メッセージ %2$d の %1$d、新規 %3$d、削除 %4$d"
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "保存中..."
16 "メール・プログラム"
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
$		/* NL_COMMENT
$		 * Messages 16 and 17 are no longer being used.  They are
$		 * being replaced by messages 86 and 87.
$		 */
17 "このメールボックスで削除マークを付けたメッセージを\n\
破棄していいですか?"
18 "了解"
19 "取消し"
20 "メールボックスを開いています..."
21 "%s はすでに存在します。\n\
上書きしますか?"
22 "メール・プログラム"
23 "%s を上書きできません。\nファイルのアクセス権を確認して再試行してください。"
24 "メール・プログラム"
25 "コンテナを読み込み中..."
26 "フォルダの概要情報"
27 "読み込み中..."
28 "空のコンテナ"
29 "了解"
30 "了解"
31 "了解"
32 "削除したメッセージを破棄中..."
33 "了解"

34 "%s は存在しません。"
35 "%s を開けません。"
36 "メモリを割り当てることができません。"
37 "アタッチメントの概要"
38 "個のアタッチメント"
39 "個のアタッチメント"
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "個のアタッチメント"
41 "個、削除しました。"

42 "%s はすでに存在します。置換しますか?"
43 "%s を置換できません。"
44 "%s を作成できません。"
45 "%s を作成できません。"


46 "空のコンテナ"
47 "%s はすでに存在します。\n上書きしますか?"
48 "メール・プログラム"
49 "%s を上書きできません。\n\
ファイルのアクセス権を確認して、再試行してください。"
50 "メール・プログラム"
51 "%s を作成できません。"
52 "メール・プログラム"
53 "%s に書き込めません。"
54 "メール・プログラム"
55 "%s を作成できません。"
56 "メール・プログラム"
57 "アタッチメント名を次の名前に変更します。"
58 "メール作成ウィンドウには、ウィンドウを閉じるとなくなる\n\
テキストまたはアタッチメントがあります。\n\
メール作成ウィンドウを閉じますか?"
59 "メモリがありません。"
60 "既存の .vacation.msg ファイルを読み込むのに十分なメモリがありません。"
61 "メール・プログラム"
62 "既存の .vacation.msg ファイルは壊れているようです。"


63 "移動するメッセージを選択してください。"
64 "コピーするメッセージを選択してください。"
65 "%d 個のメッセージを %s に移動しました。"
66 "%d 個のメッセージを %s に移動しました。"
67 "%d 個のメッセージを %s にコピーしました。"
68 "%d 個のメッセージを %s にコピーしました。"
69 "表示がすでに存在します。新規の表示を手前にします。"
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/



70 "中止したレターの書き込み中..."
71 "メール・プログラム"
72 "了解"
73 "取消し"
74 "了解"

75 "了解"
76 "了解"

77 "変更内容を保存していないアタッチメントが開いています。\nこのメッセージを送信すると、開いているアタッチメントとの接続が切れます。\n保存していない変更内容はメッセージの一部にはなりません。\n接続が切れた場合、[別名保存] を使って変更内容を保存できますが、\n変更はアタッチメントの一部にはなりません。"
78 "メール・オプションを初期化中..."
79 "破棄して終了する"
80 "破棄しないで終了する"
81 "このアタッチメントに深刻な損傷を引き起こすコマンドが含まれている可能性があります。\n\必ず安全性を確かめてから操作を行なうことをお薦めします。安全な操作の場合は [了解] を押し、操作を取り消す場合は [取消し] を押します。"
82 "他のユーザがこのメールボックスを使用しています。\n排他的アクセスを要求しますか?"
83 "メール・プログラムは、このメールボックスに対して排他的アクセスを獲得できません。\nこのメールボックスを読み取り専用として開きますか?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "%d 個のメッセージを削除しました。"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "%d 個のメッセージを削除しました。"
86 "新規メールを検索中です..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "メール・プログラム - 閉じる"
88 "削除したメッセージを破棄しこのメールボックスを閉じますか?"
89 "破棄し閉じる"
90 "破棄しないで閉じる"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "アクションが無効なので実行できません。"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "アクションの実行に失敗しました。"
93 "選択したアイコン %s は実行可能です。\nアイコンを実行するには [了解]、終了するには [取消し] をクリックします。"

94 "システムから応答がないので、メール・プログラムは、このメールボックスに対して\n排他的アクセスを獲得できません。\n\n今回だけ、このメールボックスを読み取り専用として開くか、あるいは\n(他に誰もこのメールボックスを使用していない場合のみ)排他的アクセスなしに\n読み取り・書き込み可として開くことができます。"
95 "読み取り専用"
96 "読み取り-書き込み"

$ 
$ "-NEW"
$ 
$ This message appears when dtmail tries to open a mailbox which has been
$ opened by another dtmail process.
$ 
$ Parameters:
$   1.  Error message saying that the <mailbox>.dtmail lockfile has been found.
$   2.  The mailbox path.
$   3.  "OK"
$   4.  "Cancel"
$   5.  The <mailbox>.dtmail lockfile path.
$ 
97 "%s\n\nThis may indicate that another Mailer has opened\n%s\n\nYou may open this mailbox READ ONLY by choosing '%s'.\n\nOtherwise, you may choose '%s',\nmake sure that another Mailer has not opened this mailbox,\ndelete %s,\nand reopen this mailbox."

$ 
$ "-NEW"
$ 
$ Messages 98-100 check for problems in the paths specified by users of
$ the file selection box.
$ 
98 "Search permission denied on a component of the path prefix,\n'%s'."
99 "A component of the path prefix is not a directory,\n'%s'."
100 "A component of the path prefix does not exist,\n'%s'."


$set 5
1 "メール・プログラム"
2 "メール・プログラム"
3 "このメッセージをこのまま送信すると、アタッチメント\n\
   への変更はすべて失われます。"
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "アタッチメントを 1 つだけ選択し、[名前の変更] を選択してください。"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "メッセージ内のアドレスの一部が不正です。\n\
システムの既知のユーザを参照できません。\n\
すべてのアドレスが有効であることを確認した後、\n\
再試行してください。"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "メール・プログラムに、このメッセージを送信するのに\n\
使用できる十分なメモリがありません。\n\
他のアプリケーションを終了した後、\n\
このメッセージを送信しなおしてください。"
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "メッセージの送信中にエラーが発生しました。\n\
メッセージが受信されていることを確認してください。\n\
メッセージが受信されていない場合は、このメッセージを\n\
送信しなおしてください。"
$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "メッセージの To:、Cc:、Bcc: フィールドの受信者を指定してから\n\
送信してください。"

$set 12
1 "個のアタッチメント"
2 "個のアタッチメント"
3 "displayCount"
4 "FIFO ファイル %s を接続できません。"
5 "キャラクタ型特殊ファイル %s を接続できません。"
6 "ディレクトリ %s を接続できません。"
7 "ブロック型特殊ファイル %s を接続できません。"
8 "ソケット・ファイル %s を接続できません。"


$set 13
1 "作成できません。"
2 "書き込めません。"

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "アタッチメントの追加"
2 "%s を開けません。"
3 "FIFO ファイル %s を接続できません。"
4 "キャラクタ型特殊ファイル %s を接続できません。"
5 "ディレクトリ %s を接続できません。"
6 "ブロック型特殊ファイル %s を接続できません。"
7 "ソケット・ファイル %s を接続できません。"
8 "%s を開けません。"
9 "メール・プログラム - アタッチメント名の変更"
10 "説明"
11 "アタッチメントを別名保存"

$set 15
1 "変更内容をまだ保存していません。\n変更内容を保存するか、変更を破棄するか、\nまたはダイアログ内で以前の場所に戻ることができます。"
2 "保存"
3 "破棄"
$ 
$ The followings are added by IBM for 41J release
$ 
$set 20
1 "メールボックス %s は、すでに開いています。"
$ The above message is used in RoamMenuWindow::open
$ See AIXC cmvc defect 175920
2 "ローカル名使用: "
$ The above message is used in OptCmd::init_advanced_pane()
$ see AIX cmvc defect 176608
3 "読み取り専用"
$ The above message is used in RoamMenuWindow::mapnotify()
$ see AIX cmvc defect 176608

$ 
$	SETS 21 - 25 WERE ADDED TO SUPPORT CDEnext PRINTING
$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$set 21
$ 
$	Messages 1 - 11 are used in DmxPrintJob.
$ 
$ 
$	This is the status message that gets displayed in the MainWindow
$	and RoamMenuWindow status lines when a print job is being executed.
$	%s = the name of the temporary file containing the message(s) to be
$	printed.
1 "%s 印刷中..."

$	Messages 2 - 4 are used in the error popup which gets displayed
$	when an invalid margin specifier has been supplied by the user.
$ 
$	Message 2 is the actual error messagactual error message
$	Message 3 is the title which is displayed in the error popup.
$	Message 4 is the label on the OK button of the error popup.
2 "以下のマージンの指定は間違っています。: \n %s \n %s \n %s \n %s \n\
デフォルトの値で続けますか?"
3 "メール・プログラム"
4 "了解"

$	Messages 5 - 11 are format string used to construct the header
$	and footer strings which appear in the printing output.
$ 
$	Message 5 is the format string used to make a Cc header/footer.
$	Message 6 is the format string used to make a Date header/footer.
$	Message 7 is the format string used to make a From header/footer.
$	Message 8 is the format string used to make a Subj't header/footer.
$	Message 9 is the format string used to make a To header/footer.
$	Message 10 is the format string used to make a Page# header/footer.
$	Message 11 is the format string used to make a UserName header/footer.
5 "Cc:  %s"
6 "Date:  %s"
7 "From:  %s"
8 "Subject:  %s"
9 "To:  %s"
10 "Page %d of %d"
11 "Mail For:  %s"

$ 
$	Messages 12 - 13, 20 are used in DmxPrintSetup to construct the
$	app-specific printing options for DtMail which will be included
$	in the DtPrintSetupBox.
$ 
$	Message 12 is the label used on the Toggle Button to indicate that
$	multiple messages should be printed in separate spool jobs.
$	Message 13 is the label used on the Toggle Button to indicate that
$	lines which would extend beyond the edge of the printed page be 
$	"wrapped" to the next line.
12 "別々に、印刷"
13 "折返し使用"


$	Messages 14 - 15 are status messages for the PrintToFile function.
$ 
$	Message 14 indicates that the PrintToFile function was unsuccessful.
$	Message 15 indicates that the PrintToFile function was successful.
14 "'ファイルに出力'不成功でした。"
15 "'ファイルに出力'は成功で終了しました。"

$       NL_COMMENT 
$          Messages 16 - 19 are obsolete, and have been replaced by 24
$ 
$	Messages 16 - 19 are status messages for the popup PDM function.
$ 
$	Message 16 indicates that there was no pdm deamon running.
$	Message 17 indicates that the pdm deamon was unable to start a pdm.
$	Message 18 indicates that the pdm couldnt connect to the video display.
$	Message 19 indicates that the pdm couldnt connect to the print display.
16 "環境中にPDMがみつかりません。"
17 "PDMが起動できません。"
18 "PDMはビデオディスプレイに接続を認めません。"
19 "PDMはプリントディスプレイに接続を認めません。"

$	Message 20 is the label used on the Push Button to bring up
$	the printing options dialog from the DtPrintSetupDialog.
20 "詳細..."
$	Message 21 is used for the title string on the DtPrintSetupDialog.
21 "メール・プログラム - 印刷設定"

$	Message 22 is used to alert the user to the fact that the mailer
$		   cannot close the mailer window until a task (usually
$		   a print job) has terminated.
22 "保留を閉じます。:  待っているタスクを終了します。..."

$	Message 23 is used to alert the user to the fact that the X Print
$		   Server cannot complete the print request due to a lack
$		   of resources.
$ "NEW-"
23 "The X Print Server is temporarily out of resources"

$       Messages 24 & 25 are used to handle errors from the PDM
24	"印刷・ダイアログ・マネージャ(PDM) エラー - 設定失敗."
25	"継続"


$ 
$	The messages in this set are used in pulldown menu for the
$	header/footer $	frame which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 8 are used in DmxPrintOptions.
$ 
$ 
$	Message 1 specifies that the page header/footer field be empty.
$	Message 2 put the Cc msg header in the page header/footer field.
$	Message 3 put the Date msg header in the page header/footer field.
$	Message 4 put the From msg header in the page header/footer field.
$	Message 5 put the Subject msg header in the page header/footer field.
$	Message 6 put the To msg header in the page header/footer field.
$	Message 7 put the Page Nmbr msg header in the page header/footer field.
$	Message 8 put the User Name msg header in the page header/footer field.
$set 22
1 "なし"
2 "CC ヘッダ"
3 "Date ヘッダ"
4 "From ヘッダ"
5 "Subject ヘッダ"
6 "To ヘッダ"
7 "ページ番号"
8 "ユーザ名"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 4 are used in DmxPrintOptions.
$ 
$	Message 1 don't print any message headers.
$	Message 2 print the "standard" msg headers (To, From, Subject, Cc).
$	Message 3 print the "abbreviated" msg headers as defined by the user.
$	Message 4 print all message headers.
$ 
$set 23

1 "なし"
2 "標準"
3 "略記"
4 "すべて"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 5 are used in DmxPrintOptions.
$ 
$	Message 1 use a New Line (CRLF) to separate multiple messages.
$	Message 2 use a Blank Line (2xCRLF) to separate multiple messages.
$	Message 3 use a Line of characters to separate multiple messages.
$	Message 4 start each new message on a new page.
$	Message 5 print each message in it's own spool job.
$ 
$set 24
1 "改行"
2 "空行"
3 "文字行"
4 "改ページ"
5 "新規ジョブ"

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1 - 2 are used in DmxPrintOptions.
$ 
$ 
$set 25
$ 
$	Label for the option menu used to specify which message headers are
$	printed.
1 "メッセージ・ヘッダの印刷:  "
$ 
$	Label for the option menu used to specify which how multiple messages
$	are separated.
2 "複数メッセージの分け方:  "

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1-4 are used in error dialogs to indicate an invalid
$		     entry for margin specifiers in the printing options pane.
$	Message 5 is the label string on the button to dismiss the error dialog.
$ 
$ 
$set 26
1 "上マージンの指定は無効です。:  "
2 "左マージンの指定は無効です。:  "
3 "下マージンの指定は無効です。:  "
4 "右マージンの指定は無効です。:  "
5 "続く"

$ 
$	The following set was added to support the Mail Retrieval option pane.
$ 
$	Messages 1-5 Used in the Server Protocol option menu to indicate the
$		     set of mail server network protocols which are supported.
$	Messages 6-15 Are used to label the options in the pane.
$ 
$ "-NEW"
$ 
$set 27
1 "Auto"
2 "POP3"
3 "APOP"
4 "IMAP"
5 "POP2"

6 "Automatic (system) delivery"

7 "Mail server retrieval"
8 "Server Protocol:"
9 "Server Name:"
10 "User Name:"
11 "Password:"
12 "Remember password"
13 "Delete from server after retrieval"
14 "Retrieve old messages"

15 "Custom retrieval"
16 "User Getmail command:"

17 "Null INBOX path."
18 "INBOX folder path:"

