$ $XConsortium: dtscreen.msg /main/6 1996/10/16 03:17:20 cde-hit $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 
$ *                                                                      *
$ * (c) Copyright 1993, 1994 Hewlett-Packard Company                     *
$ * (c) Copyright 1993, 1994 International Business Machines Corp.       *
$ * (c) Copyright 1993, 1994 Sun Microsystems, Inc.                      *
$ * (c) Copyright 1993, 1994 Novell, Inc.                                *
$ *

$set 2
$ message file created 1993

$quote "
1 "1386-101 %s:  不正なコマンド行オプション \"%s\"\n\n"
2 "1386-102 \n 詳細説明は %s -help と入力してください。\n\n"

3 "1386-103 使用方法\n        %s [-オプション ...]\n\nオプションは次のものを含みます:\n"
5 "1386-105    %-28s %s\n\t ではモードは、\n\"-mode mode\"あるいは\"animation mode\"のいずれかです。"

7 "1386-107 未知のモード: "
10 "1386-110 %s を割り当てられません。\n"
11 "1386-111 %d 個のピクセルを割り当てました。\n"

17 "1386-117 %s: ディスプレイ %s を開けません。\n"
18 "1386-118 %s: GetResource - メモリを割り当てられません。"
19 "1386-119 %s: Malformed -ディスプレイ 引き数、\"%s\"\n"

20 "1386-120 -batchcount 引き数は正の数でなければなりません"
21 "1386-121 -saturation 引き数は 0.0 から 1.0 までの間でなければなりません。"

25 "1386-125 %s: %d 個の画面のみサポートできます。\n"
30 "1386-130 -delay 引き数は正の数でなければなりません。"
35 "1386-135 %s を割り当てられません。代わりに %s 使用します。\n"
40 "%s: 描画をしようとしているウィンドウを検出できません。-create オプションを\n\
   使用すると、%s はそれ自体のウィンドウを作成します。\n"
