$ $XConsortium: dttypes.msg /main/4 1996/10/16 03:18:28 cde-hit $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"すべてを初期化できません。\n"
4	"空列"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	""
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"%s から読み込みました。\n"
10	"未知"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"エラー = %s\n"
$ Translate "error" only
25	"使用方法:  dttypes [-help]\n\tdttypes [-type ファイル名]\n\tdttypes [-db データベース] [-w [rec_name 正規表現] [fld_name 正規表現]\n\t\t\t[fld_value 正規表現]]\n\t\t[-l [rec_name] [rec_info] [fld_name 正規表現] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s はタイプ %s です。\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"データベースが無効です。\n"
31	"有効な引き数ではありません。\n"
32	"-w オプションの rec_info フィールドが無効です。\n"
$ do not translate "rec_info" or "-w"
33	"-w オプションまたは -l オプションにはありません。\n"
$ do not translate "-w" or "-l"
34	"未知のオプションです。\n"
35	"-help"
$ Do not Translate
36	"正規表現 %s にエラーがあります。\n"
