$ 
$   COMPONENT_NAME: desktop
$ 
$   FUNCTIONS: none
$ 
$   ORIGINS: 27,118,119,120,121
$ 
$   This module contains IBM CONFIDENTIAL code. -- (IBM
$   Confidential Restricted when combined with the aggregated
$   modules for this product)
$   OBJECT CODE ONLY SOURCE MATERIALS
$ 
$   (C) COPYRIGHT International Business Machines Corp. 1995
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/5 1996/10/16 03:13:05 cde-hit $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$set 1
1 "本当にこのコマンドを実行しますか?"
2 "了解"
3 "取消し"
4 "メールプログラムのバージョン・ダイアログ"
5 "メールプログラムのバージョン・ダイアログ"
6 "アプリケーション内のコンポーネントを必ず選択してください。\n"
$ Messages 7 and 8 are no longer used.  They are both
$ replaced by message 9.
7 "メールプログラム・ヘルプ"
8 "メールプログラム・ヘルプ"
9 "このフォルダを閉じますか?"
10 "このコマンドは元に戻せません。実行しますか?"
11 "隠しフォルダと隠しファイルを表示します。"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "メールプログラム : ヘルプ"

$set 2
1 "選択エラーにより、継続できません。\n"
2 "ユーザが選択を中止しました。\n"
