/* XPM */
/* $XConsortium: helpmgr.pm /main/4 1996/10/29 15:58:12 drk $ */
static char * helpmgr_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"44 41 13 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconColor1	m black	c black",
"X	c #7D7D7D7D7D7D",
"o	c #AFAFAFAFAFAF",
"O	c #C8C8C8C8C8C8",
"+	c #969696969696",
"@	c #4B4B4B4B4B4B",
"#	s iconColor7	m white	c cyan",
"$	c #323232323232",
"%	s iconColor3	m black	c red",
"&	c #646464646464",
"*	c #E1E1E1E1E1E1",
"=	s iconColor5	m black	c blue",
/* pixels */
"                                            ",
"         .......                            ",
"         XoO++X@.              .........    ",
"         .o#o#@@........       .OOooooX$    ",
"  ......$.#+#X%@$++++++.@.....$.o++++X&$.   ",
"  .**.Oo$.X#X%@@$+X&XXX.@$o=o=$.OXO+o+X$.   ",
"  .*Oo+X$.#+#X%@$+XXXXX.@$=o@&$.oX++XX@$.   ",
"  .*Oo+X$.X#X%@@$+XXXXX..$@&X=$.OXo+XXX$.   ",
"  .*+X&X$.#+#X%@$+XXXXX.@$=o@&$.oX++XXX$.   ",
"  .*+X&X$.X#X%@@$       @$@&@=$.OX+@XXX$.   ",
"  .*Oo+X$.#@#$%@         $=o@&$.oX++XXX$.   ",
"  .*+X&X$.X#$%@    @@@    @&@=$.OX+&XXX$.   ",
"  .*+o&X$.#+#X%   @@XXX   @o@&$.oX+@XXX$.   ",
"  .*Oo+X$.X#X%@   @XXXX   @&@=$.OX+&XXX$.   ",
"  .*+X&X$.#+#X%   @XXXX   @o@&$.oX+@XXX$.   ",
"  .*Oo+X$.X#$%@@$@XXXX    @&X=$.OX+&XXX$.   ",
"  .*+X&X$.#@#$%@$+XXX    $=o@&$.oX++XXX$.   ",
"  .*+o+X$.X#X%@@$+XX    @$@&X=$.OX++XXX$.   ",
"  .*+X&X$.#@#$%@$+X    &@$=o@&$.oX+&XXX$.   ",
"  .*Oo+X$.X#$%@@$+X   @@@$@&X=$.oX+XXXX$.   ",
"  .*Oo+X$.#+#X%@$+X   @&@$=o@&$.oX++XXX$.   ",
"  .*Oo+X$.X#X%@@$+XX@@@&@$@&X=$.oX++XXX$.   ",
"  .*Oo+X$.#+#X%@$+X   X&@$=o@&$.oX++XXX$.   ",
"  .*Oo+X$.X#X%@@$+&   @&@$@&X=$.oX++XXX$.   ",
"  .*Oo+X$.#+#X%@$+X   @&@$=o@&$.oX++XXX$.   ",
"  .*Oo+X$.X#X%@@$+&&@@@&@$@&X=$.oX+@XXX$.   ",
"  .*oX&X$.#+#X%@$+XXXXX&@$=o@&$.oX++XXX$.   ",
"  .*Oo+X$.X#X%@@$+&X@@@&@$@&X=$.oX++XXX$.   ",
"  .*Oo+X$.#+#X%@$+XXXXX&@$=o@&$.oX++XXX$.   ",
"  .*Oo+X$.X#X%@@$+XXXXX&@$@&X=$.o&++XXX$.   ",
"  .OOo+X$.#+#X%@$+XXXXX&@$=o@&$.oX++XXX$.   ",
"  .oo+XX$.XXX&&@$+&XX&@&@$@&@=$.o&XXX&&$.   ",
"  .$$$$$$$$$$$$$$$$$$$$$$$$$$$$.o$$$$$$$.   ",
"  .OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO........   ",
"  .......................................   ",
"                                            ",
"                                            ",
"                                            ",
"                                            ",
"                                            ",
"                                            "};
