/* XPM */
/* $XConsortium: stylemgr.pm /main/4 1996/10/29 16:01:10 drk $ */
static char * stylemgr_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 22 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	c #E0E0E0E0E0E0",
"X	c #E1E1E1E1E1E1",
"o	c #4B4B4B4B4B4B",
"O	c #C8C8C8C8C8C8",
"+	c #AEAEAEAEAEAE",
"@	c #AFAFAFAFAFAF",
"#	c #F9F9F9F9F9F9",
"$	c #C7C7C7C7C7C7",
"%	s iconColor8	m black	c magenta",
"&	c #FFFF0000ABAB",
"*	s iconColor6	m white	c yellow",
"=	s iconColor1	m black	c black",
"-	c #FFFF00000202",
";	c #959595959595",
":	c #7D7D7D7D7D7D",
">	c #04040000FFFF",
",	c #0909FFFF0101",
"<	c #646464646464",
"1	s iconColor5	m black	c blue",
"2	c #969696969696",
"3	c #323232323232",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"       ..................XXXXXXXXXXXXXXXoO      ",
"       .+++++++++++++++++@@@@@@@@@@@@@@XoO      ",
"       .+++++++++++++++++@@@@@@@@X #######XO    ",
"       .++...............XXXXXX##O$$$$%&%$$###  ",
"       .++.++++++++++oX++@@@@##O$$$$$%&%&o$$$O# ",
"       .++.++++++++++oX++@@@#O$$****$&%&%o$$$$= ",
"       .++.++++++++++oX++@@#O$$****-$$ooo$$$$O= ",
" ======o++.++......++oX++@#O$$$****-$$$$$$$$O=  ",
"        o+.++.ooooo++oX++#O$$$$$*--$$;===$$O=   ",
"  oooooO o.++++++++++oX++#$$--$$$$$$$=::O$O=    ",
"  :::::OOo.++++++++++oX++#$---=$$##$$=XXO$O:XXX ",
"       ::o.++++++++++oX++#$---=$#>>>$$$$$$$$$$o ",
"        Oo.oooooooooooXoo#$$==$$>>>>>$,>,>,$$$o ",
"       :::oOOOOOOOOOOOOOO<OOOOOO111>=$>,>,OO$o= ",
"       OOOo222222222222222<3OOOOO11>=$,>,oOO2=  ",
"   XX........XX22222222222233=OOOOO$$$>>o$O3=   ",
"  XOOOOOOOOOOOO22;;;;;;;;2222===@OOO$$$$O:3:    ",
" XOXXX;XXX;XXX;@o;;;;;;;;222222===========:     ",
" XOX@+<X@@<X@+<@o<2222############::::::o<      ",
" XOX@@<X@@<X@@<@o<:222##===##===##=22222oO      ",
" XOX++<X++<X@+<@o<:222#=:::##=:::#=:2222oO      ",
" XOX++<X++<X@+<@o<:222#=::2##=222#=:2222oO      ",
" XO:::@:::@:::O@o<:222==:22##=222==:2222oO      ",
" XOOOOOOOOOOOOO+o<:2222::22##=2222::2222oO      ",
" XOX$X$X$X$X$X$+o<:22222222##=2########OoO      ",
" XXXXXXXXXXXX.X+o3ooooooooo##=o#==##==#=oO      ",
" XXXXXXXXXXXXXX+o<<OOOOOOOO##= #=O##=O#=OO      ",
" XOX$X$X$X$X$X$+o<:       O##= ==O##= ==OO      ",
" XO$O$O$O$O$O$O+o<:       O##=   O##=  OOOOOO   ",
" X@O+O+O+O+O+O+;o<:       O##=   O##= O#####O   ",
" X@++++++++++++;o<:       O##=   O##= O#=#=#=   ",
" X2+;+;+;+;+;+;:o<:      OO##=OO O##=  ==#===   ",
" X22;;;;;;;;;;;2o<:     O######=OO##=   O#=     ",
" X22;;;;;;;;;;:2o<:      =======:####=  O#=     ",
" X:;:;:;:;:;:;:2o<:       :::::::===== O###=    ",
" X::::::::::::::o<:               ::::: ====:   ",
"  <::::::::::::3<<:                      ::::   ",
"   <ooooooooooo<<::                             ",
"    <<<<<<<<<<<<::                              ",
"      ::::::::::::                              ",
"                                                ",
"                                                ",
"                                                "};
