$ $XConsortium: dttypes.msg /main/2 1996/07/24 19:00:16 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"allt gick inte att initsialisera\n"
4	"TOM STRÄNG"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"laddad från %s\n"
10	"Okänd"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"fel = %o, %s\n"
$ Translate "error" only
25	"usage:  dttypes [-help]\n\tdttypes [-type filnamn]\n\tdttypes [-db databas] [-w [rec_name söksträng] [fld_name söksträng]\n\t\t\t[fld_value söksträng]]\n\t\t[-l [rec_name] [rec_info] [fld_name söksträng] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s är av typen %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"Felaktig databas\n"
31	"Felaktigt argument\n"
32	"felaktigt rec_info-fält i tillägget -w\n"
$ do not translate "rec_info" or "-w"
33	"Not in -w or -l option\n"
$ do not translate "-w" or "-l"
34	"Okänt tillägg\n"
35	"-help"
$ Do not Translate
36	"fel i söksträngen %s\n"
