$ $XConsortium: libABobjXm.msg /main/1 1995/12/08 09:40:21 rswiston $

$ ========================================================================
$ = Message source text file for App Builder's libABobjXm utility library.
$ = @(#)libABobjXm.msg	1.2 13 Sep 1994 dtappbuilder/src/libABobjXm
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in objxmP.h
$set 203
1 "VARNING: %s : Det gick inte att konvertera filen [%s] till pixmap\n"
2 "VARNING: %s : Inget namn för glyfen specificerat\n"
3 "FEL vid representation: %s: NULL-objektsbilaga\n"
4 "FEL vid representation: %s: Byggklossens ID för överordnad är NULL\n"
5 "FEL vid representation: %s: Menyn gick inte att representera\n"
6 "FEL vid representation: Objektet måste ha ett giltigt namn\n"
7 "FEL vid representation: %s: Objektet måste ha en byggklossklass\n"
8 "INTERNT FEL: Uthoppsberäkningar stämmer inte.\n"
9 "FEL: objxm_comp_get_subobj - objektet är inte xm-konfigurerat: %s\n"
10 "Mappar"
11 "Filter"
12 "Ange filnamn"
13 "Uppdatera"
