$ $XConsortium: libAButil.msg /main/1 1995/12/08 09:40:31 rswiston $

$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.2 13 Sep 1994 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR: Fel vid tilldelning i intern array\n"
2 "ISTR: Fel vid tilldelning av utrymme för strängen\n"
3 "ISTR: Fel vid minnestilldelning"
4 "Internt fel"
5 "Rekursiva funktionsanrop"
6 "Du saknar behörighet"
7 "Gick inte att öppna"
