.\" $XConsortium: strcopy.3 /main/2 1996/10/29 15:11:48 drk $
.de L		\" literal font
.ft 5
.it 1 }N
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6
..
.de LR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RL
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.PD 0
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.PD
.RE
.PP
..
.TH STRCOPY 3
.SH NAME
strcopy \- copy strings
.SH SYNOPSIS
.L "char* strcopy(char* a, char* b)"
.SH DESCRIPTION
.I strcopy
copies the nul-terminated string
.I b
into
.IR a .
A pointer to the 0 character in
.I a
is returned.
.SH "SEE ALSO"
strcpy(3)
