.\" $XConsortium: struid.3 /main/2 1996/10/29 15:15:43 drk $
.de L		\" literal font
.ft 5
.it 1 }N
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6
..
.de LR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RL
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.PD 0
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.PD
.RE
.PP
..
.TH STRUID 3
.SH NAME
struid \- return user name given user number
.SH SYNOPSIS
.L "char* struid(int uid)"
.SH DESCRIPTION
.I struid
returns the user id name string given the user number
.IR uid .
.I struid
maintains an internal cache to avoid repeated password database scans
by the low level
.IR getpwuid (3).
.SH "SEE ALSO"
getpwent(3)
