$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:46:26 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s： 错误的命令行选项 “%s”\n\n"
2 "1386-102 \n输入 %s -help 得到完整的描述。\n\n"

3 "1386-103 用法：\n        %s [-选项 …]\n\n\
	 其中选项包括：\n"
5 "1386-105    %-28s %s\n\t 其中模式是下列之一：\n\"，\"-mode 模式\"，\"动画模式"

7 "1386-107 未知模式："
10 "1386-110 不能分配：%s\n"
11 "1386-111 %d 象素分配了\n"

17 "1386-117 %s：不能打开显示 %s。\n"
18 "1386-118 %s：GetResource－不能分配存储器"
19 "1386-119 %s：Malformed -显示参数，“%s”\n"

20 "1386-120 -batchcount 参数必须是正数。"
21 "1386-121 -saturation 参数必须在 0.0 和 1.0 之间。"

25 "1386-125 %s：只能支持 %d 个屏幕。\n"
30 "1386-130 -delay 参数必须是正数。"
35 "1386-135 不能分配：%s，使用 %s 代替\n"
40 "%s：不能定位在其中绘画的窗口。使用 -create\n\
	 选项将使 %s 创建它自己的窗口。\n"


