$ $XConsortium: dttypes.msg /main/2 1996/07/24 19:02:10 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"不能初始化所有的\n"
4	"NULL"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"从 %s 中装入\n"
10	"未知"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"出错 = %o, %s\n"
$ Translate "error" only
25	"用法:  dttypes [-help]\n\tdttypes [-type 文件名]\n\tdttypes [-db 数据库] [-w [rec_name 正规表达式] [fld_name 正规表达式]\n\t\t\t[fld_value 正规表达式]]\n\t\t[-l [rec_name] [rec_info] [fld_name 正规表达式] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s 具有类型 %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"非法数据库\n"
31	"不是一个合法的参数\n"
32	"非法的 rec_info 字段在 -w 选项中\n"
$ do not translate "rec_info" or "-w"
33	"不在 -w 或者 -l 选项中\n"
$ do not translate "-w" or "-l"
34	"未知选项\n"
35	"-help"
$ Do not Translate
36	"在正规表达式 %s 中出错\n"
