
$ "$XConsortium: dtwm.msg /main/3 1995/11/08 13:53:27 rswiston $";

$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtwm.msg
$ **
$ **  Project:     DT Workspace Manager (dtwm)
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtwm
$ **
$ **
$ *****************************************************************************
$ **
$ ** (c) Copyright 1990, 1992, 1993, 1994 Hewlett-Packard Company
$ ** (c) Copyright 1994 International Business Machines Corp.
$ ** (c) Copyright 1994 Sun Microsystems, Inc.
$ ** (c) Copyright 1994 Novell, Inc.
$ **
$ **     All Rights reserved
$ **
$ *****************************************************************************
$ *************************************<+>*************************************

$ *************************************<L>*************************************
$ **  -----------------GENERAL LOCALIZATION NOTES SECTION---------------------
$ * Comment lines begin with a $ except $set which indicates the start of a 
$ * new set.
$ *
$ * Do not delete any comments; you may add comments for your use.
$ *
$ * You don't need to localize the following sets:
$ *  sets 6, 8, 26, 28, 30, 32, 34, 38 
$ *  sets 44, 46, 48, 54, 56, 70, 76, 99
$ *
$ * Please localize the following sets:
$ *  sets 16, 22, 29, 36, 40, 52, 60, 62, 82, 84, 86.  
$ **  ----------------GENERAL LOCALIZATION NOTES SECTION END------------------
$ *************************************<L>*************************************

$set 6
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmBackdrop.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 创建背景窗口失败。

3 不能获得图象 %1$s 为工作空间 %2$s。
4 无足够内存用于背景窗口。


$set 8
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmCDecor.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够内存用于客户窗口边框
2 无足够内存用于客户窗口边框
3 无足够内存用于客户窗口边框
4 无足够内存用于客户窗口边框
5 无足够内存用于客户窗口边框
6 无足够内存用于客户窗口边框
7 无足够内存用于客户窗口边框



$set 20
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmError.c --

$    This message goes to an error file. It is the name of component
$    reporting the error.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
1 工作空间管理程序


$set 22
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmFeedback.c --

$    This is the message in the confirm dialog for toggling to and from 
$         PM (Presentation Manager) behavior 

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
2 无足够内存用于局部消息字符串

$    This is the message in the confirm dialog for restarting mwm
$ Do not localize "Mwm"
3 重新启动 Mwm?

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
5 无足够存储器用于局部消息字符串

$    This is the message in the confirm dialog for quitting mwm
$ Do not localize "Mwm"
6 退出 Mwm?

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
8 无足够存储器用于局部消息字符串

$    This is the message in the confirm dialog for logging out of DT Lite
$  You'll see it when pressing the Exit button from DT lite
9 注销?

$    This is the message in the confirm dialog for restarting dtwm
10 重新启动工作空间管理程序?

$    This is the message in the confirm dialog for quitting dtwm
11 退出工作空间管理程序?

$    This is the message in the confirm dialog for toggling to standard
$         PM (Presentation Manager) behavior from custom behavior
12 切换到默认特性?

$    This is the message in the confirm dialog for toggling back from
$         PM (Presentation Manager) behavior to custom behavior 
13 切换到定制特性?


$set 26
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmFunction.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 窗口管理程序重新启动失败。窗口管理程序程序不能\
找到或不能执行。
2 释放管理屏幕 %d 失败
3 无足够存储器重新启动窗口管理程序
4 对 f.goto_workspace 指定了非法的工作空间名


$set 28
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmGraphics.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于图形数据


$set 29
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmHelp.c --
$    Messages 1 and 2 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 1-2
1 针对项的提示失败。另一个程序可能已经获得了鼠标。
2 针对项的提示失败。另一个程序可能已经获得了鼠标。

$ Message 3 is an error message that appears when you are using Item Help
$ and select on something outside of the Workspace Manager
3 您必须选择一个工作空间管理程序\n\
对话，一个在前面板的中项，\n\
或者一个子面板中的项。

$ Message 4 is the title of the Help On Item Error dialog
4 工作空间管理程序 - 针对项提示出错

$set 30
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIDecor.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 不能使得图标进入图标框
2 无足够存储器用于图标创建
3 无足够存储器用于图标创建


$set 32
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIPC.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 不能与消息服务器连接。
2 无足够存储器处理背景更改。
3 缺少用于背景更改请求的路径名。
4 缺少用于背景更改请求的象素图。


$set 34
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIPlace.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于图标布局
2 无足够存储器用于图标布局
3 无足够存储器用于图标布局
4 无足够存储器创建图标框数据


$set 36
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIconBox.c --

$    Messages 1 & 2 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 1 & 2.
1 无足够存储器创建图标框数据
2 无足够存储器创建图标框数据

$    This is the last menu item in the icon box menu.  
$        This packs the icons together in the icon box. Only the
$        "PackIcons" and the "P" should be localized unless the
$        accelerator interferes with the local keyboard.  
$        The accelerator is OSF standard for this item and should only be
$        changed if this accelerator would lock out a local key use.
$ 
$        The underbar
$        is part of the syntax for mnemonics and should not be changed.
$        The letter after the underbar should match a letter (case sensitive)
$        in the item title .
$        (e.g.   CompressIcons _C Alt Shift<Key>F7 f.pack_icons\n  
$          OR
$                CompressIcons _I Alt Shift<Key>F7 f.pack_icons\n  )         
$ 
$   The mnemonic should also be chosen such such that it does not 
$        conflict with another mnemonic in the menu.

3 "重组图标" _P  Alt Shift<Key>F7 f.pack_icons\n

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
4 无足够存储器创建图标框数据


$set 38
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmImage.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无效的图标位图
2 无效的图标位图
3 无足够存储器倾斜图标图象
4 无足够存储器倾斜图标图象
5 无足够存储器用于位图 %s\n
6 无足够存储器用于位图 %s\n
7 不能读位图文件 %s\n
8 无效的位图文件 %s\n
9 图标位图不能用在此屏幕
10 颜色图标象素图不支持
11 %s 没有合法的图标文件格式。\n\
    请检查此文件并与其他图标文件比较。

$set 40
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmInitWs.c --

$    Messages 1-13 and 15,17 and 19-21 go to an error file.
$ DO NOT LOCALIZE MESSAGES 1 THROUGH 13.
1 不能打开显示。
2 无足够存储器用于屏幕数据
3 另一个窗口管理程序正在屏幕 %d 上运行。
4 不能打开第二个显示连接。
5 不能管理在显示上的任何屏幕。
6 不能配置 X 连接
7 不能为该屏幕名创建足够的存储器
8 无足够存储器用于工作空间 数据
9 无足够存储器用于 displayString
10 无足够存储器用于窗口管理程序数据
11 无足够存储器用于窗口管理程序数据
12 无足够存储器用于屏幕名字
13 无足够存储器用于屏幕名字

$     This is the default title for the icon box
14 图标

$    Message 15 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
15 无足够存储器用于局部消息字符串

$    Message 17 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
17 无足够存储器用于局部消息字符串

$    Message 19 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
19 无足够存储器用于局部消息字符串

$    Message 20 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
20 %1$s: %2$s 在行 %3$d 配置文件 %4$s\n

$    Message 21 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
21 %1$s: %2$s 在描述字符串的行 %3$d \n

$     This is the default title for the version dialog
22 关于工作空间管理程序

$     This is the default title for the Dtwm help dialog
23 工作空间管理程序 - 提示

$     This is the default title for the Generic help dialog
24 工作空间管理程序 - 提示


$set 44
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmMain.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
$quote "
1 ""
2 "无足够存储器用于窗口管理程序的名字"
$quote


$set 46
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmManage.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器接收初始客户


$set 48
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmMenu.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 菜单描述 %s 没有找到\n
2 无足够存储器用于菜单 %s\n
3 无足够存储器用于菜单 %s\n
4 菜单描述 %s 没有找到\n
5 检测到 %s 的菜单递归\n
6 无足够存储器用于菜单 %s\n
7 无足够存储器用于菜单 %s\n
8 菜单描述 %s 没有找到，使用内部菜单\n


$set 52
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmPresence.c --
$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
1 不能创建占用工作空间对话。

$    This tells what window the occupy workspace dialog is operating on.
2 窗口:

$    This is the label for the workspace list in the occupy workspace dialog
3 工作空间:

$    This is the label for the button to put a window in all workspaces
$        from the occupy workspace dialog
4 所有工作空间

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
5 无足够存储器创建占用工作空间对话。

$    This tells what window the occupy workspace dialog is operating on.
6 图标:




$set 54
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmProperty.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于窗口管理数据
2 无足够存储器用于窗口管理数据
3 无足够存储器用于窗口管理数据
4 无足够存储器用于窗口管理程序标志


$set 56
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmProtocol.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于窗口管理程序数据
2 无足够存储器进行 XInternAtom _MOTIF_WM_QUERY_nn
3 _MOTIF_WM_QUERY_nn 选择失败
4 缺少 _MOTIF_WM_QUERY_nn 选择
5 无足够存储器变换 _MOTIF_WM_QUERY_nn 选择


$set 60
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmResParse.c --
$    Messages 1-39 are written to an error file.
$    YOU DO NOT NEED TO LOCALIZE MESSAGES 1-39, 41.
$ 
$    Message 40 allows you to alter the labels for the modifier
$    keys on the menu accelerators. You may wish to localize
$    message 40 so that these labels match the keycaps on your
$    local keyboard.
$ 
1 无足够存储器用于会话过程几何数据项
2 无足够存储器用于在会话过程项中的工作空间列表
3 无足够存储器用于 commandArgv 数组
4 无足够存储器用于 commandArgv 项
5 无足够存储器用于 Dt 会话过程提示
6 不能打开配置文件
7 无足够存储器用于菜单加速键
8 不能创建一个名为 %s 的前面板\n
9 无足够存储器用于菜单
10 无足够存储器用于菜单
11 在菜单名后期待 '{'
12 无足够存储器用于菜单项
13 无足够存储器用于菜单项
14 无效的助记符描述
15 无足够存储器用于加速键描述
16 无效的加速键描述
17 无足够存储器
18 缺少组描述
19 无效的组描述
20 无效的数字描述
21 在按钮设置名后期待 '{'
22 无足够存储器用于按钮描述
23 无效的按钮描述
24 无效的按钮上下文
25 在键设置名后期待 '{'
26 无足够存储器用于键描述
27 无效的键描述
28 无效的键上下文

31 无足够存储器用于屏幕名字
32 无足够存储器用于屏幕名字

33 %1$s: %2$s 在行 %3$d  配置文件 %4$s\n
34 %1$s: %2$s 在描述字符串的行 %3$d

35 无足够存储器用于配置文件转换
36 无足够存储器处理包含的文件: %s
37 期待 '{'
38 无足够存储器用于在会话过程项中的宿主机名
39 不能重新打开配置文件 %s

$ Message 40 is used to remap the menu accelerator
$ modifier key labels to the keycaps that the user sees on the
$ local keyboard. If modifier key labels are not remapped, then
$ the key label used in the accelerator spec will appear on
$ the menu
$ 
$ Example: menu spec in dtwmrc file
$ 	 "Close"                 _C   Alt<Key>F4      f.kill
$ 
$ Appears as
$         Close       Alt+F4
$         -                  (the 'C' in Close is underlined)
$ 
$ if message 40 doesn't remap "Alt" then accelerator text is "Alt+F4"
$ if message 40 is "Alt XYZ" then accelerator text is "XYZ+F4"
$ 
$ The format of this message is a sequence of strings separated
$ by spaces. The strings are taken in pairs. If the first string
$ in a pair matches a accelerator key label, the second string
$ appears in its place on the menu. There must be an even number 
$ of strings. The case of the first string does not matter. The 
$ case of the second string is preserved.
$ 
$quote "
40 ""
$quote

$ 
$    Messages 41 is written to an error file.
$    YOU DO NOT NEED TO LOCALIZE MESSAGE 41.
$ 
41 无足够内存获得 LANG 环境变量。


$set 62
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmResource.c --

$    Messages 1, 3, 5, 7, 9, 11, 13, 15, 17 and 19 are menu items in the 
$         built in menu. Only the title and mnemonic should be localized,
$         never change the underbar.  For example in message 1,
$        "Restore" and the "R" may be localized.  The underbar
$        is part of the syntax for mnemonics and should not be changed.
$        The letter after the underbar should match a letter (case sensitive)
$        in the item title.  
$        (e.g.   Normalize  _N  )

$ Messages 1, 3, 5, 7, 9, 11, 13, 15, 17 and 19 are not used.
$ Messages 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 to 29, 31, 33 to 38, 66-68,
$          go to an errorlog and do NOT need to be localized.
$ Messages 30 and 39-47 are not used.
$ Only messages 32, 48-57 and 59 need to be localized.

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
2 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
4 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
6 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
8 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
10 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
12 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
14 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
16 无足够存储器用于局部默认菜单。

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
18 无足够存储器用于局部默认菜单。

$    Messages 20 to 29 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 20 TO 29.
20 无足够存储器用于局部默认菜单。
21 无足够存储器用于本地化默认系统菜单
22 无足够存储器用于颜色数据
23 装载字体失败: %.100s
24 无足够存储器用于工作空间数据
25 无效的工作空间名: "%s"
26 重复的工作空间名: "%s"
27 无足够存储器用于工作空间数据
28 无足够存储器用于日期资源
29 装载字体失败: %.100s

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
31 无足够存储器用于局部消息字符串

$    This is the default title of the "Rename Workspace" dialog
32 换名工作空间

$    Messages 33 to 38 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 33 TO 38.
33 无足够存储器用于局部消息字符串
34 不能获得颜色
35 不能获得颜色
36 不能获得颜色
37 无足够存储器用于窗口管理程序数据
38 无足够存储器用于窗口管理程序数据

$ Messages for the built in menu.  The built in menu will 
$ appear unless the user (through resources and app-defaults) 
$ specified a custom window menu.

$ Messages 48-57 are the definitions for the default built in
$ window menu.  These new messges allow the localizer to change the
$ accelerators if they interfere with the local keyboard.  The only item
$ that has an accelerator is Close _C Alt<Key>F4 f.kill.

$ The underbar is part of the syntax for mnemonics and should not 
$ be changed. The letter after the underbar should match a 
$ letter (case sensitive) in the item title and should not conflict
$ with another mnemonic.
$        (e.g.   Normalize  _N  )

$ The name of the function (e.g. f.normalize) should not change

$    This item will "close" the window.  This usually results in the
$    window being withdrawn.
48 关闭[C] _C Alt<Key>F4 f.kill

$    This item normalizes a window
49 恢复[R] _R  f.restore

$    This item moves a window
50 移动[M] _M  f.move

$    This item resizes a window
51 大小[S] _S  f.resize

$    This item changes a window into an icon
52 最小化[n] _n  f.minimize

$    This item makes a window as large as allowed (determined by a number
$         of factors)
53 最大化[x] _x  f.maximize

$    This item lowers a window below other windows
54 置后[L] _L  f.lower

$    This item brings up the occupy workspace dialog.  The character
$    sequence  "\\.\\.\\."  will appear as "..." in the menu . DO NOT CHANGE 
$    THE  "\\.\\.\\."  CHARACTERS
55 占用工作空间[O]\\.\\.\\. _O  f.workspace_presence

$    This item puts a window into all workspaces.  The character sequence
$    "\\" provides a space between "Occupy" and "all"  Use this sequence
$    to provide spaces in item titles.
56 占用所有工作空间[A] _A  f.occupy_all

$    This item removes a window from a workspace.  This item will appear in
$    in the menu as  "Unoccupy Workspace"  with the first e in the title underlined
$    to indicate this is a mnemonic for this item.
57 解除占用工作空间[U] _U  f.remove

$    This is the default title of the "occupy workspace" dialog
59 占用工作空间

$    The following 6 items are Sun-specific.  The only difference being
$    that these items have accelerators.  They should be localized
$    similarly to their corresponding item above.

60 恢复[R] _R Alt<Key>F5 f.restore
61 移动[M] _M  Alt<Key>F7   f.move
62 缩放[S] _S  Alt<Key>F8   f.resize
63 最小化[n] _n  Alt<Key>F9 f.minimize
64 最大化[x] _x  Alt<Key>F10 f.maximize
65 置后[L] _L  Alt<Key>F3   f.lower
$    Messages 66 to 68 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 66 TO 68.
66 资源 autoRaiseDelay 的值越界。必须是非负整数
67 Key bindings %s not found, using builtin key bindings\n
68 Button bindings %s not found, using builtin button bindings\n

$set 70
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmWinInfo.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于客户数据
2 无足够存储器用于客户数据
3 不能产生图标框
4 不能产生前面板。
5 窗口管理程序不能转换特性 %.100s 作为 clientTitle/iconTitle:XmbTextPropertyToTextList
6 无足够存储器转换特性 %.100s 作为 clientTitle/iconTitle:XmbTextPropertyToTextList
7 [XmbTextPropertyToTextList]:\n     本地环境（%.100s）不支持。（检查 $LANG）。
8 窗口管理程序接收未知的特性作为 clientTitle/iconTitle:%.100s。特性忽略。


$set 76
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmWrkspace.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 无足够存储器用于占用工作空间特性
2 无足够存储器用于占用工作空间特性
3 无足够存储器更新工作空间信息
4 无足够存储器用于客户数据
5 无足够存储器（ConvertNamesToIDs）
6 无足够存储器（ConvertNamesToIDs）
7 无足够存储器
8 无足够存储器（ConvertNamesToIDs）
9 无足够存储器增加窗口到工作空间
10 无足够存储器（GetLeaderPresence）
11 无足够存储器
12 无足够存储器保存资源
13 无足够存储器保存资源。
14 工作空间的最大数目是 %d。没有新的工作空间被创建。


$set 82
$    THIS COMMENT FOR DTWM TEAM ONLY -- PopupMenu.c --
$    This entire set should be localized.

$ Message 1 is the title of the Delete Locked Control Error dialog
1 工作空间管理程序 - 删除锁定的控制出错

$ Message 2 is the title of the Delete Control dialog
2 工作空间管理程序 - 删除控制

$ Message 3 is the title of the Delete Locked Subpanel Error dialog
3 工作空间管理程序 - 删除锁定的子面板出错

$ Message 4 is the title of the Delete Subpanel dialog
4 工作空间管理程序 - 删除子面板

$ Message 5 is the message in the Delete Locked Control Error dialog
5 此控制不能被删除，因为它是锁定的。

$ Message 6 is the message in the Delete Control dialog
6 您确实要删除此控制?

$ Message 7 is the message in the Delete Locked Subpanel Error dialog
7 此子面板不能被删除，因为它是锁定的。

$ Message 8 is the message in the Delete Control dialog when more than
$ exits in the subpanel to be deleted.
8 此子面板包含多个控制。\n您确实要删除此子面板?

$ Message 9 is the message in the Delete Control dialog when only the
$ copy of the main panel control exists in the subpanel.
9 您确实要删除此子面板?

$ Message 10 - 19 are the menu title, menu items, and mnemonics in the
$ Main/Subpanel Menu.
$ 
$ The entries are paired (label + mnemonic). The label appears in the
$ menu. The mnemonic is the character in the label that is underlined by
$ the menu system indicating that it is a keyboard shortcut.
$ 
$ The mnemonic must be a character in the label. Each mnemonic must be 
$ unique within this particular menu.
$ 
10 增加子面板[A]
11 A
12 删除子面板[D]
13 D
14 复制到主面板[C]
15 C
16 删除[D]
17 D
18 提示[H]
19 H

$ Message 20 - 21 are used in the menu title for the workspace button
$ menus.  20 is used for the format "Workspace <Name>".  21 is the first
$ arg in the format.
20 %1$s %2$s
21 工作空间

$ Message 22 - 30 are the menu title, menu items, and mnemonics in the
$ Switch Menu.
$ 
$ The entries are paired (label + mnemonic). The label appears in the
$ menu. The mnemonic is the character in the label that is underlined by
$ the menu system indicating that it is a keyboard shortcut.
$ 
$ The mnemonic must be a character in the label. Each mnemonic must be 
$ unique within this particular menu.
$ 
22 开关控制区
23 增加工作空间[A]
24 A
25 删除[D]
26 D
27 换名[R]
28 R
29 提示[H]
30 H

$ Message 31 - 40 are the pieces for the deletion dialogs
31 删除控制:
32 如果您删除此控制，您不能用“安装图标”\n的放区域来恢复它。\n\n您可以使用应用程序管理程序中的“恢复面板”\n将此控制在以后放回。\n\n您确实要删除此控制吗?
33 删除子面板:
34 如果您删除此子面板，您不能用“安装图标”\n的放区域来恢复包含在子面板中的所有控制。\n\n您可以使用应用程序管理程序中的“恢复面板”\n将此子面板和它的控制在以后放回。\n\n您确实要删除此子面板吗?


$ Used for the name of a newly created workspace.
35 新建

$ Used for Install Icon title in Install Icon popup menu.
36 安装图标


$set 84
$    THIS COMMENT FOR DTWM TEAM ONLY -- UI.c --
$    This entire set should be localized.
$ 
$ Message used for the label of the dynamic install area.
1 安装图标


$set 86
$    THIS COMMENT FOR DTWM TEAM ONLY -- Callback.c --
$    This entire set should be localized.

$ The next two messages are used for workspace naming errors
1 工作空间管理程序 - 换名出错
2 无效的或重复的工作空间名

$ The next three messages are used for the dynamical install error dialog.
3 工作空间管理程序 - 安装图标出错
4 安装图标:

$ Messages 5 and 6 are old. They are replaced by messaged 8 and 9.
5 已经有一个此名字的图标了。
6 控制动作出错

7 不能查找该文件
8 已经有一个此名字的图标了。
9 工作空间管理程序 - 图标动作出错


$set 99
$    DO NOT TRANSLATE THESE MESSAGES
$    DO NOT CHANGE THESE MESSAGES
$    DO NOT LOCALIZE THESE MESSAGES
$    These messages are used for the version information.
$quote "
1 "@(#)version_goes_here"
2 "\n@(#)_DtMessage catalog source $XConsortium: dtwm.msg /main/3 1995/11/08 13:53:27 rswiston $"

