$ $XConsortium: dttypes.msg /main/3 1995/11/03 15:27:52 rswiston $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"couldn't initialize everything\n"
4	"NULL"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"loaded from %s\n"
10	"Unknown"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"error = %s\n"
$ Translate "error" only
25	"usage:  dttypes [-help]\n\tdttypes [-type filename]\n\tdttypes [-db database] [-w [rec_name regexp] [fld_name regexp]\n\t\t\t[fld_value regexp]]\n\t\t[-l [rec_name] [rec_info] [fld_name regexp] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s is of type %s\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"Invalid DataBase\n"
31	"Not a valid argument\n"
32	"invalid rec_info field in -w option\n"
$ do not translate "rec_info" or "-w"
33	"Not in -w or -l option\n"
$ do not translate "-w" or "-l"
34	"Unknown option\n"
35	"-help"
$ Do not Translate
36	"error in regular expression %s\n"
