/* XPM */
/* $XConsortium: stylemgr.pm /main/2 1996/07/23 13:25:12 drk $ */
static char * fpstyle_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 19 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s bottomShadowColor	m black	c #636363636363",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray7	m black	c #424242424242",
"+	s topShadowColor	m white	c #bdbdbdbdbdbd",
"@	s iconGray3	m white	c #adadadadadad",
"#	s iconColor2	m white	c white",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconColor8	m black	c magenta",
"&	s selectColor	m white	c #737373737373",
"*	s iconColor6	m white	c yellow",
"=	s iconColor3	m black	c red",
"-	s iconGray4	m white	c #949494949494",
";	s iconGray5	m black	c #737373737373",
":	s iconColor5	m black	c blue",
"?	s iconColor4	m white	c green",
">	s iconGray6	m black	c #636363636363",
",	s iconGray8	m black	c #212121212121",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      ",
"      .oooooooooooooooooooooooooooooooooO+      ",
"      .o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@oO+      ",
"      .o@@@@@@@@@@@@@@@@@@@@@@@@@o########o$    ",
"      .o@@ooooooooooooooooooooo##$$$$$%#%$$###  ",
"      .o@@o@@@@@@@@@@Oo@@@@@@##$$$$$$%#%%O$$$$#&",
"      .o@@o@@@@@@@@@@Oo@@@@@#$$$****$#%#%O$$$$.&",
"      .o@@o@@@@@@@@@@Oo@@@@#$$$****=$$OOO$$$$$.&",
"      .O@@o@@oooooo@@Oo@@@#$$$$****=$$$$$$$$$.&&",
" #######O@o@@oOOOOO@@Oo@@#$$$$$$*==$$-...$$$.&& ",
" OOOOOO$#Oo@@@@@@@@@@Oo@@#$$==$$$$$$$.;;$$$.&&  ",
"  &&&&&$$Oo@@@@@@@@@@Oo@@#$===.$$##$$.oo$$$;ooo ",
"      X;;Oo@@@@@@@@@@Oo@@#$===.$#:::$$$$$$$$$$O&",
"      .#$OoOOOOOOOOOOOoOO#$$..$$:::::$?:?:?$$$O&",
"      X;;;O$$$$$$$$$$$$$$>$$$$$$::::.$:?:?$$$O.&",
"      #$$$O--------------->,$$$$$:::.$?:?O$$-.&&",
"   oooooooooooo------------,,.$$$$$$$$::O$$,.&& ",
"  o$$$$$$$$$$$$--------------...@$$$$$$$$;,&&&  ",
" o$ooo-ooo-ooo-@O--------------...........&&    ",
" o$o@@>o@@>o@@>@O>----############;;;;;;O &     ",
" o$o@@>o@@>o@@>@O>;---##...##...##.-----O+      ",
" o$o@@>o@@>o@@>@O>;---#.;;;##.;;;#.;----O+      ",
" o$o@@>o@@>o@@>@O>;---#.;;-##.---#.;----O+      ",
" o$;;;@;;;@;;;$@O>;---..;--##.---..;----O+      ",
" o$$$$$$$$$$$$$@O>;----;;--##.----;;----O+      ",
" o$o$o$o$o$o$o$@O>;--------##.-########+O+      ",
" oooooooooooooo@O,OOOOOOOOO##.O#..##..#.O+      ",
" oooooooooooooo@OX ++++++++##.+#.+##.+#.++      ",
" o$o$o$o$o$o$o$@OX&        ##.&..&##.&..&       ",
" o$$$$$$$$$$$$$@OX&        ##.& &&##.& &&       ",
" o@$@$@$@$@$@$@-OX&        ##.&   ##.& #####    ",
" o@@@@@@@@@@@@@-OX&        ##.&   ##.& #.#.#.   ",
" o-@-@-@-@-@-@-;OX&        ##.&   ##.& ..#...&  ",
" o--------------OX&      ######.  ##.&   #.&&&  ",
" o------------;-OX&      .......&####.   #.&    ",
" o;-;-;-;-;-;-;-OX&       &&&&&&&.....& ###.    ",
" o;;;;;;;;;;;;;;OX&               &&&&&  ...&   ",
"   ;;;;;;;;;;;;,XX&                       &&&   ",
"    OOOOOOOOOOOXX&&                             ",
"     XXXXXXXXXXX&&                              ",
"      &&&&&&&&&&&&                              ",
"                                                ",
"                                                ",
"                                                "};
