$ $TOG: dtcm.msg /main/12 1999/09/20 10:35:18 mgreess $
$quote "

$set 1

1 "dtcm: Destinataire vide dans le rappel de courrier.\n"

2 "Rappel- %s"

3 "pm"

4 "am"

5 "pm"

6 "am"

7 "\n\n\
\t** Rendez-vous (agenda) **\n\n\
\tDate:\t%s\n\
\tDébut:\t%s\n\
\tFin:\t%s\n\
\tObjet:\t%s"

8 "De %2d:%02d"

9 "am"

10 "pm"

11 "am"

12 "pm"

13 "De %02d%02d à %02d%02d"

16 "Impossible de supprimer l'agenda par défaut."

17 "Sélectionnez un nom pour la suppression."

20 "Date incorrecte dans la zone Jusqu'à."

21 "Modifier liste..."

22 "Options du menu Parcourir"

23 "Semaine préc."

24 "Cette semaine"

25 "Semaine proch."

26 "Mois préc."

27 "Ce mois-ci"

28 "Jusqu'à:"

29 "Planifier..."

30 "Courrier..."

31 "Agenda affiché"

32 "Agendas affichés"

33 "Jour"

34 "Semaine"

35 "Mois"

36 "Année"

37 "Fuseau horaire..."

38 "Liste des rendez-vous..."

40 "Visualiser"

41 "Rechercher..."

42 "Rechercher par la date..."

65 "Fichier"

68 "Impr. vue en cours"

69 "Imprimer..."

72 "Options..."

73 "Quitter"

74 "Rendez-vous..."

76 "Editer"

77 "Aide"

79 "Tâches..."

80 "Référence..."

82 "Aide sur l'aide..."

84 "Affich. autre agenda..."

85 "Compar. agendas..."

86 "Editeur de menus..."

87 "Parcourir"

88 "Aujourd'hui"

89 "dans quit_handler\n"

90 "Une erreur s'est produite lors de l'ouverture du fichier d'agenda."

91 "rpc.cmsd ne répond pas pour votre nom d'utilisateur.\n\
Assurez-vous que le processus inetd s'exécute et que l'entrée\n\
relative à rpc.cmsd dans le fichier inetd.conf est correcte."

92 "Nom d'utilisateur"

93 "Hôte"

94 "Erreur - Agenda"

95 "Continuer"

96 "Aucun fichier d'agenda pour"

97 "Aucun fichier d'agenda pour"

98 "Erreur - Agenda"

99 "Continuer"

100 "PAS DE NOM"

101 "rpc.cmsd ne répond pas pour"

102 "rpc.cmsd ne répond pas pour votre nom d'utilisateur.\n\
Assurez-vous que le processus inetd s'exécute et que l'entrée\n\
relative à rpc.cmsd dans le fichier inetd.conf est correcte."

103 "Nom d'utilisateur"

104 "Hôte"

105 "Erreur - Agenda"

106 "Continuer"

107 "%s: PAS DE NOM"

108 "Aucun emplacement d'agenda indiqué pour"

109 "Aucun emplacement indiqué. Ajoutez un nom hôte dans la zone Vue initiale de\n\
l'agenda (option Afficher les paramètres du menu Caractéristiques). Si vous \n\
avez lancé DTCM avec l'option -c, vérifiez que vous avez indiqué un nom hôte."

110 "Erreur - Agenda"

111 "Continuer"

112 "Les versions de DTCM et rpc.cmsd sont différentes."

113 "Agenda"

114 "Janvier"

115 "Février"

116 "Mars"

117 "Avril"

118 "Mai"

119 "Juin"

120 "Juillet"

121 "Août"

122 "Septembre"

123 "Octobre"

124 "Novembre"

125 "Décembre"

126 "Jan"

127 "Fév"

128 "Mar"

129 "Avr"

130 "Mai"

131 "Jun"

132 "Jul"

133 "Aoû"

134 "Sep"

135 "Oct"

136 "Nov"

137 "Déc"

138 "Dim"

139 "Lun"

140 "Mar"

141 "Mer"

142 "Jeu"

143 "Ven"

144 "Sam"

145 "Dim"

146 "Dimanche"

147 "Lundi"

148 "Mardi"

149 "Mercredi"

150 "Jeudi"

151 "Vendredi"

152 "Samedi"

153 "Dimanche"

154 "D"

155 "L"

156 "M"

157 "Me"

158 "J"

159 "V"

160 "S"

161 "D"

162 "D"

163 "L"

164 "M"

165 "Me"

166 "J"

167 "V"

168 "S"

169 "D"

170 "DIM"

171 "LUN"

172 "MAR"

173 "MER"

174 "JEU"

175 "VEN"

176 "SAM"

177 "DIM"

178 "%s est en cours de visualisation."

186 "Les versions de DTCM et rpc.cmsd sont différentes."

187 "Syntaxe:\n\
\tdtcm_delete [-c agenda] [-d <mm/jj/aa>] [-v vue]\n"

188 "\n\
Impossible d'ouvrir l'agenda %s.\n"

189 "INCONNU"

190 "Elément à supprimer (numéro) ? "

191 "Syntaxe:\n\
\tdtcm_insert [ -c agenda ] [-d <mm/jj/aa>] [ -v vue ]\n"

192 "                   [-w chaîne] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"

193 "Indiquez les informations relatives au rendez-vous à ajouter.\n\
Les valeurs par défaut apparaissent entre parenthèses.\n"

194 "Agenda (%s): "

195 "Date (%s): "

196 "Début (%s): "

197 "Vous avez indiqué une heure incorrecte ; corrigez-la.\n"

198 "Fin (%s): "

199 "Fin (%s): "

200 "Une fois"

201 "Répéter (%s): "

202 "Une fois"

203 "pas de défaut"

204 "Pour (%s): "

205 "Commentaire (5 lignes au maximum, ^D pour interrompre):\n"

206 "\n\
Impossible d'ouvrir l'agenda %s.\n"

207 "Syntaxe:\n\
\tdtcm_lookup [ -c agenda ][ -d <mm/jj/aa> ] [ -v vue ]\n"

208 "\n\
Impossible d'ouvrir l'agenda \"%s\".\n"

209 "INCONNU"

210 "Le rendez-vous sera planifié dans l'agenda en cours.\n\
Confirmez-vous cette opération ?"

211 "Planifier dans"

212 "Planifier rendez-vous"

214 "Rendez-vous planifié: %s\n"

218 "La DATE indiquée est incorrecte"

219 "L'heure de DEBUT indiquée est incorrecte."

220 "L'heure de FIN indiquée est incorrecte."

221 "La zone DATE est vide ou manquante."

222 "La zone DEBUT est vide ou manquante."

223 "La zone COMMENTAIRE est vide ou manquante."

224 "Incompatibilité entre les zones REPETER et POUR."

225 "Le rendez-vous planifié a été annulé."

226 "Erreur interne lors de la planification du rendez-vous."

227 "Le rendez-vous planifié a été annulé."

228 "Charger rendez-vous"

229 "Continuer"

230 "Faire glisser rendez-vous"

231 "Sélectionnez un rendez-vous et faites le glisser de nouveau."

232 "Continuer"

234 "Faire glisser rendez-vous"

235 "Continuer"

236 "Rendez-vousAgenda"

237 "XCreateBitmapFromData() n'a pas abouti pour le bitmap.\n"

238 "XCreateBitmapFromData() n'a pas abouti pour le masque.\n"

239 "DragStart a retourné une valeur NULLE.\n"

242 "am"

243 "pm"

244 "%s 3:41am"

245 "am"

246 "pm"

247 "L'heure de fin de ce rendez-vous est antérieure\n\
à son heure de début. Voulez-vous le planifier pour\n\
le lendemain ?"

248 "Planification rendez-vous"

250 "Lendemain"

251 "Auteur"

252 "Annuler rendez-vous"

253 "Sélectionnez un rendez-vous, puis Annuler."

254 "Continuer"

255 "Annuler rendez-vous"

256 "Une erreur interne s'est produite lors de la sélection\n\
du rendez-vous. Celui-ci n'a pas été annulé."

257 "Continuer"

258 "Modifier rendez-vous"

259 "Sélectionnez un rendez-vous, puis Modifier."

260 "Continuer"

261 "Modifier rendez-vous"

262 "Une erreur interne s'est produite lors de la sélection\n\
du rendez-vous. Celui-ci n'a pas été modifié."

263 "Continuer"

267 "Modifier rendez-vous"

268 "Ce rendez-vous fait partie d'une série récurrente.\n\
Confirmez-vous la modification...?"

270 "Ce rendez-vous uniquement"

271 "Avancer"

272 "Tous"

273 "Annuler rendez-vous"

274 "Ce rendez-vous fait partie d'une série récurrente.\n\
Confirmez-vous l'annulation...?"

276 "Ce rendez-vous uniquement"

277 "Avancer"

278 "Tous"

279 "Editeur de rendez-vous"

280 "Visu. liste des rendez-vous"

281 "La liste ne contient pas de rendez-vous."

282 "Continuer"

283 "Agenda - Programme de recherche"

284 "Rechercher:"

285 "Rechercher"

289 "Aide"

290 "Indiquez une chaîne à rechercher."

291 "Rendez-vous introuvable."

292 "%d occurrences trouvées."

293 "Date:"

294 "Jusqu'à"

296 "Aide"

297 "Indiquez une date."

298 "%s est en cours de visualisation."

299 "Date incorrecte."

300 "Auteur"

304 "Courrier..."

305 "Insérer réunion"

306 "Sélectionnez un agenda, puis Insérer."

307 "Continuer"

308 "Annuler rendez-vous"

309 "Sélectionnez un rendez-vous, puis Annuler."

310 "Continuer"

311 "Annuler rendez-vous"

312 "Une erreur interne s'est produite lors de la sélection\n\
du rendez-vous. Celui-ci n'a pas été annulé."

313 "Continuer"

314 "Annuler réunion"

315 "Sélectionnez un agenda, puis Annuler."

316 "Continuer"

317 "Annuler rendez-vous"

318 "Ce rendez-vous fait partie d'une série récurrente.\n\
Confirmez-vous l'annulation...?"

320 "Ce rendez-vous uniquement"

321 "Avancer"

322 "Tout"

323 "Modifier rendez-vous"

324 "Sélectionnez un rendez-vous, puis Modifier."

325 "Continuer"

326 "Modifier rendez-vous"

327 "Une erreur interne s'est produite lors de la sélection\n\
du rendez-vous. Celui-ci n'a pas été modifié."

328 "Continuer"

329 "Modifier réunion"

330 "Sélectionnez un agenda, puis Modifier."

331 "Continuer"

332 "Modifier rendez-vous"

333 "Ce rendez-vous fait partie d'une série récurrente.\n\
Confirmez-vous la modification...?"

335 "Ce rendez-vous uniquement"

336 "Avancer"

337 "Tout"

340 "Agenda"

341 "Accès"

342 "Insérer"

343 "Modifier"

348 "Ajouter permission"

349 "Editeur de réunions"

350 "Erreur de sélection, impossible de continuer.\n"

351 "Sélection interrompue par l'utilisateur.\n"

352 "Vous devez sélectionner un élément de l'application.\n"

353 "Sans horaire"

354 "Toute la journée"

355 "Impossible d'ouvrir le fichier callog.\n\
L'opération a été annulée. Agenda"

356 "Par demande utilisateur, opération annulée.\n\
Agenda"

357 "Valeur incorrecte dans la zone DATE.\n\
L'opération a été annulée. Agenda"

358 "Valeur incorrecte dans la zone DEBUT.\n\
L'opération a été annulée. Agenda"

359 "Valeur incorrecte dans la zone FIN.\n\
L'opération a été annulée. Agenda"

360 "Vous devez indiquer une DATE.\n\
L'opération a été annulée. Agenda"

361 "Vous devez indiquer une valeur de DEBUT.\n\
L'opération a été annulée. Agenda"

362 "Vous devez indiquer des COMMENTAIRES.\n\
L'opération a été annulée. Agenda"

363 "Valeurs REPETER et POUR incorrectes ou incompatibles.\n\
L'opération a été annulée. Agenda"

364 "L'opération de l'éditeur a échoué."

365 "Continuer"

367 "L'agenda existe déjà.\n\
L'opération a été annulée. Agenda"

368 "L'agenda n'existe pas.\n\
L'opération a été annulée. Agenda"

370 "Erreur d'autorisation. Permission refusée.\n\
L'opération a été annulée. Agenda"

378 "Erreur d'allocation de mémoire - Mémoire insuffisante.\n\
L'opération a été annulée. Agenda"

383 "Erreur inconnue.\n\
L'opération a été annulée. Agenda"

386 "L'heure de fin de ce rendez-vous est antérieure à son heure de début.\n\
Voulez-vous le planifier pour le lendemain ?"

387 "Planifier rendez-vous"

389 "Lendemain"

390 "Confidentialité:"

391 "Emplacement de l'agenda utilisateur:"

392 "Début et fin de la journée:"

393 "Début:"

394 "Fin:"

395 "Affichage de l'heure:"

396 "12 heures"

397 "24 heures"

398 "Vue par défaut:"

399 "Année"

400 "Mois"

401 "Semaine"

402 "Jour"

403 "Vue initiale de l'agenda:"

404 "Accès utilisateur"

405 "Sélectionnez au moins une permission."

406 "Continuer"

407 "Paramètres d'accès groupe -- Supprimer"

408 "Sélectionnez d'abord un nom."

409 "Continuer"

410 "Nom utilisateur:"

411 "Ajouter un nom"

412 "Permissions"

413 "Permissions"

414 "Supprimer nom"

415 "P = Parcourir I = Insérer S = Supprimer"

416 "Permissions:"

417 "Parcourir"

418 "Insérer"

419 "Supprimer"

420 "Destination:"

421 "Imprimante"

422 "Fichier"

423 "Imprimante:"

424 "Répertoire:"

425 "Options:"

426 "Fichier:"

427 "Largeur:"

428 "Hauteur:"

429 "Position:"

430 "Pouces à partir de la gauche"

431 "Pouces à partir du bas"

432 "Unités:"

433 "Exemplaires:"

434 "Inclure:"

435 "Afficher l'heure et le texte"

436 "Afficher l'heure seulement"

437 "Ne rien afficher"

438 "Tri des dates:"

439 "MM | JJ | AA"

440 "JJ | MM | AA"

441 "AA | MM | JJ"

442 "Séparateur de date:"

443 "Espace"

444 "Sauvegarder options d'agenda"

445 "Une erreur s'est produite lors de l'écriture sur ~/.desksetdefaults. Assurez-vous\n\
que vous disposez des permissions permettant d'effectuer cette opération."

446 "Continuer"

447 "Lire les options d'agenda"

448 "Une erreur s'est produite lors de la lecture de ~/.desksetdefaults. Assurez-vous\n\
que vous disposez des permissions permettant d'effectuer cette opération."

449 "Continuer"

450 "Editeur de rendez-vous - Aide"

451 "Les modifications effectuées n'ont pas été sauvegardées.\n\
Vous pouvez les sauvegarder, les annuler ou revenir à\n\
l'emplacement précédent dans la boîte de dialogue."

452 "Sauvegarder"

453 "Annuler"

454 "Sauvegarder options d'agenda"

456 "Continuer"

458 "Agenda -  Options"

459 "Catégorie:"

460 "Appliquer"

463 "Aide"

464 "ps_open_file(): Indiquez un répertoire ou un fichier.\n"

465 "ps_open_file(): Répertoire %s incorrect.\n"

466 "w+"

467 "ps_open_file(): Impossible d'ouvrir le fichier %s.\n"

468 "Page"

469 "Vue quotidienne (Gestionnaire d'agenda)"

470 "Matin"

471 "Après-midi"

472 "pm"

473 "Liste des activités (Gestionnaire d'agenda)"

474 "Liste des rendez-vous (Gestionnaire d'agenda)"

475 "Page"

476 "sur"

477 "Vue mensuelle (Gestionnaire d'agenda)"

478 "sur"

479 "Page"

480 "Dim"

481 "Lun"

482 "Mar"

483 "Mer"

484 "Jeu"

485 "Ven"

486 "Sam"

487 "ps_init_printer(): Impossible d'ouvrir le fichier postscript de prologue: %s.\n"

488 "sur"

489 "   Page"

490 "Vue hebdomadaire (Gestionnaire d'agenda)"

491 "L"

492 "M"

493 "Me"

494 "J"

495 "V"

496 "S"

497 "D"

505 "Sam"

506 "Dim"

507 "Vue annuelle (Gestionnaire d'agenda)"

508 "Vue annuelle (Gestionnaire d'agenda)"

523 "Liste des activités: Année %d."

524 "Liste des rendez-vous: Année %d."

525 "Liste des activités: %s"

526 "Liste des rendez-vous: %s"

527 "Liste des activités: Semaine %s"

528 "Liste des rendez-vous: Semaine %s"

529 "Liste des activités: %s"

530 "Liste des rendez-vous: %s"

531 "Tous les %d %s"

532 "DTCM: Répéter tous les"

533 "Répéter tous les:"

534 "Fréquence:"

535 "Pour:"

536 "Confidentialité:"

537 "Planification des rendez-vous"

538 "Voulez-vous planifier ce rendez-vous pour\n\
la dernière ou la 4e semaine du mois ?"

540 "Dernière semaine"

541 "4e semaine"

542 "Tous les %d %s"

543 "Tous les %d %s"

544 "Tous les %d %s"

559 "Visualisation de %s..."

560 "Agenda - Affich. autre agenda"

561 "Nom d'utilisateur:"

562 "Afficher"

564 "Aide"

565 "Auteur"

566 "Supprimer activité"

567 "Sélectionnez une activité, puis Supprimer."

568 "Continuer"

569 "Supprimer activité"

570 "Une erreur interne s'est produite lors de la\n\
sélection de l'activité. Celle-ci n'a pas été supprimée."

571 "Continuer"

572 "Supprimer activité"

573 "Cette activité fait partie d'une série récurrente.\n\
Confirmez-vous la suppression...?"

575 "Cette activité uniquement"

576 "Avancer"

577 "Toutes"

578 "Modifier activité"

579 "Cette activié fait partie d'une série récurrente.\n\
Confirmez-vous la modification...?"

581 "Cette activité uniquement"

582 "Avancer"

583 "Toutes"

584 "Modifier activité"

585 "Sélectionnez une activité, puis Modifier."

586 "Continuer"

587 "Modifier activité"

588 "Une erreur interne s'est produite lors de la\n\
sélection de l'activité. Celle-ci n'a pas été modifiée."

589 "Continuer"

590 "Echéance:"

591 "Editeur d'activités"

595 "Semaine commençant le %s"

596 "Lundi %d"

597 "Mardi %d"

598 "Mercredi %d"

599 "Jeudi %d"

600 "Vendredi %d"

601 "Samedi %d"

602 "Dimanche %d"

603 "Entrez un nom dans la zone Nom d'utilisateur."

604 "fait déjà partie de la liste."

605 "Aide"

606 "Erreur - Agenda"

607 "Une erreur interne s'est produite lors de l'enregistrement du nom d'agenda."

608 "Continuer"

609 "Agenda - Erreur"

610 "Une erreur interne s'est produite lors de l'extraction du nom d'agenda."

611 "Continuer"

612 "Généralités..."

613 "A propos de l'agenda..."

617 "Aujourd'hui"

618 "Vous devez indiquer un paramètre pour l'argument -session.\n"

619 "Entrez un nom d'agenda sous la forme: <utilisateur>@<nom_hôte>"

620 "Agenda inconnu. Nom requis: <nom>%s"

621 "Entrez un nom d'agenda sous la forme: <utilisateur>@<nom_hôte>"

622 "Agenda inconnu. Nom hôte requis: %s@<nom_hôte>"

623 "L'agenda n'affiche pas les dates antérieures au 1er janvier 1970."

624 "L'agenda n'affiche pas les dates postérieures au 31 décembre 2037."

625 "Moins"

626 "Plus"

627 "Faire glisser rendez-vous"

628 "Heure  Commentaires"

629 "Plus"

631 "%d occurrence(s) trouvée(s)"

632 "Sélectionnez un rendez-vous à afficher dans la liste."

633 "Agenda sélectionné"

634 "Agendas sélectionnés"

635 "Moins"

636 "Plus"

637 "Plus"

641 "Le serveur n'est pas parvenu à obtenur l'adresse de réseau\n\
de l'emplacement indiqué: nom hôte incorrect."

642 "Le démon rpc.cmsd n'est pas enregistré. Vérifiez \n\
qu'il est installé correctement sur le système."

643 "Impossible d'accéder à l'agenda. Agenda"

644 "Heures de rendez-vous:"

645 "Durée:"

646 "Minutes"

647 "Recherche de %s..."

648 "SunDex"

649 "Agenda - Fuseau horaire"

650 "Heure locale"

652 "Heure GMT"

653 "GMT"

654 "Heures"

655 "OK"

656 "Appliquer"

658 "Aide"

659 "Fuseau horaire:"

660 "Fuseau horaire:"

662 "Fuseau horaire:"

663 "Moins"

664 "Plus"

666 "Plus"

667 "L'agenda n'affiche pas les dates antérieures au 1er janvier 1970."

668 "L'agenda n'affiche pas les dates postérieures au 31 décembre 2037."

670 "Dtcm"

671 "Version"

672 "Révision"

674 "Copyright (c) 1993, 1994:"

675 "Hewlett-Packard Company"

676 "International Business Machines Corp."

677 "Novell, Inc."

678 "Sun Microsystems, Inc."

679 "Suite..."

680 "Fermer"

681 "Développeurs"

682 "Cette application a été conçue par:"

683 "Fermer"

684 "Vous ne pouvez pas entrer d'espaces ou de tabulations dans les noms d'utilisateurs."

685 "Nom d'utilisateur:"

686 "Ajouter un nom"

687 "Supprimer un nom"

688 "Options du menu Parcourir"

689 "OK"

690 "Appliquer"

691 "Restaurer"

693 "Aide"

696 "Syntaxee:\n\
\tdtcm_admin [ -d ] [ -a action ] [ -c agenda][ -s <mm/jj/aa> ] [ -e <mm/jj/aa> ] [-f nom_fichier]\n"

697 "Vous avez indiqué une opération de gestion non prise en charge (\"%s\").\n"

698 "\n\
Impossible d'ouvrir le fichier en sortie \"%s\".\n"

699 "\n\
Impossible d'ouvrir le fichier en entrée \"%s\".\n"

700 "Supprimer"

702 "Aide"

703 "contexte"

704 "Année %d"

705 "%s"

706 "Semaine %s"

707 "%s"

708 "Le mode de répétition de ce rendez-vous est inconnu ; toutes les\n\
occurrences vont être modifées. Confirmez-vous la suppression ?"

710 "Continuer"

711 "Le mode de répétition de ce rendez-vous est inconnu ; toutes les\n\
occurrences vont être supprimées. Confirmez-vous la suppression ?"

712 "Continuer"

713 "Vous devez sélectionner la date de début avant la date de fin."

714 "La liste ne contient aucun rendez-vous ; l'affichage est impossible."

715 "Agenda - Rechercher par la date"

716 "Le mode de répétition de ce rendez-vous est inconnu ; toutes les\n\
occurrences vont être modififées. Confirmez-vous la suppression ?"

717 "Continuer"

718 "Le mode de répétition de ce rendez-vous est inconnu ; toutes les\n\
occurrences vont être modifiées. Confirmez-vous la modification ?"

720 "Continuer"

721 "Heure et texte accessibles aux autres"

722 "Heure accessible aux autres"

723 "Aucune donnée accessible aux autres"

724 "Des commentaires doivent être indiqués pour les rendez-vous\n\
sans horaire. L'opération a été annulée. Agenda"

725 "L'entrée d'agenda n'existe pas.\n\
L'opération a été annulée. Agenda"

727 "Dépassement de délai de la requête. Vérifiez que\n\
rpc.cmsd est installé correctement sur le système."

728 "Agenda - Imprimer"

729 "Imprimante:"

730 "Exemplaires:"

731 "De:"

732 "A:"

733 "Options d'impression:"

734 "Copier dans le fichier:"

735 "Imprimer"

736 "Agenda : Erreur - Imprimer"

737 "Aide"

738 "Liste d'accès:"

739 "Droits d'accès:"

740 "Ajouter"

741 "Supprimer"

742 "Modifier"

743 "Publique:"

744 "Semi-privé:"

745 "Privé:"

746 "Visualiser"

747 "Insérer"

748 "Modifier"

749 "Pour ajouter un élément à la liste d'accès, vous devez définir son nom et ses droits d'accès."

750 "Paramètres d'accès groupe -- Ajouter"

751 "Cette entrée figure déjà dans la liste d'accès. Voulez-vous la modifier ?"

752 "Paramètres d'accès groupe -- Ajouter"

753 "Modifier"

755 "Paramètres d'accès groupe -- Modifier"

756 "Pour modifier un élément de la liste d'accès, vous devez indiquer son nom et ses droits d'accès."

757 "Paramètres d'accès groupe -- Modifier"

758 "minuit"

759 "valeur"

760 "valeur"

761 "Supprimer"

762 "Paramètres par défaut de l'éditeur"

763 "Afficher les paramètres"

764 "Listes et autorisations"

765 "Paramètres de l'imprimante"

766 "Format de date"

767 "OK"

768 "Restaurer"

772 "Vous ne pouvez pas sauvegarder un emplacement\n\
d'agenda vide ou contenant des espaces.\n\
Les caractéristiques n'ont pas été sauvegardées."

773 "Vous ne pouvez pas sauvegarder une vue initiale\n\
d'agenda vide ou contenant des espaces.\n\
Les caractéristiques n'ont pas été sauvegardées."

774 "ps_open_file(): Pour effectuer la copie, vous devez indiquer un nom de fichier.\n"

775 "Vous devez indiquer le rappel suivant.\n\
L'opération a été annulée. Agenda"

776 "Un rappel ne doit pas contenir d'espaces.\n\
L'opération a été annulée. Agenda"

777 "Les valeurs d'avance doivent être numériques et,\n\
éventuellement, signées. L'opération a été annulée. Agenda"

778 "Liste des activités - Aide"

779 "Les modifications n'ont pas été sauvegardées.\n\
Vous pouvez les sauvegarder, les annuler ou revenir\n\
à l'emplacement précédent dans la boîte de dialogue."

780 "Supprimer"

781 "Visualiser"

782 "Tout"

783 "En attente"

784 "Terminé"

785 "OK"

786 "Appliquer"

788 "Aide"

789 "Type d'activité:"

790 "contexte"

791 "Le mode de répétition de cette activité est inconnu ; toutes les\n\
occurrences vont être modifiées. Confirmez-vous la modification ?"

793 "Continuer"

794 "Le mode de répétition de ce rendez-vous est inconnu ; toutes les\n\
occurrences vont être modifiées. Confirmez-vous la modification ?"

796 "Continuer"

797 "Activité"

798 "Echéance:"

799 "Terminé"

800 "Insérer"

801 "Modifier"

802 "Supprimer"

803 "Effacer"

805 "Aide"

806 "Année %d"

807 "%s"

808 "Semaine %s"

809 "%s"

810 "Entrez une date de début postérieure au 1/1/1970."

811 "Date de début incorrecte."

812 "Entrez un date de fin antérieure au 1/1/2038."

813 "Date de fin incorrecte."

814 "Vous devez indiquer une date postérieure à 1969 et antérieure à 2038."

815 "Vous devez indiquer une date postérieure à 1969 et antérieure à 2038."

816 "Jours"

817 "Semaines"

818 "Mois"

819 "La valeur indiquée pour la durée doit être un entier non signé.\n\
Les caractéristiques n'ont pas été sauvegardées."

820 "La valeur de début doit être une heure correcte.\n\
Les caractéristiques n'ont pas été sauvegardées."

$ 821 "Vous avez indiqué une largeur incorrecte pour l'impression.\n\
$ Les caractéristiques n'ont pas été sauvegardées."
$ "print width" has been replaced by "right margin".
821	"Vous avez indiqué une valeur incorrecte pour la marge de droite.\n Les caractéristiques n'ont pas été sauvegardées."

$  "Vous avez indiqué une hauteur incorrecte pour l'impression.\n\
$ Les caractéristiques n'ont pas été sauvegardées."
$ "print height" has been replaced by "bottom margin".
822	"Vous avez indiqué une valeur incorrecte pour la marge du bas.\n Les caractéristiques n'ont pas été sauvegardées."

825 "Jours"

826 "Semaines"

827 "Mois"

828 "Date:"

829 "Début:"

830 "AM"

831 "PM"

832 "Fin:"

833 "AM"

834 "PM"

835 "Commentaires:"

836 "Fréquence"

837 "Insérer/Modifier activité"

839 "Agenda: Rappel"

840 "Fermer"

841 "Sélectionnez \"Ajouter un nom\" pour ajouter un nom ou \"Appliquer\" pour valider les modifications."

842 "Les informations transmises ne contiennent\n\
aucun rendez-vous."

843 "L'opération de glisser-poser n'a pas abouti."

844 "Les informations transmises sont introuvables."

845 "L'opération de glisser-poser n'a pas abouti.\n\
Erreur interne de cohérence."

846 "Sauvegarder"

847 "Restaurer"

848 "Date"

849 "Heure"

850 "Commentaires"

851 "Afficher le rendez-vous"

852 "Une fois"

853 "Tous les jours"

854 "Toutes les semaines"

855 "Toutes les 2 semaines"

856 "Tous les mois, par date"

857 "Tous les mois, par jour"

858 "Tous les ans"

859 "De lundi à vendredi"

860 "Lun, Mer, Ven"

861 "Mardi, Jeudi"

862 "Répéter tous les..."

863 "2"

864 "3"

865 "4"

866 "5"

867 "6"

868 "7"

869 "8"

870 "9"

871 "10"

872 "11"

873 "12"

874 "13"

875 "14"

876 "toujours"

877 "Min."

878 "Hrs"

879 "Jours"

880 "Aide"

881 "Erreur interne #1: Identificateur d'agenda/entrée incorrect.\n\
L'opération a été annulée. Agenda"

882 "Erreur interne #2: Identificateur de session incorrect.\n\
L'opération a été annulée. Agenda"

883 "Erreur interne #3: Données incorrectes.\n\
L'opération a été annulée. Agenda"

884 "Erreur interne #4: Valeur indiquée pour un attribut\n\
en lecture seule. L'opération a été annulée. Agenda"

885 "Erreur interne #5: Type de données incorrect indiqué pour1\n\
une valeur d'attribut. L'opération a été annulée. Agenda"

886 "Erreur interne #6: L'attribut indiqué n'est pas pris en charge\n\
par cette version de l'agenda. L'opération a été annulée. Agenda"

887 "Erreur interne #7: La fonction indiquée n'est pas prise en charge\n\
par cette version de l'agenda. L'opération a été annulée. Agenda"

888 "Erreur interne #8: L'opérateur indiqué est incorrect.\n\
L'opération a été annulée. Agenda"

890 "Erreur - Fonctions d'agenda"

891 "Imprimer"

892 "Les dates indiquées pour l'impression doivent être comprises entre 1969 et 2038."

893 "Imprimer"

894 "Date \"De\" incorrecte"

895 "Imprimer"

896 "Date \"A\" incorrecte"

897 "Imprimer"

898 "La date \"A\" indiquée pour l'impression doit être postérieure à la date \"De\"."

899 "Début de la liste d'activités: %s"

900 "Début de la liste de rendez-vous: %s"

901 "Répéter tous les..."

902 "De lundi à vendredi"

903 "Lun, Mer, Ven"

904 "Mardi, Jeudi"

905 "Répéter tous les..."

906 "Faire glisser activité"

907 "Espace insuffisant pour le fichier d'agenda.\n\
L'opération a été annulée. Agenda"

908 "Vous ne pouvez pas définir une valeur de rappel vide.\n\
Les caractéristiques n'ont pas été sauvegardées."

909 "Vous ne pouvez pas définir une valeur de rappel contenant\n\
un espace. Les caractéristiques n'ont pas été sauvegardées."

910 "Les valeurs de rappel doivent être des nombres, éventuellement\n\
signés. Les caractéristiques n'ont pas été sauvegardées."

$ 911 "Vous avez indiqué une position incorrecte pour le décalage à gauche.\n\
$ Les caractéristiques n'ont pas été sauvegardées."
$ "position from left offset" has been changed to "left margin".
911	"Vous avez indiqué une valeur incorrecte pour la marge de gauche.\n Les caractéristiques n'ont pas été sauvegardées."

$ 912 "Vous avez indiqué une position incorrecte pour le décalage à droite.\n\
$ Les caractéristiques n'ont pas été sauvegardées."
$ "position from right offset" has been changed to "top margin".
912	"Vous avez indiqué une valeur incorrecte pour la marge du haut.\n Les caractéristiques n'ont pas été sauvegardées."

913 "La première ligne des commentaires associés à une activité doit contenir du texte."

914 "L'opération de l'éditeur d'agenda n'a pas abouti."

915 "L'opération de l'éditeur d'agenda n'a pas abouti."

916 "La durée doit être inférieure à 24 heures.\n\
Les caractéristiques n'ont pas été sauvegardées."

917 "Graphique\n\
manquant"

918 "Graphique\n\
manquant"

919 "Agenda"

920 "affiché."

921 "Impossible d'accéder à l'agenda:"

922 "A propos de l'agenda"

923 "Annuler"

924 "Annuler"

925 "Annuler"

926 "Fermer"

927 "Annuler"

928 "Annuler"

929 "Annuler"

930 "Insérer"

931 "Modifier"

932 "Supprimer"

933 "Effacer"

934 "Annuler"

935 "Aide"

936 "Annuler"

937 "Annuler"

938 "Annuler"

939 "Annuler"

940 "Fermer"

941 "Fermer"

942 "Annuler"

943 "Annuler"

944 "Annuler"

945 "Annuler"

946 "Annuler"

947 "Annuler"

948 "Fermer"

949 "Annuler"

950 "Annuler"

951 "Annuler"

952 "Fermer"

953 "Annuler"

954 "Fermer"

955 "Annuler"

956 "Annuler"

957 "Annuler"

958 "Annuler"

959 "Annuler"

960 "Annuler"

961 "Annuler"

962 "Annuler"

963 "Agenda - Editeur de menus"

964 "Sur l'élément"

965 "Liste des activités..."

966 "Activité..."

967 "Version du serveur Agenda"

968 "Version données Agenda"

969 "Répétition (fréquence)"

970 "La valeur de répétition doit être un entier sans signe."

971 "Heure Agenda"

972 "Commentaire"

973 "Rechercher tous"
974 "Rechercher de"
975 "à"
976 "Type de rapport :"
977 "Vue quotidienne"
978 "Vue hebdomadaire"
979 "Vue mensuelle"
980 "Vue annuelle"
981 "Liste de rendez-vous"
982 "Liste des activités"
983 "Nom de l'utilisateur"
984 " Ce rendez-vous fait partie d'une série récurrente.\n Confirmer l'insertion...?"
985 "Rappels"
986 "Bip"
987 "Clignoter"
988 "Message instantané"
989 "Message"
990 "Expédier à :"
992 "%A, %e %B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993 "Semaine commençant le %A %e %B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994 "jours"
995 "semaines"
996 "deux semaines"
997 "mois"
998 "années"
1002 "Contribue aussi :"
1003 "Ce rendez-vous existe dans un autre agenda.\nConfirmer la modification ?"
1004 "Ce rendez-vous existe dans un autre agenda.\n Confirmer la suppression ?"
1005 "Supprimer de"
1006 "Changer dans"
1007 " Une erreur interne s'est produite lors de la sélection\n\
du rendez-vous. Celui-ci n'a pas été modifié."
1008 "Agenda rendez-vous : Aide"
1009 " Une erreur interne s'est produite lors de la sélection\n\
de l'activité. Celle-ci n'a pas été modifiée."
1010 "Agenda : Comparer les agendas"
1011 "Valeur incorrecte dans la zone \"Echéance\".\nOpération annulée. Agenda"

1012 "Agenda -  Liste d'activités"

1042 "Insérer accès refusé: "
1043 "Supprimer accès refusé : "
1044 "Visualiser accès refusé : "
1045 "Annuler pour"
1046 "Rendez-vous annulé\n"
1047 "This appointment: '%s' has an end\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048 " L'heure de fin de ce rendez-vous \n"
1049 " est antérieure à son heure de début.\n"
1050 " Voulez-vous le planifier pour le lendemain ? [Y/N]  "
1051 " Le rendez-vous '%s'fait partie d'une série récurrente.  "
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052 "Voulez-vous :"
1053 "\n\t1. Les supprimer tous"
1054 "\n\t2. Ne supprimer que celui-ci"
1055 "\n\t3.  Supprimer en avant"
1056 "\n\t4.  Annuler"
1057 "\n\tOption [1-4]: "
1058 "Date spécifiée incorrecte.\n"
1059 "Heure de début spécifiée incorrecte.\n"
1060 "Heure de fin spécifiée incorrecte.\n"
1061 "Zone Date vide ou manquante.\n"
1062 "Zone Début vide ou manquante.\n"
1063 "Zone Commentaires vide ou manquante.\n"
1064 "Zones Répéter et Pour incompatibles.\n"
1065 "Insérer rendez-vous a été annulé\n"
1066 "Rendez-vous n'a pas été inséré."
1067 "Date spécifiée incorrecte :"
1068 "Rendez-vous pour"
1069 "Pas de rendez-vous pour"
1070 "Agenda : Erreur - Comparer les agendas"
1072 " Agenda : Erreur - Parcourir"
1073 " Agenda : Erreur - Faire glisser et poser"
1074 "Rendez-vous agenda"
1075 " Agenda : Erreur - Changer rendez-vous"
1076 " Agenda : Aide"
1078 " Agenda : Liste d'accès et permissions - Ajouter"
1079 " Agenda : Erreur - Paramètres d'éditeur"
1083 " Agenda : Erreur - Afficher paramètres"
1085 " Agenda : Erreur - Paramètres de l'imprimante"

1086 "Agenda - Liste de rendez-vous"

1087 "From %1$2d:%2$02d%3$s to %4$2d:%5$02d%6$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088 "%1$2d:%2$02d%3$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089 "From %1$02d%2$02d to %3$02d%4$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090 "%1$02d%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091 "%B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092 "%Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/

1100 "\n\n\
\t** Activité (agenda) **\n\n\
\tEchéance:\t%s\n\
\tHeure:\t%s\n\
\tCommentaires:\t\t%s"

1101 "Insérer rendez-vous"

1102 "Insérer activité"

1103 "Cette activité fait partie d'une série récurrente.\n\
Voulez-vous l'insérer...?"

1104 "Valeur incorrecte dans la zone Heure.\n\
L'opération a été annulée. Agenda."

1105 "Vous devez indiquer une heure.\n\
L'opération a été annulée. Agenda."

$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"Date"
1107	"Id utilisateur"
1108	"Numéro de page"
1109	"Type de rapport"
1110	"Aucun"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"Agenda Erreur - Configuration de l'impression"
1112	"Erreur du Gestionnaire d'impression (PDM) - configuration a échoué."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113	"Imprimante ou serveur d'impression incorrect."
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114	"Agenda : Erreur - Imprimer dans le fichier"
1115	"Erreur - impossible d'imprimer dans le fichier."
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116	"Agenda : Imprimer dans le fichier"
1117	"Imprimer dans le fichier terminé."
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118	"Agenda : Avertissement - Imprimer"
1119	"Avertissement - Impossible de charger la police %s."
$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled.
1120	"L'événement ne peut avoir lieu dans le temps donné.\nL'opération a été annulée."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
1121	"Agenda : Erreur du serveur d'impression"
1122	"Le travail d'impression a échoué.\n\nLe serveur d'impression X manque temporairement de ressources."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Calendar - Warning
$ "-NEW"
2 "Could not connect to ToolTalk:\n%s\n"
$ "-NEW"
3 OK
$ "-NEW"
4 "Calendar : Appointment Editor - Warning"
