$ $XConsortium: dtscreen.msg /main/3 1995/11/08 12:29:09 rswiston $
$ @(#)25\t1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37  
$   
$ COMPONENT_NAME: dtscreen  
$   
$ FUNCTIONS: dtscreen.msg  
$   
$   
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993  
$ All Rights Reserved  
$ Licensed Materials - Property of IBM  
$   
$ US Government Users Restricted Rights - Use, duplication or  
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.  
$   
$   
$quote "

$set 2
$ message file created 1993  

1 "1386-101 %s: Option de ligne de commande incorrecte \"%s\".\n\n\
"

2 "\"1386-102 \n\
Entrez %s -help pour afficher une description complète.\n\n\
"

3 "1386-103 Syntaxe:\n\
        %s [-options ...]\n\n\
\t Les options disponibles sont:\n\
"

5 "1386-105    %-28s %s\n\
\t mode correspond à:\n\
\", \"-mode mode\" ou \"animation mode"

7 "1386-107 Mode inconnu: "

10 "1386-110 Impossible d'allouer: %s\n\
"

11 "1386-111 %d pixels alloués.\n\
"

17 "1386-117 %s: Impossible d'ouvrir l'écran %s.\n\
"

18 "1386-118 %s: GetResource - impossible d'allouer de la mémoire."

19 "1386-119 %s: Argument -display incorrect, \"%s\".\n\
"

20 "1386-120 L'argument -batchcount doit être positif."

21 "1386-121 L'argument -saturation doit être compris entre 0 et 1."

25 "1386-125 %s: Seuls %d écrans peuvent être pris en charge.\n\
"

30 "1386-130 L'argument -delay doit être positif."

35 "1386-135 Impossible d'allouer: %s, utilisation de %s.\n\
"

40 "%s: Impossible de localiser la fenêtre dans laquelle le dessin doit être réalisé.\n\
        Si vous utilisez l'option -create, %s crée sa propre fenêtre.\n\
"
