$ $XConsortium: dttypes.msg /main/2 1996/07/24 18:51:36 drk $
$quote "

$set 1

1 "Dttype"
$ Do not Translate  

2 "Dttype"
$ Do not Translate  

3 "impossible d'initialiser l'ensemble\n"

4 "NULL"
$ this should mean a "Empty string".  

5 "=============== %s ===============\n"
$ Do not Translate  

6 "\0"
$ Do not Translate  

7 "%s\n"
$ Do not Translate  

8 ""
$ Do not Translate  

9 "chargé à partir de %s\n"

10 "Inconnu"

11 "\t%s"
$ Do not Translate  

12 "\0"
$ Do not Translate  

13 " :\t%s"
$ Do not Translate  

14 "\0"
$ Do not Translate  

15 "\n"
$ Do not Translate  

16 "-db"
$ Do not Translate  

17 "-w"
$ Do not Translate  

18 "-l"
$ Do not Translate  

19 "rec_info"
$ Do not Translate  

20 "rec_name"
$ Do not Translate  

21 "fld_name"
$ Do not Translate  

22 "fld_value"
$ Do not Translate  

23 "all"
$ Do not Translate  

24 "erreur = %o, %s\n"
$ Translate "error" only  

25 "Syntaxe:  dttypes [-help]\n\
\tdttypes [-type nom_fichier]\n\
\tdttypes [-db base_données] [-w [rec_name reg_exp] [fld_name reg_exp]\n\
\t\t\t[fld_value reg_exp]]\n\
\t\t[-l [rec_name] [rec_info] [fld_name reg_exp] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"  

26 "-type"
$ Do not Translate  

27 "%s est de type %s\n"

28 "$"
$ Do not Translate  

29 "--------------------- %s ----------------\n"
$ Do not Translate  

30 "Base de données incorrecte\n"

31 "Argument incorrect\n"

32 "zone rec_info incorrecte dans l'option -w\n"
$ do not translate "rec_info" or "-w"  

33 "Option introuvable dans -w ou -l\n"
$ do not translate "-w" or "-l"  

34 "Option inconnue\n"

35 "-help"
$ Do not Translate  

36 "erreur dans expression régulière %s\n"
