$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 Sélection du fichier BDF 
4 Le fichier sélectionné existe. L'annuler ?
6 L'ouverture du fichier sélectionné a échoué.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 Cette police ne contient pas de caractères définis par l'utilisateur.
4 Impossible d'ouvrir la police sélectionnée. Vous n'avez pas d'autorisation d'accès au fichier de police ou le format du fichier est incorrect.
6 Le fichier de police est utilisé dans une autre application UDC.
8 Pas de police
10 Ouvrir
12 Annuler
14 Utilitaire d'échange de données UDC
16 Sélectionner les éléments
18 - Jeu de code :
20 -   Style :
22 -   Largeur :
24 -  Hauteur :

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 Voulez-vous interrompre l'échange UDC ?
4 Il n'existe pas de UDC dans cette police
6 Le nom XLFD n'est pas sélectionné
8 Impossible d'ouvrir le fichier de polices
10 Le fichier de polices est en cours d'utilisation dans une autre application UDC.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 Utilitaire UDC d'échange de données
4 Une erreur fatale a eu lieu.
6 Impossible d'ouvrir le fichier de polices.
8 Impossible de lire le fichier de polices.
10 La mémoire est épuisée.
12 Une erreur fatale a eu lieu.
14 Le fichier de polices spécifié n'existe pas.
16 Ce n'est pas une police pcf ou snf.
18 Impossible d'ouvrir le fichier de liste de polices.
20 Le format du fichier de liste de polices est incorrect.
22 Les descriptions du fichier de liste de polices sont incorrectes.
24 Le format du fichier de liste de polices est incorrect.
26 Impossible d'ouvrir le fichier rep. de polices.
28 Impossible de lire le fichier rep. de polices
30 Impossible de lire les propriétés des polices.
32 Impossible d'obtenir la propriété de FONT.
34 Impossible d'obtenir la propriété de FAMILY_NAME.
36 Ce fichier de police est en cours d'utilisation dans une autre application.
38 Impossible de verrouiller le fichier de polices.
40 Impossible de déverrouiller le fichier de polices.
42 Im[possible d'obtenir l'information de verrou du fichier de polices.
44 Impossible de trouver le fichier de polices spécifié.
46 Impossible de lire la base de données NLS.
48 Impossible d'obtenir les noms de charset de la base de données NLS.
50 Le nom charset n'est pas défini dans la base de données NLS.
52 La police spécifiée n'a pas été ouverte.
54 Une erreur fatale a eu lieu.
56 Nom XLFD           :
58 Police d'origine (nom XLFD)  :
60 Zone de code UDC      :
62 Style              :
64 Taille (taille des lettres) :
66 Ouvrir
68 Annulerl
70 OK
72 Annuler
74 Copier le code d'origine(hex)  :
76 Copier le code de destination(hex) :
78 Copier
80 Recouvrir
82 fonction exporter
84 fonction importer
86 Annuler

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 La création du fichier BDF a échoué
4 Aucun index sélectionné
6 OK
8 Annulerl
10 index de glyphes

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Impossible d'ajouter les images glyphes de ce fichier BDF à la police.
4 L'ouverture de la police sélectionnée a échoué. Vous n'avez pas d'autorisation d'accès au fichier de polices ou le format est incorrect.
6 Une ou plusieurs images glyphes seront écrasées. Ecraser ?
8 L'ouverture de la police sélectionnée a échoué. Vous n'avez pas d'autorisation d'accès au fichier de polices ou le format est incorrect.
10 Impossible d'ajouter les images glyphes de ce fichier BDF à la police.
12 L'enregistrement du fichier de polices a échoué.
