$   
$ +SNOTICE  
$   
$  $XConsortium: MotifApp.msg /main/5 1996/10/19 15:26:10 rws $  
$   
$  RESTRICTED CONFIDENTIAL INFORMATION:  
$   
$  The information in this document is subject to special  
$  restrictions in a confidential disclosure agreement between  
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this  
$  document outside HP, IBM, Sun, USL, SCO, or Univel without  
$  Sun's specific written approval.  This document and all copies  
$  and derivative works thereof must be returned or destroyed at  
$  Sun's request.  
$   
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.  
$   
$ +ENOTICE  
$   

$quote "

$set 1
1 "Voulez-vous vraiment exécuter cette commande ?"
2 "OK"
3 "Annuler"
4 "Version de DtMail"
5 "Version de DtMail"
6 "Vous devez sélectionner un élément de l'application.\n"
7 "DtMail - Aide"
8 "DtMail - Aide"
9 "Voulez-vous fermer ce dossier ?"
10 "Vous ne pouvez pas annuler cette commande. Voulez-vous continuer ?"

11 "Affiche les dossiers et fichiers cachés"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "Programme courrier : Aide"

$set 2        Redefine set#
1 "Erreur de sélection, impossible de continuer.\n"
2 "Sélection interrompue par l'utilisateur.\n"
