/* XPM */
/* $XConsortium: minus.pm /main/2 1996/07/23 13:39:20 drk $ */
static char * minus_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"60 30 17 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconColor1	m black	c black",
"X	m black c #8282B8B8FFFF",
"o	s iconGray1	m white	c #e1e1e1e1e1e1",
"O	m black c #00006D6DFFFF",
"+	m black c #000035357D7D",
"@	s iconGray2	m white	c #c8c8c8c8c8c8",
"#	s bottomShadowColor	m black	c #646464646464",
"$	s topShadowColor	m white	c #c8c8c8c8c8c8",
"%	s iconColor5	m black	c blue",
"&	s iconGray7	m black	c #4b4b4b4b4b4b",
"*	s iconGray5	m black	c #7d7d7d7d7d7d",
"=	s iconGray4	m white	c #969696969696",
"-	s iconGray6	m black	c #646464646464",
";	s iconGray8	m black	c #323232323232",
":	s iconGray3	m white	c #afafafafafaf",
"?	s selectColor	m white	c #7d7d7d7d7d7d",
/* pixels */
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                              ...............               ",
"   XXXXXXXXXXXXXXXX           .            o.               ",
"   XOOOOOOOOOOOOOO+           . @@@@@@@@@@ o.               ",
"   XOOOOOOOOOOOOOO+        ####  @ @ @@     #######$        ",
"   XOOOOOO%%OOOOOO+       ## @@ @@@ @@ @@@  o@@@@@@&$       ",
"   XOOOOOO%%OOOOOO+      ## @*=ooooooooooooo=@o@@@@@&$      ",
"   XOOOOO%%%OOOOOO+      # @@-**************** @@@@@@&$     ",
"   XOOOOOO%%OOOOOO+      # oooooooooooooooooooooooooo&$     ",
"   XOO          OO+      # @oooooooooooooooooo------@&$     ",
"   XOO          OO+      # @oooooooooooooooooo-****-@&$     ",
"   XOOOOOO%%OOOOOO+      # @@*****************------@&$     ",
"   XOOOOOO%%OOOOOO+      # @@@@@@@@@@@@@@@@@@@@@@@@@@&$     ",
"   XOOOOOO%%OOOOOO+      # @@@@@@@@@@@@@@@@@@@@@@@@@@&$     ",
"   XOOOOOO%%OOOOOO+      # @@;;;;;;;;;;;;;;;;;;@@@@@@&$     ",
"   XOOOOOOOOOOOOOO+      # @@;=***************;@@@@@@&$     ",
"   XOOOOOOOOOOOOOO+      # ;;: ****************;;;;;;&$     ",
"   X+++++++++++++++       #:&=*****************&&&&;$$$     ",
"                           :;;;;;;;;;;;;;;;;;;;;;;;;$       ",
"                             ;;;;;;;;;;;;;;;;;;#?$$$        ",
"                             ###################?           ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};
