/* XPM */
/* $XConsortium: flagdown.pm /main/3 1996/12/18 02:35:45 cde-hit $ */
static char * flagdown_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"60 36 14 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".    s bottomShadowColor m black c #636363636363",
"X    s topShadowColor m white c #bdbdbdbdbdbd",
"o    s iconGray1     m white c #dededededede",
"O    s iconGray6     m black c #636363636363",
"+    s iconGray8     m black c #212121212121",
"@	s iconColor6	m white	c yellow",
"#	s iconColor1	m black	c black",
"$    s iconGray2     m white c #bdbdbdbdbdbd",
"%    s iconGray7     m black c #424242424242",
"&    s iconGray5     m black c #737373737373",
"*    s iconGray4     m white c #949494949494",
"=    s iconGray3     m white c #adadadadadad",
"-    s selectColor m white c #737373737373",
/* pixels */
"                                                            ",
"                                                            ",
"                                   .......           ....X  ",
"                                   .ooooo....        .oooX  ",
"                                    .oO+++ooo..     .o@@+X  ",
"                                    .oO+o@o@@oo.....o@@O+X  ",
"                                    .oO+@o@O@@@ooooo@@O@+X  ",
"                                    .oO+o@o@O@O@@o@o@O@O+X  ",
"                                    .oO+@o@O@O@@o@o@o@O@+X  ",
"       ###############              .oO+o@o@O@@O@o@o@O@O+X  ",
"       #            o#              .oO+@o@O@O@@o@o@o@O@+X  ",
"       # $$$$$$$$$$ o#              .oO+o@o@O@O@@o@o@O@O+X  ",
"    ....  $ $ $$     .......X       .oO+@o@O@O@@o@o@o@O@+X  ",
"   .. $$ $$$ $$ $$$  o$$$$$$%X      .oO+o@o@O@@O@o@o@O@O+X  ",
"  .. $&*ooooooooooooo*$o$$$$$%X     .oO+@o@O@O@@o@o@o@O@+X  ",
"  . $$O&&&&&&&&&&&&&&&& $$$$$$%X    .oO+o@o@O@O@@o@o@O@O+X  ",
"  . oooooooooooooooooooooooooo%X    .oO+@o@O@O@@o@o@o@O@+X  ",
"  . $ooooooooooooooooooOOOOOO$%X    .oO+o++++@@O@o@o@O@+XX  ",
"  . $ooooooooooooooooooO&&&&O$%X    .oO++XXXX+++o@o@O@+X    ",
"  . $$&&&&&&&&&&&&&&&&&OOOOOO$%X    .oO+X    XXX++++++X     ",
"  . $$$$$$$$$$$$$$$$$$$$$$$$$$%X    .oO+X       XXXXXX      ",
"  . $$$$$$$$$$$$$$$$$$$$$$$$$$%X    .oO+X                   ",
"  . $$++++++++++++++++++$$$$$$%X    .oO+X                   ",
"  . $$+*&&&&&&&&&&&&&&&+$$$$$$%X    .oO+X                   ",
"  . ++= &&&&&&&&&&&&&&&&++++++%X    .oO+X                   ",
"   .=%*&&&&&&&&&&&&&&&&&%%%%+XXX    .oO+X                   ",
"    =++++++++++++++++++++++++X      .oO+X                   ",
"      ++++++++++++++++++.-XXX       .oO+X                   ",
"      ...................-          .oO+X                   ",
"                                    .oO+X                   ",
"                                    .oO+X                   ",
"                                    .oO+X                   ",
"                                   ######X                  ",
"                                   XXXXXXX                  ",
"                                                            ",
"                                                            "};
