/* XPM */
/* $XConsortium: cdelogo.pm /main/3 1996/12/18 02:54:07 cde-hit $ */
static char * cdelogo [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 56 15 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s topShadowColor m white c #bdbdbdbdbdbd",
"X    s bottomShadowColor m black c #636363636363",
"o    s iconGray6     m black c #636363636363",
"O	s iconColor2	m white	c white",
"+    s iconGray5     m black c #737373737373",
"@    s iconGray3     m white c #adadadadadad",
"#    s iconGray2     m white c #bdbdbdbdbdbd",
"$    s iconGray4     m white c #949494949494",
"%	s iconColor8	m black	c magenta",
"&    s iconGray7     m black c #424242424242",
"*	s iconColor1	m black	c black",
"=	s iconColor3	m black	c red",
"-    s iconGray1     m white c #dededededede",
";	s iconColor5	m black	c blue",
/* pixels */
"                                                                ",
"    .......................................................X    ",
"    .ooooooooooooooooooooooooooooooooooooooooooooooooooooooX    ",
"    .o                                                    oX    ",
"    .o                                                    oX    ",
"    .o                    OOOOOOOOOO                      oX    ",
"    .o                   OOOOOOOOOOOO                     oX    ",
"    .o                  OOOOOOOOOOOOOO                    oX    ",
"    .o                 OOOOOOOOOOOOOOOO                   oX    ",
"    .o                 OOOOOO    OOOOOO                   oX    ",
"    .o                 OOOOO      OOOOO                   oX    ",
"    .o        XXXXXXXXXOOOOO      OOOOO                   oX    ",
"    .o        Xo+@###@+OOOOO      OOOOO    XXXXXXXXXXXXX  oX    ",
"    .o        Xo+$%@%+&&&        OOOOOO    Xo$#@#@#$#+X*. oX    ",
"    .o        Xo+%#=+=oo&XXXXXXXOOOOOO     Xo+$@@$$$$o&*. oX    ",
"    .o XXXXXXXXo+$%@=+%o&*oo+$oOOOOOOXXXXXXXo+$@@$$$$o&*. oX    ",
"    .o X@-#-#@*o+%#=+=oo&*o+$oOOOOOO*@;#;@&*o@#--##@$o&*. oX    ",
"    .o X-#@@$+*o+$%@=$%o&*o+$OOOOOO&*;@;+;&*o+++oooooo&*. oX    ",
"    .o X-#@@$+*o$##@$$$+&*o+$OOOOOo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*ooooooo&&&*o+$OOOOoo&*;@;+;&*o+$@@$$++o&*. oX    ",
"    .o X-@+oo+*o+=#=+=oo&*o+$OOOOoo&*o;&;o&*o+$@+&&++o&*. oX    ",
"    .o X-@@@o+*o+$%&=&%o&*o+@$$$+oo&*;@;+;&*o+$@+$&++o&*. oX    ",
"    .o X-@+oo+*o+%o=&=oo&*o+@$$$+oo&*o;&;o&*o+$@+o&++o&*. oX    ",
"    .o X-##@$+*o+$%&=&%o&*o+$OOOOoo&*;@;+;&*o+$@@&$++o&*. oX    ",
"    .o X-@+oo+*o+%#=+=oo&*o+$OOOOoo&*o;&;o&*o+$@+o&++o&*. oX    ",
"    .o X-#+@o+*o+$%@=+%o&*o+$OOOOoo&*;@;+;&*o+$@+o&++o&*. oX    ",
"    .o X-@+oo+*o+%#=+=oo&*o+$OOOOoo&*o;@;o&*o+$@@&$++o&*. oX    ",
"    .o X-##@$+*o+$%&=&%o&*o+$$$$+oo&*;@;+;&*o+$@+o&++o&*. oX    ",
"    .o X-@+oo+*o+%o=&=oo&*o+@@$$+oo&*o;@;o&*o+$@+$&++o&*. oX    ",
"    .o X-@+oo+*o+$%&=&%o&*o+@@$$+oo&*;@;+;&*o+$@+$&++o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-@+oo+*o+$%@=+%o&*o+@@$$+oo&*;@;+;&*o+$@+o&++o&*. oX    ",
"    .o X-@@@o+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@&$++o&*. oX    ",
"    .o X-@+oo+*o+$%@=+%o&*o+@@$$+oo&*;@;+;&*o+$@@o$++o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+$%@=+%o&*o+@@$$+oo&*;@;+;&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+$%@=+%o&*o++o&$&&&&*;@;+;&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$++o&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+$%@=+%o&*o++o&&+&&&*;@;+;&*oo+++$o&&o&*. oX    ",
"    .o X-#@@$+*o+%#=+=oo&*o+@@$$++o&*o;&;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*o+$%@=+%o&*o++o$&&&&&*;@;+;&*o+$@+$&++o&*. oX    ",
"    .o X-#@@$+*o$@@$$$++&*o+@@$$+oo&*o;&;o&*o+$@@$$++o&*. oX    ",
"    .o X-#@@$+*ooooooo&&&*o+@@$$+oo&*;@;+;&*o+$@@$$++o&*. oX    ",
"    .o X-@+oo+*o+%#=+=oo&*o+@@$$+oo&*o;@;o&*o@#--##@$+&*. oX    ",
"    .o X-@+oo+*o+$%@=+%o&*o+@@$$+oo&*;@;+;&*o+++oooooo&*. oX    ",
"    .o X-#@@$+*o+=#=+=oo&*o+@@$$+oo&*o;@;o&*o+$@@$$++o&*. oX    ",
"    .o X##@@$+*o+$%@=o%o&*o+@@$$+oo&*;@;o;&*&+$@@$$++o&*. oX    ",
"    .o X@@$$++*&oooooo&&&*ooo+++o&&&*X;&;&&*&o+++++++o&*. oX    ",
"    .o X************************************************. oX    ",
"    .o X................................................. oX    ",
"    .o                                                    oX    ",
"    .ooooooooooooooooooooooooooooooooooooooooooooooooooooooX    ",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
"                                                                "};
