$ $XConsortium: Uil.msg /main/4 1996/08/19 11:53:43 pascale $
$set UIL_SET1

UIL_0 duplicate option "%s" was ignored
UIL_1 unknown option "%s" was ignored
UIL_2 additional UIL source file: %s was ignored
UIL_3 error opening source file: %s
UIL_4 error reading next line of source file: %s
UIL_5 Internal error: %s
UIL_6 line truncated at %d characters
UIL_7 value of %s is out of range %s
UIL_8 %s not terminated %s
UIL_9 unprintable character \\%d\\ ignored
UIL_10 unknown sequence "%s" ignored
UIL_11 unknown escape sequence "\\%c" - \\ ignored
UIL_12 name exceeds %d characters - truncated to: %s
UIL_13 compiler ran out of virtual memory
UIL_14 unexpected %s token found - parsing resumes after "%c"
UIL_15 %s %s must be defined before this reference
UIL_16 context requires a %s - %s was specified
UIL_17 %s is not implemented yet
UIL_18 found %s value when expecting %s value
UIL_19 the %s %s is not supported for the %s object
UIL_20 this %s %s supersedes a previous definition in this %s %s
UIL_21 name %s previously defined as %s
UIL_22 value used in this context must be private
UIL_23 procedure %s was previously declared with %d arguments
UIL_24 found %s value - procedure %s argument must be %s value
UIL_25 found %s %s when expecting %s %s
UIL_26 %s %s was never defined
UIL_27 %s %s already specified for this %s %s
UIL_28 %s item not allowed in %s %s
UIL_29 compilation terminated - please fix previous errors
UIL_30 internal error - please submit defect report

$quote "
UIL_31 " "
$quote

UIL_32 %s missing following "%s" option
UIL_33 error opening listing file: %s
UIL_34 error writing to listing file: %s
UIL_35 invalid module structure - check UIL module syntax
UIL_36 too many source files open: %s
UIL_37 source line contains a null character
UIL_38 errors: %d  warnings: %d  informationals: %d
UIL_39 error opening UID file: %s
UIL_40 no UID file was produced
UIL_41 creation procedure is not supported by the %s widget
UIL_42 creation procedure is not allowed in a %s widget reference
UIL_43 creation procedure is required in a %s widget declaration
UIL_44 a NULL character in a string is not supported
UIL_45 widget %s is part of a circular definition
UIL_46 no source file specified
UIL_47 %s %s supports only a single %s %s
UIL_48 %s widget supports only a single control
UIL_49 unknown character set
UIL_50 place names clause before other module clauses
UIL_51 color letter string must be a single character
UIL_52 color letter used for prior color in this table
UIL_53 row %d must have same width as row 1
UIL_54 row %d, column %d: letter "%c" not in color table
UIL_55 too many %ss in %s, limit is %d
UIL_56 Subqualifier not allowed with negated qualifier
UIL_57 %s gadget is not supported - %s widget will be used instead
UIL_58 %s type is not valid for %s
UIL_59 support for this character set may be removed in a future release
UIL_60 the %s constraint is not supported for the %s %s
UIL_61 too many "%s" options, limit is %d
UIL_62 error closing source file: %s
UIL_63 the %s value is circularly defined
UIL_64 overriding built-in name %s
UIL_65 the %s argument does not support enumerated values
UIL_66 the %s argument does not support the %s enumerated value
UIL_67 $LANG contains an unknown character set
UIL_68 the %s object's controls hierarchy contains a reference to itself
UIL_69 value %s is too large for context buffer
UIL_70 forward referencing is not allowed for %s
UIL_71 cannot convert %s type to %s type
UIL_72 %s is invalid
UIL_V2_73 error reading binary database
UIL_V2_74 binary database compiled with a future version
UIL_V2_75 error opening database file: %s
UIL_V2_76 error writing UID file: %s
UIL_V2_77 '%s' is an unknown Toolkit class record name
UIL_78 invalid include file name
UIL_V2_79 incompatible unit types for arithmetic operation
UIL_V2_80 %s used as charset name; %s used as charset component

$set UIL_VALUES
UIL_VAL_0 ** error **
UIL_VAL_1 ** unknown **

$set UIL_SET_MISC

UIL_INF Info: 
UIL_WAR Warning: 
UIL_ERR Error: 
UIL_SEV Severe: 
UIL_MISC_0 \t\t line: %d  file: %s
UIL_MISC_1 \t\t line: %d  position: %d  file: %s
