/*
 * CDE - Common Desktop Environment
 *
 * Copyright (c) 1993-2012, The Open Group. All rights reserved.
 *
 * These libraries and programs are free software; you can
 * redistribute them and/or modify them under the terms of the GNU
 * Lesser General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * These libraries and programs are distributed in the hope that
 * they will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with these libraries and programs; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301 USA
 */
/* $XConsortium: DtStrDefs.h /main/4 1996/03/25 11:18:44 rswiston $ */
/* This file is automatically generated. */
/* Do not edit. */

#ifndef _DtStrDefs_h_
#define _DtStrDefs_h_

#ifdef DTSTRINGDEFINES
#define DtCAlternateImage "AlternateImage"
#define DtCBehavior "Behavior"
#define DtRBehavior "Behavior"
#define DtCBorderType "BorderType"
#define DtRBorderType "BorderType"
#define DtCBoxType "BoxType"
#define DtRBoxType "BoxType"
#define DtCButtonLabelStrings "ButtonLabelStrings"
#define DtCControlType "ControlType"
#define DtRControlType "ControlType"
#define DtCCursorFont "CursorFont"
#define DtCDrawShadow "DrawShadow"
#define DtCDropAction "DropAction"
#define DtCDropCallback "DropCallback"
#define DtCFillMode "FillMode"
#define DtRFillMode "FillMode"
#define DtCFormat "Format"
#define DtCHighResFontList "HighResFontList"
#define DtCLowResFontList "LowResFontList"
#define DtCMediumResFontList "MediumResFontList"
#define DtCPixmapPosition "PixmapPosition"
#define DtRPixmapPosition "PixmapPosition"
#define DtCPushArgument "PushArgument"
#define DtCPushFunction "PushFunction"
#define DtCStringPosition "StringPosition"
#define DtRStringPosition "StringPosition"
#define DtCSubpanel "Subpanel"
#define DtCTitleSpacing "TitleSpacing"
#define DtCTitlePosition "TitlePosition"
#define DtRTitlePosition "TitlePosition"
#define DtCUnderline "Underline"
#define DtNalternateImage "alternateImage"
#define DtNbehavior "behavior"
#define DtNbottomInset "bottomInset"
#define DtNborderType "borderType"
#define DtNboxType "boxType"
#define DtNbuttonLabelStrings "buttonLabelStrings"
#define DtNchime "chime"
#define DtNclientTimeoutInterval "clientTimeoutInterval"
#define DtNclockInterval "clockInterval"
#define DtNcontrolType "controlType"
#define DtNcursorFont "cursorFont"
#define DtNdrawShadow "drawShadow"
#define DtNdropAction "dropAction"
#define DtNdropCallback "dropCallback"
#define DtNfileName "fileName"
#define DtNfillMode "fillMode"
#define DtNformat "format"
#define DtNheightIncrement "heightIncrement"
#define DtNhighResFontList "highResFontList"
#define DtNimageName "imageName"
#define DtNleftInset "leftInset"
#define DtNlowResFontList "lowResFontList"
#define DtNmediumResFontList "mediumResFontList"
#define DtNmonitorTime "monitorTime"
#define DtNpixmapForeground "pixmapForeground"
#define DtNpixmapBackground "pixmapBackground"
#define DtNmaxPixmapWidth "maxPixmapWidth"
#define DtNmaxPixmapHeight "maxPixmapHeight"
#define DtNpixmapPosition "pixmapPosition"
#define DtNpushArgument "pushArgument"
#define DtNpushButtonClickTime "pushButtonClickTime"
#define DtNpushFunction "pushFunction"
#define DtNrightInset "rightInset"
#define DtNstringPosition "stringPosition"
#define DtNsubpanel "subpanel"
#define DtNresolution "resolution"
#define DtNtitleSpacing "titleSpacing"
#define DtNtitlePosition "titlePosition"
#define DtNtitleAlignment "titleAlignment"
#define DtNtopInset "topInset"
#define DtNunderline "underline"
#define DtNuseEmbossedText "useEmbossedText"
#define DtNwaitingBlinkRate "waitingBlinkRate"
#define DtNwidthIncrement "widthIncrement"
#define DtSicon_label "icon_label"
#define DtSicon_button "icon_button"
#define DtSicon_toggle "icon_toggle"
#define DtSicon_drag "icon_drag"
#define DtSwork_area "work_area"
#define DtStitle_area "title_area"
#define DtSseparator "separator"
#define DtSbutton "button"
#define DtSfill_none "fill_none"
#define DtSfill_parent "fill_parent"
#define DtSfill_transparent "fill_transparent"
#define DtSfill_self "fill_self"
#define DtSpixmap_top "pixmap_top"
#define DtSpixmap_bottom "pixmap_bottom"
#define DtSpixmap_left "pixmap_left"
#define DtSpixmap_right "pixmap_right"
#define DtSstring_top "string_top"
#define DtSstring_bottom "string_bottom"
#define DtSstring_left "string_left"
#define DtSstring_right "string_right"
#define DtStitle_top "title_top"
#define DtStitle_bottom "title_bottom"
#define DtNformatJP "formatJP"
#define DtCFormatJP "FormatJP"
#else
#ifndef _DtConst
#define _DtConst /**/
#endif
extern _DtConst char _DtStrings[];
#ifndef DtCAlternateImage
#define DtCAlternateImage ((char*)&_DtStrings[0])
#endif
#ifndef DtCBehavior
#define DtCBehavior ((char*)&_DtStrings[15])
#endif
#ifndef DtRBehavior
#define DtRBehavior ((char*)&_DtStrings[24])
#endif
#ifndef DtCBorderType
#define DtCBorderType ((char*)&_DtStrings[33])
#endif
#ifndef DtRBorderType
#define DtRBorderType ((char*)&_DtStrings[44])
#endif
#ifndef DtCBoxType
#define DtCBoxType ((char*)&_DtStrings[55])
#endif
#ifndef DtRBoxType
#define DtRBoxType ((char*)&_DtStrings[63])
#endif
#ifndef DtCButtonLabelStrings
#define DtCButtonLabelStrings ((char*)&_DtStrings[71])
#endif
#ifndef DtCControlType
#define DtCControlType ((char*)&_DtStrings[90])
#endif
#ifndef DtRControlType
#define DtRControlType ((char*)&_DtStrings[102])
#endif
#ifndef DtCCursorFont
#define DtCCursorFont ((char*)&_DtStrings[114])
#endif
#ifndef DtCDrawShadow
#define DtCDrawShadow ((char*)&_DtStrings[125])
#endif
#ifndef DtCDropAction
#define DtCDropAction ((char*)&_DtStrings[136])
#endif
#ifndef DtCDropCallback
#define DtCDropCallback ((char*)&_DtStrings[147])
#endif
#ifndef DtCFillMode
#define DtCFillMode ((char*)&_DtStrings[160])
#endif
#ifndef DtRFillMode
#define DtRFillMode ((char*)&_DtStrings[169])
#endif
#ifndef DtCFormat
#define DtCFormat ((char*)&_DtStrings[178])
#endif
#ifndef DtCHighResFontList
#define DtCHighResFontList ((char*)&_DtStrings[185])
#endif
#ifndef DtCLowResFontList
#define DtCLowResFontList ((char*)&_DtStrings[201])
#endif
#ifndef DtCMediumResFontList
#define DtCMediumResFontList ((char*)&_DtStrings[216])
#endif
#ifndef DtCPixmapPosition
#define DtCPixmapPosition ((char*)&_DtStrings[234])
#endif
#ifndef DtRPixmapPosition
#define DtRPixmapPosition ((char*)&_DtStrings[249])
#endif
#ifndef DtCPushArgument
#define DtCPushArgument ((char*)&_DtStrings[264])
#endif
#ifndef DtCPushFunction
#define DtCPushFunction ((char*)&_DtStrings[277])
#endif
#ifndef DtCStringPosition
#define DtCStringPosition ((char*)&_DtStrings[290])
#endif
#ifndef DtRStringPosition
#define DtRStringPosition ((char*)&_DtStrings[305])
#endif
#ifndef DtCSubpanel
#define DtCSubpanel ((char*)&_DtStrings[320])
#endif
#ifndef DtCTitleSpacing
#define DtCTitleSpacing ((char*)&_DtStrings[329])
#endif
#ifndef DtCTitlePosition
#define DtCTitlePosition ((char*)&_DtStrings[342])
#endif
#ifndef DtRTitlePosition
#define DtRTitlePosition ((char*)&_DtStrings[356])
#endif
#ifndef DtCUnderline
#define DtCUnderline ((char*)&_DtStrings[370])
#endif
#ifndef DtNalternateImage
#define DtNalternateImage ((char*)&_DtStrings[380])
#endif
#ifndef DtNbehavior
#define DtNbehavior ((char*)&_DtStrings[395])
#endif
#ifndef DtNbottomInset
#define DtNbottomInset ((char*)&_DtStrings[404])
#endif
#ifndef DtNborderType
#define DtNborderType ((char*)&_DtStrings[416])
#endif
#ifndef DtNboxType
#define DtNboxType ((char*)&_DtStrings[427])
#endif
#ifndef DtNbuttonLabelStrings
#define DtNbuttonLabelStrings ((char*)&_DtStrings[435])
#endif
#ifndef DtNchime
#define DtNchime ((char*)&_DtStrings[454])
#endif
#ifndef DtNclientTimeoutInterval
#define DtNclientTimeoutInterval ((char*)&_DtStrings[460])
#endif
#ifndef DtNclockInterval
#define DtNclockInterval ((char*)&_DtStrings[482])
#endif
#ifndef DtNcontrolType
#define DtNcontrolType ((char*)&_DtStrings[496])
#endif
#ifndef DtNcursorFont
#define DtNcursorFont ((char*)&_DtStrings[508])
#endif
#ifndef DtNdrawShadow
#define DtNdrawShadow ((char*)&_DtStrings[519])
#endif
#ifndef DtNdropAction
#define DtNdropAction ((char*)&_DtStrings[530])
#endif
#ifndef DtNdropCallback
#define DtNdropCallback ((char*)&_DtStrings[541])
#endif
#ifndef DtNfileName
#define DtNfileName ((char*)&_DtStrings[554])
#endif
#ifndef DtNfillMode
#define DtNfillMode ((char*)&_DtStrings[563])
#endif
#ifndef DtNformat
#define DtNformat ((char*)&_DtStrings[572])
#endif
#ifndef DtNheightIncrement
#define DtNheightIncrement ((char*)&_DtStrings[579])
#endif
#ifndef DtNhighResFontList
#define DtNhighResFontList ((char*)&_DtStrings[595])
#endif
#ifndef DtNimageName
#define DtNimageName ((char*)&_DtStrings[611])
#endif
#ifndef DtNleftInset
#define DtNleftInset ((char*)&_DtStrings[621])
#endif
#ifndef DtNlowResFontList
#define DtNlowResFontList ((char*)&_DtStrings[631])
#endif
#ifndef DtNmediumResFontList
#define DtNmediumResFontList ((char*)&_DtStrings[646])
#endif
#ifndef DtNmonitorTime
#define DtNmonitorTime ((char*)&_DtStrings[664])
#endif
#ifndef DtNpixmapForeground
#define DtNpixmapForeground ((char*)&_DtStrings[676])
#endif
#ifndef DtNpixmapBackground
#define DtNpixmapBackground ((char*)&_DtStrings[693])
#endif
#ifndef DtNpixmapPosition
#define DtNpixmapPosition ((char*)&_DtStrings[710])
#endif
#ifndef DtNpushArgument
#define DtNpushArgument ((char*)&_DtStrings[725])
#endif
#ifndef DtNpushButtonClickTime
#define DtNpushButtonClickTime ((char*)&_DtStrings[738])
#endif
#ifndef DtNpushFunction
#define DtNpushFunction ((char*)&_DtStrings[758])
#endif
#ifndef DtNrightInset
#define DtNrightInset ((char*)&_DtStrings[771])
#endif
#ifndef DtNstringPosition
#define DtNstringPosition ((char*)&_DtStrings[782])
#endif
#ifndef DtNsubpanel
#define DtNsubpanel ((char*)&_DtStrings[797])
#endif
#ifndef DtNresolution
#define DtNresolution ((char*)&_DtStrings[806])
#endif
#ifndef DtNtitleSpacing
#define DtNtitleSpacing ((char*)&_DtStrings[817])
#endif
#ifndef DtNtitlePosition
#define DtNtitlePosition ((char*)&_DtStrings[830])
#endif
#ifndef DtNtitleAlignment
#define DtNtitleAlignment ((char*)&_DtStrings[844])
#endif
#ifndef DtNtopInset
#define DtNtopInset ((char*)&_DtStrings[859])
#endif
#ifndef DtNunderline
#define DtNunderline ((char*)&_DtStrings[868])
#endif
#ifndef DtNuseEmbossedText
#define DtNuseEmbossedText ((char*)&_DtStrings[878])
#endif
#ifndef DtNwaitingBlinkRate
#define DtNwaitingBlinkRate ((char*)&_DtStrings[894])
#endif
#ifndef DtNwidthIncrement
#define DtNwidthIncrement ((char*)&_DtStrings[911])
#endif
#ifndef DtSicon_label
#define DtSicon_label ((char*)&_DtStrings[926])
#endif
#ifndef DtSicon_button
#define DtSicon_button ((char*)&_DtStrings[937])
#endif
#ifndef DtSicon_toggle
#define DtSicon_toggle ((char*)&_DtStrings[949])
#endif
#ifndef DtSicon_drag
#define DtSicon_drag ((char*)&_DtStrings[961])
#endif
#ifndef DtSwork_area
#define DtSwork_area ((char*)&_DtStrings[971])
#endif
#ifndef DtStitle_area
#define DtStitle_area ((char*)&_DtStrings[981])
#endif
#ifndef DtSseparator
#define DtSseparator ((char*)&_DtStrings[992])
#endif
#ifndef DtSbutton
#define DtSbutton ((char*)&_DtStrings[1002])
#endif
#ifndef DtSfill_none
#define DtSfill_none ((char*)&_DtStrings[1009])
#endif
#ifndef DtSfill_parent
#define DtSfill_parent ((char*)&_DtStrings[1019])
#endif
#ifndef DtSfill_transparent
#define DtSfill_transparent ((char*)&_DtStrings[1031])
#endif
#ifndef DtSfill_self
#define DtSfill_self ((char*)&_DtStrings[1048])
#endif
#ifndef DtSpixmap_top
#define DtSpixmap_top ((char*)&_DtStrings[1058])
#endif
#ifndef DtSpixmap_bottom
#define DtSpixmap_bottom ((char*)&_DtStrings[1069])
#endif
#ifndef DtSpixmap_left
#define DtSpixmap_left ((char*)&_DtStrings[1083])
#endif
#ifndef DtSpixmap_right
#define DtSpixmap_right ((char*)&_DtStrings[1095])
#endif
#ifndef DtSstring_top
#define DtSstring_top ((char*)&_DtStrings[1108])
#endif
#ifndef DtSstring_bottom
#define DtSstring_bottom ((char*)&_DtStrings[1119])
#endif
#ifndef DtSstring_left
#define DtSstring_left ((char*)&_DtStrings[1133])
#endif
#ifndef DtSstring_right
#define DtSstring_right ((char*)&_DtStrings[1145])
#endif
#ifndef DtStitle_top
#define DtStitle_top ((char*)&_DtStrings[1158])
#endif
#ifndef DtStitle_bottom
#define DtStitle_bottom ((char*)&_DtStrings[1168])
#endif
#ifndef DtNmaxPixmapWidth
#define DtNmaxPixmapWidth ((char*)&_DtStrings[1181])
#endif
#ifndef DtNmaxPixmapHeight
#define DtNmaxPixmapHeight ((char*)&_DtStrings[1196])
#endif
#endif
extern _DtConst char _AIXJPStrings[];
#ifndef DtNformatJP
#define DtNformatJP ((char*)&_AIXJPStrings[0])
#endif
#ifndef DtCFormatJP
#define DtCFormatJP ((char*)&_AIXJPStrings[9])
#endif

/*
 * Resource name mapping to Xm prefix.  If Motif defines on of these
 * resources, the redefined resource definition should be removed.
 */
#define XmCAlternateImage	DtCAlternateImage
#define XmCBehavior		DtCBehavior
#define XmRBehavior		DtRBehavior
#define XmCBorderType		DtCBorderType
#define XmRBorderType		DtRBorderType
#define XmCBoxType		DtCBoxType
#define XmRBoxType		DtRBoxType
#define XmCButtonLabelStrings	DtCButtonLabelStrings
#define XmCControlType		DtCControlType
#define XmRControlType		DtRControlType
#define XmCCursorFont		DtCCursorFont
#define XmCDrawShadow		DtCDrawShadow
#define XmCDropAction		DtCDropAction
#define XmCDropCallback		DtCDropCallback
#define XmCFillMode		DtCFillMode
#define XmRFillMode		DtRFillMode
#define XmCFormat		DtCFormat
#define XmCHighResFontList	DtCHighResFontList
#define XmCLowResFontList	DtCLowResFontList
#define XmCMediumResFontList	DtCMediumResFontList
#define XmCPixmapPosition	DtCPixmapPosition
#define XmRPixmapPosition	DtRPixmapPosition
#define XmCPushArgument		DtCPushArgument
#define XmCPushFunction		DtCPushFunction
#define XmCStringPosition	DtCStringPosition
#define XmRStringPosition	DtRStringPosition
#define XmCSubpanel		DtCSubpanel
#define XmCTitleSpacing		DtCTitleSpacing
#define XmCTitlePosition	DtCTitlePosition
#define XmRTitlePosition	DtRTitlePosition
#define XmCUnderline		DtCUnderline
#define XmNalternateImage	DtNalternateImage
#define XmNbehavior		DtNbehavior
#define XmNbottomInset		DtNbottomInset
#define XmNborderType		DtNborderType
#define XmNboxType		DtNboxType
#define XmNbuttonLabelStrings	DtNbuttonLabelStrings
#define XmNchime		DtNchime
#define XmNclientTimeoutInterval DtNclientTimeoutInterval
#define XmNclockInterval	DtNclockInterval
#define XmNcontrolType		DtNcontrolType
#define XmNcursorFont		DtNcursorFont
#define XmNdrawShadow		DtNdrawShadow
#define XmNdropAction		DtNdropAction
#define XmNdropCallback		DtNdropCallback
#define XmNfileName		DtNfileName
#define XmNfillMode		DtNfillMode
#define XmNformat		DtNformat
#define XmNheightIncrement	DtNheightIncrement
#define XmNhighResFontList	DtNhighResFontList
#define XmNimageName		DtNimageName
#define XmNleftInset		DtNleftInset
#define XmNlowResFontList	DtNlowResFontList
#define XmNmediumResFontList	DtNmediumResFontList
#define XmNmonitorTime		DtNmonitorTime
#define XmNpixmapForeground	DtNpixmapForeground
#define XmNpixmapBackground	DtNpixmapBackground
#define XmNmaxPixmapWidth	DtNmaxPixmapWidth
#define XmNmaxPixmapHeight	DtNmaxPixmapHeight
#define XmNpixmapPosition	DtNpixmapPosition
#define XmNpushArgument		DtNpushArgument
#define XmNpushButtonClickTime	DtNpushButtonClickTime
#define XmNpushFunction		DtNpushFunction
#define XmNrightInset		DtNrightInset
#define XmNstringPosition	DtNstringPosition
#define XmNsubpanel		DtNsubpanel
#define XmNresolution		DtNresolution
#define XmNtitleSpacing		DtNtitleSpacing
#define XmNtitlePosition	DtNtitlePosition
#define XmNtitleAlignment	DtNtitleAlignment
#define XmNtopInset		DtNtopInset
#define XmNunderline		DtNunderline
#define XmNuseEmbossedText	DtNuseEmbossedText
#define XmNwaitingBlinkRate	DtNwaitingBlinkRate
#define XmNwidthIncrement	DtNwidthIncrement
#define XmNformatJP DtNformatJP
#define XmCFormatJP DtCFormatJP

/*
 * String defines for converter string names.
 */
#define STR_ICON_LABEL          DtSicon_label
#define STR_ICON_BUTTON         DtSicon_button
#define STR_ICON_TOGGLE         DtSicon_toggle
#define STR_ICON_DRAG           DtSicon_drag
#define STR_WORK_AREA           DtSwork_area
#define STR_TITLE_AREA          DtStitle_area
#define STR_SEPARATOR           DtSseparator
#define STR_BUTTON              DtSbutton
#define STR_FILL_NONE           DtSfill_none
#define STR_FILL_PARENT         DtSfill_parent
#define STR_FILL_TRANSPARENT    DtSfill_transparent
#define STR_FILL_SELF           DtSfill_self
#define STR_PIXMAP_TOP          DtSpixmap_top
#define STR_PIXMAP_BOTTOM       DtSpixmap_bottom
#define STR_PIXMAP_LEFT         DtSpixmap_left
#define STR_PIXMAP_RIGHT        DtSpixmap_right
#define STR_STRING_TOP          DtSstring_top
#define STR_STRING_BOTTOM       DtSstring_bottom
#define STR_STRING_LEFT         DtSstring_left
#define STR_STRING_RIGHT        DtSstring_right
#define STR_TITLE_TOP           DtStitle_top
#define STR_TITLE_BOTTOM        DtStitle_bottom
#endif
