/* XPM */
/* $XConsortium: dtmail_nonewmail.l.pm /main/3 1995/07/18 16:11:06 drk $ */
static char * dtmail_nonewmail [] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray5     m black c #737373737373",
"o	s iconColor2	m white	c white",
"O    s iconGray6     m black c #636363636363",
"+    s iconGray2     m white c #bdbdbdbdbdbd",
"@    s iconGray1     m white c #dededededede",
"#    s iconGray3     m white c #adadadadadad",
"$    s iconGray4     m white c #949494949494",
"%    s topShadowColor m white c #bdbdbdbdbdbd",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"           ..........................           ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"         .XooooooooooooooooooooooooooX.         ",
"        .XoO+@@@@@@@@@@@@@@@@@@@@@@@OoX.        ",
"       .XoXO+@@@@@@@@@@@@@@@@@@@@@@@O@oX.       ",
"      .XoX#O++@@@@@@@@@@@@@@@@@@@@@@Oo@oX.      ",
"     .XoX#XO++@@@@@@@@@@@@@@@@@@@@@@O@o@oX.     ",
"    .XoX#X#O+++@@@@@@@@@@@@@@@@@@@@@Oo@o@oX.    ",
"   .XoX#X#XOOOOOOOOOOOOOOOOOOOOOOOOOO@o@o@oX.   ",
"  .XoX#X#X#O$$##@ooooooooooooooooooooO@o@o@oX.  ",
" .XoX#X#X#O$$##@@oooooooooooooooooooooO@o@o@oX. ",
".XoXXXXXXXXXXX@@oooooooooooooooooXXXXXXXXXXXXoX%",
".XooooooooooooX@ooooooooooooooooXoooooooooooooX%",
".XXoooo@o@o@oooXoooooooooooooooXo@o@o@o@o+@$+XX%",
".X$Xoooo@o@o@ooXoooooooooooooooXoo@o@o@o@@#+X+X%",
".XXoooo@o@o@o@oXoooooooooooooooXo@o@o@o@o+@$+XX%",
".X$Xoooo@o@o@ooXoooooooooooooooXoo@o@o@o@@#+X+X%",
".XXoooo@o@o@o@ooXoooooooooooooXoo@o@o@o@o+@$+XX%",
".X$Xoooo@o@o@o@ooXXXXXXXXXXXXXoo@o@o@o@o@@#+X+X%",
".XXoooo@o@o@o@o@ooooooooooooooo@o@o@o@o@o+@$+XX%",
".X$Xoooo@o@o@o@o@o@o@o@o@o@o@o@o@o@o@o@o@@#+X+X%",
".XXoooo@ooo@o@o@o@o@o@o@o@o@o@o@o@o@o@o@o+@X+XX%",
".X$X@$@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+@+X+X+X%",
" .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX% ",
"  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
