/* XPM */
/* $XConsortium: dtmail_newmail.l.pm /main/3 1995/07/18 16:10:38 drk $ */
static char * dtmail_newmail [] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X    s iconGray1     m white c #dededededede",
"o	s iconColor2	m white	c white",
"O	s iconColor5	m black	c blue",
"+    s bottomShadowColor m black c #636363636363",
"@    s iconGray8     m black c #212121212121",
"#    s iconGray3     m white c #adadadadadad",
"$    s iconGray5     m black c #737373737373",
"%    s topShadowColor m white c #bdbdbdbdbdbd",
"&    s iconGray4     m white c #949494949494",
"*    s iconGray2     m white c #bdbdbdbdbdbd",
/* pixels */
"                                                ",
"                              .                 ",
"                             .X.                ",
"                            .XoX.               ",
"                           .ooooo.              ",
"                          .XoXOXoX.             ",
"                         .oooOoOooo.            ",
"                        .XoXOXOXOXoX.           ",
"      +++++++++++++++++.oooooOoOooooo.+++++     ",
"      +@@@@@@@@@@@@@@@.XoXoXoXOXoXoXoX.@@@+     ",
"      +.#############$ooooooooooooooooo$$@+     ",
"     +..$$$$$$$$$$$$.XoXoXoXoXoXoXoXoXoX...+    ",
"     +.############.ooooooooooooooooooooo..+    ",
"    ++.$$$$$$$$$$$.XoXoXoXoXoXoXoXoXoXoXoX.++   ",
"    +.###########.ooooooooooooooooooooooooo.%   ",
"    +.&#&#&#&#&#.XoXoXoXoXoXoXoXoXoXoXoXoX..%   ",
"    +.#..#.#.##.ooooooooooooooooooooooooo.$.%   ",
"    +.&#&#&#&#.XoXoXoXoXoXoXoXoXoXoXoXoX.$&.%   ",
"    +.#.#..#..oo$ooooooooooooo$oooooooo.$O$.%   ",
"    +.&#&#&#.Xo$oXoXoXoXoXoXoXoXoXoXoX.$O$&.%   ",
"    +.#####.oooo$ooooooooooo$ooo$oooo.$O$O#.%   ",
"    +.&#&#.Xo$o$oXoXoXoXoXo$oXo$oXoX.$&$&#&.%   ",
"    +.###.oo$o$oooooooooooooooooooo.$&$####.%   ",
"    +.&#&#.Xo$oXoXoXoXoXo$oXo$oXoX.$&$&#&#&.%   ",
"   +..#####.oooooooooooo$ooo$oooo.$&$######.%   ",
"  +.o.&#&#&#.XoXoXoXoXo$oXoXoXoX.$&$&#&#&#&..%  ",
" +.o..#$#$#$#.**oooooooooo$oooo.$&$########...% ",
"+.o............***oXoXoXo$oXoX.$&............o.%",
"+.oooooooooooo..**ooooooooooo.$&@ooooooooooooo.%",
"+.$ooooXoXoXooo..**XoXoXoXoX.$&.oXoXoXoXoX*X$&.%",
"+.*#ooooXoXoXoo.$.*oooooooo.$&$.ooXoXoXoX*X*&$.%",
"+.$ooooXoXoXoXo.&$.*oXoXoX.$&$&.oXoXoXoXo**X$&.%",
"+.*#ooooXoXoXoo.$&$.XoooX.$&$&$.ooXoXoXoX*X*&$.%",
"+.$ooooXoXoXoXoo.$&$.**#.$&$&$.ooXoXoXoXoX*X$&.%",
"+.*#ooooXoXoXoXoo.............ooXoXoXoXoX*X*&$.%",
"+.$ooooXoXoXoXoXoooooooooooooooXoXoXoXoXoX*X$&.%",
"+.##ooooXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX*X*&$.%",
"+.$o#ooXoooXoXoXoXoXoXoXoXoXoXoXoXoXoXoXoX*X$&.%",
"+.#$X$X$X$X$X$X$X$X$X$X$*$X$X$X$X$X$X$X$X$*$&$.%",
" +............................................% ",
"  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
