/* XPM */
/* $XConsortium: dtmail_newmail.m.pm /main/3 1995/07/18 16:10:48 drk $ */
static char * 32_m_xpm[] = {
"32 32 11 1",
" 	s None	c None",
".	c #000000000000",
"X	c white",
"o	c #3E3E57578C8C",
"O	c #B7B7B7B7B7B7",
"+	c #CCCCCCCCCCCC",
"@	c red",
"#	c #E5E5E5E5E5E5",
"$	c #8C8C8C8C8C8C",
"%	c #7F7F7F7F7F7F",
"&	c #C3C3C3C3C3C3",
"                   .            ",
"                  .X.           ",
"                 .XoX.          ",
"                .XooOX.         ",
"               .XXXOoXX.        ",
"              .XX+@XXXXX.       ",
"             .XX+@+XXXXXX.      ",
"            .XXX@+XXXXXXXX.     ",
"           .XXXXXXXXXXXXXXX.    ",
" ..........XXXXXXXXXXXXXXXXX... ",
" .#######.XXXXXXXXXXXXXXXXX.##. ",
" .$O$O$O.XXXXXXXXXX$XXXXXX.O$O. ",
" .#####.XXXXXXXXXX$XXXXXX.####. ",
" .OOOO.XXXXXXXXXX$XX$XXX.%O%OO. ",
" .OOO.XX$XXXXXXXXXX$XXX.%O%OOO. ",
".XOO.XX$X$XXXXX$XXXXXX.%O%OOOO#.",
".XO.XX$XXXXXXX$XX$XXX.%O%OOOOO#.",
".XOO.XX$XXXXX$XX$XXX.%O%OOOOOO#.",
".XOOO.XXXXXXXXX$XXX.%O%OOOOOOO#.",
".XOOOO.XXXXXXX$XXX.%O%OOOOOOOO#.",
".X$$$$$.$OXXXXXXX.%O%OOOOOOOOO#.",
"&XXXXXXX.$OXXXXX.%O%OOOOXXXXXX#.",
"$XXXXXXX#.OXXXX.%O%OOOOXXXX#+#$.",
"&XXXXXXX#$.XXX.%O%OOOOOXXXXX#&#.",
"$#XXXXXX#$$.X.%O%OOOOOOXXXX#+#$.",
"&XXXXXXX#$$$.$$$$$$$$$$XXXXX#&#.",
"$#XXXXXXX##############XXXX#+#$.",
"&XXXXXXXXXXXXXXXXXXXXXXXXX#X#&#.",
"$#X#X#X#X#X#X#X#X#X#X#X#X#X#&#$.",
"&$&$&$&$&$#$#$#$#$#$#$#$#$#$#$#.",
" .............................. ",
"                                "};
