#!/bin/csh -f
set echo
#
# A script that aids in debugging and testing dtmail
#
if ( `uname -s` != SunOS ) then
        echo "Only support SunOS"
        exit 1
endif


setenv DT_MAIL /home/dougr/INBOX
setenv DEFAULT_BACKEND Bento
setenv LD_LIBRARY_PATH ../libDtMail:../../../lib/Bento:../../../binstall/lib:$LD_LIBRARY_PATH
ldd -r ./dtmail
exec dtmail &
