/* XPM */
/* $XConsortium: fphelp.pm /main/2 1996/07/23 12:49:25 drk $ */
static char * Ffphelp [] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	s iconGray2	m white	c #c8c8c8c8c8c8",
"o	s topShadowColor	m white	c #c8c8c8c8c8c8",
"O	s iconGray5	m black	c #7d7d7d7d7d7d",
"+	s iconColor1	m black	c black",
"@	s iconGray1	m white	c #e1e1e1e1e1e1",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconGray4	m white	c #969696969696",
"%	s iconGray7	m black	c #4b4b4b4b4b4b",
"&	s iconColor5	m black	c blue",
"*	s iconColor6	m white	c yellow",
"=	s background	m black	c #969696969696",
"-	s iconColor8	m black	c magenta",
";	s iconColor3	m black	c red",
":	s selectColor	m white	c #7d7d7d7d7d7d",
/* pixels */
"   ..........................   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXo   ",
"   .OOOOOOOOOOOOOOOOOOOOOOO+o   ",
"   .OO@@O@@@O@@OOOOOOOOOOOO+o   ",
"   .OOOOOOOOOOOOOOOOOOOOOOO+o   ",
"   .#+++++++++++++++++++++$+o   ",
"   .#+%%%%%%%%%%%%%%%%%%%%$+o   ",
"   .#+%%%%%%%%%%%%%%%%%%%%$+o   ",
"   .#+%%%@@%@@%@%%%%%%%%%%$+o   ",
"   .#+%%%%%%%%%%%%%%%%%%%%$+o   ",
"   .#+%%%%%%%%%%%%%%%%%%%%$+o   ",
"   .#+XXXXXXXXXXXXXXXXXXXX$+o   ",
"   .#+XXXXXXXXXX&&&X+O+%+X$+o   ",
"   .#+XXXXXXXXXX&X&XO+O+OX$+o   ",
"   .#+XXXXXXXXXXXXXXXXXXXX$+o   ",
"   .#+XXX*******XXXXXXXXXX$+o   ",
"   .#+XXXXXXXXXXXXXXXXXXXX$+o   ",
"@X@X@X@X@X@X@X@X@X@X@ooooooooooo",
"====================o===========",
"X$%=%*$%==X##==X%$%=o==++++++=%%",
"%$==X%$$==%%$==$%$$=o===========",
"-&$=$;&$==%%X==$%&$=o===========",
"$-==%$$%==%%%==$%$%=o*=%%%%%%=++",
"====================o===========",
"................................",
":::.$+####%#%%%%#%#%%#%%##O+ :::",
"   .#+XXXXXXXXXXXXXXXXXXXX$+o   ",
"   .#+XXXXXXXXXX&&&&&&&&&X$+o   ",
"   .#+XXXXXXXXXXXXXXXXXXXX$+o   ",
"   .#$$$$$$$$$$$$$$$$$$$$$$+o   ",
"   .++++++++++++++++++++++++o   ",
"   .ooooooooooooooooooooooooo   "};
