/* XPM */
/* $XConsortium: printer.pm /main/2 1996/07/23 12:53:29 drk $ */
static char * Fprnt [] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconGray1	m white	c #e1e1e1e1e1e1",
"X	s iconColor2	m white	c white",
"o	s iconGray2	m white	c #c8c8c8c8c8c8",
"O	s bottomShadowColor	m black	c #646464646464",
"+	s iconGray7	m black	c #4b4b4b4b4b4b",
"@	s topShadowColor	m white	c #c8c8c8c8c8c8",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconGray5	m black	c #7d7d7d7d7d7d",
"%	s iconGray4	m white	c #969696969696",
"&	s iconGray6	m black	c #646464646464",
"*	s iconGray8	m black	c #323232323232",
"=	s selectColor	m white	c #7d7d7d7d7d7d",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"            .XXXXXXXXXXXXXXXXX.                 ",
"            .XXXXXXXXXXXXXXXXX.                 ",
"            XXoooooXooooooooXX.                 ",
"        OOOOXXXXoXoXXoXoXoXXXXXOOOOOOOOOO       ",
"       OXoooXXooooXooooXoooooXX..oooooooo+@     ",
"      OXooo#XXXXXXXXXXXXXXXXXXXX#Xoooooooo+@    ",
"     OXooo$%....................%o.oooooooo+@   ",
"    OXooo+&$$$$$$$$$$$$$$$$$$$$$$$Xooooooooo+@  ",
"    OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*@  ",
"    OX......................................*@  ",
"    OXoo..........................&&&&&&&&&o*@  ",
"    OXoo.%%%oo%%%oo%%%oo%%%oo%%%..&ooo$$$$&o*@  ",
"    OXoo..........................&$$$$$$$&o*@  ",
"    OXooo$$$$$$$$$$$$$$$$$$$$$$$$$&&&&&&&&&o*@  ",
"    OXoooooooooooooooooooooooooooooooooooooo*@  ",
"    OXoooooooooooooooooooooooooooooooooooooo*@  ",
"    OXoooooooooooooooooooooooooooooooooooooo*@  ",
"    OXooo$$$$$$$$$$$$$$$$$$$$$$$$$$$oooooooo*@  ",
"    OXooo$*************************ooooooooo*@  ",
"    OXooo$*%$$$$$$$$$$$$$$$$$$$$$$**oooooooo*@  ",
"    OX****#X$$$$$$$$$$$$$$$$$$$$$$$**********@  ",
"    O@O#+*#########################*++++++*@@@  ",
"      O#+*%$$$$$$$$$$$$$$$$$$$$$$$$*++++++*@    ",
"      O#***********************************@    ",
"      O@@*%$$$$$$$$$$$$$$$$$$$$$$$$*O @@@@@@    ",
"         ***************************O=          ",
"          OOOOOOOOOOOOOOOOOOOOOOOOOOO=          ",
"           ===========================          ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
