/* XPM */
/* $XConsortium: stylemgr.pm /main/2 1996/07/23 12:55:15 drk $ */
/*********************************************************************
*  (c) Copyright 1993, 1994 Hewlett-Packard Company	
*  (c) Copyright 1993, 1994 International Business Machines Corp.
*  (c) Copyright 1993, 1994 Sun Microsystems, Inc.
*  (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
*      Novell, Inc.
**********************************************************************/

static char * Fstyle [] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 26 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s bottomShadowColor	m black	c #646464646464",
"X	c #E0E0E0E0E0E0",
"o	s iconGray1	m white	c #e1e1e1e1e1e1",
"O	s iconGray7	m black	c #4b4b4b4b4b4b",
"+	s topShadowColor	m white	c #c8c8c8c8c8c8",
"@	c #AEAEAEAEAEAE",
"#	s iconGray3	m white	c #afafafafafaf",
"$	s iconColor2	m white	c white",
"%	c #F9F9F9F9F9F9",
"&	s iconGray2	m white	c #c8c8c8c8c8c8",
"*	c #C7C7C7C7C7C7",
"=	s iconColor8	m black	c magenta",
"-	c #FFFF0000ABAB",
";	s selectColor	m white	c #7d7d7d7d7d7d",
":	s iconColor6	m white	c yellow",
"?	s iconColor1	m black	c black",
">	c #FFFF00000202",
",	c #959595959595",
"<	s iconGray5	m black	c #7d7d7d7d7d7d",
"1	c #04040000FFFF",
"2	c #0909FFFF0101",
"3	s iconGray6	m black	c #646464646464",
"4	s iconColor5	m black	c blue",
"5	s iconGray4	m white	c #969696969696",
"6	s iconGray8	m black	c #323232323232",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"      ....................................      ",
"      .XXXXXXXXXXXXXXXXXXoooooooooooooooO+      ",
"      .X@@@@@@@@@@@@@@@@@##############oO+      ",
"      .X@@@@@@@@@@@@@@@@@########o$%%%%%%%o&    ",
"      .X@@XXXXXXXXXXXXXXXoooooo%%&****=-=**%%%  ",
"      .X@@X@@@@@@@@@@Oo@@####%%&*****=-=-O***&%;",
"      .X@@X@@@@@@@@@@Oo@@###%&**::::*-=-=O****?;",
"      .X@@X@@@@@@@@@@Oo@@##%&**::::>**OOO****&?;",
"      .O@@X@@XXXXXX@@Oo@@#%&***::::>********&?;;",
" $$$$$$$O@X@@XOOOOO@@Oo@@%&*****:>>**,???**&?;; ",
" OOOOOO&$OX@@@@@@@@@@Oo@@%**>>*******?<<&*&?;;  ",
"  ;;;;;&&OX@@@@@@@@@@Oo@@%*>>>?**%%**?oo&*&<ooo ",
"      .<<OX@@@@@@@@@@Oo@@%*>>>?*%111**********O;",
"      .$&OXOOOOOOOOOOOoOO%**??**11111*21212***O;",
"      .<<<O&&&&&&&&&&&&&&3&&&&&&4441?*1212&&*O?;",
"      $&&&O55555555555555536&&&&&441?*212O&&5?;;",
"   ooXXXXXXXXoo55555555555566?&&&&&***11O*&6?;; ",
"  o&&&&&&&&&&&&55,,,,,,,,5555???#&&&****&<6;;;  ",
" o&ooo,ooo,ooo,#O,,,,,,,,555555???????????;;    ",
" o&o#@3o##3o#@3#O35555%%%%%%%%%%%%<<<<<<O ;     ",
" o&o##3o##3o##3#O3<555%%???%%???%%?55555O+      ",
" o&o@@3o@@3o#@3#O3<555%?<<<%%?<<<%?<5555O+      ",
" o&o@@3o@@3o#@3#O3<555%?<<5%%?555%?<5555O+      ",
" o&<<<#<<<#<<<&#O3<555??<55%%?555??<5555O+      ",
" o&&&&&&&&&&&&&@O3<5555<<55%%?5555<<5555O+      ",
" o&o*o*o*o*o*o*@O3<55555555%%?5%%%%%%%%+O+      ",
" ooooooooooooXo@O6OOOOOOOOO%%?O%??%%??%?O+      ",
" oooooooooooooo@O. ++++++++%%?+%?+%%?+%?++      ",
" o&o*o*o*o*o*o*@O.;        %%?;??;%%?;??;       ",
" o&*&*&*&*&*&*&@O.;        %%?; ;;%%?; ;;       ",
" o#&@&@&@&@&@&@,O.;        %%?;   %%?; %%%%%    ",
" o#@@@@@@@@@@@@,O.;        %%?;   %%?; %?%?%?   ",
" o5@,@,@,@,@,@,<O.;        %%?;   %%?; ??%???;  ",
" o55,,,,,,,,,,,5O.;      %%%%%%?  %%?;   %?;;;  ",
" o55,,,,,,,,,,<5O.;      ???????;%%%%?   %?;    ",
" o<,<,<,<,<,<,<5O.;       ;;;;;;;?????; %%%?    ",
" o<<<<<<<<<<<<<<O.;               ;;;;;  ???;   ",
"   <<<<<<<<<<<<6..;                       ;;;   ",
"    OOOOOOOOOOO..;;                             ",
"     ...........;;                              ",
"      ;;;;;;;;;;;;                              ",
"                                                ",
"                                                ",
"                                                "};
