/* XPM */
/* $XConsortium: terminal.pm /main/2 1996/07/23 12:55:48 drk $ */
/* Designed by the User Interaction Design Group, Hewlett-Packard */
/* Copyright (c) 1993 Hewlett-Packard */
static char *newterminal32[]={
/* width height ncolors cpp [x_hot y_hot] */
"32 32 22 1 0 0",
/* colors */
"  c none m none s none",
"$ s topShadowColor     m white",
"& s background         m black",
"( s selectColor        m white",
"* s bottomShadowColor  m black",
", s white      c white     m white",
". s iconColor1 c black     m black",
"B s iconColor2 c white     m white",
"4 s iconColor3 c red       m black",
"6 s iconColor4 c green     m white",
"8 s iconColor5 c blue      m black",
"0 s iconColor6 c yellow    m black",
"2 s iconColor7 c cyan      m white",
": s iconColor8 c magenta   m white",
"< s iconGray1 c #e1e1e1e1e1e1 m white",
"> s iconGray2 c #c8c8c8c8c8c8 m white",
"@ s iconGray3 c #afafafafafaf m white",
"D s iconGray4 c #969696969696 m white",
"F s iconGray5 c #7d7d7d7d7d7d m black",
"H s iconGray6 c #646464646464 m black",
"J s iconGray7 c #4b4b4b4b4b4b m black",
"L s iconGray8 c #323232323232 m black",
/* pixels */
"                                ",
"                                ",
"       *****************$       ",
"      *<<<<<<<<<<<<<<<<>*$      ",
"     *,,,,,,,,,,,,,,,,,,,.$     ",
"    *,>>>>>>>>>>>>>>>>>>>>.$    ",
"    *,>HHHHHHHHHHHHHHHHHH>.$    ",
"    *,>H................,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H.J<J<J<J<JJJJJJ.,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H.JD<J<JD<J<JJJJ.,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H.J<D<J<J<DJJJJJ.,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H.JJJJJJJJJJJJJJ.,>.$    ",
"    *,>H................,>.$    ",
"    *,>H,,,,,,,,,,,,,,,,,>.$    ",
"    *D>>>>>>>>>>>>>>>>>>>>.$    ",
"     $....................$     ",
"      $$$..HHHHHHHHHH..$$$      ",
"    *****...FFFFFFFF...$*****   ",
"   *FFFFFFFFFFFFFFFFFFFFFFFF.$  ",
"  *,,,F,F,F,F,F,F,F,F,,F,F,H,.$ ",
" *,,,H,H,H,H,H,H,H,H,H,,H,H,,,.$",
"*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.",
"*DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.",
"*...............................",
" $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
"                                ",
"                                "
};
