$ $TOG: dtcm.msg /main/12 1999/09/20 10:34:50 mgreess $
$quote "

$set 1

1 "dtcm: receptor vacío en recordatorio de correo\n"

2 "Recordatorio- %s"

3 "pm"

4 "am"

5 "pm"

6 "am"

7 "\n\n\
\t** Cita de la Agenda **\n\n\
\tFecha:\t%s\n\
\tInicio:\t%s\n\
\tFinal:\t%s\n\
\tQué hacer:\t%s"

8 "De %2d:%02d"

9 "am"

10 "pm"

11 "am"

12 "pm"

13 "De %02d%02d a %02d%02d"

16 "No puede eliminar la agenda por omisión"

17 "Seleccione un nombre a eliminar"

20 "Fecha no válida en el campo Ir a"

21 "Editar Lista..."

22 "Elementos del Menú Examinar"

23 "Vista previa de la Semana"

24 "Esta Semana"

25 "Siguiente Semana"

26 "Vista previa del Mes"

27 "Siguiente Mes"

28 "Ir a:"

29 "Planificar..."

30 "Correo..."

31 "Agenda Visualizada"

32 "Agendas Visualizadas"

33 "Día"

34 "Semana"

35 "Mes"

36 "Año"

37 "Zona Horaria..."

38 "Lista de Citas..."

40 "Vista"

41 "Buscar..."

42 "Ir a Fecha..."

65 "Archivo"

68 "Imprimir Vista Actual"

69 "Imprimir..."

72 "Opciones..."

73 "Salir"

74 "Cita..."

76 "Editar"

77 "Ayuda"

79 "Tareas..."

80 "Referencia..."

82 "Uso de la Ayuda..."

84 "Mostrar Otra Agenda..."

85 "Comparar Agendas..."

86 "Editor de Menús..."

87 "Examinar"

88 "Hoy"

89 "en quit_handler\n"

90 "Error en la apertura del archivo de Agenda"

91 "rpc.cmsd no responde a su nombre de usuario.\n\
Asegúrese de que el proceso de inetd esté en\n\
ejecución y de que la entrada de inetd.conf\n\
para rpc.cmsd sea correcta para el host."

92 "Nombre del usuario"

93 "Host"

94 "Error de la Agenda"

95 "Continuar"

96 "El archivo de la Agenda no existe para"

97 "El archivo de la Agenda no existe para"

98 "Error de la Agenda"

99 "Continuar"

100 "SIN NOMBRE"

101 "rpc.cmsd no responde a"

102 "rpc.cmsd no responde a su nombre de usuario.\n\
Asegúrese de que el proceso de inetd esté en\n\
ejecución y de que la entrada de inetd.conf\n\
para rpc.cmsd sea correcta para el host."

103 "Nombre del usuario"

104 "Host"

105 "Error de la Agenda"

106 "Continuar"

107 "%s: SIN NOMBRE"

108 "No se ha especificado ninguna Ubicación de la Agenda para"

109 "No se ha especificado ninguna ubicación; añada un nombre de host\n\
a la Vista de Agenda Inicial en Propiedades/Mostrar Valores.\n\
Si ha ejecutado DTCM con la opción -c, verifique si ha especificado\n\
un nombre de host."

110 "Error de la Agenda"

111 "Continuar"

112 "Las versiones de DTCM y rpc.cmsd son distintas."

113 "Agenda"

114 "Enero"

115 "Febrero"

116 "Marzo"

117 "Abril"

118 "Mayo"

119 "Junio"

120 "Julio"

121 "Agosto"

122 "Septiembre"

123 "Octubre"

124 "Noviembre"

125 "Diciembre"

126 "Ene"

127 "Feb"

128 "Mar"

129 "Abr"

130 "May"

131 "Jun"

132 "Jul"

133 "Ago"

134 "Sep"

135 "Oct"

136 "Nov"

137 "Dic"

138 "Dom"

139 "Lun"

140 "Mar"

141 "Mié"

142 "Jue"

143 "Vie"

144 "Sáb"

145 "Dom"

146 "Domingo"

147 "Lunes"

148 "Martes"

149 "Miércoles"

150 "Jueves"

151 "Viernes"

152 "Sábado"

153 "Domingo"

154 "D"

155 "L"

156 "M"

157 "X"

158 "J"

159 "V"

160 "S"

161 "D"

162 "D"

163 "L"

164 "M"

165 "X"

166 "J"

167 "V"

168 "Sá"

169 "D"

170 "DOM"

171 "LUN"

172 "MAR"

173 "MIE"

174 "JUE"

175 "VIE"

176 "SAB"

177 "DOM"

178 "Ya está examinando %s"

186 "Las versiones de DTCM y rpc.cmsd son distintas"

187 "Uso:\n\
\tdtcm_delete [-c agenda] [-d <mm/dd/aa>] [-v vista]\n"

188 "\n\
No se ha podido abrir la agenda %s\n"

189 "DESCONOCIDO"

190 "¿Elemento a suprimir (número)? "

191 "Uso:\n\
\tdtcm_insert [ -c agenda ] [-d <mm/dd/aa>] [ -v vista ]\n"

192 "                   [-w serie qué hacer] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"

193 "Por favor, entre la información para la cita que desee añadir.\n\
Los valores por omisión aparecerán entre paréntesis.\n"

194 "Agenda (%s): "

195 "Fecha (%s): "

196 "Inicio (%s): "

197 "Ha entrado una hora que no es válida.  Pruebe otra vez:\n"

198 "Final (%s): "

199 "Final (%s): "

200 "Una Vez"

201 "Repetir (%s): "

202 "Una Vez"

203 "sin valor por omisión"

204 "Para (%s): "

205 "Qué hacer (puede entrar hasta 5 líneas, use ^D para terminar):\n"

206 "\n\
No se ha podido abrir la agenda %s\n"

207 "Uso:\n\
\tdtcm_lookup [ -c agenda ][ -d <mm/dd/aa> ] [ -v vista ]\n"

208 "\n\
No se ha podido abrir la agenda \"%s\"\n"

209 "DESCONOCIDO"

210 "La cita se planificará en la agenda que está examinando\n\
actualmente.  ¿Aún desea planificarla?"

211 "Entrada de Planificación"

212 "Cita de Planificación"

214 "Cita planificada: %s\n"

218 "Se ha especificado una FECHA no válida"

219 "Se ha especificado una hora de INICIO no válida"

220 "Se ha especificado una fecha FINAL no válida"

221 "El campo FECHA está vacío o falta"

222 "El campo INICIO está vacío o falta"

223 "El campo QUE HACER está vacío o falta"

224 "Existe discrepancia en el campo REPETIR y PARA"

225 "La planificación de la cita se ha cancelado"

226 "Error interno al planificar la cita."

227 "La planificación de la cita se ha cancelado."

228 "Cargar Cita"

229 "Continuar"

230 "Arrastrar Cita"

231 "Seleccionar una cita y ARRASTRAR de nuevo."

232 "Continuar"

234 "Arrastrar Cita"

235 "Continuar"

236 "CitaAgenda"

237 "XCreateBitmapFromData() ha fallado para mapa de bits.\n"

238 "XCreateBitmapFromData() ha fallado para máscara.\n"

239 "DragDrop ha devuelto NULL.\n"

242 "am"

243 "pm"

244 "%s 3:41am"

245 "am"

246 "pm"

247 "Esta cita tiene una hora final anterior\n\
a su hora de inicio. ¿Desea planificarla\n\
en el día siguiente?"

248 "Planificación de Cita"

250 "Siguiente Día"

251 "Autor"

252 "Suprimir Cita"

253 "Seleccionar una cita y SUPRIMIR otra vez."

254 "Continuar"

255 "Suprimir Cita"

256 "Error interno al seleccionar una cita.\n\
La cita no se ha suprimido."

257 "Continuar"

258 "Cambiar Cita"

259 "Seleccione una cita y CAMBIAR otra vez."

260 "Continuar"

261 "Cambiar Cita"

262 "Error interno al seleccionar una cita.\n\
La cita no se ha cambiado."

263 "Continuar"

267 "Cambiar Cita"

268 "Esta cita es parte de unas cadenas de repetición.\n\
¿Desea cambiarla ...?"

270 "Esta Sólo"

271 "Reenviar"

272 "Todo"

273 "Suprimir Cita"

274 "Esta cita es parte de unas cadenas de repetición.\n\
¿Desea suprimirla ...?"

276 "Esta Sólo"

277 "Reenviar"

278 "Todo"

279 "Editor de Citas de la Agenda"

280 "Vista de la Lista de Citas"

281 "¡Lo siento, no hay Citas en la Lista!"

282 "Continuar"

283 "Agenda - Localizador"

284 "Buscar:"

285 "Buscar"

289 "Ayuda"

290 "Especifique la cadena de la Cita a buscar."

291 "Cita no encontrada."

292 "%d coincidencias encontradas"

293 "Fecha:"

294 "Ir a"

296 "Ayuda"

297 "Por favor, escriba una fecha"

298 "Ya está visualizando %s"

299 "Fecha no válida"

300 "Autor"

304 "Correo..."

305 "Insertar Cita de Grupo"

306 "Seleccione una agenda e INSERTAR otra vez."

307 "Continuar"

308 "Suprimir Cita"

309 "Seleccione una cita y SUPRIMIR otra vez."

310 "Continuar"

311 "Suprimir Cita"

312 "Error interno al seleccionar cita.\n\
La cita no se ha suprimido."

313 "Continuar"

314 "Suprimir Cita de Grupo"

315 "Seleccione una agenda y SUPRIMIR otra vez."

316 "Continuar"

317 "Suprimir Cita"

318 "Esta cita es parte de unas cadenas de repetición.\n\
¿Desea suprimirla...?"

320 "Esta Sólo"

321 "Reenviar"

322 "Todo"

323 "Cambiar Cita"

324 "Seleccione una cita y CAMBIAR otra vez."

325 "Continuar"

326 "Cambiar Cita"

327 "Error interno al seleccionar una cita.\n\
La cita no se ha cambiado."

328 "Continuar"

329 "Cambiar Cita de Grupo"

330 "Seleccione una agenda y CAMBIAR otra vez."

331 "Continuar"

332 "Cambiar Cita"

333 "Esta cita es parte de unas cadenas de repetición.\n\
¿Desea cambiarla ...?"

335 "Esta Sólo"

336 "Reenviar"

337 "Todo"

340 "Agenda"

341 "Acceso"

342 "Insertar"

343 "Cambiar"

348 "Insertar Permiso"

349 "Editor de Citas de Grupo de la Agenda"

350 "Error de selección, no se puede continuar\n"

351 "Selección cancelada por el usuario.\n"

352 "Debe seleccionar un componente dentro de la aplicación.\n"

353 "No hay hora"

354 "Todo el Día"

355 "No es posible abrir el archivo de callog.\n\
La operación se ha cancelado.  Agenda"

356 "A petición del usuario, la operación se ha cancelado.\n\
Agenda"

357 "Valor no válido en el campo FECHA.\n\
La operación se ha cancelado.  Agenda"

358 "Valor no válido en el campo INICIO.\n\
La operación se ha cancelado.  Agenda"

359 "Valor no válido en el campo FINAL.\n\
La operación se ha cancelado.  Agenda"

360 "Debe proporcionar un valor para FECHA.\n\
La operación se ha cancelado.  Agenda"

361 "Debe proporcionar un valor para INICIO.\n\
La operación se ha cancelado.  Agenda"

362 "Debe proporcionar un valor para QUE HACER.\n\
La operación se ha cancelado.  Agenda"

363 "Valores no válidos o discrepantes para REPETIR y PARA.\n\
La operación se ha cancelado.  Agenda"

364 "La operación del editor ha fallado"

365 "Continuar"

367 "La agenda ya existe.\n\
La operación se ha cancelado.  Agenda"

368 "La agenda no existe.\n\
La operación se ha cancelado.  Agenda"

370 "Error de autorización.  Permiso denegado.\n\
La operación se ha cancelado.  Agenda"

378 "Error de asignación de memoria - no existe suficiente memoria.\n\
La operación se ha cancelado.  Agenda"

383 "Error desconocido.\n\
La operación se ha cancelado.  Agenda"

386 "Esta cita tiene una hora final que es anterior a su hora de inicio.\n\
¿Desea planificarla en el día siguiente?"

387 "Planificar Cita"

389 "Siguiente Día"

390 "Privacidad:"

391 "Ubicación de la Agenda del Usuario:"

392 "Límites del Día:"

393 "Comienzo:"

394 "Fin:"

395 "Mostrar Hora:"

396 "12 Horas"

397 "24 Horas"

398 "Vista Predeterminada:"

399 "Año"

400 "Mes"

401 "Semana"

402 "Día"

403 "Vista de Agenda Inicial:"

404 "Acceso del Usuario"

405 "Por favor, seleccione al menos un permiso."

406 "Continuar"

407 "Configuración de Acceso del Grupo de la Agenda -- Eliminar"

408 "Por favor, seleccione un nombre primero."

409 "Continuar"

410 "Nombre del Usuario:"

411 "Añadir Nombre"

412 "Permisos"

413 "Permisos"

414 "Eliminar Nombre"

415 "B = Examinar I = Insertar D = Suprimir"

416 "Permisos:"

417 "Examinar"

418 "Insertar"

419 "Suprimir"

420 "Destino:"

421 "Impresora"

422 "Archivo"

423 "Impresora:"

424 "Directorio:"

425 "Opciones:"

426 "Archivo:"

427 "Anchura:"

428 "Altura:"

429 "Posición:"

430 "Pulgadas desde la izquierda"

431 "Pulgadas desde la parte inferior"

432 "Unidades:"

433 "Copias:"

434 "Incluir:"

435 "Mostrar Hora y Texto de Citas"

436 "Mostrar Sólo Horas de Citas"

437 "No Mostrar Ninguna Cita"

438 "Clasificación por Fecha:"

439 "MM | DD | AA"

440 "DD | MM | AA"

441 "AA | MM | DD"

442 "Separador de Fecha:"

443 "Blanco"

444 "Guardar Opciones de la Agenda"

445 "Se ha producido un error al grabar en ~/.desksetdefaults.\n\
Asegúrese de que tiene permiso para grabar en este archivo."

446 "Continuar"

447 "Leer Opciones de la Agenda"

448 "Se ha producido un error al leer desde ~/.desksetdefaults.\n\
Asegúrese de que tiene permiso para leer este archivo."

449 "Continuar"

450 "Ayuda para el Editor de Citas"

451 "Ha realizado modificaciones que no ha guardado.\n\
Puede guardar los cambios, descartarlos o volver \n\
a la posición anterior del diálogo."

452 "Guardar"

453 "Cancelar"

454 "Guardar Opciones de la Agenda"

456 "Continuar"

458 "Agenda -  Opciones"

459 "Categoría:"

460 "Aplicar"

463 "Ayuda"

464 "ps_open_file(): necesita que se especifique directorio o archivo\n"

465 "ps_open_file(): Directorio %s no válido\n"

466 "w+"

467 "ps_open_file(): no es posible abrir el archivo %s\n"

468 "Página"

469 "Vista del Día mediante Gestor de la Agenda"

470 "Mañana"

471 "Tarde"

472 "pm"

473 "Lista de Tareas mediante Gestor de la Agenda"

474 "Lista de Citas mediante Gestor de la Agenda"

475 "Página"

476 "de"

477 "Vista del Mes mediante Gestor de la Agenda"

478 "de"

479 "Página"

480 "Dom"

481 "Lun"

482 "Mar"

483 "Mié"

484 "Jue"

485 "Vie"

486 "Sáb"

487 "ps_init_printer(): no se puede abrir el archivo de prólogo de postscript: %s\n"

488 "de"

489 "   Página"

490 "Vista de Semana mediante Gestor de la Agenda"

491 "L"

492 "M"

493 "X"

494 "J"

495 "V"

496 "S"

497 "D"

505 "Sáb"

506 "Dom"

507 "Vista de Año mediante Gestor de la Agenda"

508 "Vista de Año mediante Gestor de la Agenda"

523 "Lista de Tareas: Año de %d"

524 "Lista de Citas: Año de %d"

525 "Lista de Tareas: %s"

526 "Lista de Citas: %s"

527 "Lista de Tareas: Semana de %s"

528 "Lista de Citas: Semana de %s"

529 "Lista de Tareas: %s"

530 "Lista de Citas: %s"

531 "Cada %d %s"

532 "DTCM: Repetir Cada"

533 "Repetir Cada:"

534 "Ocurrencia:"

535 "Para:"

536 "Privacidad:"

537 "Planificación de la Cita"

538 "¿Le gustaría planificar esta cita como la última semana\n\
del mes o como la cuarta semana del mes?"

540 "Ultima Semana"

541 "Cuarta Semana"

542 "Cada %d %s"

543 "Cada %d %s"

544 "Cada %d %s"

559 "Examinando %s..."

560 "Agenda - Mostrar Otra Agenda"

561 "Nombre del Usuario:"

562 "Mostrar"

564 "Ayuda"

565 "Autor"

566 "Suprimir Tarea"

567 "Seleccione una Tarea y SUPRIMIR otra vez."

568 "Continuar"

569 "Suprimir Tarea"

570 "Error interno al seleccionar la Tarea.\n\
La Tarea no se ha suprimido."

571 "Continuar"

572 "Suprimir Tarea"

573 "Esta Tarea es parte de unas cadenas de repetición.\n\
¿Desea suprimirla ...?"

575 "Esta Sólo"

576 "Reenviar"

577 "Todo"

578 "Cambiar Tarea"

579 "Esta Tarea es parte de unas cadenas de repetición.\n\
¿Desea cambiarla ...?"

581 "Esta Sólo"

582 "Reenviar"

583 "Todo"

584 "Cambiar Tarea"

585 "Seleccione una tarea y CAMBIAR otra vez."

586 "Continuar"

587 "Cambiar Tarea"

588 "Error interno al seleccionar la Tarea.\n\
La Tarea no se ha cambiado."

589 "Continuar"

590 "Fecha Límite:"

591 "Editor de Tareas de la Agenda"

595 "Semana Comenzando por %s"

596 "Lunes %d"

597 "Martes %d"

598 "Miércoles %d"

599 "Jueves %d"

600 "Viernes %d"

601 "Sábado %d"

602 "Domingo %d"

603 "Escriba un nombre a añadir en el campo Nombre del Usuario"

604 "ya está en la lista"

605 "Ayuda"

606 "Error de la Agenda"

607 "Error interno al registrar el nombre de la agenda."

608 "Continuar"

609 "Error de la Agenda"

610 "Error interno al recuperar el nombre de la agenda."

611 "Continuar"

612 "Información General..."

613 "Acerca de la Agenda..."

617 "Hoy"

618 "El argumento -session necesita un parámetro\n"

619 "Por favor, entre un nombre de agenda con el formato: <usuario>@<nombre de host>"

620 "Carácter desconocido. Es necesario el nombre de agenda: <nombre>%s"

621 "Por favor, entre un nombre de agenda con el formato: <usuario>@<nombre de host>"

622 "Agenda desconocida. Se necesita un nombre de host: %s@<nombre de host>"

623 "La agenda no muestra fechas anteriores al 1 de Enero de 1970"

624 "La agenda no muestra fechas posteriores al 31 de Diciembre del 2037"

625 "Menos"

626 "Más"

627 "Arrastrar Cita"

628 "Hora de Qué Hacer"

629 "Más"

631 "%d coincidencias encontradas"

632 "Por favor, seleccione una cita de la lista a mostrar"

633 "Agenda Seleccionada"

634 "Agendas Seleccionadas"

635 "Menos"

636 "Más"

637 "Más"

641 "El servidor no ha podido obtener la dirección de la red\n\
para la ubicación especificada:  nombre de host no válido."

642 "El daemon rpc.cmsd no está registrado.\n\
Por favor, verifique si rpc.cmsd está instalado correctamente en el sistema."

643 "No se ha podido acceder a la agenda. Agenda"

644 "Horas de las Citas:"

645 "Duración:"

646 "Minutos"

647 "Examinando %s..."

648 "SunDex"

649 "Agenda - Zona Horaria"

650 "Mi Hora"

652 "Personalizar Hora"

653 "GMT"

654 "Horas"

655 "OK"

656 "Aplicar"

658 "Ayuda"

659 "Zona Horaria:"

660 "Zona Horaria:"

662 "Zona Horaria:"

663 "Menos"

664 "Más"

666 "Más"

667 "La agenda no muestra fechas anteriores al 1 de Enero de 1970"

668 "La agenda no muestra fechas posteriores al 31 de Diciembre del 2037"

670 "Dtcm"

671 "Versión"

672 "Revisión"

674 "Copyright (c) 1993, 1994:"

675 "Hewlett-Packard Company"

676 "International Business Machines Corp."

677 "Novell, Inc."

678 "Sun Microsystems, Inc."

679 "Más..."

680 "Cerrar"

681 "Creadores de la Agenda"

682 "Esta aplicación ha sido suministrada por:"

683 "Cerrar"

684 "Los Nombres de Usuarios no pueden tener incluidos blancos ni tabulaciones"

685 "Nombre del Usuario:"

686 "Añadir Nombre"

687 "Eliminar Nombre"

688 "Examinar Elementos del Menú"

689 "OK"

690 "Aplicar"

691 "Restablecer"

693 "Ayuda"

696 "Uso:\n\
\tdtcm_admin [ -d ] [ -a acción ] [ -c agenda ][ -s <mm/dd/aa> ] [ -e <mm/dd/aa> ] [-f nombre de archivo]\n"

697 "Ha especificado una operación de administración a la que no se da soporte \"%s\".\n"

698 "\n\
No se ha podido abrir el archivo de salida \"%s\"\n"

699 "\n\
No se ha podido abrir el archivo de entrada \"%s\"\n"

700 "Desechar"

702 "Ayuda"

703 "contexto"

704 "Año de %d"

705 "%s"

706 "Semana de %s"

707 "%s"

708 "Esta cita se repite de una forma desconocida.  Todas las ocurrencias se cambiarán\n\
¿Aún desea cambiarla?"

710 "Continuar"

711 "Esta cita se repite de una forma desconocida.  Todas las ocurrencias se suprimirán\n\
¿Aún desea suprimirla?"

712 "Continuar"

713 "Debe elegir una fecha de inicio anterior a la fecha final."

714 "No hay ninguna cita en la lista.  Antes de mostrar una cita debe buscar una."

715 "Agenda - Ir a Fecha"

716 "Esta cita se repite de una manera desconocida.  Todas las ocurrencias se suprimirán\n\
¿Aún desea suprimirla?"

717 "Continuar"

718 "Esta cita se repite de una manera desconocida.  Todas las ocurrencias se cambiarán\n\
¿Aún desea cambiarla?"

720 "Continuar"

721 "Ver Horas y Texto para Otros"

722 "Ver Sólo Hora para Otros"

723 "No Ver Nada para Otros"

724 "Las citas de Duración no deben tener un valor de QUE HACER especificado.\n\
La operación se ha cancelado.  Agenda"

725 "La Entrada de la Agenda no existe.\n\
La operación se ha cancelado.  Agenda"

727 "La petición ha excedido el tiempo de espera\n\
Por favor, verifique si rpc.cmsd está instalado de manera correcta en el sistema."

728 "Agenda - Imprimir"

729 "Nombre de Impresora:"

730 "Copias:"

731 "De:"

732 "A:"

733 " Opciones del mandato de impresión:"

734 "Imprimir en archivo:"

735 "Imprimir"

736 "Agenda : Error - Imprimir"

737 "Ayuda"

738 "Lista de accesos:"

739 "Permisos de Acceso:"

740 "Añadir"

741 "Suprimir"

742 "Cambiar"

743 "Público:"

744 "Semiprivado:"

745 "Privado:"

746 "Vista"

747 "Insertar"

748 "Cambiar"

749 "El Nombre y los Permisos de Acceso deben establecerse para añadir un elemento a la Lista de Accesos"

750 "Valores de Acceso de Grupo de la Agenda -- Añadir"

751 "Esta entrada ya existe en la Lista de Accesos.  ¿Desea cambiarla?"

752 "Valores de Acceso de Grupo de la Agenda -- Añadir"

753 "Cambiar"

755 "Valores de Acceso de Grupo de la Agenda -- Cambiar"

756 "Deben establecerse el Nombre y los Permisos de Acceso para cambiar un elemento de la Lista de Accesos"

757 "Valores de Acceso de Grupo de la Agenda -- Cambiar"

758 "medianoche"

759 "valor"

760 "valor"

761 "Desechar"

762 "Editor Predeterminado"

763 "Mostrar Valores"

764 "Lista de Accesos y Permisos"

765 "Configuración de Impresora"

766 "Formato de Datos"

767 "OK"

768 "Restablecer"

772 "No puede guardar una Ubicación Agenda del Usuario en blanco\n\
o una que contenga blancos.\n\
La configuración de propiedades no se ha guardado."

773 "No puede guardar una Vista de agenda inicial en blanco\n\
o una que contenga blancos.\n\
La configuración de propiedades no se ha guardado."

774 "ps_open_file(): la impresión en archivo requiere nombre del archivo\n"

775 "Debe especificar un recordatorio avanzado.\n\
Se canceló la operación.  Agenda"

776 "Un recordatorio avanzado no puede contener un blanco.\n\
Se canceló la operación.  Agenda"

777 "Los valores avanzados deben ser un número con un signo opcional.\n\
Se canceló la operación.  Agenda"

778 "Ayuda Lista de Tareas Agenda"

779 "Ha efectuado cambios no guardados.\n\
No puede guardar los cambios, deseche los cambios,\n\
o vuelva al lugar anterior del diálogo."

780 "Desechar"

781 "Vista"

782 "Todo"

783 "Pendiente"

784 "Finalizada"

785 "OK"

786 "Aplicar"

788 "Ayuda"

789 "Tipo Tareas:"

790 "contexto"

791 "Tareas se repite de una manera desconocida. Se cambiarán todas las ocurrencias.\n\
¿Aún desea suprimirla?"

793 "Continuar"

794 "Esta cita se repite de una manera desconocida. Se cambiarán todas las ocurrencias.\n\
¿Todavía desea cambiarla?"

796 "Continuar"

797 "Tareas"

798 "Duración límite:"

799 "Finalizada"

800 "Insertar"

801 "Cambiar"

802 "Suprimir"

803 "Borrar"

805 "Ayuda"

806 "Año de %d"

807 "%s"

808 "Semana de %s"

809 "%s"

810 "Por favor, entre una nueva fecha de inicio posterior a 1/1/1970"

811 "Fecha de inicio errónea"

812 "Por favor, entre una fecha final anterior a 1/1/2038"

813 "Fecha final errónea"

814 "Debe entrar una fecha posterior a 1969 y anterior a 2038"

815 "Debe entrar una fecha posterior a 1969 y anterior a 2038"

816 "Días"

817 "Semanas"

818 "Meses"

819 "El valor Duración debe ser un entero sin signo.\n\
La configuración de propiedades no se ha guardado."

820 "El valor inicial debe ser una duración (hora) válida.\n\
La configuración de propiedades no se ha guardado."

$ 821 "Ha especificado un valor de anchura de impresión no permitido.\n\
$ La configuración de propiedades no se ha guardado."
$ "print width" has been replaced by "right margin".
821	"Ha especificado un valor de margen derecho no válido.\nLa configuración de propiedades no se ha guardado."

$ 822 "Ha especificado un valor de altura de impresión no válido.\n\
$ La configuración de propiedades no se ha guardado."
$ "print height" has been replaced by "bottom margin".
822	"Ha especificado un valor de margen inferior no válido.\nLa configuración de propiedades no se ha guardado."

825 "Días"

826 "Semanas"

827 "Meses"

828 "Fecha:"

829 "Inicio:"

830 "AM"

831 "PM"

832 "Final:"

833 "AM"

834 "PM"

835 "Qué hacer:"

836 "Frecuencia"

837 "Insertar/Cambiar Tareas"

839 "Agenda: Recordatorio"

840 "Cerrar"

841 "Pulsar en \"Añadir Nombre\" para añadir un nombre, \"Aplicar\" para confirmar cambios."

842 "La información transferida no contenía\n\
ninguna cita."

843 "Ha fallado la operación de Arrastrar y Soltar."

844 "No es posible ubicar la información transferida."

845 "Ha fallado la operación Arrastrar y Soltar\n\
Error interno de consistencia."

846 "Guardar"

847 "Restablecer"

848 "Fecha"

849 "Hora"

850 "Qué hacer"

851 "Mostrar Cita"

852 "Una Vez"

853 "Diariamente"

854 "Semanalmente"

855 "Cada Dos Semanas"

856 "Mensualmente Por Fecha"

857 "Mensualmente Por Día de La Semana"

858 "Anualmente"

859 "De Lunes a Viernes"

860 "Lun, Mié, Vie"

861 "Martes, Jueves"

862 "Repetir Cada..."

863 "2"

864 "3"

865 "4"

866 "5"

867 "6"

868 "7"

869 "8"

870 "9"

871 "10"

872 "11"

873 "12"

874 "13"

875 "14"

876 "siempre"

877 "Mins"

878 "Hrs"

879 "Días"

880 "Ayuda"

881 "Error interno #1: Tratamiento entrada/agenda no válido.\n\
Se canceló la operación.  Agenda"

882 "Error interno #2: Tratamiento sesión no válido.\n\
Se canceló la operación.  Agenda"

883 "Error interno #3: Datos no válidos.\n\
Se canceló la operación.  Agenda"

884 "Error interno #4: Especificado valor para un atributo de sólo-lectura.\n\
Se canceló la operación. Agenda"

885 "Error interno #5: Especificado tipo de datos incorrecto para un valor de atributo.\n\
Se canceló la operación.  Agenda"

886 "Error interno #6: El atributo especificado no está soportado en esta versión de agenda.\n\
Se canceló la operación.  Agenda"

887 "Error interno #7: La función especificada no está soportada en esta versión de agenda.\n\
Se canceló la operación.  Agenda"

888 "Error interno #8: Especificado operador no válido.\n\
Se canceló la operación.  Agenda"

890 "Error Servicios Agenda"

891 "Imprimir"

892 "Las fechas para impresión deben estar entre 1969 y 2038."

893 "Imprimir"

894 "Fecha \"De\" errónea"

895 "Imprimir"

896 "Fecha \"A\" errónea"

897 "Imprimir"

898 "La fecha \"A\" para impresión debe ser posterior a la fecha \"De\""

899 "Comienzo de la Lista de Tareas: %s"

900 "Comienzo de la Lista Appls: %s"

901 "Repetir Cada..."

902 "De Lunes a Viernes"

903 "Lun, Mié, Vie"

904 "Martes, Jueves"

905 "Repetir Cada..."

906 "Arrastrar Tareas"

907 "No se ha dejado espacio para el archivo agenda.\n\
Se canceló la operación.  Agenda"

908 "No puede establecer un valor de recordatorio a blancos.\n\
La configuración de propiedades no se ha guardado."

909 "No puede establecer un valor de recordatorio con un blanco incluido.\n\
La configuración de propiedades no se ha guardado."

910 "Los valores de recordatorio deben ser un número con un signo opcional.\n\
La configuración de propiedades no se ha guardado."

$ 911 "Ha especificado una posición no permitida desde el valor desplazamiento izquierdo.\n\
$ La configuración de propiedades no se ha guardado."
$ "position from left offset" has been changed to "left margin".
911	"Ha especificado un valor no válido para el margen izquierdo.\nLa configuración de propiedades no es ha guardado."

$ 912 "Ha especificado una posición no permitida desde el valor desplazamiento derecho.\n\
$ La configuración de propiedades no se ha guardado."
$ "position from right offset" has been changed to "top margin".
912	"Ha especificado un valor no válido para el margen superior.\nLa configuración de propiedades no se ha guardado."

913 "Un elemento de Tareas debe tener texto en la primera línea del elemento Qué hacer."

914 "Ha fallado la operación Editor de la Agenda"

915 "Ha fallado la operación Editor de la Agenda"

916 "El valor Duración debe ser inferior a 24 horas.\n\
La configuración de propiedades no se ha guardado."

917 "Faltan\n\
Gráficos"

918 "Faltan \n\
Gráficos"

919 "Agenda"

920 "mostrada."

921 "No se pudo acceder a la agenda:"

922 "Acerca de la Agenda"

923 "Cancelar"

924 "Cancelar"

925 "Cancelar"

926 "Cerrar"

927 "Cancelar"

928 "Cancelar"

929 "Cancelar"

930 "Insertar"

931 "Cambiar"

932 "Suprimir"

933 "Borrar"

934 "Cancelar"

935 "Ayuda"

936 "Cancelar"

937 "Cancelar"

938 "Cancelar"

939 "Cancelar"

940 "Cerrar"

941 "Cerrar"

942 "Cancelar"

943 "Cancelar"

944 "Cancelar"

945 "Cancelar"

946 "Cancelar"

947 "Cancelar"

948 "Cerrar"

949 "Cancelar"

950 "Cancelar"

951 "Cancelar"

952 "Cerrar"

953 "Cancelar"

954 "Cerrar"

955 "Cancelar"

956 "Cancelar"

957 "Cancelar"

958 "Cancelar"

959 "Cancelar"

960 "Cancelar"

961 "Cancelar"

962 "Cancelar"

963 "Agenda - Editor de Menús"

964 "Sobre el Tema"

965 "Lista de Tareas..."

966 "Tareas..."

967 "Versión del Servidor de Agendas"

968 "Versión de los Datos de Agenda"

969 "Repetir cada"

970 "El valor de Repetir cada debe ser un entero sin signo."

971 "Duración de cita de agenda"

972 "Que hacer"

973 "Buscar todos"
974 "Buscar desde"
975 "hasta"
976 "Tipo de informe:"
977 "Vista del día"
978 "Vista de la semana"
979 "Vista del mes"
980 "Vista del año"
981 "Lista de citas"
982 "Lista de tareas"
983 "Nombre de usuario"
984 "Esta cita forma parte de una serie repetida.\n¿Desea insertar la cita?"
985 "Recordatorios"
986 "Pitido"
987 "Intermitente"
988 "Emergente"
989 "Correo"
990 "Enviar a:"
992 "%A, %B %e, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993 "Week Starting %A, %B %e, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994 "días"
995 "semanas"
996 "quincenas"
997 "meses"
998 "años"
1002 "También contribuyen:"
1003 "Esta cita se encuentra en una agenda que pertenece a otra persona.\n¿Desea modificarla de todas maneras?"
1004 "Esta cita se encuentra en una agenda que pertenece a otra persona.\n¿Desea eliminarla de todas maneras?"
1005 "Eliminarla de"
1006 "Modificar en"
1007 "Se produjo un error al seleccionar la cita.\nLa cita no se ha modificado."
1008 "Cita de agenda: Ayuda"
1009 "Se produjo un error interno al seleccionar Tareas.\nNo se ha modificado Tareas."
1010 "Agenda: Comparar calendarios"
1011 "El campo \"Hora del plazo\" contiene un valor no válido.\nSe ha cancelado la operación.  Agenda"

1012 "Agenda -  Lista de tareas"

1042 "Acceso de inserción denegado: "
1043 "Acceso de eliminación denegado: "
1044 "Acceso de bloqueo denegado: "
1045 "Cancelar para"
1046 "Cita cancelada\n"
1047 "Esta cita: '%s' tiene fin\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048 "Esta cita tiene fin\n"
1049 "la hora es anterior a la de comienzo.  ¿Desea\n"
1050 "programarla para el próximo día? [S/N]  "
1051 "La cita '%s' pertenece a una serie que se repite.  "
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052 "Desea:"
1053 "\n\t1.  Borrar todas"
1054 "\n\t2.  Borrar ésta solamente"
1055 "\n\t3.  Borrar hacia adelante"
1056 "\n\t4.  Cancelar"
1057 "\n\tOpción [1-4]: "
1058 "Se ha especificado una fecha no válida.\n"
1059 "Se ha especificado una hora de comienzo no válida.\n"
1060 "Se ha especificado una hora de finalización no válida.\n"
1061 "El campo de fecha falta o está vacío.\n"
1062 "El campo de inicio falta o está vacío.\n"
1063 "El campo Qué hacer falta o está vacío.\n"
1064 "Los campos Repetir y Para no coinciden.\n"
1065 "Se ha cancelado la operación de inserción de la cita\n"
1066 "La cita no se ha insertado."
1067 "Se ha especificado una fecha no válida:"
1068 "Citas para"
1069 "No hay citas para"
1070 "Agenda : Error - Comparar calendarios"
1072 "Agenda: Error - Examinar"
1073 "Agenda: Error - Arrastrar y soltar"
1074 "Cita de agenda"
1075 "Agenda: Error - Cambiar cita"
1076 "Agenda: Ayuda"
1078 "Agenda: Lista de acceso y permisos - Agregar"
1079 "Agenda: Error - Opciones del editor"
1083 "Agenda: Error - Opciones de pantalla"
1085 "Agenda: Error - Opciones de la impresora"

1086 "Agenda - Lista de citas"

1087 "De %1$2d:%2$02d%3$s a %4$2d:%5$02d%6$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088 "%1$2d:%2$02d%3$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089 "De %1$02d%2$02d a %3$02d%4$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090 "%1$02d%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091 "%B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092 "%Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/

1100 "\n\n\
\t** Elemento Tareas Calendario **\n\n\
\tFecha Límite:\t%s\n\
\tLímite Duración:\t%s\n\
\tQué Hacer:\t\t%s"

1101 "Insertar Cita"

1102 "Insertar Tareas"

1103 "Esta Tarea forma parte de una serie repetitiva.\n\
¿Desea insertar el elemento ...?"

1104 "Valor no válido en campo Límite Duración.\n\
Se ha cancelado la operación.  Calendario"

1105 "Debe proporcionar un valor de Límite Duración.\n\
Se ha cancelado la operación.  Calendario"

$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"Fecha"
1107	"Identificación del usuario"
1108	"Número de página"
1109	"Tipo de informe"
1110	"Ninguno"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"Agenda: Error - Configuración de impresión"
1112	"Error del Administrador de diálogo de impresión (PDM) - Falló la configuración."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113	"Se ha especificado una impresora o servidor de impresión no válido."
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114	"Agenda:  Error - Imprimir en archivo"
1115	"Error - No es posible imprimir en un archivo."
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116	"Agenda: Imprimir en archivo"
1117	"Ha finalizado la operación de impresión en el archivo."
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118	"Agenda: Advertencia - Imprimir"
1119	"Advertencia - No se puede cargar el font %s."
$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled.
1120	"No se puede programar el evento en el período de tiempo especificado.\nSe ha cancelado la operación."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
1121	"Agenda : Error de servidor de impresión"
1122	"La tarea de impresión ha fallado.\n\nEl servidor de impresión X está temporalmente sin recursos."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Calendar - Warning
$ "-NEW"
2 "Could not connect to ToolTalk:\n%s\n"
$ "-NEW"
3 OK
$ "-NEW"
4 "Calendar : Appointment Editor - Warning"
