$ $TOG: dticon.msg /main/7 1999/09/17 12:18:22 mgreess $
$ *************************************<+>*************************************   
$ *****************************************************************************   
$ **   
$ **  File:        dticon.msg   
$ **   
$ **  Project:     HP DT Icon Editor   
$ **   
$ **  Description:   
$ **  -----------   
$ **  This file is the source for the message catalog for dticon   
$ **   
$ **   
$ *****************************************************************************   
$ **   
$ **     (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company   
$ **     (c) Copyright 1993, 1994 International Business Machines Corp.   
$ **     (c) Copyright 1993, 1994 Sun Microsystems, Inc.   
$ **     (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of   
$ **         Novell, Inc.   
$ **   
$ **     All Rights reserved   
$ **   
$ **   
$ *****************************************************************************   
$ **   
$quote "

$set 2
$ *****************************************************************************   
$ ** _DtMessage set for fileIODialog.c   
$ **   
$ ** messages 10-16 are for the FileSelectionBox widget (default labels)   
$ *****************************************************************************   

2 "Editor de iconos - E/S de archivo"

4 "Editor de iconos - E/S archivo"

6 "Editor de iconos - Guardar como"

8 "Editor de iconos - Abrir archivo"

10 "Actualizar"

12 "Carpetas"

14 "Archivos"

16 "Entrar nombre de archivo:"

17 "Entrar nombre de archivo:"

18 "Actualizar"

20 "SIN TITULO"

22 "Abrir"

24 "Guardar"

$set 4        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for newIconDialog.c   
$ **   
$ *****************************************************************************   

2 "DiálogoIconosnuevo"

4 "Editor de iconos - Redimensionar"

6 "OK"

8 "Cancelar"

10 "Ayuda"

12 "Nueva anchura:"

14 "Nueva altura:"

$set 6        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for queryDialog.c   
$ **   
$ *****************************************************************************   

2 "Editor de iconos - Aviso"

6 "OK"
$ ** DO NOT LOCALIZE - the user should never see this message   

8 "¿Lo desea realmente?"

10 "Cancelar"

$set 8        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for stdErrDialog.c   
$ **   
$ *****************************************************************************   

2 "Editor de iconos - Error"

4 "Continuar"

$ 
$ "-NEW"
6 OK

$ 
$ "-NEW"
8 "Could not connect to ToolTalk:\n%s\nExiting ..."

$set 10        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for utils.c   
$ **   
$ *****************************************************************************   
$ ** DO NOT LOCALIZE messages 2-48, they appear in the errorlog only   

2 "No se puede inicializar el icono del botón para círculo"

4 "No se puede inicializar el icono del botón para círculo sólido"

6 "No se puede inicializar el icono del botón para polilínea"

8 "No se puede inicializar el icono del botón para polígono"

10 "No se puede inicializar el icono del botón para polígono sólido"

12 "No se puede inicializar el icono del botón para elipse"

14 "No se puede inicializar el icono del botón para elipse sólida"

16 "No se puede inicializar el icono del botón para borrador"

18 "No se puede inicializar el icono del botón para línea"

20 "No se puede inicializar el icono del botón para relleno área contigua"

22 "No se puede inicializar el icono del botón para punto"

24 "No se puede inicializar el icono del botón para rectángulo"

26 "No se puede inicializar el icono del botón para rectángulo sólido"

28 "No se puede inicializar el icono del botón para selección"

30 "No se puede analizar el número de color estático."

32 "No se puede asignar el número de color estático."

38 "Sin memoria(0)"

40 "Sin memoria(1)"

42 "Sin memoria(2)"

44 "Sin memoria(3)"

46 "Sin memoria(4)"

48 "Sin memoria(5)"

50 "No se puede inicializar el almacenamiento del icono de aplicación"

52 "Uso no válido del parámetro '-f'"

54 "Uso no válido del parámetro '-i'"

56 "Uso no válido del parámetro '-session' "

58 "Formato de tamaño no válido"

60 "Ha fallado la captura de la imagen de pantalla"

62 "Ha fallado la operación.\n\
El mapa de colores está lleno"

64 "Parámetro de dimensión no válido"

66 "(SIN TÍTULO)"

$set 12        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for dtIconShell.c   
$ **   
$ *****************************************************************************   

1 "Editor de iconos"

2 "2 Color"

3 "Editor de iconos - (SIN TÍTULO)"

4 "Bienvenido al Editor de iconos."

6 "Rellenar figuras"

8 "Colores estáticos"

10 "Colores dinámicos"

12 "Grises estáticos"

14 "Primer plano"

16 "Fondo"

18 "SombraSuperior"

20 "SombraInferior"

22 "Seleccionar"

24 "Transparente"
$ ** message 26-198 are menu items with corresponding mnemonics   
$ ** (for set grouping information, see the comment at the end-of-file)   

26 "N"

28 "Nuevo..."

30 "A"

32 "Abrir..."

34 "G"

36 "Guardar"

38 "c"

40 "Guardar como..."

42 "a"

44 "Salir"

46 "r"

48 "Archivo"

50 "D"

52 "Deshacer"

54 "t"

56 "Cortar área"

58 "C"

60 "Copiar área"

62 "P"

64 "Pegar área"

68 "I"

70 "Izquierda"

72 "D"

74 "Derecha"

76 "G"

78 "Girar área"

82 "V"

84 "Vertical"

86 "H"

88 "Horizontal"

90 "l"

92 "Alternar área"

94 "E"

96 "Escalar área"

98 "i"

100 "Redimensionar icono..."

102 "p"

104 "Añadir punto de actuación"

106 "S"

108 "Suprimir punto de actuación"

110 "T"

112 "Tomar imagen pantalla"

114 "B"

116 "Borrar icono"

118 "E"

120 "Editar"

122 "V"

124 "Cuadrícula Visible"

128 "B"

130 "XBM"

134 "P"

136 "XPM"

138 "F"

140 "Formato de salida"

144 "2x"

146 "3x"

148 "4x"

150 "5x"

152 "6x"

154 "8x"

156 "10x"

158 "12x"

160 "A"

162 "Ampliación"

164 "O"

166 "Opciones"

168 "g"

170 "Visión general..."

172 "T"

174 "Tareas..."

176 "R"

178 "Referencia..."

180 "S"

182 "Sobre el tema"

188 "U"

190 "Uso de la ayuda..."

192 "i"

194 "Acerca del editor de iconos..."

196 "y"

198 "Ayuda"
$ ** message 200-are used in the "instruction" line for current drawing mode   

200 "Modalidad de edición actual:"

202 "(Rellenado)"

204 "Lápiz"

206 "Rellenar área contigua"

208 "Línea"

210 "Polilínea"

212 "Rectángulo"

214 "Polígono"

216 "Círculo"

218 "Elipse"

220 "Borrar"

222 "Seleccionar"

224 "No válido"

$set 14        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for help.c   
$ **   
$ *****************************************************************************   

2 "Editor de iconos - Ayuda"

4 "Debe seleccionar un elemento\n\
dentro del Editor de iconos."

$set 16        Redefine set#

$ *****************************************************************************   
$ ** _DtMessage set for process.c   
$ **   
$ *****************************************************************************   

2 "No se puede acceder al archivo o\n\
éste contiene datos no válidos"

4 "No se pueden grabar datos en el archivo"

6 "Esta característica todavía no está disponible"

8 "No se dispone de ninguna\n\
imagen anterior"

10 "Se ha especificado una anchura\n\
y/o altura no válida(s)"

12 "No se ha seleccionado área "

14 "No se había cortado o copiado\n\
previamente ningún área"

16 "No se ha guardado el icono actual.\n\n\
Los cambios se perderán."

20 "Comprobar permisos del archivo"

22 "No se pudo restaurar la sesión desde el archivo"

24 "No se pudo guardar la sesión para el archivo"

25 "El archivo ya existe.\n\n\
¿Desea sobreescribir el archivo?"

$set 18
$ *****************************************************************************
$ ** _DtMessage set for event.c
$ **
$ *****************************************************************************

$quote

2 Tamaño de la imagen capturada = %dx%d

$ *****************************************************************************   
$ ** End of _DtMessage Catalog File   
$ ** (Comments only below this line)   
$ *****************************************************************************   
$ **   
$ *****************************************************************************   
$ ** Unique mnemonic groupings from set 12   
$ *****************************************************************************   
$ **   
$ ** Unique Set 1:  (Main Menu Bar)   
$ **   
$ **   46 F   
$ **   48 File   
$ **   
$ **   118 E   
$ **   120 Edit   
$ **   
$ **   164 O   
$ **   166 Options   
$ **   
$ **   196 H   
$ **   198 Help   
$ **   
$ **   
$ ** Unique Set 2:  (File Menu)   
$ **   
$ **   26 N   
$ **   28 New...   
$ **   30 O   
$ **   32 Open...   
$ **   34 S   
$ **   36 Save   
$ **   38 A   
$ **   40 Save As...   
$ **   42 x   
$ **   44 Exit   
$ **   
$ **   
$ ** Unique Set 3:  (Edit Menu)   
$ **   
$ **   50 U   
$ **   52 Undo   
$ **   54 t   
$ **   56 Cut Area   
$ **   58 C   
$ **   60 Copy Area   
$ **   62 P   
$ **   64 Paste Area   
$ **   
$ **        Unique Set 3a:  (Rotate Sub-Menu)   
$ **        68 L   
$ **        70 Left   
$ **        72 R   
$ **        74 Right   
$ **   76 R   
$ **   78 Rotate Area   
$ **   
$ **        Unique Set 3b:  (Flip Sub-Menu)   
$ **        82 V   
$ **        84 Vertical   
$ **        86 H   
$ **        88 Horizontal   
$ **   90 F   
$ **   92 Flip Area   
$ **   94 S   
$ **   96 Scale Area   
$ **   98 z   
$ **   100 Resize Icon...   
$ **   102 A   
$ **   104 Add Hot Spot   
$ **   106 D   
$ **   108 Delete Hot Spot   
$ **   110 G   
$ **   112 Grab Screen Image   
$ **   114 e   
$ **   116 Clear Icon   
$ **   
$ **   
$ ** Unique Set 4:  (Options Menu)   
$ **   
$ **   122 V   
$ **   124 Visible Grid   
$ **   
$ **        Unique Set 4a:  (Output Sub-Menu)   
$ **        128 B   
$ **        130 XBM   
$ **        134 P   
$ **        136 XPM   
$ **   138 O   
$ **   140 Output Format   
$ **   160 M   
$ **   162 Magnification   
$ **   
$ **   
$ ** Unique Set 5:  (Help Menu)   
$ **   
$ **   168 I   
$ **   170 Introduction...   
$ **   172 T   
$ **   174 Tasks...   
$ **   176 R   
$ **   178 Reference...   
$ **   180 O   
$ **   182 On Item   
$ **   188 U   
$ **   190 Using Help...   
$ **   192 V   
$ **   194 Version...   
$ **   
