$ message catalog of dtimsstart
$ @(#)$XConsortium: dtimsstart.msg /main/2 1996/10/19 14:46:05 rws $

$set 1
$ 	usage
1 Uso:  %s  [opciones ..]
2 imprimir variables de entorno modificadas
3 reemplazar $SHELL
4 especifica el nombre del método de introducción de datos
5 especifica opciones de comando para el servidor de método de introducción de datos
6 especifica el anfitrión en el que se debe ejecutar el servidor de método de introducción de datos
7 cambiar el modo de selección del método de introducción de datos
8 imprimir método de introducción de datos registrados
9 mostrar este mensaje

$ 	selection mode
$ please do not translate ask_at_login and resume_current_input_method
20 SelectMode
21 ask_at_login
22 resume_current_input_method
23 forzar modo 'resume_current_input_method'
24 forzar modo 'ask_at_login'

$ 	error messages
31 opción no válida '%s'
32 la variable de entorno 'HOME' no está definida
33 la variable de entorno 'LANG' no está definida
34 esta ubicación no está soportada por el escritorio.
35 la variable de entorno 'DISPLAY' no está definida
36 no se puede abrir el archivo\n  [%s]
37 no se puede crear el archivo\n  [%s]
38 no se puede crear el directorio\n  [%s]
39 falta la anotación '%s' en el archivo de configuración\n  [%s]
40 ya se está ejecutando otro '%s'
41 no hay archivo de selección para '%s'
42 no se puede crear el archivo de selección\n  [%s]
43 no se ha seleccionado ningún ims para '%s'
44 no hay ningún archivo de configuración de ubicación para '%s'
45 no hay ningún ims configurado para '%s'
46 no hay ningún archivo de configuración ims para '%s'
47 el ims '%s' no está registrado
48 no hay ningún archivo ejecutable para '%s'\n  [%s]
49 ya se está ejecutando el ims '%s'
50 no se puede ejecutar el ims '%s'
51 la ejecución del ims '%s' se ha detenido.  Vea el archivo de registro.\n  [%s]
52 el ims '%s' todavía no está disponible
53 anfitrión desconocido '%s'
54 la operación '%s' ha fallado
55 la ejecución remota en '%s' ha fallado
56 las funciones remotas no están disponibles en '%s'
57 no hay ningún ims registrado en '%s'
58 no hay ningún ims '%1$s' registrado en '%2$s'
59 no se puede abrir la pantalla '%s'

$ 
