$     
$ +SNOTICE    
$     
$  $TOG: DtMail.msg /main/41 1999/09/14 15:44:36 mgreess $    
$     
$  RESTRICTED CONFIDENTIAL INFORMATION:    
$     
$  The information in this document is subject to special    
$  restrictions in a confidential disclosure agreement between    
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this    
$  document outside HP, IBM, Sun, USL, SCO, or Univel without    
$  Sun's specific written approval.  This document and all copies    
$  and derivative works thereof must be returned or destroyed at    
$  Sun's request.    
$     
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.    
$     
$ +ENOTICE    
$     
$     
$ Strings from dtmail/RoamApp.C    
$quote "

$set 1

1 "OK"

2 "Opciones de Correo..."

3 "Vacaciones"

4 "Actualización propiedades..."
$     
$ Strings from dtmail/RoamMenuWindow.C    

5 "Cancelar"

6 "Aplicación de correo"

7 "Aplicación de correo"

8 "Aplicación de correo"

9 "Suprimir"

10 "Siguiente"

11 "Anterior"

12 "Responder al Remitente"

13 "Imprimir"

14 "Remitente"

15 "Tema"

16 "Fecha y Hora"

17 "Tamaño"

18 "Buzón"

19 "Verificar si hay correo nuevo"

20 "Abrir Buzón de Entrada"

21 "Abrir Buzón de Entrada"

22 "Nuevo..."

23 "Aplicación de correo - Nuevo"

24 "Nuevo"

25 "Abrir..."

26 "Aplicación de correo - Abrir"

27 "Abrir"

28 "Destruir Mensajes Suprimidos"

29 "Cerrar"

30 "Abrir"

31 "Guardar Como Texto..."

32 "Aplicación de correo - Mensaje - Guardar Como Texto"

33 "Copiar A"

34 "Imprimir..."

35 "Buscar..."

36 "Seleccionar Todo"

37 "Suprimir"

38 "Rehacer Ultima Supresión"

39 "Rehacer Supresión Desde Lista..."

40 "Mensaje"

41 "Mover"

42 "Aplicación de correo - Mensajes"

43 "Copiar"

44 "Seleccionar Todo"

45 "Editar"

46 "Aplicación de correo - Texto"

47 "Siguiente"

48 "Anterior"

49 "Cabeceras abreviadas"

50 "Por Fecha/Hora"

51 "Por Remitente"

52 "Por Tema"

53 "Por Tamaño"

54 "Por Estado"

55 "Vista"

56 "Mensaje Nuevo"

57 "Nuevo, Incluir Todo"

58 "Reenviar Mensaje"

59 "Responder al Remitente"

60 "Responder a Todo"

61 "Responder al Remitente, Incluir"

62 "Responder a Todo, Incluir"

63 "Componer"

64 "Mover"

65 "Otros Buzones..."

66 "Guardar Como..."

67 "Aplicación de correo - Anexos - Guardar Como"

68 "Seleccionar Todo"

69 "Anexos"

70 "Aplicación de correo - Anexos"

71 "Visión General"

72 "Tareas"

73 "Referencia"

74 "Sobre el Tema"

75 "Uso de la Ayuda"

76 "Ayuda"

77 "Acerca de la Aplicación de correo..."

78 "La Aplicación de correo no puede entender el estado de este buzón.\n\
Cierre el buzón mediante la elección de OK y restaurando la Aplicación\n\
de correo."

79 "Convirtiendo... completado el %d por ciento"

80 "Aplicación de correo"
$     
$ Strings from dtmail/AttachArea.C    

81 "Aplicación de correo"

82 "Aplicación de correo"

83 "Aplicación de correo"
$     
$ Strings from dtmail/Attachment.C    

84 "%s es una anexo ejecutable. ¿Desea ejecutarlo?"

85 "Aplicación de correo"

86 "Aplicación de correo"

87 "Aplicación de correo"

88 "Aplicación de correo"
$     
$ Strings from dtmail/RoamCmds.C    

89 "Aplicación de correo - Otros buzones"

90 "Mover"

91 "Imprimiendo..."

92 "OK"

93 "Guardar"

94 "Guardar"

95 "Guardar"

96 "Vaciar"

97 "Renombrar"

98 "Aplicación de Correo - Renombrar"

99 "Aplicación de correo - Cerrar"

100 "OK"

101 "Cancelar"

102 "Ya está utilizando el recurso de reenviar para\n\
algo distinto de Vacaciones. Mientras Vacaciones está\n\
en ejecución, Vacaciones se añadirá a esta otra actividad\n\
de reenviar. ¿Es ello correcto para iniciar Vacaciones?\0"

103 "Aplicación de correo"

104 "Ya está ejecutando el programa vacaciones en su archivo .forward.\n\
Consulte la documentación para detenerlo y suprimirlo del archivo .forward.\n\
Intente este mandato después de solucionar el problema.\0"

105 "No se puede abrir el archivo .vacation.msg -- No tiene permiso de escritura."

106 "El archivo .vacation.msg existe. ¿Reemplazar con texto nuevo?"

107 "No se puede abrir el archivo .vacation.msg -- No tiene permiso de escritura."

108 "Estoy de vacaciones"
$ \t    /* NL_COMMENT    
$ \t     * This is the default value of the subject field in the    
$ \t     * message that gets returned to the sender when vacation    
$ \t     * is turned on.    
$ \t     */    

109 "Estoy de vacaciones.\n\
Su correo referente a \"$SUBJECT\" lo leeré cuando vuelva.\n"
$     
$ Strings from dtmail/MsgScrollingList.C    

110 "N"
$ /* NL_COMMENT    
$  * In a mailer container window's message scrolling list, a "N" appears    
$  * to the left of a mail message header indicating that the mail message    
$  * is "new" (just arrived and not yet viewed by the user).    
$  * There is only space to display 1 character.  If "N" needs to be translated,    
$  * please make sure the translation is only 1 character.    
$  */    

111 "N"
$ /* NL_COMMENT    
$  * In a mailer container window's message scrolling list, a "N" appears    
$  * to the left of a mail message header indicating that the mail message    
$  * is "new" (just arrived and not yet viewed by the user).    
$  * There is only space to display 1 character.  If "N" needs to be translated,    
$  * please make sure the translation is only 1 character.    
$  */    

112 "N"
$ /* NL_COMMENT    
$  * In a mailer container window's message scrolling list, a "N" appears    
$  * to the left of a mail message header indicating that the mail message    
$  * is "new" (just arrived and not yet viewed by the user).    
$  * There is only space to display 1 character.  If "N" needs to be translated,    
$  * please make sure the translation is only 1 character.    
$  */    

113 "N"
$ /* NL_COMMENT    
$  * In a mailer container window's message scrolling list, a "N" appears    
$  * to the left of a mail message header indicating that the mail message    
$  * is "new" (just arrived and not yet viewed by the user).    
$  * There is only space to display 1 character.  If "N" needs to be translated,    
$  * please make sure the translation is only 1 character.    
$  */    

114 "N"
$     
$ Strings from dtmail/Undelete.C    

115 "Rehacer supresión"

116 "Cerrar"
$     
$ Strings from dtmail/SendMsgDialog.C    

117 "Enviar"

118 "Cerrar"

119 "Mensaje Nuevo"

120 "Aplicación de correo"

121 "Archivo"

122 "Incluir..."

123 "Aplicación de correo - Incluir"

124 "Incluir"

125 "Guardar Como Texto..."

126 "Aplicación de correo - Guardar Como Texto"

127 "Registro de mensajes"

128 "Enviar Como"

129 "Cerrar"

130 "Editar"

131 "Deshacer"

132 "Cortar"

133 "Copiar"

134 "Pegar"

135 "Pegar Especial"

136 "Entre corchetes"

137 "Indentado"

138 "Borrar"

139 "Suprimir"

140 "Seleccionar Todo"

141 "Anexos"

142 "Añadir Archivo..."

143 "Aplicación de correo - Añadir"

144 "Añadir"

145 "Guardar Como..."

146 "Aplicación de correo - Anexos - Guardar Como"

147 "Suprimir"

148 "Rehacer supresión"

149 "Renombrar"

150 "Seleccionar Todo"
$       /* NL_COMMENT    
$        * This is an obsolete message.  It is replaced by message 226    
$        * in set 1.    
$        */    

151 "Mostrar Panel"

152 "Formato"

153 "Acomodación Automática de Texto"

154 "Configuración..."

155 "Buscar/Cambiar..."

156 "Verificar Ortografía..."

157 "Plantillas"

158 "Aplicación de correo - Anexos"

159 "Aplicación de correo - Componer"

160 "Mensaje Nuevo"
$       /* NL_COMMENT    
$        * This is the label for a toggle item in a menu.  When the item    
$        * is set to "Show List", the Attachment List is mapped in the    
$        * Compose Window.  This message replaces message 151 in set 1.    
$        */    
$     
$ Strings from dtmail/ViewMsgDialog.C    

161 "Copiar"

162 "Seleccionar Todo"

163 "Editar"

164 "Guardar Como..."

165 "Aplicación de correo - Anexos - Guardar Como"

166 "Seleccionar Todo"

167 "Anexos"

168 "Aplicación de correo - Anexos"

169 "Aplicación de correo - Texto"

170 "Información general"

171 "Tareas"

172 "Referencia"

173 "Sobre el tema"

174 "Uso de la Ayuda"

175 "Ayuda"

176 "Acerca de la Aplicación de correo..."

177 "Aplicación de correo"
$     
$ Strings from dtmail/DtMailGenDialog.C    

178 "Aplicación de correo - Acerca de Dtmail"

179 "Dtmail Versión 1.0"

180 "OK"

181 "OK"

182 "Cancelar"
$     
$ Strings from dtmail/FindDialog.C    

183 "Buscar"
$  /* NL_COMMENT    
$   * This is an obsolete message.  Replaced by message 220 in set 1    
$   */    

184 "Buscar y Seleccionar Todo"

185 "Borrar"

186 "Cerrar"

187 "Ayuda"

188 "A:"

189 "De:"

190 "Tema:"

191 "Cc:"

192 "Aplicación de correo - Buscar"

193 "Reenviar"

194 "Devolución"
$  /* NL_COMMENT    
$   * This message replaces message 184 in set 1    
$   */    
$     
$ Strings from dtmail/Editor.C    

195 "------------- Comienzo de Mensaje Reenviado -------------\n\n"

196 "------------- Comienzo de Mensaje Incluido -------------\n\n"

197 "------------- Fin del Mensaje Reenviado -------------\n\n"

198 "------------- Fin del Mensaje Incluido -------------\n\n"
$     
$ Strings from dtmail/XmTextEditor.C    

199 "\n\
------------- Comienzo del Mensaje Incluido -------------\n"

200 "\n\
------------- Fin del mensaje Incluido -------------\n"
$     
$ Strings from dtmail/DtEditor.C    

201 "\n\
------------- Comienzo del Mensaje Incluido -------------\n"

202 "\n\
------------- Fin del Mensaje Incluido -------------\n"
$     
$ Strings from dtmail/ComposeCmds.C    

203 "Aplicación de correo"

204 "No es posible crear una ventana de composición."

205 "Aplicación de correo"

206 "No es posible crear una ventana de composición."

207 "Aplicación de correo"

208 "No es posible crear una ventana de composición."

209 "Aplicación de correo"

210 "No es posible crear una ventana de composición."

211 "Aplicación de correo"

212 "No existe la plantilla."

213 "Aplicación de correo"

214 "Parece que la plantilla está dañada."

215 "Aplicación de correo"

216 "No hay memoria suficiente para cargar la plantilla."

217 "Aplicación de correo"

218 "La plantilla parece dañada."
$     
$ Strings from dtmail/SortCmd.C    

219 "Clasificando..."

220 "Seleccionar Todo"

221 "Buzón de entrada"

222 "%a %b %d %k:%M"
$ /* NL_COMMENT    
$  * The "%a %b %d %k:%M" is the time and date format, please refer to     
$  * strftime man page for explanation of each format.    
$  */    

223 "%a %b %d %H:%M"
$ /* NL_COMMENT    
$  * The "%a %b %d %H:%M" is the time and date format, please refer to     
$  * strftime man page for explanation of each format.    
$  */    

224 "%a %b %d %k:%M"
$ /* NL_COMMENT    
$  * The "%a %b %d %k:%M" is the time and date format, please refer to     
$  * strftime man page for explanation of each format.    
$  */    

225 "%a %b %d %H:%M"
$ /* NL_COMMENT    
$  * The "%a %b %d %H:%M" is the time and date format, please refer to     
$  * strftime man page for explanation of each format.    
$  */    

226 "Mostrar Lista"

$ String from Undelete.C, Deleted Messages window title
227 "Mailer - Mensajes eliminados"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "Añadir"
229 "Suprimir"
230 "Enviar"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "Buscando..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "Se ha seleccionado un mensaje"
233 "Se han seleccionado %d mensajes"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "No se encontraron coincidencias"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "Mailer - Acerca de Mailer"
236 "Mailer Versión %d.%d.%d"
$  /* NL_COMMENT
$   * String 237 is the Copy button on Move Other Mailboxes dialog (from RoamCmds.C)
$   */
237 "Copiar"

$ 
$ DTMC_BADSTATE
$ The mailbox is in a state which cannot be deciphered by the Mailer, i.e.
$ portions of the file have been deleted by another process (the Mailer
$ only knows how to handle other processes adding to the end of the mailbox.
$ 
$ "-NEW"
238 "Mailer is confused about the state of this mailbox.\nIt may be that another process has rewritten this mailbox in an unexpected way.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost."

$ 
$ DTMC_ACCESSFAILED
$ The Mailer cannot perform routine file operations on the mailbox file,
$ a.k.a. stat, fstat, write, ...
$ 
$ "-NEW"
239 "Mailer can no longer access this mailbox.\nIt may be that another process has deleted the mailbox file.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ DTMC_INODECHANGED
$ The mailbox has been rewritten by another process.
$ 
$ "-NEW"
240 "Mailer can no longer access this mailbox.\nAnother process has rewritten the mailbox file changing the inode.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ Messages 241-244 are header field labels for SendMsgDialog.
$ 
$ "-NEW"
241 "A"
$ "-NEW"
242 "Tema"
$ "-NEW"
243 "Cc"
$ "-NEW"
244 "Bcc"

$ 
$ Message 245 is the label for the Open command in the File menu
$ Message 246 is the label for the command in the OpenContainer menu
$	which opens Mailboxes not in the users folder list.
$ 
$ "-NEW"
245 "Abrir"
$ "-NEW"
246 "Otros Buzones..."

$ 
$ Message 247 is the label for the command in the Aliases menu
$	which opens the MailOptions dialog allowing the user to create
$	other aliases.
$ Message 248 is the label for the Aliases popup menu
$ 
$ "-NEW"
247 "Otros Alias..."
$ "-NEW"
248 "Aplicación de correo - Alias"

$ 
$ Messages 249-255 are strings used to generate attachment summaries
$                  in included messages.
$ 
$ "-NEW"
249 "------------- Begin Included Attachment -------------\n\n" 
$ "-NEW"
250 "------------- End Included Attachment -------------\n\n" 
$ "-NEW"
251 "       Attachment Name:  "
$ "-NEW"
252 "     Attachment DtType:  "
$ "-NEW"
253 "Attachment ContentType:  "
$ "-NEW"
254 "Attachment Description:  "
$ "-NEW"
255 "------------------ Attachments ------------------\n" 

$ "-NEW"
$ DTMC_SERVERACCESSFAILED:
$ Mailer failed in attempt to retrieve messages from the mail server
256 "Mail server access failed:\n%s"

$ "-NEW"
$ Label on the button which causes the "Mail Retrieval" options to be displayed
257 "Options..."

$ "-NEW"
$ DTMC_GETMAILCOMMANDFAILED:
$ Mailer failed in attempt to retrieve messages via custom getmail command
258 "User Getmail command failed:\n%s"

$ "-NEW"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
259 "%a %d %b %Y"
260 "%a %d %b %k:%M"
261 "%a %d %b %H:%M"

$ "-NEW"
262 "Mensaje Dead Letter"

$ "-NEW"
263 "The attachment '%s' is %d kilobytes.\nAdd as attachment?"



$set 2        Redefine set#


1 "Aplicación de correo"

2 "ToolTalk no está inicializado. No se puede ejecutar la Aplicación de correo\n\
sin ToolTalk.\n\
Intente iniciar /usr/dt/bin/dtsession, o consulte al administrador del sistema."

3 "No es posible inicializar ventanas. Se sale.\n"

4 "La Aplicación de correo no está instalada correctamente,\n\
y no se puede ejecutar porque el grupo de ejecución\n\
se ha establecido incorrectamente."

5 "No tiene permiso para ver %s"
$ \t    /* NL_COMMENT    
$ \t     * The %s is the name of the mailbox the user doesn't have    
$ \t     * permission to view.    
$ \t     */    

6 "El buzón %s es un directorio y no se pudo abrir."

7 "No es posible vaciar %s. No existe."

8 "El contenedor %s estaba vacío"

9 "Error - no fue posible vaciar %s"

10 "Aplicación de correo"

11 "%s"

12 "Aplicación de correo"

13 "Aplicación de correo"

14 "Es necesario seleccionar un anexo antes de emitir el\n\
mandato \"Guardar Como\" para guardar un archivo."

15 "Error - No es posible obtener mailrc."

16 "No hay mensaje seleccionado."
$ \t/* NL_COMMENT    
$ \t * No mail message has been selected by the user.    
$ \t */    

17 "Ha editado \"%s\". ¿Suprimir de todas formas?"

18 "Error: No se puede incluir el archivo %s"

19 "Es necesario seleccionar un anexo antes de emitir el\n\
mandato \"Guardar Como\" para guardar un archivo."

20 "Es necesario seleccionar un anexo antes de emitir el mandato\n\
\"Guardar Como\" para guardar un archivo."

21 "Aplicación de correo"

22 "Se encontraron errores de sintaxis irrecuperables en el archivo ~/.mailrc.\nVerifique si hay más mensajes en el terminal. Corrija los errores y vuelva a activar dtmail.\nSi continúa no podrá guardar en un archivo ningún cambio efectuado\nen el cuadro de diálogo de opciones."
23 "Continuar"
24 "Salir"
25 "Se encontraron errores de sintaxis irrecuperables en el archivo ~/.mailrc.\nEs posible aplicar las opciones de correo a la sesión actual pero\nno se pueden guardar en el archivo." 

$ 
$ Messages for file locking dialog displayed from the Advanced option pane.
$ 
$ "-NEW"
26 "The value of the file locking option has changed.\nTo take immediate effect, folders need to be closed and reopened.\n  o Click on 'Reopen' to reopen folders,\n    making the new option take effect immediately.\n  o Click on 'Continue' to avoid reopening folders.\n    The new option will take effect the next time you open a folder.\n  o Click on 'Cancel' to cancel the Apply and return to editing options."
$ "-NEW"
27 "Reopen"
$ "-NEW"
28 "Continue"
$ "-NEW"
29 "Cancel"

$ 
$ Messages for ToolTalk errors.
$ 
$ "-NEW"
30 "%s returned ToolTalk error: %s\n"


$set 3        Redefine set#


1 "Guardar automático..."

2 "Inicializando..."

3 "El buzón %s no existe.\n\
¿Crear un buzón con este nombre?"

4 "Aplicación de correo"

5 "OK"

6 "El buzón %s está bloqueado.\n\
Puede desbloquearlo manualmente e intentar de nuevo\n\
o consulte al administrador del sistema."

7 "Aplicación de correo"

8 "OK"

9 "OK"

10 "OK"

11 "OK"

12 "%s"

13 "Mensaje %d de %d, %d nuevo(s), %d suprimido(s)"

14 "Mensaje %d de %d, %d nuevo(s), %d suprimido(s)"
$ \t/* NL_COMMENT    
$ \t * The user will see the following message display as:    
$ \t * "Message 3 of 10, 2 new, 6 deleted"    
$ \t * This means ??? -- Explain to translator.    
$ \t */    

15 "Guardando..."

16 "Aplicación de correo"
$ \t\t/* NL_COMMENT    
$ \t\t * This dialog comes up when the user tries to quit the    
$ \t\t * mailbox and the user is asked if he wants to destroy    
$ \t\t * the messages marked for deletion.    
$ \t\t */    

17 "¿Destruir los mensajes que ha marcado\n\
 para supresión en este buzón?"

18 "OK"

19 "Cancelar"

20 "Abriendo el buzón..."

21 "%s ya existe.\n\
¿Sobreescribir?"

22 "Aplicación de correo"

23 "No es posible sobreescribir %s.\n\
Comprobar los permisos del archivo y volver a intentar."

24 "Aplicación de correo"

25 "Cargando contenedor..."

26 "Información Resumen de Carpeta"

27 "Cargando..."

28 "Vaciar contenedor"

29 "OK"

30 "OK"

31 "OK"

32 "Destruyendo mensajes suprimidos..."

33 "OK"

34 "%s no existe."

35 "No es posible abrir %s."

36 "No es posible asignar memoria."

37 "Resumen de anexos"

38 "anexo"

39 "anexos"
$ \t/* NL_COMMENT    
$ \t * "attachments" is the plural form of "attachment".    
$ \t */    

40 "anexos"

41 "suprimido(s)"

42 "%s ya existe. ¿Reemplazar?"

43 "No es posible reemplazar %s."

44 "No es posible crear %s."

45 "No es posible crear %s."

46 "Vaciar contenedor"

47 "%s ya existe.\n\
¿Sobreescribir?"

48 "Aplicación de correo"

49 "No es posible sobreescribir %s.\n\
Verificar los permisos del archivo e intentar de nuevo."

50 "Aplicación de correo"

51 "No es posible crear %s."

52 "Aplicación de correo"

53 "No es posible grabar en %s."

54 "Aplicación de correo"

55 "No es posible crear %s."

56 "Aplicación de correo"

57 "Renombrar anexo como"

58 "La ventana de Composición contiene texto o \n\
anexos que se perderán si se cierra la\n\
ventana.\n\
¿Cerrar la ventana de Composición?"

59 "Sin memoria"

60 "No hay suficiente memoria para cargar el archivo .vacation.msg existente."

61 "Aplicación de correo"

62 "El archivo .vacation.msg existente parece estar dañado."

63 "Seleccionar un mensaje para mover."

64 "Seleccionar un mensaje para copiar."

65 "%d mensajes movidos a %s"

66 "%d mensaje movido a %s"

67 "%d mensajes copiados a %s"

68 "%d mensaje copiado a %s"

69 "Vista ya existe. Emergiéndola."
$ \t/* NL_COMMENT    
$ \t* The current mail message selected is already displayed in a separate    
$ \t* window.  Therefore this 'separate' window will be raised in front    
$ \t* of existing windows so the user can see it.    
$ \t*/    

70 "Escribiendo letra muerta..."

71 "Aplicación de correo"

72 "OK"

73 "Cancelar"

74 "OK"

75 "OK"

76 "OK"


77 "Hay un anexo abierto que puede contener cambios que no se han guardado.\nAl enviar este mensaje se interrumpirá la conexión con el anexo\n abierto. Los cambios no guardados no formarán parte del\n mensaje. Podrá utilizar el comando Guardar como para guardar cambios después\n de que se interrumpa la conexión pero los cambios no formarán \n parte del anexo."
78 "Inicializando opciones de correo..."
79 "Destruir y salir"
80 "No destruir y salir"
81 "Este anexo puede contener comandos que puede producir serios\ndaños.  Se recomienda ejecutarlo solamente si está seguro\nde que no se producirán daños.\n\nPresione OK si está seguro de que no se producirán daños\no Cancelar para cancelar la ejecución."
82 "Otro usuario está utilizando este buzón.\n¿Desea solicitar acceso exclusivo?"
83 "Mailer no es capaz de obtener acceso exclusivo a este buzón.\n¿Desea abrir este buzón como tipo leer solamente?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "Se han eliminado %d mensajes"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "Se ha eliminado el mensaje %d"
86 "Checking for new mail..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "Aplicación de correo - Cerrar"
88 "¿Desea destruir los mensajes eliminados y cerrar este buzón?"
89 "Destruir y cerrar"
90 "Conservar y cerrar"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "No se puede ejecutar la operación no válida."
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "Falló la ejecución de la operación."
93 "El icono seleccionado %s es ejecutable.\nHaga clic en OK para ejecutarlo o en Cancelar para cancelar la operación."

94 "Mailer no puede obtener acceso exclusivo para este\nbuzón porque el sistema no responde.\n\nEsta vez solamente, podrá abrir este buzón\npara leer solamente o para leer y escribir sin acceso\nexclusivo (utilice este tipo de acceso si ninguna otra persona está utilizando este buzón)."
95 "Sólo lectura"
96 "Leer y escribir"

$ 
$ "-NEW"
$ 
$ This message appears when dtmail tries to open a mailbox which has been
$ opened by another dtmail process.
$ 
$ Parameters:
$   1.  Error message saying that the <mailbox>.dtmail lockfile has been found.
$   2.  The mailbox path.
$   3.  "OK"
$   4.  "Cancel"
$   5.  The <mailbox>.dtmail lockfile path.
$ 
97 "%s\n\nThis may indicate that another Mailer has opened\n%s\n\nYou may open this mailbox READ ONLY by choosing '%s'.\n\nOtherwise, you may choose '%s',\nmake sure that another Mailer has not opened this mailbox,\ndelete %s,\nand reopen this mailbox."

$ 
$ "-NEW"
$ 
$ Messages 98-100 check for problems in the paths specified by users of
$ the file selection box.
$ 
98 "Search permission denied on a component of the path prefix,\n'%s'."
99 "A component of the path prefix is not a directory,\n'%s'."
100 "A component of the path prefix does not exist,\n'%s'."



$set 5        Redefine set#


1 "Aplicación de correo"

2 "Aplicación de correo"

3 "El enviar este mensaje tal como está\n\
\t    ocasionará que pierda los cambios\n\
\t    efectuados a los anexos."
$    /* NL_COMMENT    
$     * The user tried to send a messages without saving changes in    
$     * some open attachments.  This warning makes sure that is what    
$     * the user intended.    
$     */    

4 "Seleccionar un anexo\n\
\t    y, después, elegir renombrar"
$       /* NL_COMMENT    
$        * Mailer ran out of memory.  Ask the user to quit some other    
$        * applications so there will be more memory available.    
$        */    

5 "Alguna de las direcciones del mensaje es incorrecta,\n\
y no se refiere a ningún usuario del sistema.\n\
Por favor, asegúrese de que todas las direcciones son correctas\n\
e inténtelo de nuevo."
$       /* NL_COMMENT    
$        * Mailer ran out of memory.  Ask the user to quit some other    
$        * applications so there will be more memory available.    
$        */    

6 "La aplicación de correo no tiene suficiente memoria\n\
disponible para enviar este mensaje.\n\
Intente abandonar otra aplicación y vuelva a enviar\n\
este mensaje."
$       /* NL_COMMENT    
$        * There was an error from the mail transport (sendmail).    
$        */    

7 "Se ha producido un error al intentar enviar el mensaje.\n\
Asegúrese de que el mensaje se ha recibido. Si no,\n\
tendrá que volver a enviarlo."

$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "Intente enviar después de especificar los destinatarios de los mensajes en los campos \nA:, Cc: y Cs:."

$set 12        Redefine set#


1 "Anexo"

2 "Anexos"

3 "mostrarCuenta"

4 "No se pueden anexar archivos FIFO: %s"

5 "No se pueden anexar archivos especiales de caracteres: %s"

6 "No se pueden anexar directorios: %s"

7 "No se pueden anexar archivos especiales de bloques: %s"

8 "No se pueden anexar archivos de zócalos: %s"

$set 13        Redefine set#


1 "No se puede crear"

2 "No se puede grabar"
$     
$ Strings from dtmail/AttachCmds.C    

$set 14        Redefine set#


1 "Añadir Anexo"

2 "No es posible abrir %s"

3 "No se pueden anexar archivos FIFO: %s"

4 "No se pueden anexar archivos especiales de caracteres: %s"

5 "No se pueden anexar directorios: %s"

6 "No se pueden anexar archivos especiales de bloques: %s"

7 "No se pueden anexar archivos de zócalos: %s"

8 "No es posible abrir %s"

9 "Aplicación de correo - Renombrar Anexo"

10 "Descripción"

11 "Guardar Anexo Como"




$set 15
1 "Ha realizado cambios y no los ha guardado. \nPodrá guardar o descartar los cambios\no volver al lugar anterior del cuadro de diálogo."
2 "Guardar"
3 "Descartar"
$ 
$ The followings are added by IBM for 41J release
$ 
$set 20
1 "El buzón %s ya está abierto."
$ The above message is used in RoamMenuWindow::open
$ See AIXC cmvc defect 175920
2 "Utilizar nombre local: "
$ The above message is used in OptCmd::init_advanced_pane()
$ see AIX cmvc defect 176608
3 "Sólo lectura"
$ The above message is used in RoamMenuWindow::mapnotify()
$ see AIX cmvc defect 176608

$ 
$	SETS 21 - 25 WERE ADDED TO SUPPORT CDEnext PRINTING
$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$set 21
$ 
$	Messages 1 - 11 are used in DmxPrintJob.
$ 
$ 
$	This is the status message that gets displayed in the MainWindow
$	and RoamMenuWindow status lines when a print job is being executed.
$	The '%s' is the name of the temporary file containing the message(s)
$	to be printed.
1 "Imprimiendo %s ..."

$	Messages 2 - 4 are used in the error popup which gets displayed
$	when an invalid margin specifier has been supplied by the user.
$ 
$	Message 2 is the actual error messagactual error message
$	Message 3 is the title which is displayed in the error popup.
$	Message 4 is the label on the OK button of the error popup.
2 "La sintaxis de uno de los especificadores de margen es incorrecta: \n %s \n %s \n %s \n %s \n¿Desea continuar utilizando los márgenes predeterminados?"
3 "Mailer"
4 "OK"

$	Messages 5 - 11 are format string used to construct the header
$	and footer strings which appear in the printing output.
$ 
$	Message 5 is the format string used to make a Cc header/footer.
$	Message 6 is the format string used to make a Date header/footer.
$	Message 7 is the format string used to make a From header/footer.
$	Message 8 is the format string used to make a Subj't header/footer.
$	Message 9 is the format string used to make a To header/footer.
$	Message 10 is the format string used to make a Page# header/footer.
$	Message 11 is the format string used to make a UserName header/footer.
5 "Cc:  %s"
6 "Fecha:  %s"
7 "De:  %s"
8 "Tema:  %s"
9 "A:  %s"
10 "Página %d de %d"
11 "Correo para:  %s"

$ 
$	Messages 12 - 13, 20 are used in DmxPrintSetup to construct the
$	app-specific printing options for DtMail which will be included
$	in the DtPrintSetupBox.
$ 
$	Message 12 is the label used on the Toggle Button to indicate that
$	multiple messages should be printed in separate spool jobs.
$	Message 13 is the label used on the Toggle Button to indicate that
$	lines which would extend beyond the edge of the printed page be 
$	"wrapped" to the next line.
12 "Impresión individual"
13 "Usar ajuste de texto"


$	Messages 14 - 15 are status messages for the PrintToFile function.
$ 
$	Message 14 indicates that the PrintToFile function was unsuccessful.
$	Message 15 indicates that the PrintToFile function was successful.
$       NOTE:  'Print to File' should be translated as in DtPrint.msg
$               Set 1, Message 3.
14 "'Imprimir en archivo' no funcionó."
15 "'Imprimir en archivo' se ejecutó correctamente."

$       NL_COMMENT 
$          Messages 16 - 19 are obsolete, and have been replaced by 24
$ 
$	Messages 16 - 19 are status messages for the popup PDM function.
$ 
$	Message 16 indicates that there was no pdm deamon running.
$	Message 17 indicates that the pdm deamon was unable to start a pdm.
$	Message 18 indicates that the pdm couldnt connect to the video display.
$	Message 19 indicates that the pdm couldnt connect to the print display.
16 "No se encontró ningún PDM en el entorno."
17 "No se puede activar PDM."
18 "PDM no está autorizado para conectarse con la pantalla de video."
19 "PDM no está autorizado para conectarse con la pantalla de impresión."

$	Message 20 is the label used on the Push Button to bring up
$	the printing options dialog from the DtPrintSetupDialog.
20 "Más..."
$       Message 21 is used for the title string on the DtPrintSetupDialog.
21 "Mailer - Configurar impresión"

$       Message 22 is used to alert the user to the fact that the mailer
$                  cannot close the mailer window until a task (usually
$                  a print job) has terminated.
22 "Cerrar pendientes:  esperando a que termine la ejecución de la tarea..."

$	Message 23 is used to alert the user to the fact that the X Print
$		   Server cannot complete the print request due to a lack
$		   of resources.
23 "El servidor de impresión X está temporalmente sin recursos. "

$       Messages 24 & 25 are used to handle errors from the PDM
24	"Error del Administrador de diálogo de impresión (PDM) - Falló la configuración."
25	"Continuar"




$ 
$	The messages in this set are used in pulldown menu for the
$	header/footer $	frame which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 8 are used in DmxPrintOptions.
$ 
$ 
$	Message 1 specifies that the page header/footer field be empty.
$	Message 2 put the Cc msg header in the page header/footer field.
$	Message 3 put the Date msg header in the page header/footer field.
$	Message 4 put the From msg header in the page header/footer field.
$	Message 5 put the Subject msg header in the page header/footer field.
$	Message 6 put the To msg header in the page header/footer field.
$	Message 7 put the Page Nmbr msg header in the page header/footer field.
$	Message 8 put the User Name msg header in the page header/footer field.
$set 22
1 "Vacío"
2 "Encabezamiento CC"
3 "Encabezamiento de fecha"
4 "Encabezamiento del remitente"
5 "Encabezamiento del asunto"
6 "Encabezamiento del destinatario"
7 "Número de página"
8 "Nombre de usuario"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 4 are used in DmxPrintOptions.
$ 
$	Message 1 don't print any message headers.
$	Message 2 print the "standard" msg headers (To, From, Subject, Cc).
$	Message 3 print the "abbreviated" msg headers as defined by the user.
$	Message 4 print all message headers.
$ 
$set 23

1 "Ninguno"
2 "Estándar"
3 "Abreviados"
4 "Todos"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 5 are used in DmxPrintOptions.
$ 
$	Message 1 use a New Line (CRLF) to separate multiple messages.
$	Message 2 use a Blank Line (2xCRLF) to separate multiple messages.
$	Message 3 use a Line of characters to separate multiple messages.
$	Message 4 start each new message on a new page.
$	Message 5 print each message in it's own spool job.
$ 
$set 24
1 "Nueva línea"
2 "Línea en blanco"
3 "Línea de caracteres"
4 "Nueva página"
5 "Nueva tarea"

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1 - 2 are used in DmxPrintOptions.
$ 
$ 
$set 25
$ 
$	Label for the option menu used to specify which message headers are
$	printed.
1 "Encabezamientos de mensajes impresos:  "
$ 
$	Label for the option menu used to specify which how multiple messages
$	are separated.
2 "Separación de mensajes múltiples:  "

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1-4 are used in error dialogs to indicate an invalid
$		     entry for margin specifiers in the printing options pane.
$	Message 5 is the label string on the button to dismiss the error dialog.
$ 
$ 
$set 26
1 "El especificador del margen superior no es válido:  "
2 "El especificador del margen derecho no es válido:  "
3 "El especificador del margen inferior no es válido:  "
4 "El especificador del margen izquierdo no es válido:  "
5 "Continuar"

$ 
$	The following set was added to support the Mail Retrieval option pane.
$ 
$	Messages 1-5 Used in the Server Protocol option menu to indicate the
$		     set of mail server network protocols which are supported.
$	Messages 6-15 Are used to label the options in the pane.
$ 
$ "-NEW"
$ 
$set 27
1 "Auto"
2 "POP3"
3 "APOP"
4 "IMAP"
5 "POP2"

6 "Automatic (system) delivery"

7 "Mail server retrieval"
8 "Server Protocol:"
9 "Server Name:"
10 "User Name:"
11 "Password:"
12 "Remember password"
13 "Delete from server after retrieval"
14 "Retrieve old messages"

15 "Custom retrieval"
16 "User Getmail command:"

17 "Null INBOX path."
18 "INBOX folder path:"

