$ $XConsortium: dtprintinfo.msg /main/5 1996/10/19 14:46:38 rws $
$ 
$   COMPONENT_NAME: desktop
$ 
$   FUNCTIONS: none
$ 
$   ORIGINS: 27,118,119,120,121
$ 
$   This module contains IBM CONFIDENTIAL code. -- (IBM
$   Confidential Restricted when combined with the aggregated
$   modules for this product)
$   OBJECT CODE ONLY SOURCE MATERIALS
$ 
$   (C) COPYRIGHT International Business Machines Corp. 1995
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 
$ +SNOTICE
$ 
$  $XConsortium: dtprintinfo.msg /main/5 1996/10/19 14:46:38 rws $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  SunXSQUOTEs specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  SunXSQUOTEs request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 
$		     Common Desktop Environment
$ 
$   (c) Copyright 1993, 1994, 1995 Hewlett-Packard Company
$   (c) Copyright 1993, 1994, 1995 International Business Machines Corp.
$   (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
$   (c) Copyright 1993, 1994, 1995 Novell, Inc.
$   (c) Copyright 1995 Digital Equipment Corp.
$   (c) Copyright 1995 Fujitsu Limited
$   (c) Copyright 1995 Hitachi, Ltd.
$                                                                   
$ 
$                     RESTRICTED RIGHTS LEGEND                              
$ 
$ Use, duplication, or disclosure by the U.S. Government is subject to
$ restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
$ Technical Data and Computer Software clause in DFARS 252.227-7013.  Rights
$ for non-DOD U.S. Government Departments and Agencies are as set forth in
$ FAR 52.227-19(c)(1,2).
$ 
$ Hewlett-Packard Company, 3000 Hanover Street, Palo Alto, CA 94304 U.S.A.
$ International Business Machines Corp., Route 100, Somers, NY 10589 U.S.A. 
$ Sun Microsystems, Inc., 2550 Garcia Avenue, Mountain View, CA 94043 U.S.A.
$ Novell, Inc., 190 River Road, Summit, NJ 07901 U.S.A.
$ Digital Equipment Corp., 111 Powdermill Road, Maynard, MA 01754, U.S.A.
$ Fujitsu Limited, 1015, Kamikodanaka Nakahara-Ku, Kawasaki 211, Japan
$ Hitachi, Ltd., 6, Kanda Surugadai 4-Chome, Chiyoda-ku, Tokyo 101, Japan

$quote XDQUOTE

$set DTPRINTER_SET
$ ----- These are the titles that appear on dialogs and the main window -----    

ApplicationName1L "Gestor de impresión"

ApplicationName2L "Trabajos de impresión"
$ Do not translate ApplicationName3L for this release    

ApplicationName3L "Impresoras del escritorio"
$ ----- Common Dialog Buttons -----    

YesL "Sí"

NoL "No"

OKL "OK"

ApplyL "Aplicar"

CancelL "Cancelar"

HelpL "Ayuda"
$ ----- Find dialog -----    

FindTitleL "%s - Buscar trabajos de impresión"

MyJobNameL "Mi nombre de trabajo"

OnlyRootJobsL "Sólo trabajos root"

IgnoreCaseL "Ignorar mayúsculas"

ExactMatchL "Coincidencia exacta"

GotoL "Ir a"

CancelPrintJobsL "Cancelar trabajos de impresión"

PositionL "Posición"

CloseL "Cerrar"

StartFindL "Iniciar buscar"

StopFindL "Detener buscar"

SearchL "Buscando %s...\n\n\
Pulse Detener para interrumpir"
$ Find Information dialog messages    

NoMatchesL "No hay trabajos de impresión coincidentes"

NotFoundMessageL "El trabajo de impresión ya no existe o\n\
la impresora está cerrada."
$ ----- Modify Show Dialog -----    

ModifyShowTitleL "%s - Modificar el Mostrar Lista"

SelectPrintersToBeShowL "Seleccionar las impresoras a mostrar"

SelectAllL "Seleccionar todo"

DeselectAllL "Deseleccionar todo"
$ ----- Set Options Dialog -----    

SetOptionsTitleL "%s - Establecer opciones"

RepresentationL "Representación"

LargeIconL "Icono grande"

SmallIconL "Icono pequeño"

NameOnlyL "Sólo nombre"

DetailsL "Detalles"

ShowLabelsL "Mostrar etiquetas"

JobsToShowL "Trabajos a mostrar"

OnlyMineL "Sólo el mío"

EveryoneL "Los de todos"

StatusL "Estado"

ProblemFlagL "Problema distintivo"

InformationLineL "Línea de mensajes"

UpdateIntervalL "Actualizaciones"

IntervalL "Intervalo (en segundos)"
$ ----- Print Job Properties Dialog -----    

PrintJobPropsTitleL "%s - Imprimir propiedades del trabajo"

PrinterL "Impresora"

JobName1L "Nombre del trabajo"

SubmittedL "Sometido"

BytesL "bytes"

Position1L "Posición:"

JobNameL "Nombre del trabajo:"

JobNumberL "Número de trabajo:"

OwnerL "Propietario:"

DateL "Fecha:"

TimeL "Hora:"

SizeL "Tamaño:"
$ ----- Printer Properties Dialog -----    

PrinterPropsTitleL "%s - Propiedades de impresora"

IconLabelL "Etiqueta de icono:"

IconGroupTitleL "Iconos:"

FindSetL "Buscar conjunto..."

DescriptionL "Descripción:"

PrinterStatusL "Estado:"

PrintQueueL "Cola de impresora:"

DeviceL "Nombre de dispositivo:"

DeviceNL "Dispositivo %d:"

UpL "Activar - En servicio"

DownL "Desactivar - Fuera de servicio"

PrinterOnServerL "%1$s en %2$s"

DefaultDescriptionL "Esta es la cola de impresora %s."
$ %1 is the printer name and %2 is the server name, ex: "lp0 on warpspeed"    
$ This is the value of the device field when the printer is on a remote system    
$ ----- Find Set Dialog -----    

FindSetTitleL "%s - Buscar conjunto"

IconFoldersL "Carpetas de iconos:"

IconTitleL "Iconos"

LoadingIconsL "Cargando los iconos %1$d de %2$d..."
$ %1 is a counter and %2 is the total number of icons    
$ ----- "Cancel" Print Job Confirmation Dialog -----    

CancelTitleL "%s - Cancelar %s"

CancelQuestionL "¿Está seguro de que desea cancelar %s?"
$ ----- Printer "Status" Dialog -----    

PrinterStatusTitleL "%s - Estado de la impresora"

PrinterDownL "La cola de impresora %s está fuera de servicio."

DeviceDownL "El dispositivo %s está fuera de servicio."
$ ----- Failed Action Dialog -----    

FailedActionTitleL "%s - %s ha fallado"

FailedMessageL "No se pudo aplicar la acción '%s' para\n\
  %s.  Ver la razón más abajo.\n\n\
%s"
$ ----- Main Window Information Line Messages -----    

GettingHelpL "Obteniendo Ayuda en línea..."

SearchingL "Buscando impresoras..."

ShowingMyJobsL "Mostrando sólo mis trabajos"

PrintersHiddenL "%d Impresoras %d Ocultas"

JobsL "%d Trabajos"

UpdatingActionsL "Actualizando la base de datos de acciones..."

UpdatingL "Actualizando %s..."
$ Do not translate EditLangL for this release    

EditLangL "Editando en /etc/dt/appconfig/types/%s"
$ %s is the name of the printer    
$ ----- Printer Menu Messages -----    

PrinterMenuL "Impresoras"

PrinterAcceleratorL "I"

FindChoiceL "Buscar..."

FindMnemonicL "B"

FindAcceleratorL "Control+F"

ExitChoiceL "Salir"

ExitMnemonicL "a"

ExitAcceleratorL "Alt+F4"
$ ----- Selected Menu Messages -----    

SelectedMenuL "Seleccionado"

SelectedAcceleratorL "S"
$ For Print Jobs Only - "Cancel" means to remove a print job from the printer.    
$                       This choice pops up the "Cancel" Print Job Confirmation    
$                       Dialog.     

CancelChoiceL "Cancelar"

CancelMnemonicL "C"

CancelAcceleratorL "Supr"
$ For Printers Only    

OpenChoiceL "Abrir"

OpenMnemonicL "A"

CloseChoiceL "Cerrar"

CloseMnemonicL "C"

HideChoiceL "Ocultar"

HideMnemonicL "u"
$ Do not translate RenameChoiceL for this release    

RenameChoiceL "Renombrar"
$ Do not translate RenameMnemonicL for this release    

RenameMnemonicL "R"
$ Do not translate StartChoiceL for this release    

StartChoiceL "Iniciar poner en cola"
$ Do not translate StartMnemonicL for this release    

StartMnemonicL "i"
$ Do not translate StopChoiceL for this release    

StopChoiceL "Detener poner en cola"
$ Do not translate StopMnemonicL for this release    

StopMnemonicL "D"
$ Do not translate EnableChoiceL for this release    

EnableChoiceL "Habilitar impresión"
$ Do not translate EnableMnemonicL for this release    

EnableMnemonicL "H"
$ Do not translate DisableChoiceL for this release    

DisableChoiceL "Inhabilitar impresión"
$ Do not translate DisableMnemonicL for this release    

DisableMnemonicL "h"
$ For Both Printers and Print Jobs    

PropertiesChoiceL "Propiedades..."

PropertiesMnemonicL "r"

PropertiesAcceleratorL "Control+Retroceso"

HelpChoiceL "Ayuda"

HelpMnemonicL "A"
$ ----- View Menu Messages -----    

ViewMenuL "Vista"

ViewAcceleratorL "V"

SetOptionsChoiceL "Establecer opciones..."

SetOptionsMnemonicL "o"

ModifyShowChoiceL "Modificar el Mostrar Lista..."

ModifyShowMnemonicL "f"
$ ----- Help Menu Messages -----    
$ "Help" Menu uses the "HelpChoiceL" message    
$ "Help" Accelerator uses the "HelpMnemonicL" message    

OverviewChoiceL "Información general"

OverviewMnemonicL "g"

TaskChoiceL "Tareas"

TaskMnemonicL "T"

ReferenceChoiceL "Referencia"

ReferenceMnemonicL "R"

OnItemChoiceL "Sobre el tema"

OnItemMnemonicL "S"

UsingHelpChoiceL "Uso de la ayuda"

UsingHelpMnemonicL "U"

AboutChoice1L "Acerca del Gestor de impresión"

AboutChoice2L "Acerca de los trabajos de impresión"
$ Do not translate AboutChoice3L for this release    

AboutChoice3L "Acerca de las impresoras del escritorio"

AboutMnemonicL "A"
$ ----- Misc Messages -----    

EmptyL "[ Empty ]"

FoundNoPrintersL "No se han encontrado impresoras."

NotAvailableL "no disponible"

NoDefaultPrinter1L "No hay impresora predeterminada del sistema."

NoDefaultPrinter2L "Consultar la Guía del Usuario para obtener explicación\n\
de cómo establecer el entorno de impresora\n\
LPDEST."
$ %1 is the name of the program, and %2 is either '-edit' or '-populate'.    

RootUserL "%1$s: Debe ser root para utilizar la opción %2$s."
$ ----- Command Line Help -----    
$ This message is show when the user enters 'dtprintinfo -help'    
$ on the command line. The %s is a printer list generated by the program.    

CommandLineHelpL "dtprintinfo\n\n\
    Al iniciar dtprintinfo sin ninguna opción, muestra la impresora \n\
    LPDEST o la predeterminada del sistema si no se ha establecido LPDEST.\n\n\
dtprintinfo -p <impresora>\n\n\
    Para ver una impresora específica, use la opción -p y uno de los\n\
    siguientes nombres de cola de impresión:\n\n\
%s\n\
dtprintinfo -all\n\n\
    Para ver todas las impresoras, use la opción -all.\n\n\
dtprintinfo -populate\n\n\
    La opción -populate está disponible sólo para root. Esta opción\n\
    crea las acciones predeterminadas de impresora para todas las impresoras\n\
    en /etc/dt/appconfig/types/LANG. Si no se define LANG, las acciones se\n\
    crean en /etc/dt/appconfig/types/C."

NoRemoteCancelL "El servidor de impresión no suministró el número de tarea de impresión.\nAlgunos servidores de impresión no permiten cancelar tareas de impresión\nde forma remota.  Si sabe que el servidor en cuestión permite cancelar de forma remota, \npóngase en contacto con el administrador del servidor de impresión."
FindAcceleratorKeySeq "Ctrl<Key>f"
