/*
 * CDE - Common Desktop Environment
 *
 * Copyright (c) 1993-2012, The Open Group. All rights reserved.
 *
 * These libraries and programs are free software; you can
 * redistribute them and/or modify them under the terms of the GNU
 * Lesser General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * These libraries and programs are distributed in the hope that
 * they will be useful, but WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with these libraries and programs; if not, write
 * to the Free Software Foundation, Inc., 51 Franklin Street, Fifth
 * Floor, Boston, MA 02110-1301 USA
 */
/*
 * $XConsortium: WXawPanner.h /main/3 1996/06/11 16:46:31 cde-hal $
 *
 * Copyright (c) 1991 HaL Computer Systems, Inc.  All rights reserved.
 * UNPUBLISHED -- rights reserved under the Copyright Laws of the United
 * States.  Use of a copyright notice is precautionary only and does not
 * imply publication or disclosure.
 * 
 * This software contains confidential information and trade secrets of HaL
 * Computer Systems, Inc.  Use, disclosure, or reproduction is prohibited
 * without the prior express written permission of HaL Computer Systems, Inc.
 * 
 *                         RESTRICTED RIGHTS LEGEND
 * Use, duplication, or disclosure by the Government is subject to
 * restrictions as set forth in subparagraph (c)(l)(ii) of the Rights in
 * Technical Data and Computer Software clause at DFARS 252.227-7013.
 *                        HaL Computer Systems, Inc.
 *                  1315 Dell Avenue, Campbell, CA  95008
 * 
 */

// This code is automatically generated by hand in -*- C++ -*-
#ifndef _WXawPanner_h
#define _WXawPanner_h

#include "WXawSimple.h"
#include <X11/StringDefs.h>
#include <X11/Xaw/Panner.h>

class WXawPanner : public WXawSimple {
public :
  DEFINE_INIT (WXawPanner, WXawSimple, pannerWidgetClass)

  DEFINE_GETTER_SETTER (AllowOff, Boolean, XtNallowOff)
  DEFINE_GETTER_SETTER (BackgroundStipple, String, XtNbackgroundStipple)
  DEFINE_GETTER_SETTER (CanvasWidth, Dimension, XtNcanvasWidth)
  DEFINE_GETTER_SETTER (CanvasHeight, Dimension, XtNcanvasHeight)
  DEFINE_GETTER_SETTER (DefaultScale, Dimension, XtNdefaultScale)
  DEFINE_GETTER_SETTER (Foreground, Pixel, XtNforeground)
  DEFINE_GETTER_SETTER (InternalSpace, Dimension, XtNinternalSpace)
  DEFINE_GETTER_SETTER (LineWidth, Dimension, XtNlineWidth)
  DEFINE_GETTER_SETTER (Resize, Boolean, XtNresize)
  DEFINE_GETTER_SETTER (RubberBand, Boolean, XtNrubberBand)
  DEFINE_GETTER_SETTER (ShadowColor, Pixel, XtNshadowColor)
  DEFINE_GETTER_SETTER (ShadowThickness, Dimension, XtNshadowThickness)
  DEFINE_GETTER_SETTER (SliderHeight, Dimension, XtNsliderHeight)
  DEFINE_GETTER_SETTER (SliderWidth, Dimension, XtNsliderWidth)
  DEFINE_GETTER_SETTER (SliderX, Position, XtNsliderX)
  DEFINE_GETTER_SETTER (SliderY, Position, XtNsliderY)

// Constraint Resources -- Valid only in a form

   DEFINE_GETTER_SETTER (TopAttachment,unsigned char,"topAttachment")
   DEFINE_GETTER_SETTER (BottomAttachment,unsigned char,"bottomAttachment")
   DEFINE_GETTER_SETTER (LeftAttachment,unsigned char,"leftAttachment")
   DEFINE_GETTER_SETTER (RightAttachment,unsigned char,"rightAttachment")
   DEFINE_GETTER_SETTER (TopWidget,Widget,"topWidget")
   DEFINE_GETTER_SETTER (BottomWidget,Widget,"bottomWidget")
   DEFINE_GETTER_SETTER (LeftWidget,Widget,"leftWidget")
   DEFINE_GETTER_SETTER (RightWidget,Widget,"rightWidget")
   DEFINE_GETTER_SETTER (TopPosition,int,"topPosition")
   DEFINE_GETTER_SETTER (BottomPosition,int,"bottomPosition")
   DEFINE_GETTER_SETTER (LeftPosition,int,"leftPosition")
   DEFINE_GETTER_SETTER (RightPosition,int,"rightPosition")
   DEFINE_GETTER_SETTER (TopOffset,int,"topOffset")
   DEFINE_GETTER_SETTER (BottomOffset,int,"bottomOffset")
   DEFINE_GETTER_SETTER (LeftOffset,int,"leftOffset")
   DEFINE_GETTER_SETTER (RightOffset,int,"rightOffset")
   DEFINE_GETTER_SETTER (Resizable,Boolean,"resizable")

  DEFINE_CALLBACK (ReportCallback, XtNreportCallback)
};

#define	NULLWXawPanner   WXawPanner((Widget)0)

#endif /* _WXawPanner_h */
/* DO NOT ADD ANY LINES AFTER THIS #endif */
