/* XPM */
/* $XConsortium: stylemgr.pm /main/2 1996/07/23 12:42:40 drk $ */
static char * VIctrStyMgr_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 22 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	c #E0E0E0E0E0E0",
"X	c #E1E1E1E1E1E1",
"o	c #4B4B4B4B4B4B",
"O	c #C8C8C8C8C8C8",
"+	c #AEAEAEAEAEAE",
"@	c #AFAFAFAFAFAF",
"#	c #F9F9F9F9F9F9",
"$	c #C7C7C7C7C7C7",
"%	s iconColor8	m black	c magenta",
"&	c #FFFF0000ABAB",
"*	s iconColor6	m white	c yellow",
"=	s iconColor1	m black	c black",
"-	c #FFFF00000202",
";	c #959595959595",
":	c #7D7D7D7D7D7D",
"?	c #04040000FFFF",
">	c #0909FFFF0101",
",	c #646464646464",
"<	s iconColor5	m black	c blue",
"1	c #969696969696",
"2	c #323232323232",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"       ..................XXXXXXXXXXXXXXXoO      ",
"       .+++++++++++++++++@@@@@@@@@@@@@@XoO      ",
"       .+++++++++++++++++@@@@@@@@X #######XO    ",
"       .++...............XXXXXX##O$$$$%&%$$###  ",
"       .++.++++++++++oX++@@@@##O$$$$$%&%&o$$$O# ",
"       .++.++++++++++oX++@@@#O$$****$&%&%o$$$$= ",
"       .++.++++++++++oX++@@#O$$****-$$ooo$$$$O= ",
" ======o++.++......++oX++@#O$$$****-$$$$$$$$O=  ",
"        o+.++.ooooo++oX++#O$$$$$*--$$;===$$O=   ",
"  oooooO o.++++++++++oX++#$$--$$$$$$$=::O$O=    ",
"  :::::OOo.++++++++++oX++#$---=$$##$$=XXO$O:XXX ",
"       ::o.++++++++++oX++#$---=$#???$$$$$$$$$$o ",
"        Oo.oooooooooooXoo#$$==$$?????$>?>?>$$$o ",
"       :::oOOOOOOOOOOOOOO,OOOOOO<<<?=$?>?>OO$o= ",
"       OOOo111111111111111,2OOOOO<<?=$>?>oOO1=  ",
"   XX........XX11111111111122=OOOOO$$$??o$O2=   ",
"  XOOOOOOOOOOOO11;;;;;;;;1111===@OOO$$$$O:2:    ",
" XOXXX;XXX;XXX;@o;;;;;;;;111111===========:     ",
" XOX@+,X@@,X@+,@o,1111############::::::o,      ",
" XOX@@,X@@,X@@,@o,:111##===##===##=11111oO      ",
" XOX++,X++,X@+,@o,:111#=:::##=:::#=:1111oO      ",
" XOX++,X++,X@+,@o,:111#=::1##=111#=:1111oO      ",
" XO:::@:::@:::O@o,:111==:11##=111==:1111oO      ",
" XOOOOOOOOOOOOO+o,:1111::11##=1111::1111oO      ",
" XOX$X$X$X$X$X$+o,:11111111##=1########OoO      ",
" XXXXXXXXXXXX.X+o2ooooooooo##=o#==##==#=oO      ",
" XXXXXXXXXXXXXX+o,,OOOOOOOO##= #=O##=O#=OO      ",
" XOX$X$X$X$X$X$+o,:       O##= ==O##= ==OO      ",
" XO$O$O$O$O$O$O+o,:       O##=   O##=  OOOOOO   ",
" X@O+O+O+O+O+O+;o,:       O##=   O##= O#####O   ",
" X@++++++++++++;o,:       O##=   O##= O#=#=#=   ",
" X1+;+;+;+;+;+;:o,:      OO##=OO O##=  ==#===   ",
" X11;;;;;;;;;;;1o,:     O######=OO##=   O#=     ",
" X11;;;;;;;;;;:1o,:      =======:####=  O#=     ",
" X:;:;:;:;:;:;:1o,:       :::::::===== O###=    ",
" X::::::::::::::o,:               ::::: ====:   ",
"  ,::::::::::::2,,:                      ::::   ",
"   ,ooooooooooo,,::                             ",
"    ,,,,,,,,,,,,::                              ",
"      ::::::::::::                              ",
"                                                ",
"                                                ",
"                                                "};
