$ message catalog of dtimsstart
$ @(#)$XConsortium: dtimsstart.msg /main/4 1996/08/19 11:35:10 pascale $

$set 1
$ 	usage
1 Usage:  %s  [options ..]
2 print modified environment variables
3 override $SHELL
4 specifies input method name
5 specifies command options for input method server
6 specifies host where input method server should be run
7 change input method selection mode
8 print registered input method
9 show this message

$ 	selection mode
$ please do not translate ask_at_login and resume_current_input_method
20 SelectMode
21 ask_at_login
22 resume_current_input_method
23 force 'resume_current_input_method' mode
24 force 'ask_at_login' mode

$ 	error messages
31 invalid option '%s'
32 environment variable 'HOME' not defined
33 environment variable 'LANG' not defined
34 this locale is not supported by the desktop.
35 environment variable 'DISPLAY' not defined
36 cannot open file\n  [%s]
37 cannot create file\n  [%s]
38 cannot create directory\n  [%s]
39 missing '%s' entry in configuration file\n  [%s]
40 another '%s' is already running
41 no selection file for '%s'
42 cannot create selection file\n  [%s]
43 no ims selected for '%s'
44 no locale configuration file for '%s'
45 no ims configured for '%s'
46 no ims configuration file for '%s'
47 ims '%s' not registered
48 no executable file for '%s'\n  [%s]
49 ims '%s' is already running
50 cannot execute ims '%s'
51 ims '%s' aborted.  See log file.\n  [%s]
52 ims '%s' is not available yet
53 unknown host '%s'
54 action '%s' failed
55 remote execution failed on '%s'
56 remote functionality is not available on '%s'
57 no ims registered on '%s'
58 ims '%1$s' not registered on '%2$s'
59 cannot open display '%s'

$ 
