# %%  (c) Copyright 1993, 1994 Hewlett-Packard Company			
# %%  (c) Copyright 1993, 1994 International Business Machines Corp.	
# %%  (c) Copyright 1993, 1994 Sun Microsystems, Inc.			
# %%  (c) Copyright 1993, 1994 Novell, Inc. 				
# %%  $XConsortium: Makefile.shipped /main/3 1995/10/20 17:03:37 rswiston $ 			 				
all:
	(cd libCoEd; ${MAKE} g.a)
	(cd CoEd; ${MAKE})
	tt_type_comp CoEd.types

clean:
	(cd libCoEd; ${MAKE} -i clean)
	(cd CoEd; ${MAKE} -i clean)
	$(RM) CoEd.types.deps
