$ message catalog of dtimsstart
$ @(#)$XConsortium: dtimsstart.msg /main/2 1996/10/19 15:26:40 rws $

$set 1
$ 	usage
1 Syntaxe :  %s  [options ..]
2 imprimer les variables d'environnement modifiées
3 annuler $SHELL
4 spécifie la méthode d'entrée
5 spécifie les options de commande du serveur de méthode d'entrée
6 spécifie l'hôte sur lequel le serveur de méthode d'entrée est exécuté
7 modifier le mode de sélection de méthode d'entrée
8 imprimer la méthode d'entrée enregistrée
9 Afficher ce message

$ 	selection mode
$ please do not translate ask_at_login and resume_current_input_method
20 Sélectionner le mode
21 ask_at_login
22 resume_current_input_method
23 force 'resume_current_input_method' mode
24 force 'ask_at_login' mode

$ 	error messages
31 option '%s'incorrecte
32 la variable d'environnement 'HOME' n'est pas définie
33 la variable d'environnement 'LANG' n'est pas définie 
34 le bureau ne prend pas en charge cet environnement du pays.
35 la variable d'environnement 'DISPLAY' n'est pas définie 
36 impossible d'ouvrir le fichier\n  [%s]
37 impossible de créer le fichier\n  [%s]
38 impossible de créer le répertoire\n  [%s]
39 l'entrée '%s' introuvable dans le fichier de configuration\n  [%s]
40 un autre '%s' est déjà en cours d'exécution
41 pas de fichier de sélection pour '%s'
42 impossible de créer un fichier de sélection\n  [%s]
43 aucun ims sélectionné dans '%s'
44 pas de fichier de configuration d'environnement du pays dans '%s'
45 aucun ims configuré dans '%s'
46 aucun fichier de configuration pour '%s'
47 ims '%s' n'est pas enregistré
48 pas de fichier exécutable pour '%s'\n  [%s]
49 ims '%s' est en cours d'exécution
50 exécution de l'ims '%s'impossible
51 ims '%s' annulé. Voir le fichier journal.\n  [%s]
52 ims '%s' n'est pas encore disponible
53 hôte inconnu '%s'
54 action '%s' a échoué
55 l'exécution éloignée a échoué sur '%s'
56 la fonctionalité éloignée n'existe pas sur '%s'
57 pas de ims enregistré sur '%s'
58 ims '%1$s' n'est pas enregistré sur '%2$s'
59 impossible d'ouvrir l'écran '%s'

$ 
