$    
$ +SNOTICE   
$    
$  $TOG: DtMail.msg /main/43 1999/09/14 15:45:19 mgreess $   
$    
$  RESTRICTED CONFIDENTIAL INFORMATION:   
$    
$  The information in this document is subject to special   
$  restrictions in a confidential disclosure agreement between   
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this   
$  document outside HP, IBM, Sun, USL, SCO, or Univel without   
$  Sun's specific written approval.  This document and all copies   
$  and derivative works thereof must be returned or destroyed at   
$  Sun's request.   
$    
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.   
$    
$ +ENOTICE   
$    
$    
$ Strings from dtmail/RoamApp.C   
$quote "

$set 1

1 "OK"

2 "Options de courrier..."

3 "Congé"

4 "Mise à jour des caractéristiques..."
$    
$ Strings from dtmail/RoamMenuWindow.C   

5 "Annuler"

6 "Programme courrier"

7 "Programme courrier"

8 "Programme courrier"

9 "Supprimer"

10 "Suivant"

11 "Précédent"

12 "Répondre à l'expéditeur"

13 "Imprimer"

14 "Expéditeur"

15 "Objet"

16 "Date et heure"

17 "Taille"

18 "Boîte aux lettres"

19 "Consultation nouveau courrier"

20 "Ouvrir boîte aux lettres en entrée"

21 "Ouvrir boîte aux lettres en entrée"

22 "Nouveau.."

23 "Programme courrier - Nouveau"

24 "Nouveau"

25 "Ouvrir..."

26 "Programme courrier - Ouvrir"

27 "Ouvrir"

28 "Eliminer les messages supprimés"

29 "Fermer"

30 "Ouvrir"

31 "Sauv. sous forme de texte..."

32 "Programme - Message - Sauv. sous forme de texte"

33 "Copier dans"

34 "Imprimer..."

35 "Rechercher..."

36 "Tout sélectionner"

37 "Supprimer"

38 "Annuler dernière suppression"

39 "Annuler la suppression..."

40 "Message"

41 "Déplacer"

42 "Programme courrier - Messages"

43 "Copier"

44 "Tout sélectionner"

45 "Editer"

46 "Programme courrier - Texte"

47 "Suivant"

48 "Précédent"

49 "En-têtes abrégés"

50 "Par date/heure"

51 "Par expéditeur"

52 "Par objet"

53 "Par taille"

54 "Par état"

55 "Visualiser"

56 "Nouveau message"

57 "Nouveau, Tout inclure"

58 "Faire suivre message"

59 "Répondre à l'expéditeur"

60 "Répondre à tous"

61 "Répondre à l'expéditeur, inclure"

62 "Répondre à tous, inclure"

63 "Composer"

64 "Déplacer"

65 "Autres boîtes aux lettres..."

66 "Sauvegarder sous..."

67 "Programme courrier - Connexions - Sauvegarder sous"

68 "Tout sélectionner"

69 "Connexions"

70 "Programme courrier - Connexions"

71 "Généralités"

72 "Tâches"

73 "Référence"

74 "Sur l'élément"

75 "Aide sur l'aide"

76 "Aide"

77 "A propos du programme courrier..."

78 "Le programme courrier ne parvient pas à déterminer l'état de cette boîte\n\
aux lettres ; fermez-la à l'aide de l'option OK et relancez le programme."

79 "Conversion en cours... %d %% effectué(s)"

80 "Programme courrier"
$    
$ Strings from dtmail/AttachArea.C   

81 "Programme courrier"

82 "Programme courrier"

83 "Programme courrier"
$    
$ Strings from dtmail/Attachment.C   

84 "%s est une connexion exécutable. Voulez-vous l'exécuter ?"

85 "Programme courrier"

86 "Programme courrier"

87 "Programme courrier"

88 "Programme courrier"
$    
$ Strings from dtmail/RoamCmds.C   

89 "Programme courrier - Autres boîtes aux lettres"

90 "Déplacer"

91 "Impression en cours..."

92 "OK"

93 "Sauvegarder"

94 "Sauvegarder"

95 "Sauvegarder"

96 "Vider"

97 "Renommer"

98 "Programme courrier - Renommer"

99 "Programme courrier - Fermer"

100 "OK"

101 "Annuler"

102 "La fonction de réacheminement est utilisée par un programme\n\
différent de Congé. Si ce dernier est en cours d'exécution,\n\
il sera ajouté à l'autre programme. Confirmez-vous le\n\
lancement du programme Congé ?"

103 "Programme courrier"

104 "Le programme Congé s'exécute déjà dans le fichier .forward. Pour savoir comment\n\
l'arrêter et le supprimer de ce fichier, consultez la documentation appropriée.\n\
Une fois ces opérations effectuées, relancez la commande.\0"

105 "Impossible d'ouvrir le fichier .vacation.msg. -- Vous ne disposez pas du droit d'écriture."

106 "Le fichier .vacation.msg existe. Voulez-vous le remplacer ?"

107 "Impossible d'ouvrir le fichier .vacation.msg. -- Vous ne disposez pas du droit d'écriture."

108 "Je suis en congé."
$ \t    /* NL_COMMENT   
$ \t     * This is the default value of the subject field in the   
$ \t     * message that gets returned to the sender when vacation   
$ \t     * is turned on.   
$ \t     */   

109 "Je suis en congé.\n\
Je prendrai connaissance de votre message (objet: \"$SUBJECT\") dès mon retour.\n"
$    
$ Strings from dtmail/MsgScrollingList.C   

110 "N"
$ /* NL_COMMENT   
$  * In a mailer container window's message scrolling list, a "N" appears   
$  * to the left of a mail message header indicating that the mail message   
$  * is "new" (just arrived and not yet viewed by the user).   
$  * There is only space to display 1 character.  If "N" needs to be translated,   
$  * please make sure the translation is only 1 character.   
$  */   

111 "N"
$ /* NL_COMMENT   
$  * In a mailer container window's message scrolling list, a "N" appears   
$  * to the left of a mail message header indicating that the mail message   
$  * is "new" (just arrived and not yet viewed by the user).   
$  * There is only space to display 1 character.  If "N" needs to be translated,   
$  * please make sure the translation is only 1 character.   
$  */   

112 "N"
$ /* NL_COMMENT   
$  * In a mailer container window's message scrolling list, a "N" appears   
$  * to the left of a mail message header indicating that the mail message   
$  * is "new" (just arrived and not yet viewed by the user).   
$  * There is only space to display 1 character.  If "N" needs to be translated,   
$  * please make sure the translation is only 1 character.   
$  */   

113 "N"
$ /* NL_COMMENT   
$  * In a mailer container window's message scrolling list, a "N" appears   
$  * to the left of a mail message header indicating that the mail message   
$  * is "new" (just arrived and not yet viewed by the user).   
$  * There is only space to display 1 character.  If "N" needs to be translated,   
$  * please make sure the translation is only 1 character.   
$  */   

114 "N"
$    
$ Strings from dtmail/Undelete.C   

115 "Annuler la suppression"

116 "Fermer"
$    
$ Strings from dtmail/SendMsgDialog.C   

117 "Transmettre"

118 "Fermer"

119 "Nouveau message"

120 "Programme courrier"

121 "Fichier"

122 "Inclure..."

123 "Programme courrier - Inclure"

124 "Inclure"

125 "Sauv. sous forme de texte..."

126 "Programme courrier - Sauv. sous forme de texte"

127 "Consigner message"

128 "Transmettre sous forme de:"

129 "Fermer"

130 "Editer"

131 "Défaire"

132 "Couper"

133 "Copier"

134 "Coller"

135 "Coller (spécial)"

136 "Entre crochets"

137 "Indenté"

138 "Effacer"

139 "Supprimer"

140 "Tout sélectionner"

141 "Connexions"

142 "Ajouter fichier..."

143 "Programme courrier - Ajouter"

144 "Ajouter"

145 "Sauvegarder sous..."

146 "Programme courrier - Connexions - Sauvegarder sous"

147 "Supprimer"

148 "Annuler la suppression"

149 "Renommer"

150 "Tout sélectionner"
$       /* NL_COMMENT   
$        * This is an obsolete message.  It is replaced by message 226   
$        * in set 1.   
$        */   

151 "Afficher volet"

152 "Formater"

153 "Renvoi à la ligne"

154 "Paramètres..."

155 "Rechercher/Remplacer..."

156 "Vérif. orthographe..."

157 "Modèles"

158 "Programme courrier - Connexions"

159 "Programme courrier - Composer"

160 "Nouveau message"
$       /* NL_COMMENT   
$        * This is the label for a toggle item in a menu.  When the item   
$        * is set to "Show List", the Attachment List is mapped in the   
$        * Compose Window.  This message replaces message 151 in set 1.   
$        */   
$    
$ Strings from dtmail/ViewMsgDialog.C   

161 "Copier"

162 "Tout sélectionner"

163 "Editer"

164 "Sauvegarder sous..."

165 "Programme courrier - Connexions - Sauvegarder sous"

166 "Tout sélectionner"

167 "Connexions"

168 "Programme courrier - Connexions"

169 "Programme courrier - Texte"

170 "Généralités"

171 "Tâches"

172 "Référence"

173 "Sur l'élément"

174 "Aide sur l'aide"

175 "Aide"

176 "A propos du programme courrier..."

177 "Programme courrier"
$    
$ Strings from dtmail/DtMailGenDialog.C   

178 "Programme courrier - A propos de Dtmail"

179 "Dtmail version 1.0"

180 "OK"

181 "OK"

182 "Annuler"
$    
$ Strings from dtmail/FindDialog.C   

183 "Rechercher"
$  /* NL_COMMENT   
$   * This is an obsolete message.  Replaced by message 220 in set 1   
$   */   

184 "Tout rechercher & sélectionner"

185 "Effacer"

186 "Fermer"

187 "Aide"

188 "A :"

189 "De :"

190 "Objet :"

191 "Cc :"

192 "Programme courrier - Rechercher"

193 "Faire suivre"

194 "Arrière"
$  /* NL_COMMENT   
$   * This message replaces message 184 in set 1   
$   */   
$    
$ Strings from dtmail/Editor.C   

195 "------------- Début message réacheminé -------------\n\n"

196 "------------- Début message inclus -------------\n\n"

197 "------------- Fin message réacheminé -------------\n\n"

198 "------------- Fin message inclus -------------\n\n"
$    
$ Strings from dtmail/XmTextEditor.C   

199 "\n\
------------- Début message inclus -------------\n"

200 "\n\
------------- Fin message inclus -------------\n"
$    
$ Strings from dtmail/DtEditor.C   

201 "\n\
------------- Début message inclus -------------\n"

202 "\n\
------------- Fin message inclus -------------\n"
$    
$ Strings from dtmail/ComposeCmds.C   

203 "Programme courrier "

204 "Impossible de créer une fenêtre composée."

205 "Programme courrier"

206 "Impossible de créer une fenêtre composée."

207 "Programme courrier"

208 "Impossible de créer une fenêtre composée."

209 "Programme courrier"

210 "Impossible de créer une fenêtre composée."

211 "Programme courrier"

212 "Le modèle n'existe pas."

213 "Programme courrier"

214 "Le modèle est altéré."

215 "Programme courrier"

216 "La mémoire est insuffisante pour le chargement du modèle."

217 "Programme courrier"

218 "Le modèle est altéré."
$    
$ Strings from dtmail/SortCmd.C   

219 "Tri en cours..."

220 "Tout sélectionner"

221 "Boîte aux lettres en entrée"

222 "%a %b %d %k:%M"
$ /* NL_COMMENT   
$  * The "%a %b %d %k:%M" is the time and date format, please refer to    
$  * strftime man page for explanation of each format.   
$  */   

223 "%a %b %d %H:%M"
$ /* NL_COMMENT   
$  * The "%a %b %d %H:%M" is the time and date format, please refer to    
$  * strftime man page for explanation of each format.   
$  */   

224 "%a %b %d %k:%M"
$ /* NL_COMMENT   
$  * The "%a %b %d %k:%M" is the time and date format, please refer to    
$  * strftime man page for explanation of each format.   
$  */   

225 "%a %b %d %H:%M"
$ /* NL_COMMENT   
$  * The "%a %b %d %H:%M" is the time and date format, please refer to    
$  * strftime man page for explanation of each format.   
$  */   

226 "Afficher liste"

$ String from Undelete.C, Deleted Messages window title
227 "Programme courrier - messages supprimés"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "Ajouter"
229 "Supprimer"
230 "Envoyer"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "Recherche en cours..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "1 message sélectionné"
233 "%d messages sélectionnés "

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "Correspondances introuvables"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "Programme courrier - A propos du programme courrier"
236 "Programme courrier Version %d.%d.%d"
$  /* NL_COMMENT
$   * String 237 is the Copy button on Move Other Mailboxes dialog (from RoamCmds.C)
$   */
237 "Copier"


$ 
$ DTMC_BADSTATE
$ The mailbox is in a state which cannot be deciphered by the Mailer, i.e.
$ portions of the file have been deleted by another process (the Mailer
$ only knows how to handle other processes adding to the end of the mailbox.
$ 
$ "-NEW"
238 "Mailer is confused about the state of this mailbox.\nIt may be that another process has rewritten this mailbox in an unexpected way.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost."

$ 
$ DTMC_ACCESSFAILED
$ The Mailer cannot perform routine file operations on the mailbox file,
$ a.k.a. stat, fstat, write, ...
$ 
$ "-NEW"
239 "Mailer can no longer access this mailbox.\nIt may be that another process has deleted the mailbox file.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ DTMC_INODECHANGED
$ The mailbox has been rewritten by another process.
$ 
$ "-NEW"
240 "Mailer can no longer access this mailbox.\nAnother process has rewritten the mailbox file changing the inode.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ Messages 241-244 are header field labels for SendMsgDialog.
$ 
$ "-NEW"
241 "A"
$ "-NEW"
242 "Objet"
$ "-NEW"
243 "Cc"
$ "-NEW"
244 "Bcc"

$ 
$ Message 245 is the label for the Open command in the File menu
$ Message 246 is the label for the command in the OpenContainer menu
$	which opens Mailboxes not in the users folder list.
$ 
$ "-NEW"
245 "Ouvrir"
$ "-NEW"
246 "Autres boîtes aux lettres..."

$ 
$ Message 247 is the label for the command in the Aliases menu
$	which opens the MailOptions dialog allowing the user to create
$	other aliases.
$ Message 248 is the label for the Aliases popup menu
$ 
$ "-NEW"
247 "Autres Alias..."
$ "-NEW"
248 "Programme courrier - Alias"

$ 
$ Messages 249-255 are strings used to generate attachment summaries
$                  in included messages.
$ 
$ "-NEW"
249 "------------- Begin Included Attachment -------------\n\n" 
$ "-NEW"
250 "------------- End Included Attachment -------------\n\n" 
$ "-NEW"
251 "       Attachment Name:  "
$ "-NEW"
252 "     Attachment DtType:  "
$ "-NEW"
253 "Attachment ContentType:  "
$ "-NEW"
254 "Attachment Description:  "
$ "-NEW"
255 "------------------ Attachments ------------------\n" 

$ "-NEW"
$ DTMC_SERVERACCESSFAILED:
$ Mailer failed in attempt to retrieve messages from the mail server
256 "Mail server access failed:\n%s"

$ "-NEW"
$ Label on the button which causes the "Mail Retrieval" options to be displayed
257 "Options..."

$ "-NEW"
$ DTMC_GETMAILCOMMANDFAILED:
$ Mailer failed in attempt to retrieve messages via custom getmail command
258 "User Getmail command failed:\n%s"

$ "-NEW"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
259 "%a %d %b %Y"
260 "%a %d %b %k:%M"
261 "%a %d %b %H:%M"


$ "-NEW"
262 "lettre morte message"

$ "-NEW"
263 "The attachment '%s' is %d kilobytes.\nAdd as attachment?"





$set 2        Redefine set#


1 "Programme courrier"

2 "ToolTalk n'est pas initialisé ; l'exécution du programme courrier est impossible.\n\
Lancez /usr/dt/bin/dtsession ou adressez-vous à l'administrateur système."

3 "Impossible d'initialiser les fenêtres. Abandon en cours.\n"

4 "L'installation du programme courrier présente\n\
des erreurs ; le programme ne peut pas être\n\
lancé car le groupe d'exécution est incorrect."

5 "Vous n'êtes pas autorisé à visualiser %s."
$ \t    /* NL_COMMENT   
$ \t     * The %s is the name of the mailbox the user doesn't have   
$ \t     * permission to view.   
$ \t     */   

6 "La boîte aux lettres %s est un répertoire ; son ouverture est impossible."

7 "Impossible de vider %s (conteneur inexistant)."

8 "Le conteneur %s a été vidé."

9 "Erreur - %s n'a pas été vidé."

10 "Programme courrier"

11 "%s"

12 "Programme courrier"

13 "Programme courrier"

14 "Avant de lancer la commande \"Sauvegarder sous\",\n\
vous devez sélectionner une connexion."

15 "Erreur - Impossible d'obtenir mailrc."

16 "Aucun message sélectionné."
$ \t/* NL_COMMENT   
$ \t * No mail message has been selected by the user.   
$ \t */   

17 "\"%s\" a été modifié. Confirmez-vous la suppression ?"

18 "Erreur: Impossible d'inclure le fichier %s."

19 "Avant de lancer la commande \"Sauvegarder sous\",\n\
vous devez sélectionner une connexion."

20 "Avant de lancer la commande \"Sauvegarder sous\",\n\
vous devez sélectionner une connexion."

21 "Programme courrier"

22 "Des erreurs de syntaxes irréparables ont eu lieu dans le fichier ~/.mailrc.\nVérifiez les autres messages du terminal. Corrigez les erreurs et relancez dtmail.\nSi vous continuez, vous ne pourrez peut-être pas sauvegarder les modifications effectuées \ndans la boîte de dialogue options."
23 "Continuer"
24 "Quitter"
25 " Des erreurs de syntaxes irréparables ont eu lieu dans le fichier ~/.mailrc.\nVous pouvez appliquer les configurations d'options de courrier dans la session en cours mais \nvous ne pourrez pas les sauvegarder dans le fichier." 

$ 
$ Messages for file locking dialog displayed from the Advanced option pane.
$ 
$ "-NEW"
26 "The value of the file locking option has changed.\nTo take immediate effect, folders need to be closed and reopened.\n  o Click on 'Reopen' to reopen folders,\n    making the new option take effect immediately.\n  o Click on 'Continue' to avoid reopening folders.\n    The new option will take effect the next time you open a folder.\n  o Click on 'Cancel' to cancel the Apply and return to editing options."
$ "-NEW"
27 "Reopen"
$ "-NEW"
28 "Continue"
$ "-NEW"
29 "Cancel"

$ 
$ Messages for ToolTalk errors.
$ 
$ "-NEW"
30 "%s returned ToolTalk error: %s\n"


$set 3        Redefine set#


1 "Sauvegarde automatique..."

2 "Initialisation en cours..."

3 "La boîte aux lettres %s n'existe pas.\n\
Voulez-vous la créer ?"

4 "Programme courrier"

5 "OK"

6 "La boîte aux lettres %s est verrouillée.\n\
Vous pouvez la déverrouiller manuellement et relancer\n\
l'opération ou faire appel à l'administrateur système."

7 "Programme courrier"

8 "OK"

9 "OK"

10 "OK"

11 "OK"

12 "%s"

13 "Message %d sur %d, %d nouveau(x), %d supprimé(s)."

14 "Message %d sur %d, %d nouveau(x), %d supprimé(s)."
$ \t/* NL_COMMENT   
$ \t * The user will see the following message display as:   
$ \t * "Message 3 of 10, 2 new, 6 deleted"   
$ \t * This means ??? -- Explain to translator.   
$ \t */   

15 "Sauvegarde en cours..."

16 "Programme courrier"
$ \t\t/* NL_COMMENT   
$ \t\t * This dialog comes up when the user tries to quit the   
$ \t\t * mailbox and the user is asked if he wants to destroy   
$ \t\t * the messages marked for deletion.   
$ \t\t */   

17 "Voulez-vous détruire les messages sélectionnés\n\
pour la suppression dans cette boîte aux lettres ?"

18 "OK"

19 "Annuler"

20 "Ouverture de la boîte aux lettres..."

21 "%s existe déjà.\n\
Voulez-vous l'écraser ?"

22 "Programme courrier"

23 "Impossible d'écraser %s.\n\
Vérifiez les droits d'accès et faites une nouvelle tentative."

24 "Programme courrier"

25 "Chargement en cours du conteneur..."

26 "Informations sur le dossier"

27 "Chargement en cours..."

28 "Conteneur vide"

29 "OK"

30 "OK"

31 "OK"

32 "Elimination des messages supprimés..."

33 "OK"

34 "%s n'existe pas."

35 "Impossible d'ouvrir %s."

36 "Impossible d'allouer la mémoire."

37 "Récapitulatif des connexions"

38 "connexion"

39 "connexions"
$ \t/* NL_COMMENT   
$ \t * "attachments" is the plural form of "attachment".   
$ \t */   

40 "connexions"

41 "supprimé(es)"

42 "%s existe déjà. Confirmez-vous le remplacement ?"

43 "Impossible de remplacer %s."

44 "Impossible de créer %s."

45 "Impossible de créer %s."

46 "Conteneur vide"

47 "%s existe déjà.\n\
Voulez-vous l'écraser ?"

48 "Programme courrier"

49 "Impossible d'écraser %s.\n\
Vérifiez les droits d'accès et faites une nouvelle tentative."

50 "Programme courrier"

51 "Impossible de créer %s."

52 "Programme courrier"

53 "Impossible d'écrire dans %s."

54 "Programme courrier"

55 "Impossible de créer %s."

56 "Programme courrier"

57 "Renommer les connexions en"

58 "La fenêtre composée contient du texte\n\
ou des connexions qui seront perdues à la\n\
fermeture de la fenêtre.\n\
Confirmez-vous la fermeture ?"

59 "Mémoire insuffisante"

60 "La mémoire est insuffisante pour le chargement du fichier .vacation.msg existant."

61 "Programme courrier"

62 "Le fichier .vacation.msg existant est altéré."

63 "Sélectionnez un message à déplacer."

64 "Sélectionnez un message à copier."

65 "%d messages déplacés dans %s."

66 "%d message déplacé dans %s."

67 "%d messages copiés dans %s."

68 "%d message copié dans %s."

69 "La vue existe déjà : mise au premier plan en cours."
$ \t/* NL_COMMENT   
$ \t* The current mail message selected is already displayed in a separate   
$ \t* window.  Therefore this 'separate' window will be raised in front   
$ \t* of existing windows so the user can see it.   
$ \t*/   

70 "Ecriture de dead.letter..."

71 "Programme courrier"

72 "OK"

73 "Annuler"

74 "OK"

75 "OK"

76 "OK"

77 "Il peut y avoir des modifications non enregistrées dans une connexion ouverte.\nL'envoi du message rompra la connexion.\n. Les modifications non sauvegardées ne seront pas incluses dans le message\n. Utilisez Sauvegarder sous pour enregistrer les modifications après la rupture de la connexion mais elles n'en feront pas partie \n."
78 "Initialisations des Options de courrier..."
79 "Détruire et Quitter"
80 "Ne pas détruire et Quitter"
81 "Cette connexion contient des commandes qui peuvent causer des problèmes\ngraves.  Il vous est conseillé de ne l'exécuterque si vous\nêtes sûr que cela ne présente aucun danger.\n\nDans ce cas, appuyez sur OK,\nsinon appuyez sur Annuler."
82 "Cette boîte aux lettres a un autre utilisateur.\nVoulez-vous en demander l'accès exclusif ?"
83 "Le programme courrier ne peut pas obtenir les droits exclusifs de cette boîte aux lettres .\nVoulez-vous l'ouvrir en lecture seule ?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "%d messages supprimés"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "%d message supprimé"
86 "Recherche du nouveau courrier en cours..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "Programme courrier - Fermer"
88 "Détruire les messages supprimés et fermer cette boîte aux lettres ?"
89 "Détruire et Fermer"
90 "Conserver et Fermer"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "Impossible d'exécuter une action incorrecte."
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "Exécution de l'action a échoué !"
93 "L'icône sélectionnée %s est un fichier exécutable.\nCliquez sur OK pour l'exécuter ou sur Annuler pour Quitter."

94 " Le programme courrier ne peut pas obtenir les droits exclusifs de cette boîte aux lettres parce que le système ne répond pas.\n\nDans ce cas seulement, vous pouvez choisir de l'ouvrir en lecture seule \n ou en lecture-écriture sans l'exclusivité du droit d'accès \n (Ceci n'est possible que si personne d'autre n'utilise la boîte aux lettres)."
95 "Lecture seule"
96 "Lecture-Ecriture"

$ 
$ "-NEW"
$ 
$ This message appears when dtmail tries to open a mailbox which has been
$ opened by another dtmail process.
$ 
$ Parameters:
$   1.  Error message saying that the <mailbox>.dtmail lockfile has been found.
$   2.  The mailbox path.
$   3.  "OK"
$   4.  "Cancel"
$   5.  The <mailbox>.dtmail lockfile path.
$ 
97 "%s\n\nThis may indicate that another Mailer has opened\n%s\n\nYou may open this mailbox READ ONLY by choosing '%s'.\n\nOtherwise, you may choose '%s',\nmake sure that another Mailer has not opened this mailbox,\ndelete %s,\nand reopen this mailbox."

$ 
$ "-NEW"
$ 
$ Messages 98-100 check for problems in the paths specified by users of
$ the file selection box.
$ 
98 "Search permission denied on a component of the path prefix,\n'%s'."
99 "A component of the path prefix is not a directory,\n'%s'."
100 "A component of the path prefix does not exist,\n'%s'."



$set 5        Redefine set#


1 "Programme courrier"

2 "Programme courrier"

3 "Si vous envoyez le message sous cette forme,\n\
\t    les modifications apportées aux connexions\n\
\t    seront perdues."
$    /* NL_COMMENT   
$     * The user tried to send a messages without saving changes in   
$     * some open attachments.  This warning makes sure that is what   
$     * the user intended.   
$     */   

4 "Sélectionnez une seule connexion\n\
\t    et relancez la commande Renommer."
$       /* NL_COMMENT   
$        * Mailer ran out of memory.  Ask the user to quit some other   
$        * applications so there will be more memory available.   
$        */   

5 "Certaines adresses indiquées dans le message sont incorrectes,\n\
et ne font référence à aucun utilisateur connu. Assurez-vous que\n\
toutes les adresses sont correctes et faites une nouvelle tentative."
$       /* NL_COMMENT   
$        * Mailer ran out of memory.  Ask the user to quit some other   
$        * applications so there will be more memory available.   
$        */   

6 "Le programme courrier ne dispose pas\n\
de suffisamment de mémoire pour transmettre\n\
ce message. Mettez fin à d'autres applications\n\
et relancez l'opération."
$       /* NL_COMMENT   
$        * There was an error from the mail transport (sendmail).   
$        */   

7 "Une erreur s'est produite lors de la transmission du\n\
message. Vérifiez que celui-ci est arrivé à destination.\n\
Si tel n'est pas le cas, relancez la transmission."

$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "Essayer Envoyer après avoir spécifié le ou les destinataires du message dans \nles zones A:, Cc:, ou Bcc:."


$set 12        Redefine set#


1 "Connexion"

2 "Connexions"

3 "AffichNombre"

4 "Impossible de connecter les fichiers FIFO suivants: %s."

5 "Impossible de connecter les fichiers spéciaux par caractères suivants: %s."

6 "Impossible de connecter les répertoires suivants: %s."

7 "Impossible de connecter les fichiers spéciaux par blocs suivants: %s."

8 "Impossible de connecter les fichiers de prise suivants: %s."

$set 13        Redefine set#


1 "Impossible de créer"

2 "Impossible d'écrire"
$    
$ Strings from dtmail/AttachCmds.C   

$set 14        Redefine set#


1 "Ajouter une connexion"

2 "Impossible d'ouvrir %s."

3 "Impossible de connecter les fichiers FIFO suivants: %s."

4 "Impossible de connecter les fichiers spéciaux par caractères suivants: %s."

5 "Impossible de connecter les répertoires suivants: %s."

6 "Impossible de connecter les fichiers spéciaux par blocs suivants: %s."

7 "Impossible de connecter les fichiers de prise suivants: %s."

8 "Impossible d'ouvrir %s."

9 "Programme courrier - Renommer une connexion"

10 "Description"

11 "Sauvegarder connexion sous"




$set 15
1 "Des modifications ne sont pas sauvegardées.\nVous pouvez les sauvegarder, les supprimer\nou retourner à l'emplacement précédent dans la boîte de dialogue."
2 "Sauvegarder"
3 "Supprimer"
$ 
$ The followings are added by IBM for 41J release
$ 
$set 20
1 "La boîte aux lettres %s est déjà ouverte."
$ The above message is used in RoamMenuWindow::open
$ See AIXC cmvc defect 175920
2 "Utilisez le nom local : "
$ The above message is used in OptCmd::init_advanced_pane()
$ see AIX cmvc defect 176608
3 "Lecture seule"
$ The above message is used in RoamMenuWindow::mapnotify()
$ see AIX cmvc defect 176608

$ 
$	SETS 21 - 25 WERE ADDED TO SUPPORT CDEnext PRINTING
$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$set 21
$ 
$	Messages 1 - 11 are used in DmxPrintJob.
$ 
$ 
$	This is the status message that gets displayed in the MainWindow
$	and RoamMenuWindow status lines when a print job is being executed.
$	The '%s' is the name of the temporary file containing the message(s)
$	to be printed.
1 "Impression de %s ..."

$	Messages 2 - 4 are used in the error popup which gets displayed
$	when an invalid margin specifier has been supplied by the user.
$ 
$	Message 2 is the actual error messagactual error message
$	Message 3 is the title which is displayed in the error popup.
$	Message 4 is the label on the OK button of the error popup.
2 "La syntaxe d'un des indicateurs de marge suivants est incorrecte : \n %s \n %s \n %s \n %s \nContinuer en utilisant les marges ?"
3 "Programme courrier"
4 "OK"

$	Messages 5 - 11 are format string used to construct the header
$	and footer strings which appear in the printing output.
$ 
$	Message 5 is the format string used to make a Cc header/footer.
$	Message 6 is the format string used to make a Date header/footer.
$	Message 7 is the format string used to make a From header/footer.
$	Message 8 is the format string used to make a Subj't header/footer.
$	Message 9 is the format string used to make a To header/footer.
$	Message 10 is the format string used to make a Page# header/footer.
$	Message 11 is the format string used to make a UserName header/footer.
5 "Cc :  %s"
6 "Date :  %s"
7 "De :  %s"
8 "Objet :  %s"
9 "A :  %s"
10 "Page %d de %d"
11 "Courrier pour :  %s"

$ 
$	Messages 12 - 13, 20 are used in DmxPrintSetup to construct the
$	app-specific printing options for DtMail which will be included
$	in the DtPrintSetupBox.
$ 
$	Message 12 is the label used on the Toggle Button to indicate that
$	multiple messages should be printed in separate spool jobs.
$	Message 13 is the label used on the Toggle Button to indicate that
$	lines which would extend beyond the edge of the printed page be 
$	"wrapped" to the next line.
12 "Imprimer séparément"
13 "Utiliser Retour à la ligne"


$	Messages 14 - 15 are status messages for the PrintToFile function.
$ 
$	Message 14 indicates that the PrintToFile function was unsuccessful.
$	Message 15 indicates that the PrintToFile function was successful.
$       NOTE:  'Print to File' should be translated as in DtPrint.msg
$               Set 1, Message 3.
14 "'Imprimer au fichier' a échoué."
15 "'Imprimer au fichier ' a réussi."

$       NL_COMMENT 
$          Messages 16 - 19 are obsolete, and have been replaced by 24
$ 
$	Messages 16 - 19 are status messages for the popup PDM function.
$ 
$	Message 16 indicates that there was no pdm deamon running.
$	Message 17 indicates that the pdm deamon was unable to start a pdm.
$	Message 18 indicates that the pdm couldnt connect to the video display.
$	Message 19 indicates that the pdm couldnt connect to the print display.
16 "Pas de PDM dans l' environement."
17 "Impossible de lancer le PDM."
18 "Pas de connexion autorisée entre le PDM et l'écran Vidéo."
19 " Pas de connexion autorisée entre le PDM et l'écran d'Impression."

$	Message 20 is the label used on the Push Button to bring up
$	the printing options dialog from the DtPrintSetupDialog.
20 "Suite ..."
$       Message 21 is used for the title string on the DtPrintSetupDialog.
21 "Programme Courrier - Configuration de l'impression"

$       Message 22 is used to alert the user to the fact that the mailer
$                  cannot close the mailer window until a task (usually
$                  a print job) has terminated.
22 "Fermeture imminente :  attendez la fin de la tâche..."

$	Message 23 is used to alert the user to the fact that the X Print
$		   Server cannot complete the print request due to a lack
$		   of resources.
23 "Le serveur d'impression X manque temporairement de ressources."

$       Messages 24 & 25 are used to handle errors from the PDM
24	"Erreur du Gestionnaire d'impression (PDM) - configuration a échoué."
25	"Continuer"




$ 
$	The messages in this set are used in pulldown menu for the
$	header/footer $	frame which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 8 are used in DmxPrintOptions.
$ 
$ 
$	Message 1 specifies that the page header/footer field be empty.
$	Message 2 put the Cc msg header in the page header/footer field.
$	Message 3 put the Date msg header in the page header/footer field.
$	Message 4 put the From msg header in the page header/footer field.
$	Message 5 put the Subject msg header in the page header/footer field.
$	Message 6 put the To msg header in the page header/footer field.
$	Message 7 put the Page Nmbr msg header in the page header/footer field.
$	Message 8 put the User Name msg header in the page header/footer field.
$set 22
1 "Vide"
2 "En-tête CC "
3 "En-tête Date "
4 "En-tête De"
5 "En-tête Objet"
6 "En-tête A"
7 "Numéro de page"
8 "Nom de l'utilisateur"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 4 are used in DmxPrintOptions.
$ 
$	Message 1 don't print any message headers.
$	Message 2 print the "standard" msg headers (To, From, Subject, Cc).
$	Message 3 print the "abbreviated" msg headers as defined by the user.
$	Message 4 print all message headers.
$ 
$set 23

1 "Aucun"
2 "Standard"
3 "Abrégé"
4 "Tous"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 5 are used in DmxPrintOptions.
$ 
$	Message 1 use a New Line (CRLF) to separate multiple messages.
$	Message 2 use a Blank Line (2xCRLF) to separate multiple messages.
$	Message 3 use a Line of characters to separate multiple messages.
$	Message 4 start each new message on a new page.
$	Message 5 print each message in it's own spool job.
$ 
$set 24
1 "Nouvelle Ligne"
2 "Ligne en blanc"
3 "Ligne de caractères "
4 "Nouvelle Page"
5 "Nouvelle tâche"

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1 - 2 are used in DmxPrintOptions.
$ 
$ 
$set 25
$ 
$	Label for the option menu used to specify which message headers are
$	printed.
1 "En-têtes des messages imprimés :  "
$ 
$	Label for the option menu used to specify which how multiple messages
$	are separated.
2 "Séparer les messages multiples par :  "

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1-4 are used in error dialogs to indicate an invalid
$		     entry for margin specifiers in the printing options pane.
$	Message 5 is the label string on the button to dismiss the error dialog.
$ 
$ 
$set 26
1 "La valeur de l'indicateur de la marge du haut est incorrecte :  "
2 " La valeur de l'indicateur de la marge de droite est incorrecte:  "
3 " La valeur de l'indicateur de la marge du bas est incorrecte:  "
4 " La valeur de l'indicateur de la marge de gauche est incorrecte:  "
5 "Continuer"

$ 
$	The following set was added to support the Mail Retrieval option pane.
$ 
$	Messages 1-5 Used in the Server Protocol option menu to indicate the
$		     set of mail server network protocols which are supported.
$	Messages 6-15 Are used to label the options in the pane.
$ 
$ "-NEW"
$ 
$set 27
1 "Auto"
2 "POP3"
3 "APOP"
4 "IMAP"
5 "POP2"

6 "Automatic (system) delivery"

7 "Mail server retrieval"
8 "Server Protocol:"
9 "Server Name:"
10 "User Name:"
11 "Password:"
12 "Remember password"
13 "Delete from server after retrieval"
14 "Retrieve old messages"

15 "Custom retrieval"
16 "User Getmail command:"

17 "Null INBOX path."
18 "INBOX folder path:"

