$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcfonted.msg
$ **
$ **  Project:     Fujitsu DT UDC Font Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcfonted
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **
$set 2
$ *****************************************************************************
$ ** _DtMessage set for ufont.c
$ *****************************************************************************

$ This is footer message when registration of the character.
2 Enregistrement en cours à l'intérieur.

$ Message4-8 are error messages when registration of the character.
4 L'enregistrement du caractère a échoué.
6 Code incorrect.
8 Impossible d'ajouter parce que l'allocation de mémoire est impossible.

$ Message10-16 are error messages when copying of the character.
10 Le caractère du code spécifié n'existe pas.
12 Il y a une erreur dans le code d'origine de la copie spécifiée.
14 Il y a une erreur dans le code de destination de la copie spécifiée.
16 Il n'y a pas de caractère dans la zone spécifiée.

$ This is footer message.
18 Patientez un moment, s'il vous plaît.

$ This is error message when copying of the character.
20 Le fichier de code d'origine de la copie n'est pas spécifié.

$ Message22-24 are error message of user defined character
22 Les informations du caractère défini par l'utilisateur ne peuvent pas être recueillies.\nAucune police spécifiée.
24 Les informations du caractère défini par l'utilisateur ne peuvent pas être recueillies.\nPlusieurs polices sont spécifiées.

$ UDC is User Defined Character.
26 Il n'existe pas de zones UDC pour les polices spécifiées.

28 Mémoire épuisée.
30 L'information de la zone UDC est illégale.
32 Erreur de lecture du fichier de police.\nLa zone de modèles est brisée.

$ Dtudcfonted is name of this application.
34 Dtudcfonted ne peut pas modifier les polices de caractères proportionnelles.

36 Des modifications n'ont pas été sauvegardées.\nVoulez-vous les sauvegarder avant l'ouverture ?
38 Des modifications n'ont pas été sauvegardées.\nVoulez-vous les sauvegarder avant de quitter ?
40 Au cours du traitement des copies, l'image glyphe \n des plages suivantes est modifiée.\nProcéder au traitement des copies ?\n\n
42 Pas de droit en écriture pour cette police. Changez le mode d'accès du fichier avant de le sauvegarder.\n

$ There are user-visible labels in font-open dialog.
100 Sélectionner les éléments
102 -        Jeu de codes :
104 -          Style:
106 -          Largeur :
108 -         Hauteur :
110 Ouvrir
112 Quitter

$ There are user-visible labels in menubar.
114 Police
116 Edition
118 Caractère
120 Information

$ There are user-visible labels in File menu.
122 Ouvrir...
124 Sauvegarder
126 Quitter

$ There are user-visible labels in Edit menu.
$ Message135 is copy of cut&copy
128 Effacer
130 Configurer
132 Inverser
134 Couper
135 Copier
136 Coller
138 Faire pivoter
140 Rotation verticale
142 Rotation horizontale
144 Défaire

$ There are user-visible labels in Character menu.
$ Message148 is copy of character
146 Ajouter/Supprimer...
148 Copier...

$ There are user-visible labels in Information menu.
150 Nom XLFD...
152 Zone de code...

$ There are user-visible labels in add/delete dialog.
154 Ajouter
156 Supprimer
158 Annuler

$ There are user-visible labels in copy dialog.
$ Message166 is label of execute button
160 Code(hex):
162 Code de copie d'origine(hex):
164 Code de la copie de destination(hex):
166 Copier
168 Recouvrir
170 OK

$ There are user-visible labels in unsaved edits.
172 Sauvegarder
174 Ne pas sauvegarder 
176 Sauvegarder et Quitter
178 Ne pas sauvegarder et Quitter

$ There are user-visible labels in delete notice dialog.
$ This format is `Message180 (?? Message182)' and `Message184 (?? Message186)'.
$ These Message180 and Message182 are used in only one character.
$ These Message184 and Message186 are used in plural characters.
180 Le caractère suivant sera supprimé.
182 caractère
184 Les caractères suivants seront supprimés.
186 caractères
188 Registre complet
190 Code :
192 Plage du code :

$ There are footer message label.
194 Message :

$ There are user-visible labels in code dialog.
196 code...
198 Page précédente
200 Page suivante
202 Appliquer

$ There are title.
204 Editeur de caractère défini par l'utilisateur : Question
206 Editeur de caractère défini par l'utilisateur: Avertissement
208 Editeur de caractère défini par l'utilisateur: Erreur

$ There are error message of libfal.
300 Une erreur fatale a eu lieu.
301 Impossible d'ouvrir le fichier de polices.
302 Impossible de lire le fichier de polices.
303 Mémoire épuisée.
304 Une erreur fatale a eu lieu.
305 Le fichier de polices spécifié n'existe pas.
306 Ce n'est pas une police pcf ou snf.
307 Impossible d'ouvrir le fichier de liste de polices.
308 Le format du fichier de liste de polices est incorrect.
309 Les descriptions du fichier de liste de polices sont incorrectes.
310 Le format du fichier de liste de polices est incorrect.
311 Impossible d'ouvrir le fichier rep. de polices.
312 Impossible de lire le fichier rep. de polices.
313 Impossible de lire les propriétés des polices.
314 Impossible d'obtenir la propriété de FONT.
315 Impossible d'obtenir la propriété de FAMILY_NAME.
316 Ce fichier de polices est déjà ouvert dans une autre application.
317 Impossible de verrouiller le fichier de polices.
318 Impossible de déverrouiller le fichier de polices.
319 Impossible d'obtenir l'information de verrou à partir du fichier de polices.
320 Impossible de trouver le fichier de polices spécifié.
321 Impossible de lire la base de données NLS.
322 Impossible d'obtenir les noms charset de la base de données NLS.
323 Le nom de Charset n'est pas défini dans la base de données NLS.
324 Le fichier de polices spécifié n'a pas été ouvert.
325 Une erreur fatale a eu lieu.
