#!/bin/sh

#  :ConvertToHPUX
#
#
# This script converts the universal databases into 
# HP-UX databases.
#

cd /x/toolsrc/databases.release

exec > ../databases.HPUX/:Log.ConvertToHPUX 2>&1


DATABASES="     AGRM          \
		BMS           \
		MKFONTDIR     \
		X11-FONTA     \
		X11-FONTB     \
		X11-FONTC     \
		X11-FONTSRV   \
		X11-PRG-MAN   \
		X11-PRG       \
		X11-RUN-MAN   \
		X11-RUN-INFO  \
		X11-RUN       \
		X11-SERV      \
		X11-SHLIBS    \
		CFRENCH-X11   \
		CHINESES-X11  \
		CHINESET-X11  \
		FRENCH-X11    \
		GERMAN-X11    \
		JAPANESE-X11  \
		KOREAN-X11    \
                JPN-X11-HELP  \
                JEUC-X11-HELP \
                KOR-X11-HELP  \
                GER-X11-HELP"

	for i in $DATABASES
	do 
	    echo "making                   ../databases.HPUX/$i.db"   
	    rm -f                          ../databases.HPUX/$i.db 
	    ../dbTools/udbToDb  $i.udb  >  ../databases.HPUX/$i.db

	    #
	    #  concatenate the VUE runtime and font databases onto the end
	    # of the X11-RUN database
	    #
	    if [ $i = "X11-RUN" ]; then
	       ../dbTools/udbToDb  VUE-RUN.udb       >>  ../databases.HPUX/$i.db
	       ../dbTools/udbToDb  VUE-HELP-RUN.udb  >>  ../databases.HPUX/$i.db
	    fi
	    if [ $i = "X11-RUN-MAN" ]; then
	       ../dbTools/udbToDb  VUE-MAN.udb       >>  ../databases.HPUX/$i.db
	    fi
	    if [ $i = "X11-PRG" ]; then
	       ../dbTools/udbToDb  VUE-HELP-PRG.udb  >>  ../databases.HPUX/$i.db
	    fi
	    if [ $i = "X11-RUN-INFO" ]; then
	       ../dbTools/udbToDb  VUE-HELP-INFO.udb >>  ../databases.HPUX/$i.db
	    fi
	done
