$ 
$ +SNOTICE  Bilaga
$ 
$  $TOG: DtMail.msg /main/4 1998/05/22 17:07:17 rafi $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "OK"
2 "Alternativ..."
3 "Autosvar"
4 "Uppdaterar egenskaper..."


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "Avbryt"
6 "Elektronisk post"
7 "Elektronisk post"
8 "Elektronisk post"
9 "Ta bort"
10 "Nästa"
11 "Föregående"
12 "Svar till avsändaren"
13 "Skriv ut"
14 "Avsändare"
15 "Ärende"
16 "Datum och tid"
17 "Storlek"
18 "Brevlåda"
19 "Leta efter ny post"
20 "Öppna inkorgen"
21 "Öppna inkorgen"
22 "Nytt..."
23 "Elektronisk post - Nytt"
24 "Nytt"
25 "Öppna..."
26 "Elektronisk post - Öppna"
27 "Öppna"
28 "Radera borttagna meddelanden"
29 "Stäng"
30 "Öppna"
31 "Spara som text..."
32 "Elektronisk post - Meddelande - Spara som text"
33 "Kopiera till"
34 "Skriv ut..."
35 "Sök..."
36 "Markera allt"
37 "Ta bort"
38 "Återta det sista"
39 "Återta från listan..."
40 "Meddelande"
41 "Flytta"
42 "Elektronisk post - Meddelande"
43 "Kopiera"
44 "Markera allt"
45 "Redigera"
46 "Elektronisk post - Text"
47 "Nästa"
48 "Föregående"
49 "Små meddelandehuvuden"
50 "Efter datum/tid"
51 "Efter avsändare"
52 "Efter ärende"
53 "Efter storlek"
54 "Efter status"
55 "Visa"
56 "Nytt meddelande"
57 "Nytt, infoga allt"
58 "Vidarebefordra meddelande"
59 "Svar till avsändaren"
60 "Svar till alla"
61 "Svar till avsändaren, infoga"
62 "Svar till alla, infoga"
63 "Skapa meddelande"
64 "Flytta"
65 "Andra brevlådor..."
66 "Spara som..."
67 "Elektronisk post - Bilagor - Spara som"
68 "Markera allt"
69 "Bilagor"
70 "Elektronisk post - Bilagor"
71 "Översikt"
72 "Steg-för-steg-anvisningar"
73 "Referens"
74 "Objekthjälp"
75 "Om hjälpfunktionen"
76 "Hjälp"
77 "Om Elektronisk post..."
78 "Den elektroniska posten känner inte igen brevlådan.\nStäng brevlådan genom att välja OK och starta sedan om den elektroniska posten."
79 "Konverterar... %d procent färdigt"
80 "Elektronisk post"

$ 
$ Strings from dtmail/AttachArea.C

81 "Elektronisk post"
82 "Elektronisk post"
83 "Elektronisk post"


$ 
$ Strings from dtmail/Attachment.C

84 "%s är en exekverbar bilaga. Vill du köra den?"
85 "Elektronisk post"
86 "Elektronisk post"
87 "Elektronisk post"
88 "Elektronisk post"

$ 
$ Strings from dtmail/RoamCmds.C

89 "Elektronisk post - Andra brevlådor"
90 "Flytta"
91 "Skriver ut..."
92 "OK"
93 "Spara"
94 "Spara"
95 "Spara"
96 "Töm"
97 "Byt namn"
98 "Elektronisk post - Byt namn"
99 "Elektronisk post"
100 "OK"
101 "Avbryt"
102 "Du använder redan funktionen för vidarebefordran för\nnågot annat än Autosvar. Medan Autosvar körs\nkommer Autosvar att läggas till denna andra\nvidarebefordran. Vill du ändå starta Autosvar?\0"
103 "Elektronisk post"
104 "Du kör redan autostartprogrammet i filen .forward.\nMer information om hur du avslutar och tar bort det från filen .forward finns i dokumentationen.\nGör ett nytt försök med kommandot efter att du har åtgärdat problemet.\0"
105 "Det går inte att öppna filen .vacation.msg. Du har inte behörighet att ändra."
106 "Filen .vacation.msg finns redan. Vill du ersätta den?"
107 "Det går inte att öppna filen .vacation.msg. Du har inte behörighet att ändra."
108 "Jag är upptagen på annat håll."
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "Jag är upptagen på annat håll.\nJag kommer att läsa ditt meddelande angående \"$SUBJECT\" när jag återkommer.\n"


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N"

$ 
$ Strings from dtmail/Undelete.C

115 "Återta"
116 "Stäng"

$ 
$ Strings from dtmail/SendMsgDialog.C

117 "Sänd"
118 "Stäng"
119 "Nytt meddelande"
120 "Elektronisk post"
121 "Fil"
122 "Infoga..."
123 "Elektronisk post - Infoga"
124 "Infoga"
125 "Spara som text..."
126 "Elektronisk post - Spara som text"
127 "Spara meddelande"
128 "Sänd som"
129 "Stäng"
130 "Redigera"
131 "Ångra"
132 "Klipp ut"
133 "Kopiera"
134 "Klistra in"
135 "Klistra in special"
136 "Inom markeringar"
137 "Indraget"
138 "Töm"
139 "Ta bort"
140 "Markera allt"
141 "Bilagor"
142 "Bifoga fil..."
143 "Elektronisk post - Bifoga"
144 "Bifoga"
145 "Spara som..."
146 "Elektronisk post - Bilagor - Spara som"
147 "Ta bort"
148 "Återta"
149 "Byt namn"
150 "Markera allt"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "Visa fönsterruta"
152 "Format"
153 "Radbyte"
154 "Inställningar..."
155 "Sök/Ersätt..."
156 "Kontrollera stavning..."
157 "Mallar"
158 "Elektronisk post - Bilagor"
159 "Elektronisk post - Skapa meddelande"
160 "Nytt meddelande"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "Kopiera"
162 "Markera allt"
163 "Redigera"
164 "Spara som..."
165 "Elektronisk post - Bilagor - Spara som"
166 "Markera allt"
167 "Bilagor"
168 "Elektronisk post - Bilagor"
169 "Elektronisk post - Text"
170 "Översikt"
171 "Steg-för-steg-anvisningar"
172 "Referens"
173 "Objekthjälp"
174 "Om hjälpfunktionen"
175 "Hjälp"
176 "Om Elektronisk post..."
177 "Elektronisk post"

$ 
$ Strings from dtmail/DtMailGenDialog.C

178 "Elektronisk post - Om Dtmail"
179 "Dtmail version 2.1.20"
180 "OK"
181 "OK"
182 "Avbryt"

$ 
$ Strings from dtmail/FindDialog.C

183 "Sök"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "Sök & markera allt"
185 "Töm"
186 "Stäng"
187 "Hjälp"
188 "Till:"
189 "Från:"
190 "Ärende:"
191 "Kopia:"
192 "Elektronisk post - Sök"
193 "Framåt"
194 "Bakåt"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */



$ 
$ Strings from dtmail/Editor.C
195 "---- Här börjar det vidarebefordrade meddelandet ----\n\n"
196 "-------- Här börjar det infogade meddelandet --------\n\n"
197 "---- Här slutar det vidarebefordrade meddelandet ----\n\n"
198 "-------- Här slutar det infogade meddelandet --------\n\n"

$ 
$ Strings from dtmail/XmTextEditor.C

$ 
199 "\n------- Här börjar det infogade meddelandet -------\n"
200 "\n------- Här slutar det infogade meddelandet -------\n"

$ 
$ Strings from dtmail/DtEditor.C

$ 
201 "\n------- Här börjar det infogade meddelandet -------\n"
202 "\n------- Här slutar det infogade meddelandet -------\n"

$ 
$ Strings from dtmail/ComposeCmds.C

$ 
203 "Elektronisk post"
204 "Det går inte att skapa ett meddelandefönster."
205 "Elektronisk post"
206 "Det går inte att skapa ett meddelandefönster."
207 "Elektronisk post"
208 "Det går inte att skapa ett meddelandefönster."
209 "Elektronisk post"
210 "Det går inte att skapa ett meddelandefönster."
211 "Elektronisk post"
212 "Mallen finns inte."
213 "Elektronisk post"
214 "Mallen är antagligen skadad."
215 "Elektronisk post"
216 "Det finns inte tillräckligt med minne för att ladda mallen."
217 "Elektronisk post"
218 "Mallen är antagligen skadad."

$ 
$ Strings from dtmail/SortCmd.C

219 "Sorterar..."

220 "Markera allt" 
221 "Inkorg"

222 "%a %b %d %k:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%a %b %d %H:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%a %b %d %k:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%a %b %d %H:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "Visa lista"



$set 2
1 "Elektronisk post"
2 "ToolTalk har inte initierats. Den elektroniska posten kan inte köras utan ToolTalk.\nFörsök att starta /usr/dt/bin/dtsession eller kontakta systemadministratören."
3 "Det går inte att initiera fönstret. Programmet avslutas.\n"
4 "Den elektroniska posten har inte installerats på rätt sätt.\nProgrammet kan inte köras eftersom inställningen för\nexekveringsgruppen är felaktig."
5 "Du har inte behörighet att visa %s"
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "Brevlådan %s är en katalog och kan inte öppnas."
7 "Det går inte att tömma %s. Den finns inte."
8 "Brevlådan %s har tömts"
9 "Fel - det gick inte att tömma %s"
10 "Elektronisk post"
11 "%s"
12 "Elektronisk post"
13 "Elektronisk post"
14 "Du måste markera en bilaga innan du kan använda\nkommandot \"Spara som\" för att spara filen."

15 "Fel - Det går inte att hämta mailrc."
16 "Inget meddelande har markerats."
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */
17 "Du har redigerat \"%s\". Vill du ta bort den ändå?"
18 "Fel: Det går inte att infoga filen %s"
19 "Du måste markera en bilaga innan du kan använda kommandot\n \"Spara som\" för att spara filen."

20 "Du måste markera en bilaga innan du kan använda kommandot\n \"Spara som\" för att spara filen."

21 "Elektronisk post"


$set 3
1 "Sparar automatiskt..."
 
2 "Initierar..."
3 "Brevlådan %s finns inte.\nVill du skapa en brevlåda med detta namn?"
4 "Elektronisk post"
5 "OK"
6 "Brevlådan %s är låst.\nDu kan låsa upp brevlådan manuellt och försöka igen\neller kontakta systemadministratören."
7 "Elektronisk post"
8 "OK"
9 "OK"
10 "OK"
11 "OK"
12 "%s"
13 "Meddelande %d av %d, %d nytt, %d borttaget(na)"
14 "Meddelande %d av %d, %d nya, %d borttaget(na)"
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "Sparar..."
16 "Elektronisk post"
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
17 "Vill du radera de meddelanden som du\nhar markerat för borttagning i brevlådan?"
18 "OK"
19 "Avbryt"
20 "Öppnar brevlådan..."
21 "%s finns redan.\n\
Vill du skriva över?"
22 "Elektronisk post"
23 "Det går inte att skriva över %s.\nKontrollera filbehörigheten och försök igen."
24 "Elektronisk post"
25 "Laddar brevlåda..."
26 "Allmän information om mappen"
27 "Laddar..."
28 "Töm brevlåda"
29 "OK"
30 "OK"
31 "OK"
32 "Borttagna meddelanden raderas..."
33 "OK"

34 "%s finns inte."
35 "Det går inte att öppna %s."
36 "Det går inte att tilldela minne."
37 "Sammanställning av bilagor"
38 "bilaga"
39 "bilagor"
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "bilagor"
41 "borttagen(na)"

42 "%s finns redan. Vill du ersätta?"
43 "Det går inte att ersätta %s."
44 "Det går inte att skapa %s."
45 "Det går inte att skapa %s."

46 "Tom brevlåda"
47 "%s finns redan.\nVill du skriva över?"
48 "Elektronisk post"
49 "Det går inte att skriva över %s.\nKontrollera filbehörigheten och försök igen."
50 "Elektronisk post"
51 "Det går inte att skapa %s."
52 "Elektronisk post"
53 "Det går inte att skriva till %s."
54 "Elektronisk post"
55 "Det går inte att skapa %s."
56 "Elektronisk post"
57 "Byt namn på bilagan till"
58 "Meddelandefönstret innehåller text eller\nbilagor som går förlorade om\ndu stänger fönstret.\nVill du stänga meddelandefönstret?"
59 "Det finns inget minne"
60 "Det finns inte tillräckligt med minne för att ladda den befintliga filen .vacation.msg."
61 "Elektronisk post"
62 "Den befintliga filen .vacation.msg är antagligen skadad."

63 "Markera meddelandet som du vill flytta."
64 "Markera meddelandet som du vill kopiera."
65 "%d meddelanden har flyttats till %s"
66 "%d meddelande har flyttats till %s"
67 "%d meddelanden har kopierats till %s"
68 "%d meddelande har kopierats till %s"
69 "Fönstret finns redan. Det placeras överst."
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/


70 "Skriver till dead.letter..."
71 "Elektronisk post"
72 "OK"
73 "Avbryt"
74 "OK"

75 "OK"
76 "OK"

$set 5
1 "Elektronisk post"
2 "Elektronisk post"
3 "Om detta meddelande sänds i\n\
	    befintligt tillstånd kan alla\n\
	    ändringar i bilagorna gå förlorade."
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "Markera endast en bilaga\n\
	    och välj sedan 'Byt namn'"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "Någon av adresserna i meddelandet är felaktig\noch refererar inte till någon känd användare av systemet.\nKontrollera adresserna och försök igen."
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "Elektronisk post behöver mer minne\nför att sända meddelandet. Frigör\nminne genom att avsluta andra startade program.\nSänd meddelandet igen."
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "Ett fel uppstod när detta meddelandet sändes.\nKontrollera om meddelandet har mottagits.\nOm inte, sänd meddelandet igen."



$set 12
1 "Bilaga"
2 "Bilagor"
3 "displayCount"
4 "Det går inte bifoga FIFO-filer: %s"
5 "Det går inte att bifoga teckenspecifika filer: %s"
6 "Det går inte att bifoga kataloger: %s"
7 "Det går inte att bifoga blockspecifika filer: %s"
8 "Det går inte att bifoga sockelfiler: %s"


$set 13
1 "Det går inte att skapa"
2 "Det går inte att skriva"

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "Lägg till bilaga"
2 "Det går inte att öppna %s"
3 "Det går inte att bifoga FIFO-filer: %s"
4 "Det går inte att bifoga teckenspecifika filer: %s"
5 "Det går inte att bifoga kataloger: %s"
6 "Det går inte att bifoga blockspecifika filer: %s"
7 "Det går inte att bifoga sockelfiler: %s"
8 "Det går inte att öppna %s"
9 "Elektronisk post - Byt namn på bilaga"
10 "Beskrivning"
11 "Spara bilaga som"














