$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:39:26 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s:  felaktigt alternativ för kommandoraden \"%s\"\n\n"
2 "1386-102 \nSkriv %s -help för att få en detaljerad beskrivning.\n\n"

3 "1386-103 syntax:\n        %s [-options ...]\n\n\
	 där alternativen omfattar:\n"
5 "1386-105    %-28s %s\n\t där lägena omfattar:\n\", \"-mode läge\", \"animation-läge"

7 "1386-107 Okänt läge: "
10 "1386-110 det gick inte att tilldela: %s\n"
11 "1386-111 %d bildpunkter har tilldelats\n"

17 "1386-117 %s: det gick inte att öppna visningsenheten %s.\n"
18 "1386-118 %s: GetResource - det gick inte att tilldela minne"
19 "1386-119 %s: Felaktig syntax för argumentet -display, \"%s\"\n"

20 "1386-120 argumentet -batchcount måste vara positivt."
21 "1386-121 argumentet -saturation måste vara mellan 0,0 och 1,0."

25 "1386-125 %s: stöder endast skärmar av typen %d.\n"
30 "1386-130 argumentet -delay måste vara positivt."
35 "1386-135 kunde inte tilldela: %s, %s används i stället\n"
40 "%s: Det gick inte att hitta ett ritfönster. Om du använder alternativet -create\n\
        kommer %s att skapa ett eget fönster.\n"

