$ +SNOTICE
$ 
$ 	$TOG: libDtMail.msg /main/4 1997/10/31 15:39:30 rafi $
$ 
$ 	RESTRICTED CONFIDENTIAL INFORMATION:
$ 	
$ 	The information in this document is subject to special
$ 	restrictions in a confidential disclosure agreement bertween
$ 	HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$ 	document outside HP, IBM, Sun, USL, SCO, or Univel wihtout
$ 	Sun's specific written approval.  This documment and all copies
$ 	and derivative works thereof must be returned or destroyed at
$ 	Sun's request.
$ 
$ 	Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ @(#)libDtMail.msg	1.8 03 Nov 1994
$set 1 libDtMail API set
1 Inga fel inträffade.
2 Ett meddelande som saknar giltigt Bento-objekt har påträffats.
3 Ett objekt som inte har skapats korrekt har påträffats.
4 Det går inte att skapa ett objekt.
5 Det finns inget värde för objektet.
6 Det finns inte tillräckligt med minne för att utföra operationen.
7 Ett felaktigt argument har skickats vidare till operationen.
8 Det går inte att initiera ett objekt som redan är initierat.
9 Den begärda filen finns inte.
10 Den begärda filen är inte en brevlåda med ett format som implementeringen känner igen.
11 Det finns ingen meddelandeförteckning för DtMail.
12 Felstrukturen är ogiltig.
13 Värdet är en inbäddad behållare och måste öppnas för att kunna läsas.
14 Ett annat postprogram har behörighet att ändra mappen.
15 Ett ToolTalk-meddelande kunde inte bearbetas.
16 Förfrågan nekades av den aktuella servern.
17 Användaren avbröt operationen.
18 Det gick inte att få tillgång till ett objekt.
19 Det gick inte att skapa den begärda filen.
20 Ett internt fel inträffade under operationens gång.
21 Den efterfrågade operationen stöds inte för det aktuella objektet.
22 Det finns ingen datatyp som matchar protokolltypen.
23 Användaren avbröt konverteringen.
24 Det fanns inga implementeringar i postbiblioteket.
25 Den angivna implementeringen finns inte.
26 Den angivna implementeringen kunde inte utföra den önskade operationen.
27 Operationen stöds inte av den aktuella implementeringen.
28 Biblioteket känner inte igen datatypen.
29 Det gick inte att bearbeta den angivna postadressen.
30 Postprotokollet misslyckades.
31 Signaturen MD5 stämde inte överens med meddelandets innehåll.
32 Den faktiska körgruppen är inte "post" (mail).

$ 
$ Strings from libDtMail/Common/DtMailValuesBuiltin.C

$set 2
1 "%C" 
$ /* NL_COMMENT
$  * The %C is the time and date format, please refer to strftime man page for 
$  * explanation of each format.
$  */

