$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/3 1995/11/08 13:31:23 rswiston $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$ -------------------------------------
$ MotifApp/Application.C
$ 

$quote "

$ -------------------------------------
$ MotifApp/AskFirstCmd.C
$ 

$quote "


$set 1
1 "Vill du verkligen exekvera kommandot?"
$ -------------------------------------
$ MotifApp/DialogManager.C
$ 

$quote "


2 "OK"
3 "Avbryt"
$ -------------------------------------
$ MotifApp/Help.C
$ 

$quote "


4 "DtMail version"
5 "DtMail version"
6 "Du måste markera en komponent i programmet.\n"
7 "DtMail - Hjälp"
8 "DtMail - Hjälp"


$quote "


9 "Vill du stänga den här mappen?"
$ -------------------------------------
$ MotifApp/WarnNoUndoCmd.C
$ 

$quote "


10 "Detta kommandot kan inte ångras. Vill du fortsätta ändå?"

$quote "

$set 2
1 "Markeringsfel. Det går inte att fortsätta.\n"
2 "Markeringen har avbrutits av användaren.\n"
$ -------------------------------------
$ MotifApp/QuitCmd.C
$ 
