/* XPM */
/* $XConsortium: audio.pm /main/2 1996/07/23 13:12:32 drk $ */
static char * AudioOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 9 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X	s iconColor2	m white	c white",
"o    s iconGray1     m white c #dededededede",
"O    s iconGray3     m white c #adadadadadad",
"+    s iconGray7     m black c #424242424242",
"@    s iconGray5     m black c #737373737373",
"#    s iconGray8     m black c #212121212121",
"$    s topShadowColor m white c #bdbdbdbdbdbd",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                           ....                                 ",
"                X          .ooo.                                ",
"                OX         .oOOO.                               ",
"                +OX        .O++OO.                              ",
"                 +OX       .X+@OOO.                             ",
"                  +OX      .X++OOOO.                            ",
"                   +OX     .X++XOOOO.                           ",
"                    +OX    .X+@XXOOOO.                          ",
"             XXXX    +OX   .X++XXXOOO........                   ",
"             OOOXXX   +OX  .O+@XXXXOOOOOOOOO..                  ",
"             +++OOOXXX +O  .OO@XXXXXO+OOOOOO#$                  ",
"               ++++OOO  +  .O++XXXXXXXXXXXXXX$                  ",
"                  ++++     .O++OXOXOX+XOXOXO#$                  ",
"                          .XO@+XOXOXO+OXOXOX#$                  ",
"           XXXXXXXXXXXXXX .OO++OXOXOX+XOXOXO#$                  ",
"           OOOOOOOOOOOOOO .XO+@X@X@X@+@X@X@X#$                  ",
"           ++++++++++++++ .OO++@X@X@X+X@X@X@#$                  ",
"                          .XO++X@X@X@+@X@X@X#$                  ",
"                  XXXX    ..O++@X@@@@+@@@@@@#$                  ",
"               XXXXOOO  X  .O++@@@@@@+@@@@@@#$                  ",
"             XXXOOO+++ XO  .O++@@@@@@+@@@@@##$                  ",
"             OOO+++   XO+  .O++@@@@@@+######$$                  ",
"             ++++    XO+   .+++@@@@++#$$$$$$$                   ",
"                    XO+    .+++@@@++#$                          ",
"                   XO+     .+++@@++#$                           ",
"                  XO+      .+++@++#$                            ",
"                 XO+       .+++++#$                             ",
"                XO+        .O+++#$                              ",
"                O+         .O++#$                               ",
"                +          .###$                                ",
"                           .$$$                                 ",
"                                                                ",
"                                                                "};
