/* XPM */
/* $XConsortium: font.pm /main/2 1996/07/23 13:13:56 drk $ */
static char * FontOL [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 3 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray8     m black c #212121212121",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"    ..........................                                  ",
"    ...XXXXXXX......XXXXXXX...X                                 ",
"    ..XXXXXXXXX....XXXXXXXXX..XX                                ",
"    .XXX     XX....XXX    XXX.XX                                ",
"    .XX       X....XX      XX.XX                                ",
"    .X         ....XX       X.XX                                ",
"    .X         ....XX        XXX                                ",
"               ....XX         XX                                ",
"               ....XX     .................                     ",
"               ....XX     ..XXXX.....XXXX..X                    ",
"               ....XX     .XXXXXX...XXXXXX.XX                   ",
"               ....XX     .XX   X...XXX  X.XX                   ",
"               ....XX     .X     ...XX    XXX                   ",
"               ....XX            ...XX     XX                   ",
"               ....XX            ...XX     ..............       ",
"               ....XX            ...XX     ..XXX....XXX..X      ",
"               ....XX            ...XX     .XXXXX..XXXXX.XX     ",
"               ....XX            ...XX     .X   X..XX  X.XX     ",
"               ....XX            ...XX           ..XX   XXX     ",
"               ....XX            ...XX           ..XX    XX     ",
"               ....XX            ...XX           ..XX           ",
"               ....XX            ...XX           ..XX           ",
"               ....XX            ...XX           ..XX           ",
"               ....XX            ...XX           ..XX           ",
"               ....XX            ...XX           ..XX           ",
"              ......X            ...XX           ..XX           ",
"             ........           .....X          ....X           ",
"           ............X      .........X      ........X         ",
"            XXXXXXXXXXXXX      XXXXXXXXXX      XXXXXXXXX        ",
"             XXXXXXXXXXXXX      XXXXXXXXXX      XXXXXXXXX       ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "};
