/* XPM */
/* $XConsortium: winmgr.pm /main/2 1996/07/23 13:16:18 drk $ */
static char * Vuewm [] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 37 7 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s bottomShadowColor m black c #636363636363",
"X    s iconGray1     m white c #dededededede",
"o    s topShadowColor m white c #bdbdbdbdbdbd",
"O    s iconGray8     m black c #212121212121",
"+    s iconGray3     m white c #adadadadadad",
"@    s iconGray5     m black c #737373737373",
/* pixels */
"                                                                ",
"                                                                ",
"  ............................................................  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++++++++++++++++++++OX++++++++++++++++++++++++++++++++o  ",
"  .XX++++OOOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo  ",
"  .XX++++OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo   ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++++++o   ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++++o    ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++++o    ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++XXXXXXXX++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++X++++++O++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++X++++++O++++OX+++++++++++++++++++++++++++++o     ",
"  .XX++++OX++++XOOOOOOO++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX++++++++++++++++++++++++++++o      ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OX++++++++++++++++OX+++++++++++++++++++++++++++o       ",
"  .XX++++OXOOOOOOOOOOOOOOOOOXOOOOOOOOOOOOOOOOOOOOOOOOOOOo       ",
"  .XOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo        ",
"  .XXXXXXXO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o        ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o        ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .XX++++OO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@o         ",
"  .oooooooooooooooooooooooooooooooooooooooooooooooooooo         ",
"                                                                ",
"                                                                ",
"                                                                "};
