/* XPM */
/* $XConsortium: plus.pm /main/3 1995/07/18 17:37:22 drk $ */
static char * plus_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"60 30 17 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s iconColor1	m black	c black",
"X	m black c #8282B8B8FFFF",
"o    s iconGray1     m white c #dededededede",
"O	m black c #00006D6DFFFF",
"+	m black c #000035357D7D",
"@    s iconGray2     m white c #bdbdbdbdbdbd",
"#    s bottomShadowColor m black c #636363636363",
"$    s topShadowColor m white c #bdbdbdbdbdbd",
"%    s iconGray7     m black c #424242424242",
"&    s iconGray5     m black c #737373737373",
"*    s iconGray4     m white c #949494949494",
"=	s iconColor5	m black	c blue",
"-    s iconGray6     m black c #636363636363",
";    s iconGray8     m black c #212121212121",
":    s iconGray3     m white c #adadadadadad",
"?    s selectColor m white c #737373737373",
/* pixels */
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                              ...............               ",
"   XXXXXXXXXXXXXXXX           .            o.               ",
"   XOOOOOOOOOOOOOO+           . @@@@@@@@@@ o.               ",
"   XOOOOOOOOOOOOOO+        ####  @ @ @@     #######$        ",
"   XOOOOOO  OOOOOO+       ## @@ @@@ @@ @@@  o@@@@@@%$       ",
"   XOOOOOO  OOOOOO+      ## @&*ooooooooooooo*@o@@@@@%$      ",
"   XOOOOO=  OOOOOO+      # @@-&&&&&&&&&&&&&&&& @@@@@@%$     ",
"   XOOOOOO  OOOOOO+      # oooooooooooooooooooooooooo%$     ",
"   XOO          OO+      # @oooooooooooooooooo------@%$     ",
"   XOO          OO+      # @oooooooooooooooooo-&&&&-@%$     ",
"   XOOOOOO  OOOOOO+      # @@&&&&&&&&&&&&&&&&&------@%$     ",
"   XOOOOOO  OOOOOO+      # @@@@@@@@@@@@@@@@@@@@@@@@@@%$     ",
"   XOOOOOO  OOOOOO+      # @@@@@@@@@@@@@@@@@@@@@@@@@@%$     ",
"   XOOOOOO  OOOOOO+      # @@;;;;;;;;;;;;;;;;;;@@@@@@%$     ",
"   XOOOOOOOOOOOOOO+      # @@;*&&&&&&&&&&&&&&&;@@@@@@%$     ",
"   XOOOOOOOOOOOOOO+      # ;;: &&&&&&&&&&&&&&&&;;;;;;%$     ",
"   X+++++++++++++++       #:%*&&&&&&&&&&&&&&&&&%%%%;$$$     ",
"                           :;;;;;;;;;;;;;;;;;;;;;;;;$       ",
"                             ;;;;;;;;;;;;;;;;;;#?$$$        ",
"                             ###################?           ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            ",
"                                                            "};
