$ $XConsortium: dtudcfonted.msg
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtudcexch.msg
$ **
$ **  Project:     Fujitsu DT UDC Exchange
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtudcexch
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Fujitsu Ltd.
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for getbdffn.c
$ *****************************************************************************

2 BDF file selection
4 The selected file exists. Overwrite?
6 Failed to open the selected file.

$set 4
$ *****************************************************************************
$ ** _DtMessage set for selectx.c
$ *****************************************************************************

2 This font has no user defined characters.
4 Failed to open the selected font. You do not have permission to access the font file, or the format of the file is incorrect.
6 The font file is in use by another UDC application.
8 There is no font
10 Open
12 Cancel
14 UDC data exchange utility
16 SelectItems
18 - Codeset:
20 -   Style:
22 -   Width:
24 -  Height:

$set 6
$ *****************************************************************************
$ ** _DtMessage set for selectxlfd.c
$ *****************************************************************************

2 Do you want to terminate UDC Exchange?
4 No UDCs exist in this font
6 XLFD name is not selected
8 Cannot open the font file
10 The font file is in use by another UDC application.

$set 8
$ *****************************************************************************
$ ** _DtMessage set for udcexc.c
$ *****************************************************************************

2 UDC data exchange utility
4 Fatal error occurred.
6 Cannot open the font file.
8 Cannot read the font file.
10 There is no more memory.
12 Fatal error occurred.
14 The specified font file does not exist.
16 This font is not a pcf or snf font.
18 Cannot open the fonts.list file.
20 The format of the fonts.list file is incorrect.
22 The descriptions of the fonts.list file are incorrect.
24 The format of the fonts.list file is incorrect.
26 Cannot open the fonts.dir file.
28 Cannot read the fonts.dir file.
30 Cannot read the font properties.
32 Cannot get the FONT property.
34 Cannot get the FAMILY_NAME property.
36 This font file is already in use by another application.
38 Cannot lock the font file.
40 Cannot unlock the font file.
42 Cannot get lock information from the font file.
44 Cannot find the specified font file.
46 Cannot read the NLS database.
48 Cannot get charset names from the NLS database.
50 The charset name is not defined in the NLS database.
52 The specified font has not been opened.
54 A fatal error occurred.
56 XLFD name          :
58 Original font (XLFD name)  :
60 UDC code area      :
62 Style              :
64 Size (letter size) :
66 Open
68 Cancel
70 OK
72 cancel
74 Copy origin code(hex)  :
76 Copy target code(hex) :
78 Copy
80 Overlay
82 export function
84 import function
86 Cancel

$set 10
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Failed to create the BDF file
4 No indexes are selected
6 OK
8 Cancel
10 glyph indexes

$set 12
$ *****************************************************************************
$ ** _DtMessage set for udcexp.c
$ *****************************************************************************

2 Glyph images in this BDF file cannot be added to the font.
4 Failed to open the selected BDF font. You do not have permission to access the font file, or the format of the file is incorrect.
6 One or more glyph images will be overwritten. Overwrite?
8 Failed to open the selected font. You do not have permission to access the font file, or the format of the file is incorrect.
10 Glyph images in this BDF file cannot be added to the font.
12 Registration of the font file failed.
