$ $TOG: dtcm.msg /main/13 1999/09/20 10:35:48 mgreess $



$quote "
$set	1
1	"dtcm: nessun destinatario nel promemoria\n"
2	"Promemoria- %s"
3	"pm"
4	"am"
5	"pm"
6	"am"
7	"\n\n\t** Appuntamento **\n\n\tData:\t%s\n\tInizio:\t%s\n\tFine:\t%s\n\tDescrizione:\t%s"
8	"Dalle %2d:%02d"
9	"am"
10	"pm"
11	"am"
12	"pm"
13	"Dalle %02d%02d alle %02d%02d"
16	"Non è possibile eliminare l'agenda predefinita"
17	"Selezionare il nome da eliminare"
20	"Data non valida nel campo Andare a"
21	"Editare elenco..."
22	"Voci del menu Consultare"
23	"Settimana precedente"
24	"Settimana corrente"
25	"Settimana successiva"
26	"Mese precedente"
27	"Mese successivo"
28	"Andare a:"
29	"Fissare appuntamento..."
30	"Posta..."
31	"Agenda visualizzata"
32	"Agende visualizzate"
33	"Giorno"
34	"Settimana"
35	"Mese"
36	"Anno"
37	"Fuso orario..."
38	"Elenco degli appuntamenti..."
40	"Visualizzare"
41	"Ricercare..."
42	"Andare alla data..."
65	"File"
68	"Stampare l'agenda visualizzata"
69	"Stampare..."
72	"Opzioni..."
73	"Chiudere"
74	"Appuntamento..."
76	"Editare"
77	"Aiuto"
79	"Attività..."
80	"Riferimenti..."
82	"Uso dell'aiuto..."
84	"Mostrare altra agenda..."
85	"Confrontare agende..."
86	"Editor del menu..."
87	"Consultare"
88	"Oggi"
89	"in quit_handler\n"
90	"Errore nell'apertura del file dell'Agenda"
91	"rpc.cmsd non risponde al nome utente specificato.\nVerificare che il processo inetd sia in esecuzione\ne che la riga di inetd.conf per rpc.cmsd sia corretta per l'host in uso."
92	"Nome utente"
93	"Host"
94	"Errore dell'Agenda"
95	"Continuare"
96	"Nessun file dell'Agenda esistente per"
97	"Nessun file dell'Agenda esistente per"
98	"Errore dell'Agenda"
99	"Continuare"
100	"SENZA NOME"
101	"rpc.cmsd non risponde per"
102	"rpc.cmsd non risponde al nome utente specificato.\nVerificare che il processo inetd sia in esecuzione\ne che la riga di inetd.conf per rpc.cmsd sia corretta per l'host in uso."
103	"Nome utente"
104	"Host"
105	"Errore dell'Agenda"
106	"Continuare"
107	"%s: SENZA NOME"
108	"Nessuna posizione specificata per"
109	"Nessuna posizione specificata; inserire un nome host\nnel campo `Agenda da visualizzare all'avvio' in Caratteristiche/Impostazioni di visualizzazione. \nSe DTCM viene avviato con l'opzione -c, accertarsi di specificare un nome host."
110	"Errore dell'Agenda"
111	"Continuare"
112	"Le versioni di DTCM e rpc.cmsd sono diverse."
113	"Agenda"
114	"gennaio"
115	"febbraio"
116	"marzo"
117	"aprile"
118	"maggio"
119	"giugno"
120	"luglio"
121	"agosto"
122	"settembre"
123	"ottobre"
124	"novembre"
125	"dicembre"
126	"Gen"
127	"Feb"
128	"Mar"
129	"Apr"
130	"Mag"
131	"Giu"
132	"Lug"
133	"Ago"
134	"Set"
135	"Ott"
136	"Nov"
137	"Dic"
138	"Dom"
139	"Lun"
140	"Mar"
141	"Mer"
142	"Gio"
143	"Ven"
144	"Sab"
145	"Dom"
146	"Domenica"
147	"Lunedì"
148	"Martedì"
149	"Mercoledì"
150	"Giovedì"
151	"Venerdì"
152	"Sabato"
153	"Domenica"
154	"D"
155	"L"
156	"M"
157	"M"
158	"G"
159	"V"
160	"S"
161	"D"
162	"D"
163	"L"
164	"M"
165	"M"
166	"G"
167	"V"
168	"S"
169	"D"
170	"DOM"
171	"LUN"
172	"MAR"
173	"MER"
174	"GIO"
175	"VEN"
176	"SAB"
177	"DOM"
178	"Si sta già consultando %s"
186	"Le versioni di DTCM e rpc.cmsd sono diverse"
187	"Sintassi:\n\tdtcm_delete [-c agenda] [-d <mm/gg/aa>] [-v vista]\n"
188	"\nImpossibile aprire l'agenda %s\n"
189	"SCONOSCIUTO"
190	"Elemento da cancellare (numero)? "
191	"Sintassi:\n\tdtcm_insert [ -c agenda ] [-d <mm/gg/aa>] [ -v vista ]\n"
192	"                   [-w descrizione] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"
193	"Inserire le informazioni relative all'appuntamento da aggiungere.\nI valori predefiniti sono mostrati tra parentesi.\n"
194	"Agenda (%s): "
195	"Data (%s): "
196	"Inizio (%s): "
197	"È stata inserita un'ora non valida. Ripetere:\n"
198	"Fine (%s): "
199	"Fine (%s): "
200	"Singolo"
201	"Ripetere (%s): "
202	"Singolo"
203	"nessun valore predefinito"
204	"Per (%s): "
205	"Descrizione (inserire fino a 5 righe, usare ^D per terminare):\n"
206	"\nImpossibile aprire l'agenda %s\n"
207	"Sintassi:\n\tdtcm_lookup [ -c agenda ][ -d <mm/gg/aa> ] [ -v vista ]\n"
208	"\nImpossibile aprire l'agenda \"%s\"\n"
209	"SCONOSCIUTO"
210	"L'appuntamento verrà fissato nell'agenda\nattualmente in consultazione. Confermare l'operazione?"
211	"Fissare in"
212	"Fissare l'appuntamento"
214	"Appuntamento fissato: %s\n"
218	"La DATA specificata non è valida"
219	"L'ora di INIZIO specificata non è valida"
220	"L'ora di FINE specificata non è valida"
221	"Campo DATA vuoto o mancante"
222	"Campo INIZIO vuoto o mancante"
223	"Campo DESCRIZIONE vuoto o mancante"
224	"Incoerenza tra i campi RIPETERE e PER"
225	"La registrazione dell'appuntamento è stata annullata"
226	"Errore interno nel fissare l'appuntamento."
227	"La registrazione dell'appuntamento è stata annullata."
228	"Caricare l'appuntamento"
229	"Continuare"
230	"Trascinare l'appuntamento"
231	"Selezionare un appuntamento e ripetere il comando TRASCINARE."
232	"Continuare"
234	"Trascinare l'appuntamento"
235	"Continuare"
236	"CalendarAppointment"
237	"XCreateBitmapFromData() non eseguito per la mappa di bit.\n"
238	"XCreateBitmapFromData() non eseguito per la maschera.\n"
239	"DragStart ha restituito il valore NULL.\n"
242	"am"
243	"pm"
244	"%s 3:41am"
245	"am"
246	"pm"
247	"L'ora di fine di questo appuntamento è anteriore\nall'ora di inizio. Si desidera\nfissarla per il giorno successivo?"
248	"Fissare l'appuntamento"
250	"Giorno successivo"
251	"Autore"
252	"Cancellare l'appuntamento"
253	"Selezionare un appuntamento e ripetere il comando CANCELLARE."
254	"Continuare"
255	"Cancellare l'appuntamento"
256	"Errore interno nel selezionare l'appuntamento.\nL'appuntamento non è stato cancellato."
257	"Continuare"
258	"Cambiare l'appuntamento"
259	"Selezionare un appuntamento e ripetere il comando CAMBIARE."
260	"Continuare"
261	"Cambiare l'appuntamento"
262	"Errore interno nel selezionare l'appuntamento.\nL'appuntamento non è stato cambiato."
263	"Continuare"
267	"Cambiare l'appuntamento"
268	"Questo appuntamento è ripetuto più volte.\nSi desidera cambiare..."
270	"Solo questo"
271	"In avanti"
272	"Tutti"
273	"Cancellare l'appuntamento"
274	"Questo appuntamento è ripetuto più volte.\nSi desidera cancellare..."
276	"Solo questo"
277	"In avanti"
278	"Tutti"
279	"Editor degli appuntamenti"
280	"Visualizzare l'elenco degli appuntamenti"
281	"Spiacente, l'elenco degli appuntamenti è vuoto!"
282	"Continuare"
283	"Agenda - Ricerca"
284	"Ricercare:"
285	"Ricercare"
289	"Aiuto"
290	"Specificare la stringa da ricercare negli appuntamenti."
291	"Appuntamento non trovato."
292	"%d appuntamenti trovati"
293	"Data:"
294	"Andare a"
296	"Aiuto"
297	"Inserire una data"
298	"%s è già visualizzato"
299	"Data non valida"
300	"Autore"
304	"Posta..."
305	"Inserire l'appuntamento di gruppo"
306	"Selezionare un'agenda e ripetere il comando INSERIRE."
307	"Continuare"
308	"Cancellare l'appuntamento"
309	"Selezionare un appuntamento e ripetere il comando CANCELLARE."
310	"Continuare"
311	"Cancellare l'appuntamento"
312	"Errore interno nel selezionare l'appuntamento.\nL'appuntamento non è stato cancellato."
313	"Continuare"
314	"Cancellare l'appuntamento di gruppo"
315	"Selezionare un'agenda e ripetere il comando CANCELLARE."
316	"Continuare"
317	"Cancellare l'appuntamento"
318	"Questo appuntamento è ripetuto più volte.\nSi desidera cancellare..."
320	"Solo questo"
321	"In avanti"
322	"Tutti"
323	"Cambiare l'appuntamento"
324	"Selezionare un'agenda e ripetere il comando CAMBIARE."
325	"Continuare"
326	"Cambiare l'appuntamento"
327	"Errore interno nel selezionare l'appuntamento.\nL'appuntamento non è stato cambiato."
328	"Continuare"
329	"Cambiare l'appuntamento di gruppo"
330	"Selezionare un'agenda e ripetere il comando CAMBIARE."
331	"Continuare"
332	"Cambiare l'appuntamento"
333	"Questo appuntamento è ripetuto più volte.\nSi desidera cambiare..."
335	"Solo questo"
336	"In avanti"
337	"Tutti"
340	"Agenda"
341	"Accesso"
342	"Inserire"
343	"Modificare"
348	"Inserire autorizzazione"
349	"Editor degli appuntamenti di gruppo"
350	"Errore di selezione, impossibile continuare\n"
351	"Selezione abbandonata dall'utente.\n"
352	"Selezionare un componente all'interno del proprio appuntamento.\n"
353	"Ora non specificata"
354	"Tutto il giorno"
355	"Impossibile aprire il file callog.\nL'operazione è stata annullata. Agenda"
356	"Per richiesta dell'utente, l'operazione è stata annullata.\nAgenda"
357	"Valore non valido nel campo DATA.\nL'operazione è stata annullata. Agenda"
358	"Valore non valido nel campo INIZIO.\nL'operazione è stata annullata. Agenda"
359	"Valore non valido nel campo FINE.\nL'operazione è stata annullata. Agenda"
360	"Occorre specificare un valore per DATA.\nL'operazione è stata annullata. Agenda"
361	"Occorre specificare un valore per INIZIO.\nL'operazione è stata annullata. Agenda"
362	"Occorre specificare un valore per DESCRIZIONE.\nL'operazione è stata annullata. Agenda"
363	"Valori non valido o incoerenti nei campi RIPETERE e PER.\nL'operazione è stata annullata. Agenda"
364	"Operazione dell'Editor non eseguita"
365	"Continuare"
367	"L'Agenda specificata esiste già.\nL'operazione è stata annullata. Agenda"
368	"L'Agenda specificata non esiste.\nL'operazione è stata annullata. Agenda"
370	"Errore di autorizzazione. Autorizzazione negata.\nL'operazione è stata annullata. Agenda"
378	"Errore di allocazione della memoria - memoria insufficiente.\nL'operazione è stata annullata. Agenda"
383	"Errore non identificato.\nL'operazione è stata annullata. Agenda"
386	"L'ora di fine di questo appuntamento è anteriore\nall'ora di inizio. Si desidera\nfissarlo per il giorno successivo?"
387	"Fissare l'appuntamento"
389	"Giorno successivo"
390	"Riservatezza:"
391	"Posizione dell'agenda utente:"
392	"Inizio/fine della giornata:"
393	"Inizio:"
394	"Fine:"
395	"Visualizzazione ora:"
396	"12 ore"
397	"24 ore"
398	"Vista predefinita:"
399	"Anno"
400	"Mese"
401	"Settimana"
402	"Giorno"
403	"Agenda da visualizzare all'avvio:"
404	"Accesso dell'utente"
405	"Selezionare almeno un'autorizzazione."
406	"Continuare"
407	"Impostazioni di accesso del gruppo -- Eliminare"
408	"È necessario selezionare un nome."
409	"Continuare"
410	"Nome utente:"
411	"Aggiungere nome"
412	"Autorizzazioni"
413	"Autorizzazioni"
414	"Eliminare nome"
415	"C = Consultazione I = Inserimento Z = Cancellazione"
416	"Autorizzazioni:"
417	"Consultazione"
418	"Inserimento"
419	"Cancellazione"
420	"Destinazione:"
421	"Stampante"
422	"File"
423	"Stampante:"
424	"Directory:"
425	"Opzioni:"
426	"File:"
427	"Larghezza:"
428	"Altezza:"
429	"Posizione:"
430	"pollici da sinistra"
431	"pollici dal basso"
432	"Unità:"
433	"Copie:"
434	"Includere:"
435	"Appuntamenti da visualizzare con l'ora e il testo"
436	"Appuntamenti da visualizzare con solo l'ora"
437	"Appuntamenti da non visualizzare"
438	"Formato della data:"
439	"MM | GG | AA"
440	"GG | MM | AA"
441	"AA | MM | GG"
442	"Separatore della data:"
443	"Spazio vuoto"
444	"Salvare le opzioni dell'Agenda"
445	"Errore durante la scrittura in ~/.desksetdefaults.\nVerificare di possedere le autorizzazioni di scrittura per questo file."
446	"Continuare"
447	"Leggere le opzioni dell'Agenda"
448	"Errore durante la lettura da ~/.desksetdefaults.\nVerificare di possedere le autorizzazioni di lettura per questo file."
449	"Continuare"
450	"Aiuto dell'Editor degli appuntamenti"
451	"Le modifiche non sono state salvate. \nÈ possibile salvare le modifiche, abbandonarle \no ritornare al riquadro di dialogo."
452	"Salvare"
453	"Annullare"
454	"Salvare le opzioni dell'Agenda"
456	"Continuare"
458	"Agenda -  Opzioni"
459	"Categoria:"
460	"Applicare"
463	"Aiuto"
464	"ps_open_file(): Specificare una directory o un file\n"
465	"ps_open_file(): Directory %s non valida\n"
466	"w+"
467	"ps_open_file(): Impossibile aprire il file %s\n"
468	"Pagina"
469	"Vista del giorno"
470	"Mattino"
471	"Pomeriggio"
472	"pm"
473	"Elenco degli impegni"
474	"Elenco degli appuntamenti"
475	"Pagina"
476	"di"
477	"Vista del mese"
478	"di"
479	"Pagina"
480	"Dom"
481	"Lun"
482	"Mar"
483	"Mer"
484	"Gio"
485	"Ven"
486	"Sab"
487	"ps_init_printer(): Impossibile aprire il file postscript prolog: %s\n"
488	"di"
489	"   Pagina"
490	"Vista della settimana"
491	"L"
492	"M"
493	"M"
494	"G"
495	"V"
496	"S"
497	"D"
505	"Sab"
506	"Dom"
507	"Vista dell'anno"
508	"Vista dell'anno"
523	"Elenco degli impegni: Anno di %d"
524	"Elenco degli appuntamenti: Anno di %d"
525	"Elenco degli impegni: %s"
526	"Elenco degli appuntamenti: %s"
527	"Elenco degli impegni: Settimana di %s"
528	"Elenco degli appuntamenti: Settimana di %s"
529	"Elenco degli impegni: %s"
530	"Elenco degli appuntamenti: %s"
531	"Ogni %d %s"
532	"DTCM: Ripetere ogni"
533	"Ripetere ogni:"
534	"Ripetere:"
535	"Per:"
536	"Riservatezza:"
537	"Fissare l'appuntamento"
538	"Si desidera fissare questo appuntamento nell'ultima\nsettimana del mese o nella quarta settimana del mese?"
540	"Ultima settimana"
541	"Quarta settimana"
542	"Ogni %d %s"
543	"Ogni %d %s"
544	"Ogni %d %s"
559	"Consultazione di %s in corso..."
560	"Agenda - Mostrare altra agenda"
561	"Nome utente:"
562	"Mostrare"
564	"Aiuto"
565	"Autore"
566	"Cancellare l'impegno"
567	"Selezionare un impegno e ripetere il comando CANCELLARE."
568	"Continuare"
569	"Cancellare l'impegno"
570	"Errore interno nel selezionare l'impegno.\nL'impegno non è stato cancellato."
571	"Continuare"
572	"Cancellare l'impegno"
573	"Questo impegno è ripetuto più volte.\nSi desidera cancellare..."
575	"Solo questo"
576	"In avanti"
577	"Tutti"
578	"Cambiare l'impegno"
579	"Questo impegno è ripetuto più volte.\nSi desidera cambiare..."
581	"Solo questo"
582	"In avanti"
583	"Tutti"
584	"Cambiare l'impegno"
585	"Selezionare un impegno e ripetere il comando CAMBIARE."
586	"Continuare"
587	"Cambiare l'impegno"
588	"Errore interno nella selezione.\nL'impegno non è stato cambiato."
589	"Continuare"
590	"Data:"
591	"Editor degli impegni"
595	"Settimana con inizio da %s"
596	"Lunedì %d"
597	"Martedì %d"
598	"Mercoledì %d"
599	"Giovedì %d"
600	"Venerdì %d"
601	"Sabato %d"
602	"Domenica %d"
603	"Digitare il nome da aggiungere nel campo Nome utente"
604	"è già nell'elenco"
605	"Aiuto"
606	"Errore dell'Agenda"
607	"Errore interno nella registrazione del nome dell'agenda."
608	"Continuare"
609	"Errore"
610	"Errore interno nel richiamare il nome dell'agenda."
611	"Continuare"
612	"Panoramica..."
613	"Informazioni sull'Agenda..."
617	"Oggi"
618	"L'argomento -session richiede un parametro\n"
619	"Inserire il nome di un'agenda nel formato: <utente>@<nomehost>"
620	"Agenda sconosciuta. Usare il formato: <nome>%s"
621	"Inserire il nome di un'agenda nel formato: <utente>@<nomehost>"
622	"Agenda sconosciuta. Inserire il nome host: %s@<nomehost>"
623	"L'Agenda non visualizza le date anteriori al 1 gennaio 1970"
624	"L'Agenda non visualizza le date posteriori al 31 dicembre 2037"
625	"Ridurre finestra"
626	"Espandere finestra"
627	"Trascinare appuntamento"
628	"Ora  Descrizione"
629	"Espandere finestra"
631	"%d appuntamento/i trovato/i"
632	"Selezionare un appuntamento da visualizzare"
633	"Agenda selezionata"
634	"Agende selezionate"
635	"Ridurre finestra"
636	"Espandere finestra"
637	"Altri"
641	"Il server non è riuscito a ottenere l'indirizzo di rete\nper la posizione specificata: nome host non valido."
642	"Il daemon rpc.cmsd non è registrato.\nVerificare che rpc.cmsd sia installato correttamente sul sistema."
643	"Impossibile accedere all'agenda. Agenda"
644	"Orari dell'appuntamento:"
645	"Durata:"
646	"minuti"
647	"Ricerca di %s in corso..."
648	"SunDex"
649	"Agenda - Fuso orario"
650	"Ora locale"
652	"Ora personalizzata"
653	"GMT"
654	"ore"
655	"OK"
656	"Applicare"
658	"Aiuto"
659	"Fuso orario:"
660	"Fuso orario:"
662	"Fuso orario:"
663	"Ridurre finestra"
664	"Espandere finestra"
666	"Espandere finestra"
667	"L'Agenda non visualizza le date anteriori al 1 gennaio 1970"
668	"L'Agenda non visualizza le date posteriori al 31 dicembre 2037"
670	"Dtcm"
671	"Versione"
672	"Revisione"
674	"Copyright (c) 1993, 1994:"
675	"Hewlett-Packard Company"
676	"International Business Machines Corp."
677	"Novell, Inc."
678	"Sun Microsystems, Inc."
679	"Altre informazioni..."
680	"Chiudere"
681	"Hanno contribuito alla realizzazione"
682	"Questa applicazione è stata realizzata da:"
683	"Chiudere"
684	"I nomi degli utenti non possono contenere spazi vuoti o tabulazioni"
685	"Nome utente:"
686	"Aggiungere nome"
687	"Cancellare nome"
688	"Voci del menu Consultare"
689	"OK"
690	"Applicare"
691	"Ripristinare"
693	"Aiuto"
696	"Sintassi:\n\tdtcm_admin [ -d ] [ -a azione ] [ -c agenda ][ -s <mm/gg/aa> ] [ -e <mm/gg/aa> ] [-f nomefile]\n"
697	"È stata specificata un'operazione di amministrazione non supportata \"%s\".\n"
698	"\nImpossibile aprire il file di output \"%s\"\n"
699	"\nImpossibile aprire il file di input \"%s\"\n"
700	"Abbandonare"
702	"Aiuto"
703	"contesto"
704	"Anno %d"
705	"%s"
706	"Settimana di %s"
707	"%s"
708	"Il tipo di ripetizione di questo appuntamento è sconosciuto. Tutte le occorrenze verranno modificate\nConfermare la modifica?"
710	"Confermare"
711	"Il tipo di ripetizione di questo appuntamento è sconosciuto. Tutte le occorrenze verranno cancellate\nConfermare la cancellazione?"
712	"Confermare"
713	"La data d'inizio deve essere anteriore a quella finale."
714	"L'elenco non contiene appuntamenti. È necessario trovare un appuntamento per visualizzarlo."
715	"Agenda - Andare alla data"
716	"Il tipo di ripetizione di questo appuntamento è sconosciuto. Tutte le occorrenze verranno cancellate\nConfermare la cancellazione?"
717	"Confermare"
718	"Il tipo di ripetizione di questo appuntamento è sconosciuto. Tutte le occorrenze verranno modificate\nConfermare la modifica?"
720	"Confermare"
721	"Visualizzare l'ora e il testo"
722	"Visualizzare solo l'ora"
723	"Non visualizzare"
724	"Gli appuntamenti senza orario devono comprendere una DESCRIZIONE.\nL'operazione è stata annullata. Agenda"
725	"La voce specificata non esiste.\nL'operazione è stata annullata. Agenda"
727	"Tempo scaduto senza risposta.\nVerificare che rpc.cmsd sia installato in modo corretto sul sistema."
728	"Agenda - Stampa"
729	"Nome della stampante:"
730	"Copie:"
731	"Dal:"
732	"Al:"
733	" Opzioni del comando di stampa:"
734	"Stampare su file:"
735	"Stampare"
736	"Agenda : Errore - Stampa"
737	"Aiuto"
738	"Elenco utenti autorizzati:"
739	"Livello di accesso:"
740	"Aggiungere"
741	"Cancellare"
742	"Modificare"
743	"Pubblico:"
744	"Semiprivato:"
745	"Privato:"
746	"Consultazione"
747	"Inserimento"
748	"Modifica"
749	"Per aggiungere una voce all'elenco degli utenti autorizzati occorre specificarne il nome e i diritti di accesso"
750	"Impostazioni di accesso al gruppo di agende -- Inserimento"
751	"Questa voce fa già parte dell'elenco utenti autorizzati. Si desidera modificarla?"
752	"Impostazioni di accesso al gruppo di agende -- Inserimento"
753	"Modificare"
755	"Impostazioni di accesso al gruppo di agende -- Modifica"
756	"Per modificare una voce dell'elenco degli utenti autorizzati occorre specificarne il nome e i diritti di accesso"
757	"Impostazioni di accesso al gruppo di agende -- Modifica"
758	"mezzanotte"
759	"valore"
760	"valore"
761	"Abbandonare"
762	"Valori predefiniti dell'Editor"
763	"Impostazioni di visualizzazione"
764	"Elenco utenti autorizzati e autorizzazioni"
765	"Impostazioni della stampante"
766	"Formato della data"
767	"OK"
768	"Ripristinare"
772	"Non è possibile salvare una posizione senza nome\no che contenga spazi vuoti.\nLe impostazioni non sono state salvate."
773	"Non è possibile salvare un'agenda iniziale senza nome\no che contenga spazi vuoti.\nLe impostazioni non sono state salvate."
774	"ps_open_file(): è necessario indicare un nome di file per stampare su file\n"
775	"È necessario specificare un anticipo per il promemoria\nL'operazione è stata annullata. Agenda"
776	"L'anticipo del promemoria non può contenere spazi vuoti\nL'operazione è stata annullata. Agenda"
777	"I valori di anticipo devono essere numeri, e possono essere preceduti dal segno\nL'operazione è stata annullata. Agenda"
778	"Aiuto dell'elenco degli impegni dell'agenda"
779	"Alcune modifiche non sono state salvate.\nÈ possibile salvare le modifiche, abbandonarle \no tornare al punto precedente nel riquadro di dialogo."
780	"Eliminare"
781	"Visualizzare"
782	"Tutti"
783	"In sospeso"
784	"Completati"
785	"OK"
786	"Applicare"
788	"Aiuto"
789	"Tipo di impegni:"
790	"contesto"
791	"Il tipo di ripetizione di questo impegno è sconosciuto. Tutte le occorrenze verranno cancellate.\nConfermare la cancellazione?"
793	"Confermare"
794	"Il tipo di ripetizione di questo appuntamento è sconosciuto. Tutte le occorrenze verranno modificate.\nConfermare la modifica?"
796	"Confermare"
797	"Impegni"
798	"Ora:"
799	"Completato"
800	"Inserire"
801	"Modificare"
802	"Cancellare"
803	"Ripristinare"
805	"Aiuto"
806	"Anno %d"
807	"%s"
808	"Settimana di %s"
809	"%s"
810	"Inserire una data di inizio posteriore al 1/1/1970"
811	"Data di inizio errata"
812	"Inserire una data finale anteriore al 1/1/2038"
813	"Data finale errata"
814	"È necessario inserire una data compresa tra il 1969 e il 2038"
815	"È necessario inserire una data compresa tra il 1969 e il 2038"
816	"Giorni"
817	"Settimane"
818	"Mesi"
819	"La Durata deve essere un numero intero senza segno.\nLe impostazioni non sono state salvate."
820	"Il campo Inizio deve contenere un'ora valida.\nLe impostazioni non sono state salvate."

$ 821	"La larghezza di stampa specificata non è valida.\nLe impostazioni non sono state salvate."
$ "print width" has been replaced by "right margin".
821	"Il margine destro specificato non è valido.\nLe impostazioni non sono state salvate."

$ 822	"L'altezza di stampa specificata non è valida.\nLe impostazioni non sono state salvate."
$ "print height" has been replaced by "bottom margin".
822	"Il margine inferiore non è valido.\nLe impostazioni non sono state salvate."

825	"Giorni"
826	"Settimane"
827	"Mesi"
828	"Data:"
829	"Inizio:"
830	"AM"
831	"PM"
832	"Fine:"
833	"AM"
834	"PM"
835	"Descrizione:"
836	"Frequenza"
837	"Inserire/Modificare impegno"
839	"Agenda: Promemoria"
840	"Chiudere"
841	"Fare clic su \"Aggiungere nome\" per aggiungere un nome, \"Applicare\" per confermare le modifiche."
842	"Le informazioni trasferite non\ncontengono alcun appuntamento."
843	"Operazione di trascinamento e rilascio non riuscita."
844	"Impossibile trovare le informazioni trasferite."
845	"Operazione di trascinamento e rilascio non riuscita\nErrore interno di coerenza."
846	"Salvare"
847	"Ripristinare"
848	"Data"
849	"Ora"
850	"Descrizione"
851	"Mostrare appuntamento"
852	"Una volta"
853	"Ogni giorno"
854	"Ogni settimana"
855	"Ogni due settimane"
856	"Ogni mese per data"
857	"Ogni mese per giorno della settimana"
858	"Ogni anno"
859	"Da lunedì a venerdì"
860	"Lunedì, mercoledì, venerdì"
861	"Martedì e giovedì"
862	"Ripetere ogni..."
863	"2"
864	"3"
865	"4"
866	"5"
867	"6"
868	"7"
869	"8"
870	"9"
871	"10"
872	"11"
873	"12"
874	"13"
875	"14"
876	"sempre"
877	"Min."
878	"Ore"
879	"Giorni"
880	"Aiuto"
881	"Errore interno n.1: Gestione dell'agenda/voce non valida.\nL'operazione è stata annullata. Agenda"
882	"Errore interno n.2: Gestione della sessione non valida.\nL'operazione è stata annullata. Agenda"
883	"Errore interno n.3: Valore di data non valido.\nL'operazione è stata annullata. Agenda"
884	"Errore interno n.4: Valore specificato per un attributo di sola lettura.\nL'operazione è stata annullata. Agenda"
885	"Errore interno n.5: Tipo di dati specificato non corretto come valore di attributo.\nL'operazione è stata annullata. Agenda"
886	"Errore interno n.6: L'attributo specificato non è supportato da questa versione dell'agenda.\nL'operazione è stata annullata. Agenda"
887	"Errore interno n.7: La funzione specificata non è supportata da questa versione dell'agenda.\nL'operazione è stata annullata. Agenda"
888	"Errore interno n.8: L'operatore specificato non è valido.\nL'operazione è stata annullata. Agenda"
890	"Errore dei servizi dell'agenda"
891	"Stampare"
892	"Le date per la stampa devono essere comprese tra il 1969 e il 2038."
893	"Stampare"
894	"Data \"Dal\" errata"
895	"Stampare"
896	"Data \"Al\" errata"
897	"Stampare"
898	"La data \"Al\" indicata per la stampa deve essere successiva alla data \"Dal\""
899	"Inizio elenco impegni: %s"
900	"Inizio elenco appuntamenti: %s"
901	"Ripetere ogni..."
902	"Da lunedì a venerdì"
903	"Lunedì, mercoledì, venerdì"
904	"Martedì e giovedì"
905	"Ripetere ogni..."
906	"Trascinare impegno"
907	"Spazio disponibile insufficiente per il file dell'agenda.\nL'operazione è stata annullata. Agenda"
908	"Non è possibile impostare un valore di promemoria vuoto.\nLe impostazioni delle caratteristiche non sono state salvate."
909	"Non è possibile impostare un valore di promemoria con uno spazio vuoto al suo interno.\nLe impostazioni delle caratteristiche non sono state salvate."
910	"I valori dei promemoria devono essere numeri e possono essere preceduti da un segno.\nLe impostazioni delle caratteristiche non sono state salvate."

$ 911	"È stata specificata una posizione di spostamento da sinistra non valida.\nLe impostazioni delle caratteristiche non sono state salvate."
$ "position from left offset" has been changed to "left margin".
911	"Il valore del margine sinistro non è valido.\nLe impostazioni delle caratteristiche non sono state salvate."

$ 912	"È stata specificata una posizione di spostamento da destra non valida.\nLe impostazioni delle caratteristiche non sono state salvate."
$ "position from right offset" has been changed to "top margin".
912	"Il valore del margine superiore non è valido.\nLe impostazioni delle caratteristiche non sono state salvate."

913	"Un impegno deve contenere del testo nella prima riga della voce Descrizione."
914	"Operazione dell'Editor non riuscita"
915	"Operazione dell'Editor non riuscita"
916	"Il valore di Durata deve essere inferiore a 24 ore.\nLe impostazioni delle caratteristiche non sono state salvate."
917	"Grafico\nmancante"
918	"Grafico\nmancante"
919	"Agenda"
920	"visualizzata."
921	"Impossibile accedere all'Agenda: "
922	"Informazioni sull'Agenda"
923	"Annullare"
924	"Annullare"
925	"Annullare"
926	"Chiudere"
927	"Annullare"
928	"Annullare"
929	"Annullare"
930	"Inserire"
931	"Modificare"
932	"Cancellare"
933	"Ripristinare"
934	"Annullare"
935	"Aiuto"
936	"Annullare"
937	"Annullare"
938	"Annullare"
939	"Annullare"
940	"Chiudere"
941	"Chiudere"
942	"Annullare"
943	"Annullare"
944	"Annullare"
945	"Annullare"
946	"Annullare"
947	"Annullare"
948	"Chiudere"
949	"Annullare"
950	"Annullare"
951	"Annullare"
952	"Chiudere"
953	"Annullare"
954	"Chiudere"
955	"Annullare"
956	"Annullare"
957	"Annullare"
958	"Annullare"
959	"Annullare"
960	"Annullare"
961	"Annullare"
962	"Annullare"
963	"Agenda - Editor del menu"
964	"Sull'elemento"
965	"Elenco degli impegni..."
966	"Impegno..."
967	"Versione del server dell'agenda"
968	"Versione dell'agenda"
969	"Ripetere ogni"
970	"Il valore \"Ripetere ogni\" deve essere un numero intero senza segno."
971	"Ora Agenda"
972	"Descrizione"

973	"Ricercare in tutti"
974	"Ricerca dal"
975	"al"
976	"Tipo di agenda:"
977	"Giorno"
978	"Settimana"
979	"Mese"
980	"Anno"
981	"Elenco degli appuntamenti"
982	"Elenco degli impegni"
983	"Nome utente"
984	"Questo appuntamento fa parte di una serie che si ripete.\n\
Si desidera inserire tale voce ...?"
985	"Promemoria"
986	"Segnale acustico"
987	"Lampeggio"
988	"Popup"
989	"Posta"
990	"Spedire a:"
992	"%A, %e %B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993	"Settimana di %A, %e %B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994	"giorni"
995	"settimane"
996	"due settimane"
997	"mesi"
998	"anni"
1002	"Hanno anche contribuito:"
1003	"Questo appuntamento appartiene all'agenda di un altro utente.\nConfermare ugualmente la cancellazione?"
1004	"Questo appuntamento appartiene all'agenda di un altro utente.\nConfermare ugualmente la cancellazione?"
1005	"Cancellare dal"
1006	"Modificare in"
1007	"Errore interno durante la selezione dell'appuntamento.\nL'appuntamento non è stato modificato."
1008	"Appuntamento : Aiuto"
1009	"Errore interno durante la selezione dell'Impegno.\nL'Impegno non è stato modificato."
1010	"Agenda : Confrontare agende"
1011	"Valore non valido nel campo \"Ora\".\nOperazione annullata.  Agenda"

1012	"Agenda - Elenco degli impegni"

1042	"Autorizzazione di inserimento negata: "
1043	"Autorizzazione di cancellazione negata: "
1044	"Autorizzazione di consultazione negata: "
1045	"Annullato per"
1046	"Appuntamento annullato\n"
1047	"L'ora di fine dell'appuntamento'%s' è\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048	"L'ora di fine di questo appuntamento è\n"
1049	"anteriore all'ora di inizio. Si desidera fissarla\n"
1050	"per il giorno successivo? [Y/N]  "
1051	"Questo appuntamento '%s' fa parte di una serie che si ripete.  "
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052	"Si desidera:"
1053	"\n\t1.  Cancellare tutti"
1054	"\n\t2.  Cancellare solo questo"
1055	"\n\t3.  Cancellare in avanti"
1056	"\n\t4.  Annullare"
1057	"\n\tOpzione [1-4]: "
1058	"La data specificata non è valida.\n"
1059	"L'ora di Inizio specificata non è valida.\n"
1060	"L'ora di Fine specificata non è valida.\n"
1061	"Campo Data vuoto o mancante.\n"
1062	"Campo Inizio vuoto o mancante.\n"
1063	"Campo Descrizione vuoto o mancante.\n"
1064	"Incoerenza tra i campi Ripetere e Per.\n"
1065	"L'azione Inserire appuntamento è stata annullata.\n"
1066	"L'appuntamento non è stato inserito."
1067	"La data specificata non è valida:"
1068	"Appuntamenti per"
1069	"Nessun appuntamento per"
1070	"Agenda : Errore - Confrontare agende"
1072	"Agenda : Errore - Consultazione"
1073	"Agenda : Errore - Trascinamento e rilascio"
1074	"Appuntamento"
1075	"Agenda : Errore - Modifica dell'appuntamento"
1076	"Agenda : Aiuto"
1078	"Agenda : Elenco utenti autorizzati - Aggiunta"
1079	"Agenda : Errore - Impostazioni dell'Editor"
1083	"Agenda : Errore - Impostazioni della visualizzazione"
1085	"Agenda : Errore - Impostazioni della stampante"

1086	"Agenda - Elenco degli appuntamenti"

1087	"Dalle %1$2d:%2$02d%3$s alle %4$2d:%5$02d%6$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088	"%1$2d:%2$02d%3$s"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089	"Dalle %1$02d%2$02d alle %3$02d%4$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090	"%1$02d%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091	"%B, %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092	"%Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/

1100	"\n\n\
\t** Impegno dell'Agenda **\n\n\
\tData:\t%s\n\
\tOra:\t%s\n\
\tDescrizione:\t\t%s"
1101	"Inserire Appuntamento"
1102	"Inserire Impegno"
1103	"Questo impegno fa parte di una serie che si ripete.\n\
Si desidera inserire tale voce ...?"
1104	"Valore non valido nel campo Ora.\n\
L'operazione è stata cancellata.  Agenda"
1105	"Occorre fornire un valore per l'Ora.\n\
L'operazione è stata cancellata.  Agenda"

$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"Data"
1107	"ID utente"
1108	"Numero di pagina"
1109	"Tipo di agenda"
1110	"Nessun testo"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"Agenda : Errore - Impostazione della stampa"
1112	"Errore Gestione del dialogo di stampa (PDM) - Impostazione non riuscita."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113	"Stampante non valida oppure Server di stampa incorretto."
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114	"Agenda : Errore - Stampa su file"
1115	"Errore - impossibile stampare su file."
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116	"Agenda : Stampa su file"
1117	"L'operazione Stampa su file è stata completata."
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118	"Agenda : Avvertimento - Stampa"
1119	"Avvertimento - Impossibile caricare il font %s."
$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled.
1120	"L'evento non può essere prenotato all'ora richiesta.\nL'operazione è stata annullata."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
1121	"Agenda : Errore del server di stampa"
1122	"Lavoro di stampa fallito.\n\nIl server di stampa X è temporaneamente senza risorse."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Calendar - Warning
$ "-NEW"
2 "Could not connect to ToolTalk:\n%s\n"
$ "-NEW"
3 OK
$ "-NEW"
4 "Calendar : Appointment Editor - Warning"
