$ message catalog of dtimsstart
$ @(#)$XConsortium: dtimsstart.msg /main/3 1996/11/19 19:28:25 rws $

$set 1
$ 	usage
1 Sintassi:  %s  [opzioni ..]
2 stampare le variabili d'ambiente modificate
3 ignorare $SHELL
4 specifica il nome del metodo di input
5 specifica le opzione del comando per il server del metodo input
6 specifica l'host per l'esecuzione del server del metodo input
7 modificare la modalità di selezione del metodo di input
8 stampare il metodo di input registrato
9 visualizza questo messaggio

$ 	selection mode
$ please do not translate ask_at_login and resume_current_input_method
20 Modalità di selezione
21 ask_at_login
22 resume_current_input_method
23 forzare 'resume_current_input_method'
24 forzare 'ask_at_login'

$ 	error messages
31 opzione non valida '%s'
32 variabile d'ambiente 'HOME' non definita
33 variabile d'ambiente 'LANG' non definita
34 il desktop non supporta questa versione locale.
35 variabile d'ambiente 'DISPLAY' non definita
36 impossibile aprire il file\n  [%s]
37 impossibile creare il file\n  [%s]
38 impossibile creare la directory\n  [%s]
39 la riga '%s' è mancante nel file di configurazione\n  [%s]
40 un altro '%s' è già in esecuzione
41 non si trova un file di selezione per '%s'
42 impossibile creare il file di selezione\n  [%s]
43 nessun ims selezionato per '%s'
44 nessun file di configurazione della versione locale per '%s'
45 nessun metdodo ims configurato per '%s'
46 nessun file di configurazione ims per '%s'
47 ims '%s' non è stato registrato
48 nessun file eseguibile per '%s'\n  [%s]
49 ims '%s' è già in esecuzione
50 impossibile eseguire ims '%s'
51 ims '%s' interrotto.  Consultare il logfile.\n  [%s]
52 ims '%s' non è ancora disponibile
53 host sconosciuto '%s'
54 l'azione '%s' è fallita
55 esecuzione remota è fallita su '%s'
56 operazioni remote non sono disponibili su '%s'
57 nessun ims registrato su '%s'
58 ims '%1$s' non è registrato su '%2$s'
59 impossibile aprire il video '%s'

$ 
