$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/43 1999/09/14 15:46:00 mgreess $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "OK" 
2 "Opzioni..." 
3 "Assenza" 
4 "Aggiornamento delle caratteristiche..." 


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "Annullare" 
6 "Gestione posta" 
7 "Gestione posta" 
8 "Gestione posta" 
9 "Cancellare" 
10 "Successivo" 
11 "Precedente" 
12 "Rispondere al mittente" 
13 "Stampare" 
14 "Mittente" 
15 "Oggetto" 
16 "Data e ora" 
17 "Dimensione" 
18 "Casella postale" 
19 "Controllare la posta in arrivo" 
20 "Aprire la casella della posta in arrivo" 
21 "Aprire la casella della posta in arrivo" 
22 "Nuova..." 
23 "Gestione posta - Nuova casella postale" 
24 "Creare" 
25 "Aprire..." 
26 "Gestione posta - Apertura casella postale" 
27 "Aprire" 
28 "Distruggere i messaggi cancellati" 
29 "Chiudere" 
30 "Aprire" 
31 "Salvare come testo..." 
32 "Gestione posta - Messaggio - Salvataggio come testo" 
33 "Copiare in" 
34 "Stampare..." 
35 "Ricercare..." 
36 "Selezionare tutto" 
37 "Cancellare" 
38 "Annullare la cancellazione dell'ultimo messaggio" 
39 "Annullare la cancellazione del messaggio..." 
40 "Messaggio" 
41 "Spostare" 
42 "Gestione posta - Messaggi" 
43 "Copiare" 
44 "Selezionare tutto" 
45 "Editare" 
46 "Gestione posta - Testo" 
47 "Successivo" 
48 "Precedente" 
49 "Intestazioni brevi" 
50 "Per data/ora" 
51 "Per mittente" 
52 "Per oggetto" 
53 "Per dimensione" 
54 "Per stato" 
55 "Visualizzare" 
56 "Nuovo messaggio" 
57 "Nuovo, includere tutto" 
58 "Inoltrare" 
59 "Rispondere al mittente" 
60 "Rispondere a tutti" 
61 "Rispondere al mittente, includere" 
62 "Rispondere a tutti, includere" 
63 "Comporre" 
64 "Spostare" 
65 "Altre caselle postali..." 
66 "Salvare come..." 
67 "Gestione posta - Allegati - Salvataggio come" 
68 "Selezionare tutto" 
69 "Allegati" 
70 "Gestione posta - Allegati" 
71 "Panoramica" 
72 "Attività" 
73 "Riferimenti" 
74 "Sull'elemento" 
75 "Uso dell'aiuto" 
76 "Aiuto" 
77 "Informazioni sulla Gestione posta..." 
78 "La Gestione posta non è in grado di determinare con chiarezza lo stato di questa casella postale.\nChiudere la casella postale scegliendo OK e riavviare l'applicazione." 
79 "Conversione in corso... %d percento" 
80 "Gestione posta" 

$ 
$ Strings from dtmail/AttachArea.C

81 "Gestione posta" 
82 "Gestione posta" 
83 "Gestione posta" 


$ 
$ Strings from dtmail/Attachment.C

84 "%s è un allegato eseguibile. Confermare l'esecuzione?" 
85 "Gestione posta" 
86 "Gestione posta" 
87 "Gestione posta" 
88 "Gestione posta" 


$ 
$ Strings from dtmail/RoamCmds.C

89 "Gestione posta - Altre caselle postali" 
90 "Spostare" 
91 "Stampa in corso..." 
92 "OK" 
93 "Salvare" 
94 "Salvare" 
95 "Salvare" 
96 "Vuotare" 
97 "Cambiare nome" 
98 "Gestione posta - Cambiamento di nome" 
99 "Gestione posta - Chiusura"
100 "OK" 
101 "Annullare" 
102 "La funzione di inoltro è già in uso per\nun'altra attività. Avviando la funzione Assenza,\nessa si aggiungerà all'altra attività in esecuzione.\nConfermare l'avvio di Assenza?\0" 
103 "Gestione posta" 
104 "Il programma vacation è già in esecuzione nel file .forward.\nPer istruzioni su come interromperlo ed eliminarlo dal file .forward, consultare la documentazione.\nEseguire questo comando solo dopo avere risolto il problema.\0" 
105 "Impossibile aprire il file .vacation.msg -- L'utente non possiede l'autorizzazione di scrittura." 
106 "Il file .vacation.msg esiste già. Si desidera sostituirlo con un testo nuovo?" 
107 "Impossibile aprire il file .vacation.msg -- L'utente non possiede l'autorizzazione di scrittura." 
108 "Sono assente" 
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "Sono assente.\nLeggerò i vostri messaggi su \"$SUBJECT\" al mio ritorno.\n" 


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N" 
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N" 


$ 
$ Strings from dtmail/Undelete.C

115 "Ripristinare" 
116 "Chiudere" 

$ 
$ Strings from dtmail/SendMsgDialog.C

117 "Inviare" 
118 "Chiudere" 
119 "Nuovo messaggio" 
120 "Gestione posta" 
121 "File" 
122 "Includere file..." 
123 "Gestione posta - Includere file" 
124 "Includere" 
125 "Salvare come testo..." 
126 "Gestione posta - Salvataggio come testo" 
127 "Registrare nel log" 
128 "Inviare come" 
129 "Chiudere" 
130 "Editare" 
131 "Annullare" 
132 "Tagliare" 
133 "Copiare" 
134 "Incollare" 
135 "Incollare in forma speciale" 
136 "Tra separatori" 
137 "Con margine rientrato" 
138 "Ripulire" 
139 "Cancellare" 
140 "Selezionare tutto" 
141 "Allegati" 
142 "Allegare file..." 
143 "Gestione posta - Allegare file" 
144 "Allegare" 
145 "Salvare come..." 
146 "Gestione posta - Allegati - Salvataggio come" 
147 "Cancellare" 
148 "Annullare la cancellazione" 
149 "Cambiare nome" 
150 "Selezionare tutto" 
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "Mostrare la finestra" 
152 "Formato" 
153 "A capo automatico" 
154 "Impostazioni..." 
155 "Ricercare/sostituire..." 
156 "Controllare ortografia..." 
157 "Modelli" 
158 "Gestione posta - Allegati" 
159 "Gestione posta - Messaggio" 
160 "Nuovo messaggio" 
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "Copiare" 
162 "Selezionare tutto" 
163 "Editare" 
164 "Salvare come..." 
165 "Gestione posta - Allegati - Salvataggio come" 
166 "Selezionare tutto" 
167 "Allegati" 
168 "Gestione posta - Allegati" 
169 "Gestione posta - Testo" 
170 "Panoramica" 
171 "Attività" 
172 "Riferimenti" 
173 "Sull'elemento" 
174 "Uso dell'aiuto" 
175 "Aiuto" 
176 "Informazioni sulla Gestione posta..." 
177 "Gestione posta" 


$ 
$ Strings from dtmail/DtMailGenDialog.C

178 "Gestione posta - Informazioni su Dtmail" 
179 "Dtmail Versione 1.0" 
180 "OK" 
181 "OK" 
182 "Annullare" 

$ 
$ Strings from dtmail/FindDialog.C

183 "Ricercare" 
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "Ricercare e selezionare tutto" 
185 "Cancellare" 
186 "Chiudere" 
187 "Aiuto" 
188 "A:" 
189 "Da:" 
190 "Oggetto:" 
191 "Pc:" 
192 "Gestione posta - Ricerca" 
193 "In avanti" 
194 "Indietro" 
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */



$ 
$ Strings from dtmail/Editor.C

195 "------------- Inizio messaggio inoltrato -------------\n\n" 
196 "------------- Inizio messaggio incluso -------------\n\n" 
197 "------------- Fine messaggio inoltrato -------------\n\n" 
198 "------------- Fine messaggio incluso -------------\n\n" 

$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n------------- Inizio messaggio incluso -------------\n" 
200 "\n------------- Fine messaggio incluso -------------\n" 

$ 
$ Strings from dtmail/DtEditor.C

201 "\n------------- Inizio messaggio incluso -------------\n" 
202 "\n------------- Fine messaggio incluso -------------\n" 

$ 
$ Strings from dtmail/ComposeCmds.C

203 "Gestione posta" 
204 "Impossibile creare la finestra di composizione." 
205 "Gestione posta" 
206 "Impossibile creare la finestra di composizione." 
207 "Gestione posta" 
208 "Impossibile creare la finestra di composizione." 
209 "Gestione posta" 
210 "Impossibile creare la finestra di composizione." 
211 "Gestione posta" 
212 "Il modello specificato non esiste." 
213 "Gestione posta" 
214 "Il modello sembra danneggiato." 
215 "Gestione posta" 
216 "Memoria insufficiente per caricare il modello." 
217 "Gestione posta" 
218 "Il modello sembra danneggiato." 

$ 
$ Strings from dtmail/SortCmd.C

219 "Ordinamento in corso..." 

220 "Selezionare tutto" 
221 "Casella della posta in arrivo" 

222 "%a %d %b %k:%M" 
$ /* NL_COMMENT
$  * The "%a %d %b %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%a %d %b %H:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%a %d %b %k:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%a %d %b %H:%M" 
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "Mostrare gli allegati" 

$ String from Undelete.C, Deleted Messages window title
227 "Gestione posta - Messaggi cancellati"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "Aggiungere"
229 "Cancellare"
230 "Inviare"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "Ricerca in corso..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "1 messaggio selezionato"
233 "%d messaggi selezionati"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "Non è stato trovato nessun messaggio corrispondente allo schema di ricerca."

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "Gestione posta - Informazioni sulla Gestione posta"
236 "Gestione posta - versione %d.%d.%d"
$  /* NL_COMMENT
$   * String 237 is the Copy button on Move Other Mailboxes dialog (from RoamCmds.C)
$   */
237 "Copiare"


$ 
$ DTMC_BADSTATE
$ The mailbox is in a state which cannot be deciphered by the Mailer, i.e.
$ portions of the file have been deleted by another process (the Mailer
$ only knows how to handle other processes adding to the end of the mailbox.
$ 
$ "-NEW"
238 "Mailer is confused about the state of this mailbox.\nIt may be that another process has rewritten this mailbox in an unexpected way.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost."

$ 
$ DTMC_ACCESSFAILED
$ The Mailer cannot perform routine file operations on the mailbox file,
$ a.k.a. stat, fstat, write, ...
$ 
$ "-NEW"
239 "Mailer can no longer access this mailbox.\nIt may be that another process has deleted the mailbox file.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ DTMC_INODECHANGED
$ The mailbox has been rewritten by another process.
$ 
$ "-NEW"
240 "Mailer can no longer access this mailbox.\nAnother process has rewritten the mailbox file changing the inode.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ Messages 241-244 are header field labels for SendMsgDialog.
$ 
$ "-NEW"
241 "A"
$ "-NEW"
242 "Oggetto"
$ "-NEW"
243 "Pc"
$ "-NEW"
244 "Bcc"

$ 
$ Message 245 is the label for the Open command in the File menu
$ Message 246 is the label for the command in the OpenContainer menu
$	which opens Mailboxes not in the users folder list.
$ 
$ "-NEW"
245 "Aprire" 
$ "-NEW"
246 "Altre caselle postali..." 

$ 
$ Message 247 is the label for the command in the Aliases menu
$	which opens the MailOptions dialog allowing the user to create
$	other aliases.
$ Message 248 is the label for the Aliases popup menu
$ 
$ "-NEW"
247 "Altre Alias..."
$ "-NEW"
248 "Gestione posta - Alias"

$ 
$ Messages 249-255 are strings used to generate attachment summaries
$                  in included messages.
$ 
$ "-NEW"
249 "------------- Begin Included Attachment -------------\n\n" 
$ "-NEW"
250 "------------- End Included Attachment -------------\n\n" 
$ "-NEW"
251 "       Attachment Name:  "
$ "-NEW"
252 "     Attachment DtType:  "
$ "-NEW"
253 "Attachment ContentType:  "
$ "-NEW"
254 "Attachment Description:  "
$ "-NEW"
255 "------------------ Attachments ------------------\n" 

$ "-NEW"
$ DTMC_SERVERACCESSFAILED:
$ Mailer failed in attempt to retrieve messages from the mail server
256 "Mail server access failed:\n%s"

$ "-NEW"
$ Label on the button which causes the "Mail Retrieval" options to be displayed
257 "Options..."

$ "-NEW"
$ DTMC_GETMAILCOMMANDFAILED:
$ Mailer failed in attempt to retrieve messages via custom getmail command
258 "User Getmail command failed:\n%s"

$ "-NEW"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
259 "%a %d %b %Y"
260 "%a %d %b %k:%M"
261 "%a %d %b %H:%M"


$ "-NEW"
262 "Messaggi non inviati"

$ "-NEW"
263 "The attachment '%s' is %d kilobytes.\nAdd as attachment?"





$set 2
1 "Gestione posta" 
2 "ToolTalk non è inizializzato. La Gestione posta non può essere avviata senza ToolTalk.\nProvare ad avviare /usr/dt/bin/dtsession, oppure rivolgersi all'amministratore di sistema." 

3 "Impossibile inizializzare le finestre. Operazione interrotta.\n" 
4 "La Gestione posta non è stata installata correttamente, \n\
e non può essere avviata perché il gruppo di \n\
esecuzione non è impostato correttamente."
5 "Autorizzazioni insufficienti per visualizzare %s" 
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "La casella postale %s è una directory e non può essere aperta." 
7 "Impossibile vuotare %s. Il raccoglitore non esiste." 
8 "Il raccoglitore %s è stato vuotato" 
9 "Errore - Impossibile vuotare %s" 
10 "Gestione posta" 
11 "%s" 
12 "Gestione posta" 
13 "Gestione posta" 
14 "Prima di eseguire il comando \"Salvare come\" \noccorre selezionare un allegato." 

15 "Errore - Impossibile individuare mailrc." 
16 "Nessun messaggio selezionato." 
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */


17 "\"%s\" è stato modificato. Confermare ugualmente la cancellazione?" 
18 "Errore: Impossibile includere il file %s" 
19 "Prima di eseguire il comando \"Salvare come\" \noccorre selezionare un allegato." 


20 "Prima di eseguire il comando \"Salvare come\" \noccorre selezionare un allegato." 

21 "Gestione posta" 


22 "Errori gravi nel file ~/.mailrc file.\nControllare la finestra Terminale per ulteriori messaggi. Correggere gli errori e riavviare dtmail.\nAltrimenti, non sarà possibile salvare su file le modifiche apportate nel dialogo Opzioni."
23 "Continuare"
24 "Uscire"
25 "Errori gravi nel file ~/.mailrc \nÈ possibile applicare le impostazioni alla sessione \ncorrente però non sarà possibile salvarle su file." 

$ 
$ Messages for file locking dialog displayed from the Advanced option pane.
$ 
$ "-NEW"
26 "The value of the file locking option has changed.\nTo take immediate effect, folders need to be closed and reopened.\n  o Click on 'Reopen' to reopen folders,\n    making the new option take effect immediately.\n  o Click on 'Continue' to avoid reopening folders.\n    The new option will take effect the next time you open a folder.\n  o Click on 'Cancel' to cancel the Apply and return to editing options."
$ "-NEW"
27 "Reopen"
$ "-NEW"
28 "Continue"
$ "-NEW"
29 "Cancel"

$ 
$ Messages for ToolTalk errors.
$ 
$ "-NEW"
30 "%s returned ToolTalk error: %s\n"


$set 3
1 "Salvataggio automatico..." 

2 "Inizializzazione..." 
3 "La casella postale %s non esiste.\n\
Si desidera creare una casella postale con questo nome?"
4 "Gestione posta" 
5 "OK" 
6 "La casella postale %s è bloccata.\n\
Sbloccare la casella manualmente e riprovare,\n\
oppure rivolgersi all'amministratore di sistema."
7 "Gestione posta" 
8 "OK" 
9 "OK" 
10 "OK" 
11 "OK" 
12 "%s" 
13 "Messaggio %d di %d, %d nuovo/i, %d cancellato/i" 
14 "Messaggio %d di %d, %d nuovo/i, %d cancellato/i" 
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "Salvataggio in corso..." 
16 "Gestione posta" 
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
17 "Confermare la distruzione dei messaggi\n\
selezionati per la cancellazione?"
18 "OK" 
19 "Annullare" 
20 "Apertura della casella postale in corso..." 
21 "%s esiste già.\n\
Sovrascrivere la versione esistente?"
22 "Gestione posta" 
23 "Impossibile sovrascrivere %s.\nControllare le autorizzazioni del file e riprovare." 
24 "Gestione posta" 
25 "Caricamento del raccoglitore in corso..." 
26 "Informazioni generali sulla cartella" 
27 "Caricamento in corso..." 
28 "Vuotare il raccoglitore" 
29 "OK" 
30 "OK" 
31 "OK" 
32 "Distruzione dei messaggi cancellati in corso..." 
33 "OK" 

34 "%s non esiste." 
35 "Impossibile aprire %s." 
36 "Impossibile allocare memoria per l'operazione." 
37 "Informazioni sugli allegati" 
38 "allegato" 
39 "allegati" 
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "allegati" 
41 "cancellati" 

42 "%s esiste già. Sostituire?" 
43 "Impossibile sostituire %s." 
44 "Impossibile creare %s." 
45 "Impossibile creare %s." 


46 "Vuotare il raccoglitore" 
47 "%s esiste già.\nSovrascrivere?" 
48 "Gestione posta" 
49 "Impossibile sovrascrivere %s.\n\
Controllare le autorizzazioni del file e riprovare."
50 "Gestione posta" 
51 "Impossibile creare %s." 
52 "Gestione posta" 
53 "Impossibile scrivere in %s." 
54 "Gestione posta" 
55 "Impossibile creare %s." 
56 "Gestione posta" 
57 "Rinominare l'allegato in" 
58 "Chiudendo la finestra di composizione \n\
il testo e gli allegati andranno perduti.\n\
Confermare la chiusura della finestra?"
59 "Memoria esaurita" 
60 "Memoria insufficiente per caricare il file .vacation.msg." 
61 "Gestione posta" 
62 "Il file .vacation.msg sembra danneggiato." 


63 "Selezionare i messaggi da spostare." 
64 "Selezionare i messaggi da copiare." 
65 "%d messaggi spostati in %s" 
66 "%d messaggio spostato in %s" 
67 "%d messaggi copiati in %s" 
68 "%d messaggio copiato in %s" 
69 "Il messaggio è già visualizzato. La sua finestra verrà portata in primo piano." 
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/



70 "Scrittura nella cartella dei messaggi non inviati..." 
71 "Gestione posta" 
72 "OK" 
73 "Annullare" 
74 "OK" 

75 "OK" 
76 "OK" 


77 "C'è un allegato che contiene modifiche che non sono state salvate.\nLa spedizione del messaggio interromperà il collegamento all'allegato aperto.\Le modifiche non salvate non verranno incluse nel messaggio.\n Il comando Salvare come sarà disponibile\n dopo l'interruzione del collegamento però le modifiche \n non verranno incluse nell'allegato."
78 "Inizializzazione delle Opzioni posta..."
79 "Eliminare e uscire"
80 "Uscire senza eliminare"
81 "L'allegato può contenere comandi che possono causare un grave danno.\nVi raccomandiamo di eseguirlo solo nel caso che siate certi che sia\nappropriato.\n\nPremere OK per eseguire,\nAnnullare per annullare l'esecuzione."
82 "Un altro utente sta usando questa casella postale.\nVolete l'accesso esclusivo?.\n"
83 "La gestione posta non è riuscita ad ottenere l'accesso esclusivo a questa casella postale.\nAprire la casella in modo di sola lettura?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "%d messaggi cancellati"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "%d messaggio cancellato"
86 "Controllo della posta in arrivo..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "Gestione posta - Chiusura"
88 "Eliminare i messaggi cancellati e chiudere la casella postale?"
89 "Eliminare e chiudere"
90 "Mantenere e chiudere"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "L'azione non è valida e non verrà eseguita."
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "Esecuzione fallita."
93 "L'icona selezionata %s è un file eseguibile.\nFare clic su OK per eseguirlo oppure Annullare."

94 "La Gestione posta non è riuscita ad ottenere l'accesso esclusivo a questa casella\npostale perché  il sistema non risponde.\n\nPer la sessione in corso, è possibile aprire la casella in modo di sola lettura\no aprirla in modo di scrittura-lettura senza l'esclusivo accesso."
95 "Sola lettura"
96 "Lettura-Scrittura"

$ 
$ "-NEW"
$ 
$ This message appears when dtmail tries to open a mailbox which has been
$ opened by another dtmail process.
$ 
$ Parameters:
$   1.  Error message saying that the <mailbox>.dtmail lockfile has been found.
$   2.  The mailbox path.
$   3.  "OK"
$   4.  "Cancel"
$   5.  The <mailbox>.dtmail lockfile path.
$ 
97 "%s\n\nThis may indicate that another Mailer has opened\n%s\n\nYou may open this mailbox READ ONLY by choosing '%s'.\n\nOtherwise, you may choose '%s',\nmake sure that another Mailer has not opened this mailbox,\ndelete %s,\nand reopen this mailbox."

$ 
$ "-NEW"
$ 
$ Messages 98-100 check for problems in the paths specified by users of
$ the file selection box.
$ 
98 "Search permission denied on a component of the path prefix,\n'%s'."
99 "A component of the path prefix is not a directory,\n'%s'."
100 "A component of the path prefix does not exist,\n'%s'."



$set 5
1 "Gestione posta" 
2 "Gestione posta" 
3 "Inviando il messaggio nella forma corrente, le \n\
	    modifiche apportate agli allegati andranno perdute."
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "Selezionare solo un allegato\n\
	    e quindi scegliere Cambiare nome"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "Una parte degli indirizzi contenuti nel messaggio non \n\
sono corretti e non corrispondono ad utenti del sistema.\n\
Verificare che tutti gli indirizzi siano validi e riprovare."
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "La Gestione posta non ha memoria sufficiente\n\
per inviare questo messaggio.\n\
Provare a chiudere altre applicazioni \n\
e a ripetere l'invio."
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "Si è verificato un errore durante l'invio del messaggio.\n\
Verificare che il messaggio sia stato ricevuto. \n\
In caso contrario, ripetere l'invio."

$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "Prima di inviare il messaggio, specificare i destinatari nei campi A:, Pc: o Cs:"



$set 12
1 "Allegato" 
2 "Allegati" 
3 "displayCount" 
4 "Impossibile allegare un file FIFO: %s" 
5 "Impossibile allegare un file speciale a caratteri: %s" 
6 "Impossibile allegare una directory: %s" 
7 "Impossibile allegare un file speciale a blocchi: %s" 
8 "Impossibile allegare un file socket: %s" 


$set 13
1 "Creazione non riuscita" 
2 "Scrittura non riuscita" 

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "Aggiungere allegato" 
2 "Impossibile aprire %s" 
3 "Impossibile allegare un file FIFO: %s" 
4 "Impossibile allegare un file speciale a caratteri: %s" 
5 "Impossibile allegare una directory: %s" 
6 "Impossibile allegare un file speciale a blocchi: %s" 
7 "Impossibile allegare un file socket: %s" 
8 "Impossibile aprire %s" 
9 "Gestione posta - Cambiamento di nome all'allegato" 
10 "Descrizione" 
11 "Salvare l'allegato come" 




$set 15
1 "Ci sono modifiche che non sono state salvate.\nSalvare le modifiche, perdere le modifiche oppure\ncontinuare dalla posizione precedente nel dialogo."
2 "Salvare"
3 "Perdere"
$ 
$ The followings are added by IBM for 41J release
$ 
$set 20
1 "La casella postale %s è già aperta."
$ The above message is used in RoamMenuWindow::open
$ See AIXC cmvc defect 175920
2 "Usare il nome locale:"
$ The above message is used in OptCmd::init_advanced_pane()
$ see AIX cmvc defect 176608
3 "Sola lettura"
$ The above message is used in RoamMenuWindow::mapnotify()
$ see AIX cmvc defect 176608

$ 
$	SETS 21 - 25 WERE ADDED TO SUPPORT CDEnext PRINTING
$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$set 21
$ 
$	Messages 1 - 11 are used in DmxPrintJob.
$ 
$ 
$	This is the status message that gets displayed in the MainWindow
$	and RoamMenuWindow status lines when a print job is being executed.
$	The '%s' is the name of the temporary file containing the message(s)
$	to be printed.
1 "Stampa di %s..."

$	Messages 2 - 4 are used in the error popup which gets displayed
$	when an invalid margin specifier has been supplied by the user.
$ 
$	Message 2 is the actual error messagactual error message
$	Message 3 is the title which is displayed in the error popup.
$	Message 4 is the label on the OK button of the error popup.
2 "Sintassi non valida nella specifica del margine:\n %s \n %s \n %s \n %s \nContinuare con i margini predefiniti?"
3 "Gestione posta"
4 "OK"

$	Messages 5 - 11 are format string used to construct the header
$	and footer strings which appear in the printing output.
$ 
$	Message 5 is the format string used to make a Cc header/footer.
$	Message 6 is the format string used to make a Date header/footer.
$	Message 7 is the format string used to make a From header/footer.
$	Message 8 is the format string used to make a Subj't header/footer.
$	Message 9 is the format string used to make a To header/footer.
$	Message 10 is the format string used to make a Page# header/footer.
$	Message 11 is the format string used to make a UserName header/footer.
5 "Pc:  %s"
6 "Data:  %s"
7 "Da:  %s"
8 "Oggetto:  %s"
9 "A:  %s"
10 "Pagina %d di %d"
11 "Posta per:  %s"

$ 
$	Messages 12 - 13, 20 are used in DmxPrintSetup to construct the
$	app-specific printing options for DtMail which will be included
$	in the DtPrintSetupBox.
$ 
$	Message 12 is the label used on the Toggle Button to indicate that
$	multiple messages should be printed in separate spool jobs.
$	Message 13 is the label used on the Toggle Button to indicate that
$	lines which would extend beyond the edge of the printed page be 
$	"wrapped" to the next line.
12 "Stampare separatamente"
13 "A capo automatico"


$	Messages 14 - 15 are status messages for the PrintToFile function.
$ 
$	Message 14 indicates that the PrintToFile function was unsuccessful.
$	Message 15 indicates that the PrintToFile function was successful.
$       NOTE:  'Print to File' should be translated as in DtPrint.msg
$               Set 1, Message 3.
14 "L'operazione 'Stampare su file' non è riuscita."
15 "L'operazione 'Stampare su file' è riuscita."

$       NL_COMMENT 
$          Messages 16 - 19 are obsolete, and have been replaced by 24
$ 
$	Messages 16 - 19 are status messages for the popup PDM function.
$ 
$	Message 16 indicates that there was no pdm deamon running.
$	Message 17 indicates that the pdm deamon was unable to start a pdm.
$	Message 18 indicates that the pdm couldnt connect to the video display.
$	Message 19 indicates that the pdm couldnt connect to the print display.
16 "Impossibile trovare la Gestione del dialogo di stampa PDM nell'ambiente corrente."
17 "Impossibile avviare la Gestione del dialogo di stampa PDM."
18 "Gestione del dialogo di stampa non è autorizzata a collegarsi al display Video"
19 "Gestione del dialogo di stampa non è autorizzata a collegarsi al display Stampa"

$	Message 20 is the label used on the Push Button to bring up
$	the printing options dialog from the DtPrintSetupDialog.
20 "Altre ..."
$       Message 21 is used for the title string on the DtPrintSetupDialog.
21 "Gestione posta - Impostazione della stampa"
 
$       Message 22 is used to alert the user to the fact that the mailer
$                  cannot close the mailer window until a task (usually
$                  a print job) has terminated.
22 "Chiusura in corso: attesa del termine dell'attività corrente..."

$	Message 23 is used to alert the user to the fact that the X Print
$		   Server cannot complete the print request due to a lack
$		   of resources.
23 "Il server di stampa X è temporaneamente senza risorse."
  
$       Messages 24 & 25 are used to handle errors from the PDM
24	"Errore Gestione del dialogo di stampa (PDM) - Impostazione non riuscita."
25	"Continuare"




$ 
$	The messages in this set are used in pulldown menu for the
$	header/footer $	frame which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 8 are used in DmxPrintOptions.
$ 
$ 
$	Message 1 specifies that the page header/footer field be empty.
$	Message 2 put the Cc msg header in the page header/footer field.
$	Message 3 put the Date msg header in the page header/footer field.
$	Message 4 put the From msg header in the page header/footer field.
$	Message 5 put the Subject msg header in the page header/footer field.
$	Message 6 put the To msg header in the page header/footer field.
$	Message 7 put the Page Nmbr msg header in the page header/footer field.
$	Message 8 put the User Name msg header in the page header/footer field.
$set 22
1 "Nessun testo"
2 "Intestazione Pc"
3 "Intestazione Data"
4 "Intestazione Da"
5 "Intestazione Oggetto"
6 "Intestazione A"
7 "Numero di pagina"
8 "Nome dell'utente"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 4 are used in DmxPrintOptions.
$ 
$	Message 1 don't print any message headers.
$	Message 2 print the "standard" msg headers (To, From, Subject, Cc).
$	Message 3 print the "abbreviated" msg headers as defined by the user.
$	Message 4 print all message headers.
$ 
$set 23

1 "Nessuna"
2 "Standard"
3 "Abbreviate"
4 "Tutte"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 5 are used in DmxPrintOptions.
$ 
$	Message 1 use a New Line (CRLF) to separate multiple messages.
$	Message 2 use a Blank Line (2xCRLF) to separate multiple messages.
$	Message 3 use a Line of characters to separate multiple messages.
$	Message 4 start each new message on a new page.
$	Message 5 print each message in it's own spool job.
$ 
$set 24
1 "Nuova riga"
2 "Riga vuota"
3 "Riga di caratteri"
4 "Nuova pagina"
5 "Nuovo lavoro di stampa"

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1 - 2 are used in DmxPrintOptions.
$ 
$ 
$set 25
$ 
$	Label for the option menu used to specify which message headers are
$	printed.
1 "Intestazioni stampate:  "
$ 
$	Label for the option menu used to specify which how multiple messages
$	are separated.
2 "Separare messaggi multipli:  "

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1-4 are used in error dialogs to indicate an invalid
$		     entry for margin specifiers in the printing options pane.
$	Message 5 is the label string on the button to dismiss the error dialog.
$ 
$ 
$set 26
1 "Il valore del margine superiore non è valido:  "
2 "Il valore del margine destro non è valido:"
3 "Il valore del margine inferiore non è valido:"
4 "Il margine sinistro non è valido:"
5 "Continuare"

$ 
$	The following set was added to support the Mail Retrieval option pane.
$ 
$	Messages 1-5 Used in the Server Protocol option menu to indicate the
$		     set of mail server network protocols which are supported.
$	Messages 6-15 Are used to label the options in the pane.
$ 
$ "-NEW"
$ 
$set 27
1 "Auto"
2 "POP3"
3 "APOP"
4 "IMAP"
5 "POP2"

6 "Automatic (system) delivery"

7 "Mail server retrieval"
8 "Server Protocol:"
9 "Server Name:"
10 "User Name:"
11 "Password:"
12 "Remember password"
13 "Delete from server after retrieval"
14 "Retrieve old messages"

15 "Custom retrieval"
16 "User Getmail command:"

17 "Null INBOX path."
18 "INBOX folder path:"

