$ $XConsortium: dtscreen.msg /main/4 1995/12/08 09:28:04 rswiston $
$ @(#)25	1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 

$quote "

$set 2
$ message file created 1993

1 "1386-101 %s: Errore nell'opzione \"%s\" del comando.\n\n"
2 "1386-102 \nPer una descrizione completa delle opzioni, digitare %s -help.\n\n"

3 "1386-103 Sintassi:\n        %s [-opzioni ...]\n\n dove le opzioni disponibili sono:\n"
5 "1386-105    %-28s %s\n\t dove il modo è uno dei seguenti:\n\", \"-mode modo\", \"modo di animazione"

7 "1386-107 Modo sconosciuto: "
10 "1386-110 Impossibile allocare: %s\n"
11 "1386-111 %d pixel allocati\n"

17 "1386-117 %s: Impossibile accedere allo schermo %s.\n"
18 "1386-118 %s: GetResource - impossibile allocare la memoria"
19 "1386-119 %s: Argomento -display formulato erroneamente, \"%s\"\n"

20 "1386-120 L'argomento -batchcount deve essere positivo."
21 "1386-121 L'argomento -saturation deve essere compreso tra 0.0 e 1.0."

25 "1386-125 %s: Sono supportati solo %d schermi.\n"
30 "1386-130 L'argomento -delay deve essere positivo."
35 "1386-135 Impossibile allocare: %s; verrà usato %s\n"
40 "%s: Impossibile localizzare la finestra di visualizzazione. \nUsando l'opzione -create, %s creerà una propria finestra.\n"

