$ $XConsortium: libAButil.msg /main/1 1995/12/08 09:28:58 rswiston $

$ ========================================================================
$ = Message source text file for App Builder's libAButil utility library.
$ = @(#)libAButil.msg	1.2 13 Sep 1994 dtappbuilder/src/libAButil
$ ========================================================================

$quote "

$ The set number set below must be syncronized with the #define in utilP.h
$set 202
1 "ISTR: Errore di allocazione nell'array int\n"
2 "ISTR: Errore nell'allocazione dello spazio per la stringa\n"
3 "ISTR: Errore nell'allocazione della memoria"
4 "Errore interno"
5 "Chiamate ricorsive della funzione"
6 "Autorizzazione negata"
7 "Apertura non riuscita"
