$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/5 1996/10/19 16:10:42 rws $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$set 1
1 "Si desidera confermare l'esecuzione del comando?"
2 "OK"
3 "Annullare"
4 "Versione di DtMail"
5 "Versione di DtMail"
6 "Selezionare un componente all'interno dell'applicazione.\n"
7 "Aiuto di DtMail"
8 "Aiuto di DtMail"
9 "Chiudere questa cartella?"
10 "Questo comando non potrà essere annullato. Confermare l'esecuzione?"

11 "Mostrare i file e le cartelle nascosti"
$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "Gestione posta : Aiuto"

$set 2
1 "Errore di selezione, impossibile continuare\n"
2 "Selezione abbandonata dall'utente.\n"
