$ $TOG: dtcm.msg /main/12 1999/09/20 10:34:19 mgreess $
$quote "

$set 1

1 "dtcm: leerer Empfänger in Posterinnerung\n"

2 "Erinnerung- %s"

3 "pm"

4 "am"

5 "pm"

6 "am"

7 "\n\n\
\t** Kalendertermin **\n\n\
\tDatum:\t%s\n\
\tStart:\t%s\n\
\tEnde:\t%s\n\
\tKommentar:\t%s"

8 "Von %2d:%02d"

9 "am"

10 "pm"

11 "am"

12 "pm"

13 "Von %02d%02d an %02d%02d"

16 "Standardkalender kann nicht entfernt werden"

17 "Zu entfernenden Namen auswählen"

20 "Ungültiges Datum im Feld \"Gehe zu\""

21 "Liste bearbeiten..."

22 "Einträge des Anzeigemenüs"

23 "Vorh. Woche"

24 "Diese Woche"

25 "Nächste Woche"

26 "Vorh. Monat"

27 "Nächster Monat"

28 "Gehe zu:"

29 "Planen..."

30 "Post..."

31 "Angezeigter Kalender"

32 "Angezeigte Kalender"

33 "Tag"

34 "Woche"

35 "Monat"

36 "Jahr"

37 "Zeitzone..."

38 "Terminliste..."

40 "Ansicht"

41 "Suchen..."

42 "Gehe zu Datum..."

65 "Datei"

68 "Aktuelle Ansicht drucken"

69 "Druckereinrichtung..."

72 "Optionen..."

73 "Beenden"

74 "Termin..."

76 "Bearbeiten"

77 "Hilfe"

79 "Aufgaben..."

80 "Referenzinformation..."

82 "Zu Hilfe..."

84 "Anderen Kalender anzeigen..."

85 "Kalender vergleichen..."

86 "Menü-Editor..."

87 "Anzeigen"

88 "Heute"

89 "in quit_handler\n"

90 "Fehler beim Öffnen der Kalenderdatei"

91 "rpc.cmsd reagiert nicht auf Ihren Benutzernamen.\n\
Sicherstellen, daß der inetd-Prozeß läuft und der\n\
Eintrag in inetd.conf für rpc.cmsd für Ihren Rechner\n\
korrekt ist."

92 "Benutzername"

93 "Rechner"

94 "Fehler bei Kalender"

95 "Weiter"

96 "Kalenderdatei nicht vorhanden für"

97 "Kalenderdatei nicht vorhanden für"

98 "Fehler bei Kalender"

99 "Weiter"

100 "KEIN NAME"

101 "rpc.cmsd reagiert nicht auf"

102 "rpc.cmsd reagiert nicht auf Ihren Benutzernamen.\n\
Sicherstellen, daß der inetd-Prozeß läuft und der\n\
Eintrag in inetd.conf für rpc.cmsd für Ihren Rechner\n\
korrekt ist."

103 "Benutzername"

104 "Rechner"

105 "Fehler bei Kalender"

106 "Weiter"

107 "%s: KEIN NAME"

108 "Es wurde keine Kalenderposition angegeben für"

109 "Es wurde keine Position angegeben; einen Rechnernamen in dem\n\
beim Start angezeigten Kalender in Eigenschaften/Einstellungen anzeigen\n\
hinzufügen. Wurde DTCM mit der Option -c ausgeführt, überprüfen, ob \n\
ein Rechnername angegeben wurde."

110 "Fehler bei Kalender"

111 "Weiter"

112 "Die Versionen von DTCM und rpc.cmsd sind unterschiedlich."

113 "Kalender"

114 "Januar"

115 "Februar"

116 "März"

117 "April"

118 "Mai"

119 "Juni"

120 "Juli"

121 "August"

122 "September"

123 "Oktober"

124 "November"

125 "Dezember"

126 "Jan"

127 "Feb"

128 "Mär"

129 "Apr"

130 "Mai"

131 "Jun"

132 "Jul"

133 "Aug"

134 "Sep"

135 "Okt"

136 "Nov"

137 "Dez"

138 "Son"

139 "Mon"

140 "Die"

141 "Mit"

142 "Don"

143 "Fre"

144 "Sam"

145 "Sun"

146 "Sonntag"

147 "Montag"

148 "Dienstag"

149 "Mittwoch"

150 "Donnerstag"

151 "Freitag"

152 "Samstag"

153 "Sonntag"

154 "S"

155 "M"

156 "D"

157 "M"

158 "D"

159 "F"

160 "S"

161 "S"

162 "S"

163 "M"

164 "D"

165 "M"

166 "O"

167 "F"

168 "Sa"

169 "S"

170 "SON"

171 "MON"

172 "DIE"

173 "MIT"

174 "DON"

175 "FRE"

176 "SAM"

177 "SON"

178 "%s wird bereits angezeigt"

186 "Die Versionen von DTCM und rpc.cmsd sind unterschiedlich"

187 "Verwendung:\n\
\tdtcm_delete [-c Kalender] [-d <mm/tt/jj>] [-v Ansicht]\n"

188 "\n\
Kalender %s konnte nicht geöffnet werden\n"

189 "UNBEKANNT"

190 "Zu löschender Eintrag (Nummer)? "

191 "Verwendung:\n\
\tdtcm_insert [ -c Kalender ] [-d <mm/tt/jj>] [ -v Ansicht ]\n"

192 "                   [-w Kommentar] [-s <HH:MMam/pm>] [-e <HH:MMam/pm>]\n"

193 "Bitte die Informationen für den Termin eingeben, der hinzugefügt werden soll.\n\
Die Standardeinstellungen werden in Klammern angezeigt.\n"

194 "Kalender (%s): "

195 "Datum (%s): "

196 "Start (%s): "

197 "Es würde eine ungültige Uhrzeit eingegeben. Bitte erneut eingeben:\n"

198 "Ende (%s): "

199 "Ende (%s): "

200 "Ein Mal"

201 "Periodisch (%s): "

202 "Ein Mal"

203 "kein Standard"

204 "Für (%s): "

205 "Kommentar (es können bis zu 5 Zeilen eingegeben werden, mit ^D beenden):\n"

206 "\n\
Kalender %s konnte nicht geöffnet werden\n"

207 "Verwendung:\n\
\tdtcm_lookup [ -c Kalender ][ -d <mm/tt/jj> ] [ -v Ansicht ]\n"

208 "\n\
Kalender %s konnte nicht geöffnet werden\n"

209 "UNBEKANNT"

210 "Der Termin wird im derzeit angezeigten Kalender geplant.\n\
Soll der Termin wirklich geplant werden?"

211 "Planen in"

212 "Termin planen"

214 "Termin geplant: %s\n"

218 "Es wurde ein ungültiges DATUM angegeben"

219 "Es wurde eine ungültige START-Zeit angegeben"

220 "Es wurde eine ungültige STOPP-Zeit angegeben"

221 "Leeres oder fehlendes Feld bei DATUM"

222 "Leeres oder fehlendes Feld für STATUS"

223 "Leeres oder fehlendes Feld für KOMMENTAR"

224 "Fehlende Übereinstimmung zwischen den Feldern PERIODISCH und FÜR."

225 "Terminplanung wurde abgebrochen"

226 "Interner Fehler bei Terminplanung"

227 "Terminplanung wurde abgebrochen"

228 "Termin laden"

229 "Weiter"

230 "Termin ziehen"

231 "Termin auswählen und erneut ziehen"

232 "Weiter"

234 "Termin ziehen"

235 "Weiter"

236 "Kalendertermin"

237 "XCreateBitmapFromData() für Bitmap fehlgeschlagen.\n"

238 "XCreateBitmapFromData() für Maske fehlgeschlagen.\n"

239 "DragStart gab NULL zurück.\n"

242 "am"

243 "pm"

244 "%s 3:41am"

245 "am"

246 "pm"

247 "Bei diesem Termin liegt die Endzeit vor der Anfangszeit.\n\
Soll der Termin für den nächsten Tag geplant werden?"

248 "Terminplan"

250 "Nächster Tag"

251 "Verfasser"

252 "Termin löschen"

253 "Einen Termin auswählen und erneut LÖSCHEN."

254 "Weiter"

255 "Termin löschen"

256 "Interner Fehler beim Auswählen eines Termins.\n\
Termin wurde nicht gelöscht."

257 "Weiter"

258 "Termin ändern"

259 "Einen Termin auswählen und erneut ÄNDERN."

260 "Weiter"

261 "Termin ändern"

262 "Interner Fehler beim Auswählen eines Termins.\n\
Termin wurde nicht geändert."

263 "Weiter"

267 "Termin ändern"

268 "Dieser Termin ist Teil einer Wiederholungsserie.\n\
Soll ... geändert werden?"

270 "Nur dieser"

271 "Weiterleiten"

272 "Alle"

273 "Termin löschen"

274 "Dieser Termin ist Teil einer Wiederholungsserie.\n\
Soll ... gelöscht werden?"

276 "Nur dieser"

277 "Weiterleiten"

278 "Alle"

279 "Kalender-Termin-Editor"

280 "Terminliste anzeigen"

281 "Es sind keine aufzulistenden Termine vorhanden!"

282 "Weiter"

283 "Kalender - Suchfunktion"

284 "Suchen:"

285 "Suchen"

289 "Hilfe"

290 "Terminzeichenfolge für Übereinstimmung angeben."

291 "Termin nicht gefunden."

292 "%d Übereinstimmungen gefunden"

293 "Datum:"

294 "Gehe zu"

296 "Hilfe"

297 "Bitte ein Datum eingeben"

298 "%s wird bereits angezeigt"

299 "Ungültiges Datum"

300 "Verfasser"

304 "Post..."

305 "Gruppentermin einfügen"

306 "Einen Kalender auswählen und erneut EINFÜGEN."

307 "Weiter"

308 "Termin löschen"

309 "Einen Termin auswählen und erneut LÖSCHEN."

310 "Weiter"

311 "Termin löschen"

312 "Interner Fehler beim Auswählen eines Termins.\n\
Termin wurde nicht gelöscht."

313 "Weiter"

314 "Gruppentermin löschen"

315 "Einen Kalender auswählen und erneut LÖSCHEN."

316 "Weiter"

317 "Termin löschen"

318 "Dieser Termin ist Teil einer Wiederholungsserie. \n\
Soll ... gelöscht werden?"

320 "Nur dieser"

321 "Weiterleiten"

322 "Alle"

323 "Termin ändern"

324 "Einen Termin auswählen und erneut ÄNDERN."

325 "Weiter"

326 "Termin ändern"

327 "Interner Fehler beim Auswählen eines Termins.\n\
Termin wurde nicht geändert."

328 "Weiter"

329 "Gruppentermin ändern"

330 "Einen Kalender auswählen und erneut ÄNDERN."

331 "Weiter"

332 "Termin ändern"

333 "Dieser Termin ist Teil einer Wiederholungsserie. \n\
Soll ... geändert werden?"

335 "Nur dieser"

336 "Weiterleiten"

337 "Alle"

340 "Kalender"

341 "Zugriff"

342 "Einfügen"

343 "Ändern"

348 "Einfügeberechtigung"

349 "Editor für Kalendergruppentermine"

350 "Fehler bei Auswahl, Fortfahren nicht möglich\n"

351 "Auswahl durch Benutzer abgebrochen.\n"

352 "Es muß eine Komponente innerhalb der Anwendung ausgewählt werden."

353 "Keine Zeit"

354 "Jederzeit"

355 "Katalogdatei kann nicht geöffnet werden.\n\
Operation abgebrochen. Kalender"

356 "Operation durch Benutzeranforderung abgebrochen.\n\
Kalender"

357 "Ungültiges Datum im Feld für DATUM.\n\
Operation abgebrochen. Kalender"

358 "Ungültiger Wert im Feld für START.\n\
Operation abgebrochen. Kalender"

359 "Ungültiger Wert im Feld für STOPP.\n\
Operation abgebrochen. Kalender"

360 "Es muß ein Wert für DATUM angegeben werden.\n\
Operation abgebrochen. Kalender"

361 "Es muß ein Wert für START angegeben werden.\n\
Operation abgebrochen. Kalender"

362 "Es muß ein Wert für KOMMENTAR angegeben werden.\n\
Operation abgebrochen. Kalender"

363 "Werte für PERIODISCH und FÜR ungültig oder fehlende Übereinstimmung.\n\
Operation abgebrochen. Kalender"

364 "Editoroperation fehlgeschlagen"

365 "Weiter"

367 "Kalender bereits vorhanden.\n\
Operation abgebrochen. Kalender"

368 "Kalender nicht vorhanden.\n\
Operation abgebrochen. Kalender"

370 "Berechtigungsfehler. Berechtigung verweigert.\n\
Operation abgebrochen. Kalender"

378 "Speicherzuordnungsfehler - nicht genügend Speicher vorhanden.\n\
Operation abgebrochen. Kalender"

383 "Unbekannter Fehler.\n\
Operation abgebrochen. Kalender"

386 "Dieser Termin weist einen Endzeitpunkt auf, der vor dem Anfangszeitpunkt liegt.\n\
Soll der Termin für den nächsten Tag geplant werden?"

387 "Termin planen"

389 "Nächster Tag"

390 "Vertraulichkeit:"

391 "Position des Benutzerkalenders:"

392 "Tagesgrenzen:"

393 "Beginn:"

394 "Ende:"

395 "Stundenanzeige:"

396 "12 Stunden"

397 "24 Stunden"

398 "Standardansicht:"

399 "Jahr"

400 "Monat"

401 "Woche"

402 "Tag"

403 "Beim Start angezeigter Kalender:"

404 "Benutzerzugriff"

405 "Mindestens eine Berechtigung auswählen."

406 "Weiter"

407 "Einstellungen für Kalendergruppenzugriff -- Entfernen"

408 "Bitte zunächst einen Namen auswählen."

409 "Weiter"

410 "Benutzername:"

411 "Einen Namen hinzufügen"

412 "Berechtigungen"

413 "Berechtigungen"

414 "Namen entfernen"

415 "A = Anzeigen E = Einfügen L = Löschen"

416 "Berechtigungen:"

417 "Anzeigen"

418 "Einfügen"

419 "Löschen"

420 "Ziel:"

421 "Drucker"

422 "Datei"

423 "Drucker:"

424 "Verzeichnis:"

425 "Optionen:"

426 "Datei:"

427 "Breite:"

428 "Höhe:"

429 "Position:"

430 "Zoll von links"

431 "Zoll von unten"

432 "Einheiten:"

433 "Exemplare:"

434 "Einschließlich:"

435 "Termine mit 'Zeit und Text anzeigen'"

436 "Termine mit 'Nur Zeit anzeigen'"

437 "Termine mit 'Nichts anzeigen'"

438 "Anordnung:"

439 "MM | TT | JJ"

440 "TT | MM | JJ"

441 "JJ | MM | TT"

442 "Trennzeichen:"

443 "Leerzeichen"

444 "Kalenderoptionen speichern"

445 "Fehler beim Schreiben in ~/.desksetdefaults.\n\
Sicherstellen, daß Schreibberechtigung für diese Datei vorliegt."

446 "Weiter"

447 "Kalenderoptionen lesen"

448 "Fehler beim Lesen aus ~/.desksetdefaults.\n\
Sicherstellen, daß Leseberechtigung für diese Datei vorliegt."

449 "Weiter"

450 "Hilfe für Kalenderoptionen"

451 "Es wurden Änderungen vorgenommen, die nicht gespeichert wurden ..."

452 "Speichern"

453 "Trotzdem verlassen"

454 "Kalenderoptionen speichern"

456 "Weiter"

458 "Kalender -  Optionen"

459 "Kategorie:"

460 "Anwenden"

463 "Hilfe"

464 "ps_open_file(): Es muß ein Verzeichnis oder eine Datei angegeben werden\n"

465 "ps_open_file(): Ungültiges Verzeichnis %s\n"

466 "w+"

467 "ps_open_file(): Datei %s kann nicht geöffnet werden\n"

468 "Seite"

469 "Tagesübersicht des Kalender-Managers"

470 "Morgens"

471 "Nachmittags"

472 "pm"

473 "Aufgabenliste des Kalender-Managers"

474 "Terminliste des Kalender-Managers"

475 "Seite"

476 "von"

477 "Monatsübersicht des Kalender-Managers"

478 "von"

479 "Seite"

480 "Son"

481 "Mon"

482 "Die"

483 "Mit"

484 "Don"

485 "Fre"

486 "Sam"

487 "ps_init_printer(): Postscript-Prolog-Datei kann nicht geöffnet werden: %s\n"

488 "von"

489 "   Seite"

490 "Wochenübersicht des Kalender-Managers"

491 "M"

492 "D"

493 "M"

494 "T"

495 "F"

496 "S"

497 "S"

505 "Sam"

506 "Son"

507 "Jahresübersicht des Kalender-Managers"

508 "Jahresübersicht des Kalender-Managers"

523 "Aufgabenliste: Jahr %d"

524 "Terminliste: Jahr %d"

525 "Aufgabenliste: %s"

526 "Terminliste: %s"

527 "Aufgabenliste: Woche %s"

528 "Terminliste: Woche %s"

529 "Aufgabenliste: %s"

530 "Terminliste: %s"

531 "Alle %d %s"

532 "DTCM: Periodisch alle"

533 "Periodisch alle:"

534 "Periodisch:"

535 "Für:"

536 "Vertraulichkeit:"

537 "Terminplan"

538 "Soll dieser Termin in der letzten Woche des Monats oder in\n\
der 4. Woche des Monats geplant werden?"

540 "Letzte Woche"

541 "4. Woche"

542 "Alle %d %s"

543 "Alle %d %s"

544 "Alle %d %s"

559 "Durchsuchen von %s..."

560 "Kalender - Anderen Kalender anzeigen"

561 "Benutzername:"

562 "Anzeigen"

564 "Hilfe"

565 "Verfasser"

566 "Aufabe löschen"

567 "Aufgabe auswählen und erneut LÖSCHEN."

568 "Weiter"

569 "Aufgabe löschen"

570 "Interner Fehler beim Auswählen einer Aufgabe.\n\
Aufgabe wurde nicht gelöscht."

571 "Weiter"

572 "Aufgabe löschen"

573 "Diese Aufgabe ist Teil einer Wiederholungsserie.\n\
Soll ... gelöscht werden? "

575 "Nur dieses"

576 "Weiterleiten"

577 "Alle"

578 "Aufgabe ändern"

579 "Diese Aufgabe ist Teil einer Wiederholungsserie.\n\
Soll ... geändert werden? "

581 "Nur diese"

582 "Weiterleiten"

583 "Alle"

584 "Aufgabe ändern"

585 "Aufgaben auswählen und erneut ÄNDERN."

586 "Weiter"

587 "Aufgabe ändern"

588 "Interner Fehler beim Auswählen einer Aufgabe.\n\
Aufgabe wurde nicht geändert."

589 "Weiter"

590 "Fälligkeitsdatum:"

591 "Kalender-Aufgaben-Editor"

595 "Wochenbeginn %s"

596 "Montag %d"

597 "Dienstag %d"

598 "Mittwoch %d"

599 "Donnerstag %d"

600 "Freitag %d"

601 "Samstag %d"

602 "Sonntag %d"

603 "Ein hinzuzufügenden Namen im Feld 'Benutzername' eingeben"

604 "ist bereits in der Liste enthalten"

605 "Hilfe"

606 "Fehler bei Kalender"

607 "Interner Fehler beim Registrieren des Kalendernamens."

608 "Weiter"

609 "Fehler bei Kalender"

610 "Interner Fehler beim Abrufen des Kalendernamens."

611 "Weiter"

612 "Überblick..."

613 "Informationen zu Kalender..."

617 "Heute"

618 "Das Argument -session erfordert einen Parameter\n"

619 "Bitte einen Kalendernamen im folgenden Format eingeben: <Benutzer>@<Rechnername>"

620 "Unbekannter Kalender. Kalendername erforderlich: <Name>%s"

621 "Bitte einen Kalendernamen im folgenden Format eingeben: <Benutzer>@<Rechnername>"

622 "Unbekannter Kalender. Rechnername erforderlich: %s@<Rechnername>"

623 "Der Kalender zeigt keine Einträge vor dem 1. Januar 1970 an"

624 "Der Kalender zeigt keine Einträge nach dem 31.Dezember 2037 an"

625 "Weniger"

626 "Mehr"

627 "Termin"

628 "Zeit  Kommentar"

629 "Mehr"

631 "%d Übereinstimmung gefunden"

632 "Bitte einen Termin aus der Liste auswählen"

633 "Ausgewählter Kalender"

634 "Ausgewählte Kalender"

635 "Weniger"

636 "Mehr"

637 "Mehr"

641 "Server erhielt keinen Netzzugriff für den angegebenen\n\
Standort: ungültiger Rechnername."

642 "Dämon rpc.cmsd nicht registriert.\n\
Bitte überprüfen, ob rpc.cmsd korrekt auf dem System installiert ist."

643 "Kein Zugriff auf den Kalender. Kalender"

644 "Terminzeiten:"

645 "Dauer:"

646 "Minuten"

647 "Suche nach %s..."

648 "SunDex"

649 "Kalender - Zeitzone"

650 "Meine Zeit"

652 "Spezifische Zeit"

653 "WEZ"

654 "Stunden"

655 "OK"

656 "Anwenden"

658 "Hilfe"

659 "Zeitzone:"

660 "Zeitzone:"

662 "Zeitzone:"

663 "Weniger"

664 "Mehr"

666 "Mehr"

667 "Kalender zeigt keine Daten vor dem 1. Januar 1970 an"

668 "Kalender zeigt keine Daten nach dem 31. Dezember 2037 an"

670 "Dtcm"

671 "Version"

672 "Überarbeitung"

674 "Copyright (c) 1993, 1994:"

675 "Hewlett-Packard Company"

676 "International Business Machines Corp."

677 "Novell, Inc."

678 "Sun Microsystems, Inc."

679 "Weitere..."

680 "Schließen"

681 "Mitwirkende"

682 "Diese Anwendung wurde erstellt durch:"

683 "Schließen"

684 "Benutzernamen dürfen keine Leerzeichen oder Tabulatoren enthalten"

685 "Benutzername:"

686 "Name hinzufügen"

687 "Name entfernen"

688 "Menüpunkte anzeigen"

689 "OK"

690 "Anwenden"

691 "Zurücksetzen"

693 "Hilfe"

696 "Verwendung:\n\
\tdtcm_admin [ -d ] [ -a Aktion ] [ -c Kalender ][ -s <mm/tt/jj> ] [ -e <mm/tt/jj> ] [-f Dateiname]\n"

697 "Es wurde eine nicht unterstützte Verwaltungsoperation \"%s\" angegeben.\n"

698 "\n\
Ausgabedatei \"%s\" konnte nicht geöffnet werden\n"

699 "\n\
Eingabedatei \"%s\" konnte nicht geöffnet werden\n"

700 "Entfernen"

702 "Hilfe"

703 "Kontext"

704 "Jahr %d"

705 "%s"

706 "Woche %s"

707 "%s"

708 "Dieser Termin wiederholt sich auf unbekannte Weise. Alle Auftreten werden geändert.\n\
Soll Änderung durchgeführt werden?"

710 "Weiter"

711 "Dieser Termin wiederholt sich auf unbekannte Weise. Alle Auftreten werden gelöscht.\n\
Soll Löschen durchgeführt werden?"

712 "Weiter"

713 "Es muß ein Anfangsdatum vor dem Enddatum gewählt werden."

714 "Die Liste enthält keine Termine."

715 "Kalender - Zu Datum"

716 "Dieser Termin wiederholt sich auf unbekannte Weise. Alle Auftreten werden gelöscht.\n\
Soll Löschen durchgeführt werden?"

717 "Weiter"

718 "Dieser Termin wiederholt sich auf unbekannte Weise. Alle Auftreten werden geändert.\n\
Soll Änderung durchgeführt werden?"

720 "Weiter"

721 "Alles öffentlich"

722 "Andere sehen nur Zeit"

723 "Alles privat"

724 "Bei Terminen ohne Zeitangabe muß ein Kommentar angegeben werden.\n\
Operation abgebrochen. Kalender"

725 "Kalendereintrag nicht vorhanden.\n\
Operation abgebrochen. Kalender"

727 "Zeitlimitüberschreitung bei Anforderung aufgetreten\n\
Bitte überprüfen, ob verify rpc.cmsd ordnungsgemäß auf dem System installiert ist."

728 "Kalender - Drucken"

729 "Druckername:"

730 "Exemplare:"

731 "Von:"

732 "An:"

733 "Druckbefehlsoptionen:"

734 "Drucken in Datei:"

735 "Drucken"

736 "Kalender : Fehler - Druck"

737 "Hilfe"

738 "Zugriffsliste:"

739 "Zugriffsrechte:"

740 "Hinzufügen"

741 "Löschen"

742 "Ändern"

743 "Öffentlich:"

744 "Halb privat:"

745 "Privat:"

746 "Ansicht"

747 "Einfügen"

748 "Ändern"

749 "Name und Zugriffsberechtigungen muß auf einen Eintrag in der Zugriffsliste gesetzt sein"

750 "Einstellungen für Kalenderzugriffsgruppe -- Hinzufügen"

751 "Dieser Eintrag existiert bereits in der Zugriffsliste. Soll er geändert werden?"

752 "Einstellungen für Kalenderzugriffsgruppe -- Hinzufügen"

753 "Ändern"

755 "Einstellungen für Kalenderzugriffsgruppe -- Ändern"

756 "Name und Zugriffsberechtigungen müssen festgelegt sein, um einen Eintrag in der Zugriffsliste zu ändern"

757 "Einstellungen für Kalenderzugriffsgruppe -- Ändern"

758 "Mitternacht"

759 "Wert"

760 "Wert"

761 "Entfernen"

762 "Standardeinstellungen für Editor"

763 "Standardeinstellungen für Anzeige"

764 "Zugriffsliste und Berechtigungen"

765 "Druckereinstellungen"

766 "Datumsformat"

767 "OK"

768 "Zurücksetzen"

772 "Es kann keine leere Benutzerkalenderposition gesichert\n\
werden oder eine Position, die Leerzeichen enthält.\n\
Die Einstellungen für die Eigenschaften wurden nicht gesichert."

773 "Es kann keine leere Anfangskalenderansicht gesichert\n\
werden oder eine Ansicht, die Leerzeichen enthält.\n\
Die Einstellungen für die Eigenschaften wurden nicht gesichert."

774 "ps_open_file(): Beim Drucken in Datei muß ein Dateiname angegeben werden.\n"

775 "Es muß ein Erinnerungsvorlauf angegeben werden.\n\
Operation wurde abgebrochen. Kalender"

776 "Ein Erinnerungsvorlauf darf kein Leerzeichen enthalten.\n\
Operation wurde abgebrochen. Kalender"

777 "Als Vorlaufwerte können Zahlen (evtl. mit Vorzeichen) angegeben werden.\n\
Operation wurde abgebrochen. Kalender"

778 "Hilfe für Kalender-Aufgabenliste"

779 "Es wurden Änderungen vorgenommen, die noch\n\
nicht gesichert wurden. Es besteht die Möglichkeit,\n\
die Änderungen zu sichern, sie zu verwerfen oder\n\
oder zur vorherigen Stelle im Dialog zurückzukehren."

780 "Verwerfen"

781 "Ansicht"

782 "Alle"

783 "Anstehend"

784 "Abgeschlossen"

785 "OK"

786 "Anwenden"

788 "Hilfe"

789 "Art der Aufgabe:"

790 "Kontext"

791 "Diese Aufgabe wiederholt sich auf unbekannte Weise. Alle Auftreten werden geändert.\n\
Soll Änderung durchgeführt werden?"

793 "Weiter"

794 "Dieser Termin wiederholt sich auf unbekannte Weise. Alle Auftreten werden geändert.\n\
Soll Änderung durchgeführt werden?"

796 "Weiter"

797 "Aufgabe"

798 "Fälligkeitszeit:"

799 "Abgeschlossen"

800 "Einfügen"

801 "Ändern"

802 "Löschen"

803 "Inhalt löschen"

805 "Hilfe"

806 "Jahr %d"

807 "%s"

808 "Woche %s"

809 "%s"

810 "Bitte Anfangsdatum nach dem 1.1.1970 angeben"

811 "Falsches Anfangsdatum"

812 "Bitte Enddatum vor dem 1.1.2038 angeben"

813 "Falsches Enddatum"

814 "Es muß ein Datum zwischen 1969 und 2038 eingegeben werden"

815 "Es muß ein Datum zwischen 1969 und 2038 eingegeben werden"

816 "Tage"

817 "Wochen"

818 "Monate"

819 "Der Wert für die Dauer muß eine ganze Zahl ohne Vorzeichen sein.\n\
Die Einstellungen für die Eigenschaften wurden nicht gesichert."

820 "Die Startzeit muß eine gültige Zeit sein.\n\
Die Einstellungen für die Eigenschaften wurden nicht gesichert."

$ 821 "Es wurde ein ungültiger Wert für die Druckweite angegeben.\n\
$ Die Einstellungen für die Eigenschaften wurden nicht gesichert."
$ "print width" has been replaced by "right margin".
821	"Sie haben einen ungültigen Wert für den rechten Rand angegeben.\nDie Einstellungen für die Eigenschaften wurden nicht gesichert."

$ 822 "Es wurde ein ungültiger Wert für die Druckhöhe angegeben.\n\
$ Die Einstellungen für die Eigenschaften wurden nicht gesichert."
$ "print height" has been replaced by "bottom margin".
822	"Es wurde ein ungültiger Wert für den unteren Rand angegeben.\nDie Einstellungen für die Eigenschaften wurden nicht gesichert."

825 "Tage"

826 "Wochen"

827 "Monate"

828 "Datum:"

829 "Start:"

830 "AM"

831 "PM"

832 "Ende:"

833 "AM"

834 "PM"

835 "Kommentar:"

836 "Häufigkeit"

837 "Aufgabe einfügen/ändern"

839 "Kalender: Erinnerung"

840 "Schließen"

841 "Auf \"Name hinzufügen\", um einen Namen hinzufügen,\n\
auf \"Anwenden\" klicken, um die Änderungen festzuschreiben."

842 "Die übertragenen Informationen enthielten keine\n\
Termine."

843 "Ziehen und Übergeben gescheitert."

844 "Übertragene Information ist nicht auffindbar."

845 "Ziehen und Übergeben ist gescheitert.\n\
Interner Konsistenzfehler."

846 "Sichern"

847 "Zurücksetzen"

848 "Datum"

849 "Zeit"

850 "Kommentar"

851 "Termin anzeigen"

852 "Ein Mal"

853 "Täglich"

854 "Wöchentlich"

855 "Alle zwei Wochen"

856 "Monatlich nach Datum"

857 "Montatlich nach Wochentag"

858 "Jährlich"

859 "Montag bis Freitag"

860 "Mon, Mit, Fre"

861 "Dienstag, Donnerstag"

862 "Periodisch alle ..."

863 "2"

864 "3"

865 "4"

866 "5"

867 "6"

868 "7"

869 "8"

870 "9"

871 "10"

872 "11"

873 "12"

874 "13"

875 "14"

876 "immer"

877 "Min"

878 "Std"

879 "Tage"

880 "Hilfe"

881 "Interner Fehler 1: Kalender/Eintrag ungültig.\n\
Operation wurde abgebrochen. Kalender"

882 "Interner Fehler 2: Session ungültig.\n\
Operation wurde abgebrochen. Kalender"

883 "Interner Fehler 3: Datenwert ungültig.\n\
Operation wurde abgebrochen. Kalender"

884 "Interner Fehler 4: Wert für Nur-Lese-Attribut angegeben.\n\
Operation wurde abgebrochen. Kalender"

885 "Interner Fehler 5: Ungültiger Datentyp für Attributwert angegeben.\n\
Operation wurde abgebrochen. Kalender"

886 "Interner Fehler 6: Angegebene Funktion wird bei dieser Kalenderversion\n\
nicht unterstützt. Operation wurde abgebrochen. Kalender"

887 "Interner Fehler 7: Angegebene Funktion wird bei dieser Kalenderversion\n\
nicht unterstützt. Operation wurde abgebrochen. Kalender"

888 "Interner Fehler 8: Ungültiger Operator angegeben.\n\
Operation wurde abgebrochen. Kalender"

890 "Fehler bei Kalender-Services"

891 "Drucken"

892 "Die Datumsangaben für das Drucken müssen zwischen 1969 und 2038 liegen."

893 "Drucken"

894 "Fehler bei Datumsangabe \"Von\""

895 "Drucken"

896 "Fehler bei Datumsangabe \"Bis\""

897 "Drucken"

898 "Für \"Bis\" muß ein späterer Zeitpunkt als für \"Von\" angegeben werden"

899 "Anfang der Aufgabenliste: %s"

900 "Anfang der Terminliste: %s"

901 "Periodisch alle ..."

902 "Montag bis Freitag"

903 "Mon, Mit, Fre"

904 "Dienstag, Donnerstag"

905 "Periodisch alle ..."

906 "Aufgabe ziehen"

907 "Kein Platz für Kalenderdatei vorhanden.\n\
Operation wurde abgebrochen. Kalender"

908 "Es kann kein leerer Erinnerungswert festgelegt werden.\n\
Die Einstellungen für die Eigenschaften wurden nicht gespeichert."

909 "Es kann kein Erinnerungswert mit einem Leerzeichen festgelegt werden.\n\
Die Einstellungen für die Eigenschaften wurden nicht gespeichert."

910 "Für Erinnerungswerte muß eine Zahl (evtl. mit Vorzeichen) angegeben werden.\n\
Die Einstellungen für die Eigenschaften wurden nicht gespeichert."

$ 911 "Es wurde eine ungültige Position für die relative Position von links angegeben.\n\
$ Die Einstellungen für die Eigenschaften wurden nicht gespeichert."
$ "position from left offset" has been changed to "left margin".
911	"Es wurde ein ungültiger Wert für den linken Rand angegeben.\nDie Einstellungen für die Eigenschaften wurden nicht gespeichert."

$ 912 "Es wurde eine ungültige Position für die relative Position von rechts angegeben.\n\
$ Die Einstellungen für die Eigenschaften wurden nicht gespeichert."
$ "position from right offset" has been changed to "top margin".
912	"Es wurde ein ungültiger Wert für den oberen Rand angegeben.\ Die Einstellungen für die Eigenschaften wurden nicht gespeichert."

913 "Bei einem Aufgabenpunkt muß in der ersten Kommentarzeile Text eingegeben werden."

914 "Operation des Kalender-Editors gescheitert"

915 "Operation des Kalender-Editors gescheitert"

916 "Die Dauer muß weniger als 24 Stunden betragen.\n\
Die Einstellungen für die Eigenschaften wurden nicht gespeichert."

917 "Fehlende\n\
Grafiken"

918 "Fehlende\n\
Grafiken"

919 "Kalender"

920 "angezeigt."

921 "Kein Zugriff auf Kalender: "

922 "Informationen zu Kalender"

923 "Abbrechen"

924 "Abbrechen"

925 "Abbrechen"

926 "Schließen"

927 "Abbrechen"

928 "Abbrechen"

929 "Abbrechen"

930 "Einfügen"

931 "Ändern"

932 "Löschen"

933 "Inhalt löschen"

934 "Abbrechen"

935 "Hilfe"

936 "Abbrechen"

937 "Abbrechen"

938 "Abbrechen"

939 "Abbrechen"

940 "Schließen"

941 "Schließen"

942 "Abbrechen"

943 "Abbrechen"

944 "Abbrechen"

945 "Abbrechen"

946 "Abbrechen"

947 "Abbrechen"

948 "Schließen"

949 "Abbrechen"

950 "Abbrechen"

951 "Abbrechen"

952 "Schließen"

953 "Abbrechen"

954 "Schließen"

955 "Abbrechen"

956 "Abbrechen"

957 "Abbrechen"

958 "Abbrechen"

959 "Abbrechen"

960 "Abbrechen"

961 "Abbrechen"

962 "Abbrechen"

963 "Kalender - Menü-Editor"

964 "Kontexthilfe"

965 "Aufgabenliste..."

966 "Aufgaben..."

967 "Kalender Server-Version"

968 "Kalender Daten-Version"

969 "Periodisch alle"

970 "Der Wert für 'Periodisch alle' muß eine Ganzzahl ohne Vorzeichen sein."

971 "Zeitkalender"

972 "Was"

973 "Alle suchen"
974 "Suchen von"
975 "bis"
976 "Reporttyp:"
977 "Tagesübersicht"
978 "Wochenübersicht"
979 "Monatsübersicht"
980 "Jahresübersicht"
981 "Terminliste"
982 "Aufgabenliste"
983 "Benutzername"
984 "Dieser Termin ist Teil einer Wiederholungsserie.\nMöchten Sie den Termin einfügen ...?"
985 "Nicht vergessen"
986 "Tonsignal"
987 "Optisches Signal"
988 "Popup"
989 "Erinnerungsschreiben"
990 "Erinnerungsschreiben an:"
992 "%A, %e. %B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar day view.  In the C locale
$ 	   it has the form:
$ 
$ 		Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
993 "Woche vom %A, %e. %B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar week view.  In the C locale
$ 	   it has the form: 
$ 
$ 			Monday, January 16, 1995
$ 
$ 	   strftime conversion string: "%A, %B %e, %Y" is used.  The string
$ 	   will be used in a label that looks like this:
$ 
$ 			Week Starting Monday, January 16, 1995
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
994 "Tage"
995 "Wochen"
996 "zwei Wochen"
997 "Monate"
998 "Jahre"
1002 "Ebenfalls beigetragen haben:"
1003 "Dieser Termin befindet sich in einem Kalender, der einen anderen Eigentümer hat.\nMöchten Sie ihn trotzdem ändern ?"
1004 " Dieser Termin befindet sich in einem Kalender, der einen anderen Eigentümer hat.\nMöchten Sie ihn trotzdem löschen ?"
1005 "Löschen aus"
1006 "Ändern in"
1007 "Interner Fehler bei der Terminauswahl.\nTermin wurde nicht geändert."
1008 "Kalendertermin: Hilfe"
1009 "Interner Fehler bei der Aufgabenauswahl.\nAufgabe wurde nicht geändert."
1010 "Kalender: Kalender vergleichen"
1011 "Ungültiger Wert im Feld \"Fälligkeitszeit\".\nOperation wurde abgebrochen. Kalender"

1012 "Kalender - Aufgabenliste"


1042 "Einfügezugriff verweigert: "
1043 "Löschzugriff verweigert: "
1044 "Lesezugriff verweigert: "
1045 "Abgebrochen wegen"
1046 "Termin abgebrochen\n"
1047 "Dieser Termin: '%s' endet\n"
$ 	/* NL_COMMENT
$ 	   
$ 	   The following four messages (1047-1050) will be printed to stdout 
$ 	   and can have the following two forms:
$ 
$ 		"This appointment: '<appt text>' has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   or 
$ 
$ 		"This appointment has an end
$ 		 time earlier than its begin time.  Do you
$ 		 want to schedule it into the next day? [Y/N]  "
$ 
$ 	   The text <appt text> and [Y/N] should not be translated.
$ 
$ 	*/
1048 "Dieser Termin endet\n"
1049 "früher, als er beginnt. Soll er\n"
1050 "in den nächsten Tag hinein dauern? [Y/N]  "
1051 "Dieser Termin '%s' ist Teil einer Wiederholungsserie.  "
$ 		/* NL_COMMENT
$ 
$ 		   Message numbers 1051-1057 are printed to stdout and
$ 		   should appear like:
$ 
$ 		   "The appointment '<appt text>' is part of a repeating series. Do you want to:
$ 			1.  Delete all of them
$ 			2.  Delete this on only
$ 			3.  Delete forward
$ 			4.  Cancel
$ 			Option [1-4]: "
$ 
$ 		*/
1052 "Möchten Sie:"
1053 "\n\t1.  Alle löschen?"
1054 "\n\t2.  Nur diesen löschen?"
1055 "\n\t3.  Vorwärts löschen"
1056 "\n\t4.  Abbrechen?"
1057 "\n\tOption [1-4]: "
1058 "Ungültiges Datum angegeben.\n"
1059 "Es wurde eine ungültige START-Zeit angegeben.\n"
1060 "Es wurde eine ungültige STOPP-Zeit angegeben.\n"
1061 "Leeres oder fehlendes Feld bei DATUM.\n"
1062 "Leeres oder fehlendes Feld für START.\n"
1063 "Leeres oder fehlendes Feld für KOMMENTAR.\n"
1064 "Fehlende Übereinstimmung zwischen den Feldern PERIODISCH und FÜR.\n"
1065 "Termineinfügung wurde abgebrochen\n"
1066 "Termin wurde nicht eingefügt."
1067 "Ungültiges Datum angegeben:"
1068 "Termine für"
1069 "Keine Termine für"
1070 "Kalender : Fehler - Kalender vergleichen"
1072 "Kalender : Fehler - durchsuchen"
1073 "Kalender : Fehler - ziehen und übergeben"
1074 "Kalendertermin"
1075 "Kalender : Fehler - Termin ändern"
1076 "Kalender : Hilfe"
1078 "Kalender : Zugriffsliste und Zugriffsrechte - hinzufügen"
1079 "Kalender : Fehler - Editoreinstellungen"
1083 "Kalender : Fehler - Einstellungen anzeigen"
1085 "Kalender : Fehler - Druckereinstellungen"

1086 "Kalender - Terminliste"

1087 "Von %1$2d:%2$02d bis %4$2d:%5$02d "
$ 				/* NL_COMMENT
$ 
$ 				   Message 1087 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  In the C locale it would
$ 				   look something like this:
$ 
$ 				   ``From 11:00am to 1:00pm''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 					$4	-> stop hour
$ 					$5	-> stop minute
$ 					$6	-> am or pm
$ 
$ 				*/
1088 "%1$2d:%2$02d "
$ 				/* NL_COMMENT
$ 
$ 				   Message 1088 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  It is used when an appt
$ 				   does not have and ``end'' time.  In the 
$ 				   C locale it would look something like this:
$ 
$ 				   ``11:00am''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> am or pm
$ 
$ 				*/
1089 "Von %1$02d:%2$02d bis %3$02d:%4$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1089 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   a user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``From 0100 to 1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 					$3	-> stop hour
$ 					$4	-> stop minute
$ 
$ 				*/
1090 "%1$02d:%2$02d"
$ 				/* NL_COMMENT
$ 
$ 				   Message 1090 : This message is used to form
$ 				   the alarm string that appears in the
$ 				   reminder popup.  This string is used when
$ 				   an appt does not have an end time and the
$ 				   user has asked that times be displayed
$ 				   in 24 hour format.  In the C locale it 
$ 				   would look something like this:
$ 
$ 				   ``1600''
$ 
$ 				   In the printf conversion string the $n are:
$ 
$ 					$1 	-> start hour
$ 					$2	-> start minute
$ 
$ 				*/
1091 "%B %Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar month view.  In the C locale
$ 	   it has the form:
$ 
$ 		July, 1995
$ 
$ 	   strftime conversion string: "%B, %Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
1092 "%Y"
$ 	/* NL_COMMENT
$ 	   Attention Translator:
$ 
$ 	   This string is used in the calendar year view.  In the C locale
$ 	   it has the form:
$ 
$ 		1995
$ 
$ 	   strftime conversion string: "%Y" is used.
$ 
$ 	   Use the appropriate strftime conversion for your locale.
$ 	*/
$ 	/* NL_COMMENT
$ 	The following message were added because message numbers from
$    	IBM and Sunsoft conflicted - they both used the same message number
$    	for different messages.  The IBM message number was changed as
$    	follows:
$ 
$		1100 was 978 from IBM
$		1101 was 979 from IBM. 
$		1102 was 981 from IBM. 
$		1103 was 982 from IBM. 
$		1104 was 985 from IBM. 
$		1105 was 986 from IBM. 
$ 	*/

1100 "\n\n\
\t** Kalenderaufgabe **\n\n\
\tFälligkeitsdatum:\t%s\n\
\tFälligkeitszeit:\t%s\n\
\tKommentar:\t\t%s"

1101 "Termin einfügen"

1102 "Aufgabe einfügen"

1103 "Diese Aufgabe ist Teil einer Wiederholungsserie.\n\
Soll der Eintrag ... eingefügt werden?"

1104 "Ungültiger Wert im Feld für FÄLLIGKEITSZEIT.\n\
Operation abgebrochen.  Kalender"

1105 "Es muß ein Wert für FÄLLIGKEITSZEIT angegeben werden.\n\
Operation abgebrochen.  Kalender"

$ Message numbers 1106-1110 represent choices for the content of
$ left and right headers and footers on the printed page.  These
$ items are displayed in option menus in the "Printer Settings..."
$ category of the "Options..." dialog.
1106	"Datum"
1107	"Benutzerkennung"
1108	"Seitenzahl"
1109	"Reporttyp"
1110	"Keine"
$ Message 1111 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Setup..." from the
$ "Print..." dialog box.  Message 1112 is the text displayed in
$ that error dialog.
1111	"Kalender : Fehler - Druckereinstellungen"
1112	"Druckdialogmanager (PDM)-Fehler - Einstellungen fehlgeschlagen."
$ Message 1113 is the error message displayed if the user selects
$ "Print" from the "Print..." dialog box while an invalid printer
$ name is specified.
1113	"Ungültiger Drucker oder Druck-Server angegeben."
$ Message 1114 is placed in the title bar of an error dialog if an
$ error is encountered when the user invokes "Print" from the
$ "Print..." dialog box with the "Print to File" toggle selected.
$ Message 1115 is the text displayed in that error dialog.
1114	"Kalender : Fehler - Drucken in Datei"
1115	"Fehler - kann nicht in Datei drucken."
$ Message 1116 is placed in the title bar of an information dialog
$ if the operation completes successfully when the user invokes "Print"
$ from the "Print..." dialog box with the "Print to File" toggle
$ selected.  Message 1117 is the text displayed in that information dialog.
1116	"Kalender : Drucken in Datei"
1117	"Drucken in Datei beendet."
$ Message 1118 is placed in the title bar of a warning dialog if a
$ font cannot be found during the "Print" operation.  Message 1119
$ is the text displayed in that warning dialog; the %s will be replaced
$ by the name of the font.
1118	"Kalender : Warnung - Drucken"
1119	"Warnung - Kann Schriftart %s nicht laden."
$ 
$ Message 1120 appears in an error dialog when an appointment cannot
$   be scheduled.
1120	"Das Ereignis kann in dem vorgegebenen Zeitrahmen nicht eingetragen werden.\n Die Aktion wurde abgebrochen."

$ 
$ Message 1121 is placed in the title bar of a warning dialog if a
$ print job fails because the Print Server returns BadAlloc.  Message
$ 1122 is the text displayed in that warning dialog.
1121	"Kalender : Fehler im Druckserver"
1122	"Druckjob gescheitert.\n\nDem X-Druckserver fehlen vorübergehend die notwendigen Ressourcen."

$set 2
$ *****************************************************************************
$ **
$ ** Message set for  DieFromToolTalkError Dialog
$ **
$ *****************************************************************************
$ These are the messages for the ToolTalk error dialog
$ "-NEW"
1 Calendar - Warning
$ "-NEW"
2 "Could not connect to ToolTalk:\n%s\n"
$ "-NEW"
3 OK
$ "-NEW"
4 "Calendar : Appointment Editor - Warning"
