$ message catalog of dtimsstart
$ @(#)$XConsortium: dtimsstart.msg /main/2 1996/10/19 14:26:56 rws $

$set 1
$ 	usage
1 Verwendung:  %s  [Optionen ..]
2 geänderte Umgebungsvariablen drucken
3 $SHELL aufheben
4 gibt Namen der Eingabemethode an
5 gibt Befehlsoptionen für Eingabemethode-Server an
6 gibt den Rechner an, auf dem der Eingabemethode-Server betrieben werden soll
7 Auswahlmodus der Eingabemethode ändern
8 registrierte Eingabemethode drucken
9 diese Meldung zeigen

$ 	selection mode
$ please do not translate ask_at_login and resume_current_input_method
20 SelectMode
21 ask_at_login
22 resume_current_input_method
23 Modus 'resume_current_input_method' erzwingen
24 Modus 'ask_at_login' erzwingen

$ 	error messages
31 Ungültige Option '%s'.
32 Umgebungsvariable 'HOME' nicht definiert.
33 Umgebungsvariable 'LANG' nicht definiert.
34 Diese Sprachumgebung wird vom Desktop nicht unterstützt.
35 Umgebungsvariable 'DISPLAY' nicht definiert.
36 Kann Datei\n  [%s] nicht öffnen.
37 Kann Datei\n  [%s] nicht erstellen.
38 Kann Verzeichnis\n  [%s] nicht erstellen.
39 Fehlender Eintrag '%s' in Konfigurationsdatei.\n  [%s]
40 Ein anderer?? '%s' wird bereits betrieben.
41 Keine Auswahldatei für '%s'.
42 Kann Auswahldatei\n  [%s] nicht erstellen.
43 Kein IMS ausgewählt für '%s'.
44 Keine Konfigurationsdatei für länderspezifische Angaben für '%s'.
45 Kein IMS konfiguriert für '%s'.
46 Keine IMS-Konfigurationsdatei für '%s'.
47 IMS '%s' nicht registriert.
48 Keine ausführbare Datei für '%s'.\n  [%s]
49 IMS '%s' wird bereits betrieben.
50 Kann IMS '%s' nicht ausführen.
51 IMS '%s' abgebrochen. Siehe Protokolldatei.\n  [%s]
52 IMS '%s' ist noch nicht verfügbar.
53 Unbekannter Rechner '%s'.
54 Aktion '%s' fehlgeschlagen.
55 Entfernte Ausführung fehlgeschlagen auf '%s'.
56 Entfernte Funktionsvielfalt ist nicht verfügbar auf '%s'.
57 Kein IMS registriert auf '%s'.
58 IMS '%1$s' nicht registriert auf '%2$s'.
59 Kann Bildschirm '%s' nicht öffnen.

$ 
