$ $TOG: DtMail.msg /main/40 1999/09/14 15:43:47 mgreess $
$ 
$   COMPONENT_NAME: desktop
$ 
$   FUNCTIONS: none
$ 
$   ORIGINS: 27,118,119,120,121
$ 
$   This module contains IBM CONFIDENTIAL code. -- (IBM
$   Confidential Restricted when combined with the aggregated
$   modules for this product)
$   OBJECT CODE ONLY SOURCE MATERIALS
$ 
$   (C) COPYRIGHT International Business Machines Corp. 1995
$   All Rights Reserved
$   US Government Users Restricted Rights - Use, duplication or
$   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/40 1999/09/14 15:43:47 mgreess $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 
$		     Common Desktop Environment
$ 
$   (c) Copyright 1993, 1994, 1995 Hewlett-Packard Company
$   (c) Copyright 1993, 1994, 1995 International Business Machines Corp.
$   (c) Copyright 1993, 1994, 1995 Sun Microsystems, Inc.
$   (c) Copyright 1993, 1994, 1995 Novell, Inc.
$   (c) Copyright 1995 Digital Equipment Corp.
$   (c) Copyright 1995 Fujitsu Limited
$   (c) Copyright 1995 Hitachi, Ltd.
$                                                                   
$ 
$                     RESTRICTED RIGHTS LEGEND                              
$ 
$ Use, duplication, or disclosure by the U.S. Government is subject to
$ restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in
$ Technical Data and Computer Software clause in DFARS 252.227-7013.  Rights
$ for non-DOD U.S. Government Departments and Agencies are as set forth in
$ FAR 52.227-19(c)(1,2).
$ 
$ Hewlett-Packard Company, 3000 Hanover Street, Palo Alto, CA 94304 U.S.A.
$ International Business Machines Corp., Route 100, Somers, NY 10589 U.S.A. 
$ Sun Microsystems, Inc., 2550 Garcia Avenue, Mountain View, CA 94043 U.S.A.
$ Novell, Inc., 190 River Road, Summit, NJ 07901 U.S.A.
$ Digital Equipment Corp., 111 Powdermill Road, Maynard, MA 01754, U.S.A.
$ Fujitsu Limited, 1015, Kamikodanaka Nakahara-Ku, Kawasaki 211, Japan
$ Hitachi, Ltd., 6, Kanda Surugadai 4-Chome, Chiyoda-ku, Tokyo 101, Japan

$quote "

$set 1

1 "OK"

2 "Postoptionen..."

3 "Abwesenheit"

4 "Aktualisieren der Eigenschaften..."
$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "Abbrechen"

6 "Post"

7 "Post"

8 "Post"

9 "Löschen"

10 "Nächste"

11 "Vorherige"

12 "Antwort an Absender"

13 "Drucken"

14 "Absender"

15 "Betreff"

16 "Datum und Uhrzeit"

17 "Größe"

18 "Briefkasten"

19 "Auf neue Post prüfen"

20 "Eingangskorb öffnen"

21 "Eingangskorb öffnen"

22 "Erstellen..."

23 " - Erstellen"

24 "Erstellen"

25 "Öffnen..."

26 " - Öffnen"

27 "Öffnen"

28 "Gelöschte Meldungen vernichten"

29 "Schließen"

30 "Öffnen"

31 "Als Text speichern..."

32 " - Meldung - Als Text speichern"

33 "Kopieren in"

34 "Drucken..."

35 "Suchen..."

36 "Alles auswählen"

37 "Löschen"

38 "Letzte wiederherstellen"

39 "Aus Liste wiederherstellen..."

40 "Meldung"

41 "Verschieben"

42 " - Meldungen"

43 "Kopieren"

44 "Alles auswählen"

45 "Bearbeiten"

46 " - Text"

47 "Nächste(s)"

48 "Vorherige(s)"

49 "Verkürzte Umschläge"

50 "Nach Datum/Uhrzeit"

51 "Nach Absender"

52 "Nach Betreff"

53 "Nach Größe"

54 "Nach Status"

55 "Ansicht"

56 "Neue Meldung"

57 "Erstellen, alle einschließen"

58 "Meldung weiterleiten"

59 "Antwort an Absender"

60 "Antwort an alle"

61 "Antwort an Absender, einschließen"

62 "Antwort an alle, einschließen"

63 "Erstellen"

64 "Verschieben"

65 "Andere Briefkästen..."

66 "Speichern als..."

67 " - Anlagen - Speichern als"

68 "Alles auswählen"

69 "Anlagen"

70 " - Anlagen"

71 "Überblick"

72 "Aufgaben"

73 "Referenzinformation"

74 "Kontexthilfe"

75 "Hilfe für Hilfe"

76 "Hilfe"

77 "Informationen zu ..."

78 " hat Probleme, den Status dieses Briefkastens festzustellen.\n\
Den Briefkasten durch Auswahl von OK schließen und das Programm 'Post' neu starten."

79 "Konvertieren... %d Prozent ausgeführt"

80 "Post"
$ 
$ Strings from dtmail/AttachArea.C

81 "Post"

82 "Post"

83 "Post"
$ 
$ Strings from dtmail/Attachment.C

84 "%s ist eine ausführbare Anlage. Soll sie ausgeführt werden?"

85 "Post"

86 "Post"

87 "Post"

88 "Post"
$ 
$ Strings from dtmail/RoamCmds.C

89 " - Andere Briefkästen"

90 "Verschieben"

91 "Drucken..."

92 "OK"

93 "Speichern"

94 "Speichern"

95 "Speichern"

96 "Leeren"

97 "Umbenennen"

98 " - Umbenennen"

99 "Post - Schließen"

100 "OK"

101 "Abbrechen"

102 "Die Weiterleitungsfunktion wird bereits für eine andere Funktion\n\
als 'Abwesenheit' benutzt. Die Funktion 'Abwesenheit' wird\n\
beim Ausführen an diese andere Weiterleitungsaktivität\n\
angehängt. Soll die Funktion 'Abwesenheit' trotzdem gestartet werden?\0"

103 "Post"

104 "Das Programm 'Abwesenheit' wird bereits in der Datei .forward ausgeführt.\n\
In der Dokumentation kann nachgelesen werden, wie das Programm beendet und aus der Datei .forward entfernt werden kann.\n\
Nach dem Beheben dieses Problems diesen Befehl versuchen.\0"

105 "Die Datei .vacation.msg kann nicht geöffnet werden -- fehlende Schreibberechtigung."

106 "Die Datei .vacation.msg ist bereits vorhanden. Soll sie durch den neuen Text ersetzt\n\
werden?"

107 "Die Datei .vacation.msg kann nicht geöffnet werden -- fehlende Schreibberechtigung."

108 "Ich bin nicht anwesend"
$ \t    /* NL_COMMENT
$ \t     * This is the default value of the subject field in the
$ \t     * message that gets returned to the sender when vacation
$ \t     * is turned on.
$ \t     */

109 "Ich bin in Urlaub.\n\
Ihre Post betreffend \"$SUBJECT\" lese ich nach meiner Rückkehr.\n"
$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */

111 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */

112 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */

113 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */

114 "N"
$ 
$ Strings from dtmail/Undelete.C

115 "Wiederherstellen"

116 "Schließen"
$ 
$ Strings from dtmail/SendMsgDialog.C

117 "Senden"

118 "Schließen"

119 "Neue Meldung"

120 "Post"

121 "Datei"

122 "Einschließen..."

123 " - Einschließen"

124 "Einschließen"

125 "Als Text speichern..."

126 " - Als Text speichern"

127 "Meldung protokollieren"

128 "Senden als"

129 "Schließen"

130 "Bearbeiten"

131 "Rückgängig"

132 "Ausschneiden"

133 "Kopieren"

134 "Einfügen"

135 "Format einfügen"

136 "In Klammern"

137 "Eingerückt"

138 "Inhalt löschen"

139 "Löschen"

140 "Alles auswählen"

141 "Anlagen"

142 "Datei hinzufügen..."

143 " - Hinzufügen"

144 "Hinzufügen"

145 "Speichern als..."

146 " - Anlagen - Speichern als"

147 "Löschen"

148 "Wiederherstellen"

149 "Umbenennen"

150 "Alles auswählen"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */

151 "Teilfenster anzeigen"

152 "Format"

153 "Zeilenumbruch"

154 "Einstellungen..."

155 "Suchen/Ersetzen..."

156 "Rechtschreibprüfung..."

157 "Templates"

158 " - Anlagen"

159 " - Erstellen"

160 "Neue Meldung"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */
$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "Kopieren"

162 "Alles auswählen"

163 "Bearbeiten"

164 "Speichern als..."

165 " - Anlages - Speichern als"

166 "Alles auswählen"

167 "Anlagen"

168 " - Anlagen"

169 " - Text"

170 "Überblick"

171 "Aufgaben"

172 "Referenzinformation"

173 "Kontexthilfe"

174 "Hilfe für Hilfe"

175 "Hilfe"

176 "Informationen zu ..."

177 "Post"
$ 
$ Strings from dtmail/DtMailGenDialog.C

178 " - Informationen zu Dtmail"

179 "Dtmail Version 1.0"

180 "OK"

181 "OK"

182 "Abbrechen"
$ 
$ Strings from dtmail/FindDialog.C

183 "Suchen"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */

184 "Suchen und Alles auswählen"

185 "Inhalt löschen"

186 "Schließen"

187 "Hilfe"

188 "An:"

189 "Von:"

190 "Betreff:"

191 "Cc:"

192 " - Suchen"

193 "Vorwärts"

194 "Rückwärts"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */
$ 
$ Strings from dtmail/Editor.C

195 "------------- Beginn der weitergeleiteten Meldung -------------\n\n"

196 "------------- Beginn der eingeschlossenen Meldung -------------\n\n"

197 "------------- Ende der weitergeleiteten Meldung -------------\n\n"

198 "------------- Ende der eingeschlossenen Meldung -------------\n\n"
$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n\
------------- Beginn der eingeschlossenen Meldung -------------\n"

200 "\n\
------------- Ende der eingeschlossenen Meldung -------------\n"
$ 
$ Strings from dtmail/DtEditor.C

201 "\n\
------------- Beginn der eingeschlossenen Meldung -------------\n"

202 "\n\
------------- Ende der eingeschlossenen Meldung -------------\n"
$ 
$ Strings from dtmail/ComposeCmds.C

203 "Post"

204 "Es kann kein Erstellungsfenster erzeugt werden."

205 "Post"

206 "Es kann kein Erstellungsfenster erzeugt werden."

207 "Post"

208 "Es kann kein Erstellungsfenster erzeugt werden."

209 "Post"

210 "Es kann kein Erstellungsfenster erzeugt werden."

211 "Post"

212 "Die Schablone ist nicht vorhanden."

213 "Post"

214 "Die Schablone ist offensichtlich beschädigt."

215 "Post"

216 "Es steht nicht genügend Speicher zum Laden der Schablone zur Verfügung."

217 "Post"

218 "Die Schablone ist offensichtlich beschädigt."
$ 
$ Strings from dtmail/SortCmd.C

219 "Sortieren..."

220 "Alles auswählen"

221 "Eingangskorb"

222 "%a %b %d %k:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to
$  * strftime man page for explanation of each format.
$  */

223 "%a %b %d %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to
$  * strftime man page for explanation of each format.
$  */

224 "%a %b %d %k:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to
$  * strftime man page for explanation of each format.
$  */

225 "%a %b %d %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to
$  * strftime man page for explanation of each format.
$  */

226 "Liste anzeigen"

$ String from Undelete.C, Deleted Messages window title
227 "Post - Gelöschte Nachrichten"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "Hinzufügen"
229 "Löschen"
230 "Senden"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "Sucht..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "1 Nachricht gefunden."
233 "%d Nachrichten gefunden."

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "Keine Übereinstimmungen gefunden."

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "Post - Informationen zu Post"
236 "Post-Version %d.%d.%d"
$  /* NL_COMMENT
$   * String 237 is the Copy button on Move Other Mailboxes dialog (from RoamCmds.C)
$   */
237 "Kopieren"

$ 
$ DTMC_BADSTATE
$ The mailbox is in a state which cannot be deciphered by the Mailer, i.e.
$ portions of the file have been deleted by another process (the Mailer
$ only knows how to handle other processes adding to the end of the mailbox.
$ 
$ "-NEW"
238 "Mailer is confused about the state of this mailbox.\nIt may be that another process has rewritten this mailbox in an unexpected way.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost."

$ 
$ DTMC_ACCESSFAILED
$ The Mailer cannot perform routine file operations on the mailbox file,
$ a.k.a. stat, fstat, write, ...
$ 
$ "-NEW"
239 "Mailer can no longer access this mailbox.\nIt may be that another process has deleted the mailbox file.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ DTMC_INODECHANGED
$ The mailbox has been rewritten by another process.
$ 
$ "-NEW"
240 "Mailer can no longer access this mailbox.\nAnother process has rewritten the mailbox file changing the inode.\n\nSelecting OK will cause the Mailer to close and reopen the mailbox.\nNOTE that any changes made to the mailbox since the last save may be lost.\n\nSelecting CANCEL will leave the mailbox unchanged."

$ 
$ Messages 241-244 are header field labels for SendMsgDialog.
$ 
$ "-NEW"
241 "An"
$ "-NEW"
242 "Betreff"
$ "-NEW"
243 "Cc"
$ "-NEW"
244 "Bcc"

$ 
$ Message 245 is the label for the Open command in the File menu
$ Message 246 is the label for the command in the OpenContainer menu
$	which opens Mailboxes not in the users folder list.
$ 
$ "-NEW"
245 "Öffnen"
$ "-NEW"
246 "Andere Briefkästen..."

$ 
$ Message 247 is the label for the command in the Aliases menu
$	which opens the MailOptions dialog allowing the user to create
$	other aliases.
$ Message 248 is the label for the Aliases popup menu
$ 
$ "-NEW"
247 "Andere Alias-Namen..."
$ "-NEW"
248 "Post - Alias-Namen"

$ 
$ Messages 249-255 are strings used to generate attachment summaries
$                  in included messages.
$ 
$ "-NEW"
249 "------------- Begin Included Attachment -------------\n\n" 
$ "-NEW"
250 "------------- End Included Attachment -------------\n\n" 
$ "-NEW"
251 "       Attachment Name:  "
$ "-NEW"
252 "     Attachment DtType:  "
$ "-NEW"
253 "Attachment ContentType:  "
$ "-NEW"
254 "Attachment Description:  "
$ "-NEW"
255 "------------------ Attachments ------------------\n" 

$ "-NEW"
$ DTMC_SERVERACCESSFAILED:
$ Mailer failed in attempt to retrieve messages from the mail server
256 "Mail server access failed:\n%s"

$ "-NEW"
$ Label on the button which causes the "Mail Retrieval" options to be displayed
257 "Options..."

$ "-NEW"
$ DTMC_GETMAILCOMMANDFAILED:
$ Mailer failed in attempt to retrieve messages via custom getmail command
258 "User Getmail command failed:\n%s"

$ "-NEW"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
259 "%a %d %b %Y"
260 "%a %d %b %k:%M"
261 "%a %d %b %H:%M"

$ "-NEW"
262 "nicht zustellbare Post Meldung"

$ "-NEW"
263 "The attachment '%s' is %d kilobytes.\nAdd as attachment?"




$set 2        Redefine set#


1 "Post"

2 "ToolTalk ist nicht initialisiert. Das Postzustellprogramm kann nicht ohne ToolTalk\n\
ausgeführt werden. /usr/dt/bin/dtsession starten oder den Systemadministrator\n\
fragen."

3 "Fenster können nicht initialisiert werden. Anforderung wird beendet.\n"

4 " wurde nicht ordnungsgemäß installiert\n\
und kann nicht ausgeführt werden, da die Ausführungsgruppe\n\
falsch gesetzt ist."

5 "Fehlende Berechtigung zum Anzeigen von %s"
$ \t    /* NL_COMMENT
$ \t     * The %s is the name of the mailbox the user doesn't have
$ \t     * permission to view.
$ \t     */

6 "Der Briefkasten %s ist ein Verzeichnis und kann nicht geöffnet werden."

7 "%s kann nicht geleert werden, da nicht vorhanden."

8 "Behälter %s wurde geleert"

9 "Fehler - %s konnte nicht geleert werden"

10 "Post"

11 "%s"

12 "Post"

13 "Post"

14 "Es muß eine Anlage ausgewählt werden, bevor eine Datei mit dem Befehl \"Speichern als\" gespeichert werden kann."

15 "Fehler - mailrc ist nicht abrufbar."

16 "Keine Meldung ausgewählt."
$ \t/* NL_COMMENT
$ \t * No mail message has been selected by the user.
$ \t */

17 "\"%s\" wurde bearbeitet. Trotzdem löschen?"

18 "Fehler: Datei %s kann nicht eingeschlossen werden"

19 "Vor dem Speichern in einer Datei mit dem Befehl\n\
\"Speichern als\" muß eine Anlage ausgewählt werden."

20 "Vor dem Speichern in einer Datei mit dem Befehl\n\
\"Speichern als\" muß eine Anlage ausgewählt werden."

21 "Post"

22 "Irreparable Syntaxfehler in der Datei ~/.mailrc gefunden.\nAchten Sie auf weitere Meldungen am Terminal. Die Fehler beheben und dtmail erneut starten.\nSollten Sie trotzdem fortfahren, werden Sie keine Änderungen in der\nDatei options dialog to?? speichern können."
23 "Fortfahren"
24 "Beenden"
25 " Irreparable Syntaxfehler in der Datei ~/.mailrc gefunden.\nDie Einstellungen der Postoptionen können zwar in der aktuellen Session angewendet, jedoch nicht\nin der Datei gespeichert werden." 

$ 
$ Messages for file locking dialog displayed from the Advanced option pane.
$ 
$ "-NEW"
26 "The value of the file locking option has changed.\nTo take immediate effect, folders need to be closed and reopened.\n  o Click on 'Reopen' to reopen folders,\n    making the new option take effect immediately.\n  o Click on 'Continue' to avoid reopening folders.\n    The new option will take effect the next time you open a folder.\n  o Click on 'Cancel' to cancel the Apply and return to editing options."
$ "-NEW"
27 "Reopen"
$ "-NEW"
28 "Continue"
$ "-NEW"
29 "Cancel"

$ 
$ Messages for ToolTalk errors.
$ 
$ "-NEW"
30 "%s returned ToolTalk error: %s\n"

$set 3        Redefine set#


1 "Automatisches Speichern..."

2 "Initialisieren..."

3 "Der Briefkasten %s ist nicht vorhanden.\n\
Soll ein Briefkasten mit diesem Namen erstellt werden?"

4 "Post"

5 "OK"

6 "Der Briefkasten %s ist gesperrt.\n\
Die Sperre manuell aufheben und erneut versuchen\n\
oder den Systemadministrator verständigen."

7 "Post"

8 "OK"

9 "OK"

10 "OK"

11 "OK"

12 "%s"

13 "Meldung %d von %d, %d neu, %d gelöscht"

14 "Meldung %d von %d, %d neu, %d gelöscht"
$ \t/* NL_COMMENT
$ \t * The user will see the following message display as:
$ \t * "Message 3 of 10, 2 new, 6 deleted"
$ \t * This means ??? -- Explain to translator.
$ \t */

15 "Speichern..."

16 "Post"
$ \t\t/* NL_COMMENT
$ \t\t * This dialog comes up when the user tries to quit the
$ \t\t * mailbox and the user is asked if he wants to destroy
$ \t\t * the messages marked for deletion.
$ \t\t */

17 "Sollen die in diesem Briefkasten zum Löschen\n\
markierten Meldungen vernichtet werden?"

18 "OK"

19 "Abbrechen"

20 "Öffnen des Briefkastens..."

21 "%s ist bereits vorhanden.\n\
Überschreiben?"

22 "Post"

23 "%s kann nicht überschrieben werden.\n\
Dateiberechtigungen überprüfen und erneut versuchen."

24 "Post"

25 "Laden des Behälters..."

26 "Ordnerübersichtsinformation"

27 "Laden..."

28 "Behälter leeren"

29 "OK"

30 "OK"

31 "OK"

32 "Vernichten gelöschter Meldungen..."

33 "OK"

34 "%s ist nicht vorhanden."

35 "%s kann nicht geöffnet werden."

36 "Es kann kein Speicher zugeordnet werden."

37 "Übersicht über Anlagen"

38 "Anlage"

39 "Anlagen"
$ \t/* NL_COMMENT
$ \t * "attachments" is the plural form of "attachment".
$ \t */

40 "Anlagen"

41 "gelöscht"

42 "%s ist bereits vorhanden. Ersetzen?"

43 "%s kann nicht ersetzt werden."

44 "%s kann nicht erstellt werden."

45 "%s kann nicht erstellt werden."

46 "Leerer Behälter"

47 "%s ist bereits vorhanden.\n\
Überschreiben?"

48 "Post"

49 "%s kann nicht überschrieben werden.\n\
Dateiberechtigungen überprüfen und erneut versuchen."

50 "Post"

51 "%s kann nicht erstellt werden."

52 "Post"

53 "%s kann nicht geschrieben werden."

54 "Post"

55 "%s kann nicht erstellt werden."

56 "Post"

57 "Anlage umbenennen als"

58 "Das Erstellungsfenster enthält Text oder\n\
Anlagen, die beim Schließen des Fensters\n\
verlorengehen.\n\
Soll das Erstellungsfenster geschlossen werden?"

59 "Kein Speicher"

60 "Es steht nicht genügend Speicher zum Laden der vorhandenen Datei .vacation.msg zur Verfügung."

61 "Post"

62 "Die vorhandene Datei .vacation.msg ist offensichtlich beschädigt."

63 "Zu verschiebende Meldung auswählen."

64 "Zu kopierende Meldung auswählen."

65 "%d Meldungen verschoben nach %s"

66 "%d Meldung verschoben nach %s"

67 "%d Meldungen kopiert nach %s"

68 "%d Meldung kopiert nach %s"

69 "Die Anzeige ist bereits vorhanden. Sie wird in den Vordergrund gestellt."
$ \t/* NL_COMMENT
$ \t* The current mail message selected is already displayed in a separate
$ \t* window.  Therefore this 'separate' window will be raised in front
$ \t* of existing windows so the user can see it.
$ \t*/

70 "Schreiben von nicht zustellbarer Post..."

71 "Post"

72 "OK"

73 "Abbrechen"

74 "OK"

75 "OK"

76 "OK"

77 "Eine Anlage ist geöffnet, die möglicherweise ungespeicherte Änderungen enthält.\nDas Senden dieser Nachricht wird die Verbindung mit der geöffneten\n Anlage unterbrechen. Alle ungespeicherten Änderungen werden daher nicht in der\n Nachricht enthalten sein. Sie können mit Speichern unter Änderungen speichern, nachdem die\n Verbindung unterbrochen wurde; die Änderungen werden jedoch nicht Teil der\n Anlage sein."
78 "Postoptionen werden initialisiert..."
79 "Vernichten und beenden"
80 "Nicht vernichten, beenden"
81 "Diese Anlage kann Befehle enthalten, die schwere Schäden\nverursachen können. Es wird empfohlen, sie nur dann auzuführen, nachdem\nSie sich von der Sicherheit dieses Vorgehens überzeugt haben.\n\nDrücken Sie auf OK, wenn das der Fall ist,\nund auf Abbrechen, um die Ausführung abzubrechen."
82 "Jemand anders benutzt diesen Briefkasten.\nHätten Sie gern exklusiven Zugriff?"
83 "Post kann keinen exklusiven Zugriff auf diesen Briefkasten erhalten.\nMöchten Sie diesen Briefkasten als schreibgeschütztes Dokument öffnen?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "%d Nachrichten gelöscht."

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "%d Nachricht gelöscht."
86 "Sucht nach neuer Post..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "Post - Schließen"
88 "Gelöschte Nachrichten vernichten und diesen Briefkasten schließen?"
89 "Vernichten und schließen"
90 "Bewahren und schließen"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "Kann ungültige Aktion nicht ausführen."
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "Ausführen der Aktion fehlgeschlagen!"
93 "Ausgewähltes Symbol %s ist ausführbar.\nKlicken Sie zur Ausführung auf OK oder zur Beendung auf Abbrechen."

94 "Post kann keinen exklusiven Zugriff auf diesen Briefkasten\nerhalten, weil das System nicht antwortet.\n\nNur dieses Mal haben Sie die Möglichkeit, diesen Briefkasten als schreibgeschütztes Dokument\nzu öffnen, oder es als Lese-Schreibdokument ohne exklusiven Zugriff zu öffnen\n(bitte nur verwenden, wenn niemand anders diesen Briefkasten benutzt)."
95 "Schreibgeschützt"
96 "Lesen-Schreiben"

$ 
$ "-NEW"
$ 
$ This message appears when dtmail tries to open a mailbox which has been
$ opened by another dtmail process.
$ 
$ Parameters:
$   1.  Error message saying that the <mailbox>.dtmail lockfile has been found.
$   2.  The mailbox path.
$   3.  "OK"
$   4.  "Cancel"
$   5.  The <mailbox>.dtmail lockfile path.
$ 
97 "%s\n\nThis may indicate that another Mailer has opened\n%s\n\nYou may open this mailbox READ ONLY by choosing '%s'.\n\nOtherwise, you may choose '%s',\nmake sure that another Mailer has not opened this mailbox,\ndelete %s,\nand reopen this mailbox."

$ 
$ "-NEW"
$ 
$ Messages 98-100 check for problems in the paths specified by users of
$ the file selection box.
$ 
98 "Search permission denied on a component of the path prefix,\n'%s'."
99 "A component of the path prefix is not a directory,\n'%s'."
100 "A component of the path prefix does not exist,\n'%s'."


$set 5        Redefine set#


1 "Post"

2 "Post"

3 "Wenn diese Meldung unverändert gesendet wird,\n\
\t    gehen alle Änderungen an den Anlagen\n\
\t    verloren."
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */

4 "Nur eine Anlage auswählen\n\
\t    und 'Umbenennen' auswählen"
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */

5 "Einige der Adressen in der Meldung sind nicht korrekt und\n\
beziehen sich nicht auf bekannte Benutzer des Systems.\n\
Sicherstellen, daß alle Adressen gültig sind und den\n\
Vorgang wiederholen."
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */

6 "Im Postzustellprogramm ist nicht genügend Speicher verfügbar,\n\
um diese Meldung zu senden.\n\
Try quitting other applications and\n\
resend this message."
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */

7 "Bei dem Versuch, die Meldung zu senden, ist ein Fehler aufgetreten.\n\
Überprüfen, ob die Meldung empfangen wurde. Wenn nicht,\n\
muß die Meldung erneut gesendet werden."
$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "Versuchen Sie zu senden, nachdem Sie den/die Empfänger der Nachricht in\nden Feldern An:, Kopie: oder Blindkopie: angegeben haben."


$set 12        Redefine set#


1 "Anschluß"

2 "Anschlüsse"

3 "Anzeigezähler"

4 "Anschluß folgender FIFO-Dateien nicht möglich: %s"

5 "Anschluß folgender Dateien mit Sonderzeichen nicht möglich: %s"

6 "Anschluß folgender Verzeichnisse nicht möglich: %s"

7 "Anschluß folgender Dateien mit speziellen Blöchen nicht möglich: %s"

8 "Anschluß folgender Socket-Dateien nicht möglich: %s"

$set 13        Redefine set#


1 "Erstellen nicht möglich"

2 "Schreiben nicht möglich"
$ 
$ Strings from dtmail/AttachCmds.C

$set 14        Redefine set#


1 "Anschluß hinzufügen"

2 "Öffnen von %s nicht möglich"

3 "Anschluß folgender FIFO-Dateien nicht möglich: %s"

4 "Anschluß folgender Dateien mit Sonderzeichen nicht möglich: %s"

5 "Anschluß folgender Verzeichnisse nicht möglich: %s"

6 "Anschluß folgender Dateien mit speziellen Blöcken nicht möglich: %s"

7 "Anschluß folgender Socket-Dateien nicht möglich: %s"

8 "Öffnen von %s nicht möglich"

9 "Postzustellprogramm - Anschluß umbenennen"

10 "Beschreibung"

11 "Anschluß sichern als"




$set 15
1 "Sie haben ungespeicherte Änderungen vorgenommen.\nSie können Ihre Änderungen speichern, sie verwerfen,\noder an die vorherige Stelle im Dialog zurückkehren."
2 "Speichern"
3 "Verwerfen"
$ 
$ The followings are added by IBM for 41J release
$ 
$set 20
1 "Der Briefkasten %s ist bereits geöffnet."
$ The above message is used in RoamMenuWindow::open
$ See AIXC cmvc defect 175920
2 "Lokalen Namen verwenden: "
$ The above message is used in OptCmd::init_advanced_pane()
$ see AIX cmvc defect 176608
3 "Schreibgeschützt"
$ The above message is used in RoamMenuWindow::mapnotify()
$ see AIX cmvc defect 176608

$ 
$	SETS 21 - 25 WERE ADDED TO SUPPORT CDEnext PRINTING
$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$set 21
$ 
$	Messages 1 - 11 are used in DmxPrintJob.
$ 
$ 
$	This is the status message that gets displayed in the MainWindow
$	and RoamMenuWindow status lines when a print job is being executed.
$	The '%s' is the name of the temporary file containing the message(s)
$	to be printed.
1 "Druckt %s ..."

$	Messages 2 - 4 are used in the error popup which gets displayed
$	when an invalid margin specifier has been supplied by the user.
$ 
$	Message 2 is the actual error messagactual error message
$	Message 3 is the title which is displayed in the error popup.
$	Message 4 is the label on the OK button of the error popup.
2 "Die Syntax einer der folgenden Randangaben\n ist nicht korrekt: \n %s \n %s \n %s \n %s \n Mit Standardrändern fortfahren?"
3 "Post"
4 "OK"

$	Messages 5 - 11 are format string used to construct the header
$	and footer strings which appear in the printing output.
$ 
$	Message 5 is the format string used to make a Cc header/footer.
$	Message 6 is the format string used to make a Date header/footer.
$	Message 7 is the format string used to make a From header/footer.
$	Message 8 is the format string used to make a Subj't header/footer.
$	Message 9 is the format string used to make a To header/footer.
$	Message 10 is the format string used to make a Page# header/footer.
$	Message 11 is the format string used to make a UserName header/footer.
5 "Kopie:  %s"
6 "Datum:  %s"
7 "Von:  %s"
8 "Betreff:  %s"
9 "An:  %s"
10 "Seite %d von %d"
11 "Post für:  %s"

$ 
$	Messages 12 - 13, 20 are used in DmxPrintSetup to construct the
$	app-specific printing options for DtMail which will be included
$	in the DtPrintSetupBox.
$ 
$	Message 12 is the label used on the Toggle Button to indicate that
$	multiple messages should be printed in separate spool jobs.
$	Message 13 is the label used on the Toggle Button to indicate that
$	lines which would extend beyond the edge of the printed page be 
$	"wrapped" to the next line.
12 "Separat drucken"
13 "Zeilenumbruch verwenden"


$	Messages 14 - 15 are status messages for the PrintToFile function.
$ 
$	Message 14 indicates that the PrintToFile function was unsuccessful.
$	Message 15 indicates that the PrintToFile function was successful.
$       NOTE:  'Print to File' should be translated as in DtPrint.msg
$               Set 1, Message 3.
14 "'In Datei drucken' fehlgeschlagen."
15 "'In Datei drucken' erfolgreich ausgeführt."

$       NL_COMMENT 
$          Messages 16 - 19 are obsolete, and have been replaced by 24
$ 
$	Messages 16 - 19 are status messages for the popup PDM function.
$ 
$	Message 16 indicates that there was no pdm deamon running.
$	Message 17 indicates that the pdm deamon was unable to start a pdm.
$	Message 18 indicates that the pdm couldnt connect to the video display.
$	Message 19 indicates that the pdm couldnt connect to the print display.
16 "Keinen PDM in der Umgebung gefunden."
17 "Kann PDM nicht starten."
18 "PDM ist nicht zum Anschluß an Video-Bildschirm berechtigt."
19 "PDM ist nicht zum Anschluß an Druckbildschirm berechtigt."

$	Message 20 is the label used on the Push Button to bring up
$	the printing options dialog from the DtPrintSetupDialog.
20 "Optionen..."
$       Message 21 is used for the title string on the DtPrintSetupDialog.
21 "Post - Druckereinstellungen"
 
$       Message 22 is used to alert the user to the fact that the mailer
$                  cannot close the mailer window until a task (usually
$                  a print job) has terminated.
22 "Schließen anstehend: wartet auf Beendung der Aufgabe ..."

$	Message 23 is used to alert the user to the fact that the X Print
$		   Server cannot complete the print request due to a lack
$		   of resources.
23 "Dem X-Druckserver fehlen vorübergehend die notwendigen Ressourcen"
  
$       Messages 24 & 25 are used to handle errors from the PDM
24	"Druckdialogmanager (PDM)-Fehler - Einstellungen fehlgeschlagen."
25	"Weiter"





$ 
$	The messages in this set are used in pulldown menu for the
$	header/footer $	frame which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 8 are used in DmxPrintOptions.
$ 
$ 
$	Message 1 specifies that the page header/footer field be empty.
$	Message 2 put the Cc msg header in the page header/footer field.
$	Message 3 put the Date msg header in the page header/footer field.
$	Message 4 put the From msg header in the page header/footer field.
$	Message 5 put the Subject msg header in the page header/footer field.
$	Message 6 put the To msg header in the page header/footer field.
$	Message 7 put the Page Nmbr msg header in the page header/footer field.
$	Message 8 put the User Name msg header in the page header/footer field.
$set 22
1 "Leer"
2 "Kopie-Umschlag"
3 "Datum-Umschlag"
4 "Von-Umschlag"
5 "Betreff-Umschlag"
6 "An-Umschlag"
7 "Seitenzahl"
8 "Benutzername"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 4 are used in DmxPrintOptions.
$ 
$	Message 1 don't print any message headers.
$	Message 2 print the "standard" msg headers (To, From, Subject, Cc).
$	Message 3 print the "abbreviated" msg headers as defined by the user.
$	Message 4 print all message headers.
$ 
$set 23

1 "Keine"
2 "Standard"
3 "Abgekürzt"
4 "Alle"

$ 
$	The messages in this set are used in pulldown menu for the
$	Printed Message Headers option which is part of the "Printing" pane
$	in the Options dialog.
$ 
$	Messages 1 - 5 are used in DmxPrintOptions.
$ 
$	Message 1 use a New Line (CRLF) to separate multiple messages.
$	Message 2 use a Blank Line (2xCRLF) to separate multiple messages.
$	Message 3 use a Line of characters to separate multiple messages.
$	Message 4 start each new message on a new page.
$	Message 5 print each message in it's own spool job.
$ 
$set 24
1 "Neue Zeile"
2 "Leerzeile"
3 "Zeichenzeile"
4 "Neue Seite"
5 "Neuer Job"

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1 - 2 are used in DmxPrintOptions.
$ 
$ 
$set 25
$ 
$	Label for the option menu used to specify which message headers are
$	printed.
1 "Gedruckte Nachrichtumschläge:  "
$ 
$	Label for the option menu used to specify which how multiple messages
$	are separated.
2 "Mehrere Nachrichten trennen durch:  "

$ 
$	The following set was added to support CDEnext printing based on
$	the Xp Print Server.
$ 
$	Messages 1-4 are used in error dialogs to indicate an invalid
$		     entry for margin specifiers in the printing options pane.
$	Message 5 is the label string on the button to dismiss the error dialog.
$ 
$ 
$set 26
1 "Obere Randangabe ist ungültig:  "
2 "Rechte Randangabe ist ungültig:  "
3 "Untere Randangabe ist ungültig:  "
4 "Linke Randangabe ist ungültig:  "
5 "Fortfahren"

$ 
$	The following set was added to support the Mail Retrieval option pane.
$ 
$	Messages 1-5 Used in the Server Protocol option menu to indicate the
$		     set of mail server network protocols which are supported.
$	Messages 6-15 Are used to label the options in the pane.
$ 
$ 
$ "-NEW"
$set 27
1 "Auto"
2 "POP3"
3 "APOP"
4 "IMAP"
5 "POP2"

6 "Automatic (system) delivery"

7 "Mail server retrieval"
8 "Server Protocol:"
9 "Server Name:"
10 "User Name:"
11 "Password:"
12 "Remember password"
13 "Delete from server after retrieval"
14 "Retrieve old messages"

15 "Custom retrieval"
16 "User Getmail command:"

17 "Null INBOX path."
18 "INBOX folder path:"

