$ $XConsortium: dticon.msg /main/3 1995/11/08 13:17:06 rswiston $
$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dticon.msg
$ **
$ **  Project:     HP DT Icon Editor
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dticon
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1992, 1993, 1994 Hewlett-Packard Company
$ **     (c) Copyright 1993, 1994 International Business Machines Corp.
$ **     (c) Copyright 1993, 1994 Sun Microsystems, Inc.
$ **     (c) Copyright 1993, 1994 Unix System Labs, Inc., a subsidiary of
$ **         Novell, Inc.
$ **
$ **     All Rights reserved
$ **
$ **
$ *****************************************************************************
$ **

$set 2
$ *****************************************************************************
$ ** _DtMessage set for fileIODialog.c
$ **
$ ** messages 10-16 are for the FileSelectionBox widget (default labels)
$ *****************************************************************************

2 아이콘 편집기 - 파일 입출력
4 아이콘 편집기 - 파일 입출력
6 아이콘 편집기 - 새이름 저장
8 아이콘 편집기 - 파일 열기
10 폴더 열기 
12 폴더
14 파일
16 파일 이름 입력
17 파일 이름 입력
18 폴더 열기
20 UNTITLED
22 파일 열기
24 저장

$set 4
$ *****************************************************************************
$ ** _DtMessage set for newIconDialog.c
$ **
$ *****************************************************************************

2 newIconDialog
4 아이콘 편집기 - 크기 바꾸기
6 예 
8 취소
10 도움말
12 새 세로:
14 새 가로:

$set 6
$ *****************************************************************************
$ ** _DtMessage set for queryDialog.c
$ **
$ *****************************************************************************

2 아이콘 편집기 - 경고
6 예 
$ ** DO NOT LOCALIZE - the user should never see this message
8 확실합니까?
10 취소

$set 8
$ *****************************************************************************
$ ** _DtMessage set for stdErrDialog.c
$ **
$ *****************************************************************************

2 아이콘 편집기 - 오류
4 계속

$set 10
$ *****************************************************************************
$ ** _DtMessage set for utils.c
$ **
$ *****************************************************************************

$ ** DO NOT LOCALIZE messages 2-48, they appear in the errorlog only
2 Cannot initialize button icon for circle
4 Cannot initialize button icon for solid circle
6 Cannot initialize button icon for polyline
8 Cannot initialize button icon for polygon
10 Cannot initialize button icon for solid polygon
12 Cannot initialize button icon for ellipse
14 Cannot initialize button icon for solid ellipse
16 Cannot initialize button icon for eraser
18 Cannot initialize button icon for line
20 Cannot initialize button icon for flood
22 Cannot initialize button icon for point
24 Cannot initialize button icon for rectangle
26 Cannot initialize button icon for solid rectangle
28 Cannot initialize button icon for select
30 Unable to parse static color no.
32 Unable to allocate static color no.
38 No memory(0)
40 No memory(1)
42 No memory(2)
44 No memory(3)
46 No memory(4)
48 No memory(5)

50 응용프로그램 아이콘 기억장치를 초기화할 수 없습니다.
52 유효하지 않은 '-f' 매개변수 사용
54 유효하지 않은 '-i' 매개변수 사용
56 유효하지 않은 '-session' 매개변수 사용
58 유효하지 않은 크기 형식
60 화면 이미지를 잡지 못했습니다.
62 작동이 실패했습니다.\n색상맵이 꽉 찼습니다.
64 유효하지 않은 차원 매개변수

66 (제목없음)

$set 12
$ *****************************************************************************
$ ** _DtMessage set for dtIconShell.c
$ **
$ *****************************************************************************

1 아이콘 편집기
2 2 색상
3 아이콘 편집기 - (제목없음)
4 아이콘 편집기에 들어오신 것을 환영합니다.
6 도형 채우기
8 고정 색상
10 동적 색상
12 고정 회색
14 전경색
16 바탕색 
18 위 그림자
20 아래 그림자
22 선택
24 투명

$ ** message 26-198 are menu items with corresponding mnemonics
$ ** (for set grouping information, see the comment at the end-of-file)
26 N
28 새 아이콘N...
30 O
32 열기O...
34 S
36 저장S
38 A
40 새이름 저장A...
42 x
44 마침x
46 F
48 파일F
50 U
52 원래대로U
54 t
56 영역 자르기t
58 C
60 영역 복사하기C
62 P
64 영역 붙이기P
68 L
70 왼쪽L
72 R
74 오른쪽R
76 R
78 영역 회전R
82 V
84 수직V
86 H
88 수평H
90 F
92 영역 뒤집기F
94 S
96 영역 크기조절S
98 z
100 아이콘 크기바꾸기z...
102 A
104 실제위치점 정의A
106 D
108 실제위치점 없애기D
110 G
112 화면 이미지 잡기G
114 e
116 아이콘 다시입력e
118 E
120 편집E
122 V
124 모눈 표시V
128 B
130 XBM
134 P
136 XPM
138 O
140 출력 형식O
144 2x
146 3x
148 4x
150 5x
152 6x
154 8x
156 10x
158 12x
160 M
162 확대율M
164 O
166 선택사항O
168 v
170 개요v...
172 T
174 작업T...
176 R
178 참조R...
180 O
182 항목O
188 U
190 도움말 사용U...
192 A
194 아이콘 편집기에 관하여A...
196 H
198 도움말H

$ ** message 200-are used in the "instruction" line for current drawing mode
200 현재 편집 모드:
202 (채움)
204 연필
206 채우기
208 선
210 다선
212 사각형
214 다각형
216 원
218 타원
220 지우개
222 선택
224 유효하지 않음

$set 14
$ *****************************************************************************
$ ** _DtMessage set for help.c
$ **
$ *****************************************************************************

2 아이콘 편집기 - 도움말
4 아이콘 편집기 내의 항목을 \n선택해야 합니다.

$set 16
$ *****************************************************************************
$ ** _DtMessage set for process.c and fileIO.c
$ **
$ *****************************************************************************

2 파일이 사용할 수 없거나\n유효하지 않은 데이타를 포함하고 있습니다.
4 파일에 데이타를 써넣을 수 없습니다.
6 이 기능은 아직 사용할 수 없습니다.
8 사용할 수 있는 이전 이미지가\n없습니다.
10 유효하지 않은 가로나 세로를\n지정했습니다.
12 영역을 선택하지 않았습니다.
14 전에 오려두거나 복사한 영역이 없습니다.
16 현재 아이콘을 저장하지 않았습니다.\n\n변경사항이 없어지게 됩니다.
20 파일 사용 권한을 점검하십시오.
22 파일에서 세션을 복원할 수 없었습니다.
24 세션을 파일에 저장할 수 없었습니다.
25 파일이 이미 있습니다.\n\n파일에 겹쳐써도 좋습니까?

$set 18
$ *****************************************************************************
$ ** _DtMessage set for event.c
$ **
$ *****************************************************************************
2 잡은 이미지 크기 = %dx%d

$ *****************************************************************************
$ ** End of _DtMessage Catalog File
$ ** (Comments only below this line)
$ *****************************************************************************
$ **
$ *****************************************************************************
$ ** Unique mnemonic groupings from set 12
$ *****************************************************************************
$ **
$ ** Unique Set 1:  (Main Menu Bar)
$ **
$ **   46 F
$ **   48 File
$ **
$ **   118 E
$ **   120 Edit
$ **
$ **   164 O
$ **   166 Options
$ **
$ **   196 H
$ **   198 Help
$ **
$ **
$ ** Unique Set 2:  (File Menu)
$ **
$ **   26 N
$ **   28 New
$ **   30 O
$ **   32 Open...
$ **   34 S
$ **   36 Save
$ **   38 A
$ **   40 Save As...
$ **   42 x
$ **   44 Exit
$ **
$ **
$ ** Unique Set 3:  (Edit Menu)
$ **
$ **   50 U
$ **   52 Undo
$ **   54 t
$ **   56 Cut Area
$ **   58 C
$ **   60 Copy Area
$ **   62 P
$ **   64 Paste Area
$ **
$ **        Unique Set 3a:  (Rotate Sub-Menu)
$ **        68 L
$ **        70 Left
$ **        72 R
$ **        74 Right
$ **   76 R
$ **   78 Rotate Area
$ **
$ **        Unique Set 3b:  (Flip Sub-Menu)
$ **        82 V
$ **        84 Vertical
$ **        86 H
$ **        88 Horizontal
$ **   90 F
$ **   92 Flip Area
$ **   94 S
$ **   96 Scale Area
$ **   98 z
$ **   100 Resize Icon...
$ **   102 A
$ **   104 Add Hot Spot
$ **   106 D
$ **   108 Delete Hot Spot
$ **   110 G
$ **   112 Grab Screen Image
$ **   114 e
$ **   116 Clear Icon
$ **
$ **
$ ** Unique Set 4:  (Options Menu)
$ **
$ **   122 V
$ **   124 Visible Grid
$ **
$ **        Unique Set 4a:  (Output Sub-Menu)
$ **        128 B
$ **        130 XBM
$ **        134 P
$ **        136 XPM
$ **   138 O
$ **   140 Output Format
$ **   160 M
$ **   162 Magnification
$ **
$ **
$ ** Unique Set 5:  (Help Menu)
$ **
$ **   168 I
$ **   170 Introduction...
$ **   172 T
$ **   174 Tasks...
$ **   176 R
$ **   178 Reference...
$ **   180 O
$ **   182 On Item
$ **   188 U
$ **   190 Using Help...
$ **   192 V
$ **   194 Version...
$ **
