$ 
$ +SNOTICE
$ 
$  $TOG: DtMail.msg /main/4 1998/05/22 17:06:52 rafi $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993, 1994, 1995 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$quote "

$ 
$ Strings from dtmail/RoamApp.C

$set 1
1 "예"
$ 	    /* NL_COMMENT
$ 	     * This is a menu label, please refer to the resource file "Dtmail" for
$            * appropriate mnemonics tranlation
$ 	     */
2 "우편 선택사항p..."
3 "휴가"
4 "특성 갱신..."


$ 
$ Strings from dtmail/RoamMenuWindow.C

5 "취소"
6 "우편 시스템"
7 "우편 시스템"
8 "우편 시스템"
9 "없애기"
10 "다음 메세지"
11 "이전 메세지"
12 "보낸 사람에게 응답"
13 "인쇄"
14 "보낸 사람"
15 "제목"
16 "날짜와 시간"
17 "크기"
$ 	    /* NL_COMMENT
$            * Menu labels in Main Mailer (from RoamMenuWindow.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 18-22,25,28,29 are menu labels for "Mailbox" pull down menu.
$            * Message 30,31,33-40 are menu labels for "Message" pull down menu. 
$            * Message 43-45 are menu labels for "Edit" pull down menu. 
$            * Message 47--55 are menu labels for "View" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
18 "우편함x"
19 "새 우편 점검M"
20 "수신함 열기I"
21 "수신함 열기"
22 "새 우편함N..."
23 "우편 시스템 - 새 우편함"
24 "새 우편함"
25 "열기O..."
26 "우편 시스템 - 열기"
27 "열기"
28 "메세지 완전히 없애기D"
29 "닫기C"
30 "열기O"
31 "텍스트파일로 저장A..."
32 "우편 시스템 - 메세지 - 텍스트파일로 저장"
33 "복사하기C"
34 "인쇄P..."
35 "찾기F..."
36 "모두 선택S"
37 "없애기D"
38 "최종 없애기 취소r"
39 "목록으로 되살리기U..."
40 "메세지M"
41 "옮기기o"
42 "우편 시스템 - 메세지"
43 "복사하기C"
44 "모두 선택S"
45 "편집E"
46 "우편 시스템 - 텍스트"
47 "다음 메세지N"
48 "이전 메세지P"
49 "헤더 숨기기H"
50 "날짜/시간으로D"
51 "보낸 사람으로S"
52 "제목으로b"
53 "크기로z"
54 "상태로t"
55 "열람V"
56 "새 메세지M"
57 "새 작성, 모두 포함N"
58 "메세지 전달F"
59 "보낸 사람에게 응답R"
60 "모든 사람에게 응답A"
61 "보낸 사람에게 응답, 포함S"
62 "모든 사람에게 응답, 포함I"
63 "메세지 작성p"
64 "옮기기o"
65 "기타 우편함O..."
66 "새이름 저장A..."
67 "우편 시스템 - 별첨 - 새이름 저장"
68 "모두 선택S"
69 "별첨A"
70 "우편 시스템 - 별첨"
71 "개요v..."
72 "작업T..."
73 "참조R..."
74 "항목O"
75 "도움말 사용U..."
76 "도움말H"
77 "우편 시스템에 관하여A"
78 "우편 시스템이 이 우편함의 상태를 제대로 인식하지 못합니다.\n예를 눌러 해당 우편함을 닫고 우편 시스템을 다시 시작하십시오."
79 "변환중... %d 퍼센트 완료"
80 "우편 시스템"

$ 
$ Strings from dtmail/AttachArea.C

81 "우편 시스템"
82 "우편 시스템"
83 "우편 시스템"


$ 
$ Strings from dtmail/Attachment.C

84 "%s은(는) 실행할 수 있는 별첨입니다. 수행하겠습니까?"
85 "우편 시스템"
86 "우편 시스템"
87 "우편 시스템"
88 "우편 시스템"


$ 
$ Strings from dtmail/RoamCmds.C

89 "우편 시스템 - 기타 우편함"
90 "옮기기"
91 "인쇄P..."
92 "예"
93 "저장"
94 "저장"
95 "저장"
96 "비어있음"
97 "이름 바꾸기"
98 "우편 시스템 - 이름 바꾸기"
99 "우편 시스템"
100 "예"
101 "취소"
102 "사용자는 휴가가 아닌 것에 대한 발송 기능을 \n사용중입니다. 휴가가 수행중일 때는 \n이와 같은 다른 발송 활동에 휴가가 첨부됩니다. \n그래도 휴가를 시작하시겠습니까?\0"
103 "우편 시스템"
104 "사용자는 .forward 파일에 휴가 프로그램을 이미 수행중입니다.\n그것을 멈추고 .forward 파일에서 그것을 없애는 방법에 대해서는 설명서를 참조하십시오.\n그 문제를 해결한 후에 이 명령을 수행하십시오.\0"
105 ".vacation.msg 파일을 열 수 없습니다. -- 쓰기 사용 권한이 없습니다."
106 ".vacation.msg 파일이 이미 있습니다. 새 문자로 바꾸겠습니까?"
107 ".vacation.msg 파일을 열 수 없습니다. -- 쓰기 사용 권한이 없습니다."
108 "I am on vacation."
$ 	    /* NL_COMMENT
$ 	     * This is the default value of the subject field in the
$ 	     * message that gets returned to the sender when vacation
$ 	     * is turned on.
$ 	     */
109 "I'm on vacation.\nYour mail regarding \"$SUBJECT\" will be read when I return.\n"


$ 
$ Strings from dtmail/MsgScrollingList.C

110 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
111 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
112 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
113 "N"
$ /* NL_COMMENT
$  * In a mailer container window's message scrolling list, a "N" appears
$  * to the left of a mail message header indicating that the mail message
$  * is "new" (just arrived and not yet viewed by the user).
$  * There is only space to display 1 character.  If "N" needs to be translated,
$  * please make sure the translation is only 1 character.
$  */
114 "N"


$ 
$ Strings from dtmail/Undelete.C

115 "복원"
116 "닫기"

$ 
$ Strings from dtmail/SendMsgDialog.C

$ 	    /* NL_COMMENT
$            * Menu labels in Compose dialog (from SendMsgDialog.C).
$            * The following menu labels require translation plus parenthesized 
$            * mnemonics for all Asian locales. Please refer to the resource file 
$            * "Dtmail" for each mnemonics.
$ 	     * Message 117,121,122,125,127-129 are menu labels for "File" pull down menu.
$            * Message 130-134,139,140,155,156 are menu labels for "Edit" pull down menu. 
$            * Message 141,142,145,147-150,226 are menu labels for "Attachment" pull down menu. 
$            * Message 152-154,157 are menu labels for "Format" pull down menu. 
$            * Message 56-63 are menu labels for "Compose" pull down menu. 
$            * Message 64,65,221 are menu labels for "Move" pull down menu. 
$            * Message 66,68,69 are menu labels for "Attachment" pull down menu. 
$            * Message 71-77 are menu labels for "Help" pull down menu. 
$ 	     */
117 "보내기"
118 "닫기"
119 "새 메세지"
120 "우편 시스템"
121 "파일F"
122 "포함I..."
123 "우편 시스템 - 포함"
124 "포함"
125 "텍스트파일로 저장A..."
126 "우편 시스템 - 텍스트파일로 저장"
127 "메세지 기록L"
128 "보내기 형식n"
129 "닫기C"
130 "편집E"
131 "원래대로U"
132 "오려두기t"
133 "복사하기C"
134 "붙이기P"
135 "특수 붙이기"
136 "대괄호로 묶기"
137 "들여쓰기 표시"
138 "다시입력"
139 "없애기D"
140 "모두 선택S"
141 "별첨A"
142 "파일 붙이기F..."
143 "우편 시스템 - 더하기"
144 "더하기"
145 "새이름 저장A..."
146 "우편 시스템 - 별첨 - 새이름 저장"
147 "없애기D"
148 "없애기 취소U"
149 "이름 바꾸기R"
150 "모두 선택S"
$       /* NL_COMMENT
$        * This is an obsolete message.  It is replaced by message 226
$        * in set 1.
$        */
151 "구획 보기"
152 "형식r"
153 "줄내리기W"
154 "설정값S..."
155 "찾기/바꾸기F..."
156 "철자 검사k..."
157 "원형T"
158 "우편 시스템 - 별첨"
159 "우편 시스템 - 편집"
160 "새 메세지"
$       /* NL_COMMENT
$        * This is the label for a toggle item in a menu.  When the item
$        * is set to "Show List", the Attachment List is mapped in the
$        * Compose Window.  This message replaces message 151 in set 1.
$        */


$ 
$ Strings from dtmail/ViewMsgDialog.C

161 "복사하기C"
162 "모두 선택S"
163 "편집E"
164 "새이름 저장A..."
165 "우편 시스템 - 별첨 - 새이름 저장"
166 "모두 선택S"
167 "별첨A"
168 "우편 시스템 - 별첨"
169 "우편 시스템 - 텍스트"
170 "개요v..."
171 "작업T..."
172 "참조R..."
173 "항목O"
174 "도움말 사용U..."
175 "도움말H"
176 "우편 시스템에 관하여A"
177 "우편 시스템"


$ 
$ Strings from dtmail/DtMailGenDialog.C

$  /* NL_COMMENT
$   * 178 and 179 are obsolete messages, replaced by messages
178 "우편 시스템 - Dtmail에 관하여"
179 "Dtmail 버전 1.0"
180 "예"
181 "예"
182 "취소"

$ 
$ Strings from dtmail/FindDialog.C

183 "찾기"
$  /* NL_COMMENT
$   * This is an obsolete message.  Replaced by message 220 in set 1
$   */
184 "찾기와 모두 선택"
185 "다시입력"
186 "닫기"
187 "도움말"
188 "받는 사람:"
189 "보낸 사람:"
190 "제목:"
191 "참조:"
192 "우편 시스템 - 찾기"
193 "앞으로"
194 "뒤로"
$  /* NL_COMMENT
$   * This message replaces message 184 in set 1
$   */



$ 
$ Strings from dtmail/Editor.C

195 "------------- 전달된 메세지 시작 -------------\n\n"
196 "------------- 포함된 메세지 시작 ------------\n\n"
197 "------------- 전달된 메세지 종료 -----------\n\n"
198 "------------- 포함된 메세지 종료 ----------\n\n"

$ 
$ Strings from dtmail/XmTextEditor.C

199 "\n------------- 포함된 메세지 시작 -------------\n"
200 "\n------------- 포함된 메세지 종료 ------------\n"

$ 
$ Strings from dtmail/DtEditor.C

201 "\n------------- 포함된 메세지 시작 -------------\n"
202 "\n------------- 포함된 메세지 종료 ------------\n"

$ 
$ Strings from dtmail/ComposeCmds.C

203 "우편 시스템"
204 "작성 창을 만들 수 없습니다."
205 "우편 시스템"
206 "작성 창을 만들 수 없습니다."
207 "우편 시스템"
208 "작성 창을 만들 수 없습니다."
209 "우편 시스템"
210 "작성 창을 만들 수 없습니다."
211 "우편 시스템"
212 "해당 원형은 없습니다."
213 "우편 시스템"
214 "해당 원형은 손상된 것으로 나타납니다."
215 "우편 시스템"
216 "해당 원형을 로드할 메모리가 부족합니다."
217 "우편 시스템"
218 "해당 원형은 손상된 것으로 나타납니다."

$ 
$ Strings from dtmail/SortCmd.C

219 "분류..."

220 "모두 선택"
221 "수신함"

222 "%m/%d (%a) %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
223 "%m/%d (%a) %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
224 "%m/%d (%a) %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %k:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
225 "%m/%d (%a) %H:%M"
$ /* NL_COMMENT
$  * The "%a %b %d %H:%M" is the time and date format, please refer to 
$  * strftime man page for explanation of each format.
$  */
226 "목록 보기L"

$ String from Undelete.C, Deleted Messages window title
227 "메일러 - 없앤 메세지"

$ Strings from SendMsgDialog.C, Add Bcc, Delete Bcc menu buttons
228 "다음 더하기"
229 "다음 지우기"
230 "보내기"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line
$   * when searching for a matching message.
$   */
231 "찾는중임..."

$        /* NL_COMMENT
$         * These strings are displayed on the find dialog status line
$         * when one or more matching messages are found.  The first
$         * string is displayed when there is one matching message,
$         * and the second string is displayed when there is more than
$         * one.  The %d is the number of messages that matched.
$         */
232 "1개 메세지가 선택됨"
233 "%d개 메세지가 선택됨"

$  /* NL_COMMENT
$   * This string is displayed on the find dialog status line when
$   * no matching messages were found.
$   */
234 "찾을 수 없음"

$  /* NL_COMMENT
$   * These strings replace strings 178 and 179.  They are used in
$   * the "About Mailer" dialog box.
$   */
235 "메일러 - 메일러에 관하여"
236 "메일러 버전 1.0"

$set 2
1 "우편 시스템"
2 "ToolTalk가 초기화되지 않았습니다. 우편 시스템은 ToolTalk가 없으면 수행할 수 없습니다.\n/usr/dt/bin/dtsession을 수행해 보거나, 사용자의 시스템 관리자에게 연락하십시오."

3 "창을 초기화할 수 없습니다. 마치는 중입니다.\n"
4 "우편 시스템이 적절하게 설치되지 않았으며,\실행 그룹이 잘못 설정되었기 때문에 수행할 \n수 없습니다."
5 "사용자는 %s을(를) 열람하기 위한 사용 권한을 가지고 있지 않습니다."
$ 	    /* NL_COMMENT
$ 	     * The %s is the name of the mailbox the user doesn't have
$ 	     * permission to view.
$ 	     */
6 "우편함 %s은(는) 디렉토리이며 열 수 없습니다."
7 "%s을(를) 비울 수 없습니다. 그것이 없습니다."
8 "콘테이너 %s이(가) 비워졌습니다."
9 "오류 - %s을(를) 비울 수 없습니다."
10 "우편 시스템"
11 "%s"
12 "우편 시스템"
13 "우편 시스템"
14 "별첨은 \"새이름 저장\" 명령을 내서 파일에 저장하기 전에 \n선택해야 합니다."

15 "오류 - mailrc를 가져올 수 없습니다."
16 "메세지를 선택하지 않았습니다."
$ 	/* NL_COMMENT
$ 	 * No mail message has been selected by the user.
$ 	 */


17 "\"%s\"을(를) 편집했습니다. 삭제하겠습니까?"
18 "오류: 파일 %s을(를) 포함시킬 수 없습니다."
19 "별첨은 \"새이름 저장\" 명령을 내서 파일에 저장하기 전에 \n선택해야 합니다."


20 "별첨은 \"새이름 저장\" 명령을 내서 파일에 저장하기 전에 \n선택해야 합니다."

21 "우편 시스템"



$set 3
1 "자동 저장..."

2 "초기화중..."
3 "우편함 %s은(는) 존재하지 않습니다. 이 이름의 우편함을 만들겠습니까?"
4 "우편 시스템"
5 "예"
6 "우편함 %s은(는) 잠겨 있습니다.\n우편함을 수동으로 풀고 다시 해 볼 수 있습니다.\n또는 사용자의 시스템 관리자에게 연락하십시오."
7 "우편 시스템"
8 "예"
9 "예"
10 "예"
11 "예"
12 "%s"
13 "메세지 %d번 (전체%d개중), %d개는 새 메세지이며, %d개는 삭제되었습니다."
14 "메세지 %d번 (전체%d개중), %d개는 새 메세지이며, %d개는 삭제되었습니다."
$ 	/* NL_COMMENT
$ 	 * The user will see the following message display as:
$ 	 * "Message 3 of 10, 2 new, 6 deleted"
$ 	 * This means ??? -- Explain to translator.
$ 	 */
15 "저장중..."
16 "우편 시스템"
$ 		/* NL_COMMENT
$ 		 * This dialog comes up when the user tries to quit the
$ 		 * mailbox and the user is asked if he wants to destroy
$ 		 * the messages marked for deletion.
$ 		 */
$		/* NL_COMMENT
$		 * Messages 16 and 17 are no longer being used.  They are
$		 * being replaced by messages 86 and 87.
$		 */
17 "이 우편함에서 없애기 표시가 된 메세지를 \n완전히 없애겠습니까?"
18 "예"
19 "취소"
20 "우편함을 여는 중입니다...."
21 "%s은(는) 이미 있습니다.\n겹쳐쓰겠습니까?"
22 "우편 시스템"
23 "%s을(를) 겹쳐쓸 수 없습니다.\n파일 사용 권한을 점검하고 다시 해 보십시오."
24 "우편 시스템"
25 "콘테이너를 여는 중입니다...."
26 "폴더 요약 정보"
27 "로드중입니다..."
28 "비어있는 콘테이너"
29 "예"
30 "예"
31 "예"
32 "메세지를 완전히 없애는 중입니다...."
33 "예"

34 "%s은(는) 없습니다."
35 "%s을(를) 열 수 없습니다."
36 "메모리를 할당할 수 없습니다."
37 "별첨 요약"
38 "별첨"
39 "별첨들"
$ 	/* NL_COMMENT
$ 	 * "attachments" is the plural form of "attachment".
$ 	 */
40 "별첨들"
41 "없앰"

42 "%s은(는) 이미 있습니다. 바꾸겠습니까?"
43 "%s을(를) 바꿀 수 없습니다."
44 "%s을(를) 만들 수 없습니다."
45 "%s을(를) 만들 수 없습니다."


46 "비어있는 콘테이너"
47 "%s은(는) 이미 있습니다.\n겹쳐쓰겠습니까?"
48 "우편 시스템"
49 "%s을(를) 겹쳐쓸 수 없습니다.\n파일 사용 권한을 점검하고 다시 해 보십시오."
50 "우편 시스템"
51 "%s을(를) 만들 수 없습니다."
52 "우편 시스템"
53 "%s에 써넣을 수 없습니다."
54 "우편 시스템"
55 "%s을(를) 만들 수 없습니다."
56 "우편 시스템"
57 "별첨 이름 바꾸기"
58 "해당 편집 창은 창이 닫히면 \n없어지게 될 문자 또는 별첨을 \n포함하고 있습니다.\n편집 창을 닫겠습니까?"
59 "메모리 없음"
60 "기존 .vacation.msg 파일을 로드할 메모리가 부족합니다."
61 "우편 시스템"
62 "기존 .vacation.msg 파일이 손상된 것으로 나타납니다."


63 "옮길 메세지를 선택하십시오."
64 "복사할 메세지를 선택하십시오."
65 "%d개의 메세지를 %s(으)로 옮겼습니다."
66 "%d개의 메세지를 %s(으)로 옮겼습니다."
67 "%d개의 메새지를 %s(으)로 복사했습니다."
68 "%d개의 메새지를 %s(으)로 복사했습니다."
69 "열람이 이미 있습니다. 그것을 올리는 중입니다."
$ 	/* NL_COMMENT
$ 	* The current mail message selected is already displayed in a separate
$ 	* window.  Therefore this 'separate' window will be raised in front
$ 	* of existing windows so the user can see it.
$ 	*/



70 "dead-letter로 만드는 중입니다..."
71 "우편 시스템"
72 "예"
73 "취소"
74 "예"

75 "예"
76 "예"

77 "보관되지않은 변경사항을 가진 열려진 별첨이 있습니다.\n이 메세지를 보내게 되면 열려진 별첨과의 연결을 끊게될 우려가\n있습니다. 보관되지 않은 변경사항들은 메세지의 일부가 되지 않을것\n입니다. 새이름으로 저장하는 것을 이용하여 연결이\n끊어진후 변경사항들을 보관하실수 있으나, 그 변경사항들이 첨부의\n일부가 되지는 않을것입니다."
78 "우편 옵션들을 초기화하는 중임..."
79 "완전히 없애고 닫기"
80 "없애지 않고 종료"
81 "이 별첨에는 심각한 피해를 야기할수 있는 명령들을 포함하고 있을수도\n\있습니다.  실행하는것이 안전하다고 확신하실때에만 실행시키시기를 권장드립니다.  실행하는 것이 안전하다고 생각되시면 \"예\"를 누르시고, 실행을 취소하시려면 \"취소\"를 누르십시오."
82 "다른 사람이 이 우편함을 사용하고 있습니다.\n독점적인 액세스를 요청하시겠습니까?"
83 "메일러가 이 우편함에 대한 독점적인 액세스를 획득할수 없습니다.\n이 우편함을 읽기-전용으로 여시겠습니까?"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the plural form
$             * of the message that gets printed if more than one message
$             * is moved.
$             */
84 "%d개 메세지가 없어짐"

$            /* NL_COMMENT
$             * The following sentence means %d number of mail messages have
$             * been deleted from the mail folder.  This is the singular
$             * form of the message that gets printed if only one message
$             * is moved.
$             */
85 "%d개 메세지가 없어짐"
86 "새 우편 점검중..."
$		/* NL_COMMENT
$		 * This dialog comes up when the user tries to quit the
$		 * mailbox.  The user is asked if they want to destroy
$		 * the deleted messages.
$		 */
87 "메일러 - 닫기"
88 "없앤 메세지들을 완전히 없앤후 이 우편함을 닫을까요?"
89 "완전히 없앤후 닫기"
90 "현 상태에서 닫기"
$        /* NL_COMMENT
$         * Post a dialog explaining that the action was invalid
$         */
91 "틀린 활동을 실행할수 없음."
$        /* NL_COMMENT
$         * Post a dialog explaining that the action failed.
$         */
92 "활동 실행 실패!"
93 "선택된 아이콘 %s는 실행가능합니다.\n실행하시려면 \"예\"를 누르시고 취소하시려면 \"취소\"를 누르십시오."

94 "시스템이 응답하지 않기때문에 이 우편함에 대한 독점 액세스를\n획득할수 없습니다.\n\n이번에 한하여, 읽기-전용으로 또는 독점 액세스 없이\n읽기-쓰기용으로 여실수 있습니다 (다른 사람이 이 우편함을\n사용하고 있지 않을때에만 읽기-쓰기용으로 여십시오)."
95 "읽기-전용"
96 "읽기-쓰기"


$set 5
1 "우편 시스템"
2 "우편 시스템"
3 "이 메세지를 다른 이름으로 보내면\n       별첨에 대한 변경사항이\n     없어지게 됩니다."
$    /* NL_COMMENT
$     * The user tried to send a messages without saving changes in
$     * some open attachments.  This warning makes sure that is what
$     * the user intended.
$     */
4 "한 별첨만을 선택하고 나서\n        이름 바꾸기를 선택하십시오."
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
5 "메세지의 주소 중 일부가 틀리며 \n시스템 내의 알려진 사용자를 참조하지 않습니다.\n 모든 주소가 유효한지 확인하고 다시 해 보십시오."
$       /* NL_COMMENT
$        * Mailer ran out of memory.  Ask the user to quit some other
$        * applications so there will be more memory available.
$        */
6 "우편함에는 이 메세지를 보내는 데 사용할 만한 \n메모리가 부족합니다.\n다른 응용프로그램을 마치고 나서\n이 메세지를 다시 보내십시오."
$       /* NL_COMMENT
$        * There was an error from the mail transport (sendmail).
$        */
7 "사용자의 메세지를 보내는 중에 오류가 발생했습니다.\n해당 메세지를 받았는지 확인해 주십시오. 만약 받지 않았다면,\n이 메세지를 다시 보내야 할 수 있습니다."
$       /* NL_COMMENT
$        * User trying to send a message that has no addressed recipient.
$        */
8 "메세지의 수신인을 To:, Cc:, 또는 Bcc: 항목에 지정하신후 \n\메세지 \"보내기\"를 시도하십시오."

$set 12
1 "별첨"
2 "별첨"
3 "displayCount"
4 "다음 FIFO 파일을 붙일 수 없습니다. %s"
5 "다음 특수 문자 파일을 붙일 수 없습니다. %s"
6 "다음 디렉토리를 붙일 수 없습니다. %s"
7 "다음 특수 블럭 파일을 붙일 수 없습니다. %s"
8 "소켓 파일을 붙일 수 없습니다. %s"


$set 13
1 "만들 수 없습니다."
2 "쓸 수 없습니다."

$ 
$ Strings from dtmail/AttachCmds.C

$set 14
1 "별첨 더하기"
2 "%s을(를) 열 수 없습니다."
3 "다음 FIFO 파일을 붙일 수 없습니다. %s"
4 "다음 특수 문자 파일을 붙일 수 없습니다. %s"
5 "다음 디렉토리를 붙일 수 없습니다. %s"
6 "다음 특수 블럭 파일을 붙일 수 없습니다. %s"
7 "다음 소켓 파일을 붙일 수 없습니다. %s"
8 "%s을(를) 열 수 없습니다."
9 "우편 시스템 - 별첨 이름바꾸기"
10 "설명"
11 "별첨 새이름 저장"

$set 15
1 "저장되지 않은 변경사항들을 만드셨습니다.\n변경사항들을 저장하시거나, 변경사항을 무시하시거나, 또는\n문답상자에서 이전의 장소로 되돌아 가실수 있습니다."
2 "저장"
3 "무시"
