$ $XConsortium: dtscreen.msg /main/3 1995/12/08 09:35:56 rswiston $
$ @(#)25   1.1.1.1  com/XTOP/aixclients/xlock/xlock.msg, xclients, r5gos325, 9333325d 5/6/93 20:13:37
$ 
$ COMPONENT_NAME: dtscreen
$ 
$ FUNCTIONS: dtscreen.msg
$ 
$ 
$ (C) COPYRIGHT International Business Machines Corp. 1987, 1993
$ All Rights Reserved
$ Licensed Materials - Property of IBM
$ 
$ US Government Users Restricted Rights - Use, duplication or
$ disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
$ 
$quote "

$ 
$set 2
$ message file created 1993
1 "1386-101 %s:  잘못된 명령 행 선택사항 \"%s\"\n\n"
2 "1386-102 \n전체 설명을 보려면 %s -help를 입력하십시오.\n\n"
3 "1386-103 사용법:\n        %s [-options ...]\n\n\
        여기서 options으로는 다음과 같은 것들이 있습니다.\n"
5 "1386-105    %-28s %s\n\t 여기서, 모드는 다음 중 하나입니다.\n\", \"-mode mode\", \"animation mode"
7 "1386-107 알 수 없는 모드: "
10 "1386-110 할당할 수 없습니다. %s\n"
11 "1386-111 %d 픽셀을 할당했습니다.\n"
17 "1386-117 %s: 디스플레이 %s을(를) 열 수 없습니다.\n"
18 "1386-118 %s: GetResource - 메모리를 할당할 수 없었습니다."
19 "1386-119 %s: 틀린 양식의 -display 인수, \"%s\"\n"
20 "1386-120 -batchcount 인수는 양수이어야 합니다."
21 "1386-121 -saturation 인수는 0.0부터 1.0 사이의 수이어야 합니다."
25 "1386-125 %s: %d 화면밖에 지원할 수 없습니다.\n"
30 "1386-130 -delay 인수는 양수이어야 합니다."
35 "1386-135 다음을 할당할 수 없었습니다. %s. %s을(를) 대신 사용합니다.\n"
40 "%s: 그릴 창을 찾을 수 없습니다. -create 선택사항을 사용하면\n\
        %s이(가) 자체의 창을 만들게 됩니다.\n"
