$ $XConsortium: dttypes.msg /main/2 1996/07/24 18:58:23 drk $

$quote "


$set 1
1	"Dttype"
$ Do not Translate
2	"Dttype"
$ Do not Translate
3	"모두 초기화할 수는 없습니다.\n"
4	"NULL"
$ this should mean a "Empty string".
5	"=============== %s ===============\n"
$ Do not Translate
6	"\0"
$ Do not Translate
7	"%s\n"
$ Do not Translate
8	""
$ Do not Translate
9	"%s에서 로드되었습니다.%s\n"
10	"알 수 없음"
11	"\t%s"
$ Do not Translate
12	"\0"
$ Do not Translate
13	" :\t%s"
$ Do not Translate
14	"\0"
$ Do not Translate
15	"\n"
$ Do not Translate
16	"-db"
$ Do not Translate
17	"-w"
$ Do not Translate
18	"-l"
$ Do not Translate
19	"rec_info"
$ Do not Translate
20	"rec_name"
$ Do not Translate
21	"fld_name"
$ Do not Translate
22	"fld_value"
$ Do not Translate
23	"all"
$ Do not Translate
24	"오류 = %o, %s\n"
$ Translate "error" only
25	"사용법:  dttypes [-help]\n\tdttypes [-type filename]\n\tdttypes [-db database] [-w [rec_name regexp] [fld_name regexp]\n\t\t\t[fld_value regexp]]\n\t\t[-l [rec_name] [rec_info] [fld_name regexp] [fld_value]]\n"
$ Translate only the following: "filename" "database" "regexp"
26	"-type"
$ Do not Translate
27	"%s은(는) 유형 %s입니다.\n"
28	"$"
$ Do not Translate
29	"--------------------- %s ----------------\n"
$ Do not Translate
30	"유효하지 않은 데이타베이스\n"
31	"유효한 인수가 아닙니다.\n"
32	"-w 선택사항에 유효하지 않은 rec_info 필드\n"
$ do not translate "rec_info" or "-w"
33	"-w 또는 -l 선택사항에 없습니다.\n"
$ do not translate "-w" or "-l"
34	"알 수 없는 선택사항\n"
35	"-help"
$ Do not Translate
36	"정규식 %s에서의 오류\n"
