
$ "$XConsortium: dtwm.msg /main/3 1995/11/08 13:19:16 rswiston $";

$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        dtwm.msg
$ **
$ **  Project:     DT Workspace Manager (dtwm)
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the message catalog for dtwm
$ **
$ **
$ *****************************************************************************
$ **
$ ** (c) Copyright 1990, 1992, 1993, 1994 Hewlett-Packard Company
$ ** (c) Copyright 1994 International Business Machines Corp.
$ ** (c) Copyright 1994 Sun Microsystems, Inc.
$ ** (c) Copyright 1994 Novell, Inc.
$ **
$ **     All Rights reserved
$ **
$ *****************************************************************************
$ *************************************<+>*************************************

$ *************************************<L>*************************************
$ **  -----------------GENERAL LOCALIZATION NOTES SECTION---------------------
$ * Comment lines begin with a $ except $set which indicates the start of a
$ * new set.
$ *
$ * Do not delete any comments; you may add comments for your use.
$ *
$ * You don't need to localize the following sets:
$ *  sets 6, 8, 26, 28, 30, 32, 34, 38
$ *  sets 44, 46, 48, 54, 56, 70, 76, 99
$ *
$ * Please localize the following sets:
$ *  sets 16, 22, 29, 36, 40, 52, 60, 62, 82, 84, 86.
$ **  ----------------GENERAL LOCALIZATION NOTES SECTION END------------------
$ *************************************<L>*************************************

$set 6
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmBackdrop.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 배경 창을 만들지 못했습니다.

3 작업장 %2$s에 대한 이미지 %1$s을(를) 가져올 수 없었습니다.
4 배경 창을 위한 메모리 부족


$set 8
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmCDecor.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 클라이언트 창 지정을 위한 메모리 부족
2 클라이언트 창 지정을 위한 메모리 부족
3 클라이언트 창 지정을 위한 메모리 부족
4 클라이언트 창 지정을 위한 메모리 부족
5 클라이언트 창 지정을 위한 메모리 부족
6 클라이언트 창 지정을 위한 메모리 부족
7 클라이언트 창 지정을 위한 메모리 부족



$set 20
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmError.c --

$    This message goes to an error file. It is the name of component
$    reporting the error.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
1 작업장 관리자


$set 22
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmFeedback.c --

$    This is the message in the confirm dialog for toggling to and from
$         PM (Presentation Manager) behavior

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
2 로컬 메세지 문자열을 위한 메모리 부족

$    This is the message in the confirm dialog for restarting mwm
$ Do not localize "Mwm"
3 Mwm을 다시 시작하겠습니까?

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
5 로컬 문자열을 위한 메모리 부족

$    This is the message in the confirm dialog for quitting mwm
$ Do not localize "Mwm"
6 Mwm을 마치겠습니까?

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
8 로컬 문자열을 위한 메모리 부족

$    This is the message in the confirm dialog for logging out of DT Lite
$  You'll see it when pressing the Exit button from DT lite
9 로그아웃하겠습니까?

$    This is the message in the confirm dialog for restarting dtwm
10 작업장 관리자를 다시 시작하겠습까?

$    This is the message in the confirm dialog for quitting dtwm
11 작업장 관리자를 마치겠습니까?

$    This is the message in the confirm dialog for toggling to standard
$         PM (Presentation Manager) behavior from custom behavior
12 기본 작동으로 전환하겠습니까?

$    This is the message in the confirm dialog for toggling back from
$         PM (Presentation Manager) behavior to custom behavior
13 사용자 작동으로 전환하겠습니까?


$set 26
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmFunction.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 창 관리자가 다시 시작하지 못했습니다. 창 관리자 프로그램을 찾을 수 없거나\
실행할 수 없었습니다.
2 화면 %d을(를) 관리 해제하지 못했습니다.
3 창 관리자를 다시 시작하기 위한 메모리 부족
4 f.goto_workspace에 유효하지 않은 작업장 이름


$set 28
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmGraphics.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 그래픽 데이타를 위한 메모리 부족


$set 29
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmHelp.c --
$    Messages 1 and 2 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 1-2
1 항목 도움말이 실패했습니다. 다른 프로그램이 마우스를 잡았을 수 있습니다.
2 항목 도움말이 실패했습니다. 다른 프로그램이 마우스를 잡았을 수 있습니다.

$ Message 3 is an error message that appears when you are using Item Help
$ and select on something outside of the Workspace Manager
3 작업장 관리자 대화, 프론트 패널의 항목,\n\
또는 부속패널의 항목을 선택해야 합니다.

$ Message 4 is the title of the Help On Item Error dialog
4 작업장 관리자 - 항목 도움말 오류

$set 30
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIDecor.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 아이콘을 아이콘 상자로 가게 할 수 없었습니다.
2 아이콘을 만들기 위한 메모리 부족
3 아이콘을 만들기 위한 메모리 부족


$set 32
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIPC.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 메세지 서버와 연결할 수 없습니다.
2 배경 바꾸기를 처리하기 위한 메모리 부족
3 배경 바꾸기 요구에 경로 이름이 빠졌습니다.
4 배경 바꾸기 요구에 픽스맵 id가 빠졌습니다.


$set 34
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIPlace.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 아이콘 배치를 위한 메모리 부족
2 아이콘 배치를 위한 부족
3 아이콘 배치를 위한 부족
4 아이콘 상자 데이타를 만들기 위한 메모리 부족


$set 36
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmIconBox.c --

$    Messages 1 & 2 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 1 & 2.
1 아이콘 상자 데이타를 만들기 위한 메모리 부족
2 아이콘 상자 데이타를 만들기 위한 메모리 부족

$    This is the last menu item in the icon box menu.
$        This packs the icons together in the icon box. Only the
$        "PackIcons" and the "P" should be localized unless the
$        accelerator interferes with the local keyboard.
$        The accelerator is OSF standard for this item and should only be
$        changed if this accelerator would lock out a local key use.
$ 
$        The underbar
$        is part of the syntax for mnemonics and should not be changed.
$        The letter after the underbar should match a letter (case sensitive)
$        in the item title .
$        (e.g.   CompressIcons _C Alt Shift<Key>F7 f.pack_icons\n
$          OR
$                CompressIcons _I Alt Shift<Key>F7 f.pack_icons\n  )
$ 
$   The mnemonic should also be chosen such such that it does not
$        conflict with another mnemonic in the menu.

3 "아이콘 묶기P" _P  Alt Shift<Key>F7 f.pack_icons\n

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
4 아이콘 상자 데이타를 만들기 위한 메모리 부족


$set 38
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmImage.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 유효하지 않은 아이콘 비트맵
2 유효하지 않은 아이콘 비트맵
3 아이콘 이미지의 꼭지점을 자르기 위한 메모리 부족
4 아이콘 이미지의 꼭지점을 자르기 위한 메모리 부족
5 비트맵 %s을(를) 위한 메모리 부족\n
6 비트맵 %s을(를) 위한 메모리 부족\n
7 비트맵 파일 %s을(를) 읽을 수 없습니다.\n
8 유효하지 않은 비트맵 파일 %s\n
9 이 화면에서는 아이콘 비트맵을 사용할 수 없습니다.
10 색상 아이콘 픽스맵은 지원되지 않습니다.
11 %s은(는) 유효하지 않은 아이콘 파일 형식으로 되어 있습니다.\n\
    파일을 검토하여 다른 아이콘 파일과 비교해 보십시오.

$set 40
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmInitWs.c --

$    Messages 1-13 and 15,17 and 19-21 go to an error file.
$ DO NOT LOCALIZE MESSAGES 1 THROUGH 13.
1 Could not open display.
2 Insufficient memory for Screen data
3 Another window manager is running on screen %d
4 Could not open second display connection.
5 Unable to manage any screens on display.
6 Cannot configure X connection
7 Cannot create enough memory for the screen names
8 Insufficient memory for Workspace data
9 Insufficient memory for displayString
10 Insufficient memory for window manager data
11 Insufficient memory for window manager data
12 Insufficient memory for screen names
13 Insufficient memory for screen names

$     This is the default title for the icon box
14 아이콘

$    Message 15 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
15 로컬 메세지 문자열을 위한 메모리 부족

$    Message 17 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
17 로컬 메세지 문자열을 위한 메모리 부족

$    Message 19 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
19 로컬 메세지 문자열을 위한 메모리 부족

$    Message 20 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
20 %1$s: 구성 파일 %4$s의 줄 %3$d에 있는 %2$s\n

$    Message 21 goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE
21 %1$s: 사양 문자열의 줄 %3$d에 있는 %2$s\n

$     This is the default title for the version dialog
22 작업장 관리자에 관하여

$     This is the default title for the Dtwm help dialog
23 작업장 관리자 - 도움말

$     This is the default title for the Generic help dialog
24 작업장 관리자 - 도움말


$set 44
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmMain.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 
2 창 관리자의 이름을 위한 메모리 부족


$set 46
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmManage.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 초기 클라이언트에 적응하기 위한 메모리 부족


$set 48
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmMenu.c --
$    This entire set is written to an error file
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 메뉴 사양 %s이(가) 없습니다.\n
2 메뉴 %s을(를) 위한 메모리 부족\n
3 메뉴 %s을(를) 위한 메모리 부족\n
4 메뉴 사양 %s이(가) 없습니다.\n
5 %s에 대한 메뉴 순환이 검출되었습니다.\n
6 메뉴 %s을(를) 위한 메모리 부족\n
7 메뉴 %s을(를) 위한 메모리 부족\n
8 메뉴 사양 %s이(가) 없습니다. 내부 메뉴를 사용합니다.\n


$set 52
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmPresence.c --
$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
1 표시할 작업장 대화를 만들 수 없습니다.

$    This tells what window the occupy workspace dialog is operating on.
2 창:

$    This is the label for the workspace list in the occupy workspace dialog
3 작업장:

$    This is the label for the button to put a window in all workspaces
$        from the occupy workspace dialog
4 모든 작업장

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
5 표시할 작업장 대화를 만들기 위한 메모리 부족.

$    This tells what window the occupy workspace dialog is operating on.
6 아이콘:




$set 54
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmProperty.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 창 관리 데이타를 위한 메모리 부족
2 창 관리 데이타를 위한 메모리 부족
3 창 관리 데이타를 위한 메모리 부족
4 창 관리 플래그를 위한 메모리 부족


$set 56
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmProtocol.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 창 관리 데이타를 위한 메모리 부족
2 _MOTIF_WM_QUERY_nn을 XInternAtom하기 위한 메모리 부족
3 _MOTIF_WM_QUERY_nn 선택을 갖지 못했습니다.
4 _MOTIF_WM_QUERY_nn 선택을 하지 못했습니다.
5 _MOTIF_WM_QUERY_nn 선택을 변환하기 위한 메모리 부족


$set 60
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmResParse.c --
$    Messages 1-39 are written to an error file.
$    YOU DO NOT NEED TO LOCALIZE MESSAGES 1-39, 41.
$ 
$    Message 40 allows you to alter the labels for the modifier
$    keys on the menu accelerators. You may wish to localize
$    message 40 so that these labels match the keycaps on your
$    local keyboard.
$ 
1 세션 기하 항목을 위한 메모리 부족
2 세션 항목의 작업장 목록을 위한 메모리 부족
3 CommandArgv 배열을 위한 메모리 부족
4 CommandArgv 항목을 위한 메모리 부족
5 Dt 세션 힌트를 위한 메모리 부족
6 구성 파일을 열 수 없습니다.
7 메뉴 가속 키를 위한 메모리 부족
8 이름 %s의 프론트 패널을 만들 수 없습니다.\n
9 메뉴를 위한 메모리 부족
10 메뉴를 위한 메모리 부족
11 메뉴 이름 뒤에는 '{'가 와야 했습니다.
12 메뉴 항목을 위한 메모리 부족
13 메뉴 항목을 위한 메모리 부족
14 유효하지 않은 연상 사양
15 가속 키 사양을 위한 메모리 부족
16 유효하지 않은 가속 키 사양
17 메모리 부족
18 그룹 사양이 빠졌습니다.
19 유효하지 않은 그룹 사양
20 유효하지 않은 번호 사양
21 단추 세트 이름 뒤에는 '{'가 와야 했습니다.
22 단추 사양을 위한 메모리 부족
23 유효하지 않은 단추 사양
24 유효하지 않은 단추 문맥
25 키 세트 이름 뒤에는 '{'가 와야 했습니다.
26 키 사양을 위한 메모리 부족
27 유효하지 않은 키 사양
28 유효하지 않은 키 문맥

31 화면 이름을 위한 메모리 부족
32 화면 이름을 위한 메모리 부족

33 %1$s: 구성 파일 %4$s의 줄 %3$d에 있는 %2$s\n
34 %1$s: 사양 문자열의 줄 %3$d에 있는 %2$s\n

35 구성 파일 변환을 위한 메모리 부족
36 다음 포함 파일을 처리하기 위한 메모리 부족: %s
37 '{'가 와야 했습니다.
38 세션 항목의 호스트 이름을 위한 메모리 부족
39 구성 파일 %s을(를) 다시 열 수 없었습니다.

$ Message 40 is used to remap the menu accelerator
$ modifier key labels to the keycaps that the user sees on the
$ local keyboard. If modifier key labels are not remapped, then
$ the key label used in the accelerator spec will appear on
$ the menu
$ 
$ Example: menu spec in dtwmrc file
$       "Close"                 _C   Alt<Key>F4      f.kill
$ 
$ Appears as
$         Close       Alt+F4
$         -                  (the 'C' in Close is underlined)
$ 
$ if message 40 doesn't remap "Alt" then accelerator text is "Alt+F4"
$ if message 40 is "Alt XYZ" then accelerator text is "XYZ+F4"
$ 
$ The format of this message is a sequence of strings separated
$ by spaces. The strings are taken in pairs. If the first string
$ in a pair matches a accelerator key label, the second string
$ appears in its place on the menu. There must be an even number
$ of strings. The case of the first string does not matter. The
$ case of the second string is preserved.
$ 
40 

$ 
$    Messages 41 is written to an error file.
$    YOU DO NOT NEED TO LOCALIZE MESSAGE 41.
$ 
41 LANG 환경 변수를 얻기 위한 메모리 부족

$set 62
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmResource.c --

$    Messages 1, 3, 5, 7, 9, 11, 13, 15, 17 and 19 are menu items in the
$         built in menu. Only the title and mnemonic should be localized,
$         never change the underbar.  For example in message 1,
$        "Restore" and the "R" may be localized.  The underbar
$        is part of the syntax for mnemonics and should not be changed.
$        The letter after the underbar should match a letter (case sensitive)
$        in the item title.
$        (e.g.   Normalize  _N  )

$ Messages 1, 3, 5, 7, 9, 11, 13, 15, 17 and 19 are not used.
$ Messages 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 to 29, 31, 33 to 38, 66-68,
$          go to an errorlog and do NOT need to be localized.
$ Messages 30 and 39-47 are not used.
$ Only messages 32, 48-57 and 59 need to be localized.

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
2 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
4 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
6 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
8 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
10 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
12 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
14 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
16 로컬 기본 메뉴를 위한 메모리 부족

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
18 로컬 기본 메뉴를 위한 메모리 부족

$    Messages 20 to 29 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 20 TO 29.
20 로컬 기본 메뉴를 위한 메모리 부족
21 지역화한 기본 시스템 메뉴를 위한 메모리 부족
22 색상 데이타를 위한 메모리 부족
23 글꼴을 로드하지 못했습니다. %.100s
24 작업장 데이타를 위한 메모리 부족
25 유효하지 않은 작업장 이름: "%s"
26 중복 작업장 이름: "%s"
27 작업장 데이타를 위한 메모리 부족
28 데이타 자원을 위한 메모리 부족
29 글꼴을 로드하지 못했습니다. %.100s

$    This message goes to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS MESSAGE.
31 로컬 메세지 문자열을 위한 메모리 부족

$    This is the default title of the "Rename Workspace" dialog
32 작업장 이름바꾸기

$    Messages 33 to 38 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 33 TO 38.
33 로컬 메세지 문자열을 위한 메모리 부족
34 색상을 가져올 수 없습니다.
35 색상을 가져올 수 없습니다.
36 색상을 가져올 수 없습니다.
37 창 관리 데이타를 위한 메모리 부족
38 창 관리 데이타를 위한 메모리 부족

$ Messages for the built in menu.  The built in menu will
$ appear unless the user (through resources and app-defaults)
$ specified a custom window menu.

$ Messages 48-57 are the definitions for the default built in
$ window menu.  These new messges allow the localizer to change the
$ accelerators if they interfere with the local keyboard.  The only item
$ that has an accelerator is Close _C Alt<Key>F4 f.kill.

$ The underbar is part of the syntax for mnemonics and should not
$ be changed. The letter after the underbar should match a
$ letter (case sensitive) in the item title and should not conflict
$ with another mnemonic.
$        (e.g.   Normalize  _N  )

$ The name of the function (e.g. f.normalize) should not change

$    This item will "close" the window.  This usually results in the
$    window being withdrawn.
48 닫기C _C Alt<Key>F4 f.kill

$    This item normalizes a window
49 이전 상태로R _R  f.restore

$    This item moves a window
50 옮기기M _M  f.move

$    This item resizes a window
51 크기 바꾸기S _S  f.resize

$    This item changes a window into an icon
52 아이콘으로n _n  f.minimize

$    This item makes a window as large as allowed (determined by a number
$         of factors)
53 가장 크게x _x  f.maximize

$    This item lowers a window below other windows
54 뒤로 보내기L _L  f.lower

$    This item brings up the occupy workspace dialog.  The character
$    sequence  "\\.\\.\\."  will appear as "..." in the menu . DO NOT CHANGE
$    THE  "\\.\\.\\."  CHARACTERS
55 표시할\\ 작업장O\\.\\.\\. _O  f.workspace_presence

$    This item puts a window into all workspaces.  The character sequence
$    "\\" provides a space between "Occupy" and "all"  Use this sequence
$    to provide spaces in item titles.
56 모든\\ 작업장에\\ 표시A _A  f.occupy_all

$    This item removes a window from a workspace.  This item will appear in
$    in the menu as  "Unoccupy Workspace"  with the first e in the title underlined
$    to indicate this is a mnemonic for this item.
57 작업장\\표시\\ 지우기U _U  f.remove

$    This is the default title of the "occupy workspace" dialog
59 표시할 작업장

$    The following 6 items are Sun-specific.  The only difference being
$    that these items have accelerators.  They should be localized
$    similarly to their corresponding item above.

60 이전 상태로R _R Alt<Key>F5 f.restore
61 옮기기M _M  Alt<Key>F7   f.move
62 크기 바꾸기S _S  Alt<Key>F8   f.resize
63 아이콘으로n _n  Alt<Key>F9 f.minimize
64 가장 크게x _x  Alt<Key>F10 f.maximize
65 뒤로 보내기L _L  Alt<Key>F3   f.lower

$    Messages 66 to 68 go to an error file.
$ YOU DON'T NEED TO LOCALIZE MESSAGES 66 TO 68.
66 자동 화면 떠오름 지연 자원값이 범위를 넘었습니다. 음수가 아니여야 합니다.
67 키 묶기 %s을(를) 찾을 수 없습니다. 내장된 키 묶기를 사용합니다.
68 단추 묶기 %s을(를) 찾을 수 없습니다. 내장된 단추 묶기를 사용합니다.

$set 70
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmWinInfo.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 클라이언트 데이타를 위한 메모리 부족
2 클라이언트 데이타를 위한 메모리 부족
3 아이콘 상자를 만들 수 없었습니다.
4 프론트 패널을 만들 수 없었습니다.
5 창 관리자가 %.100s 특성을 clientTitle/iconTitle: XmbTextPropertyToTextList로 변환할 수 없었습니다.
6 %.100s 특성을 clientTitle/iconTitle: XmbTextPropertyToTextList로 변환할 메모리가 부족합니다.
7 [XmbTextPropertyToTextList]:\n     로케일 (%.100s)이 지원되지 않습니다. ($LANG을 점검하십시오).
8 창 관리자가 알 수 없는 특성을 clientTitle/iconTitle: %.100s(으)로 받았습니다. 특성이 무시됩니다.


$set 76
$    THIS COMMENT FOR DTWM TEAM ONLY -- WmWrkspace.c --
$    This entire set is written to an error file.
$ YOU DON'T NEED TO LOCALIZE THIS SET.
1 표시할 작업장 특성을 위한 메모리 부족
2 표시할 작업장 특성을 위한 메모리 부족
3 작업장 정보를 갱신할 메모리 부족
4 클라이언트 데이타를 위한 메모리 부족
5 메모리 부족 (ConvertNamesToIDs)
6 메모리 부족 (ConvertNamesToIDs)
7 메모리 부족
8 메모리 부족 (ConvertNamesToIDs)
9 작업장에 창을 추가하기 위한 메모리 부족
10 메모리 부족 (GetLeaderPresence)
11 메모리 부족
12 자원을 저장할 메모리 부족
13 자원을 저장할 메모리 부족
14 최대 작업장 수는 %d입니다. 새 작업장이 만들어지지 않았습니다.


$set 82
$    THIS COMMENT FOR DTWM TEAM ONLY -- PopupMenu.c --
$    This entire set should be localized.

$ Message 1 is the title of the Delete Locked Control Error dialog
1 작업장 관리자 - 잠긴 조절도구 없애기 오류

$ Message 2 is the title of the Delete Control dialog
2 작업장 관리자 - 조절도구 없애기 

$ Message 3 is the title of the Delete Locked Subpanel Error dialog
3 작업장 관리자 - 잠긴 부속패널 없애기 오류

$ Message 4 is the title of the Delete Subpanel dialog
4 작업장 관리자 - 부속패널 없애기 

$ Message 5 is the message in the Delete Locked Control Error dialog
5 이 조절도구는 잠겼기 때문에 삭제할 수 없습니다.

$ Message 6 is the message in the Delete Control dialog
6 이 조절도구를 확실히 삭제하겠습니까?

$ Message 7 is the message in the Delete Locked Subpanel Error dialog
7 이 부속패널은 잠겼기 때문에 삭제할 수 없습니다.

$ Message 8 is the message in the Delete Control dialog when more than
$ exits in the subpanel to be deleted.
8 이 부속패널은 둘 이상의 조절도구를 포함하고 있습니다.\n이 부속패널을 확실히 삭제하겠습니까?

$ Message 9 is the message in the Delete Control dialog when only the
$ copy of the main panel control exists in the subpanel.
9 이 부속패널을 확실히 삭제하겠습니까?

$ Message 10 - 19 are the menu title, menu items, and mnemonics in the
$ Main/Subpanel Menu.
$ 
$ The entries are paired (label + mnemonic). The label appears in the
$ menu. The mnemonic is the character in the label that is underlined by
$ the menu system indicating that it is a keyboard shortcut.
$ 
$ The mnemonic must be a character in the label. Each mnemonic must be
$ unique within this particular menu.
$ 
10 부속패널 더하기A
11 A
12 부속패널 없애기D
13 D
14 기본 패널로 복사하기C
15 C
16 없애기D 
17 D
18 도움말H
19 H

$ Message 20 - 21 are used in the menu title for the workspace button
$ menus.  20 is used for the format "Workspace <Name>".  21 is the first
$ arg in the format.
20 %1$s %2$s
21 작업장

$ Message 22 - 30 are the menu title, menu items, and mnemonics in the
$ Switch Menu.
$ 
$ The entries are paired (label + mnemonic). The label appears in the
$ menu. The mnemonic is the character in the label that is underlined by
$ the menu system indicating that it is a keyboard shortcut.
$ 
$ The mnemonic must be a character in the label. Each mnemonic must be
$ unique within this particular menu.
$ 
22 영역 전환
23 작업장 더하기A
24 A
25 없애기D
26 D
27 이름 바꾸기R
28 R
29 도움말H
30 H

$ Message 31 - 40 are the pieces for the deletion dialogs
31 조절도구 없애기:
32 이 조절도구를 삭제하면, \"아이콘 설치\" 놓기 영역을\n사용하여 복원할 수 없습니다.\n\n응용프로그램 관리자의 \"RestorePanel\"을 사용하면 \n이 조절도구를 나중에 되살릴 수 있습니다.\n\n이 조절도구를 삭제하겠습니까?
33 부속패널 없애기:
34 이 부속패널을 삭제하면, \"아이콘 설치\" 놓기 영역을 \n사용하여 해당 부속패널에 포함된 모든 조절도구를 \n복원할 수 없습니다.\n\n응용프로그램 관리자의 \"RestorePanel\"을 사용하면 \n이 부속패널과 그것의 조절도구들을 나중에 되살릴 수 있습니다.\n\n이 부속패널을 확실히 삭제하겠습니까?

$ Used for the name of a newly created workspace.
35 새 작업장

$ Used for Install Icon title in Install Icon popup menu.
36 아이콘 설치


$set 84
$    THIS COMMENT FOR DTWM TEAM ONLY -- UI.c --
$    This entire set should be localized.
$ 
$ Message used for the label of the dynamic install area.
1 아이콘 설치


$set 86
$    THIS COMMENT FOR DTWM TEAM ONLY -- Callback.c --
$    This entire set should be localized.

$ The next two messages are used for workspace naming errors
1 작업장 관리자 - 이름 바꾸기 오류
2 유효하지 않거나 중복된 작업장 이름입니다.

$ The next three messages are used for the dynamical install error dialog.
3 작업장 관리자 - 아이콘 설치 오류
4 아이콘 설치:

$ Messages 5 and 6 are old. They are replaced by messaged 8 and 9.
5 이 이름의 아이콘이 이미 있습니다.
6 조절도구 활동 오류

7 파일을 찾을 수 없습니다.
8 이 이름의 아이콘이 이미 있습니다.
9 작업장 관리자 - 아이콘 활동 오류


$set 99
$    DO NOT TRANSLATE THESE MESSAGES
$    DO NOT CHANGE THESE MESSAGES
$    DO NOT LOCALIZE THESE MESSAGES
$    These messages are used for the version information.
1 @(#)version_goes_here
2 \n@(#)_DtMessage catalog source $XConsortium: dtwm.msg /main/3 1995/11/08 13:19:16 rswiston $
