$ +SNOTICE
$ 
$      $TOG: libDtMail.msg /main/4 1997/10/31 15:39:02 rafi $
$ 
$      RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$      The information in this document is subject to special
$      restrictions in a confidential disclosure agreement bertween
$      HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$      document outside HP, IBM, Sun, USL, SCO, or Univel wihtout
$      Sun's specific written approval.  This documment and all copies
$      and derivative works thereof must be returned or destroyed at
$      Sun's request.
$ 
$      Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ @(#)libDtMail.msg    1.8 03 Nov 1994
$set 1 libDtMail API set
1 오류가 발생하지 않았습니다.
2 유효한 Bento 오브젝트를 갖지 않은 메세지를 사용했습니다.
3 적절하게 만들어지지 않은 오브젝트를 사용했습니다.
4 오브젝트를 만들 수 없었습니다.
5 오브젝트에 대한 값을 찾을 수 없었습니다.
6 해당 작동을 수행하기 위한 메모리가 충분하지 않습니다.
7 잘못된 인수가 작동에 대한 매개변수로 전달되었습니다.
8 이미 초기화된 오브젝트를 초기화하려 했습니다.
9 요구한 파일이 없습니다.
10 요구한 파일은 이 구현에서 인식되는 형식의 우편함이 아닙니다.
11 DtMail에 대한 메세지 카탈로그가 없습니다.
12 오류 구조가 유효하지 않습니다.
13 값이 내장된 콘테이너이고 읽기 위해 열려져야 합니다.
14 다른 우편 프로그램이 폴더에 대한 쓰기 권한을 가지고 있습니다.
15 ToolTalk 메세지를 처리할 수 없습니다.
16 작동 서버가 해당 요구를 거부했습니다.
17 사용자가 해당 작동을 중단했습니다.
18 오브젝트를 사용할 수 없습니다.
19 요구한 파일을 만들 수 없습니다.
20 해당 작동을 수행하는 중에 내부 오류가 발생했습니다.
21 요구한 작동은 현재 오브젝트에서 지원되지 않습니다.
22 이동 유형에 맞는 데이타 유형이 없습니다.
23 사용자가 변환을 가로챘습니다.
24 우편 라이브러리가 구현되지 않았습니다.
25 지정한 구현이 없습니다.
26 지정한 구현이 요구한 작동을 수행할 수 없습니다.
27 현재 구현에서는 해당 작동이 지원되지 않습니다.
28 데이타 유형이 라이브러리에 알려지지 않습니다.
29 지정한 우편 주소를 처리할 수 없습니다.
30 우편 배달 이동이 실패했습니다.
31 MD5 서명이 메세지 내용과 맞지 않습니다.
32 유효한 수행 그룹은 "mail"이 아닙니다.

$ 
$ Strings from libDtMail/Common/DtMailValuesBuiltin.C

$set 2
1 "%C"
$ /* NL_COMMENT
$  * The %C is the time and date format, please refer to strftime man page for
$  * explanation of each format.
$  */
