$ 
$ +SNOTICE
$ 
$  $XConsortium: MotifApp.msg /main/3 1995/11/08 13:13:38 rswiston $
$ 
$  RESTRICTED CONFIDENTIAL INFORMATION:
$ 
$  The information in this document is subject to special
$  restrictions in a confidential disclosure agreement between
$  HP, IBM, Sun, USL, SCO and Univel.  Do not distribute this
$  document outside HP, IBM, Sun, USL, SCO, or Univel without
$  Sun's specific written approval.  This document and all copies
$  and derivative works thereof must be returned or destroyed at
$  Sun's request.
$ 
$  Copyright 1993 Sun Microsystems, Inc.  All rights reserved.
$ 
$ +ENOTICE
$ 

$ -------------------------------------
$ MotifApp/Application.C
$ 

$quote "

$ -------------------------------------
$ MotifApp/AskFirstCmd.C
$ 

$quote "


$set 1
1 "이 명령을 실행하겠습니까?"
$ -------------------------------------
$ MotifApp/DialogManager.C
$ 

$quote "


2 "예"
3 "취소"
$ -------------------------------------
$ MotifApp/Help.C
$ 

$quote "


4 "DtMail 버전 대화"
5 "DtMail 버전 대화"
6 "사용중인 응용프로그램의 구성 요소를 선택해야 합니다.\n"

$ Messages 7 and 8 are no longer used.  They are both
$ replaced by message 9.

7 "DtMail 도움말"
8 "DtMail 도움말"


$quote "


9 "이 폴더를 닫겠습니까?"
$ -------------------------------------
$ MotifApp/WarnNoUndoCmd.C
$ 

$quote "


10 "이 명령을 취소할 수 없습니다. 계속하겠습니까?"
11 "숨은 폴더 및 파일 보기"

$quote "

$ /* NL_COMMENT
$  * This message replaces messages 7 and 8.
$  */
12 "메일러 : 도움말"

$set 2
1 "선택 오류, 계속할 수 없습니다.\n"
2 "사용자가 선택을 중단했습니다.\n"
$ -------------------------------------
$ MotifApp/QuitCmd.C
$ 

