$ $XConsortium: Mrm.msg /main/3 1996/10/19 14:47:45 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 
$ (c) Copyright 1996 Digital Equipment Corporation.
$ (c) Copyright 1996 Hewlett-Packard Company.
$ (c) Copyright 1996 International Business Machines Corp.
$ (c) Copyright 1996 Sun Microsystems, Inc.
$ (c) Copyright 1996 Novell, Inc. 
$ (c) Copyright 1996 FUJITSU LIMITED.
$ (c) Copyright 1996 Hitachi.
$ 

$ This message catalog contains messages issued by Motif Mrm library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.

$quote "

$set MS_Mrm

MSG__0000 "Falló la asignación del vector"

MSG__0001 "Falló la asignación de memoria intermedia"

MSG__0002 "Memoria intermedia no válida"

MSG__0003 "Falló la obtención del bloque"

MSG__0004 "Falló la colocación del bloque"

MSG__0005 "Anotación de encabezamiento no válida"

MSG__0006 "Contexto no válido"

MSG__0007 "Datos introducidos no válidos"

MSG__0008 "Segmento introducido no válido"

MSG__0009 "Tipo de datos introducidos no válidos"

MSG__0010 "Tipo de anotación inesperado"

MSG__0011 "La versión de archivo %s es mayor que la versión de Mrm %s."

MSG__0012 "Esta no es la anotación del encabezamiento."

MSG__0013 "El índice de recursos está fuera de intervalo"

MSG__0014 "Puntero de datos NULL"

MSG__0015 "Anotación de desbordamiento no válida"

MSG__0016 "La anotación GT no coincide"

MSG__0017 "La anotación LT no coincide"

MSG__0018 "Tipo inesperado de anotación madre"

MSG__0019 "La anotación se encuentra después de EOF"

MSG__0020 "No se puede intercambiar la anotación #%d de tipo %d"

MSG__0021 "Se encontró el tipo %d no implementado en el elemento de devolución de llamada %d"

MSG__0022 "Se encontró un tipo %d de argumento no implementado"

MSG__0023 "Identificación de jerarquía NULL"

MSG__0024 "Jerarquía no válida"

MSG__0025 "Módulo de interfaz no válido"

MSG__0026 "Anotación de widget no válida"

MSG__0027 "Falló la asignación de contexto"

MSG__0028 "Falló la validación"

MSG__0029 "El tamaño del recurso es demasiado grande"

MSG__0030 "La pantalla no se ha abierto todavía"

MSG__0031 "No se pudo abrir el archivo %s"

MSG__0032 "No se pudo abrir el archivo %s. La versión del archivo UID no coincide."

MSG__0033 "XmGetPixmap falló con XmUNSPECIFIED_PIXMAP para %s"

MSG__0034 "XCreateImage falló durante la conversión de IconImage"

MSG__0035 "XCreatePixmap falló durante la conversión de IconImage"

MSG__0036 "XCreateGC falló durante la conversión de IconImage"

MSG__0037 "XtMalloc falló durante la conversión de IconImage"

MSG__0038 "No se ha podido cargar el color '%s'"

MSG__0039 "No se pudo convertir el color o pixel RGB '%d,%d,%d'"

MSG__0040 "Tipo de descriptor de color no válido"

MSG__0041 "Elemento de color no válido en el estado monocromático %d"

MSG__0042 "No se puede encontrar '%s' literal"
$ literal in this context means a named value.

MSG__0043 "Contexto de recurso no válido"

MSG__0044 "Demasiados widgets"

MSG__0045 "El índice que se encuentra más arriba está fuera de límites"

MSG__0046 "Falló la asignación de lista"

MSG__0047 "Falló la asignación del vector de lista"

MSG__0048 "Falló la reasignación del vector"

MSG__0049 "Falló la asignación de la cadena"

MSG__0050 "El archivo UID es obsoleto ya que no contiene ninguna compresión de tabla"

MSG__0051 "No se pudo encontrar el descriptor de la clase %s"

MSG__0052 "No se puede encontrar el widget indexado '%s'"

MSG__0053 "No se puede encontrar el widget RID '%x'"

MSG__0054 "?? Tipo de clave UNKNOWN %d"

MSG__0055 "Variedad de widget desconocida"

MSG__0056 "Referencia de widget no resuelta en la creación de la devolución de llamada"

MSG__0057 "No se pudieron reparar las devoluciones de llamada de creación"

MSG__0058 "Tipo de hijo desconocido"

MSG__0059 "No se encontró el hijo del padre"

MSG__0060 "La referencia del widget no está indexada"

MSG__0061 "No se pudo convertir el color o pixel '%s'"

MSG__0062 "No se pudo descomprimir el código de cadena %d"

MSG__0063 "Grupo de recursos no manipulado"

MSG__0064 "No se pudo convertir ASCIZ '%s' en cadena compuesta"

MSG__0065 "No se pudo efectuar el análisis sintáctico de la tabla de conversión '%s'"

MSG__0066 "No se pudo convertir el identificador '%s'"

MSG__0067 "Error interno: se encontró el caso MrmRtypeIconImage"

MSG__0068 "Error interno: se encontró el caso MrmRtypeXBitmapFile"

MSG__0069 "Error interno: no se pudo convertir la pantalla en cadena"

MSG__0070 "No se pudo convertir el font '%s'"

MSG__0071 "No se pudo convertir fontset '%s'"
$ please do not translate fontset.

MSG__0072 "No se pudieron abrir fonts del fontset '%s'"

MSG__0073 "No se pudo añadir el font '%s' de fontset a la lista"

MSG__0074 "No se pudo añadir el fontset '%s' de la lista de fonts a la lista"

MSG__0075 "No se pudo convertir el nombre de la anotación de la clase '%s'"

MSG__0076 "No se pudo convertir la cadena keysym '%s' en KeySym"

MSG__0077 "No se puede encontrar el valor literal indexado '%s'"

MSG__0078 "No se puede encontrar el RID literal '%x'"

MSG__0079 "Tipo de clave literal %d desconocido"

MSG__0080 "Tipo de ColorTable %d no válido"

MSG__0081 "Código de tipo ColorTable %d no válido"

MSG__0082 "Tipo de valor literal de color %d no válido"

MSG__0083 "Código de tipo ColorItem %d no válido"

MSG__0084 "La rutina '%s' de devolución de llamada no está registrada"

MSG__0085 "La referencia del widget no está indexada"

MSG__0086 "No se puede encontrar el recurso widget '%s' indexado"

MSG__0087 "No se puede encontrar el recurso widget RID '%x'"

MSG__0088 "Tipo de clave de recurso %d desconocido"

MSG__0089 "No se pudieron crear casos del árbol de widgets"

MSG__0090 "Nombre nulo de clase definida por el usuario"

MSG__0091 "Código de clase no válido"

MSG__0092 "Demasiados argumentos"

MSG__0093 "Código de compresión no válido"

MSG__0094 "Tipo no válido o no procesado"

MSG__0095 "El vector es demasiado grande"

MSG__0096 "Nombre de rutina vacío"

MSG__0097 "Char8Vector todavía no está implementado"

MSG__0098 "CStringVector todavía no está implementado"

MSG__0099 "Demasiados hijos"

MSG__0100 "Descriptor de lista de hijos nulo"

MSG__0101 "El índice del hijo está fuera de límite"

MSG__0102 "Indice nulo"

MSG__0103 "Tipo de clave no válido"

MSG__0104 "El índice del argumento está fuera de límite"

MSG__0105 "Anotación de widget/gadget no válida"

MSG__0106 "Descriptor de devolución de llamada no válido"

MSG__0107 "El índice del elemento de devolución de llamada está fuera de límite"

MSG__0108 "No se pudo descomprimir el código de cadena %d"

MSG__0109 "Demasiados elementos"

MSG__0110 "No se pudo convertir la cadena de bites múltiples en una cadena de caracteres anchos "

MSG__0111 "No se pudo convertir el número entero '%d' en una imagen de icono"

MSG__0112 "No se pudo convertir en imagen de icono"

MSG__0113 "No se pudo abrir la memoria intermedia. La versión de UID no coincide."

MSG__0114 "No se pudo abrir la memoria intermedia"

MSG__0115 "No se pudieron convertir las unidades en XmPIXELS debido a que el formato o tipo es incorrecto"

MSG__0116 "No se pudieron convertir la unidades en XmPIXELS debido a un desbordamiento de coma flotante"

MSG__0117 "El archivo UID contiene la cadena de versión g %s no válida. No se puede leer el archivo."

MSG__0118 "La versión %s de Mrm es mayor que la versión del archivo %s.\nPor favor vuelva a compilar el archivo UIL."

MSG__0119 "El objeto '%s' se ha declarado como PRIVATE."

