$ $XConsortium: Uil.msg /main/3 1996/10/19 14:47:48 rws $

$quote "

$set UIL_SET1


UIL_0 "Se ha ignorado la opción duplicada \"%s\""

UIL_1 "Se ha ignorado la opción desconocida \"%s\""

UIL_2 "Se ha ignorado el archivo de origen UIL %s adicional"

UIL_3 "Se produjo un error al abrir el archivo de origen %s"

UIL_4 "Se produjo un error al leer la siguiente línea del archivo de origen %s"

UIL_5 "Error interno %s"

UIL_6 "La línea está truncada en %d caracteres"

UIL_7 "El valor de %s está fuera del intervalo %s"

UIL_8 "%s no terminó %s"

UIL_9 "Se ha ignorado el carácter \\%d\\ que no se puede imprimir"

UIL_10 "La secuencia \"%s\" se ha ignorado"

UIL_11 "Se ha ignorado la secuencia de escape \"\\%c\" - \\"

UIL_12 "El nombre excede los %d caracteres, se ha truncado a %s"

UIL_13 "Se agotó la memoria virtual para el compilador"

UIL_14 "Se ha encontrado el testigo %s inesperado, el análisis sintáctico se reanudará después de \"%c\""

UIL_15 "%s %s debe definirse antes de esta referencia"

UIL_16 "El contexto requiere %s pero se ha especificado %s"

UIL_17 "%s todavía no se ha implementado"

UIL_18 "Se encontró el valor %s pero se esperaba el valor %s"

UIL_19 "%s %s no está soportado para el objeto %s"

UIL_20 "%s %s reemplaza toda definición anterior en %s %s"

UIL_21 "El nombre %s ha sido definido anteriormente como %s"

UIL_22 "El valor utilizado en este contexto debe ser privado"

UIL_23 "El procedimiento %s se ha declarado anteriormente con %d argumentos"

UIL_24 "Se encontró el valor %s pero el argumento de procedimiento %s debe utilizar el valor %s"

UIL_25 "Se encontró %s %s pero se esperaba %s %s"

UIL_26 "%s %s nunca ha sido definido"

UIL_27 "%s %s ya ha sido especificado para este %s %s"

UIL_28 "El elemento %s no es válido en %s %s"

UIL_29 "Se ha cancelado la compilación, por favor resuelva los errores anteriores"

UIL_30 "Error interno. Por favor envíe un informe acerca del error."

UIL_31 " "

UIL_32 "A %s le falta la siguiente opción \"%s\""

UIL_33 "Se produjo un error al abrir el archivo de lista %s"

UIL_34 "Se produjo un error al escribir en el archivo de lista %s"

UIL_35 "La estructura del módulo no es válida. Verifique la sintaxis del módulo UIL"

UIL_36 "Demasiados archivos para abrir: %s"

UIL_37 "La línea de origen contiene un carácter nulo"

UIL_38 "Errores: %d  advertencias: %d  mensajes de información: %d"

UIL_39 "Se produjo un error al abrir el archivo UID %s"

UIL_40 "No se ha obtenido ningún archivo UID"

UIL_41 "El widget %s no soporta el procedimiento de creación"

UIL_42 "No se permite el procedimiento de creación en referencias de widget %s"

UIL_43 "La declaración de widgets %s requiere un procedimiento de creación"

UIL_44 "Las cadenas no pueden contener caracteres NULL"

UIL_45 "El widget %s forma parte de una definición circular"

UIL_46 "No se ha especificado ningún archivo de origen"

UIL_47 "%s %s solamente soporta un %s %s"

UIL_48 "El widget %s solamente soporta un control"

UIL_49 "Juego de caracteres desconocido"

UIL_50 "Ubique la cláusula de nombres antes de las cláusulas de otros módulos"

UIL_51 "La cadena de la letra del color debe contener sólo un carácter"

UIL_52 "La letra del color ya se ha utilizado anteriormente para otro color en esta tabla"

UIL_53 "El ancho de la fila %d debe ser igual al de la fila 1"

UIL_54 "Fila %d, columna %d: la letra \"%c\" no se encuentra en la tabla de colores"

UIL_55 "Demasiados %ss en %s. Límite: %d"

UIL_56 "No se puede utilizar un subcalificador en un calificador negado"

UIL_57 "El gadget %s no está soportado. Se utilizará el widget %s en vez del gadget."

UIL_58 "El tipo %s no es válido para %s"

UIL_59 "Es posible que futuras versiones no soporten este carácter"

UIL_60 "La limitación %s para el %s %s no está soportada"

UIL_61 "Demasiadas opciones \"%s\". Límite: %d"

UIL_62 "Se produjo un error al cerrar el archivo de origen %s"

UIL_63 "El valor %s está definido de forma circular"

UIL_64 "Se ignorará y reemplazará el nombre %s incorporado"

UIL_65 "El argumento %s no soporta valores enumerados"

UIL_66 "El argumento %s no soporta el valor enumerado %s"

UIL_67 "$LANG contiene un juego de caracteres desconocido"

UIL_68 "La jerarquía de controles del objeto %s contiene una referencia a sí mismo"

UIL_69 "El valor %s es demasiado grande para caber en la memoria intermedia de contexto"

UIL_70 "No se permite utilizar referencias hacia adelante para %s"

UIL_71 "No se puede convertir el tipo %s en el tipo %s"

UIL_72 "%s no es válido"

UIL_V2_73 "Se produjo un error al leer la base de datos binaria"

UIL_V2_74 "La base de datos binaria se ha compilado con una versión futura "

UIL_V2_75 "Se produjo un error al abrir el archivo de base de datos %s"

UIL_V2_76 "Se produjo un error al escribir el archivo UID %s"

UIL_V2_77 "'%s' es un nombre de anotación de clase de juego de herramientas"

UIL_78 "La operación para incluir el nombre del archivo no es válida"

UIL_V2_79 "Los tipos de unidad son incompatibles para la operación aritmética"

UIL_V2_80 "%s se utiliza como nombre de juego de caracteres. %s se utiliza como componente de juego de caracteres"


$set UIL_VALUES

UIL_VAL_0 "** Error **"

UIL_VAL_1 "** Desconocido **"


$set UIL_SET_MISC


UIL_INF "Información: "

UIL_WAR "Advertencia: "

UIL_ERR "Error: "

UIL_SEV "Grave: "

UIL_MISC_0 "\t\t Línea: %d  archivo: %s"

UIL_MISC_1 "\t\t Línea: %d  posición: %d  archivo: %s"
