#!/bin/ksh

TMPFILE=/tmp/xxIIee$$
TMPFILE300=${TMPFILE}300
TMPFILE700=${TMPFILE}700
TMPFILEOTHER=${TMPFILE}OTHER
TMPFILEEMPTY=${TMPFILE}EMPTY

if (( $#  < 1 ))
then
   PWDIR=`/bin/pwd`
   DATEDIR=`basename $PWDIR`
   DIR=/x/logs/build/$DATEDIR
else
   DIR=/x/logs/build/$1
fi


echo >$TMPFILEEMPTY
echo >>$TMPFILEEMPTY
echo >>$TMPFILEEMPTY

echo "300   Build Machines in $DIR" > $TMPFILE300
echo  >> $TMPFILE300

echo "700   Build Machines in $DIR" > $TMPFILE700
echo >> $TMPFILE700

echo "Other Build Machines in $DIR" > $TMPFILEOTHER
echo >> $TMPFILEOTHER


find $DIR -name summar\*  -exec grep master_build {} \;  > $TMPFILE



grep 300 $TMPFILE | sort -k 6,6 >> $TMPFILE300

grep 700 $TMPFILE | sort -k 6,6 >> $TMPFILE700

grep -v 300 $TMPFILE | grep -v 700 | sort -k 6,6 >> $TMPFILEOTHER

cat  $TMPFILE700  $TMPFILEEMPTY $TMPFILEOTHER   $TMPFILEEMPTY $TMPFILE300



 rm $TMPFILE
 rm $TMPFILE300
 rm $TMPFILE700
 rm $TMPFILEOTHER
 rm $TMPFILEEMPTY



