$ $XConsortium: Mrm.msg /main/3 1996/12/01 23:20:34 cde-hit $
$
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 
$ (c) Copyright 1996 Digital Equipment Corporation.
$ (c) Copyright 1996 Hewlett-Packard Company.
$ (c) Copyright 1996 International Business Machines Corp.
$ (c) Copyright 1996 Sun Microsystems, Inc.
$ (c) Copyright 1996 Novell, Inc. 
$ (c) Copyright 1996 FUJITSU LIMITED.
$ (c) Copyright 1996 Hitachi.
$

$ This message catalog contains messages issued by Motif Mrm library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.
 
$quote "

$set MS_Mrm

$ "NEW-"
MSG__0000 "ベクトルの確保に失敗しました。"

$ "NEW-"
MSG__0001 "バッファの確保に失敗しました。"

$ "NEW-"
MSG__0002 "無効なバッファです。"

$ "NEW-"
MSG__0003 "ブロックの入力に失敗しました。"

$ "NEW-"
MSG__0004 "ブロックの出力に失敗しました。"

$ "NEW-"
MSG__0005 "無効なレコード・ヘッダです。"

$ "NEW-"
MSG__0006 "無効なコンテキストです。"

$ "NEW-"
MSG__0007 "無効なデータ・エントリです。"

$ "NEW-"
MSG__0008 "無効なセグメント・エントリです。"

$ "NEW-"
MSG__0009 "未知のデータ・エントリ型です。"

$ "NEW-"
MSG__0010 "予期しないレコード型です。"

$ "NEW-"
MSG__0011 "ファイルのバージョン %s が Mrm のバージョン %s を超えています。"

$ "NEW-"
MSG__0012 "ヘッダ・レコードではありません。"

$ "NEW-"
MSG__0013 "リソースのインデックスが範囲外です。"

$ "NEW-"
MSG__0014 "NULL のデータ・ポインタです。"

$ "NEW-"
MSG__0015 "不正なオーバーフロー・レコードです。"

$ "NEW-"
MSG__0016 "GT レコードが一致しません。"

$ "NEW-"
MSG__0017 "LT レコードが一致しません。"

$ "NEW-"
MSG__0018 "予期しない親のレコート型です。"

$ "NEW-"
MSG__0019 "EOF を超えたレコードです。"

$ "NEW-"
MSG__0020 "レコード #%d 型 %d を交換できません。"

$ "NEW-"
MSG__0021 "コールバック項目 %d で、未実装の型 %d が見つかりました。"

$ "NEW-"
MSG__0022 "未実装の引数の型 %d が見つかりました。"

$ "NEW-"
MSG__0023 "NULL の階層idです。"

$ "NEW-"
MSG__0024 "無効な階層です。"

$ "NEW-"
MSG__0025 "無効なインタフェース・モジュールです。"

$ "NEW-"
MSG__0026 "無効なウィジェット・レコートです。"

$ "NEW-"
MSG__0027 "コンテキストの確保に失敗しました。"

$ "NEW-"
MSG__0028 "検証に失敗しました。"

$ "NEW-"
MSG__0029 "レコードのサイズが長過ぎます。"

$ "NEW-"
MSG__0030 "ディスプレイがオープンされていません。"

$ "NEW-"
MSG__0031 "ファイル %s がオープンできません。"

$ "NEW-"
MSG__0032 "ファイル %s がオープンできません。UID ファイルのバージョンが一致しません。"

$ "NEW-"
MSG__0033 "%s の XmUNSPECIFIED_PIXMAP で XmGetPixmap が失敗しました。"

$ "NEW-"
MSG__0034 "アイコンイメージの変換で XCreateImage が失敗しました。"

$ "NEW-"
MSG__0035 "アイコンイメージの変換で XCreatePixmap が失敗しました。"

$ "NEW-"
MSG__0036 "アイコンイメージの変換で XCreateGC が失敗しました。"

$ "NEW-"
MSG__0037 "アイコンイメージの変換で XtMalloc が失敗しました。"

$ "NEW-"
MSG__0038 "カラー '%s' を読み込むことができませんでした。"

$ "NEW-"
MSG__0039 "RGB カラー/ピクセル '%d,%d,%d' を変換できませんでした。"

$ "NEW-"
MSG__0040 "無効なカラー記述子の型です。"

$ "NEW-"
MSG__0041 "不正なカラー項目のモノクローム・ステート %d です。"

$ "NEW-"
MSG__0042 "リテラル '%s' が見つかりません。"
$ literal in this context means a named value.

$ "NEW-"
MSG__0043 "無効なリソース・コンテキストです。"

$ "NEW-"
MSG__0044 "ウィジェットが多過ぎます。"

$ "NEW-"
MSG__0045 "頂点のインデックスが境界外です。"

$ "NEW-"
MSG__0046 "リストの確保に失敗しました。"

$ "NEW-"
MSG__0047 "リストのベクトルの確保に失敗しました。"

$ "NEW-"
MSG__0048 "ベクトルの再確保に失敗しました。"

$ "NEW-"
MSG__0049 "文字列の確保に失敗しました。"

$ "NEW-"
MSG__0050 "UID ファイルは無効です。圧縮テーブルがありません。"

$ "NEW-"
MSG__0051 "クラス %s のクラス記述子が見つかりませんでした。"

$ "NEW-"
MSG__0052 "インデックスが示すウィジェット '%s' が見つかりません。"

$ "NEW-"
MSG__0053 "RID ウィジェット '%x' が見つかりません。"

$ "NEW-"
MSG__0054 "?? 「未知の」キー型です。%d"

$ "NEW-"
MSG__0055 "未知のウィジェット種類です。"

$ "NEW-"
MSG__0056 "作成コールバックに未解決のウィジェット参照があります。"

$ "NEW-"
MSG__0057 "作成コールバックを決定することができませんでした。"

$ "NEW-"
MSG__0058 "未知の子の型です。"

$ "NEW-"
MSG__0059 "親の子が見つかりません。"

$ "NEW-"
MSG__0060 "ウィジェット参照にインデックスがありません。"

$ "NEW-"
MSG__0061 "カラー/ピクセル '%s' を変換できませんでした。"

$ "NEW-"
MSG__0062 "文字列コード %d を圧縮できませんでした。"

$ "NEW-"
MSG__0063 "未処理のリソース・グループです。"

$ "NEW-"
MSG__0064 "ASCIZ '%s' をコンパウンド・ストリングに変換できませんでした。"

$ "NEW-"
MSG__0065 "トランスレーション・テーブル '%s' を解析できませんでした。"

$ "NEW-"
MSG__0066 "識別子 '%s' を変換できませんでした。"

$ "NEW-"
MSG__0067 "内部エラーです。場合 MrmRtypeIconImage が見つかりました。"

$ "NEW-"
MSG__0068 "内部エラーです。場合 MrmRtypeXBitmapFile が見つかりました。"

$ "NEW-"
MSG__0069 "内部エラーです。ディスプレイを文字列に変換できませんでした。"

$ "NEW-"
MSG__0070 "フォント '%s' を変換できませんでした。"

$ "NEW-"
MSG__0071 "fontset '%s' を変換できませんでした。"
$ please do not translate fontset.

$ "NEW-"
MSG__0072 "fontset '%s' のひとつまたは複数のフォントをオープンできませんでした。"

$ "NEW-"
MSG__0073 "フォントリストのフォント '%s' をリストに追加できませんでした。"

$ "NEW-"
MSG__0074 "フォントリストの fontset '%s' をリストに追加できませんでした。"

$ "NEW-"
MSG__0075 "クラス・レコード名 '%s' を変換できませんでした。"

$ "NEW-"
MSG__0076 "キーシム文字列 '%s' を KeySym に変換できませんでした。"

$ "NEW-"
MSG__0077 "インデックスが示すリテラル '%s' が見つかりません。"

$ "NEW-"
MSG__0078 "RID リテラル '%x' が見つかりません。"

$ "NEW-"
MSG__0079 "未知のリテラルのキー型です。%d"

$ "NEW-"
MSG__0080 "無効なカラーテーブルのリテラル型です。%d"

$ "NEW-"
MSG__0081 "無効なカラーテーブルの型コードです。%d"

$ "NEW-"
MSG__0082 "無効なカラーのリテラル型です。%d"

$ "NEW-"
MSG__0083 "無効なカラーアイテムの型コードです。%d"

$ "NEW-"
MSG__0084 "コールバック・ルーチン '%s' は登録されていません。"

$ "NEW-"
MSG__0085 "ウィジェット参照にインデックスがありません。"

$ "NEW-"
MSG__0086 "インデックスで示されたウィジェットのリソース '%s' が見つかりません。"

$ "NEW-"
MSG__0087 "RID ウィジェットのリソース '%x' が見つかりません。"

$ "NEW-"
MSG__0088 "未知のリソースのキー型です。%d"

$ "NEW-"
MSG__0089 "ウィジェット・ツリーを初期化できませんでした。"

$ "NEW-"
MSG__0090 "Null のユーザ定義クラス名です。"

$ "NEW-"
MSG__0091 "無効なクラス・コードです。"

$ "NEW-"
MSG__0092 "引数が多過ぎます。"

$ "NEW-"
MSG__0093 "無効な圧縮コードです。"

$ "NEW-"
MSG__0094 "無効または未処理の型です。"

$ "NEW-"
MSG__0095 "ベクトルが大き過ぎます。"

$ "NEW-"
MSG__0096 "空のルーチン名です。"

$ "NEW-"
MSG__0097 "Char8Vector は実装されていません。"

$ "NEW-"
MSG__0098 "CStringVector は実装されていません。"

$ "NEW-"
MSG__0099 "子の数が多過ぎます。"

$ "NEW-"
MSG__0100 "Null の子のリスト記述子です。"

$ "NEW-"
MSG__0101 "子のインデックスが境界外です。"

$ "NEW-"
MSG__0102 "Null のインデックスです。"

$ "NEW-"
MSG__0103 "無効なキー型です。"

$ "NEW-"
MSG__0104 "Arg のインデックスが境界外です。"

$ "NEW-"
MSG__0105 "無効なウィジェット/ガジェット・レコートです。"

$ "NEW-"
MSG__0106 "無効なコールバック記述子です。"

$ "NEW-"
MSG__0107 "コールバック項目のインデックスが境界外です。"

$ "NEW-"
MSG__0108 "文字列コード %d を圧縮できませんでした。"

$ "NEW-"
MSG__0109 "項目が多過ぎます。"

$ "NEW-"
MSG__0110 "マルチバイト文字列をワイドキャラクタ文字列に変換できませんでした。"

$ "NEW-"
MSG__0111 "整数 '%d' をアイコンイメージに変換できませんでした。"

$ "NEW-"
MSG__0112 "アイコンイメージに変換できませんでした。"

$ "NEW-"
MSG__0113 "バッファがオープンできませんでした。UID のバージョンが一致しません。"

$ "NEW-"
MSG__0114 "バッファがオープンできませんでした。"

$ "NEW-"
MSG__0115 "ユニットを XmPIXELS に変換できません。無効なユニットのフォーマットまたは型です。"

$ "NEW-"
MSG__0116 "ユニットを XmPIXELS に変換できません。浮動少数点オーバーフローです。"

$ "NEW-"
MSG__0117 "UID ファイルに無効なバージョン文字列があります。ファイルを読み込むことができません。"

$ "NEW-"
MSG__0118 "Mrm のバージョン %s がファイルのバージョン %s を超えています。\n\
UIL ファイルを再コンパイルしてください。"

$ "NEW-"
MSG__0119 "PRIVATE で宣言されたオブジェクトです。 '%s'"

