#! /bin/ksh
########
#  Product: CDE
#  Fileset: CDE-RUN
#  configure
#  @(#) $TOG: configRun /main/2 1998/11/05 15:04:43 mgreess $
########

PRODUCT=CDE
FILESET=CDE-RUN
retval=0



CreateAppConfigDirectory()
{
#
# Create the APPCONFIG directory inside DT_CONFIG_TOP and create
# all of its subdirectories
#

    cd $DT_CONFIG_TOP
    if [ ! -d $APPCONFIG ]
    then
	mkdir $APPCONFIG
    fi

    cd $APPCONFIG

    for i in $APPCONFIG_DIRS
    do
	if [ ! -d $i ]
	then
	    mkdir $i
	fi
	cd $i
	#
	# for each locale
	#
	for j in $DT_TOP/$APPCONFIG/$i/*
	do
	    if [ ! -d `basename $j` ]
	    then
		mkdir `basename $j`
	    fi
	done
	cd ..
    done

}

FixInetdDotConf()
{
FILE="/etc/inetd.conf"
TMPFILE="/tmp/inetd.conf"

#
# desired inetd.conf entry:
# rpc dgram  udp  wait  root  /usr/dt/bin/rpc.cmsd 100068 2-4 cmsd
#

#
# get rid of legacy entry
#

    awk '{if ($1 == "#rpc" && $7 == "100068" && $9 == "rpc.cmsd")
		;
	  else
		print $0
	 }' $FILE >$TMPFILE

    mv $FILE ${FILE}.old
    mv $TMPFILE $FILE

    CMSD=/usr/dt/bin/rpc.cmsd

    awk -v cmsd=$CMSD \
		'{if ($7 == "100068" && $6 != cmsd)
			print "#cde " $0;
		  else
			print $0
		 }' $FILE >$TMPFILE

#
# remove 100068 2-4 rpc.cmsd entry
#

    awk -v cmsd=$CMSD \
		'{if ($6 == cmsd && $7 == "100068" && $8 == "2-4")
			;
		  else
			print $0
		 }' $FILE >$TMPFILE

    mv $FILE ${FILE}.old
    mv $TMPFILE $FILE

#
# now see if there is an occurrence of cmsd
#

    awk -v cmsd=$CMSD \
		'{if ($6 == cmsd && $7 == "100068" && $8 == "2-5")
			print $0 >"/tmp/cmsd-already-there"
		 }' $FILE >/dev/null

#
# if it is not there, add it
#

    if [ ! -f /tmp/cmsd-already-there ]
    then
        echo "rpc dgram udp wait root $CMSD 100068 2-5 rpc.cmsd" >>$FILE
    else
	rm /tmp/cmsd-already-there
    fi

}

UnfixInetdDotConf()
{
FILE="/etc/inetd.conf"
TMPFILE="/tmp/inetd.conf"
CMSD=/usr/dt/bin/rpc.cmsd

# first remove the CDE rpc.cmsd entry

    awk -v cmsd=$CMSD \
	'{if ($7 == "100068" && $6 == cmsd)
		;
	  else
		print $0
	 }' $FILE >$TMPFILE

    mv $TMPFILE $FILE

# now uncomment any previously existing 100068 entry

    awk '{if ($1 == "#cde") {
		if ($8 == "100068") {
			$1 = $2;
			$2 = ""
		}
	  }
	  print $0
	 }' $FILE >$TMPFILE

    mv $TMPFILE $FILE
}

FixEtcRpc()
{
#
# now check to see if the proper entry is in /etc/rpc
#

    RPCFILE=/etc/rpc
    TMPFILE=/tmp/etc-rpc

    if [ ! -f $RPCFILE ]
    then
	# if the file doesn't exist (highly unlikely), make one
	# with the proper entry
	#

	echo "cmsd     100068  dtcalendar" >$RPCFILE

    else
	#
	# check to see if the entry is already there
	#

	awk '{if ($1 == "cmsd" && $2 == "100068")
		print $0 > "/tmp/etc-rpc-already-there"
	     }' $RPCFILE >/dev/null

	if [ ! -f /tmp/etc-rpc-already-there ]
	then
	#
	# if it isn't, check to see if either term already
	# exists
	#

	    awk '{if ($1 == "cmsd" || $2 == "100068")
			print $0 > "/tmp/etc-rpc-already-there"
		 }' $RPCFILE >/dev/null

	#
	# if either one does they need to be commented out
	#

	    if [ ! -f /tmp/etc-rpc-already-there ]
	    then
	        echo "cmsd     100068  dtcalendar" >>$RPCFILE
	    else
		awk '{if ($1 == "cmsd" || $2 == "100068")
			print "#cde " $0;
		      else
			print $0
		     }'	$RPCFILE >$TMPFILE

	        echo "cmsd     100068  dtcalendar" >>$TMPFILE
		mv $TMPFILE $RPCFILE
		rm /tmp/etc-rpc-already-there
	    fi
	else
	    rm /tmp/etc-rpc-already-there
	fi
    fi

}

UnfixEtcRpc()
{
FILE="/etc/rpc"
TMPFILE="/tmp/etc-rpc"

    awk '{if ($1 == "cmsd" && $2 == "100068")
		;
	  else
		print $0
	 }' $FILE >$TMPFILE

    mv $TMPFILE $FILE

    awk '{if ($1 == "#cde" && ($2 == "cmsd" || $3 == "100068"))
		;
	  else
		print $0
	 }' $FILE >$TMPFILE

    mv $TMPFILE $FILE
}

ConfigurePrintersDir()
{
    cd $DT_TOP/$APPCONFIG/appmanager
#
# for each locale
#
    for i in *
    do
        if [ -d $i ]
	then
	    cd $i
	#
	# for each directory in the locale, check for a
	# localized version of the Printers directory
	# and for the file lp_Print within that directory
	#
	    for j in *
	    do
	      if [ -f $j/$DEFAULT_PRINTER ]
	      then

		PRINTERS=$j

		# make the equivalent directory in the configuration
		# directory

	        if [ ! -d $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i ]
	        then
		    mkdir $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i
	        fi
	        cd $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i
	        if [ ! -d $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i/$PRINTERS ]
	        then
		    mkdir $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i/$PRINTERS
                fi
	        cd $DT_CONFIG_TOP/$APPCONFIG/appmanager/$i/$PRINTERS

		# now copy the file over from the installation dirctory
		# if it is not already present.

	        if [ ! -f $DEFAULT_PRINTER ]
	        then
		    cp $DT_TOP/$APPCONFIG/appmanager/$i/$PRINTERS/$DEFAULT_PRINTER .
	        fi
	        cd $DT_TOP/$APPCONFIG/appmanager/$i
	      fi
	    done
	    cd $DT_TOP/$APPCONFIG/appmanager
	fi
    done
}

KillIt()
{
    ps -ef | fgrep $1 | grep -v grep >/tmp/tmppsout
    if [ -s /tmp/tmppsout ]
    then
	awk '{print "kill " $2}' /tmp/tmppsout | /bin/ksh
        sleep 2
	ps -ef | fgrep $1 | grep -v grep >/tmp/tmppsout
        if [ -s /tmp/tmppsout ]
        then
	    awk '{print "kill -TERM " $2}' /tmp/tmppsout | /bin/ksh
            sleep 2
	    ps -ef | fgrep $1 | grep -v grep >/tmp/tmppsout
            if [ -s /tmp/tmppsout ]
            then
	        awk '{print "kill -9 " $2}' /tmp/tmppsout | /bin/ksh
                sleep 2
	    fi
        fi
    fi
    rm /tmp/tmppsout
}

RemoveRunFiles()
{
    while read SRC
    do
      if [ "$SRC" != "" ]
      then
	rm -f $SRC
	dirname=${SRC%/*}
	if [ -d $dirname ]
	then
	  cd $dirname
	  while [ "$dirname" != "$CDE_TOP" ]
	  do
	    cd ..
	    rmdir ${dirname##*/} >/dev/null 2>/dev/null
	    dirname=${dirname%/*}
	  done
	fi
      fi
    done <<-EOF
/usr/dt/config/Xfailsafe
/usr/dt/bin/dtrc
/usr/dt/bin/dtrc
/usr/dt/bin/rc.dt
/usr/dt/config/Xconfig
/usr/dt/config/Xreset
/usr/dt/config/Xsetup
/usr/dt/config/Xservers
/usr/dt/config/Xaccess
/usr/dt/config/Xstartup
/usr/dt/config/C/Xresources
/usr/dt/config/C/sys.dtwmrc
/usr/dt/config/sys.dtprofile
/usr/dt/config/C/sys.resources
/usr/dt/config/C/sys.session
/usr/dt/config/C/sys.font
/usr/dt/config/dtlogin.rc
/usr/dt/bin/dtconfig
/usr/dt/bin/dtconfig
/usr/dt/app-defaults/C/Dthello
/usr/dt/app-defaults/C/Dtsession
/usr/dt/app-defaults/C/Dtwm
/usr/dt/app-defaults/C/Dtfile
/usr/dt/app-defaults/C/Dtstyle
/usr/dt/app-defaults/C/Dtpad
/usr/dt/app-defaults/C/Dtscreen
/usr/dt/app-defaults/C/Dticon
/usr/dt/app-defaults/C/Dtcalc
/usr/dt/app-defaults/C/Dtterm
/usr/dt/app-defaults/C/Dt
/usr/dt/app-defaults/C/Dtcreate
/usr/dt/app-defaults/C/Dtprintinfo
/usr/dt/app-defaults/C/UNIXbindings
/usr/dt/bin/Xsession
/usr/dt/config/Xsession.d/0010.dtpaths
/usr/dt/config/Xsession.d/0020.dtims
/usr/dt/config/Xsession.d/0030.dttmpdir
/usr/dt/config/Xsession.d/0050.srcdotsh
/usr/dt/share/examples/sys.font.iso
/usr/dt/bin/dtprintinfo
/usr/dt/config/C/dtfile.config
/usr/dt/bin/dtconvertvf
/usr/dt/bin/dtconvertvf
/usr/dt/bin/dtcreate
/usr/dt/appconfig/appmanager/C/Information/README
/usr/dt/appconfig/appmanager/C/System_Admin/README
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Bitmap
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Spell
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xclipboard
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Diff
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Compress
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermConsole
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Wc
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XclockDig
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DuSort
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Df
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xfd
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DtwmrcEdit
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadResources
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ExecuteCmd
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Env
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xlsfonts
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Nm
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwininfo
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xprop
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Make
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xrefresh
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadActions
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadApps
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermRlogin
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermDtspcd
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XtermRlogin
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XtermDtspcd
/usr/dt/appconfig/appmanager/C/Desktop_Tools/RestorePanel
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Rm
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Grep
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xload
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Tar
/usr/dt/appconfig/appmanager/C/Desktop_Tools/TarList
/usr/dt/appconfig/appmanager/C/Desktop_Tools/TarUnpack
/usr/dt/appconfig/appmanager/C/Desktop_Tools/File
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Uncompress
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Vi
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermErrorlog
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xterm
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xdpyinfo
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwd
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwud
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcalc
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcm
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcreate
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtfile
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dticon
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dthelpview
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtmail
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtmanpageview
/usr/dt/appconfig/appmanager/C/Desktop_Apps/DtPrintManager
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtstyle
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtpad
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtterm
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dttrash
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Dttypes
/usr/dt/bin/dtlp
/usr/dt/share/palettes/desc.C
/usr/dt/share/backdrops/desc.C
/usr/dt/share/backdrops/Foreground.bm
/usr/dt/share/backdrops/Background.bm
/usr/dt/share/backdrops/NoBackdrop.pm
/usr/dt/share/backdrops/Ankh.bm
/usr/dt/share/backdrops/BrickWall.bm
/usr/dt/share/backdrops/Concave.pm
/usr/dt/share/backdrops/Convex.pm
/usr/dt/share/backdrops/Corduroy.pm
/usr/dt/share/backdrops/Crochet.pm
/usr/dt/share/backdrops/InlayColor.pm
/usr/dt/share/backdrops/InlayPlain.pm
/usr/dt/share/backdrops/KnitLight.pm
/usr/dt/share/backdrops/Lattice.pm
/usr/dt/share/backdrops/LatticeBig.pm
/usr/dt/share/backdrops/Leaves.pm
/usr/dt/share/backdrops/OldChars.pm
/usr/dt/share/backdrops/Paver.pm
/usr/dt/share/backdrops/Pebbles.pm
/usr/dt/share/backdrops/PinStripe.pm
/usr/dt/share/backdrops/RakedSand.bm
/usr/dt/share/backdrops/RicePaper.pm
/usr/dt/share/backdrops/SkyDark.pm
/usr/dt/share/backdrops/SkyLight.pm
/usr/dt/share/backdrops/Sprinkles.pm
/usr/dt/share/backdrops/Toronto.bm
/usr/dt/share/backdrops/WaterDrops.pm
/usr/dt/share/backdrops/Wooly.pm
/usr/dt/backdrops
/usr/dt/bin/dtfile_error
/usr/dt/bin/dtfile
/usr/dt/bin/dtfile_copy
/usr/dt/bin/dtsession
/usr/dt/bin/dtsession_res
/usr/dt/bin/dtwm
/usr/dt/bin/dtfplist
/usr/dt/bin/dtlogin
/usr/dt/bin/dtchooser
/usr/dt/bin/dtgreet
/usr/dt/bin/hpterm
/usr/dt/bin/hpterm
/usr/dt/bin/aixterm
/usr/dt/bin/dthello
/usr/dt/bin/dtaction
/usr/dt/bin/dtpad
/usr/dt/bin/dtstyle
/usr/dt/bin/dtscreen
/usr/dt/bin/dticon
/usr/dt/bin/dtcalc
/usr/dt/bin/dtterm
/usr/dt/config/dtterm.ti
/usr/dt/bin/dtsearchpath
/usr/dt/bin/dtappgather
/usr/dt/bin/dttypes
/usr/dt/bin/dsdm
/usr/dt/bin/rpc.cmsd
/usr/dt/bin/dtcm
/usr/dt/bin/dtcm_admin
/usr/dt/bin/dtcm_editor
/usr/dt/bin/dtcm_delete
/usr/dt/bin/dtcm_insert
/usr/dt/bin/dtcm_lookup
/usr/dt/appconfig/types/C/dtcm.dt
/usr/dt/app-defaults/C/Dtcm
/usr/dt/bin/dtdspmsg
/usr/dt/bin/dtmail
/usr/dt/bin/dtmailpr
/usr/dt/bin/dtmailconv
/usr/dt/appconfig/types/C/dtmail.dt
/usr/dt/app-defaults/C/Dtmail
/usr/dt/appconfig/types/C/dtwm.fp
/usr/dt/appconfig/types/C/autoStart.dt
/usr/dt/appconfig/types/C/uxstd.dt
/usr/dt/appconfig/types/C/dt.dt
/usr/dt/appconfig/types/C/develop.dt
/usr/dt/appconfig/types/C/datatypes.dt
/usr/dt/appconfig/types/C/dtappman.dt
/usr/dt/appconfig/types/C/dtfile.dt
/usr/dt/appconfig/types/C/dtpad.dt
/usr/dt/appconfig/types/C/xclients.dt
/usr/dt/appconfig/types/C/print.dt
/usr/dt/appconfig/types/C/user-prefs.dt
/usr/dt/appconfig/types/C/dthelp.dt
/usr/dt/appconfig/types/C/dtscreen.dt
/usr/dt/share/examples/types/C/IconBrowse.dt
/usr/dt/share/examples/types/C/miscActions.dt
/usr/dt/share/examples/types/C/miscImages.dt
/usr/dt/bin/dterror.ds
/usr/dt/bin/xmbind
/usr/dt/lib/bindings/xmbind.alias
/usr/dt/lib/bindings/acorn
/usr/dt/lib/bindings/apollo
/usr/dt/lib/bindings/dg_AViiON
/usr/dt/lib/bindings/doubleclick
/usr/dt/lib/bindings/hitachi
/usr/dt/lib/bindings/hp
/usr/dt/lib/bindings/ibm
/usr/dt/lib/bindings/intergraph
/usr/dt/lib/bindings/intergraph17
/usr/dt/lib/bindings/megatek
/usr/dt/lib/bindings/motorola
/usr/dt/lib/bindings/ncr_at
/usr/dt/lib/bindings/ncr_vt
/usr/dt/lib/bindings/sgi
/usr/dt/lib/bindings/siemens_9733
/usr/dt/lib/bindings/siemens_wx200
/usr/dt/lib/bindings/sony
/usr/dt/lib/bindings/sun
/usr/dt/lib/bindings/tek
/usr/dt/config/Xsession.d/0040.xmbind
/usr/dt/examples
	EOF
}


VerifyInstalledFiles()
{
    echo "Status   mode    owner   group   filename"
    echo "-----------------------------------------"
#	  exists  correct correct correct  /usr/dt/foo1
#	  MISSING  WRONG   WRONG   WRONG   /usr/dt/foo2
#        exists    the link is correct    /usr/dt/link

    while read SRC
    do
      if [ "$SRC" != "" ]
      then
	set -A tokens $SRC
	if [ "${tokens[3]}" = "file" ]
	then
	  if [ -f ${tokens[0]} ]
	  then
	    echo "exists  \c"
	  else
	    echo "MISSING or REMOVED               \c"
	    echo "${tokens[0]}"
	    continue
	  fi
	elif [ "${tokens[3]}" = "sym_link" ]
	then
	  if [ -L ${tokens[0]} ]
	  then
	    echo "exists  \c"
	  else
	    echo "MISSING or REMOVED               \c"
	    echo "${tokens[0]}"
	    continue
	  fi
	fi

	if [ "${tokens[3]}" = "file" ]
	then
	  touch /tmp/config-test
	  chmod ${tokens[1]} /tmp/config-test
	  tmpperms=`ls -l /tmp/config-test | awk '{print $1}'`
	  realperms=`ls -l ${tokens[0]} | awk '{print $1}'`

	  if [ "$tmpperms" = "$realperms" ]
	  then
	    echo "correct \c"
	  else
	    echo " WRONG  \c"
	  fi

	  owner=`ls -l ${tokens[0]} | awk '{print $3}'`

	  if [ "$owner" = "${tokens[4]}" ]
	  then
	    echo "correct \c"
	  else
	    echo " WRONG  \c"
	  fi

	  group=`ls -l ${tokens[0]} | awk '{print $4}'`

	  if [ "$group" = "${tokens[5]}" ]
	  then
	    echo "correct  \c"
	  else
	    echo " WRONG   \c"
	  fi
	elif [ "${tokens[3]}" = "sym_link" ]
	then
	  linkto=`ls -l ${tokens[0]} | awk '{print $11}'`
	  if [ "${tokens[2]}" = "$linkto" ]
	  then
	    echo "  the link is correct    \c"
	  else
	    echo "  the link is WRONG      \c"
	  fi
	fi
	echo "${tokens[0]}"
      fi
    done <<-EOF
/usr/dt/config/Xfailsafe 0555 cde1/dtlogin/config/Xfailsafe file bin bin di---- 378 cde_dt
/usr/dt/bin/dtrc 0544 cde1/dtconfig/hp/dtrc file bin bin di---- 378 cde_dt
/usr/dt/config/Xconfig 0444 cde1/dtlogin/config/Xconfig file bin bin di---- 378 cde_dt
/usr/dt/config/Xreset 0544 cde1/dtlogin/config/Xreset file bin bin di---- 378 cde_dt
/usr/dt/config/Xsetup 0544 cde1/dtlogin/config/Xsetup file bin bin di---- 378 cde_dt
/usr/dt/config/Xservers 0444 cde1/dtlogin/config/Xservers file bin bin di---- 378 cde_dt
/usr/dt/config/Xaccess 0444 cde1/dtlogin/config/Xaccess file bin bin di---- 378 cde_dt
/usr/dt/config/Xstartup 0544 cde1/dtlogin/config/Xstartup file bin bin di---- 378 cde_dt
/usr/dt/config/C/Xresources 0444 cde1/localized/C/config/Xresources file bin bin di---- 378 cde_dt
/usr/dt/config/C/sys.dtwmrc 0444 cde1/localized/C/config/sys.dtwmrc file bin bin di---- 378 cde_dt
/usr/dt/config/sys.dtprofile 0555 cde1/dtlogin/config/dtprofile file bin bin di---- 378 cde_dt
/usr/dt/config/C/sys.resources 0444 cde1/localized/C/config/sys.resources file bin bin di---- 378 cde_dt
/usr/dt/config/C/sys.session 0444 cde1/localized/C/config/sys.session file bin bin di---- 378 cde_dt
/usr/dt/config/C/sys.font 0444 cde1/localized/C/config/sys.font file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dthello 0444 cde1/localized/C/app-defaults/Dthello file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtsession 0444 cde1/localized/C/app-defaults/Dtsession file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtwm 0444 cde1/localized/C/app-defaults/Dtwm file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtfile 0444 cde1/localized/C/app-defaults/Dtfile file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtstyle 0444 cde1/localized/C/app-defaults/Dtstyle file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtpad 0444 cde1/localized/C/app-defaults/Dtpad file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtscreen 0444 cde1/localized/C/app-defaults/Dtscreen file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dticon 0444 cde1/localized/C/app-defaults/Dticon file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtcalc 0444 cde1/localized/C/app-defaults/Dtcalc file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtterm 0444 cde1/localized/C/app-defaults/Dtterm file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dt 0444 cde1/localized/C/app-defaults/Dt file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtcreate 0444 cde1/localized/C/app-defaults/Dtcreate file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtprintinfo 0444 cde1/dtprintinfo/Dtprintinfo file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/UNIXbindings 0444 lib1/DtWidget/UNIXbindings file bin bin di---- 378 cde_dt
/usr/dt/bin/Xsession 0555 cde1/dtlogin/config/Xsession file bin bin di---- 378 cde_dt
/usr/dt/config/Xsession.d/0010.dtpaths 0555 cde1/dtsearchpath/0010.dtpaths file bin bin di---- 378 cde_dt
/usr/dt/config/Xsession.d/0020.dtims 0555 cde1/dtlogin/config/0020.dtims file bin bin di---- 378 cde_dt
/usr/dt/config/Xsession.d/0030.dttmpdir 0555 cde1/dtsearchpath/0030.dttmpdir file bin bin di---- 378 cde_dt
/usr/dt/config/Xsession.d/0050.srcdotsh 0555 cde1/dtsearchpath/0050.srcdotsh file bin bin di---- 378 cde_dt
/usr/dt/share/examples/sys.font.iso 0444 cde1/dtsession/sys.font.iso file bin bin di---- 378 cde_dt
/usr/dt/bin/dtprintinfo 04555 cde1/dtprintinfo/dtprintinfo file root bin di---- 378 cde_dt
/usr/dt/config/C/dtfile.config 0444 cde1/localized/C/config/dtfile.config file bin bin di---- 378 cde_dt
/usr/dt/bin/dtconvertvf 0555 cde1/util/scripts/convertvf file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcreate 0555 cde1/dtcreate/dtcreate file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Information/README 0444 cde1/dtappgather/howto-customize file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/System_Admin/README 0444 cde1/dtappgather/howto-customize file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Bitmap 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Spell 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xclipboard 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Diff 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Compress 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermConsole 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Wc 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XclockDig 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DuSort 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Df 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xfd 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DtwmrcEdit 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadResources 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ExecuteCmd 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Env 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xlsfonts 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Nm 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwininfo 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xprop 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Make 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xrefresh 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadActions 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/ReloadApps 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermRlogin 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermDtspcd 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XtermRlogin 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/XtermDtspcd 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/RestorePanel 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Rm 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Grep 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xload 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Tar 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/TarList 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/TarUnpack 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/File 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Uncompress 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Vi 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/DttermErrorlog 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xterm 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xdpyinfo 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwd 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Xwud 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcalc 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcm 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtcreate 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtfile 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dticon 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dthelpview 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtmail 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtmanpageview 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/DtPrintManager 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtstyle 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtpad 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dtterm 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Apps/Dttrash 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/appconfig/appmanager/C/Desktop_Tools/Dttypes 0555 cde1/localized/C/types/action file bin bin di---- 378 cde_dt
/usr/dt/bin/dtlp 0555 cde1/dtprintegrate/dtlp file bin bin di---- 378 cde_dt
/usr/dt/share/palettes/desc.C 0444 cde1/localized/C/palettes/desc.C file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/desc.C 0444 cde1/localized/C/backdrops/desc.C file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Foreground.bm 0444 cde1/backdrops/Foreground.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Background.bm 0444 cde1/backdrops/Background.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/NoBackdrop.pm 0444 cde1/backdrops/NoBackdrop.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Ankh.bm 0444 cde1/backdrops/Ankh.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/BrickWall.bm 0444 cde1/backdrops/BrickWall.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Concave.pm 0444 cde1/backdrops/Concave.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Convex.pm 0444 cde1/backdrops/Convex.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Corduroy.pm 0444 cde1/backdrops/Corduroy.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Crochet.pm 0444 cde1/backdrops/Crochet.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/InlayColor.pm 0444 cde1/backdrops/InlayColor.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/InlayPlain.pm 0444 cde1/backdrops/InlayPlain.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/KnitLight.pm 0444 cde1/backdrops/KnitLight.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Lattice.pm 0444 cde1/backdrops/Lattice.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/LatticeBig.pm 0444 cde1/backdrops/LatticeBig.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Leaves.pm 0444 cde1/backdrops/Leaves.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/OldChars.pm 0444 cde1/backdrops/OldChars.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Paver.pm 0444 cde1/backdrops/Paver.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Pebbles.pm 0444 cde1/backdrops/Pebbles.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/PinStripe.pm 0444 cde1/backdrops/PinStripe.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/RakedSand.bm 0444 cde1/backdrops/RakedSand.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/RicePaper.pm 0444 cde1/backdrops/RicePaper.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/SkyDark.pm 0444 cde1/backdrops/SkyDark.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/SkyLight.pm 0444 cde1/backdrops/SkyLight.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Sprinkles.pm 0444 cde1/backdrops/Sprinkles.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Toronto.bm 0444 cde1/backdrops/Toronto.bm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/WaterDrops.pm 0444 cde1/backdrops/WaterDrops.pm file bin bin di---- 378 cde_dt
/usr/dt/share/backdrops/Wooly.pm 0444 cde1/backdrops/Wooly.pm file bin bin di---- 378 cde_dt
/usr/dt/backdrops 0444 /usr/dt/share/backdrops sym_link bin bin di---- 378 cde_dt
/usr/dt/bin/dtfile_error 0555 cde1/dtfile/dtfile_error file bin bin di---- 378 cde_dt
/usr/dt/bin/dtfile 0555 cde1/dtfile/dtfile file bin bin di---- 378 cde_dt
/usr/dt/bin/dtfile_copy 0555 cde1/dtfile/dtcopy/dtfile_copy file bin bin di---- 378 cde_dt
/usr/dt/bin/dtsession 04555 cde1/dtsession/dtsession file root bin di---- 378 cde_dt
/usr/dt/bin/dtsession_res 0555 cde1/dtsession/dtloadresources file bin bin di---- 378 cde_dt
/usr/dt/bin/dtwm 0555 cde1/dtwm/dtwm file bin bin di---- 378 cde_dt
/usr/dt/bin/dtfplist 0555 cde1/dtwm/dtfplist file bin bin di---- 378 cde_dt
/usr/dt/bin/dtlogin 0544 cde1/dtlogin/dtlogin file root bin di---- 378 cde_dt
/usr/dt/bin/dtchooser 0544 cde1/dtlogin/dtchooser file root bin di---- 378 cde_dt
/usr/dt/bin/dtgreet 0544 cde1/dtlogin/dtgreet file bin bin di---- 378 cde_dt
/usr/dt/bin/hpterm 04555 /usr/bin/X11/hpterm sym_link root bin di---- 378 cde_dt
/usr/dt/bin/dthello 0555 cde1/dthello/dthello file bin bin di---- 378 cde_dt
/usr/dt/bin/dtaction 06555 cde1/dtaction/dtaction file root sys di---- 378 cde_dt
/usr/dt/bin/dtpad 0555 cde1/dtpad/dtpad file bin bin di---- 378 cde_dt
/usr/dt/bin/dtstyle 0555 cde1/dtstyle/dtstyle file bin bin di---- 378 cde_dt
/usr/dt/bin/dtscreen 0555 cde1/dtscreen/dtscreen file bin bin di---- 378 cde_dt
/usr/dt/bin/dticon 0555 cde1/dticon/dticon file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcalc 0555 cde1/dtcalc/dtcalc file bin bin di---- 378 cde_dt
/usr/dt/bin/dtterm 04555 cde1/dtterm/dtterm file root bin di---- 378 cde_dt
/usr/dt/config/dtterm.ti 0444 cde1/dtterm/dtterm.ti file bin bin di---- 378 cde_dt
/usr/dt/bin/dtsearchpath 0555 cde1/dtsearchpath/dtsp/dtsp file bin bin di---- 378 cde_dt
/usr/dt/bin/dtappgather 04555 cde1/dtappgather/dtappg file root bin di---- 378 cde_dt
/usr/dt/bin/dttypes 0555 cde1/util/dttypes/dttypes file bin bin di---- 378 cde_dt
/usr/dt/bin/dsdm 0555 cde1/dsdm/dsdm file bin bin di---- 378 cde_dt
/usr/dt/bin/rpc.cmsd 0555 cde1/dtcm/server/rpc.cmsd file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm 0555 cde1/dtcm/dtcm/dtcm file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm_admin 0555 cde1/dtcm/dtcm/dtcm_admin file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm_editor 0555 cde1/dtcm/dtcm/dtcm_editor file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm_delete 0555 cde1/dtcm/dtcm/dtcm_delete file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm_insert 0555 cde1/dtcm/dtcm/dtcm_insert file bin bin di---- 378 cde_dt
/usr/dt/bin/dtcm_lookup 0555 cde1/dtcm/dtcm/dtcm_lookup file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtcm.dt 0444 cde1/localized/C/types/dtcm.dt file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtcm 0444 cde1/localized/C/app-defaults/Dtcm file bin bin di---- 378 cde_dt
/usr/dt/bin/dtdspmsg 0555 cde1/dtdspmsg/dtdspmsg file bin bin di---- 378 cde_dt
/usr/dt/bin/dtmail 02555 cde1/dtmail/dtmail/dtmail file bin mail di---- 378 cde_dt
/usr/dt/bin/dtmailpr 02555 cde1/dtmail/dtmailpr/dtmailpr file bin mail di---- 378 cde_dt
/usr/dt/bin/dtmailconv 0555 cde1/dtmail/mailconv/mailconv file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtmail.dt 0444 cde1/localized/C/types/dtmail.dt file bin bin di---- 378 cde_dt
/usr/dt/app-defaults/C/Dtmail 0444 cde1/localized/C/app-defaults/Dtmail file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtwm.fp 0444 cde1/localized/C/types/dtwm.fp file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/autoStart.dt 0444 cde1/localized/C/types/autoStart.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/uxstd.dt 0444 cde1/localized/C/types/uxstd.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dt.dt 0444 cde1/localized/C/types/dt.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/develop.dt 0444 cde1/localized/C/types/develop.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/datatypes.dt 0444 cde1/localized/C/types/datatypes.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtappman.dt 0444 cde1/localized/C/types/dtappman.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtfile.dt 0444 cde1/localized/C/types/dtfile.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtpad.dt 0444 cde1/localized/C/types/dtpad.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/xclients.dt 0444 cde1/localized/C/types/xclients.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/print.dt 0444 cde1/localized/C/types/print.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/user-prefs.dt 0444 cde1/localized/C/types/user-prefs.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dthelp.dt 0444 cde1/localized/C/types/dthelp.dt file bin bin di---- 378 cde_dt
/usr/dt/appconfig/types/C/dtscreen.dt 0444 cde1/localized/C/types/dtscreen.dt file bin bin di---- 378 cde_dt
/usr/dt/share/examples/types/C/IconBrowse.dt 0444 cde1/localized/C/types/IconBrowse.dt file bin bin di---- 378 cde_dt
/usr/dt/share/examples/types/C/miscActions.dt 0444 cde1/localized/C/types/miscActions.dt file bin bin di---- 378 cde_dt
/usr/dt/share/examples/types/C/miscImages.dt 0444 cde1/localized/C/types/miscImages.dt file bin bin di---- 378 cde_dt
/usr/dt/bin/dterror.ds 0555 cde1/localized/C/types/error.ds file bin bin di---- 378 cde_dt
/usr/dt/bin/xmbind 0555 osf/xmbind/xmbind file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/xmbind.alias 0444 lib/Xm/bindings/xmbind.alias file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/acorn 0444 lib/Xm/bindings/acorn file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/apollo 0444 lib/Xm/bindings/apollo file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/dg_AViiON 0444 lib/Xm/bindings/dg_AViiON file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/doubleclick 0444 lib/Xm/bindings/doubleclick file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/hitachi 0444 lib/Xm/bindings/hitachi file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/hp 0444 lib/Xm/bindings/hp file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/ibm 0444 lib/Xm/bindings/ibm file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/intergraph 0444 lib/Xm/bindings/intergraph file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/intergraph17 0444 lib/Xm/bindings/intergraph17 file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/megatek 0444 lib/Xm/bindings/megatek file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/motorola 0444 lib/Xm/bindings/motorola file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/ncr_at 0444 lib/Xm/bindings/ncr_at file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/ncr_vt 0444 lib/Xm/bindings/ncr_vt file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/sgi 0444 lib/Xm/bindings/sgi file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/siemens_9733 0444 lib/Xm/bindings/siemens_9733 file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/siemens_wx200 0444 lib/Xm/bindings/siemens_wx200 file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/sony 0444 lib/Xm/bindings/sony file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/sun 0444 lib/Xm/bindings/sun file bin bin di---- 378 cde_dt
/usr/dt/lib/bindings/tek 0444 lib/Xm/bindings/tek file bin bin di---- 378 cde_dt
/usr/dt/config/Xsession.d/0040.xmbind 0444 osf/xmbind/0040.xmbind file bin bin di---- 378 cde_dt
/usr/dt/examples 0444 /usr/dt/share/examples sym_link bin bin di---- 378 cde_dt
	EOF
}
HandleOption()
{
  while [ $# -ne 0 ]; do
    case $1 in
        -e) OPERATION="configure"
            shift;
            ;;
	-d) OPERATION="deconfigure"
	    shift;
	    ;;
	-v) OPERATION="verify"
	    shift;
	    ;;
	-s) OPERATION="size"
	    shift;
	    ;;
    esac
  done
}

doDttermTerminfo()
{
    if [ -f $DT_TOP/config/dtterm.ti ]
    then
	tic $DT_TOP/config/dtterm.ti
	if [ -f /usr/lib/terminfo/d/dtterm ]
	then
	    chown bin /usr/lib/terminfo/d/dtterm
	    chgrp bin /usr/lib/terminfo/d/dtterm
	    chmod 444 /usr/lib/terminfo/d/dtterm
	else
	    echo "Unable to compile $DT_TOP/config/dtterm.ti"
	fi
    else
	echo "Unable to find $DT_TOP/config/dtterm.ti"
    fi
}

#############################################################################
#
#				Main Body
#
##############################################################################

PRODUCT=CDE
FILESET=CDE-RUN

DT_TOP=/usr/dt
DT_CONFIG_TOP=/etc/dt
DT_TEMP_TOP=/var/dt
ROOT=/
DO_CONFIGURATION=""

retval=0

APPCONFIG=appconfig
APPCONFIG_DIRS="appmanager help icons types"
PRINTERS=""
DEFAULT_PRINTER="DtPrint"

  HandleOption $*

  if [ "$OPERATION" = "configure" ]
  then

    echo "Configuring for CDE-RUN..."

#
# create the /var/dt directory
#
    if [ ! -d $DT_TEMP_TOP/$APPCONFIG/appmanager ]
    then
	mkdir -p $DT_TEMP_TOP/$APPCONFIG/appmanager
    fi
    cd $DT_TEMP_TOP
    mv $APPCONFIG/appmanager .hidden-appmanager
    chmod -R 755 *
    chmod 755 .hidden-appmanager
    chown -R bin *
    chgrp -R bin *
    mv .hidden-appmanager $APPCONFIG/appmanager
    chmod 755 .
    chown bin .
    chgrp bin .


#
# create the /etc/dt and its config directory
#

    umask 022

    if [ ! -d $DT_CONFIG_TOP ]
    then
	mkdir -p $DT_CONFIG_TOP
	chmod 755 $DT_CONFIG_TOP
    fi
    if [ ! -d $DT_CONFIG_TOP/config ]
    then
	mkdir -p $DT_CONFIG_TOP/config
    fi

    CreateAppConfigDirectory

#
# ConfigurePrintersDir
#
    env LANG=C /usr/dt/bin/dtprintinfo -populate

#
# Configure Xsession.d
#

    cd $DT_CONFIG_TOP/config
    if [ ! -d Xsession.d ]
    then
	mkdir Xsession.d
    fi

    cd $DT_CONFIG_TOP
    chmod -R 755 *

    FixInetdDotConf

    FixEtcRpc

#	After adding the Calendar Manager to the inetd service list, the inet
#	daemon needs to reread its configuration.

    /etc/inetd -c

    doDttermTerminfo

  elif [ "$OPERATION" = "deconfigure" ]
  then

    echo "de-Configuring CDE-RUN..."

    /etc/inetd -k

    KillIt "rpc.cmsd"

    /etc/inetd

    UnfixInetdDotConf

    UnfixEtcRpc

#	After removing the Calendar Manager from the inetd service list, the
#	inet daemon needs to reread its configuration.

    /etc/inetd -c

    rm -f /usr/lib/terminfo/d/dtterm
    rm -rf $DT_TEMP_TOP/*

    RemoveRunFiles

    VerifyInstalledFiles

  elif [ "$OPERATION" = "verify" ]
  then

    VerifyInstalledFiles

  fi

  return $retval
