/* XPM */
/* $XConsortium: popupwin.pm /main/3 1996/12/18 01:18:30 cde-hit $ */
static char * popupwin_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 32 8 1 0 0",
/* colors */
"     s iconGray4     m white c #949494949494",
".	s iconColor1	m black	c black",
"X    s iconGray8     m black c #212121212121",
"o    s iconGray2     m white c #bdbdbdbdbdbd",
"O	c #C3C3C3C3C3C3",
"+	c #8C8C8C8C8C8C",
"@	c #D9D9D9D9D9D9",
"#	c #7E7E7E7E7E7E",
/* pixels */
"     .                                         X",
" ooo .                                         X",
" ooo .                                         X",
" ... .                                         .",
"     .                                         .",
"................................................",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .                                           O+.",
" .  @@@@@@@@@@@@. @@@@@@@@@@@@. @@@@@@@@@@@. O+.",
" .  @###########. @###########. @##########. O+.",
" .  @###########. @###########. @##########. O+.",
" .  ............. ............. ............ O+.",
" .oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO+.",
" .+++++++++++++++++++++++++++++++++++++++++++++.",
" ..............................................."};
