# $XConsortium: Makefile /main/3 1996/05/13 11:41:59 drk $
# use the load* target to force building

all::

findnewrcs.700.90:findnewrcs.c
	rm -f $@
	cc +DA1.0 +O1 -o $@ findnewrcs.c
loadfindnewrcs.700.90:
	rm -f findnewrcs.700.90
	cc +DA1.0 +O1 -o findnewrcs.700.90 findnewrcs.c

findnewrcs.700.807:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.700.807:
	rm -f findnewrcs.700.807
	cc +O1 -o findnewrcs.700.807 findnewrcs.c

findnewrcs.800.90:findnewrcs.c
	rm -f $@
	cc +DA1.0 +O1 -o $@ findnewrcs.c
loadfindnewrcs.800.90:
	rm -f findnewrcs.800.90
	cc +DA1.0 +O1 -o findnewrcs.800.90 findnewrcs.c

findnewrcs.800.80:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.800.80:
	rm -f findnewrcs.800.80
	cc +O1 -o findnewrcs.800.80 findnewrcs.c

findnewrcs.800.70:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.800.70:
	rm -f findnewrcs.800.70
	cc +O1 -o findnewrcs.800.70 findnewrcs.c

findnewrcs.300.90:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.300.90:
	rm -f findnewrcs.300.90
	cc +O1 -o findnewrcs.300.90 findnewrcs.c

findnewrcs.300.80:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.300.80:
	rm -f findnewrcs.300.80
	cc +O1 -o findnewrcs.300.80 findnewrcs.c

findnewrcs.SunOS:findnewrcs.c
	rm -f $@
	cc -o $@ findnewrcs.c
loadfindnewrcs.SunOS:
	rm -f findnewrcs.SunOS
	cc -o findnewrcs.SunOS findnewrcs.c

findnewrcs.SunOS_PPC:findnewrcs.c
	rm -f $@
	cc -o $@ findnewrcs.c
loadfindnewrcs.SunOS_PPC:
	rm -f findnewrcs.SunOS_PPC
	cc -o findnewrcs.SunOS_PPC findnewrcs.c

findnewrcs.AIX:findnewrcs.c
	rm -f $@
	cc -o $@ findnewrcs.c
loadfindnewrcs.AIX:
	rm -f findnewrcs.AIX
	cc -o findnewrcs.AIX findnewrcs.c

findnewrcs.UNIX_SV:findnewrcs.c
	rm -f $@
	cc -DUSL -o $@ findnewrcs.c
loadfindnewrcs.UNIX_SV:
	rm -f findnewrcs.UNIX_SV
	cc -o findnewrcs.UNIX_SV findnewrcs.c

findnewrcs.UNIX_System_V:findnewrcs.c
	rm -f $@
	cc -DUSL -o $@ findnewrcs.c
loadfindnewrcs.UNIX_System_V:
	rm -f findnewrcs.UNIX_System_V
	cc -o findnewrcs.UNIX_System_V findnewrcs.c

findnewrcs.HP-UX:findnewrcs.c
	rm -f $@
	cc +O1 -o $@ findnewrcs.c
loadfindnewrcs.HP-UX:
	rm -f findnewrcs.HP-UX
	cc +O1 -o findnewrcs.HP-UX findnewrcs.c
