# %%  (c) Copyright 1993, 1994 Hewlett-Packard Company			
# %%  (c) Copyright 1993, 1994 International Business Machines Corp.	
# %%  (c) Copyright 1993, 1994 Sun Microsystems, Inc.			
# %%  (c) Copyright 1993, 1994 Novell, Inc. 				
# %%  $XConsortium: Makefile.test /main/3 1995/10/23 09:44:34 rswiston $ 			 				
# Use this Makefile to build the demos against the system in 
# $(TT_DIR)/proto.

CPPFLAGS += -I../../proto/include
LDFLAGS += -L../../proto/lib

include Makefile.shipped
