/* XPM */
/* $XConsortium: template_icon.pm /main/3 1995/07/18 16:06:52 drk $ */
static char * template_icon_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray6     m black c #636363636363",
/* pixels */
"                                ",
"   ............                 ",
"   .XXXXXXXXXXo                 ",
"   .XXXXXXXXXXo                 ",
"   .XXXXXXXXXXo                 ",
"   .XXXXXXXXXXo                 ",
"   .XXXXXXXXXXo      .          ",
"   .XXXXXXXXXXo      .o         ",
"   .XXXXXXXXXXo     .XXo        ",
"   .XXXXXXXXXXo     .XXXo       ",
"   .XXXXXXXXXXo    .XXXXo       ",
"   .XXXXXXXXXXo    .XXXXXo      ",
"   .ooooooooooo   .XXXXXXXo     ",
"                  .XXXXXXXo     ",
"                 .XXXXXXXXXo    ",
"                 .XXXXXXXXXo    ",
"                .XXXXXXXXXXXo   ",
"                .oooooooooooo   ",
"                                ",
"           .......              ",
"          .XXXXXXXo             ",
"         .XXXXXXXXXo            ",
"        .XXXXXXXXXXXo           ",
"        .XXXXXXXXXXXo           ",
"        .XXXXXXXXXXXo           ",
"        .XXXXXXXXXXXo           ",
"        .XXXXXXXXXXXo           ",
"        .XXXXXXXXXXXo           ",
"         .XXXXXXXXXo            ",
"          .XXXXXXXo             ",
"           ooooooo              ",
"                                "};
