/* XPM */
/* $XConsortium: template.l.pm /main/3 1995/07/18 16:06:22 drk $ */
static char * template_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 4 1 0 0",
/* colors */
" 	s none	m none	c none",
".    s iconGray1     m white c #dededededede",
"X    s iconGray2     m white c #bdbdbdbdbdbd",
"o    s iconGray6     m black c #636363636363",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"        ..............                          ",
"        .XXXXXXXXXXXXo                          ",
"        .XXXXXXXXXXXXo                          ",
"        .XXXXXXXXXXXXo                          ",
"        .XXXXXXXXXXXXo                          ",
"        .XXXXXXXXXXXXo           .              ",
"        .XXXXXXXXXXXXo          .Xo             ",
"        .XXXXXXXXXXXXo          .XXo            ",
"        .XXXXXXXXXXXXo         .XXXo            ",
"        .XXXXXXXXXXXXo         .XXXXo           ",
"        .XXXXXXXXXXXXo        .XXXXXo           ",
"        .XXXXXXXXXXXXo        .XXXXXXo          ",
"        .XXXXXXXXXXXXo       .XXXXXXXo          ",
"        .ooooooooooooo       .XXXXXXXXo         ",
"                            .XXXXXXXXXXo        ",
"                            .XXXXXXXXXXo        ",
"                           .XXXXXXXXXXXXo       ",
"                           .XXXXXXXXXXXXo       ",
"                          .XXXXXXXXXXXXXXo      ",
"                          .XXXXXXXXXXXXXXo      ",
"                         .ooooooooooooooooo     ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                .........                       ",
"               .XXXXXXXXXo                      ",
"              .XXXXXXXXXXXo                     ",
"             .XXXXXXXXXXXXXo                    ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"            .XXXXXXXXXXXXXXXo                   ",
"             .XXXXXXXXXXXXXo                    ",
"              .XXXXXXXXXXXo                     ",
"               .XXXXXXXXXo                      ",
"                ooooooooo                       ",
"                                                ",
"                                                ",
"                                                "};
