$ $XConsortium: Mrm.msg /main/4 1996/11/19 19:35:59 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 
$ (c) Copyright 1996 Digital Equipment Corporation.
$ (c) Copyright 1996 Hewlett-Packard Company.
$ (c) Copyright 1996 International Business Machines Corp.
$ (c) Copyright 1996 Sun Microsystems, Inc.
$ (c) Copyright 1996 Novell, Inc. 
$ (c) Copyright 1996 FUJITSU LIMITED.
$ (c) Copyright 1996 Hitachi.
$ 

$ This message catalog contains messages issued by Motif Mrm library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.

$quote "

$set MS_Mrm

MSG__0000 "Allocazione vettore fallita."

MSG__0001 "Allocazione buffer fallita."

MSG__0002 "Buffer non valido"

MSG__0003 "Get block fallito"

MSG__0004 "Put block fallito"

MSG__0005 "Intestazione di record non valida."

MSG__0006 "Contesto non valido"

MSG__0007 "Immissione dati non valida"

MSG__0008 "Immissione segmento non valida"

MSG__0009 "Tipo di dati sconosciuto"

MSG__0010 "Tipo di record non previsto"

MSG__0011 "La versione del file %s è superiore alla versione Mrm  %s."

MSG__0012 "Questo non è il record  di intestazione."

MSG__0013 "L'indice di risorse non è compreso nell'intervallo consentito."

MSG__0014 "puntatore dati NULL"

MSG__0015 "Overflow record non ammesso"

MSG__0016 "Incoerenze nei record GT"

MSG__0017 "Incoerenza nei record LT"

MSG__0018 "Tipo di record non previsto nei livelli superiori"

MSG__0019 "Record al di fuori EOF"

MSG__0020 "Impossibile swap il record #%d tipo %d"

MSG__0021 "Tipo %d (non implementato) incontrato nella voce Callback %d"

MSG__0022 "L'argomento %d non è implementato"

MSG__0023 "id gerarchia è NULL"

MSG__0024 "Gerarchia non valida"

MSG__0025 "Modulo di interfaccia utente non è valido"

MSG__0026 "Widget di record non è valido"

MSG__0027 "Allocazione del contesto è fallita"

MSG__0028 "Convalida fallita"

MSG__0029 "Dimensione della risorsa è troppo grande"

MSG__0030 "Display non è ancora aperto"

MSG__0031 "Impossibile aprire il file %s"

MSG__0032 "Impossibile aprire il file %s - versione UID incompatibile"

MSG__0033 "XmGetPixmap fallito con XmUNSPECIFIED_PIXMAP per %s"

MSG__0034 "XCreateImage fallito durante la conversione di IconImage"

MSG__0035 "XCreatePixmap fallito durante la conversione di IconImage"

MSG__0036 "XCreateGC fallito durante la conversione di IconImage"

MSG__0037 "XtMalloc fallito durante la conversione di IconImage"

MSG__0038 "Impossibile caricare il colore '%s'"

MSG__0039 "Impossibile convertire il colore/pixel RGB (rosso, verde, blu) '%d,%d,%d'"

MSG__0040 "Il tipo di descrittore del colore non è valido"

MSG__0041 "Lo stato monocromatico non è ammesso per l'elemento colore %d"

MSG__0042 "La variabile letterale '%s' è introvabile"
$ literal in this context means a named value.

MSG__0043 "Il contesto della risorsa non è valido"

MSG__0044 "Troppi widget"

MSG__0045 "L'indice superiore è al di fuori dei limiti"

MSG__0046 "Allocazione dell'elenco è fallita"

MSG__0047 "Allocazione dell'elenco vettoriale è fallita"

MSG__0048 "Riallocazione dei vettori è fallita"

MSG__0049 "Allocazione delle stringhe è fallita"

MSG__0050 "Il file UID è obsoleto - manca la tabella di compressione"

MSG__0051 "Impossibile trovare il descrittore di classe per la classe %s"

MSG__0052 "Impossibile trovare il widget '%s' nell'indice"

MSG__0053 "Impossibile trovare il widget RID '%x'"

MSG__0054 "?? Tipo di chiave SCONOSCIUTO: %d"

MSG__0055 "Tipo di widget sconosciuto"

MSG__0056 "Impossibile identificare uno dei widget specificati nella chiamata automatica Creazione"

MSG__0057 "Non è possibile utilizzare Fixup per le chiamate automatiche di Creazione"

MSG__0058 "Il tipo di figlio è sconosciuto."

MSG__0059 "Figlio introvabile."

MSG__0060 "Il widget specificato non è incluso nell'indice"

MSG__0061 "Impossibile convertire il colore/pixel/pixel '%s'"

MSG__0062 "Impossibile decomprimere il codice della stringa %d"

MSG__0063 "Gruppo di risorse non gestite"

MSG__0064 "Impossibile convertire ASCIZ '%s' in una stringa composta"

MSG__0065 "Impossibile analizzare la tabella di traduzioni '%s'"

MSG__0066 "Impossibile convertire l'identificatore '%s'"

MSG__0067 "Errore interno: caso MrmRtypeIconImage incontrato"

MSG__0068 "Errore interno: caso MrmRtypeXBitmapFile incontrato"

MSG__0069 "Errore interno: impossibile convertire Display in String"

MSG__0070 "Impossibile convertire il font '%s'"

MSG__0071 "Impossibile convertire il fontset '%s'"
$ please do not translate fontset.

MSG__0072 "Impossibile aprire uno o più font per il fontset '%s'"

MSG__0073 "Impossibile aggiungere il font '%s' della fontlist all'elenco"

MSG__0074 "Impossibile aggiungere il fontset '%s' della fontlist all'elenco"

MSG__0075 "Impossibile convertire il nome della classe."

MSG__0076 "Impossibile convertire la stringa keysym '%s' in KeySym"

MSG__0077 "Impossibile trovare la variabile letterale '%s'"

MSG__0078 "Impossibile trovare la variabile letterale RID '%x'"

MSG__0079 "Tipo di chiave letterale %d è sconosciuto"

MSG__0080 "Tipo di letterale ColorTable %d non è valido"

MSG__0081 "Tipo di letterale ColorTable non valido, codice %d"

MSG__0082 "Tipo di letterale Color %d non è valido"

MSG__0083 "Tipo di ColorItem non valido, codice %d"

MSG__0084 "Routine di chiamata '%s' non è registrata"

MSG__0085 "Il widget specificato non si trova nell'indice"

MSG__0086 "Impossibile trovare la risorsa widget '%s' nell'indice"

MSG__0087 "Impossibile trovare la risorsa widget RID '%x'"

MSG__0088 "Tipo di chiave della risorsa è sconosciuto %d"

MSG__0089 "Impossibile creare un'istanza della struttura widget"

MSG__0090 "Nome di classe definita dall'utente è NULL"

MSG__0091 "Codice di classe non valido"

MSG__0092 "Troppi argomenti"

MSG__0093 "Codice di compressione non valido"

MSG__0094 "Tipo non gestito o non valido"

MSG__0095 "Vettore troppo grande"

MSG__0096 "Il nome della routine è vuoto"

MSG__0097 "Char8Vector non è ancora implementato"

MSG__0098 "CStringVector non è ancora implementato"

MSG__0099 "Troppi processi figli"

MSG__0100 "Descrittore dell'elenco di processi figli è null"

MSG__0101 "L'indice dei processi figli è al di fuori dei limiti previsti"

MSG__0102 "Indice Null"

MSG__0103 "Il tipo di chiave non è valido"

MSG__0104 "L'indice Arg è al di fuori dei limiti previsti"

MSG__0105 "Record di widget/gadget non valido"

MSG__0106 "Descrittore di chiamata non valido"

MSG__0107 "Un elemento della chiamata è al di fuori dei limiti previsti"

MSG__0108 "Impossibile decomprimere il codice della stringa %d"

MSG__0109 "Troppi elementi"

MSG__0110 "Impossibile convertire una stringa multibyte in una stringa widecharacter"

MSG__0111 "Impossibile convertire un numero intero '%d' in icona"

MSG__0112 "Impossibile convertire in icona"

MSG__0113 "Impossibile aprire il buffer - versione UID incompatibile"

MSG__0114 "Impossibile aprire il buffer"

MSG__0115 "Impossibile convertire le unità in XmPIXELS: formato o tipo di unità non valido"

MSG__0116 "Impossibile convertire le unità in XmPIXELS: overflow a virgola mobile"

MSG__0117 "File UID contiene una stringa di versione  %s non valida.  Impossibile leggere il file."

MSG__0118 "La versione Mrm %s è maggiore della versione del file %s.\nCompilare il file UIL di nuovo."

MSG__0119 "Oggetto '%s' dichiarato PRIVATE."

