$ $XConsortium: Uil.msg /main/6 1996/11/21 17:16:33 rws $

$quote "

$set UIL_SET1


UIL_0 "l'opzione duplicata \"%s\"  è stata ignorata"

UIL_1 "l'opzione sconosciuta \"%s\"  è stata ignorata"

UIL_2 "il file di origine UIL: %s è stato ignorato"

UIL_3 "errore di apertura del file di origine: %s"

UIL_4 "errore di lettura nella riga successiva del file di origine: %s"

UIL_5 "Errore interno: %s"

UIL_6 "riga troncata a %d caratteri"

UIL_7 "valore di %s non è compreso nell'intervallo consentito %s"

UIL_8 "%s non terminato %s"

UIL_9 "il carattere \\%d\\  non è stampabile ed è stato ignorato"

UIL_10 "la sequenza sconosciuta \"%s\" è stata ignorata"

UIL_11 "la sequenza escape  \"\\%c\" - \\ è sconosciuta ed è stata ignorata"

UIL_12 "il nome eccede i %d caratteri - troncato: %s"

UIL_13 "memoria virtuale del compiler è esaurita"

UIL_14 " È stato incontrato un token %s inatteso - si riprenderà l'analisi dopo \"%c\""

UIL_15 "%s %s deve essere definito prima di essere specificato"

UIL_16 "il contesto richiede %s - %s  è stato specificato"

UIL_17 "%s non è stato ancora implementato"

UIL_18 "Il valore %s  è stato incontrato. Attesa del valore %s"

UIL_19 "il %s %s non è supportato per l'oggetto %s"

UIL_20 "%s %s ha la precedenza sulla la definizione esistente in %s %s"

UIL_21 "il nome %s è già stato definito %s"

UIL_22 "un valore utilizzato in questo contesto deve essere privato"

UIL_23 "la procedura %s è già stata dichiarata con %d argomenti"

UIL_24 "valore %s incontrato - l'argomento della procedura %s deve essere del valore %s"

UIL_25 "Trovato: %s %s Attesa di: %s %s"

UIL_26 "%s %s non è stato definito"

UIL_27 "%s %s è già stato specificato per questo %s %s"

UIL_28 "elemento %s non ammesso in %s %s"

UIL_29 "Compilazione interrotta - Correggere gli errori precedenti"

UIL_30 "Errore interno - Inviare un rapporto difetti"

UIL_31  

UIL_32 "%s mancante dopo l'opzione \"%s\" "

UIL_33 "errore di apertura del file elenco: %s"

UIL_34 "errore di scrittura del file elenco: %s"

UIL_35 "struttura modulo non valida - verificare la sintassi del modulo UIL"

UIL_36 "troppi file di origine sono aperti: %s"

UIL_37 "la riga di origine contiene un carattere null"

UIL_38 "errori: %d  avvisi: %d  informativi: %d"

UIL_39 "errore di apertura del file UID: %s"

UIL_40 "non è stato prodotto nessun file UID"

UIL_41 "widget %s non supporta la procedura di creazione"

UIL_42 "la specificazione di widget %s non può contenere una routine di creazione"

UIL_43 "la dichiarazione di widget %s richiede una routine di creazione"

UIL_44 "la stringa non può contenere un carattere NULL"

UIL_45 "widget %s fa parte di una definizione circolare"

UIL_46 "non è stato specificato un file di origine"

UIL_47 "%s %s supporta solo un %s %s"

UIL_48 "%s widget supporta solo un controllo singolo"

UIL_49 "set di caratteri sconosciuto"

UIL_50 "posizionare la clausula di paese prima delle altre clausule"

UIL_51 "la stringa Colore deve consistere di un solo carattere alfabetico"

UIL_52 "questo carattere è già in uso nella tabella per indicare un alto colore "

UIL_53 "riga %d deve avere la stessa larghezza della riga 1"

UIL_54 "riga %d, colonna %d: carattere \"%c\" non si trova nella tabelle colori"

UIL_55 "troppi %ss in %s, il limite è %d"

UIL_56 "Subqualifier not allowed with negated qualifier"

UIL_57 "gadget %s non è supportato - verrà sostituito widget %s"

UIL_58 "il tipo %s non è valido per %s"

UIL_59 "È possibile che questo set di caratteri non verrà supportato nelle versioni future del software."

UIL_60 "la restrizione %s  è supportata per il %s %s"

UIL_61 "troppe opzioni \"%s\", il limite è %d"

UIL_62 "errore di chiusura del file di origine: %s"

UIL_63 "il valore %s ha una definizione circolare"

UIL_64 "il nome predefinito %s verrà ignorato"

UIL_65 "l'argomento %s non supporta i valori enumerati"

UIL_66 "l'argomento %s non supporta il valore enumerato %s"

UIL_67 "$LANG contiene un set di caratteri sconosciuto"

UIL_68 "la gerarchia di controlli dell'oggetto %s punta su se stessa"

UIL_69 "Il valore %s è troppo grande per il buffer"

UIL_70 "È necessario %s prima di specificarlo"

UIL_71 "impossibile convertire il tipo %s nel tipo %s"

UIL_72 "%s non è valido"

UIL_V2_73 "errore di lettura del database binario"

UIL_V2_74 "il database binario è stato compilato con una versione futura"

UIL_V2_75 "errore di apertura del file database: %s"

UIL_V2_76 "errore di scrittura del file UID: %s"

UIL_V2_77 "'%s' è un nome di classe Toolkit valido"

UIL_78 "il nome del file da includere non è valido"

UIL_V2_79 "unità incompatibili con le operazioni aritmetiche."

UIL_V2_80 "%s è usato come nome charset; %s è usato come componente del charset"


$set UIL_VALUES

UIL_VAL_0 "** errore **"

UIL_VAL_1 "** sconosciuto **"


$set UIL_SET_MISC


UIL_INF "Informazioni: "

UIL_WAR "Avviso: "

UIL_ERR "Errore: "

$ UIL_SEV "Severe: "
UIL_SEV "Errore grave: "
UIL_MISC_0 "\t\t riga: %d  file: %s"

