$ $XConsortium: Xm.msg /main/11 1996/12/06 13:57:25 rws $
$ 
$  @OSF_COPYRIGHT@
$  COPYRIGHT NOTICE
$  Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
$  ALL RIGHTS RESERVED (MOTIF). See the file named COPYRIGHT.MOTIF for
$  the full copyright text.
$ 

$ This message catalog contains messages issued by Motif toolkit library.
$ Consult X-Window systems, OSF/MOTIF Programmer's Guide and OSF/MOTIF
$ Programmer's Reference Manual for technical terms if you have any
$ doubts about their meanings.
$ Do not translate variables such as %s, %d %s ... etc.
$ Do not translate Motif resource name, such as XmNlabelType.
$ Special terms with capital letter(s) should not be translated.
$ "False" and "True" are keywords. Do not translate.

$quote " 


$set MS_ArrowButton

MSG_ArrowButton_1000 "La direzione della freccia non è corretta."
$ MSG_ArrowButton_1000 message is obsolete - DO NOT localize this message.

$set MS_BulletinB

MSG_BulletinB_1000 "Tecnica di ridimensionamento non corretta."
$ MSG_BulletinB_1000 message is obsolete - DO NOT localize this message.

$ MSG_BulletinB_0001 "Stile di dialogo non corretto."
MSG_BulletinB_0001 "Stile di dialogo deve essere XmDIALOG_MODELESS."

MSG_BulletinB_1001 "Tipo di ombreggiatura non corretto."
$ MSG_BulletinB_1001 message is obsolete - DO NOT localize this message.

MSG_BulletinB_1002 "Lista dei font vuota (nessun valore predefinito per la shell)"
$ MSG_BulletinB_1002 message is obsolete - DO NOT localize this message.


$set MS_CascadeB

MSG_CascadeB_1000 "XmCascadeButton deve avere il tipo corretto di\n\
XmRowColumnWidgetClass principale."
$ MSG_CascadeB_1000 message is obsolete - DO NOT localize this message.

$ MSG_CascadeB_0001 "Solo gli XmMENU_PULLDOWN XmRowColumnWidgets possono essere submenus."
MSG_CascadeB_0001 "Solo gli XmRowColumnWidgets del tipo XmMENU_PULLDOWN possono essere submenus."
$ please do not translate submenus. 

MSG_CascadeB_0002 "XmNmappingDelay deve essere maggiore o uguale a zero."

MSG_CascadeB_0000 "XmCascadeButton[Gadget] deve avere un padre XmRowColumn con \n\
XmNrowColumnType XmMENU_PULLDOWN, XmMENU_POPUP, XmMENU_BAR oppure XmMENU_OPTION."

MSG_CascadeB_0003 "XtGrabPointer non riuscito."

MSG_RowColText_0024 "XtGrabKeyboard non riuscito."


$set MS_Command

MSG_Command_0000 "Il tipo di riquadro di dialogo deve essere XmDIALOG_COMMAND."

MSG_Command_0001 "Tipo di figlio non valido.\n\
Il widget Command non possiede questo figlio."
$ please do not translate Command.

MSG_Command_0002 "XmString vuoto o NULL."

MSG_Command_0003 "XmString vuoto o NULL è stato passato a XmCommandAppendValue."

MSG_Command_0004 "XmNmustMatch è sempre False per i widget Command."
$ please do not translate False or Command. 

MSG_Command_0005 "XmNhistoryMaxItems deve essere un numero positivo maggiore di zero."


$set MS_CutPaste

MSG_CutPaste_0000 "XmClipboardStartCopy() deve essere chiamato prima di XmClipboardCopy()"

MSG_CutPaste_0001 "XmClipboardStartCopy() deve essere chiamato prima di XmClipboardEndCopy()"

MSG_CutPaste_0002 "Troppi formati in XmClipboardCopy()"

MSG_CutPaste_0003 "ClipboardBadDataType"
$ please do not translate ClipboardBadDataType.

MSG_CutPaste_0004 "tipo di dati non corretto"

MSG_CutPaste_0005 "ClipboardCorrupt"
$ please do not translate ClipboardCorrupt.

MSG_CutPaste_0006 "errore interno - Struttura dei dati corrotta"

MSG_CutPaste_0007 "ClipboardBadFormat"
$ please do not translate ClipboardBadFormat

MSG_CutPaste_0008 "Errore - la lunghezza del formato registrato deve essere 8, 16, o 32"

MSG_CutPaste_0009 "Errore - il nome del formato registrato non può essere nullo"


$set MS_DialogS

MSG_DialogS_0000 "Il widget DialogShell supporta un solo figlio RectObj"
$ please do not translate DialogShell and RectObj.

MSG_DialogS_1000 "Non sono ammessi gadget nella Shell"
$ MSG_DialogS_1000 message is obsolete - DO NOT localize this message.


$set MS_DrawingA

MSG_DrawingA_1001 "La larghezza o l'altezza del margine non possono avere un valore negativo."
$ MSG_DrawingA_1001 message is obsolete - DO NOT localize this message.

MSG_DrawingA_1002 "Tecnica di ridimensionamento non corretta."
$ MSG_DrawingA_1002 message is obsolete - DO NOT localize this message.


$set MS_Form

MSG_Form_0000 "La base della frazione non può essere zero."

MSG_Form_1000 "Tipo di allegato Form non corretto."
$ MSG_Form_1000 message is obsolete - DO NOT localize this message.

MSG_Form_1001 "Non è possibile fissare limiti per i widget non ridimensionabili."
$ MSG_Form_1001 message is obsolete - DO NOT localize this message.

MSG_Form_1002 "Il widget Attachment non può essere nullo."
$ MSG_Form_1002 message is obsolete - DO NOT localize this message.
$ please do not translate Attachment

MSG_Form_0002 "Dipendenza circolare nei figli del widget Form.\n\
Controllare che non ci siano dipendenze circolari tra i figli."
$ please do not translate Form. 

MSG_Form_1006 "È stato assegnato un bordo a un widget, ma non è stato specificato alcun widget."
$ MSG_Form_1006 message is obsolete - DO NOT localize this message.

MSG_Form_0003 "Abbandono della sincronizzazione dopo 10000 iterzioni.\n\
Contollare possibili conflitti nei figli di questo widget Form."
$ please do not translate Form.

MSG_Form_0004 "Il widget Attachment deve provenire dallo stesso processo principale del widget."
$ please do not translate Attachment
$ MSG_Form_0004 message is obsolete - DO NOT localize this message.


$set MS_Frame

MSG_Frame_1000 "Inserire solo un figlio per ogni cornice."
$ please do not translate Frame.
$ MSG_Frame_1000 message is obsolete - DO NOT localize this message.

MSG_Frame_1001 "Larghezza del margine non valida."
$ MSG_Frame_1001 message is obsolete - DO NOT localize this message.

MSG_Frame_1002 "Altezza del margine non valida."
$ MSG_Frame_1002 message is obsolete - DO NOT localize this message.


$set MS_Gadget

MSG_Gadget_1000 "Spessore di evidenziazione non valido."
$ MSG_Gadget_1000 message is obsolete - DO NOT localize this message.

MSG_Gadget_1001 "Il tipo di unità non è corretto."
$ MSG_Gadget_1001 message is obsolete - DO NOT localize this message.

MSG_Gadget_1002 "Spessore di ombreggiatura non valido."
$ MSG_Gadget_1002 message is obsolete - DO NOT localize this message.

MSG_Gadget_1003 "Impossibile impostare la risorsa pixmap senza specificare un valore."
$ MSG_Gadget_1003 message is obsolete - DO NOT localize this message.

MSG_Gadget_0000 "Impossibile modificare XmNlayoutDirection dopo l'inizializzazione."


$set MS_Label

MSG_Label_1001 "XmNlabeType non valido."
$ MSG_Label_1001 message is obsolete - DO NOT localize this message.

MSG_Label_1002 "Valore non ammesso in XmNalignment"
$ MSG_Label_1002 message is obsolete - DO NOT localize this message.

MSG_Label_1003 "Valore non ammesso in XmNstringDirection"
$ MSG_Label_1003 message is obsolete - DO NOT localize this message.

MSG_Label_0003 "XmNlabelString deve essere un Compound String."
$ please do not translate Compound String.

MSG_Label_0004 "XmNacceleratorText deve essere un Compound String."
$ please do not translate Compound String.


$set MS_List

MSG_List_0000 "Dopo la modifica, XmNvisibleItemCount deve essere almeno 1."

MSG_List_1001 "Selection Policy non valida."
$ MSG_List_1001 message is obsolete - DO NOT localize this message.

MSG_List_1002 "Size Policy non valida."
$ MSG_List_1002 message is obsolete - DO NOT localize this message.

MSG_List_1003 "ScrollBar Display Policy non valida."
$ MSG_List_1003 message is obsolete - DO NOT localize this message.

MSG_List_1004 "String Direction non valida."
$ MSG_List_1004 message is obsolete - DO NOT localize this message.

MSG_List_0005 "Impossibile cambiare XmNlistSizePolicy dopo l'inizializzazione."

MSG_List_0006 "Dopo la modifica, XmNitemCount deve essere positivo o zero."
$ non-negative means zero or positive.

MSG_List_1007 "Font NULL in SetValues ignorato."
$ MSG_List_1007 message is obsolete - DO NOT localize this message.
$ please do not translate SetValues

MSG_List_0007 "Le voci da cancellare non si trovano nella lista."

MSG_List_1009 "Nessuna Horizontal Scrollbar da impostare."
$ MSG_List_1009 message is obsolete - DO NOT localize this message.

MSG_List_1010 "Valore di Margin non ammesso."
$ MSG_List_1010 message is obsolete - DO NOT localize this message.

MSG_List_0008 "XmNlistSpacing deve essere positivo o zero."

MSG_List_0009 "Impossibile impostare XmNitems a NULL quando XmNitemCount è positivo."

MSG_List_0010 "XmNselectedItemCount non può essere negativo."

MSG_List_0011 "Impossibile impostare XmNselectedItems a NULL quando XmNselectedItemCount \
è positivo."

MSG_List_0012 "XmNtopItemPosition deve essere un numero positivo o zero."

MSG_List_0013 "XmNitems e XmNitemCount non corrispondono!"

MSG_List_1017 "Impossibile lasciare la modalità di aggiunta nella selezione multipla."
$ MSG_List_1017 message is obsolete - DO NOT localize this message.

MSG_List_0014 "XmNselectedPositionCount non può essere negativo."

MSG_List_0015 "Impossibile impostare XmNselectedPositions su NULL quando XmNselectedPositionCount \
è positivo."


$set MS_MainW

MSG_MainW_0000 "La MenuBar non può essere cambiata in NULL."
$ please do not translate MenuBar.

MSG_MainW_0001 "La CommandWindow non può essere cambiata in NULL."
$ please do not translate CommandWindow.

MSG_MainW_1003 "Margine negativo ignorato."
$ MSG_MainW_1003 message is obsolete - DO NOT localize this message.


$set MS_MenuShell

MSG_MenuShell_0000 "I widget MenuShell accettano solo i figli XmRowColumn."
$ please do not translate MenuShell.

MSG_MenuShell_0001 "Si è cercato di gestire un menu a tendina che non  è collegato a un pulsante Cascade."

MSG_MenuShell_0002 "XmPopup rechiede una sottoclasse di shellWidgetClass"
$ please do not translate shellWidgetClass.

MSG_MenuShell_0003 "XmPopdown rechiede una sottoclasse di shellWidgetClass"
$ please do not translate shellWidgetClass.

MSG_MenuShell_0004 "XtMenuPopup richiede un solo argomento."

MSG_MenuShell_0005 "XtMenuPopup supporta solo gli eventi del tipo ButtonPress, KeyPress o EnterNotify."
$ please do not translate ButtonPress, KeyPress or EnterNotify.

MSG_MenuShell_0006 "Impossibile trovare il widget popup \"%s\" in XtMenuPopup."

MSG_MenuShell_0007 "Impossibile trovare il widget \"%s\" in XtMenuPopdown."

MSG_MenuShell_0008 "XtMenuPopdown chiamato con più di 1 argomento."

MSG_MenuShell_0009 "Impossibile cambiare XmNlayoutDirection dopo l'inizializzazione."


$set MS_MessageB

MSG_MessageB_1001 "Dialog Type non valido."
$ MSG_MessageB_1001 message is obsolete - DO NOT localize this message.

MSG_MessageB_1002 "Default Button Type non valido."
$ MSG_MessageB_1002 message is obsolete - DO NOT localize this message.

MSG_MessageB_1003 "Alignment Type non valido."
$ MSG_MessageB_1003 message is obsolete - DO NOT localize this message.

MSG_MessageB_0003 "Tipo di figlio non valido; il widget non ha questo figlio."

MSG_MessageB_0004 "Non  è possibile cambiare il pulsante Annuallare (Cancel)."

MSG_MessageB_1006 "Usare XmNdefaultButtonType per impostare il pulsante predefinito MessageBox."
$ MSG_MessageB_1006 message is obsolete - DO NOT localize this message.


$set MS_PanedW

MSG_PanedW_0000 "Il valore minimo deve essere maggiore di 0."

MSG_PanedW_0001 "Il valore massimo deve essere maggiore di 0."

MSG_PanedW_0002 "Il valore minimo deve essere inferiore a quello massimo."

MSG_PanedW_0003 "I limiti non consentono un dimensionamento appropriato."
$ MSG_PanedW_0003 message is obsolete - DO NOT localize this message.

MSG_PanedW_0004 "Numero di parametri insufficienti nella chiamata automatica (sash)."

MSG_PanedW_0005 "Il primo parametro nella chiamata automatica sash non è valido."


$set MS_PWidget

MSG_PWI_1001 "La fontList non è definita"
$ MSG_PWI_1001 message is obsolete - DO NOT localize this message.
$ please do not translate fontList.


$set MS_Protocols

MSG_Protocols_0000 "Widget deve essere un VendorShell"
$ please do not translate VendorShell.

MSG_Protocols_0001 "La gestione dei protocolli esiste già"

MSG_Protocols_0002 "Troppi protocolli per questo widget;\n\
il limite è 32."


$set MS_PushB

MSG_PushB_1001 "Memoria insufficiente"
$ MSG_PushB_1001 message is obsolete - DO NOT localize this message.


$set MS_RowColumn

$ In this set, do not translate the word that starts with "XmN" or "Xm". 

MSG_RowColumn_1001 "Si è cercato di impostare la larghezza al valore zero.\n\
Verrà usato il valore predefinito 16."
$ MSG_RowColumn_1001 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0000 "Si è cercato di impostare l'altezza al valore zero. Richiest ignorata."

MSG_RowColumn_1003 "Si è cercato di impostare l'altezza al valore zero.\n\
Verrà usato il valore predefinito 16."
$ MSG_RowColumn_1003 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0001 "Si è cercato di impostare l'altezza al valore zero. Ignorato."

MSG_RowColumn_0002 "XmNhelpWidget impostato a NULL poiché non  è usato dai menu a scomparsa."

MSG_RowColumn_0003 "XmNhelpWidget impostato a NULL poiché non  è usato dai menu a tendina."

MSG_RowColumn_0004 "XmNhelpWidget impostato a NULL poiché non  è usato dai menu delle opzioni."

MSG_RowColumn_0005 "XmNhelpWidget impostato a NULL poiché non  è usato dai Work Areas."

MSG_RowColumn_1009 "Valore di XmNrowColumnType sconosciuto.\n\
Verrà impostato il valore WorkArea."
$ MSG_RowColumn_1009 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0007 "La gerarchia widget non è appropriata per questo XmNrowColumnType:\n\
Verrà impostato il valore XmWORK_AREA."

MSG_RowColumn_0008 "Si è cercato di cambiare XmNrowColumnType dopo l'inizializzazione. Operazione ignorata."

MSG_RowColumn_1012 "Valore di XmNorientation sconosciuto.\n\
Verrà usato il valore predefinito."
$ MSG_RowColumn_1012 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1013 "Si è cercato di impostare XmNorientation a un valore sconosciuto.\n\
Il valore verrà ignorato."
$ MSG_RowColumn_1013 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1014 "Valore di XmNpacking sconosciuto.\n\
Verrà usato il valore predefinito."
$ MSG_RowColumn_1014 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1015 "Si è cercato di impostare XmNpacking a un valore sconosciuto.\n\
Il valore verrà ignorato."
$ MSG_RowColumn_1015 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1016 "Valore di XmNentryAlignment sconosciuto.\n\
Verrà usato il valore predefinito."
$ MSG_RowColumn_1016 message is obsolete - DO NOT localize this message.

MSG_RowColumn_1017 "Si è cercato di impostare XmNentryAlignment a un valore sconosciuto.\n\
Il valore verrà ignorato."
$ MSG_RowColumn_1017 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0015 "Si è cercato di impostare XmNisHomogenous a FALSE \
per un widget RowColumn widget di tipo XmMENU_BAR.  Operazione ignorata."
$ please do not translate FALSE and RowColumn.

MSG_RowColumn_0016 "Si è cercato di modificare XmNentryClass per un \
widget RowColumn di tipo XmMENU_BAR. Operazione ignorata."
$ please do not translate RowColumn.

MSG_RowColumn_0017 "Si è cercato di modificare XmNwhichButton tramite XtSetValues per un widget RowColumn \
del tipo XmMENU_PULLDOWN. Operazione ignorata."
$ please do not translate RowColumn.

MSG_RowColumn_0018 "Si è cercato di modificare XmNmenuPost mediante XtSetValues\
per un widget RowColumn di tipo XmMENU_PULLDOWN. Operazione ignorata."
$ please do not translate RowColumn.

MSG_RowColumn_0019 "Si è cercato di impostare XmNmenuPost ad un valore non ammesso.\
Operazione ignorata."

MSG_RowColumn_0020 "Si è cercato di modificare XmNshadowThickness per un widget \
RowColumn che non  è di tipo XmMENU_PULLDOWN o di tipo XmMENU_POPUP \
Operazione ignorata."
$ please do not translate RowColumn.

MSG_RowColumn_1024 "Si è cercato di modificare XmNorientation per un widget \n\
RowColumn di tipo XmMENU_OPTION.\n\
Il valore verrà ignorato."
$ MSG_RowColumn_1024 message is obsolete - DO NOT localize this message.

MSG_RowColumn_0022 "Si è cercato di aggiungere un figlio di tipo sbagliato \n\
d un widget menu (RowColumn)"

MSG_RowColumn_0023 "Si è cercato di aggiungere un figlio di tipo sbagliato \n\
ad un widget RowColumn omogeneo"

MSG_RowColumn_0025 "Si è cercato di modificare XmNisHomogeneous per un widget \n\
RowColumn di tipo XmMENU_OPTION. Operazione ignorata."
$ please do not translate RowColumn.

MSG_RowColumn_0026 "L'abilitazione del tear off in un pannello di menu\n\
condiviso non  è raccomandata."

MSG_RowColumn_0027 "Carattere mnemonico non valido. Impossibile convertire \n\
X KEYSYM in un codice di un tasto."
$ please do not translate X KEYSYM.


$set MS_Scale

MSG_Scale_0000 "Il valore minimo della scala è maggiore o \n\
uguale al suo valore massimo."

MSG_Scale_0001 "Il valore di scala specificato è inferiore al \n\
valore minimo consentito."

MSG_Scale_0002 "Il valore di scala specificato è superiore al \n\
valore massimo consentito."

MSG_Scale_1004 "Orientamento non corretto."
$ MSG_Scale_1004 message is obsolete - DO NOT localize this message.

MSG_ScaleScrBar_0004 "Direzione di elaborazione non corretta."

MSG_Scale_0005 "Spessore di evidenziazione non valido."
$ MSG_Scale_0005 message is obsolete - DO NOT localize this message.

MSG_Scale_0006 "XmNscaleMultiple non valido; maggiore del (massimo - minimo)"

MSG_Scale_0007 "XmNscaleMultiple non valido; valore inferiore a zero"

MSG_Scale_0008 "(Massimo - minimo) non può essere maggiore di \n\
INT_MAX diviso per 2. Il valore minimo è stato impostato su zero. \n\
Il valore massimo potrebbe essere stato impostato come (INT_MAX/2)."

MSG_Scale_0009 "XmNshowValue ha un valore non corretto"


$set MS_ScrollBar

MSG_ScrollBar_0000 "Il valore minimo della barra di scorrimento\n\
è maggiore o uguale al suo valore massimo."

MSG_ScrollBar_0001 "Il valore specificato per la guida di scorrimento è minore di 1."

MSG_ScrollBar_0002 "Il valore specificato per la barra di scorrimento\n\
è inferiore al valore minimo."

MSG_ScrollBar_0003 "Il valore specificato per la barra di scorrimento\n\
è superiore al suo valore massimo meno la dimensione della guida di scorrimento."

MSG_ScrollBar_1005 "Orientamento non corretto."
$ MSG_ScrollBar_1005 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_1006 "Direzione di elaborazione non corretta."
$ MSG_ScrollBar_1006 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_0004 "L'incremento della barra di scorrimento è minore di 1."

MSG_ScrollBar_0005 "L'incremento pagina della barra di scorrimento è minore di 1."

MSG_ScrollBar_0006 "Il ritardo iniziale della barra di scorrimento è minore di 1."

MSG_ScrollBar_0007 "Il ritardo di ripetizione della barra di scorrimento è minore di 1."

MSG_ScrollBar_1011 "Errore nella gestione dei contesti; i colori di sfondo della\n\
barra di scorrimento non possono essere impostati correttamente"
$ MSG_ScrollBar_1011 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_1012 "Errore nella gestione dei contesti; i colori di primo piano della\n\
barra di scorrimento non possono essere impostati correttamente"
$ MSG_ScrollBar_1012 message is obsolete - DO NOT localize this message.

MSG_ScrollBar_0008 "La dimensione specificata per la guida di scorrimento è maggiore del\n\
valore massimo della barra di scorrimento meno il suo valore minimo."


$set MS_ScrolledW

MSG_ScrolledW_1001 "ScrollBar Display Policy non valida."
$ MSG_ScrolledW_1001 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1002 "Scrolling Policy non valida."
$ MSG_ScrolledW_1002 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1003 "Visual Policy non valida."
$ MSG_ScrolledW_1003 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_1004 "Placement Policy non valida."
$ MSG_ScrolledW_1004 message is obsolete - DO NOT localize this message.

MSG_ScrolledW_0004 "Impossibile cambiare la Scrolling Policy dopo l'inizializzazione."

MSG_ScrolledW_0005 "Impossibile cambiare la Visual Policy dopo l'inizializzazione."

MSG_ScrolledW_0006 "Impossibile impostare la tecnica per la barra di scorrimento \n\
come AS_NEEDED con una tecnica di visualizzazione VARIABLE."
$ please do not translate AS_NEEDED or VARIABLE.

MSG_ScrolledW_0007 "Impossibile modificare il widget della barra di scorrimento in modo AUTOMATIC."
$ please do not translate AUTOMATIC.

MSG_ScrolledW_0008 "Impossibile cambiare la finestra appunti"

MSG_ScrolledW_0009 "Impossibile impostare la tecnica di visualizzazione CONSTANT in modalità APPLICATION_DEFINED."
$ please do not translate CONSTANT or APPLICATION_DEFINED.

MSG_ScrollVis_0000 "Parametri errati passati alla funzione XmScrollVisible."


$set MS_SelectioB

MSG_SelectioB_1001 "Tipo di dialogo non corretto."
$ MSG_SelectioB_1001 message is obsolete - DO NOT localize this message.

MSG_SelectioB_0001 "Impossibile modificare il tipo di Dialog."
$ please do not translate Dialog.

MSG_SelectioB_1003 "È ammesso un solo figlio per l'area di lavoro."
$ MSG_SelectioB_1003 message is obsolete - DO NOT localize this message.

MSG_SelectioB_0002 "Widget non supporta figli di questo tipo."


$set MS_Separator

MSG_Separator_1001 "Tipo di separatore non valido."
$ MSG_Separator_1001 message is obsolete - DO NOT localize this message.

MSG_Separator_1002 "Orientamento non valido."
$ MSG_Separator_1002 message is obsolete - DO NOT localize this message.


$set MS_Text

MSG_Text_0000 "Il testo di origine non è corretto e verrà ignorato."

MSG_Text_1003 "Modalità di editazione non valida."
$ MSG_Text_1003 message is obsolete - DO NOT localize this message.

MSG_Text_0002 "Text widget is è aggiornabile; XmNtraversalOn deve essere True."
$ please do not translate XmNtraversalOn and True.
$ MSG_Text_0002 message is obsolete - DO NOT localize this message.

MSG_TextIn_0000 "Non è possibile trovare il posizionamento mentre si tenta lo spostamento alla riga precedente."

MSG_TextOut_0000 "Il numero di righe deve essere maggiore di 0."

MSG_TextF_0002 "XmFontListInitFontContext non riuscito."
$ please do not translate XmFontListInitFontContext.

MSG_TextF_0003 "XmFontListGetNextFont non riuscito."
$ please do not translate XmFontListGetNextFont.

MSG_TextF_0004 "Il font non supporta il carattere '%s'.  Il carattere verrà ignorato."

MSG_TextFWcs_0000 "Il font non supporta il carattere '%s'.  Il carattere verrà ignorato."

MSG_TextFWcs_0001 "Cannot use multibyte locale without a fontset.  Value discarded."
$ MSG_TextFWcs_0001 message is obsolete - DO NOT localize this message.

$set MS_TextF

MSG_TextF_0000 "La posizione del cursore deve essere maggiore di o uguale a 0."

MSG_TextF_0001 "Il numero di colonne deve essere maggiore di 0."

MSG_TextF_0005 "XmNtraversalOn must always be True."
$ please do not translate XmNtraversalOn and True.
$ MSG_TextF_0005 message is obsolete - DO NOT localize this message.

MSG_TextF_0006 "Il numero di colonne deve essere maggiore di 0."


$set MS_ToggleB

MSG_ToggleB_1001 "Il tipo di indicatore deve essere XmONE_OF_MANY o XmN_OF_MANY"
$ MSG_ToggleB_1001 message is obsolete - DO NOT localize this message.


$set MS_Traversal

MSG_Traversal_1001 "Valore non ammesso per navigation_type"
$ MSG_Traversal_1001 message is obsolete - DO NOT localize this message.

MSG_Traversal_1002 "Valore errato nel vecchio navigation_type!!"
$ MSG_Traversal_1002 message is obsolete - DO NOT localize this message.

MSG_Traversal_1003 "Situazione di traversal bootstrap con parametri errati"
$ MSG_Traversal_1003 message is obsolete - DO NOT localize this message.

MSG_Traversal_1004 "Si è cercato di passare alla nuova tabulazione usando parametri errati"
$ MSG_Traversal_1004 message is obsolete - DO NOT localize this message.

MSG_Traversal_1005 "startWidget non è incluso nella lista dei figli"
$ MSG_Traversal_1005 message is obsolete - DO NOT localize this message.
$ please do not translate startWidget

MSG_Traversal_1006 "Parametri errati per TraverseToChild"
$ MSG_Traversal_1006 message is obsolete - DO NOT localize this message.
$ please do not translate TraverseToChild.


$set MS_Vendor

MSG_Vendor_0000 Valore non valido per XmNdeleteResponse

MSG_Vendor_1002 "XmNpreeditType non valido; verrà usato il valore predefinito OverTheSpot"
$ MSG_Vendor_1002 message is obsolete - DO NOT localize this message.

MSG_Vendor_0001 "Valore non valido per XmNinputPolicy"

MSG_Vendor_0002 "Impossibile modificare XmNlayoutDirection."

MSG_Vendor_0003 "Errore irreversibile: \n\
Impossibile usare _XmGetDefaultDisplay prima di VendorS.Initialize, restituisce NULL"


$set MS_VendorE

MSG_VendorE_1001 "FetchUnitType: classe di widget errata"
$ MSG_VendorE_1001 message is obsolete - DO NOT localize this message.

MSG_VendorE_0000 "String to no-op conversion needs no extra arguments"
$ MSG_VendorE_0000 message is obsolete - DO NOT localize this message.

MSG_VendorE_0005 "FetchUnitType chiamato senza un widget di riferimento."
$ please do not translate FetchUnitType.
$ MSG_VendorE_0005 message is obsolete - DO NOT localize this message.


$set MS_VirtKeys

MSG_VirtKey_1001 "Non è stato chiamato un processo Initialize per i collegamenti virtuali"
$ MSG_VirtKey_1001 message is obsolete - DO NOT localize this message.


$set MS_Visual

MSG_Visual_0000 "Colore non valido richiesto da _XmAccessColorData."

MSG_Visual_0001 "Impossibile allocare il valore mappa dei colori per lo sfondo predefinto."

MSG_Visual_0002 "Impossibile analizzare la specificazione del colore per lo sfondo predefinito."


$set MS_XmIm

MSG_XmIm_0000 "Impossibile aprire il metodo di input - si usera' XLookupString."

MSG_XmIm_1002 "Impossibile creare l'Input Method Object"
$ MSG_XmIm_1002 message is obsolete - DO NOT localize this message.

MSG_XmIm_1003 "XmIMFocus chiamato con widget NULL."
$ MSG_XmIm_1003 message is obsolete - DO NOT localize this message.

MSG_XmIm_1004 "XmIMMove chiamato senza il fuoco su Input Method."
$ MSG_XmIm_1004 message is obsolete - DO NOT localize this message.


$set MS_Resources

MSG_Resource_0001 "OK"
$ "OK" as in "Go ahead"/"Confirmed to proceed as instructed"/"Fine"

MSG_Resource_0002 "Annullare"
$ ... as in "Never mind"/"abort this operation"/"Stop current request"

MSG_Resource_0003 "Selezione"
$ ... as in "choosing from a list of items"

MSG_Resource_0004 "Applicare"
$ ... as in "To do something with the things selected"

MSG_Resource_0005 "Aiuto"
$ ... as in "Need more guidance on how to deal with this dialog box"

MSG_Resource_0006 "Filtro"
$ ... the noun "Filter", as in "a sifter/a filter/a qualifier to screen out"
$ files with

MSG_Resource_0007 "File"
$ ... as in "a list of the files"

MSG_Resource_0008 "Directory"
$ ... as in "a list of the directories" 

MSG_Resource_0009 "Elementi"
$ ... as in "a list of things to choose from"

MSG_Resource_0010 "Applicare filtro"
$ ... the verb "Filter", as in "To screen out some files"
$ Note this has a slightly different semantics from MSG_Res_1006.
$ In English, it is the same word, but MSG_Res_1006 means "a sifter", and
$ MSG_Res_1010 means "Push this button to filter out some files"
$ MSG_Res_1006 is a label indicating "entry below is qualifier to filter out" 
$ files with

MSG_Resource_0011 "Directory"

MSG_Resource_0012 ">"
$ command-line prompt in the Command widget. 


$set MS_BaseClass

MSG_BaseClass_0000 "Nessun contesto trovato per l'estensione."

MSG_BaseClass_0001 "_XmPopWidgetExtData: nessuna estensione trovata con XFindContext."

MSG_BaseClass_0002 "XmFreeWidgetExtData non è una routine supportata."
$ MSG_BaseClass_0002 message is obsolete - DO NOT localize this message.

MSG_GetSecRes_0000 "getLabelSecResData: memoria insufficiente."
$ please do not translate getLabelSecResData.
$ MSG_GetSecRes_0000 message is obsolete - DO NOT localize this message.


$set MS_Display

MSG_Display_0001 "Vengono creati più XmDisplays per lo stesso schermo a\n\
finestre. Solo il primo XmDisplay creato per un particolare schermo a finestre\n\
può fungere da riferimento per le chiamate a XmGetXmDisplay."
$ please do not translate XmDisplay or XmGetXmDisplay

MSG_Display_0002 "Ricevuto TOP_LEVEL_LEAVE senza alcun DragContext attivo."
$ please do not translate TOP_LEVEL_LEAVE or DragContext

MSG_Display_0003 "La classe XmDisplay deve essere una sottoclasse di XmDisplay."
$ please do not translate XmDisplay


$set MS_DragBS

MSG_DragBS_0000 "La _MOTIF_DRAG_WINDOW è stata distrutta."
$ please do not translate _MOTIF_DRAG_WINDOW

MSG_DragBS_0001 "Le versioni dei protocolli non corrispondono."

MSG_DragBS_0002 "Impossibile accedere allo schermo."

MSG_DragBS_0003 "La tabella degli atomi è vuota."

MSG_DragBS_0004 "La tabella delle destinazioni è vuota."

MSG_DragBS_0005 "La tabella delle destinazioni ha una caratteristica incongruente."

MSG_DragBS_0006 "Indice della tabella delle destinazioni non valido."


$set MS_DragC

MSG_DragC_0001 "GenerateCallback non può accettare XmCR_DROP_SITE_ENTER come causa."
$ please do not translate GenerateCallback or XmCR_DROP_SITE_ENTER

MSG_DragC_0002 "Selezione non valida in DropConvertCallback."
$ please do not translate DropConvertCallback

MSG_DragC_0003 "La selezione per il rilascio è stata persa."

MSG_DragC_0004 "XGrabPointer non riuscito."

MSG_DragC_0005 "ExternalNotifyHandler: la causa del richiamo non è accettabile."
$ please do not translate ExternalNotifyHandler

MSG_DragC_0006 "XmDragStart deve essere chiamato come risultato di un evento del tipo MotionEvent o ButtonPress."
$ please do not translate XmDragStart


$set MS_DragICC

MSG_DragICC_0000 "Tipo di messaggio di trascinamento e rilascio sconosciuto."

MSG_DragICC_0001 "Le versioni dei protocolli non corrispondono."


$set MS_DragIcon

MSG_DragIcon_0000 "Nessuna geometria specificata per la mappa di pixel dragIcon."
$ please do not translate dragIcon

MSG_DragIcon_0001 "dragIcon creata senza alcuna mappa di pixel."
$ please do not translate dragIcon

MSG_DragIcon_0002 "String to Bitmap converter needs Screen argument"
$ MSG_DragIcon_0002 message is obsolete - DO NOT localize this message.


$set MS_DragOverS

MSG_DragOverS_0000 "Le profondità non corrispondono."

MSG_DragOverS_0001 "Allegato con icona sconosciuta."

MSG_DragOverS_0002 "Stato di trascinamento sconosciuto."

MSG_DragOverS_0003 "XmNblendModel sconosciuto."
$ please do not translate XmNblendModel 


$set MS_DragUnder

MSG_DragUnder_0000 "Impossibile ottenere la geometria della finestra dropSite."

MSG_DragUnder_0001 "animationPixmapDepth non valido."
$ please do not translate animationPixmapDepth


$set MS_DropSMgr

MSG_DropSMgr_0001 "Impossibile creare posizioni di rilascio che siano figlie di una posizione di rilascio semplice."

MSG_DropSMgr_0002 "Vengono ricevuti Motion Events senza un contesto di trascinamento attivo."

MSG_DropSMgr_0003 "Vengono ricevute operazioni cambiate senza un contesto di trascinamento attivo."

MSG_DropSMgr_0004 "Viene creata una posizione di rilascio attiva senza alcuna procedura di rilascio."

MSG_DropSMgr_0005 "Impossibile impostare rettangoli o serie di rettangoli per posizioni di rilascio composite."

MSG_DropSMgr_0006 "Si sta registrando un widget come posizione di rilascio fuori sequenza.\n\
Per registrare dei widget discendenti occorre prima registrare i loro antenati."

MSG_DropSMgr_0007 "Impossibile registrare un widget come posizione di rilascio più di una volta."

MSG_DropSMgr_0008 "Il tipo di DropSite può essere impostato solo al momento della creazione."
$ please do not translate DropSite

MSG_DropSMgr_0009 "Impossibile modificare i rettangoli di un Dropsite non semplice."

MSG_DropSMgr_0010 "Impossibile registrare una Shell come posizione di rilascio."

MSG_DropSMgrI_0001 "Impossibile registrare una posizione di rilascio che sia una discendente di una posizione di rilascio semplice."

MSG_DropSMgrI_0002 "Impossibile creare una lista di figli discontinua per una posizione di rilascio composita."

MSG_DropSMgrI_0003 "%s non è una posizione di rilascio figlia di %s."


$set MS_GeoUtils

MSG_GeoUtils_0000 "Failure of geometry request to \"almost\" reply"
$ please do not translate "almost"
$ MSG_GeoUtils_0000 message is obsolete - DO NOT localize this message.

MSG_GeoUtils_0001 "Invalid layout of children found"
$ MSG_GeoUtils_0001 message is obsolete - DO NOT localize this message.

MSG_GeoUtils_0002 "Invalid order found in XmSelectionBox"
$ MSG_GeoUtils_0002 message is obsolete - DO NOT localize this message.


$set MS_Region

MSG_Region_0000 "Errore di memoria."


$set MS_RepType

MSG_RepType_0001 "Id del tipo di rappresentazione non valido."

MSG_RepType_0002 "Valore non ammesso (%d) per il tipo di rappresentazione XmR%s."
$ please do not translate XmR%s

MSG_RepType_0000 "Conversione inversa di "


$set MS_ResConvert

MSG_ResConvert_0000 "FetchUnitType: classe di widget errata."
$ please do not translate FetchUnitType.
$ MSG_ResConvert_0000 message is obsolete - DO NOT localize this message.

MSG_ResConvert_0001 "La lista predefinita non è definita correttamente. Uscita..."

MSG_ResConvert_0002 "Manca il carattere due punti nella stringa di font \"%s\"; i font rimanenti nella lista non verranno analizzati."

MSG_ResConvert_0003 "Delimitatore non valido in \"%s\"; i font rimanenti nella lista non verranno analizzati."

MSG_ResConvert_0004 "Unmatched quotation marks in string \"%s\"; any remaining fonts in list unparsed"
$ MSG_ResConvert_0004 message is obsolete - DO NOT localize this message.

MSG_ResConvert_0005 "Virgoletta senza corrispondente in \"%s\"; i font rimanenti nella lista non verranno analizzati."

MSG_ResConvert_0006 "È stata incontrata una stringa nulla durante la conversione in tipo  %s; i font rimanenti nella lista non verranno  analizzati."

MSG_ResConvert_0007 "Impossibile convertire XmString in testo composto."

MSG_ResConvert_0008 "Memoria insufficiente per XmbTextListToTextProperty"

MSG_ResConvert_0009 "Versione locale non supportata per XmbTextListToTextProperty"

MSG_ResConvert_0010 "XmbTextListToTextProperty non riuscito"

MSG_ResConvert_0011 "Impossibile convertire nome widget in Widget."
$ please do not translate Widget.

MSG_ResConvert_0012 "Impossibile convertire testo composto in XmString"

MSG_ResConvert_0013 "Impossibile convertire XmString in testo composto"

MSG_ResConvert_0014 "FetchUnitType called without a widget to reference"
$ please do not translate FetchUnitType.
$ MSG_ResConvert_0014 message is obsolete - DO NOT localize this message

MSG_ResConvert_0015 "FetchDisplayArg called without a widget to reference"
$ please do not translate FetchDisplayArg.
$ MSG_ResConvert_0015 message is obsolete - DO NOT localize this message

MSG_ResConvert_0016 "FetchWidgetArg called without a widget to reference"
$ please do not translate FetchWidgetArg.
$ MSG_ResConvert_0016 message is obsolete - DO NOT localize this message


$set MS_Screen

MSG_Screen_0000 "Gli schermi delle icone non corrispondono."

MSG_Screen_0001 "Impossibile ottenere XmScreen perché XmDisplay non è stato trovato."


$set MS_ColObj

MSG_ColObj_0001 "Impossibile allocare memoria per i dati dell'oggetto colore."

MSG_ColObj_0002 "La selezione del server dei colori ha restituito un numero di schermo errato."


$set MS_IG

MSG_IG_1 "Allineamento non corretto."
$ MSG_IG_1 message is obsolete - DO NOT localize this message.

MSG_IG_2 "Comportamento non corretto."
$ MSG_IG_2 message is obsolete - DO NOT localize this message.

MSG_IG_3 "Modalità di riempimento non corretta."
$ MSG_IG_3 message is obsolete - DO NOT localize this message.

MSG_IG_4 "Posizione della mappa di pixel o della stringa non corretta."
$ MSG_IG_4 message is obsolete - DO NOT localize this message.

MSG_IG_5 "Larghezza o altezza dei margini non corrette."
$ MSG_IG_5 message is obsolete - DO NOT localize this message.

MSG_IG_6 "Tipo di ombreggiatura non corretto."
$ MSG_IG_6 message is obsolete - DO NOT localize this message.


$set MS_ComboBox

MSG_ComboBox_0000 "Applicazioni non possono aggiungere figli ai widget XmComboBox."

MSG_ComboBox_0001 "Non è possibile utilizzare XtSetValues per modificare la risorsa XmNcomboBoxType."

MSG_ComboBox_0002 "XmFontListGetNextFont failed."
$ MSG_ComboBox_0002 message is obsolete - DO NOT localize this message.

MSG_ComboBox_0003 "XmFontListInitFontContext failed."
$ MSG_ComboBox_0003 message is obsolete - DO NOT localize this message.

MSG_ComboBox_0004 "Un widget interno è stato distrutto. Comportamento non definito."

MSG_ComboBox_0005 "Un widget interno non è gestito. Comportamento non definito."

MSG_ComboBox_0006 "XmQUICK_NAVIGATE  è valido solo per ComboBoxes di tipo XmNcomboBoxType XmDROP_DOWN_LIST"

MSG_ComboBox_0007 "Azione richiamata con un numero errato di parametri."

MSG_ComboBox_0008 "Routine di azione è stata richiamata da un widget che non deriva da ComboBox"

MSG_ComboBox_0009 "XmComboBoxSelectItem richiamato con un elemento che non è presente nel ComboBox."

MSG_ComboBox_0010 "XmComboBoxSetItem chiamato con un elemento che non è presente nel ComboBox."

MSG_ComboBox_0011 "XmComboBoxDeletePos chiamato con una posizione non ammessa."

MSG_ComboBox_0012 "Routine XmComboBox chiamata con un widget non valido."

MSG_ComboBox_0013 "Applicazioni non possono impostare i figli widget del XmComboBox automatico."

MSG_ComboBox_0014 "Non  è possibile modificare positionMode di XmComboBox dopo la creazione."
$ please do not translate positionMode.


$set MS_Container

MSG_Container_0000 "Azione richiamata con un numero errato di parametri."

MSG_Container_0001 "XmNdetailColumnHeading e XmNdetailColumnHeadingCount non corrispondono!"


$set MS_CSText

MSG_CSText_0000 "Invalid margin height; must be greater than or equal to 0."
$ MSG_CSText_0000 message is obsolete - DO NOT localize this message.

MSG_CSText_0001 "Invalid margin width; must be greater than or equal to 0."
$ MSG_CSText_0001 message is obsolete - DO NOT localize this message.

MSG_CSText_0002 "Invalid edit mode."
$ MSG_CSText_0002 message is obsolete - DO NOT localize this message.

MSG_CSText_0003 "XmNtraversalOn must always be true."
$ MSG_CSText_0003 message is obsolete - DO NOT localize this message.

MSG_CSText_0004 "Cannot change XmNscrollHorizontal after initialization."
$ MSG_CSText_0004 message is obsolete - DO NOT localize this message.

MSG_CSText_0005 "Cannot change XmNscrollVertical after initialization."
$ MSG_CSText_0005 message is obsolete - DO NOT localize this message.

MSG_CSText_0006 "Cannot change XmNscrollTopSide after initialization."
$ MSG_CSText_0006 message is obsolete - DO NOT localize this message.

MSG_CSText_0007 "Cannot change XmNscrollLeftSide after initialization."
$ MSG_CSText_0007 message is obsolete - DO NOT localize this message.


$set MS_GrabShell

MSG_GrabS_0000 "XmPopup requires a subclass of shellWidgetClass."
$ please do not translate shellWidgetClass.
$ MSG_GrabS_0000 message is obsolete - DO NOT localize this message.


$set MS_Manager

MSG_Manager_0000 "La classe widget %s ha un record CompositeClassExtension non valido."
$ please do not translate CompositeClassExtension.

MSG_Manager_0001 "Impossibile modificare XmNlayoutDirection o XmNstringDirection dopo l'inizializzazione."


$set MS_NavigMap

MSG_NavigMap_0000 "_XmNavigate called with invalid direction"
$ MSG_NavigMap_0000 message is obsolete - DO NOT localize this message.


$set MS_Notebook

MSG_Notebook_0000 "Non è possibile utilizzare XtSetValues per modificare la risorsa XmNnotebookChildType."


$set MS_PixConv

MSG_PixConv_0000 "Numero errato di parametri per CvtStringToPixmap"
$ please do not translate CvtStringToPixmap.


$set MS_Primitive

MSG_Primitive_0000 "Impossibile modificare XmNlayoutDirection dopo l'inizializzazione."


$set MS_ScrollFrameT

MSG_ScrollFrameT_0000 "AssocNavigator richiede un navigator trait"
$ please do not translate AssocNavigator.

MSG_ScrollFrameT_0001 "DeAssocNavigator richiede un navigator trait"
$ please do not translate DeAssocNavigator.


$set MS_SpinB

MSG_SpinB_0001 "Valore non valido per XmNarrowLayout."
$ MSG_SpinB_0001 message is obsolete - DO NOT localize this message.

MSG_SpinB_0002 "XmNminimumValue equals XmNmaximumValue."
$ MSG_SpinB_0002 message is obsolete - DO NOT localize this message.

MSG_SpinB_0003 "Nessun elemento fornito per il figlio XmSTRING."

MSG_SpinB_0004 "XmNincrementValue non  può essere 0. Il valore 1 verrà usato."

MSG_SpinB_0005 "La direzione specificata dal valore XmNincrementValue\n\
 è stata modificata per corrispondere ai valori \n\
XmNminimumValue e XmNmaximumValue specificati."

MSG_SpinB_0006 "XmNposition è fuori dall'intervallo consentito; \n\
verrà usato il valore minimo XmNposition."

MSG_SpinB_0007 "XmNposition è fuori dall'intervallo consentito; \n\
verrà usato il valore massimo XmNposition."

MSG_SpinB_0008 "Valore non valido per XmNpositionType.  Verrà usato il valore predefinito."

MSG_SpinB_0009 "XmNpositionType resource can only be set at creation time."
$ MSG_SpinB_0009 message is obsolete - DO NOT localize this message.


$set MS_Transfer

MSG_Transfer_0000 "Richiamo di SelectionCallbackWrapper al termine del trasferimento."
$ please do not translate SelectionCallbackWrapper.

MSG_Transfer_0001 "Impossibile bloccare ilclipboard; aborting transfer"
$ MSG_Transfer_0001 message is obsolete - DO NOT localize this message.

MSG_Transfer_0002 "Il formato e il tipo dei dati forniti dalla chiamata automatica non corrispondono a quelli dei dati da unire."

MSG_Transfer_0003 "Lo stato in XmConvertCallbackStruct non è XmCONVERT_MERGE."

MSG_Transfer_0004 "CONVERT_MORE non è ancora supportato."
$ please do not translate CONVERT_MORE.

MSG_Transfer_0005 "Valore atomo non ammesso."

MSG_Transfer_0006 "Avviso: Si è cercato di iniziare un trasferimento MULTIPLE mentre uno è già  in corso."
$ please do not translate MULTIPLE.

MSG_Transfer_0007 "Avviso: Si è cercato di inviare un trasferimento MULTIPLE quando c'è ne uno già  in corso."
$ please do not translate MULTIPLE.


$set MS_VaSimple

MSG_VaSimple_0000 "La conversione XtVaTypedArg richiede uno handle di widget che non sia nullo."

MSG_VaSimple_0001 "Impossibile trovare il tipo di risorsa per la conversione."

MSG_VaSimple_0002 "Conversione del tipo non riuscito."


$set MS_Xm

MSG_Motif_0000 "\nNome: %s\nClasse: %s\n"

MSG_Motif_0001 "Azione richiamata con un numero errato di parametri."


$set MS_XmRenderT

MSG_XmRenderT_0000 "XmNtag non può essere NULL.  Si imposterà una stringa vuota."

MSG_XmRenderT_0001 "Display è NULL.  Impossibile caricare il font."

MSG_XmRenderT_0002 "XmNfontType non valido.  Impossibile caricare il font."

MSG_XmRenderT_0003 "Conversione fallita.  Impossibile caricare il font."

MSG_XmRenderT_0004 "XmNfontType impostato a XmAS_IS.  Impossibile caricare il font."

MSG_XmRenderT_0005 "XmNloadModel è XmLOAD_IMMEDIATE ma XmNfont e XmNfontName non sono specificati.\n\
Impossibile caricare il font."


$set MS_XmSelect

MSG_XmSelect_0000 "Internal error: no selection property context for display"
$ MSG_XmSelect_0000 message is obsolete - DO NOT localize this message.

MSG_XmSelect_0001 "Selection owner returned type INCR property with format != 32"
$ please do not translate INCR.
$ MSG_XmSelect_0001 message is obsolete - DO NOT localize this message.

MSG_XmSelect_0002 "XtGetSelectionRequest chiamato per il widget \"%s\" fuori del processo ConvertSelection"
$ please do not translate ConvertSelection.
$ MSG_XmSelect_0002 message is obsolete - DO NOT localize this message.


$set MS_XmString

MSG_XmString_0000 "Nessun font trovato."


$set MS_XmTabList

MSG_XmTabList_0000 "Il valore Tab non può essere negativo."


$set MS_SSpinB

MSG_SSpinB_0001 "Impossibile impostare la risorsa XmNtextField."

MSG_SSpinB_0002 "XmNpositionType può essere impostata solo al tempo di creazione."

MSG_SSpinB_0003 "L'elemento non esiste. XmNposition non è stato modificato."
