#! /bin/ksh

echo
find . -name MAM.time -print -exec rm -f {} \;
echo
echo "******************"
echo
find . -name in.log -print -exec rm -f {} \;
echo
echo "******************"
echo
find . -name \*.a -print -exec rm -f {} \;
echo
echo "******************"
echo
find . -name \*.o -print -exec rm -f {} \;
echo
echo "******************"
echo
find . -name BUILT -print -exec rm -f {} \;
echo
echo "******************"
echo
find . -name ERROR -print -exec rm -f {} \;
echo
echo "******************"
echo
echo "rm ksh93/bin/*"
rm -f ksh93/bin/feature
rm -f ksh93/bin/iffe
rm -f ksh93/bin/ignore
rm -f ksh93/bin/pax
rm -f ksh93/bin/bax
rm -f ksh93/bin/pax.save
rm -f ksh93/bin/proto
rm -f ksh93/bin/silent
rm -f ksh93/bin/suid_exec
rm -f ksh93/bin/shcomp
rm -f ksh93/bin/nocom
rm -f ksh93/bin/*.old
echo
echo "rm ksh93/src/cmd/ksh93/suid_exec"
rm -f ksh93/src/cmd/ksh93/suid_exec
echo "rm ksh93/src/cmd/ksh93/shcomp"
rm -f ksh93/src/cmd/ksh93/shcomp
echo "rm ksh93/src/cmd/ksh93/ksh.msg"
rm -f ksh93/src/cmd/ksh93/ksh.msg
echo "rm ksh93/src/cmd/pax/pax"
rm -f ksh93/src/cmd/pax/pax
echo "rm ksh93/src/cmd/pax/bax"
rm -f ksh93/src/cmd/pax/bax
echo "rm ksh93/src/cmd/pax/nocom"
rm -f ksh93/src/cmd/pax/nocom
echo "rm ksh93/src/cmd/pax/cpio"
rm -f ksh93/src/cmd/pax/cpio
echo "rm ksh93/src/cmd/pax/tar"
rm -f ksh93/src/cmd/pax/tar
#echo "rm ksh93/src/lib/libcmd/cmd.h"
#rm -f ksh93/src/lib/libcmd/cmd.h
echo "rm ksh93/src/lib/libcmd/cmd.req"
rm -f ksh93/src/lib/libcmd/cmd.req
echo "rm ksh93/src/cmd/ksh"
rm -f ksh93/src/cmd/ksh
echo "rm ksh93/bin/ksh"
rm -f ksh93/bin/ksh
echo "rm ksh93/ship/shipslog/!t_gryphon_dgk"
rm -f ksh93/ship/shipslog/!t_gryphon_dgk
echo "rm ksh93/ship/shipslog/!t_gryphon_gsf"
rm -f ksh93/ship/shipslog/!t_gryphon_gsf

echo "rm ksh93/src/cmd/ksh93/FEATURE/*"
rm -f ksh93/src/cmd/ksh93/FEATURE/*
echo "cp /dev/null ksh93/src/cmd/ksh93/FEATURE/options"
cp /dev/null ksh93/src/cmd/ksh93/FEATURE/options
echo "cp /dev/null ksh93/src/cmd/ksh93/FEATURE/setjmp"
cp /dev/null ksh93/src/cmd/ksh93/FEATURE/setjmp
echo "cp /dev/null ksh93/src/cmd/ksh93/FEATURE/sigfeatures"
cp /dev/null ksh93/src/cmd/ksh93/FEATURE/sigfeatures
echo "cp /dev/null ksh93/src/cmd/ksh93/FEATURE/dynamic"
cp /dev/null ksh93/src/cmd/ksh93/FEATURE/dynamic

echo "rm ksh93/src/cmd/pax/FEATURE/*"
rm -f ksh93/src/cmd/pax/FEATURE/*

echo "rm ksh93/src/lib/libast/FEATURE/*"
rm -f ksh93/src/lib/libast/FEATURE/*

echo "rm ksh93/src/lib/libcmd/FEATURE/*"
rm -f ksh93/src/lib/libcmd/FEATURE/*

echo "rm ksh93/src/lib/libast/*.h"
rm -f ksh93/src/lib/libast/*.h

echo "rm ksh93/src/lib/libast/conf"
rm -f ksh93/src/lib/libast/conf

echo "rm ksh93/src/lib/lib0ast/hostinfo"
rm -f ksh93/src/lib/lib0ast/hostinfo

echo "rm ksh93/src/cmd/ksh93/ksh"
rm -f ksh93/src/cmd/ksh93/ksh

echo "rm ksh93/ship/SHIP*"
rm -f ksh93/ship/SHIP*

echo "rm ksh93/ship/shipfeature"
rm -f ksh93/ship/shipfeature

echo "rm ksh93/ship/shipproto"
rm -f ksh93/ship/shipproto
